packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountCard/TransferFormAccountCard.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountSelection/TransferFormAccountSelection.scss
=> [WALL] Lubega / WALL-3351/3353 / Transfer form account card icon styling

packages/core/src/App/Components/Elements/NotificationMessage/notification.jsx, packages/core/src/Stores/notification-store.js
This PR fixes the issue of permanently closing the `Proof of identity required` & `Account verification required` notifications after clicking the redirect button. This is done by adding a onClick function which internally marks the respective notifications. Marking the notifications helps us identify which notifications should not be displayed.
=> [UPM]Utkarsha/Notifications for 'Proof of identity required' & 'Account verification required' appear even after being clicked on

packages/core/src/public/.well-known/apple-app-site-association
Redirection to cashier withdrawal issue to p2p.
=> fix: redirection issue in ios for cashier withdrawal

package-lock.json, packages/account-v2/package.json, packages/cashier-v2/package.json, packages/library/package.json, packages/p2p-v2/package.json, packages/tradershub/package.json
Update the `deriv/quill-icons` package version from 1.17.25 to 1.17.27 in all the V2 packages.
=> [cashier-v2] george / bump version of deriv/quill-iconsi from 1.17.25 to 1.18.3

.github/workflows/release_test.yml
This is to pass the default github token from workflow to the action.
=> ci: pass the default github token from workflow

.github/workflows/release_test.yml
This is to fix the wrongly provided env to vars.
=> ci: use vars instead of env

packages/cashier/src/components/crypto-fiat-converter/crypto-fiat-converter.tsx
Addressing the issue raised in this thread https://deriv-group.slack.com/archives/CEP7GPTP0/p1707966455543589
=> [WALL] Lubega / WALL-2879 / Crypto transfer wrong exchange rate conversion 

packages/appstore/src/components/cfds-listing/cfds-listing.scss
When hover on the "Forgot password?" hyperlink in MT5 Trade Modal, the underline goes away. It should stay and only the cursor should change to a hand symbol.
=> Hirad/CFDs-3152: fixed the hover effect of forgot password part

packages/api/src/hooks/useRemoteConfig.ts
In case the app is running on local we dont need to have access to remote config url and therefore the error is not needed. so i just removed that error from the local development server.
=> Ako/ prevent remote config url error on local development

packages/api/src/hooks/useSettings.ts
- Enables the useSettings hook only on successful authorization
=> [COJ] Shaheer / Hooks / Fixes useSettings hook

packages/p2p/src/pages/my-ads/order-time-selection/order-time-selection.tsx
Issue with translation not working on hovering info icon on create ad page.
=> fix: info icon message not getting translated

packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
This is to remove the livechat placeholder on mobile if its remote config is disabled.
=> Ako/ remove the livechat placeholder when its disabled

packages/bot-web-ui/src/pages/bot-builder/quick-strategy/config.ts
The content of the tooltips for each strategy and their fields were updated
=> [BOT] Farabi/bot-1289/correct tooltips for each strategy

packages/wallets/src/components/DesktopWalletsList/DesktopWalletsList.tsx, packages/wallets/src/components/WalletsCard/WalletsCard.tsx
https://github.com/binary-com/deriv-app/assets/142860499/e8e76b3f-8399-4061-8595-da0c4eec394d
=> [WALL] Lubega / WALL-3466 / Wallet account switcher active focus fix

packages/cfd/src/Helpers/constants.ts
- corrected capitalisation macOS --> MacOS
- Due to the changes of this card  , the capitalisation in MT5 modal has changed
=> [WEBREL] shontzu/WEBREL-2544/Incorrect-Capitalisation-macOS

.github/actions/invalidate_npm_cache/action.yml, .github/actions/npm_install_from_cache/action.yml
as the internal nod_modules are just symlinks to the root level node_modules, I removed them from the cache mechanism of gh actions.
=> ci: remove the cache for internal packages

packages/wallets/src/components/DatePicker/__tests__/DatePicker.spec.tsx
=> [WALL] Lubega / WEBREL-2549 / fix failing tests on staging and master

packages/trader/src/Stores/Modules/Trading/trade-store.ts
This is an additional fix for https://github.com/binary-com/deriv-app/pull/13179 to avoid showing UrlUnavailableModal when a user logs in while the asset, which was selected before login, stops being available.
=> [DTRA] Maryia/fix: avoid showing UrlUnavailableModal when logging into account where selected asset is unavailable

packages/shared/src/utils/contract/__tests__/trade-url-params-config.spec.ts, packages/shared/src/utils/contract/trade-url-params-config.ts
- to hotfix redirecting user back from DTrader to other pages by using history.replaceState to not affect routing history.
=> [DTRA] Maryia/WEBREL-2551/hotfix: restore logic of redirecting back to other pages by using history.replaceState for DTrader URL

packages/core/src/Stores/client-store.js
- Ignore new trade query params from redirect_url in order to keep redirection to Trader's hub upon logging in.
=> [DTRA] Maryia/WEBREL-2553/hotfix: restore redirection to Trader's hub upon logging in

packages/wallets/src/components/Base/ModalWrapper/ModalWrapper.scss, packages/wallets/src/features/cfd/modals/VerificationFailedModal/VerificationFailedModal.tsx, packages/wallets/src/features/cfd/screens/VerificationFailed/VerificationFailed.scss, packages/wallets/src/features/cfd/screens/VerificationFailed/VerificationFailed.tsx
=> [WALL] Lubega / WALL-3511 / Verification failed modal design fixes

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
- update @deriv/deriv-charts version to 2.1.4
=> Maryia/DTRA-952/build: update @deriv/deriv-charts version to 2.1.4

.github/CODEOWNERS
Lock old API to prevent them from being updated / used.
Next step in next PR: add linting to prevent cross-package imports spaghetti (basically to avoid e.g. use of api-v2 within legacy code and other imports which shouldn't happen but used to cause problems before)
=> [WALL-3531] wojtek/lock old api

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
- to update @deriv/deriv-charts version to patched `2.1.5`, which reverts changes in the asset dropdown on the chart https://github.com/binary-com/SmartCharts/pull/1529.
=> [DTRA] Maryia/WEBREL-2569/hotfix: update charts version to patched 2.1.5

packages/bot-skeleton/src/constants/config.js, packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_multiplier.js, packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_tradeoptions.js, packages/bot-web-ui/src/stores/toolbar-store.ts
fix issue 1): block overlap by pressing "reset" strategy button, on refreshing the default strategy page(as an example)
fix issue 2): by pressing  "sort blocks" option button blocks are made pinned on the top of the Blockly workspace
=> [BOT][Spike /Experemental]Maryia/fix: block overlap on "reset" strategy, on "sort blocks" option

packages/tradershub/src/components/EUDisclaimerMessage/EUDisclaimerMessage.tsx
EU disclaimer is not positioned properly in the Trader's Hub page and has styles issue
Before the fix:
After the fix: 
Desktop: 
Responsive:
=> [TRAH] Mitra/TRAH-3025/Broken style of eu disclaimer in footer

packages/bot-web-ui/src/stores/__tests__/chart-store.spec.tsx, packages/bot-web-ui/src/stores/__tests__/toolbar-store.spec.tsx, packages/bot-web-ui/src/stores/__tests__/toolbar-strore.spec.tsx, packages/bot-web-ui/src/stores/chart-store.ts, packages/bot-web-ui/src/stores/toolbar-store.ts, packages/bot-web-ui/src/utils/mock/mock-local-storage.ts, packages/bot-web-ui/src/utils/mock/ws-mock.js
- Added test case for toolbar store
- Added test case for chart store
=> [BOT] Farabi/bot-1034/test coverage chart store and toolbar store 

packages/wallets/src/components/WalletCard/WalletCard.scss, packages/wallets/src/components/WalletCard/WalletCard.tsx, packages/wallets/src/components/WalletCard/__tests__/WalletCard.spec.tsx, packages/wallets/src/components/WalletListCardActions/WalletListCardActions.tsx, packages/wallets/src/components/WalletsCarousel/WalletsCarousel.tsx, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx, packages/wallets/src/components/WalletsCarouselHeader/WalletsCarouselHeader.scss, packages/wallets/src/components/WalletsCarouselHeader/WalletsCarouselHeader.tsx
https://github.com/binary-com/deriv-app/assets/142860499/90d870ca-0fdb-4a35-90c4-c8a68b52ae25
=> [WALL] Lubega / WALL-3595 / Wallet carousel responsive UI update and button reorder

packages/wallets/src/features/cashier/modules/WithdrawalCrypto/WithdrawalCrypto.tsx, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/__tests__/WithdrawalCrypto.spec.tsx, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoForm/WithdrawalCryptoForm.tsx, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoForm/__tests__/WithdrawalCryptoForm.spec.tsx
=> [WALL] Lubega / WALL-2998 / WithdrawalCrypto and WithdrawalCryptoForm unit tests

packages/wallets/src/components/WalletsAddMoreCard/WalletsAddMoreCard.tsx, packages/wallets/src/components/WalletsAddMoreCardBanner/WalletsAddMoreCardBanner.scss, packages/wallets/src/components/WalletsAddMoreCardBanner/WalletsAddMoreCardBanner.tsx, packages/wallets/src/components/WalletsAddMoreCarousel/WalletsAddMoreCarousel.tsx, packages/wallets/src/types.ts
- Remove landing company logo from Wallet Card in Carousel.
- Fix types errors.
- Remove stylings.
=> Aizad/WALL-2067/Remove Landing Company Logo from Wallet Carousel Card

packages/wallets/src/features/cashier/modules/WithdrawalLocked/WithdrawalLockedContent.tsx, packages/wallets/src/features/cashier/modules/WithdrawalLocked/__tests__/WithdrawalLockedContent.spec.tsx
1. Withdrawal limit reached
2. POI not uploaded and verified
3. POA not uploaded and verified
=> [WALL] Lubega / WALL-3539 / Withdrawal locked part 2

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.10
=> Update deriv-charts to 2.1.10

packages/core/src/Services/socket-general.js, packages/core/src/Stores/client-store.js
MX accounts were getting logged out on refreshing . The issue was due to FE logic to check valid LoginId. If the loginId is doesn't match regex, we used to call logout immediately. 
This PR removes this check from FE side since we do not need this logic in FE. By right, all authorized login from BE should be valid
=> [COJ]/Amina/COJ_643/Fixing MX account getting logged out on refreshing

package-lock.json, packages/account-v2/package.json, packages/account/package.json, packages/api-v2/package.json, packages/api/package.json, packages/appstore/package.json, packages/bot-web-ui/package.json, packages/cashier/package.json, packages/cfd/package.json, packages/hooks/src/__tests__/useResidenceSelfDeclaration.spec.tsx, packages/p2p/package.json, packages/shared/package.json, packages/stores/package.json, packages/stores/types.ts, packages/trader/package.json, packages/utils/package.json
Updated version for deriv/api-types from 1.0.118 to 1.0.172, to include p2p_country_list endpoint. also replaced the TResidenceList with ResidenceList from api-types.
=> version update for api-types

.github/workflows/generate_app_id.yml, .github/workflows/lighthouse.yml, .github/workflows/smoketests.yml
Reverts binary-com/deriv-app#14233
This is to revert bumping vercel preview url version as it is not working on production.
=> Revert "Matin/ Update Vercel Preview URL"

packages/bot-skeleton/src/scratch/utils/index.js, packages/bot-web-ui/src/stores/toolbox-store.js
On RTL the Blockly Workspace scroll was not working properly and the blocks were getting hidden under the flyout on the right side.
- Updated the calculation for horizontal scroll on RTL mode
- Updated the calculation for vertical scroll on RTL mode so that it doesn't keep decreasing the Y value on each render
=> [BOT] Shafin/bot 1586/fix RTL workspace issue

packages/core/src/App/Containers/AccountSwitcherWallet/__tests__/account-switcher-wallet-mobile.spec.tsx, packages/core/src/App/Containers/AccountSwitcherWallet/__tests__/account-switcher-wallet.spec.tsx, packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.scss, packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx, packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet.scss, packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet.tsx
https://github.com/binary-com/deriv-app/assets/142860499/e4ead38f-fff9-446f-b8e1-12f115004bbe
=> [WALL] Lubega / WALL-3630 / Header account switcher wallet redirection

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.11
=> Update deriv-charts to 2.1.11

packages/wallets/src/utils/password-validation.ts
- Update missing MT5 password validation: `Password should have lower and uppercase English letters with numbers.`
=> Aizad/WALL-3701/ Update missing MT5 Password Validation 

packages/core/src/Stores/client-store.js
To show the add or manage modal, we have a check to see if the currency is fiat or crypto which we rely on `legal_allowed_currency` and `website_status => currencies_config` ( the type of the currency is shown here but all other currencies are here also ), as GBP is removed from `legal_allowed_currency` our condition is failing for existing client, this means the changes are not backward compatible, 
We needed the BE here to help us with this, they added the type of currency in the `account_list` itself so we don't check it in currencies_config in website_status which is another endpoint. 
before the changes
After changes
=> [TRAH]/Mitra/ TRAH-3032/ Using currency type from account list for removing GBP for eu client

packages/account/src/Containers/Account/account.tsx, packages/account/src/Sections/Security/Passkeys/__tests__/passkeys.spec.tsx, packages/account/src/Sections/Security/Passkeys/passkeys-configs.tsx, packages/account/src/Sections/Security/Passkeys/passkeys.tsx, packages/account/src/Types/common.type.ts, packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx, packages/hooks/src/useGetPasskeysList.ts, packages/shared/src/utils/object/__tests__/object.spec.ts, packages/shared/src/utils/object/object.ts, packages/shared/src/utils/route/route.tsx
1) Removed filtering the routes, which caused double rerendering. Add just hiding the menu if passkeys are not supported
2) Fixed error fetching for passkeys_list (not showing the PasskeysOff error)
=> fix: [WEBREL-2641]/evgeniy/account settings flickering, not showing the error in passkeys page

.github/workflows/release_test.yml
- to restore envs except for Datadog:
- DATADOG_APPLICATION_ID: ${{ vars.DATADOG_APPLICATION_ID }}
- DATADOG_CLIENT_TOKEN: ${{ vars.DATADOG_CLIENT_TOKEN }}
- DATADOG_CLIENT_TOKEN_LOGS: ${{ vars.DATADOG_CLIENT_TOKEN_LOGS }}
- DATADOG_SESSION_REPLAY_SAMPLE_RATE: ${{ vars.DATADOG_SESSION_REPLAY_SAMPLE_RATE }}
- DATADOG_SESSION_SAMPLE_RATE: ${{ vars.DATADOG_SESSION_SAMPLE_RATE }}
- DATADOG_SESSION_SAMPLE_RATE_LOGS: ${{ vars.DATADOG_SESSION_SAMPLE_RATE_LOGS }}
=> Maryia/build: restore envs except for Datadog

.github/workflows/release_test.yml
- to restore all envs besides `CROWDIN_WALLETS_API_KEY: ${{ secrets.CROWDIN_WALLETS_API_KEY }}`
=> Maryia/build: restore envs besides CROWDIN_WALLETS_API_KEY

.github/workflows/release_test.yml
- to restore envs except for `NODE_ENV: staging`
=> Maryia/build: restore envs except for node_env

.github/workflows/release_staging.yml, .github/workflows/release_test.yml
- to use `NODE_ENV: production` for test and staging env
=> Maryia/build: use NODE_ENV production for test and staging env

.github/workflows/generate_app_id.yml
- Updated `.github/workflows/generate_app_id.yml` action to point to the action `tag` at `https://github.com/deriv-com/deriv-app-id-action/tree/v1/` instead of `binary-com`
=> ci: update appid reference

packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx
=> [WALL] [Fix] Rostislav / WALL-3744 / cTrader acc number design mismatch

packages/wallets/src/components/WalletListCardActions/WalletListCardActions.tsx
- Added `bold` font weight to "Deposit" button only in Mobile.
=> [WALL] Aizad/WALL-3769/Deposit Button text to be Bold 

packages/wallets/src/components/Base/WalletText/WalletText.tsx, packages/wallets/src/components/TradingAccountCard/TradingAccountCard.scss, packages/wallets/src/features/cfd/components/CFDPlatformsListAccounts/CFDPlatformsListAccounts.scss, packages/wallets/src/features/cfd/components/CFDPlatformsListAccounts/CFDPlatformsListAccounts.tsx, packages/wallets/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.scss, packages/wallets/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.scss, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.tsx
https://github.com/binary-com/deriv-app/assets/142860499/45f22c9a-1798-4e63-9c9e-7f9b246a9e5d
https://github.com/binary-com/deriv-app/assets/142860499/5b4c0d7b-deed-45f1-87c8-d9f7a39e4367
=> [WALL] Lubega / WALL-3745 / CFD chevron design fixes

.github/workflows/release_production.yml
Use `ubuntu-latest` as the job runner for the slack notification send job.
=> fix: use ubuntu-latest as the runner

packages/bot-web-ui/src/components/notify-item/__tests__/notify-item.spec.tsx
test: arrayAsMessage of notify-item file
=> [BOt]Maryia/BOT-1417/test: arrayAsMessage of notify-item file

packages/wallets/src/components/WalletsResetMT5Password/WalletSuccessResetMT5Password.tsx, packages/wallets/src/components/WalletsResetMT5Password/WalletsResetMT5Password.tsx
- Update password validation for MT5 Reset modal.
- Fix disable button for both MT5 and DerivX reset modal.
- Updated Modal Title for MT5 Investor password reset.
- Updated content for Success Modal both for investor and non-investor clients.
=> [WALL] Aizad/WALL-3762/ Update Reset MT5 Password Fix based on new MT5 Policy changes

packages/trader/src/Modules/Contract/Components/Digits/digits.tsx, packages/trader/src/Modules/Contract/Components/LastDigitPrediction/__tests__/last-digit-prediction.spec.tsx, packages/trader/src/Modules/Contract/Components/LastDigitPrediction/last-digit-prediction.tsx
Changed last digit prediction for all contracts. Now it's based on `quote`, previously - on `ask_price` (both are coming inside of `tick` response). `quote` has already been used in SmartTrader and SmartCharts.
=> [DTRA-1018] / Kate / Fix last digit prediction

packages/cashier-v2/src/lib/WithdrawalVerification/WithdrawalVerificationRequest/WithdrawalVerificationRequest.tsx, packages/cashier-v2/src/lib/WithdrawalVerification/WithdrawalVerificationRequest/__tests__/WithdrawalVerificationRequest.spec.tsx, packages/cashier-v2/src/lib/WithdrawalVerification/__tests_/WithdrawalVerification.spec.tsx, packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationRequest/WithdrawalVerificationRequest.tsx, packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationRequest/__tests__/WithdrawalVerificationRequest.spec.tsx, packages/wallets/src/features/cashier/modules/WithdrawalVerification/__tests_/WithdrawalVerification.spec.tsx
Update the content for WithdrawalEmailVerification request page for both `Wallets` and `Cashier-v2`.
Old Content
New Content
=> [WALL] [cashier-v2] Aum / WALL-3363 / content-change-withdrawal-email-verification

packages/wallets/src/components/WalletsResetMT5Password/WalletsResetMT5Password.tsx
- Added error handling for  ResetInvestorPasswordModal and for ResetMT5PasswordModal
=> [WALL] Aizad/WALL-3802/Error Message doesn't appear when Failed Reset MT5 Password Modal

packages/core/src/public/.well-known/apple-app-site-association, packages/core/src/public/.well-known/assetslinks.json
Updated the following files to remove the passkeys configuration related to P2P since it's not yet implemented in the mobile app:
core/src/public/.well-known/assetslinks.json
core/src/public/.well-known/apple-app-site-association
=> [P2PS] farrah/P2PS-2733/fix: p2p app redirection

packages/core/src/sass/app/_common/layout/header.scss
- Added only in desktop rule for `align-items: center`
=> chore: small fix for navbar icons

packages/core/src/sass/app/_common/layout/header.scss
- Added only in desktop rule for `align-items: center`
=> Aizad/WEBREL-2689/Minor Fix Navbar Icons

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.12
=> Update deriv-charts to 2.1.12

packages/wallets/src/components/WalletsCarousel/WalletsCarousel.tsx, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx, packages/wallets/src/components/WalletsCarouselHeader/WalletsCarouselHeader.scss, packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.scss, packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.tsx
https://github.com/binary-com/deriv-app/assets/142860499/27d25cf4-41ad-41eb-b94e-ea5498be667c
=> [WALL] Lubega / WALL-3639 / Mobile carousel swiping improvements

packages/account/src/Containers/Account/__tests__/account.spec.tsx, packages/account/src/Containers/Account/account.tsx, packages/account/src/Sections/Profile/LanguageSettings/__tests__/language-settings.spec.tsx, packages/account/src/Sections/Profile/LanguageSettings/language-settings.tsx, packages/core/src/App/AppContent.tsx, packages/core/src/App/Components/Layout/Header/Components/ToggleMenu/menu-title.tsx, packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx, packages/core/src/App/Containers/Layout/default-footer.jsx, packages/core/src/App/Containers/Layout/trading-hub-footer.jsx
Hide dark theme and language switcher for client with wallet account:
- in footer
- in mobile menu drawer
Switch theme to light mode if the user is going to `wallets` route with already selected dark mode 
https://github.com/binary-com/deriv-app/assets/103181646/9f1bc285-5d8f-4ed6-8b5c-7f911256f9b3
=> [WALL] george / WALL-3652 / Hide dark theme and language switcher for client with wallet account

packages/p2p/src/pages/my-ads/create-ad-form.jsx
- removed reaction to display modal in create-ad-form because it was already being handled in the store when user clicks the create ad button. The reaction caused it to create two modals instead of one
=> [WEBREL] / Ameerul / WEBREL-2701 Update ad button needs to be clicked twice to dismiss duplicate ad pop up

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.13
=> Update deriv-charts to 2.1.13

.github/workflows/smoketests.yml
It was perceived that this was causing the issue for the run of the action. But as it wasn't it's best to revert it back.
jim-deriv's initial change:
=> Revert back secure version of checkout

packages/cfd/src/Containers/migration-banner/index.ts, packages/cfd/src/Containers/migration-banner/migration-banner.tsx
To import CSS changes in the component itselve
Before fix:
After Fix:
=> [HOTFIX]/Mitra/WEBREL-2710/MT5 migration banner css issue

.github/workflows/smoketests.yml
The github.event info isn't being pushed through to Cypress Cloud, which may be because we haven't supplied the token.
NB. I've temporarily removed the write to comments on failure, to avoid confusion with devs, whilst we're testing this.
=> Re-add Github token

packages/wallets/src/features/cashier/modules/DepositLocked/DepositLockedContent.tsx
=> [WALL] Lubega / WALL-3833 / Deposit locked welcome status description

packages/tradershub/src/components/Tooltip/Tooltip.classnames.ts, packages/tradershub/src/features/cfd/screens/TradeScreen/TradeDetailsItem/TradeDetailsItem.tsx
this is for V2 (!standalone)
fixed the tooltip which is covering the button clickability and hiding the whole flow
=> [CFDS] [TRAH] shontzu/CFDS-3884/Add-the-functionality-of-Change-password-button-on-trademodal

packages/core/src/Stores/client-store.js
This is the test PR which should be reverted.
To make sure that the `test-app.deriv.dev` and `test-app.deriv.com` are pointing to the same environment on CF
=> chore: add console to test passkeys conditions

packages/wallets/src/components/DesktopWalletsList/DesktopWalletsList.scss, packages/wallets/src/components/WalletsAddMoreCarousel/WalletsAddMoreCarousel.scss, packages/wallets/src/components/WalletsAddMoreCarousel/WalletsAddMoreCarousel.tsx, packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.scss
- Change the Trader's Hub with Wallets background in desktop to white.
- Add border radius and color for DesktopWalletsList.
https://github.com/binary-com/deriv-app/assets/125039206/19a63c86-37d7-4a8f-8ae1-2cfe2a6f5f49
=> [WALL] aum / WALL-3679 / wallets-traders-hub-white-bg

packages/tradershub/src/components/Tooltip/Tooltip.classnames.ts, packages/tradershub/src/components/Tooltip/Tooltip.tsx
* Fixed: tooltip overflow and alignment issue
**Before:**
**After:**
=> [CFDS]/Hasan/CFDS-3891/tooltip overflow issue

packages/wallets/src/components/Base/WalletDropdown/WalletDropdown.tsx, packages/wallets/src/components/WalletCurrencyCard/WalletCurrencyCard.scss, packages/wallets/src/components/WalletListCard/WalletListCard.scss, packages/wallets/src/components/WalletListCard/WalletListCard.tsx, packages/wallets/src/components/WalletListCard/__tests__/WalletListCard.spec.tsx, packages/wallets/src/components/WalletListCardDetails/WalletListCardDetails.scss
- Replaced WalletCurrencyIcon with WalletCurrencyCard for the header.
- Replaced bold chevron with filled chevron.
- Add gap between active wallet name (dropdown) and balance.
https://github.com/binary-com/deriv-app/assets/125039206/480afeba-0951-445c-9e49-06d3c6b50330
=> [WALL] aum / WALL-3530 / wallets-header-design-changes

packages/cfd/src/Containers/ctrader-derivx-trade-modal.tsx
cTrader account balance is showing in DerivX trade modal. Account balance is correctly reflecting in TH .
=> Hirad/CFDs-3925/ Fixed the issue of wrong balance shown in trade modal

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.14
=> Update deriv-charts to 2.1.14

packages/wallets/src/components/DatePicker/DatePicker.scss
Fix the overlapping of document preview of Dropzone on DatePicker by adding z-index to DatePicker
=> [WALL] aum / WALL-3816 / fix-DatePicker-overlap-Dropzone-in-doc-upload

packages/wallets/src/components/Base/IconButton/IconButton.scss, packages/wallets/src/features/cfd/components/CompareAccountsCarousel/CompareAccountsCarouselButton.scss, packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsScreen.tsx
- Re-add previous and next button inside of Compare Account Page inside of mobile
- Rename CFDCompareAccountsCard to CompareAccountsCard to match with component name and filename
- Disable hover background on mobile instead show on active
- Refactor code
=> [WALL] Aizad/WALL-3900/Re-add Buttons inside of Compare Account Page

packages/appstore/src/components/modals/regulators-compare-modal/regulators-compare-modal.scss, packages/appstore/src/components/modals/regulators-compare-modal/regulators-compare-modal.tsx, packages/cfd/build/constants.js, packages/cfd/package.json, packages/cfd/src/Containers/cfd-compare-accounts/__tests__/cfd-compare-accounts.spec.tsx, packages/cfd/src/Containers/cfd-compare-accounts/cfd-compare-accounts.scss, packages/cfd/src/Containers/cfd-compare-accounts/cfd-compare-accounts.tsx, packages/stores/src/mockStore.ts, packages/stores/types.ts
- modify `regulators-compare-modal` component and styles for it
- modify `cfd-compare-accounts` component and styles for it
- override styles for `dc-page-overlay` if it's a wrapper for `cfd-compare-accounts` modal
- add `deriv-com/ui `to `cfd` package
[Tablet view]
[Tablet view]
=> [TRAH] Sergei / TRAH-2762, TRAH-2763 / Tablet view for Jurisdiction Modal and Compare CFDs Accounts modal

packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsHeader.scss
https://github.com/binary-com/deriv-app/assets/142860499/74b2ee84-2bec-4718-8542-e60a2ceb06f0
https://github.com/binary-com/deriv-app/assets/142860499/d6d40028-9aed-4f4f-8819-97e7d0f301e9
=> [WALL] Lubega / WALL-3944 / Compare accounts header z-index

packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
https://github.com/binary-com/deriv-app/assets/142860499/ec71baf9-60dc-4561-a404-82280d3c63bd
https://github.com/binary-com/deriv-app/assets/142860499/021c8677-04d8-4c2b-b3c5-c3d42a6c3dfc
=> [WALL] Lubega / WALL-3922 / Wallet carousel interactivity fix

packages/core/src/App/Containers/NotificationsDialog/notification-list-wrapper.tsx
- Fixed an issue where the notifications are misaligned when in Wallets cashier
=> [WALL] Fix notifications misalign in cashier wallets

packages/wallets/src/features/cfd/screens/DynamicLeverage/DynamicLeverageTitle.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardBack.tsx
- Replace icon inside of `JurisdictionCardBack`
- Replace icon inside of `DynamicLeverageTitle`
=> Aizad/WALL-3966/Back Arrow Incorrect Placement fix

packages/wallets/jest.config.js, packages/wallets/jestTransformer.js
=> [WALL] Lubega / WALL-4037 / Fix failing unit and integration tests

packages/components/src/components/contract-card/contract-card-items/tick-counter-bar.tsx, packages/components/src/components/contract-card/contract-card.scss
Fix: style for tick counter bar alignment and color
- Removed text-align & color css styles in favor of `Text` component props
=> [DTRA-1266] shahzaib / style - accumulator tick count bar misaligned in contract card

packages/appstore/src/components/cfds-listing/index.tsx, packages/appstore/src/components/main-title-bar/asset-summary.tsx, packages/appstore/src/components/options-multipliers-listing/index.tsx, packages/appstore/src/modules/traders-hub/index.tsx, packages/shared/src/services/performance-metrics-methods.ts
End login_time rudderstack metrics calculation once CFD section is loaded. Right now it's ending while total deposit is getting loaded. This is skewing the data, as users are changing pages before this event
Start a new metric when client is on tradershub and end it once option and multiplier section is loaded we need to measure how much time it takes till option and multiplier section loads
=> [TRAH]/Mitra/TRAH-3381/Set performance value for login time once cfd section is loaded

packages/wallets/src/components/WalletGradientBackground/WalletGradientBackground.tsx, packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.tsx
All across the codebase we tend to default to USD currency. While its risky pattern, typically it does not cause any visible problems. Fixed the single case known to cause visible flickering of incorrect currency. 
Separately, as technical improvement, we should remove all the cases where we default to USD (imagine defaulting to incorrect currency exchange rate etc - really do not want to show incorrect data to users). 
Before:
https://github.com/binary-com/deriv-app/assets/141034155/66a21b0d-6dce-4d0c-910e-345a2f67d2dc
After:
https://github.com/binary-com/deriv-app/assets/141034155/95195e34-ad43-48e0-bf5b-a8cd20d58b37
=> [WALL-4020] feat: fixed flickering of USD background

packages/appstore/src/components/cfds-listing/cfds-listing.scss, packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-content-wrapper.tsx, packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal.tsx
- clients were not able to see the Next button  when trying to add an MT5 account right after clicking on the jurisdiction, these clients have a zoom level higher than 100% on their browsers, in order for them to see the Next button, they need to lower their zoom, scrolling does not work. 
- As this impacting MT5 account creation, may need to treat this as high priority
- [thread](https://deriv-group.slack.com/archives/C05H3QQ3FHA/p1715222456194569)
- [thread](https://deriv-group.slack.com/archives/C0124FT6URM/p1715202935359309)
- check on mobile and desktop
- check modal for derived, financial, and all
- check dynamic leverage modal and verification card
https://github.com/binary-com/deriv-app/assets/108507236/f744e82f-7808-461a-aeb0-df3962bce721
=> [CFDS] shontzu/CFDS-3970/Next-button-not-visible-during-account-creation

packages/wallets/src/features/cfd/modals/MT5AccountAdded/MT5AccountAdded.tsx, packages/wallets/src/features/cfd/screens/CFDSuccess/CFDSuccess.scss, packages/wallets/src/features/cfd/screens/CFDSuccess/CFDSuccess.tsx
- Added displayBalance and add it inside of useMemo
- Refactor code
- Added loading animation for Balance section
**Before**:
(skip to 00:25s)
https://github.com/binary-com/deriv-app/assets/103104395/c6e7c5ab-eec5-4423-96f0-0fc6d5bef036
**After**
https://github.com/binary-com/deriv-app/assets/103104395/f976a3f4-654e-42f9-8daa-b9a33f2c28e3
=> [WALL] Aizad/WALL-3967/ Fix "USD" is missing from swap free account creation success card

packages/wallets/src/features/cashier/modules/FiatOnRamp/FiatOnRamp.tsx, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoReceipt/WithdrawalCryptoReceipt.scss, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoReceipt/WithdrawalCryptoReceipt.tsx
- Fix the arrow direction in WithdrawalCryptoReceipt by replacing it with the correct quill-icon counterpart.
- (Extra) Fixed arrow for back button in FiatOnRamp
=> [WALL] aum / WALL-4052 / fix-arrow-direction-wallet-withdrawal-crypto-receipt

packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoForm/components/WithdrawalCryptoAmountConverter/WithdrawalCryptoAmountConverter.scss
Fix the arrow direction in WithdrawalCryptoAmountConverter after it was replaced from quill-icons.
=> [WALL] aum / WALL-4034 / fix-wallet-crypto-withdrawal-arrow-direction

packages/wallets/src/features/cashier/modules/Transfer/components/TransferReceipt/TransferReceipt.scss
Fix the arrow direction shown between wallets in TransferReceipt after successful transfer.
https://github.com/binary-com/deriv-app/assets/125039206/694a584f-7411-48e5-9975-5694b449311e
https://github.com/binary-com/deriv-app/assets/125039206/d007d54d-ea4b-45fa-a21a-1fb71a6ae8e3
=> [WALL] aum / WALL-3959 / fix-transfer-success-receipt-arrow-direction

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.15
=> Update deriv-charts to 2.1.15

packages/wallets/src/components/WalletsAppLinkedWithWalletIcon/WalletsAppLinkedWithWalletIcon.tsx, packages/wallets/src/components/WalletsAppLinkedWithWalletIcon/__tests__/WalletsAppLinkedWithWalletIcon.spec.tsx, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountCard/TransferFormAccountCard.tsx, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountCard/__tests__/TransferFormAccountCard.spec.tsx
=> [WALL] Lubega / WALL-2991 / TransferFormAccountCard unit test

packages/reports/src/_common/components/__tests__/loading.spec.tsx
Add tests for packages/reports/src/_common/components/loading.tsx
=> DTRA/ Kate / WEBREL-5 / Add tests for loader component

packages/shared/src/utils/date/date-time.ts
- fix duration date localization by ensuring that no languages are ignored in `initMoment()`.
=> [DTRA] Maryia/DTRA-1219/fix: month not translated in duration

packages/bot-web-ui/src/app/app-content.jsx, packages/bot-web-ui/src/stores/app-store.ts
- Fixed DBot keep on requesting for `active_symbols` API call
=> chore: :fire: fix the active_symbols refetching issue on bot

packages/core/src/App/Components/Layout/Header/account-actions.jsx, packages/core/src/App/Components/Layout/Header/toggle-notifications.jsx, packages/core/src/App/Components/Layout/Header/wallets/account-actions-wallets.tsx, packages/shared/src/utils/os/os_detect.ts, packages/trader/src/Modules/Trading/Components/Elements/purchase-fieldset.tsx
- Made popover optional for purchase button for Multipliers and links in the header (notifications and account settings).
Note: function for detection TabletOS was taken from [here](https://github.com/binary-com/deriv-app/pull/15123/files#diff-d05e01aebb22cbc5a1ee9d4830bedce5ace5a036dc9d4a8422c5083d0c259147). Failing test cases were also fixed there.
https://github.com/binary-com/deriv-app/assets/121025168/31ab74aa-4e6d-4383-a799-a6d69715bdf4
=> DTRA / Kate / FEQ-2213 + FEQ-2205 / Made popover optional

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.16
=> Update deriv-charts to 2.1.16

packages/components/src/components/contract-card/contract-card-items/contract-card-sell.tsx, packages/reports/src/Components/__tests__/empty-trade-history-message.spec.tsx, packages/reports/src/Components/__tests__/indicative-cell.spec.tsx, packages/reports/src/Components/indicative-cell.tsx
This feature enhances the project's test suite by adding test coverage for two specific areas: the empty trade history message and the indicative cell.
- Empty Trade History Message: Implement tests to ensure that the message displayed when there is no trade history functions correctly. This includes verifying that the message appears under the correct conditions and is accurate.
- Indicative Cell: Add tests for the indicative cell component to confirm it displays the correct information and updates appropriately based on various scenarios.
These tests will help maintain the reliability and correctness of these components, ensuring they behave as expected across different use cases and edge cases.
=> Akmal / feat: add test coverage for empty trade history message and indicative cell

packages/core/src/public/.well-known/apple-app-site-association
Updated Deriv Go's app links paths for dev and staging in the file apple-app-site-association.
=> refactor(deriv_go): updated Deriv Go's app links paths for dev and staging

package-lock.json, packages/core/package.json, packages/trader/package.json, packages/trader/src/AppV2/app.tsx
- to update quill-ui library version to 1.9.27.
- to import @deriv-com/quill-ui/quill.css in the entry file to have library styles applied in DTrader V2.
=> [DTRA] Maryia/build: update quill-ui library version to 1.9.27 + utilize lib styles

.github/actions/analyze/action.yml, .github/actions/analyze/compareReports.js, .github/workflows/analyze.yml
This will add a comment to every pull requests with bundle size information
- 🟢 the bundle size is **less** than master
- 🟡 the bundle size is **more** than master, but by no more than 5%
- 🔴 the bundle size is **more** than 5% of master
This will not fail or block a build, it's just an indicator for reviewers to take into consideration before approving a request.
=> [TRAH-3259]: chore: add comment to pull requests with bundle size information

packages/wallets/src/components/WalletTourGuide/WalletTourGuide.tsx, packages/wallets/src/components/WalletTourGuide/WalletTourGuideSteps.tsx
- added checks for `allWalletsAreAdded` within `desktopStepTourGuide` and `mobileStepTourGuide`.
- made changes to make onboarding to appear smooth.
Desktop:
https://github.com/binary-com/deriv-app/assets/103104395/4174d9a4-34f1-42e8-beb9-c7917c123604
Mobile:
https://github.com/binary-com/deriv-app/assets/103104395/c88311b9-35de-4921-80a0-f6aaa7a6ab0f
=> [WALL] Aizad/WALL-4096/Skip Step Add More Wallets

packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx, packages/wallets/src/features/cfd/modals/CTraderSuccessModal/CTraderSuccessModal.tsx, packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx, packages/wallets/src/features/cfd/modals/MT5AccountAdded/MT5AccountAdded.tsx, packages/wallets/src/features/cfd/modals/MT5AccountAdded/__tests__/MT5AccountAdded.spec.tsx
- fix balance for CFDs success popup (MT5, DerivX, Dxtrade)
=> [WALL-4083] george / WALL-4083 / demo wallet balance is displayed instead CFDs balance on CFDs success popup

packages/shared/src/utils/routes/routes.ts
Fixed the routing issue for the `Manage Funds` button in account settings page. On clicking the button, the user must be routed to wallets transfer page with the correct wallet authorized and correct destination account selection.
https://github.com/binary-com/deriv-app/assets/125039206/384753fb-ce85-4913-87e7-2e9193ffc649
https://github.com/binary-com/deriv-app/assets/125039206/b198030f-7c5f-4a9c-adb2-354fbbcdf487
=> [WALL] aum / WALL-4085 / fix-routing-for-manage-funds-button-in-account-settings

.github/actions/analyze/action.yml, .github/workflows/analyze.yml
Fix the build, by using the correct node file path.
=> chore: get the last successful master artifact

packages/core/src/Utils/Datadog/index.ts
Here we were binding clients consent api to our remote config implementation which wasn't right.
I removed that extra thing until we have answer from compliance team to implement the proper consent form if needed.
The issue was that we were returning from the function if datadog was enabled from firebase remote config.
=> Ako/ Fix datadog initialisation on the app

packages/bot-web-ui/src/components/bot-notification/bot-notification-utils.ts, packages/bot-web-ui/src/components/bot-notification/bot-notification.tsx, packages/bot-web-ui/src/components/download/download.scss, packages/bot-web-ui/src/components/download/download.tsx, packages/bot-web-ui/src/components/run-panel/run-panel.scss, packages/bot-web-ui/src/components/transactions/transactions.scss, packages/bot-web-ui/src/components/transactions/transactions.tsx, packages/bot-web-ui/src/pages/bot-builder/quick-strategy/quick-strategy.scss, packages/bot-web-ui/src/pages/bot-builder/toolbar/workspace-group.tsx, packages/bot-web-ui/src/pages/dashboard/dashboard.scss
- Fixed notification visibility to autoclose when browser tab is switched and timer is complete
- Improved alignment of action buttons on quick strategy form
- Improved dashboard shortcut icons alignment
- Improved bugs on different languages
=> [BOT] Farabi/bot-1601/dbot bugs and improvements

packages/wallets/src/components/WalletListCardDetails/WalletListCardDetails.tsx
https://github.com/binary-com/deriv-app/assets/119863957/bf555647-6ace-48bb-b678-67e5fb1e8872
=> [WALL] [Fix] Rostislav / WALL-4135 / Fix wallet name in wallet account switcher looking odd in-between switches

packages/account/src/Components/currency-selector/__tests__/currency-selector.spec.tsx, packages/account/src/Components/currency-selector/currency-selector.tsx, packages/account/src/Components/currency-selector/radio-button-group.tsx
As per figma design, in staging Cryptocurrencies subheading is not removed in the Account Creation modal while adding a real deriv account.
=> [WEBREL]/Mitra/[WEBREL-2753] remove crypto subheader

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.18
=> Update deriv-charts to 2.1.18

.github/workflows/test.yml, analyze.html, jest.config.base.js, jest.config.js, lerna.json, package.json, packages/core/build/config.js, packages/core/package.json, packages/core/src/App/Components/Routes/route-with-sub-routes.jsx, packages/core/src/App/Constants/routes-config.js, packages/core/src/root_files/robots.txt, packages/shared/src/utils/routes/routes.ts, packages/stores/src/stores/FeatureFlagsStore.ts, packages/tradershub/package.json, packages/tradershub/tsconfig.json, packages/tradershub/webpack.config.js
Development on account-v2 package has been deprioritized. Hence all checks on this package can be removed to speed up CI during deployments
-  Remove CI instructions from test.yml
-  Remove is_next_account_enabled flag
- Remove /account-v2 route
- Remove usage of @deriv/account-v2 and @deriv/account-v2-lib
- Exclude account-v2 & account-v2-lib from `build:all`, `test:eslint-all`
- Exclude account-v2 from jest
=> [COJ]/likhith/[coj-1131]chore: remove account-v2 checks from CI

packages/wallets/src/components/Base/WalletClipboard/WalletClipboard.tsx, packages/wallets/src/components/Base/WalletClipboard/__tests__/WalletClipboard.spec.tsx
=> [WALL] [Jest] Rostislav / WALL-3050 / Unit tests for `<WalletClipboard />`

packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/compareAccountsConfig.ts, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardRow.scss, packages/wallets/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/jurisdiction-svg-contents.ts
=> [WALL] Lubega / WALL-4163/4165 / Compare accounts and jurisdiction fixes

packages/wallets/src/components/Base/ModalStepWrapper/ModalStepWrapper.scss, packages/wallets/src/features/accounts/screens/AddressSection/AddressSection.tsx, packages/wallets/src/features/accounts/screens/DocumentSubmission/DocumentSubmission.tsx, packages/wallets/src/features/accounts/screens/DocumentSubmission/__tests__/DocumentSubmission.spec.tsx, packages/wallets/src/features/accounts/screens/PersonalDetails/PersonalDetails.scss, packages/wallets/src/features/accounts/screens/PersonalDetails/PersonalDetails.tsx, packages/wallets/src/features/accounts/screens/PersonalDetails/constants.tsx, packages/wallets/src/features/accounts/validations.ts, packages/wallets/src/features/cfd/flows/Verification/Verification.tsx
https://github.com/binary-com/deriv-app/assets/142860499/4d371f6c-7795-4262-abb4-5edd81dd4e14
https://github.com/binary-com/deriv-app/assets/142860499/7330a510-f7a5-47a1-a2bd-6161bd0d4c29
Livechat:
https://github.com/binary-com/deriv-app/assets/142860499/15fec1a8-c45e-44e5-9edf-60bbc1aa07cc
https://github.com/binary-com/deriv-app/assets/142860499/f128657e-4896-4eb3-8c5f-e8a8d420bdda
=> [WALL] Lubega / WALL-4175 / POA and personal details validations and discrepancies

packages/wallets/src/components/WalletGradientBackground/WalletGradientBackground.scss, packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
Account creation flow:
https://github.com/binary-com/deriv-app/assets/142860499/b08c22e9-42a2-4194-8d9c-ef72202fcb10
MT5 reset password flow:
https://github.com/binary-com/deriv-app/assets/142860499/9ba820a2-1e37-42d6-9830-3b21526ddaf1
=> [WALL] Lubega / WALL-4162 / Account creation success message fix

packages/components/src/components/date-picker/date-picker.scss, packages/components/src/components/date-picker/date-picker.tsx, packages/components/src/components/form-submit-button/form-submit-button.scss, packages/core/src/App/Containers/RealAccountSignup/add-crypto-currency.jsx, packages/core/src/App/Containers/RealAccountSignup/currency-selector.scss, packages/core/src/sass/account-wizard.scss
Change css mixins and js breakpoints
=> Sergei / FEQ-2201, FEQ-2241, FEQ-2232, FEQ-2223, FEQ-2222 / Fix tablet view issue

packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
- Added `PasswordLimit` exceeded modal to MT5
=> [WALL] Jim/WALL-4213/ add missing modal in MT5

packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
- The issue arises because the company field passed to the Demo account must always be `svg`. If it is not, the error specified in the card will occur.
- Added a condition where if the account type is demo then it will return `svg`.
- Replace hard coded values with values from constant file.
**Before:**
**After:**
=> [WALL] Aizad/WALL-4223/Error When Receiving Demo Derived & Financial MT5 for Demo Account

packages/p2p/src/components/modal-manager/modals/add-payment-method-error-modal/add-payment-method-error-modal.tsx, packages/p2p/src/pages/my-profile/payment-methods/edit-payment-method-form/edit-payment-method-form.tsx
- Fixed issues with user not able to click on save changes button after receiving error
- Fixed issues with user not being able to stay on create payment method page after an error is received
https://github.com/binary-com/deriv-app/assets/103412909/f9a7f475-33dc-4636-a563-83eef2847ac1
=> [P2PS] / Ameerul / P2PS-2819 Unable to click on save button upon getting duplicate error

packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- Remove Cashier link from responsive menu if Wallets is enabled
- Remove Trader link from responsive menu if is not at the root directory.
Tradershub [Wallet enabled] homepage:
On the Trade page [Wallet enabled] or any other page than the homepage:
=> Aizad/WEBREL-2778/Remove Cashier Trader Link from Wallets Responsive

packages/wallets/src/components/DatePicker/DatePicker.tsx, packages/wallets/src/features/accounts/screens/VerifyDocumentDetails/VerifyDocumentDetails.tsx, packages/wallets/src/features/accounts/screens/VerifyDocumentDetails/__tests__/VerifyDocumentDetails.spec.tsx, packages/wallets/src/utils/utils.ts
- Added format param to `unixToDateString` util function.
- Added `displayFormat` prop to DatePicker.
- Added custom format of `DD-MM-YYYY` as displayFormat to DatePicker used in VerifyDocumentDetails form to make it consistent with prod.
=> [WALL] aum/WALL-4241/fix-dob-format-verify-document-details

packages/wallets/src/components/DerivAppsSection/DerivAppsGetAccount.tsx, packages/wallets/src/components/WalletsAddMoreCardBanner/WalletsAddMoreCardBanner.tsx, packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx
Fix the below mentioned issues when tapping buttons in quick succession
- Quickly tap on `Add` button in `Add more wallets` section multiple times throws error.
- For a client without CTrader account, quickly tap on `CTrader` in CFDs section multiple times creates multiple CTrader accounts.
- For a Wallet without Options account, quickly tap on `Get` button in Options account section crashes the application.
=> Nijil / wall-4221 / Fix rapid button click issues

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.19
=> Update deriv-charts to 2.1.19

packages/trader/src/Modules/Contract/Components/InfoBox/info-box-longcode.tsx, packages/trader/src/sass/app/modules/contract.scss
For small Android tablets in landscape view we were applying className for IPhone SE, which rewritten font-size. Add check for detecting Tablet OS
IPhone SE is still the same
Android Tablet (Tab 9)
Android Tablet (Tab 8)
=> FEQ-2313 / Kate / Android tablet- Long code message content is showing in smaller size

packages/trader/src/sass/app/_common/components/contract-type-dialog.scss
=> Akmal / set contract type dialog height

packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.tsx, packages/wallets/src/routes/WalletsListingRoute/__tests__/WalletsListingRoute.spec.tsx
This is a PR to reduce the load time for wallets with TH by performing code-splitting in WalletsListingRoute component.
Previously, we loaded both the `DesktopWalletsList` (wallets shown in desktop) and `WalletsCarousel` (wallets carousel shown in mobile) regardless of the viewport in which the app was loaded.
Now, we only load `DesktopWalletsList` if the user is accessing app through desktop device and `WalletsCarousel` if accessed through mobile device.
This has helped in performance improvements by shaving-off: 
- `~1 MB` (1000 KB) of extra data loaded for `mobile`
- `~400 KB` of extra data loaded for `desktop`
Before:
After:
=> [WALL] aum / WALL-4307 / Lazy-load-DesktopWalletsList-and-WalletsCarousel

packages/account/src/Components/reset-trading-password-modal/reset-trading-password-modal.tsx, packages/account/src/Containers/reset-trading-password.tsx, packages/appstore/src/components/modals/modal-manager.tsx, packages/core/src/Stores/ui-store.js, packages/wallets/src/components/WalletsResetMT5Password/WalletSuccessResetMT5Password.tsx, packages/wallets/src/components/WalletsResetMT5Password/WalletsResetMT5Password.tsx
- after clicking the email link to reset password on TradersHub, the password modal still popup when user navigate to accounts setting
- there are two conflicting visibility states in `ui-store` causing inconsistency in modal behaviour
- `/account` is using `is_reset_trading_password_modal_visible` && `setResetTradingPasswordModalOpen`
- `/cfd` is using `is_cfd_reset_password_modal_enabled` && `setCFDPasswordResetModal`
- they are duplicated
- both these actions and observers handle `ResetTradingPassword` Modal  visibility
Below are demo video for Wallets and Prod after the fix
https://github.com/binary-com/deriv-app/assets/108507236/22cb652c-acc8-431d-8492-5a73223bedba
https://github.com/binary-com/deriv-app/assets/108507236/ffc566f3-3db6-4071-8cb0-03924dee0b1f
=> [WALL][CFDS] shontzu/CFDS-3999/Create-New-password-modal-reappears-on-manage-account-settings

packages/appstore/src/components/currency-switcher-card/real/real-account-card.tsx
Pass currency instead of uppercase currency to `BalanceText` component
=> [TRAH] Sergei / TRAH 3496 / Naming correction from "EUSDT" to "eUSDT" and from "TUSDT" to "tUSDT"

packages/core/src/App/Containers/Redirect/redirect.jsx
https://github.com/binary-com/deriv-app/assets/108507236/3ef06ee2-8f65-4fe3-898d-ecef6adf1e74
https://github.com/binary-com/deriv-app/assets/108507236/753d8d90-0f4f-416e-9c22-22dc1ae24dca
=> fix: V20240606_0 hotfix/Password reset popup not opening for DerivX and MT5

packages/account/src/Sections/Security/SelfExclusion/__tests__/self-exclusion.spec.tsx, packages/account/src/Sections/Security/SelfExclusion/self-exclusion.tsx, packages/cashier/src/pages/withdrawal/withdrawal.tsx, packages/cashier/src/stores/__tests__/withdraw-store.spec.ts, packages/cashier/src/stores/withdraw-store.ts, packages/core/src/Stores/client-store.js
- Add WS.wait("get_limits") to the withdraw store
- Remove `get_limits` calling from `switchAccountHandler` in client store because it calls init() where we are calling `get_limits` again
- Change `WS.authorized.getLimits` to `getLimits` from store in `SelfExclusion` component
https://github.com/binary-com/deriv-app/assets/120570511/52672b5e-a012-4f74-8461-1ceba931f1ee
=> [TRAH] Sergei / TRAHH - 3666 / Investigate get_limits being triggered many times

packages/reports/src/Components/Form/CompositeCalendar/__tests__/composite-calendar.spec.tsx, packages/reports/src/Components/Form/CompositeCalendar/__tests__/list-item.spec.tsx, packages/reports/src/Components/Form/CompositeCalendar/__tests__/side-list.spec.tsx, packages/reports/src/Components/Form/CompositeCalendar/side-list.tsx
- Added tests for composite-calendar, side-list & list-item in Reports package.
=> WEBREL-4 / Kate / Test coverage: composite-calendar, side-list & list-item in Reports

packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.tsx
Replace the hard-coded value for broker name in MT5TradeModal with name received under `landing_company` key from BE.
https://github.com/binary-com/deriv-app/assets/125039206/f58ff45a-2c72-4a15-90bd-e3f5ba3ccaa4
https://github.com/binary-com/deriv-app/assets/125039206/368f0360-bb44-4cad-b492-0c9778eaa1c4
=> [WALL] aum/WALL-4364/fix-MT5TradeModal-broker-name

packages/bot-web-ui/src/stores/app-store.ts, packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx, packages/shared/src/utils/digital-options/digital-options.ts
- Add check for `DBot` route, because for `DBot` we have to `logout` first and only after this redirect to `TH`
https://github.com/binary-com/deriv-app/assets/120570511/66659e94-f550-448a-b30d-666371ed6922
=> [WEBREL] Sergei / WEBREL - 2813 / Logout is not working from Dbot

packages/bot-web-ui/src/analytics/rudderstack-quick-strategy.ts
- Added the strategy name parameters on the run_quick_strategy and edit_quick_strategy actions for quick strategy events
=> [BOT] Farabi/bot-1900/add strategy name on run edit qs rudderstack

packages/bot-web-ui/src/analytics/rudderstack-quick-strategy.ts, packages/bot-web-ui/src/analytics/utils.ts, packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/__tests__/useQsSubmitHandler.spec.tsx, packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/desktop-form-wrapper.tsx, packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/useQsSubmitHandler.tsx
- Fixed the trigger of rudderstack event for run strategy and edit strategy from quick strategy form to send only after form validation is completed
=> [BOT] Farabi/bot 1900/fix qs run and edit rudderstack event

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.21
=> Update deriv-charts to 2.1.21

packages/trader/src/Stores/Modules/Trading/Helpers/__tests__/chart.spec.ts, packages/trader/src/Stores/Modules/Trading/Helpers/chart.ts
- to stop Rudderstack tracking of `open` & `close` actions for `ce_chart_types_form` (Markets dropdown) and `ce_market_types_form` (Chart Types modal) on the chart.
=> [DTRA] Maryia/CRO-624/Stop Rudderstack tracking of open/close actions for ce_chart_types_form and ce_market_types_form

packages/bot-web-ui/src/stores/app-store.ts
- Updated EU check on URL
- If it includes `/bot/?something=` it should block the bot for EU users
=> [BOT] sandeep/bot-1910/eu-access-bot

packages/wallets/src/components/WalletMarketCurrencyIcon/WalletMarketCurrencyIcon.tsx, packages/wallets/src/components/WalletMarketCurrencyIcon/__test__/WalletMarketCurrencyIcon.spec.tsx
- added test case for WalletMarketCurrencyIcon
=> [WALL] Aizad/WALL-2899/WalletMarketCurrencyIcon-test-case

packages/core/package.json, packages/core/src/App/Components/Layout/Header/__tests__/platform-dropdown.spec.tsx, packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx, packages/shared/src/utils/contract/trade-url-params-config.ts, packages/trader/src/Stores/Modules/Trading/trade-store.ts
To fix cases when search params (trade params: '?chart_type...) are missing from DTrader URL:
1. When Contract Details page is opened from DTrader, and after that, 'Close' button is pressed to come back to DTrader,
2. When DTrader is already open but a user selects it again from the Platform Switcher in the app Header.
=> [DTRA] Maryia/DTRA-1234/fix: always show search params in DTrader URL when DTrader is open

.github/workflows/sync-translations.yml
sync_translation.yml file triggers for PRs from forked repos. This results in failure as the workflow triggered from forked repo dosen't have access to repository secrets and environmental variables.
Hence restricting the workflow to only PRs merged to upstream master
=> chore: removed pull_request section

packages/account/src/Components/language-settings/language-radio-button.tsx, packages/core/src/App/Components/Layout/Footer/toggle-language-settings.tsx, packages/core/src/App/Components/Layout/Header/Components/ToggleMenu/menu-title.tsx, packages/core/src/App/Components/Routes/language-link.tsx, packages/shared/src/utils/constants/translation-flag.tsx
Change TranslationFlag from using size to use width and height
=> Suisin/chore: fix size for translation flag

packages/wallets/src/components/DerivAppsSection/DerivAppsTradingAccount.tsx
- replace reset balance icon with transfer icon inside of Demo Wallets
- redirect to transfer page instead of reset balance page when pressing on the icon
- changes is applied on both desktop and mobile
=> [WALL] Aizad/WALL-4421/Replace Reset With Transfer Icon inside of Demo Wallet

packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-content-wrapper.tsx, packages/stores/types.ts
- The root cause of this issue is that in the swap-free jurisdiction model, we are only filtering for `market_type = "all"`
- it is not unique to swap-free / zero-spread
- use `product` to uniquely identify swap-free
=> [CFDS] shontzu/CFDS-4248/Add-product-filtering-for-swap-free-jurisdiction-modal

packages/bot-web-ui/src/pages/server-bot/server-bot-list.tsx, packages/bot-web-ui/src/pages/server-bot/server-bot.scss, packages/bot-web-ui/src/pages/server-bot/server-bot.tsx, packages/bot-web-ui/src/stores/server-bot-store.ts
Test link bug fixing and improvements
1)Handle the situation where a user closes the browser tab and then reopens the application. To address this, we implement the following logic:
1. run API call `"bot_list"`
2. check data in the response, find an **active/running** bot
3. send request `"bot_notification"` with bot id to subscribe
`{"bot_notification": 1, "bot_id" : "ID", "subscribe" : 1, "limit": 1000 }`
2)Remove the stop button and instead integrate a toggle button to switch to stop if the bot is running.
https://github.com/binary-com/deriv-app/assets/103181650/53458953-534e-49b3-8bb5-3f9ed8c2aa96
=> [BOT] [Server Side Bot]maryia/bot 1913/Test link bug fixing and improvements

packages/account/src/Sections/Profile/LanguageSettings/language-settings.tsx, packages/core/src/App/Components/Routes/language-link.tsx, packages/core/src/App/Containers/SettingsModal/settings-language.jsx
Language icon in the footer dosen't get updated to new language when user changes the Deriv app language. 
This is because the language change function returns a promise which is not awaited before setting the state of the new language
=> [COJ]/likhith/coj-1246/fix: awaited language change before update

packages/wallets/src/components/OptionsAndMultipliersListing/LinkTitle.tsx, packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.tsx, packages/wallets/src/components/WalletMarketIcon/WalletMarketIcon.tsx, packages/wallets/src/constants/constants.tsx
- Refactor `OptionsAndMultipliersListing` component
- Use `WalletMarketIcon` component
- Remove imports from constant files and instead import required icons inside of `WalletMarketIcon`
- Separate `LinkTItle` as its own child component
- Remove unused icons
Link to CU: https://app.clickup.com/t/20696747/WALL-4436
=> [WALL] Aizad/WALL-4436/Refactor Options Multiplier Listings

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.22
=> Update deriv-charts to 2.1.22

packages/cfd/src/Containers/cfd-compare-accounts/cfd-compare-accounts.tsx, packages/components/src/components/cfd-compare-accounts-carousel/cfd-compare-accounts-carousel-button.tsx, packages/components/src/components/cfd-compare-accounts-carousel/cfd-compare-accounts-carousel.tsx
- add `isRtl` prop for carousel in `cfd-compare-accounts` component
- add `direction` option to `embla` carousel
- change order of arrows for `rtl` languages
**Desktop:**
**Mobile:**
=> [TRAH] Sergei / TRAH - 3699 / 'Compare CFDs accounts' page does not have side arrow options for navigation for Arabic language

packages/wallets/src/components/SkeletonLoader/SkeletonLoader.scss, packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.scss, packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.tsx
- Add skeleton loader for balance in header cashier overlay
- Add `0.3 opacity` to skeleton loader
https://github.com/binary-com/deriv-app/assets/103181646/fb9486be-b0b0-49a5-a3b7-3338e910d882
=> [WALL] george / WALL-4422 / Wallet header showing 0.00 for split second if click wallet's related button from Trader's hub home

jest.config.base.js, packages/cashier-v2/jest.config.ts, packages/components/jest.config.js, packages/p2p-v2/jest.config.js, packages/p2p/jest.config.js, packages/trader/jest.config.js
- extending `transformIgnorePatterns` from base jest config
- remove `@deriv/quill-design|@deriv/quill-icons|@deriv-com/translations` packages from `transformIgnorePatterns` that could also slowdown test execution
Previous test time execution:
Current time execution:
=> fix: :ambulance: fix test time execution

packages/reports/src/sass/app/modules/reports.scss
- to fix a spacing issue between filters and table in Reports related to [Tablet view feature](https://github.com/binary-com/deriv-app/pull/15011)
=> [DTRA] Maryia/WEBREL-2873/fix: spacing issue between filters and table in Reports

packages/p2p/src/components/modal-manager/modals/buy-sell-modal/buy-sell-modal.tsx, packages/p2p/src/stores/buy-sell-store.js
- hide modal when user confirms in attention fluctuation modal
- use error message from BE and not from FE side for slippage rate error
=> [WEBREL] / Ameerul / WEBREL-2858 Order unsuccessful error modal showing in glitch when trying to place order again after market rate change

packages/account/src/Styles/account.scss
Unset `margin-top` for `financial-assessment`
=> [WEBREL] Sergei / WEBREL - 2869 / Spacing between fields and container size is different in Financial assessment page

packages/appstore/src/components/main-title-bar/account-type-dropdown.scss, packages/appstore/src/modules/traders-hub/traders-hub.scss
- Unset `margin-top`
- set TH `width` as on production
=> [WEBREL] Sergei / WEBREL - 2866, 2867 / TradersHub title is not aligned with real/demo switcher as in production and change TH container size

packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.tsx, packages/wallets/src/features/cashier/components/WalletCashierHeader/__tests__/WalletCashierHeader.spec.tsx
=> [WALL] Lubega / WALL-4224 / Remove badge from cashier overlay

packages/trader/src/AppV2/Containers/Positions/positions-content.tsx, packages/trader/src/AppV2/Utils/__tests__/contract-details-config.spec.ts, packages/trader/src/AppV2/Utils/__tests__/positions-utils.spec.ts, packages/trader/src/AppV2/Utils/positions-utils.ts
- Added CALLE/PUTE  to config in order to send it together with CALL/PUT in the array of contract_type to profit_table request, when user applies 'Rise/Fall' filter.
- Refactor existing tests
=> DTRA-1368 / Kate /  Position and Contract Details Page refactor: add CALLE/PUTE filtration

packages/trader/src/AppV2/Components/Filter/contract-type-filter.tsx, packages/trader/src/AppV2/Components/Filter/time-filter.tsx, packages/trader/src/AppV2/Containers/Positions/positions-content.tsx
- Console error was visible only on tests links. Issue is coming from Quill library: in `Chip` component `label` should accept only `string`, but according to type it can be `React.ReactNode`. Because of that, when we are passing `ReactNode` and during cloning element we will get an error here:
`{label &&. React.cloneElement(LabelTextSizes[size], {children: label})}`
- Refactor existing config with Localized filters
- Added additional condition for `shouldShowLoading` in order to fix fetching loader
https://github.com/binary-com/deriv-app/assets/121025168/f5b8ac6f-697e-4ce9-b196-16d43d6d187f
=> DTRA-1366 / Kate / Fix: console error on the test links for DTrader-V2

packages/bot-web-ui/src/pages/dashboard/dashboard.scss, packages/bot-web-ui/src/pages/dashboard/load-bot-preview/index.scss
Fix dashboard shortcuts icons alignment when the your bots list is populated on tablet view
=> fix: dashboard shortcuts on tablet view

packages/bot-web-ui/src/pages/tutorials/quick-strategy-content/quick-strategy-guides-details.tsx, packages/bot-web-ui/src/pages/tutorials/tutorials-tab-mobile.tsx
- Fixed issue with content scroll to top on tutorial tabs switching on mobile
=> fix: scroll to top when tutorial tab switch on mobile

packages/wallets/src/components/ToggleSwitch/ToggleSwitch.scss, packages/wallets/src/components/WalletListHeader/WalletListHeader.scss
=> [WALL] Lubega / WALL-3902 / Safari transactions toggle ui fix

packages/bot-skeleton/src/services/tradeEngine/trade/Balance.js
The property `balance` is getting missed in some instances for which the destructure error is thrown. Added a check to ensure that `balance` is also present before destructuring the value.
=> [BOT] shafin/fix: balance destructure from undefined trackjs issue

packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AvailableDxtradeAccountsList/AvailableDxtradeAccountsList.tsx, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AvailableDxtradeAccountsList/__test__/AvailableDxtradeAccountsList.spec.tsx
Added unit test for `AvailableMT5AccountsList`
=> Aizad/WALL-2937/Unit test for AvailableDxtradeAccountsList in DxTrade flow

packages/core/src/sass/app/modules/notifications-dialog.scss
Fixes the overflow of button description text in notification tray
=> chore: fix description crop

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.23
=> Update deriv-charts to 2.1.23

packages/wallets/src/components/WalletsCarouselHeader/WalletsCarouselHeader.scss, packages/wallets/src/components/WalletsCarouselHeader/WalletsCarouselHeader.tsx, packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.scss, packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.tsx
- Replace old icons with new ones based on latest design changes in the Transfer page for both Real and Demo Wallets
- Replace old icon with new one on the sticky header
=> [WALL] Aizad/WALL-4228/Consistent Icons Across Wallet Overlay and TH Main Page

packages/api-v2/types.ts, packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsScreen.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionScreen.tsx
There are 2 Swap-free accounts under compare accounts and There is an additional BVI card in the modal.
=> Hirad/wall-4485/ swap-free and compare accounts fix

packages/bot-web-ui/src/components/draggable/draggable.tsx
- Fixed the issue where transactions detail modal was not scrolling on firefox browser upon dragging or resizing the modal
https://github.com/binary-com/deriv-app/assets/102643568/65be47a9-71ce-4a6d-9804-be1e7dd221be
=> [BOT] Farabi/bot-1723/unable to scroll transactions details modal on firefox

packages/bot-web-ui/src/components/load-modal/load-modal.scss, packages/bot-web-ui/src/components/load-modal/local.tsx, packages/bot-web-ui/src/components/load-modal/section-message/index.ts, packages/bot-web-ui/src/components/load-modal/section-message/section-message.scss, packages/bot-web-ui/src/components/load-modal/section-message/section-message.tsx
- Replaced quill-ui SectionMessage with custom SectionMessage component to mitigate the style override issue in the icons.
Mobile
Desktop
=> fix: :fire: replaced section message with custom comp

packages/appstore/src/components/containers/trading-app-card.tsx
=> [WEBREL] Sergei / WEBREL - 2898 / Found an extra symbol of semicolon on the NEW! label for MT5 Zero Spread account on Trader's Hub Real/Demo site

packages/trader/build/webpack.config.js, packages/trader/package.json
`@deriv/reports` is not used inside deriv-app, so it can be safely removed
* no cards :)
=> Remove `@deriv/reports` from DTrader dependencies

packages/core/src/sass/app/_common/components/account-common.scss
issue :
Footer in Desktop view is not aligned to the content of the page which doesnt match the design 
issue :
fix:
=> Footer issue in POi aligned in Desktop view

packages/reports/jest.config.js, packages/reports/src/Stores/__tests__/use-reports-stores.spec.tsx, packages/reports/src/__tests__/app.spec.tsx, packages/reports/src/__tests__/reports-providers.spec.tsx
- Added tests for packages/reports/src/app.tsx
- Added tests for packages/reports/src/reports-providers.tsx
- Added tests for packages/reports/src/Stores/useReportsStores.tsx
- Changed jest config in order to support absolute path for Containers folder
=> WEBREL-17/ Kate / Add tests for reports files and change jest config for absolute path

packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_multiplier.js, packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_tradeoptions.js
- Removed the stake amount limit of min and max value on trade options block for multiplier
=> [BOT] Farabi/bot-529/remove limits from multiplier block

package-lock.json, package.json, packages/account/package.json, packages/api-v2/package.json, packages/appstore/package.json, packages/cfd/package.json, packages/core/package.json, packages/hooks/package.json, packages/reports/package.json, packages/shared/package.json, packages/trader/package.json, packages/wallets/package.json
- Downgrade `@deriv-com/analytics` package to v1.5.9 to avoid `@rudderstack/analytics-js` version inconsistency between deriv-app and deriv-com apps.
=> [WEBREL] george / WEBREL-2905 / downgrade deriv-com/analytics to v1.5.9

package-lock.json, package.json, packages/account/package.json, packages/api-v2/package.json, packages/appstore/package.json, packages/cfd/package.json, packages/core/package.json, packages/hooks/package.json, packages/reports/package.json, packages/shared/package.json, packages/trader/package.json, packages/wallets/package.json
- Downgrade `@deriv-com/analytics` package to v1.5.9 to avoid `@rudderstack/analytics-js` version inconsistency between deriv-app and deriv-com apps.
=> [FEQ] george / FEQ-2462 / downgrade deriv-com/analytics package to v1.5.9

packages/core/src/sass/app/_common/layout/header.scss, packages/trader/src/AppV2/Components/BottomNav/bottom-nav.scss, packages/trader/src/AppV2/Components/ContractCard/contract-card.scss, packages/trader/src/AppV2/Components/Filter/filter.scss, packages/trader/src/AppV2/Components/Guide/guide.scss
Reset default button and link tags style in DTrader-V-2:
1) Account switcher
2) Bottom navigation
3) Time Filter (custom section)
4) Both open and closed Positions (card+buttons, that appear on swipe)
5) Guide (chips)
https://github.com/user-attachments/assets/84137718-211a-4821-9088-6d76489d3025
=> DTRA / Kate / DTRA-1533 / Reset default button and link tags' style in DTrader V-2

packages/appstore/src/components/modals/modal-manager.tsx
=> Amina/ fix: deriv-x password modal

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.25
=> Update deriv-charts to 2.1.25

packages/core/src/App/Components/Elements/LandscapeBlocker/landscape-blocker.tsx, packages/shared/src/utils/os/os_detect.ts
=> [DTRA] henry/dtra-1448/enable-landscape-blocker-dtrader

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.2.0
=> Update deriv-charts to 2.2.0

packages/trader/src/sass/app/modules/contract/digits.scss
Fixed the issue of digit contract tick count value getting truncated in responsive view
=> [DTRA]fix: fixed the issue of digit contract tick count value getting truncated in responsive view

.github/workflows/build_docker_passkey_image.yml
This workflow will get the docker tag name from inputs on workflow disaptch.
=> Ako/ get the tag name from inputs

packages/bot-web-ui/src/components/self-exclusion/__tests__/self-exclusion.spec.tsx, packages/bot-web-ui/src/components/self-exclusion/self-exclusion.jsx
test: Folder: bot-web-ui/src/components/self-exclusion
=> [BOT] maryia/BOT-1479/[Test Coverage] Folder: bot-web-ui/src/components/self-exclusion

packages/bot-web-ui/src/pages/tutorials/dbot-tours/__tests__/tour-content.spec.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/bot-builder-tour/__tests__/bot-builder-tour-desktop.spec.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/bot-builder-tour/__tests__/bot-builder-tour-handler.spec.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/bot-builder-tour/__tests__/bot-builder-tour-mobile.spec.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/bot-builder-tour/bot-builder-tour-desktop.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/common/__tests__/tour-button.spec.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/common/__tests__/tour-end-dialog.spec.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/common/__tests__/tour-start-dialog.spec.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/common/__tests__/tour-steps.spec.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/onboarding-tour/__tests__/onboarding-tour-desktop.spec.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/onboarding-tour/__tests__/onboarding-tour-handler.spec.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/onboarding-tour/__tests__/onboarding-tour-mobile.spec.tsx
- Added test coverage for all dbot tour files in tutorials folder including
- Onboarding Tour
- Bot Builder Tour
- Tour start and tour end dialog 
- Tour steps
- Tour content
=> [BOT] Farabi/bot-1499/dbot tours tutorials test coverage 

.github/workflows/build_docker_image.yml
=> Suisin/chore: update workflows to have environment of staging

packages/trader/src/AppV2/Hooks/__tests__/useActiveSymbols.spec.tsx, packages/trader/src/AppV2/Hooks/useActiveSymbols.ts
- to make 1 `active_symbols` API call for both of the **Vanillas** contract types (`VANILLALONGCALL`, `VANILLALONGPUT`) only once when `Vanillas` trade type is selected, instead of separate calls for each of them when we switch between `Call`/`Put` tabs:
```
{
active_symbols: 'brief',
contract_type: ['VANILLALONGCALL', 'VANILLALONGPUT'],
}
```
- to make 1 `active_symbols` API call for both of the **Turbos** contract types (`TURBOSLONG`, `TURBOSSHORT`) only once when `Turbos` trade type is selected, instead of separate calls for each of them when we switch between `Up`/`Down` tabs:
```
{
active_symbols: 'brief',
contract_type: ['TURBOSLONG', 'TURBOSSHORT'],
}
```
=> [DTRA] Maryia/DTRA-1557/feat: [V2] make 1 active_symbols API call for each pair of Vanillas and Turbos contract types

packages/trader/src/AppV2/Components/ContractCard/contract-cards-sections.tsx, packages/trader/src/AppV2/Components/ContractDetailsFooter/contract-details-footer.tsx, packages/trader/src/AppV2/Containers/ContractDetails/contract-details.tsx, packages/trader/src/AppV2/Containers/Positions/positions-content.tsx
This fix ensures that the currency information is consistently passed across closed positions and contract details, maintaining accuracy and coherence throughout the platform.
- Closed Positions: Update the logic to correctly pass and display the currency information in the closed positions section.
- Contract Details: Ensure that currency details are accurately reflected in the contract details, providing users with clear and consistent information.
By addressing this issue, users will experience improved accuracy and clarity in currency-related information, enhancing their overall interaction with closed positions and contract details.
=> Akmal / fix: pass currency across closed positions and contract details

packages/trader/src/AppV2/Components/TradeParameters/LastDigitPrediction/__tests__/last-digit-prediction.spec.tsx, packages/trader/src/AppV2/Components/TradeParameters/LastDigitPrediction/last-digit-prediction.scss, packages/trader/src/AppV2/Components/TradeParameters/LastDigitPrediction/last-digit-prediction.tsx, packages/trader/src/AppV2/Components/TradeParameters/LastDigitPrediction/last-digit-selector.tsx, packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.scss, packages/trader/src/AppV2/Containers/Trade/trade.tsx
- Removed Last digit prediction Stats from Even/Odd trade type according to the latest design;
- Aligned Parameters minimized buttons for stake and duration based on the design for Even/Odd;
=> DTRA / Kate / DTRA-1561 / Update layout for Even / Odd

packages/bot-skeleton/src/scratch/backward-compatibility.js, packages/bot-skeleton/src/scratch/blocks/Binary/Before Purchase/purchase.js
Fixing the getBlocksInStatement Error
The getBlocksInStatement error occurred because, in the Binary Bot system, we used to load the workspace when we uploaded an XML file. This approach allowed the system to handle blocks that were not present by ensuring they were properly loaded into the workspace. However, in the Deriv Bot system, we now directly load the XML file without initializing the workspace first. As a result, blocks that are referenced in the XML but are not present can lead to errors.
To fix this issue, you need to ensure that the system correctly handles blocks that are missing or not yet loaded when processing the XML. This might involve initializing the workspace or implementing logic to handle missing blocks gracefully.
=> Rupato/fix: getBlocksInStatement trackjs error

packages/bot-web-ui/src/pages/server-side-bot/bot-list/bot-list.tsx, packages/bot-web-ui/src/stores/server-side-bot-store.ts
We have noticed during the demo that whenever the server bot is running and user jumps from server bot tab to another tab and goes back to server tab, user is encountered with and error `Already Subscribed`.
To fix the error we have added a flag which will make sure that even after switching the tabs the bot do not try to subscribe again since the subscriptions are being handled at store leave.
=> [BOT] Sandeep/bot-2072/ssb-fix-already-subscribed

packages/bot-skeleton/src/scratch/hooks/workspace_svg.js, packages/bot-skeleton/src/scratch/utils/index.js, packages/bot-web-ui/src/stores/app-store.ts, packages/bot-web-ui/src/stores/toolbox-store.ts
- This PR addresses issues with the track JS that emerged after we changed the Blockly reference according to the import loader. As a result, registerOnAccountSwitch was executed on a switcher change, leading to an error where id was undefined. This occurred because we were not sending the correct block reference.
- Additionally, when resizing the workspace, the scrollbar was set to null, which caused an "undefined" error in the scrollbar set method.
=> [BOT]TrackJS/Rupato/BOT-1320/Fix-Cannot-Read-Properties-undefined-set

packages/wallets/src/constants/password.ts
Fix error message shown during password field validation for MT5 and DerivX accounts.
=> [WALL] [WEBREL] aum / WEBREL-3055 / wallet-password-validation-error-DerivX-MT5

packages/bot-web-ui/src/app/__tests__/app-content.spec.tsx, packages/bot-web-ui/src/app/app-content.jsx
- Listens to the account switch event to unsubscribe and resubscribe to the message event if the account is switched
- This should ensure the pending translations are resolved as soon as we get the proper response from the API
- Also added logic to not trying to subscribe if user is not logged in
=> fix: subscribe to api message after account switch

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.3.0
=> Update deriv-charts to 2.3.0

packages/trader/src/AppV2/Containers/Chart/trade-chart.tsx
- to disable vertical scroll on the chart outside Y-axis using the new `isVerticalScrollEnabled` SmartCharts prop added in this PR: https://github.com/deriv-com/SmartCharts/pull/1625.
The reason: We need the entire Trade page to be scrolled instead of the chart when users are scrolling vertically on it.
=> [DTRA] Maryia/DTRA-1559/feat: [V2] disable vertical scroll on the chart outside Y-axis

packages/appstore/webpack.config.js
Move webpack plugins to default plugins
=> Sergei / Move webpack plugins to default plugins

packages/cashier/src/components/cashier-container/real/real.scss, packages/cashier/src/components/cashier-container/real/real.tsx
Fixed the iframe height in withdrawal page for mobile devices to make the payment methods visible.
Before:
After:
=> [WALL] farrah/WALL-4530/fixed iframe height in withdrawal

packages/wallets/src/features/cashier/helpers/transaction-helpers.tsx
- Replaced `Localize` with `localize`
=> [WEBREL] Jim/WEBREL-3070/replace localize component with localize function

packages/bot-web-ui/src/analytics/__tests__/utils.spec.ts
- Test coverage for rudderstack files under analytics folder:
=> [BOT] Farabi/bot-1493/test coverage analytics folder

packages/appstore/src/components/cfds-listing/cfds-listing.scss, packages/cfd/src/sass/cfd.scss
- fix input width (tablet and mobile)
- fix footer button width and position (tablet)
- remove duplicated css
=> [CFDS] shontzu/CFDS-4266/new-password-input-field-is-misaligned-in-MT5-new-password-policy-modal

packages/bot-skeleton/src/scratch/dbot.js, packages/bot-skeleton/src/scratch/hooks/gesture.js
Changed the return type of the method to false after the block is dragged from the flyout. Because other events do not trigger unless this is set to false. The method returns true while the block is being dragged from the flyout.
=> Rupato/bot 2098/fix delete and zoom after blockly update

packages/appstore/src/components/account-transfer-modal/__tests__/account-transfer-modal.spec.tsx, packages/appstore/src/components/account-transfer-modal/account-transfer-modal.tsx, packages/cashier/src/pages/account-transfer/account-transfer-form/__tests__/account-transfer-form.spec.tsx, packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.tsx, packages/cfd/src/Containers/cfd-compare-accounts/cfd-compare-accounts.scss, packages/components/src/components/cfd-compare-accounts-carousel/cfd-compare-accounts-carousel.scss
- financial assessment link redirection is handled in `cashier` but not handled in `appstore`
- "Financial Assessment" redirection link on `tradershub` and `cashier` properly redirects to `accounts/financial-assessment`
- "OK" button dismisses the error
- navigating between `/cashier/transfer` and `/tradershub` does not cause modal or dialog popup issue
- added unit test for the dialog
- included a small css fix in cfd-compare-accounts
https://github.com/user-attachments/assets/ccf6e0dc-34d9-4add-99e8-023611ca95b4
=> [CFDS][TRAH] shontzu/CFDS-3959/Financial-Assessment-hyperlink-is-not-working-from-transfer-page

packages/p2p/src/stores/general-store.js
- Added setIsLoading(false) at the end of onMount function in general store as it sets it to true even after it was set to false due to how p2p renders when switching from BTC to USD.
https://github.com/user-attachments/assets/828e4f4d-dbda-4004-b766-2457340ea6f0
https://github.com/user-attachments/assets/54a18fa8-f4f2-40be-8e8d-623d84de5e06
=> [P2PS] / Ameerul / P2PS-3224 P2P page is stuck on loading when switching accounts

packages/wallets/src/features/cfd/flows/ClientVerification/ClientVerification.tsx
Fix issue when the client is going through POI/POA verification for MT5 account creation, if they drop the flow midway and then they come back to complete it, the flow restarts.
=> [WEBREL] aum/WEBREL-3083/wallet-poi-asked-again-after-creation-of-regulated-mt5-account

packages/bot-web-ui/package.json, packages/bot-web-ui/src/pages/bot-builder/quick-strategy/descriptions/strategy-description.tsx, packages/bot-web-ui/src/pages/tutorials/faq-content/index.tsx
refactor: Remove dangerouslySetInnerHTML
Description:
To provide tag content renderer and also to keep **some words in bold** we need to use `html-react-parser` library, for example, this kind of code:
```
const exampleHtml = `
<b>Bold text</b> и <i>italic text</i>
<p>Paragraph with<b>bold</b>text inside.</p>
`;
```
=> [BOT]maryia/BOT-2108/refactor: Remove dangerouslySetInnerHTML

packages/wallets/src/components/WalletListCardBalance/WalletListCardBalance.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsHeader.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsPlatformLabel.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsTitleIcon.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/InstrumentsIconWithLabel.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/CompareAccountsCard.spec.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/CompareAccountsDescription.spec.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/CompareAccountsHeader.spec.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/CompareAccountsPlatformLabel.spec.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/CompareAccountsScreen.spec.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/CompareAccountsTitleIcon.spec.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/InstrumentsIconWithLabel.spec.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/InstrumentsLabelHighlighted.spec.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/compareAccountsConfig.spec.ts, packages/wallets/src/features/cfd/screens/CompareAccounts/constants.tsx, packages/wallets/src/public/images/tradingInstruments.tsx
=> [WALL] Lubega / WALL-4750 /Compare accounts components unit tests

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.4.0
=> Update deriv-charts to 2.4.0

packages/wallets/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.scss
remove overriding css since PlatformStatusBadge is warning in default:
=> [WEBREL] [WALL] shontzu/WEBREL-3106/The-text-for-the-Verification-failed-is-yellow-in-staging

packages/appstore/src/components/modals/modal-manager.tsx, packages/core/src/App/Containers/Redirect/redirect.jsx, packages/core/src/Stores/ui-store.js
- Reset `MT5 Password` should not open `Investor Password` modal
- Reset `Investor Password` should not open `MT5 Password `modal
- Reset `MT5 Password` and `Investor Password` should be smooth in both appstore and account/password
- Navigating between `tradershub` and `account/passwords` should not cause modal issue (i.e. reopening the modal)
https://github.com/user-attachments/assets/9e14aa36-dcac-4359-9fef-9318ef9eb2e5
https://github.com/user-attachments/assets/727114be-820b-4c53-9712-110d18b3b372
=> [CFDS] CFDS-4278/shontzu/Overlapping-in-reset-investor-password-modal

packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/__tests__/lifetimeAccountLimitsBetweenWalletsMessageFn.spec.tsx, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/lifetimeAccountLimitsBetweenWalletsMessageFn.tsx
=> [WALL] Lubega / WALL-4410 / Remove fiat text from transfer messages

packages/wallets/src/features/cfd/screens/CreatePassword/CreatePassword.tsx, packages/wallets/src/features/cfd/screens/CreatePassword/__test__/CreatePassword.spec.tsx
- Create test case for `CreatePassword` component
- Change import `useDevice` from internal package to `deriv-com/ui`
=> Aizad/WALL-2948/Unit test for CreatePassword

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.5.0
=> Update deriv-charts to 2.5.0

packages/trader/src/Modules/SmartChart/Components/__tests__/toolbar-widgets.spec.tsx, packages/trader/src/Modules/SmartChart/Components/toolbar-widgets.tsx
- to show all 5 chart tools for minimized screen on a desktop device (unless minimized to responsive screen size) instead of hiding 3 of them like for a tablet device:
=> [DTRA] Maryia/DTRA-1410/fix: show all chart tools for minimized screen on a desktop device

packages/wallets/src/features/cfd/screens/ChangePassword/InvestorPassword/__tests__/MT5ChangeInvestorPasswordInputsScreen.spec.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/InvestorPassword/__tests__/MT5ChangeInvestorPasswordSavedScreen.spec.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/InvestorPassword/__tests__/MT5ChangeInvestorPasswordScreens.spec.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/MT5ChangePasswordScreens.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/__tests__/ChangePassword.spec.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/__tests__/MT5ChangePasswordScreens.spec.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/__tests__/TradingPlatformChangePasswordScreens.spec.tsx
- Added unit tests for:
`MT5ChangeInvestorPasswordInputsScreen`
`MT5ChangeInvestorPasswordSavedScreen`
`MT5ChangeInvestorPasswordScreens`
`ChangePassword`
`MT5ChangePasswordScreens`
`TradingPlatformChangePasswordScreens`
=> Jim/wall 2947/unit tests for change password

packages/wallets/src/features/cfd/screens/EnterPassword/__test__/EnterPassword.spec.tsx
- Implement unit test for EnterPassword component
=> [WALL] Aizad/WALL-2950/Unit test for EnterPassword

packages/bot-web-ui/src/pages/server-side-bot/add-bot/constants.ts, packages/bot-web-ui/src/pages/server-side-bot/add-bot/form-wrappers/useQsSubmitHandler.tsx, packages/bot-web-ui/src/pages/server-side-bot/add-bot/parts/__tests__/loss-threshold-warning.spec.tsx, packages/bot-web-ui/src/pages/server-side-bot/add-bot/parts/loss-threshold-warning-dialog.tsx, packages/bot-web-ui/src/stores/server-side-bot-store.ts
Fixed `Error shown upon running contract with Match/Differ purchase condition.`
"Error: Missing required contract parameters (last digit prediction for digit contracts). (code: ContractCreationFailure)" shown
NA
=> [BOT] sandeep/bot-2144/ server-bot fix: :fire: fixed digits contract bot error

packages/wallets/src/features/cfd/__tests__/CFDPlatformsList.spec.tsx, packages/wallets/src/features/cfd/__tests__/CFDPlatformsListEmptyState.spec.tsx, packages/wallets/src/features/cfd/__tests__/ResetMT5PasswordHandler.spec.tsx
Implement unit test for `CFDPlatformsList`, `CFDPlatformsListEmptyState` and `ResetMT5PasswordHandler` components.
=> [WALL] george / WALL-2951 / Unit test for CompareAccounts components

packages/appstore/src/components/containers/listing-container.scss
=> Lubega / TRAH-3965 / Trader's hub link underline fix

packages/wallets/src/components/Base/ModalStepWrapper/ModalStepWrapper.tsx
Fix the issue of double clicking `next` for triggering IDV submission. This problem happened because of `Footer` component created inside of the the `ModalStepWrapper` which would unpredictably break the state of footer upon re-renders.
=> [WALL] aum / WALL-4617 / idv-fix-double-click-issue-of-next-button

packages/trader/src/AppV2/Components/PurchaseButton/__tests__/purchase-button-content.spec.tsx, packages/trader/src/AppV2/Components/PurchaseButton/__tests__/purchase-button.spec.tsx, packages/trader/src/AppV2/Components/PurchaseButton/purchase-button-content.tsx, packages/trader/src/AppV2/Components/PurchaseButton/purchase-button.tsx, packages/trader/src/AppV2/Components/TradeParameters/AccumulatorsInformation/__tests__/accumulators-information.spec.tsx, packages/trader/src/AppV2/Components/TradeParameters/AccumulatorsInformation/accumulators-information.tsx, packages/trader/src/AppV2/Components/TradeParameters/BarrierInfo/__tests__/barrier-info.spec.tsx, packages/trader/src/AppV2/Components/TradeParameters/BarrierInfo/barrier-info.tsx, packages/trader/src/AppV2/Components/TradeParameters/PayoutPerPointInfo/payout-per-point-info.tsx
- Added disabling logic  for purchase button if index was turned off from BO + added text with error under the label.
- Added conditional rendering for PPP (Vanillas), Barrier (Turbos), Max payout (Acc): ff there is an error, we won't render them. In case if values haven't not loaded yet we would show Skeleton Loader.
=> DTRA / Kate / DTRA-1722 / Show error message on purchase button if index was turned off from BO

packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/__tests__/risk_management-picker.spec.tsx, packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/risk-management-picker.tsx, packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/risk-management.tsx, packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/take-profit-and-stop-loss-input.tsx
- Added prop (initial_tab_index), for controlling opened by default tab in Risk Management. If DC is active, then selected tab in the ActionSheet will be DC, not TP&SL and vise versa. 
- Fixed case when DC is active and user is trying to add TP, but we are showing a BE error below the input, preventing user from saving. 
- Add test cases 
https://github.com/user-attachments/assets/e5bcb155-e1ae-484c-a618-8021196310a3
=> DTRA-1810 / Kate / [DTrader-V2]: Risk Management bug fixes

packages/wallets/src/features/cfd/screens/VerificationFailed/__tests__/VerificationFailed.spec.tsx
This PR is for adding unit tests to the VerificationFailed modal shown when the client tries to add MT5 accounts and their POI/POA fails. The modal pops-up when they click on `Verification failed. Why?` .
=> [WALL] aum / WALL-2957 / unit-test-wallets-VerificationFailed

package-lock.json, package.json, packages/account/package.json, packages/api-v2/package.json, packages/appstore/package.json, packages/appstore/src/components/modals/setup-real-account-or-go-to-demo-modal/__tests__/setup-real-account-or-go-to-demo-modal-content.spec.tsx, packages/appstore/src/components/modals/setup-real-account-or-go-to-demo-modal/__tests__/setup-real-account-or-go-to-demo-modal.spec.tsx, packages/cashier/package.json, packages/cfd/package.json, packages/components/src/components/icon/icons.js, packages/core/package.json, packages/core/src/Stores/client-store.js, packages/core/src/Utils/Analytics/index.ts, packages/hooks/package.json, packages/p2p/package.json, packages/reports/package.json, packages/shared/package.json, packages/trader/package.json, packages/wallets/package.json
This is to ensure we initialise the rudderstack and growthbook at the same time. which will fix the Growthbook Experiments issue.
We also dont need to pass the country location from initialise function anymore as it will picked up automatically on analytics package.
=> Ako/ CRO-724/ Pass growthbook attributes on initialisation 

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.5.1
=> Update deriv-charts to 2.5.1

packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.tsx
=> [WALL] Lubega / WALL-4525 / Reorder demo tabs in cashier header

package-lock.json, packages/account/package.json, packages/core/package.json, packages/trader/package.json, packages/trader/src/AppV2/Components/PurchaseButton/purchase-button.scss, packages/trader/src/AppV2/Components/TradeParameters/__tests__/trade-parameters-container.spec.tsx, packages/trader/src/AppV2/Components/TradeParameters/trade-parameters-container.tsx, packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.scss, packages/trader/src/AppV2/Containers/Trade/trade.scss
While switching between trade types subtypes, layout was jumping. There are 2 identified reasons: 
1. Changes (index) in `Segmented control` in minimized trade params causing same changes in the `Segmented control` in normal trade params above. In Quill repository changing selected tab was happening with focusing. Using `.focus()` method usually initiate scrolling into view to the focusing element. Current issue was fixed by passing options:
```
(ref as RefObject<HTMLButtonElement>)?.current?.focus();
---->
(ref as RefObject<HTMLButtonElement>)?.current?.focus({ preventScroll: true});
```
[Link](https://github.com/deriv-com/quill-ui/pull/419/files#diff-1f2fd78138cf506fc4237030eaa3f32b633e0359e7ce0badf330811702e74f4e) to PR with fixes
2. Purchase button position: during switching `sticky` …
=> DTRA-1707 / Kate / [DTrader-V2]: Fix UX issue for Turbos,Vanillas,Higher/Lower and Touch/No Touch trade type

packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.tsx, packages/trader/src/AppV2/Containers/Trade/__tests__/trade.spec.tsx, packages/trader/src/AppV2/Containers/Trade/trade.tsx, packages/trader/src/AppV2/Utils/__tests__/layout-utils.spec.ts, packages/trader/src/AppV2/Utils/layout-utils.tsx
- Removed all chart height calculations. Created getChartHeight function, which take into consider 'stats' section for Accumulators trade type and additional information for expiration, deal cancellation, payout per point, allow equals and payout, based on passed arguments.
- Moved function for checking if trade_param is visible or not to layout-utils. Previously it was in trade-parameters.tsx, but I need to reuse it in another place too.
- Covered changes with tests.
=> DTRA-1855 / Kate / [DTrader-V2]: Change chart height calculations based on the latest design

packages/trader/src/AppV2/Containers/Trade/__tests__/trade.spec.tsx
it fix the hotfix for trade test cases
=> Ahmad/Trade Spec fix

packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/__tests__/contract_type.spec.tsx, packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/__tests__/duration_type.spec.tsx, packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/__tests__/symbol.spec.tsx, packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/__tests__/trade-type.spec.tsx, packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/trade-type.tsx
-  Test coverage increased for symbol.tsx, contract_type.tsx, trade_type.tsx and duration_type.tsx
=> [BOT] Farabi/bot-1488/test-coverage-for-qs-selects

packages/trader/src/AppV2/Components/TradeParameters/Barrier/barrier-description.tsx, packages/trader/src/AppV2/Components/TradeParameters/Barrier/barrier.scss, packages/trader/src/AppV2/Components/TradeParameters/Multiplier/multiplier.tsx, packages/trader/src/AppV2/Components/TradeParameters/Strike/__tests__/strike.spec.tsx, packages/trader/src/AppV2/Components/TradeParameters/Strike/strike.tsx
=> [DTRA-V2] fix: change actionsheet content

packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
=> [WALL] Lubega / WEBREL-3157 / MT5 enter password button size

packages/wallets/src/components/OptionsAndMultipliersListing/__test__/OptionsAndMultipliersListing.spec.tsx, packages/wallets/src/components/TradingAccountCard/TradingAccountCard.scss, packages/wallets/src/components/TradingAccountCard/TradingAccountCard.tsx, packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.tsx, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AvailableDxtradeAccountsList/__test__/AvailableDxtradeAccountsList.spec.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsScreen.tsx
=> [WALL] Lubega / WEBREL-3156 / Fix console errors

packages/core/src/App/Containers/Modals/deposit-now-or-later-modal/__test__/deposit-now-or-later-modal.spec.tsx, packages/core/src/App/Containers/Modals/deposit-now-or-later-modal/deposit-now-or-later-modal.tsx, packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx
This PR is to hide the one-time deposit flow for MF clients.
=> aum / WALL-4881 / remove-deposit-pop-up-for-mf-clients-real-account-creation

packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeDetailsItem/__test__/MT5TradeDetailsItem.spec.tsx, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeLink/__tests__/MT5DesktopRedirectOption.spec.tsx, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeLink/__tests__/MT5MobileRedirectOption.spec.tsx, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeLink/__tests__/MT5TradeLink.spec.tsx, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeLink/__tests__/constants.spec.ts, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.tsx, packages/wallets/src/features/cfd/screens/MT5TradeScreen/__test__/MT5TradeScreen.spec.tsx
=> [WALL] Lubega / WALL-2955 / MT5 trade screen unit test

packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/take-profit-and-stop-loss-input.tsx
- Added a fallback value. If there are no TP or SL , the value in the trade store  for `take_profit` & `stop_loss` is `undefined` (expected). When user was clicking on 'plus' button, math operation (+1) was performed with `undefined` and the error was thrown.
https://github.com/user-attachments/assets/606169d6-ba35-4c00-8fbd-a45ff3e10d51
=> DTRA-1891 / Kate / [DTrader-V2]: Bug - Plus stepper on risk management showing NaN

packages/core/src/App/Containers/Layout/header/dtrader-header-wallets.tsx
=> [WEBREL] george / WEBREL-3155 / Reports link on Dtrader page not appearing for wallet accounts

packages/bot-web-ui/src/stores/server-side-bot-store.ts
=> fix: server side pdf fix

packages/trader/src/AppV2/Components/RiskManagementItem/risk-management-item.tsx, packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/take-profit-and-stop-loss-input.tsx, packages/trader/src/AppV2/Components/TradeParameters/Stake/stake.tsx, packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.scss, packages/trader/src/AppV2/Containers/Positions/positions.scss
- Via css class  alignement in Quill components was changed the same way as it was done in production. The Issue was fixed for all InputFields with Steppers in V-2: Stake, TP&SL (trade page + contract details). The issue was fixed in our repp, not in quill, because the component contains a lot of additional elements inside, like left/right icons, left/right text and etc.
=> DTRA-1913 / Kate / [DTrader-V2] Stake field header and the amount is not aligned properly

packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.tsx
This feature modifies the trade parameters by swapping the positions of "Payout per Point" and "Stake" for improved clarity and user interaction.
- Parameter Swap: Switch the order of "Payout per Point" and "Stake" in the trade settings, making the layout more intuitive.
- User Interface Update: Adjust the user interface to reflect the new order, ensuring the change is seamlessly integrated.
- User Experience: Enhance the flow of selecting trade parameters, making it easier for users to configure their trades efficiently.
This update improves the usability of trade settings by presenting key parameters in a more logical and user-friendly order.
=> Akmal / feat: swap payout per point and stake in trade params

packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-wallet-address/deposit-crypto-wallet-address.scss
=> [WALL] Lubega / WALL-4890 / Deposit clipboard rtl alignment

packages/bot-skeleton/src/scratch/hooks/gesture.js
This is done because when this flag is set to true inside Blockly,
the handleMove function is called, which also triggers handleTouchMove
if the flag is false. This method wont be called everything will be handled in handleMove.
card: https://app.clickup.com/t/20696747/BOT-2103
=> Rupato/BOT-2103/fix: maximum call stack exceeded

packages/cashier/src/components/crypto-fiat-converter/crypto-fiat-converter.scss, packages/cashier/src/pages/withdrawal/withdrawal-crypto-form/withdrawal-crypto-form.scss
=> [WALL] Lubega / WALL-4909 / Withdrawal crypto form text alignment

packages/wallets/webpack.config.js
- adjust webpack config by adding `'react/jsx-runtime': true` to `externals`.
- pls refer [this](https://github.com/mui/material-ui/issues/34150#:~:text=After%20this%20change,though%20it%20shouldn%27t.) for more info
=> [WALL] george / WALL-4887 / Console error-Each child in a list should have a unique

packages/bot-web-ui/src/utils/__tests__/dom-observer.spec.ts, packages/bot-web-ui/src/utils/__tests__/download.spec.ts, packages/bot-web-ui/src/utils/__tests__/gtm.spec.ts, packages/bot-web-ui/src/utils/__tests__/xml-dom-quick-strategy.spec.ts, packages/bot-web-ui/src/utils/download.ts, packages/bot-web-ui/src/utils/xml-dom-quick-strategy.ts
=> fix: test cases

packages/trader/src/AppV2/Components/Guide/__tests__/guide-description-modal.spec.tsx, packages/trader/src/AppV2/Components/Guide/__tests__/guide.spec.tsx, packages/trader/src/AppV2/Components/Guide/guide-description-modal.tsx, packages/trader/src/AppV2/Components/Guide/guide.tsx
This feature ensures that only available trade types are displayed in the guide, improving the relevance and accuracy of the information provided.
1. Filter Trade Types: Implement logic to filter out unavailable trade types and display only those currently supported in the guide.
2. User Interface Update: Adjust the guide interface to reflect the updated list of available trade types, ensuring users see only valid options.
3. Enhanced User Experience: Provide a clearer and more focused guide by removing irrelevant trade types, improving usability and reducing confusion.
This feature improves the user experience by ensuring the guide displays only relevant trade types based on availability.
=> Akmal / feat: show only available trade types in guide

packages/trader/src/AppV2/Components/MarketSelector/__tests__/market-selector.spec.tsx, packages/trader/src/AppV2/Components/MarketSelector/market-selector.tsx
- Added loader for market selector for cases when symbol is not available for current trade type and it's changing it to the default one
- Replaced old skeleton with the new one from Quill
https://github.com/user-attachments/assets/c6abcee1-1f14-42d8-bff2-46f8feabc198
=> DTRA-2003 / Kate / [DTrader-V2] Blinking of 'Close' market

packages/shared/src/utils/routes/routes.ts
Fixed spelling error in the URL redirecting to the "Compare CFDs demo accounts" page (https://app.deriv.com/cfd-compare-acccounts).
=> Niloofar/ Fixed "cfd-compare-accounts" route typo

packages/bot-web-ui/src/pages/chart/chart.scss
- Make chart tab dropdown feed values visible for mobile devices
=> [BOT] Farabi/bot-2235/chart-feed-values-not-showing-on-mobile 

packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountSelection/TransferFormAccountSelection.scss
https://github.com/user-attachments/assets/361afcbe-34c0-4516-b290-037dcb1d9a26
https://github.com/user-attachments/assets/48132658-8360-4e47-9a26-f39db1d298aa
=> [WALL] Lubega / WALL-4938 / Responsive transfer menu overlap

packages/account/src/Sections/Profile/PhoneVerification/verification-link-expired-modal.tsx
make verification link expired modal to be not closable
=> [UPM-1349] Suisin/fix: make verification link expired modal to be not closable

packages/bot-web-ui/src/pages/dashboard/announcements/__tests__/announcement-dialog.spec.tsx, packages/bot-web-ui/src/pages/dashboard/announcements/__tests__/announcement.spec.tsx, packages/bot-web-ui/src/pages/dashboard/announcements/__tests__/announcements.spec.tsx, packages/bot-web-ui/src/pages/dashboard/announcements/announcement-dialog.tsx, packages/bot-web-ui/src/pages/dashboard/announcements/announcements.tsx, packages/bot-web-ui/src/pages/dashboard/announcements/config.tsx
- Open accumulators video directly in tutorials when clicking on learn more from the announcements from dashboard
https://github.com/user-attachments/assets/caa79da2-31fe-477e-bdd9-8d3f061a4e74
=> [BOT] Farabi/bot-2301/open-accumulator-video-directly

packages/wallets/src/features/cashier/flows/WalletWithdrawal/WalletWithdrawal.tsx, packages/wallets/src/features/cashier/modules/WithdrawalFiat/WithdrawalFiat.tsx, packages/wallets/src/features/cashier/modules/WithdrawalFiat/__tests__/WithdrawalFiat.spec.tsx
- fix the Resend Email CTA is not clickable on the expired withdrawal verification page for fiat withdrawal
https://github.com/user-attachments/assets/8f53db24-8242-4800-9fa1-6173b09c009e
=> [WALL] WALL-4761 / george / The Resend Email CTA is not clickable on the expired withdrawal verification page

packages/wallets/src/components/Base/WalletAlertMessage/WalletAlertMessage.scss, packages/wallets/src/components/Base/WalletAlertMessage/WalletAlertMessage.tsx, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/__tests__/lifetimeAccountLimitsBetweenWalletsMessageFn.spec.tsx, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/lifetimeAccountLimitsBetweenWalletsMessageFn.tsx
- If the user attempts to transfer an amount greater than the lifetime transfer limit, they should not be allowed to proceed. The transfer button should be disabled, and an error message related to the lifetime transfer limit should be displayed within the transfer form.
- Fix info icon color
=> [WALL] george /  WALL-4541 / For lifetime transfer limit errors, it displays a cumulative transfer error message.

packages/account/src/Components/terms-of-use/terms-of-use-messages.tsx
chore: MF tnc content update
In MF, during real account creation, the **Risk warning** section used to have an extra MF-specific content which is now being removed
=> [TRAH] shontzu/TRAH-4286/Remove-Trading-accounts-and-funds-section-in-terms-of-use-screen

packages/trader/src/AppV2/Components/TradeParameters/TradeTypeTabs/trade-type-tabs.tsx
This fix ensures that a default trade type is set when switching to Vanillas or Turbos, preventing an issue where buttons may disappear due to undefined trade types.
1. Default Trade Type Handling: Automatically set a default trade type when switching to Vanillas or Turbos to avoid issues with missing buttons caused by undefined selections.
2. User Interface Stability: Ensure the interface remains stable and all necessary buttons are visible when changing trade categories.
3. Improved User Experience: Prevent confusion or workflow interruptions by guaranteeing the default trade type is properly initialized, maintaining button visibility.
This fix enhances the user experience by preventing button disappearance when switching between Vanillas and Turbos, ensuring seamless trade …
=> Akmal / fix: set default trade type when switching to vanillas and turbos

packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoReceipt/WithdrawalCryptoReceipt.tsx, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoReceipt/__tests__/WithdrawalCryptoReceipt.spec.tsx, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/provider/WithdrawalCryptoProvider.tsx, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/types/types.ts
- fix formatting of received amount and transaction fee
**Normal withdrawal (without fee):**
**Priority withdrawal (with fee):**
=> [WALL] george / WALL-5011 / Difference in presenting withdraw amount on the same screen

packages/core/src/App/Components/Elements/LiveChat/live-chat.tsx, packages/core/src/App/Components/Elements/LiveChat/use-freshchat.ts, packages/core/src/Stores/client-store.js, packages/core/src/Utils/Analytics/index.ts
=> Freshchat feature flag params

packages/bot-web-ui/src/analytics/constants.ts, packages/bot-web-ui/src/analytics/rudderstack-common-events.ts, packages/bot-web-ui/src/analytics/rudderstack-dashboard.ts, packages/bot-web-ui/src/pages/dashboard/announcements/announcement-dialog.tsx, packages/bot-web-ui/src/pages/dashboard/announcements/announcements.tsx, packages/bot-web-ui/src/pages/dashboard/announcements/config.tsx
- Added rudderstack tracking events for announcement open
- Added rudderstack tracking events for announcement click
- Added rudderstack tracking events for announcement action
- Added rudderstack tracking events for announcement close
=> [BOT] Farabi/bot-2299/add-usage-tracking-for-announcements 

packages/account/src/Components/poi/status/limited/limited.tsx, packages/account/src/Configs/poi-error-config.tsx, packages/appstore/src/components/modals/wallets-migration-failed/wallets-migration-failed.tsx, packages/cashier/src/components/cashier-locked/cashier-locked-provider.tsx, packages/cashier/src/components/side-notes/side-note-faq/side-note-faq.tsx, packages/cashier/src/modules/cashier-onboarding/components/cashier-onboarding-side-notes/cashier-onboarding-side-note-fiat.tsx, packages/cashier/src/modules/deposit-fiat/deposit-fiat.tsx, packages/components/src/components/open-livechat-link/open-livechat-link.tsx, packages/core/src/App/Components/Elements/WhatsApp/whatsapp.tsx, packages/core/src/App/Containers/OneTimeDepositModal/one-time-deposit-modal-content.tsx, packages/core/src/App/Containers/RealAccountSignup/change-account-currency.jsx, packages/core/src/App/Containers/RealAccountSignup/signup-error-content.jsx, packages/core/src/App/Containers/Redirect/redirect.jsx, packages/core/src/Stores/client-store.js, packages/core/src/Stores/notification-store.js, packages/core/src/Utils/Analytics/index.ts, packages/hooks/src/useIsLiveChatWidgetAvailable.ts, packages/hooks/src/useLiveChat.ts, packages/p2p/src/components/dp2p-blocked/dp2p-blocked-description.tsx, packages/p2p/src/components/modal-manager/modals/ad-visibility-error-modal/ad-visibility-error-modal.tsx, packages/shared/src/utils/constants/phone-number-verification.tsx, packages/utils/src/__tests__/getCountry.spec.ts, packages/utils/src/getCountry.ts, packages/utils/src/index.ts, packages/wallets/src/features/accounts/modules/TaxInformation/components/NeedHelpMessage/NeedHelpMessage.tsx, packages/wallets/src/features/cashier/modules/DepositLocked/DepositLockedContent.tsx, packages/wallets/src/features/cashier/modules/WithdrawalLocked/WithdrawalLockedContent.tsx
=> CSIT-1559/Prince/add livechat widget call check

packages/account/src/Sections/Verification/Helpers/verification.js, packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-container.tsx
Added a condition to check for users with `poa_authenticated_with_idv_photo` status. This will require resubmission of POA in accounts page.
=> farrah/fix: added poa_authenticated_with_idv_photo

packages/p2p/src/pages/app.jsx
Redirects user to cashier, once user is redirected from p2p to standalone and then clicks on browser back button.
https://github.com/user-attachments/assets/0bb0c0c7-a572-4d89-982c-29a49a43316d
=> [P2PS]- Nada/P2PS-4248/fix: redirect to cashier from p2p

packages/trader/src/AppV2/Components/Guide/guide.tsx, packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.tsx, packages/trader/src/AppV2/Hooks/__tests__/useActiveSymbols.spec.tsx, packages/trader/src/AppV2/Hooks/useActiveSymbols.ts
- Added current language as a key to trade params and Guide button in order to rerender them on language change
- Added language as a dependency key to useActiveSymbols hook in order to refetch data (symbols are translated on BE side)
https://github.com/user-attachments/assets/3fa3c4b1-9b06-49aa-96f0-58ec880cb817
=> DTRA-1965 / Kate / [DTrader-V2] Trading Page translation issues

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.6.1
=> Update deriv-charts to 2.6.1

packages/bot-web-ui/src/app/__tests__/app-main.spec.tsx, packages/bot-web-ui/src/app/app-main.tsx, packages/bot-web-ui/src/public-path.ts
- Add **Survicate tracking script** to Deriv Bot so that we can conduct monthly **Customer Satisfaction Score (CSAT)** and **Customer Effort Score (CES) surveys** and collect more responses than **Hotjar** allows
- Survicate will help us gather CSAT and CES metrics with a higher response rate
- Survicate allows us to capture user metadata such as user’s **country of residence**, **account type**, and **account creation date**, which will help us personalize and segment survey results for more in-depth analysis.
=> Passed user attributes:
=> [BOT]maryia/feat: Implement Survicate Script for In-App Surveys on Deriv Bot

packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/multipliers-trade-description.tsx, packages/trader/src/AppV2/Components/Guide/guide.scss
Bug was to show the double quote in same lines as the word it self in multiplier guide description . It is fixed here
=> [DTRA-V2]/Ahmad/Guide Button quotation fix

packages/trader/src/AppV2/Components/RiskManagementItem/risk-management-item.tsx
This feature disallows saving when take profit (TP) and stop loss (SL) fields are set to their default values, ensuring users set meaningful values before saving.
1. Save Restriction: Prevent the save action if TP and SL fields are left at default values, prompting users to enter custom values.
2. Improved Validation: Add validation checks to detect default values in TP and SL fields, enhancing input accuracy.
3. Enhanced User Experience: Guide users toward setting actionable TP and SL values by disabling save on defaults, reducing potential errors.
This feature ensures users configure TP and SL values meaningfully before saving, improving trade management and accuracy.
=> Akmal / feat: disallow-save-on-default-for-tp-sl

packages/trader/src/AppV2/Components/RiskManagementItem/risk-management-item.tsx
This feature disallows saving when take profit (TP) and stop loss (SL) fields are set to their default values, ensuring users set meaningful values before saving.
1. Save Restriction: Prevent the save action if TP and SL fields are left at default values, prompting users to enter custom values.
2. Improved Validation: Add validation checks to detect default values in TP and SL fields, enhancing input accuracy.
3. Enhanced User Experience: Guide users toward setting actionable TP and SL values by disabling save on defaults, reducing potential errors.
This feature ensures users configure TP and SL values meaningfully before saving, improving trade management and accuracy.
=> Akmal / feat: disallow save on default for tp and sl

packages/trader/src/AppV2/Components/ServicesErrorSnackbar/__tests__/services-error-snackbar.spec.tsx, packages/trader/src/AppV2/Components/ServicesErrorSnackbar/services-error-snackbar.tsx
- Added BO error handler: it turns out, some that BO errors are coming not inside of the `services_error`, but inside of `proposal_info` for a proper trade type.  Such errors have no `error_field` and it is one of the main differences from trade parameters errors (because they have `error_field` such as `duration`, `stake` and etc. Another difference is that trade params errors arrays in `validation_errors` are empty.
- Added tests cases
https://github.com/user-attachments/assets/cb89bbcb-fe09-4c3a-ac5b-8e9bc7c7eb68
=> DTRA-2208 / Kate / [Dtrader-V2]There is no error message for disabled symbol from BO

packages/hooks/src/useSendOTPVerificationCode.tsx, packages/shared/src/utils/constants/phone-number-verification.tsx
Show 1 attempt left for users in error message on otp screens.
=> [UPM-1689] Suisin/chore: show 1 attempt left error message

packages/trader/src/AppV2/Components/DraggableList/__tests__/draggable-list.spec.tsx, packages/trader/src/AppV2/Components/DraggableList/draggable-list.scss, packages/trader/src/AppV2/Components/DraggableList/draggable-list.tsx, packages/trader/src/AppV2/Components/TradeTypeList/__tests__/trade-type-list.spec.jsx, packages/trader/src/AppV2/Components/TradeTypeList/trade-type-list.scss, packages/trader/src/AppV2/Components/TradeTypeList/trade-type-list.tsx, packages/trader/src/AppV2/Containers/Trade/trade-types.tsx, packages/trader/src/AppV2/Containers/Trade/trade.scss
In this PR, the "Customize" and "Done" buttons on the "View All Trade Types" and "Draggable Trade Type" pages are now fixed to the header for continuous accessibility. This update eliminates the need to scroll up to click "Done," enhancing usability.
=> [DTRA-V2]/Ahmad/Draggable Trade Type Scroll fix

packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/accumulator_take_profit.js
Remove disable enable feature on the accumulator take profit block.
=> fix: disable enable on accumulator block

packages/bot-skeleton/src/scratch/blockly.js, packages/bot-skeleton/src/scratch/utils/index.js
Fixed the blockly translations on the context menu
=> Rupato/BOT-2020/fix: blockly delete block translations

packages/core/build/config.js
Remove path related transformation from `copy-webpack-plugin` configrations
=> [WEBREL] Jim/WEBREL-3328/Unable to notice demo cashier icon

packages/cashier/src/components/cashier-container/virtual/virtual.tsx
Wrapped `toggleAccountsDialog` in another function, so that we don't pass in the `event object` from the `span`
https://github.com/user-attachments/assets/e5edf221-9939-4434-88a5-5fcc93fe90a9
https://github.com/user-attachments/assets/966294e6-56bd-4a36-adea-6a7192d8a642
=> [WEBREL] Jim/WEBREL-3330/Console errors on Cashier page

packages/trader/src/Stores/Modules/Trading/trade-store.ts
This fix ensures that the correct trade type is selected by default when the "allow equals" option is enabled, improving trade setup consistency.
1. Default Trade Selection: Automatically select the appropriate trade type by default when "allow equals" is activated, avoiding incorrect configurations.
2. Consistent Behavior: Maintain consistent behavior across trade types, ensuring the right defaults are applied based on settings.
3. User Experience: Simplify setup by auto-selecting compatible trade types, reducing user intervention and setup errors.
This fix enhances user experience and consistency by ensuring the correct trade type is pre-selected with "allow equals" enabled.
=> Akmal / fix: default to correct trade type when allow equals is enabled

packages/wallets/src/components/Base/WalletPasswordField/WalletPasswordField.tsx, packages/wallets/src/components/Base/WalletPasswordFieldLazy/WalletPasswordFieldLazy.tsx, packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx, packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModalFooters.tsx, packages/wallets/src/features/cfd/modals/MT5PasswordModal/__tests__/MT5PasswordModal.spec.tsx, packages/wallets/src/features/cfd/modals/MT5PasswordModal/__tests__/MT5PasswordModalFooters.spec.tsx, packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx, packages/wallets/src/features/cfd/screens/EnterPassword/__test__/EnterPassword.spec.tsx
https://github.com/user-attachments/assets/7a1313bc-f4d0-4a64-ae2c-758bdf59106f
https://github.com/user-attachments/assets/f2e8f7f1-88d6-4c8d-b9e3-1c1ca6956159
=> [WALL] Lubega / WALL-5049 / Enter existing mt5 password modal

packages/trader/src/AppV2/Components/TradeParameters/Stake/stake.tsx
Fix for stake error not to be shown when error in only one payout and also allow user to save
=> [DTRA]fix: stake error not to be shown when error in only one payout

packages/wallets/src/features/cashier/helpers/__tests__/helpers.spec.ts, packages/wallets/src/features/cashier/helpers/helpers.ts, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowAccountDetails/TransactionsCompletedRowAccountDetails.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowAccountDetails/__tests__/TransactionsCompletedRowAccountDetails.spec.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowTransferAccountDetails/TransactionsCompletedRowTransferAccountDetails.tsx, packages/wallets/src/features/cashier/modules/Transfer/hooks/useExtendedTransferAccountProperties.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useSortedTransferAccounts.ts
=> [WALL] Lubega / WALL-5148/ Transfer market type API value

packages/cashier/src/stores/general-store.ts, packages/cashier/src/stores/withdraw-store.ts
Added conditional to check if `client.currency !== 'XRP'`, so that `XRP` is redirected to the `else` branch where the `iframe url` will be set and the `withdrawal page` will therefore be displayed.
https://github.com/user-attachments/assets/7800e91e-af7a-4f0c-9ec3-a0e12adfec75
https://github.com/user-attachments/assets/dffc0fd0-6b2a-4b4f-ae25-2712217bbcd2
=> [WALL] Jim/WALL-5145/iframe is not loading for XRP

README.md, packages/wallets/src/features/cfd/screens/MT5ResetPasswordModal/__tests__/MT5ResetPasswordModal.spec.tsx
=> [WALL] Lubega / WALL-5155 / MT5ResetPaswordModal unit test

packages/trader/src/AppV2/Components/ContractDetailsHeader/contract-details-header.tsx, packages/trader/src/AppV2/Components/Filter/contract-type-filter.tsx
- Refactored ContractTypeFilter. Because of the way how label was inserted in Chip component in Quill, it created console error
https://github.com/user-attachments/assets/a262a39c-4213-490a-8e67-111612ddf32e
=> DTRA-1933 / Kate / Console error fix

packages/wallets/src/components/WalletsResetMT5Password/WalletSuccessResetMT5Password.tsx, packages/wallets/src/components/WalletsResetMT5Password/__test__/WalletSuccessResetMT5Password.spec.tsx
=> [WALL] Lubega / WALL-5053 / Change password success modal content update

packages/trader/src/Stores/Modules/Trading/trade-store.ts
- Added missing data when granularity is !== 0 
https://github.com/user-attachments/assets/b0c05be6-44e0-4e1e-9867-69ed9347cf48
=> GRWT-3232 / Kate / DTrader-V2] Market info price keeps on loading for other chart time interval

packages/core/src/Stores/client-store.js, packages/core/src/Stores/notification-store.js, packages/stores/src/mockStore.ts, packages/stores/types.ts
Display Trustpilot Review Notification based on `customer_review_eligible` status received in `get_account_status` API. This PR removes the existing business logic for displaying trustpilot notification.
=> chore: trustpilot changes

packages/bot-web-ui/src/stores/summary-card-store.ts
fix: Run panel animation result does not match contact result on win/loss
!we need the value of each transaction of the profit field relative to one contract, not just the first one
=> [BOT]maryia/GRWT-2382/fix: Run panel animation result does not match contact result on win/loss

packages/trader/src/AppV2/Components/TradeParameters/PayoutPerPoint/__tests__/payout-per-point.spec.tsx, packages/trader/src/AppV2/Components/TradeParameters/PayoutPerPoint/payout-per-point-wheel.tsx, packages/trader/src/AppV2/Components/TradeParameters/PayoutPerPoint/payout-per-point.tsx
- Refactored Payout per point component: remove all logic connected with rewriting local storage value, added useDtraderQuery for validation and new barrier value
https://github.com/user-attachments/assets/b44fe26b-dc91-4c37-9e84-eebdf68beb9b
=> GRWT-2668 / Kate / [DTrader-V2] Payout per point display value is not refreshing when changing market type

packages/wallets/src/features/cfd/modals/CTraderSuccessModal/CTraderSuccessModal.tsx, packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx, packages/wallets/src/features/cfd/modals/MT5AccountAdded/MT5AccountAdded.tsx, packages/wallets/src/features/cfd/modals/MT5AccountAdded/__tests__/MT5AccountAdded.spec.tsx
=> [WALL] Lubega / WALL-5054 / MT5 demo create success modal content

.github/workflows/coveralls.yml
-   Added a step to cache `node_modules` to speed up the workflow by avoiding repeated installations of dependencies.
-   Utilized the `actions/cache@v4` action to cache the  `node_modules` directory and any `node_modules` within  `packages/*`.
-   The cache key is generated using the hash of  `package-lock.json` and `packages/*/package.json` files to ensure the cache is updated when dependencies change.
-   Introduced a conditional step to install dependencies only if the cache is not hit `(cache-hit != 'true')`.
-   Removed trigger on master push because we already running tests in [Deriv App Release to Test environment Workflow](https://github.com/deriv-com/deriv-app/actions/runs/12112309040/workflow)
> Note: These changes aim to optimize the workflow by reducing the time spent on …
=> [FEQ] george / FEQ-2702 / Improve Coverall workflow time execution. Part 2. Adding caching npm packages

.github/workflows/coveralls.yml
Reverts deriv-com/deriv-app#17702
Reverting PR because cache does't restore from the master branch
=> Revert "[FEQ] george / FEQ-2702 / Improve Coverall workflow time execution. Part 2. Adding caching npm packages"

packages/appstore/src/components/cfds-listing/__tests__/index.spec.tsx, packages/appstore/src/components/cfds-listing/index.tsx, packages/core/src/Stores/client-store.js, packages/core/src/Stores/traders-hub-store.js, packages/stores/src/mockStore.ts, packages/stores/types.ts
fix cfd not showing for Spain users. 
https://github.com/user-attachments/assets/8ec5aa88-7f44-4f30-a4ce-021d134ba697
=> [TRAH4525] Suisin/chore: fix cfd not showing to spain users

packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx, packages/core/src/Stores/client-store.js
- Added is_authorize check in the useEffect before subscribing to p2p_settings as we have another authorize call in socket-general.js, and we didn't wait for that authorize check as well
=> [P2PS] / Ameerul / P2PS-4532 PA client gets logout when login

packages/core/src/App/Containers/Modals/tnc-status-update-modal/__test__/tnc-status-update-modal.spec.tsx, packages/core/src/App/Containers/Modals/tnc-status-update-modal/tnc-status-update-modal.tsx
Update content for TNC Acceptance period pop up modal
=> [WALL5207] Suisin/chore: update content for tnc modal

packages/bot-web-ui/src/components/draggable/draggable.tsx
This pull request includes changes to the `Draggable` component in the `packages/bot-web-ui` to improve its robustness by adding type checks for style properties.
Improvements to `Draggable` component:
* [`packages/bot-web-ui/src/components/draggable/draggable.tsx`](diffhunk://#diff-8cdde222cb106b9fdfb85fe2a755b530636b44636efe55c93feb8808054e2690L199-R204): Updated the styles to include type checks for `position.y`, `position.x`, and `zIndex` to ensure they are numbers, defaulting to 0 if not.
* [`packages/bot-web-ui/src/components/draggable/draggable.tsx`](diffhunk://#diff-8cdde222cb106b9fdfb85fe2a755b530636b44636efe55c93feb8808054e2690L209-R217): Added type checks for `size.width` and `size.height` to ensure they are numbers, defaulting to 0 if not.## Changes:
Please provide a summary …
=> fix: draggable component console css errors

packages/bot-web-ui/src/stores/transactions-store.ts
fix: Total Payout remains zero for multipliers and accumulator QS
=> [BOT]maryia/BOT-2462/fix: Total Payout remains zero for multipliers and accumulator QS

packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/accumulator_take_profit.js, packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/multiplier_stop_loss.js, packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/multiplier_take_profit.js, packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_accumulator.js, packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_multiplier.js, packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_tradeoptions.js, packages/bot-skeleton/src/scratch/utils/index.js, packages/bot-web-ui/src/constants/quick-strategies/d_alembert.ts, packages/bot-web-ui/src/stores/app-store.ts
Fixed currecy on trade definition block. by updating to the new blockly method called setValue
=> Rupato/BOT-2436/fix: updated blockly method

packages/core/src/App/Containers/Layout/app-contents.jsx
Adding network information (network type, network rtt, network downlink) on the page view event
=> chore: adding network information to page view event

packages/core/src/App/Containers/RootComponent/root-component.jsx, packages/wallets/src/App.tsx
- add popup notification functionality into wallets
=> [WALL] george / WALL-5235 / Notification Missing on Trader’s Hub Page for Wallet Accounts

packages/core/src/Stores/client-store.js
Removed tokens and account1 from localStorage once user is logged in. 
config.tokens and config.account1 was set in localStorage in the callback page so that it doesnt affect legacy code. So once client store retrieves the tokens and account1 and set the `client.accounts`, we dont need config.tokens and account1 anymore. Therefore removing it
=> Thisyahlen/fix: account switching

packages/trader/src/AppV2/Components/MarketCategory/market-category.tsx, packages/trader/src/AppV2/Components/OnboardingGuide/GuideForPages/onboarding-guide.tsx, packages/trader/src/AppV2/Components/OnboardingGuide/QuickAdjGuide/quick-adj-guide.tsx, packages/trader/src/AppV2/Components/OnboardingGuide/TradeParamsGuide/trade-params-guide.tsx, packages/trader/src/AppV2/Components/OnboardingGuide/TradeTypesSelectionGuide/trade-types-selection-guide.tsx, packages/trader/src/AppV2/Components/TradeParameters/trade-parameters-container.tsx, packages/trader/src/AppV2/Containers/Positions/positions.tsx, packages/trader/src/AppV2/Containers/Trade/trade-types.tsx
=> Akmal / fix: do not reset local storage at every guide step

packages/bot-web-ui/src/stores/run-panel-store.ts, packages/reports/src/Containers/open-positions.tsx
When clicking on the Reports link, the page redirects to reports/positions. However, the redirection does not carry the correct trade type. For example, if the user clicks on a Reports link associated with Accumulators, the page still redirects to reports/positions with the default trade type set to Options. This results in an error message stating "No contract positions", which can be misleading for the user.
Expected Behavior:
The redirection to reports/positions should reflect the context of the selected trade type. For instance:
If the user clicks on a Reports link for Accumulators, the reports/positions page should display Accumulators as the selected trade type and load relevant contract positions (if available).
Similarly, if the user clicks on a link associated with Multipliers, …
=> fix: improve report  push notification on click 

packages/bot-web-ui/src/app/app-main.tsx, packages/wallets/src/constants/constants.tsx
This pull request includes changes to the `packages/bot-web-ui` and `packages/wallets` to enhance redirection functionality and update content constants. The most important changes are listed below:
Redirection functionality:
* [`packages/bot-web-ui/src/app/app-main.tsx`](diffhunk://#diff-894a3e7a00fd927125af65c43ef2e9e28476a990e20e74d7b7fa4d56bf7c0ba4R15-R34): Added a mapping from origin to domain and implemented a redirection mechanism to ensure users are redirected to the appropriate `dbot` domain based on the current origin.
Content constants update:
* [`packages/wallets/src/constants/constants.tsx`](diffhunk://#diff-8fe136de4d9ebe1cb74f2601acd838491842646392046a9d5c64266c0fa60aa5R29): Added the `isExternal` property to the 'Deriv Bot' option to indicate that it is an external link.## …
=> chore: add redirection for staging and production bot to standalone bot

.github/workflows/coveralls.yml
The Coveralls workflow was being unnecessarily triggered on PR metadata edits (e.g., title or description changes) in the `deriv-app` project. This was caused by the inclusion of the edited event type in the workflow trigger for pull_request.
This PR removes the `edited` event type to ensure the workflow only runs for relevant events like new commits or PR creation, optimizing CI/CD resource usage.
=> [FEQ-2705] george / FEQ-2705 / Avoid Triggering Coveralls Workflow on PR Edits

packages/trader/src/AppV2/Components/DraggableList/draggable-list.scss, packages/trader/src/AppV2/Containers/Trade/trade-types-content.tsx, packages/trader/src/AppV2/Containers/Trade/trade-types.tsx, packages/trader/src/AppV2/Containers/Trade/trade.scss
**Reasons:**
TrackJS  `{"message":"Invariant failed"}` was caused by `react-beautiful-dnd` library, that is used for trade types drag-and-drop functionality. In all logs users were changing the order of trade types and get an error. In dev mode on localhost it's possible to reproduce it and get '`Droppable: unsupported nested scroll container detected.A Droppable can only have one scroll parent (which can be itself)Nested scroll containers are currently not supported.'`. 
**Solutions:**
There are 3 ways of solving the issue:
1. To find all parents containers with `overflow` css property equal to `scroll/auto` and make them not scrollable. According to the library documentation it's possible to have only 1 scrollable parent, so in my implementation it's `action-sheet--content …
=> DTRA-2471 / Kate / DND console error 

packages/trader/src/AppV2/Components/ServiceErrorSheet/__tests__/service-error-sheet.spec.tsx, packages/trader/src/AppV2/Components/ServiceErrorSheet/service-error-sheet.tsx, packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.tsx, packages/trader/src/AppV2/Containers/Trade/trade.tsx, packages/trader/src/AppV2/Utils/__tests__/layout-utils.spec.ts, packages/trader/src/AppV2/Utils/layout-utils.tsx
**Reason of the bug:**
after switching the language we are opening a new websocket connection in both cases (desktop + mobile). In desktop, in buy 'request' we are sending a new contract id from the second opened websocket connection, BUT in mobile we are STILL USING THE OLD ID.
`Solution:`
updating the store on language change. Additionally removed code of invalid proposal from conditions of showing the error modal.
https://github.com/user-attachments/assets/d844349d-4fa0-4af1-91a0-17e4aad5e514
=> GRWT-3938 / Kate / Insufficient balance error when changing language

packages/components/src/components/mobile-drawer/mobile-drawer.scss, packages/components/src/components/page-overlay/page-overlay.tsx, packages/core/src/App/Components/Layout/Header/toggle-menu-drawer-accounts-os.jsx, packages/core/src/App/Containers/Layout/app-contents.jsx, packages/core/src/App/Containers/Layout/header/dtrader-header.tsx, packages/core/src/App/Containers/Layout/header/header.tsx, packages/core/src/Stores/common-store.js, packages/core/src/sass/app/_common/layout/header.scss
=> TRAH-4715/show_account_settings_header_when_redirected_from_low_Code_to_account_settings_high_sode

packages/translations/src/i18next/i18next.ts
- If we are passing `an empty string` or `undefined` into `<Localize/>` component the application crashes. I've added the fallback into `hashTransKey` handler to avoid application crashing. `<Localize />` component is using `<Trans />` component under the hood from `react-i18next` library. And `hashTransKey` is running inside `<Trans />` component, so most likely the issue is inside this third-party library, because `defaults` prop in  `<Trans />` component receives an empty string, but in `hashTransKey` it becomes `undefined`. For now I've made a quick fix for this issue by adding fallback into `hashTransKey` handler.
https://github.com/user-attachments/assets/e949e27d-460a-41d0-b947-3d9ced7f7223
=> [WALL] george / WALL-5263 / TrackJS undefined is not an object (evaluating 'e.length') 

packages/core/src/App/AppContent.tsx, packages/core/src/App/app.jsx, packages/hooks/src/__tests__/useIsHubRedirectionEnabled.spec.tsx, packages/hooks/src/index.ts, packages/hooks/src/useIsHubRedirectionEnabled.ts
App ID should change to 61554 when `trigger_login_for_hub_country_list` feature flag value is true for certain countries
https://github.com/user-attachments/assets/52bc08c3-1afb-4d49-9495-e55a2d9dca0c
=> [TRAH-5056] Suisin/chore: change app ID based on FF value

packages/components/src/components/icon/icons.js, packages/trader/src/AppV2/Components/Carousel/carousel.tsx
Info content is missing in Carousal component for RTL layout
Before
After
=> Nijil / Info content is missing in Carousal component for RTL layout

packages/trader/src/AppV2/Components/TradeParameters/Duration/__tests__/duration_container.spec.tsx, packages/trader/src/AppV2/Components/TradeParameters/Duration/datepicker.tsx, packages/trader/src/Modules/Trading/Components/Form/DatePicker/__tests__/trading-date-picker.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/DatePicker/trading-date-picker.tsx, packages/trader/src/Stores/Modules/Trading/Helpers/contract-type.ts
This feature utilizes the `trading_days` property from the Trading Times API to deliver detailed trading availability.
1. Property Integration: Leverage the `trading_days` property to retrieve specific market open days.
2. Accurate Data: Provide users with precise information on trading availability for better planning.
3. Enhanced Functionality: Improve API usage by incorporating the `trading_days` property into trading tools.
This feature enhances the system by integrating detailed trading day information from the Trading Times API.
=> Akmal / feat: implement trading days API

packages/cfd/src/Containers/cfd-compare-accounts/cfd-compare-accounts.tsx, packages/cfd/src/Helpers/compare-accounts-config.ts, packages/wallets/src/features/cfd/screens/CompareAccounts/compareAccountsConfig.ts
- remove DerivedFX from compare account tables from wallets and legacy
- fix duplicated key error in mobile/tablet view
=> [WALL] george / WALL-5275 / Remove DerivedFX from compare account tables

package-lock.json, packages/cfd/package.json, packages/cfd/src/Containers/__tests__/dmt5-trade-modal.spec.tsx, packages/cfd/src/Containers/dmt5-trade-modal.tsx, packages/components/src/components/information-banner/index.tsx, packages/components/src/components/information-banner/information-banner.scss, packages/components/src/components/information-banner/information-banner.tsx, packages/components/src/index.ts, packages/wallets/src/components/InformationBanner/InformationBanner.scss, packages/wallets/src/components/InformationBanner/InformationBanner.tsx, packages/wallets/src/components/InformationBanner/index.tsx, packages/wallets/src/components/index.ts, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.tsx
Add Alpha generation guide to mt5 except for gold
Wallet account
Non-wallet account
=> [TRAH5305] Suisin/chore: add alpha generation guide to mt5 except gold

packages/api-v2/src/hooks/useIsHubRedirectionEnabled.ts, packages/core/src/App/AppContent.tsx, packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx, packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx, packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet.tsx, packages/core/src/App/Containers/RootComponent/root-component.jsx, packages/hooks/src/__tests__/useIsHubRedirectionEnabled.spec.tsx, packages/hooks/src/useIsHubRedirectionEnabled.ts, packages/wallets/src/components/ModalProvider/ModalProvider.tsx, packages/wallets/src/components/WalletsAddMoreCardBanner/__tests__/WalletsAddMoreCardBanner.spec.tsx, packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/__tests__/CryptoTransaction.spec.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/__tests__/TransactionsPendingRow.spec.tsx, packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/__tests__/AddedCTraderAccountsList.spec.tsx, packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/__tests__/AvailableCtraderAccountsList.spec.tsx, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/__test__/AddedDxtradeAccountsList.spec.tsx, packages/wallets/src/features/cfd/modals/CTraderSuccessModal/__tests__/CtraderSuccessModal.spec.tsx, packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/__tests__/DxtradeEnterPasswordModal.spec.tsx
Reverts deriv-com/deriv-app#18005
=> Revert "Lubega/TRAH: 5324/Change redirection for residence"

packages/core/src/Stores/client-store.js
=> Adrienne / Fixed an issue where during onboarding, SSO kicks in

packages/core/src/App/Containers/OSRedirect/os-redirect.tsx, packages/core/src/App/Containers/RootComponent/root-component.jsx, packages/core/src/Modules/Callback/CallbackPage.tsx
=> Adrienne / Store redirect metadata for traders hub from os-redirect

packages/trader/src/AppV2/Components/TradeParameters/Duration/day.tsx
Fixed the below issue. the time should be 23:59 for future [dates](url)
=> fix: timer picker field should display appropriate value for future dates

packages/cfd/src/Helpers/constants.ts
Add localize function to make sure translation happen in CTrader Important Notes
=> Suisin/chore: add localize function for important notes strings

packages/cfd/src/Containers/ctrader-derivx-trade-modal.tsx, packages/cfd/src/Helpers/constants.ts
=> Suisin/ chore: make staging translation issue pr towards master

packages/appstore/src/components/cfds-listing-logged-out/cfds-listing-logged-out.tsx, packages/cfd/src/Containers/cfd-compare-accounts/__tests__/cfd-compare-accounts-title-icon.spec.tsx, packages/cfd/src/Containers/cfd-compare-accounts/cfd-compare-accounts-title-icon.tsx, packages/cfd/src/Helpers/compare-accounts-config.ts, packages/core/src/Stores/traders-hub-store.js, packages/wallets/src/features/cfd/constants.tsx
EU no longer limited to financial products since trading team insisted DIEL financial should have synthetic instrument too
**Before:**
in EU, MT5 is shown as MT5 `CFDs` with yellow variant icon
**After:**
in EU, MT5 `CFDs`should just show MT5 `Standard` with the regular blue icon
**Note to dev:**
BE deployed in qa137 
use `es` `mf` account for EU tradershub
use `cz` `mfw` for EU wallets
https://github.com/user-attachments/assets/81cb4c73-fc82-41f1-a8c7-bd1fe904fb39
https://github.com/user-attachments/assets/708391aa-2b81-4c04-9fc8-35c464e75b6b
=> [TRAH] shontzu/TRAH-5356/fe-implementation-api-group-cleanup

packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.tsx
=> fix: account transfer form's status text

packages/cfd/src/Stores/Modules/CFD/cfd-store.js
set `transfer_to` after real cfd account creation 
[card](https://app.clickup.com/t/86c26qa09)
https://github.com/user-attachments/assets/598a4394-45f1-45d4-a682-61d47b5c9205
This is applicable to mt5, ctrader, and dxtrade
=> Shontzu/TRAH/Unexpected Behaviour on Transfer funds modal after cfd account creation

packages/api-v2/src/AuthProvider.tsx, packages/api/src/APIProvider.tsx, packages/api/src/hooks/useAuthorize.ts, packages/core/src/App/Components/Layout/Header/dtrader-v2/account-switcher-dtrader-v2.tsx, packages/core/src/App/Components/Layout/Header/wallets/account-info-wallets.tsx, packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-item.tsx, packages/core/src/App/Containers/Redirect/redirect.jsx, packages/core/src/App/app.jsx, packages/core/src/Stores/client-store.js, packages/shared/src/utils/config/config.ts, packages/utils/src/getActiveLoginIDFromLocalStorage.ts, packages/wallets/src/hooks/__tests__/useWalletAccountSwitcher.spec.tsx, packages/wallets/src/hooks/useSyncLocalStorageClientAccounts.ts, packages/wallets/src/hooks/useWalletAccountSwitcher.ts
Account switching for dtrader redirection in url param
https://github.com/user-attachments/assets/c493cef4-3d8c-4a57-bb48-bfa4a098670b
=> Suisin/chore: implement session account switching in dtrader and tradershub

packages/core/src/App/Containers/Redirect/redirect.jsx, packages/core/src/App/app.jsx, packages/core/src/Modules/Callback/CallbackPage.tsx, packages/core/src/Stores/client-store.js
Dtrader page is not showing issue
=> Suisin/chore: fix blank screen issue

packages/core/src/App/AppContent.tsx, packages/core/src/App/Containers/RootComponent/root-component.jsx, packages/hooks/src/__tests__/useSilentLoginAndLogout.spec.tsx, packages/hooks/src/useSilentLoginAndLogout.ts
=> Adrienne / Fix SSO triggering multiple times

packages/trader/src/Modules/Trading/Containers/trade.tsx
Clear session storage once we land on Dtrader page so that OIDC won't take the session storage value 
=> Suisin/chore: fix redirection to dtrader everytime landing on home page after coming from smart trader

packages/core/src/Stores/Helpers/redirectToOutSystems.ts, packages/core/src/Stores/ui-store.js
This PR introduces a feature flag that controls the redirection for real account creation. When the flag is enabled, all redirections will route to the Outsystems low-code real account creation page. If the flag is disabled, the redirection will open the real account creation modal in the high-code environment. This allows for easier testing and flexibility in transitioning between the two account creation methods.
=> Niloofar / Add Feature Flag for Redirecting to Low-Code or High-Code Real Account Creation

packages/components/src/components/contract-card/contract-card-items/__tests__/tick-counter-bar.spec.tsx, packages/components/src/components/contract-card/contract-card-items/contract-card-header.tsx, packages/components/src/components/contract-card/contract-card-items/tick-counter-bar.tsx, packages/trader/src/App/Components/Elements/ContractAudit/contract-details.tsx, packages/trader/src/AppV2/Components/ContractCard/__tests__/contract-card-status-timer.spec.tsx, packages/trader/src/AppV2/Components/ContractCard/__tests__/contract-card.spec.tsx, packages/trader/src/AppV2/Components/ContractCard/contract-card-status-timer.tsx, packages/trader/src/AppV2/Hooks/__tests__/useOrderDetails.spec.tsx, packages/trader/src/AppV2/Hooks/useOrderDetails.ts
Remove max ticks from contract card in open positions and contract details page in DTrader
=> Nijil / GRWT-5310 / Remove max ticks from contract card in open positions and contract details page in DTrader

packages/core/src/Stores/ui-store.js, packages/wallets/src/helpers/urls.ts
This PR removes the feature flags `dynamic_fa_os_real_account` and `trigger_os_real_account_creation` from the app.deriv.com codebase. These flags are no longer needed as the associated feature for real account creation is now fully integrated and no longer requires conditional activation. This cleanup simplifies the codebase and ensures that the real account creation flow is always enabled for all users.
=> Niloofar/TRAH-5939/Remove Feature Flags for Real Account Creation in app.deriv.com

packages/core/src/App/Containers/Redirect/redirect.jsx, packages/core/src/App/app.jsx
instead of using landing_company to check is_virtual, directly use is_virtual to check it. Added is virtual check as well in dtrader redirect.
https://github.com/user-attachments/assets/cf2267cd-ec98-43c4-972b-8f62a33f230f
=> Suisin/chore: check if account is_virtual

packages/core/src/sass/app/_common/components/account-switcher.scss
Increased width of the loader in DTrader account switcher in order to position it properly and hide data below it
=> GRWT-5438 / Kate / Positioned Account loader for DTrader properly

packages/trader/src/sass/app/modules/trading.scss
Add css fix for selective ignoring rtl
https://github.com/user-attachments/assets/7b8df391-5695-456d-9848-09495b0627ea
=> GRWT-5431 / Kate / [DTrader] Text cursor is behind the currency for Take profit, Stoploss in Arabic language

packages/trader/src/AppV2/Components/TradeParameters/MultipliersDealCancellationInfo/__tests__/multipliers-deal-cancellation-info.spec.tsx, packages/trader/src/AppV2/Components/TradeParameters/MultipliersDealCancellationInfo/multipliers-deal-cancellation-info.scss, packages/trader/src/AppV2/Components/TradeParameters/MultipliersDealCancellationInfo/multipliers-deal-cancellation-info.tsx, packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.scss, packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.tsx
This PR addresses an issue with the display of Deal Cancellation fees in Multiplier contracts. Previously, in the mobile/responsive view, only the UP contract's cancellation fee was displayed, while the desktop view correctly showed both UP and DOWN fees. This inconsistency affected the Stake value displayed on the purchase buttons.
Changes
Updated MultipliersDealCancellationInfo component:
-Modified the component to display both UP and DOWN cancellation fees in a horizontal layout
-Ensured the "DC Fee" label and value are displayed on the same line
-Maintained proper spacing and alignment between elements
Updated CSS styling:
- Added styles for the horizontal layout with proper spacing
- Created fee-row class to display label and value side by side
- Added appropriate padding and margins …
=> Akmal / fix: enhance multipliers deal cancellation info layout and visibility handling

packages/trader/src/AppV2/Components/TradeParameters/Duration/duration.tsx, packages/trader/src/AppV2/Utils/__tests__/trade-param-utils.spec.tsx, packages/trader/src/AppV2/Utils/trade-params-utils.tsx
Fix ticks naming. For plural  - ticks, for single - tick.
Refactored utility functions in packages/trader/src/AppV2/Utils/trade-params-utils.tsx.
Refactored tests.
NOTE: For the duration field, changed 1 ticks to 1 tick, 1 minutes to 1 minute, 1 hours to 1 hour.
=> GRWT-5433 / Kate / Inconsistency of 'ticks' and 'tick' for Tick duration

packages/core/src/App/Containers/RootComponent/root-component.jsx
Clear local storage in safari browser since iFrame for front Channel is not available in Safari
Chrome:
https://github.com/user-attachments/assets/d6d93a72-a014-482c-a751-d60db38732f8
Safari:
https://github.com/user-attachments/assets/9e45514a-8277-4f0f-8c7b-9ae8f2c7d61c
=> [FEWP465] Suisin/chore: add checks for safari browser only we clear local storage

packages/core/src/App/Containers/RealAccountSignup/currency-selector.scss
- Made small CSS changes to account currency popover tooltip icon.
**Before:**
**After**
=> Aizad/TRAH-5988/[Onboarding] (i) icon overlapped with the selected currency square box line

packages/core/src/Stores/traders-hub-store.js
- update `shortcode_and_region` badge to just `shortcode`
- ❌ `SVG - Asia`  `SVG - Africa`  `SVG - Europe`  `Vanuatu`
- ✅ `SVG`  `SVG`  `SVG`  `Vanuatu`
- Check in Tradershub dashboard
- Check in Transfers modal
Before:
After:
=> [CFDS] shontzu/CFDS-3449/shortcode-and-region-label

packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.scss
Issue: Input amount was overlapping the currency (icon prop of input field) due to overridden text align.
Fix: Change text-align from "left" to "start" which automatically switches input alignment based on RTL of browser.
https://github.com/user-attachments/assets/a5d4366a-9575-428b-a0a1-2969892648e1
=> Aum / TRAH-6000 / Fix cashier transfer field

packages/shared/src/utils/date/__tests__/date-time.spec.ts, packages/shared/src/utils/date/date-time.ts, packages/trader/src/AppV2/Components/TradeParameters/Duration/day.tsx, packages/trader/src/AppV2/Components/TradeParameters/Duration/duration.tsx, packages/trader/src/Modules/Trading/Components/Form/DatePicker/trading-date-picker.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Duration/advanced-duration.tsx
- Added a default value for end date equal to tomorrow (current date + 1 day) for both desktop + mobile
- Created helper function
- Expanded test cases
Recommend to refactor mobile duration component
https://github.com/user-attachments/assets/ec9b558c-d940-4628-a3e1-172976ddc4ee
https://github.com/user-attachments/assets/bc7919e7-2be2-4c86-a038-e375e773a501
=> GRWT-5552 / Kate / [DTrader] End time showing wrongly while user switch from Duration to End time for Rise/Fall

packages/trader/src/AppV2/Containers/Trade/trade.scss
The task was removed all background colors from chip with trade types except white&black in order not to confuse users with light-grey chip highlight on hover/active. Because original styles coming from quill I was forced to use !important
https://github.com/user-attachments/assets/751cd2c0-a1f9-4cfe-83c8-e85a9870c028
=> GRWT-5444 / Kate / Overwrite chip style

packages/core/src/Modules/Callback/CallbackPage.tsx
Replace state before redirecting to the page, so that the browser will not redirect back to the callback page
https://github.com/user-attachments/assets/049f517b-722f-4d87-b534-649bf98457e9
=> Suisin/chore: replace window state before redirecting because safari issue

packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/__tests__/useTransferMessages.spec.tsx, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/useTransferMessages.tsx, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/index.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/minimumTransferLimitMessageFn.tsx
Issue: The minimum transfer message does not appear when the user enters the amount for transfer. The message only appears after clicking the transfer button and receiving an error.
Expected Behavior: The minimum transfer message should appear as soon as the user enters an amount below the minimum transfer limit, not only after clicking the transfer button.
=> Nijil / TRAH-5968 / Min transfer limit message on user input

packages/appstore/src/components/modals/modal-manager.tsx
**Issue:** Wallet intro modal shows up when user tries to open the verification link for changing email in a different (logged-out) session.
**Fix:** Don't show the wallet intro modal _if_ the URL contains _any action params_.
=> Aum / TRAH-6056 / fix to hide wallet intro modal during email change

packages/core/src/Constants/currency.js, packages/core/src/Stores/client-store.js
The Thether Omni USDT is still coming in Authorize call, but with disabled flag. As I want to preserve the logic for disabling accounts, I added a filtration to exclude 'UST' if it's disabled with a comment. Haven't removed icon in case if it will be enabled in future.
Account will be removed from DTrader and DBot.
In SmartTrader (production) account is not visible, hence haven't change it.
=> GRWT-5624 / Kate / Removed disabled account from account switcher

packages/core/src/App/Containers/Redirect/redirect.jsx, packages/shared/src/utils/config/platform-config.ts
=> Lubega / TRAH-6172 / Ctrader account transfer redirect

packages/trader/src/AppV2/Components/RiskManagementItem/risk-management-item.tsx, packages/trader/src/AppV2/Components/TradeParameters/Barrier/barrier-input.tsx, packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/take-profit-and-stop-loss-input.tsx, packages/trader/src/AppV2/Components/TradeParameters/Stake/stake-input.tsx
The issue happens not only in barrier input, but in other Quill inputs too (Stake, Take profit, Stop Loss). The issue is in prop 'shouldRound' that we are passing to text input.
When value ends with '00', Quill rounds it and cut all numbers, except two first.
E.g. 300,00 -> 30
127675,00 -> 12
Ideally, fix should be applied to Quill repository, but because of the hight priority of the card, the fact that we don't actually need rounding in mobile (as we are not using it in desktop, stick to consistency) and taht design team is building new quill components, we can fix it on our side (deriv-app). Now, if value ends with '00' we are not rounding/cutting it. Instead we are handling it the same way as in desktop (consistency) and allowing user to enter it. Fixed was applied to Barrier, Stake, …
=> GRWT-5645 / Kate / Remove Quill component rounding issues

packages/trader/src/App/Components/Elements/PositionsDrawer/__tests__/positions-drawer.spec.tsx, packages/trader/src/App/Components/Elements/PositionsDrawer/positions-drawer.tsx, packages/trader/src/sass/app/_common/drawer/positions-drawer.scss
fix: added total p/l functionality for desktop app
Removed go to reports button and added total p/l block
P/L calculation set on current active trades
Updated Positions drawer to only show active trades
Removed filtering on positions drawer for current market (all active trades will be displayed)
Total P/L block to be removed when no trades are active
=> Moiz-GRWT-5559-[DTrader] Implement P/L of all positions in Recent Positions drawer

packages/trader/src/App/Components/Elements/EmptyPortfolioMessage/__tests__/empty-portfolio-message.spec.tsx, packages/trader/src/App/Components/Elements/EmptyPortfolioMessage/empty-portfolio-message.tsx, packages/trader/src/App/Components/Elements/PositionsDrawer/positions-drawer.tsx, packages/trader/src/App/Components/Elements/TogglePositions/__tests__/toggle-positions-mobile.spec.tsx
Updated logic to display all contracts instead of filtering for active contracts and added a callback to trigger closing of the trade card once trade has been completed after an 8 second delay
Also resolved issue where adding new trades of different markets would trigger a re-render and cause previous trades to show up due to memory leak
https://github.com/user-attachments/assets/28560296-3d06-4809-8424-cfe06decdab5
=> Moiz-WEBREL-4229-Closed contract card is not displays in Open position drawer

packages/appstore/src/components/modals/verification-docs-list-modal/ListItem.tsx, packages/appstore/src/components/modals/verification-docs-list-modal/__tests__/Listitem.spec.tsx, packages/wallets/src/components/ClientVerificationModal/components/DocumentsList/DocumentsList.tsx, packages/wallets/src/components/ClientVerificationModal/components/DocumentsList/__tests__/DocumentsList.spec.tsx
Before - While creating a CFD account that requires POI/POA verification, clicking on POI/POA first redirects to the high-code account settings page before opening the low-code account settings page, causing an inconsistent redirection flow.
Fix - Redirect to OS or account settings page based on feature flag value when creating a CFD account that requires POI/POA verification.
=> Nijil/ TRAH-5819 / Redirect to OS or account settings page based on feature flag

packages/api-v2/src/hooks/useIsHubRedirectionEnabled.ts
- Replaced hub_enabled_country_list from Growthbook with Firebase Remote Config (useRemoteConfig).
- Fixed the incorrect redirection when navigating from DTrader to the Wallet page.
=> Niloofar/86c3jcquh/Replace hub_enabled_country_list with Firebase Config

packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- replace `routes.traders_hub` with `handleTradershubRedirect` on click redirect for Tradershub mobile menu
https://github.com/user-attachments/assets/02bafe3f-180c-4bd6-93d2-620a5c9a71c9
=> Aizad/TRAH-6600/Wallet User Redirected to Traders Hub Highcode Instead of Lowcode in Mobile

packages/core/src/App/Components/Layout/Footer/account-limits.jsx, packages/hooks/src/__tests__/useAccountSettingsRedirect.spec.ts, packages/hooks/src/useAccountSettingsRedirect.ts
Clicking on the "Account Limits" link in the Deriv App footer should redirect the user to the new low-code Account Limits page for hub enabled countries.
=> Nijil / Account limits footer icon redirection

packages/hooks/src/__tests__/useAccountSettingsRedirect.spec.ts, packages/hooks/src/useAccountSettingsRedirect.ts
Clicking on the Account Limits icon ( bottom right next to language icon ) in the Trader's Hub page for non migrated/non hub enabled users redirects to the Account Limits page instead of Personal Details page.
=> Nijil / Fix account limits redirection for non migrated/non hub enabled countries

packages/trader/src/AppV2/Components/SymbolNotFound/symbol-not-found.tsx
This pull request updates the `SymbolNotFound` component to improve localization handling by switching from the `Localize` component to the `localize` function for dynamic text.
Localization improvements:
* [`packages/trader/src/AppV2/Components/SymbolNotFound/symbol-not-found.tsx`](diffhunk://#diff-1f50a19cb9d8748b2b22fba707fae7c61d359040d4969e9fbc08127a13c173fcL2-R13): Replaced the `Localize` component with the `localize` function for the dynamic "No results for {{searchTerm}}" message. This allows for additional options, such as disabling HTML escaping via `interpolation: { escapeValue: false }`.
=> [DTrader] Farabi/grwt-6239/random-strings-on-market-search

packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
This pull request refactors the `appendAccountParamToUrl` function in `platform-dropdown.jsx` to improve readability and extend its functionality by adding support for a `symbol` parameter from session storage.
* Refactored the `appendAccountParamToUrl` function to use a single `url` variable for constructing the modified URL, improving readability and maintainability.
* Added functionality to append a `symbol` parameter to the URL if it exists in session storage under the `trade_store` key. Included error handling to ensure the function continues gracefully if JSON parsing fails.
=> [DTrader] Farabi/grwt-6171/market-changes-on-app-switching

packages/appstore/src/components/banners/traders-hub-banners/traders-hub-banners.tsx
don't show the deposit banner if the wallet migration banner is active
=> Fix deposit and wallet banner clash

packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-flow.tsx
Due to a GrowthBook feature flag load issue, some clients are not being properly redirected to the Outsystems POA flow. Removing the feature flag to terminate Deriv Verify traffic
=> Hirad/RSKT-3429/Removed the redirect_to_poa feature flag

packages/cfd/src/Containers/account-nakala-modal/account-nakala-modal.scss, packages/cfd/src/Containers/account-nakala-modal/account-nakala-modal.tsx
This pull request introduces a minor UI improvement to the `CFDDerivNakalaLinkAccount` modal by updating the visual styling of the steps indicator. The main change is the addition of a new CSS class that adds a line before the steps, enhancing the user interface.
**UI Enhancement:**
* Added the `cfd-nakala-modal__steps--with-line` CSS class to the steps container in `account-nakala-modal.tsx` to visually separate the steps with a line.
* Defined the new `cfd-nakala-modal__steps--with-line` class in the SCSS file to implement the line styling using the `:before` pseudo-element.
=> fix: remove extra line on get started modal

.github/workflows/coveralls.yml, .github/workflows/release_production.yml
This branch addresses permission issues in GitHub Actions workflows:
- Added missing permissions for Slack notification jobs in production workflow
- Added missing permissions for Coveralls Finished job
These fixes ensure proper execution of CI/CD workflows by explicitly defining required permissions for GitHub Actions jobs.
=> DSEC-63673: Fix GitHub Actions workflow permission issues

packages/cfd/src/init-store.js, packages/core/src/App/initStore.js, packages/trader/src/App/init-store.ts
- configure MobX to isolate global state in core, trader, and cfd modules
=> fix: isolate MobX global state
