- .github/workflows/release_production.yml
This replaces the slack notification logic with the built in github action `if`.
> chore: fix slack notification sending logic

- package-lock.json
- packages/account-v2/package.json
- packages/account-v2/src/modules/src/AddressFields/__tests__/validations.spec.ts
- packages/account-v2/src/modules/src/AddressFields/validations.ts
- packages/cashier-v2/package.json
- packages/cfd/package.json
- packages/core/package.json
- packages/p2p-v2/package.json
- packages/p2p/package.json
- packages/trader/package.json
- packages/tradershub/package.json
- packages/wallets/package.json
Refactoring the regex validations to use validation constants from @deriv-com/utils
> Amina/ fix: FEQ_2005_refactor_deprecated_validaton_regex

- packages/wallets/src/components/SkeletonLoader/WalletsCarouselLoader/WalletsCarouselLoader.scss
- packages/wallets/src/components/WalletsCarousel/WalletsCarousel.scss
- packages/wallets/src/components/WalletsCarousel/WalletsCarousel.tsx
- packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.scss
- Added "Traders Hub" ontop of Wallet Carousel on Mobile.
> Aizad/wall 3768/adding tradershub word in mobile

- packages/wallets/src/components/WalletTourGuide/DesktopSteps.tsx
https://github.com/binary-com/deriv-app/assets/142860499/7ef181f5-7767-4c53-bf19-2210ced86444
https://github.com/binary-com/deriv-app/assets/142860499/9e25b5ad-5c2a-407c-a4c6-fdefc466b510
> [WALL] Lubega / WALL-3645 / Wallet onboarding walkthrough missing steps

- packages/wallets/src/components/WalletTourGuide/DesktopSteps.tsx
Reverts binary-com/deriv-app#14630
> Revert "[WALL] Lubega / WALL-3645 / Wallet onboarding walkthrough missing steps"

- packages/wallets/src/components/WalletListCardActions/WalletListCardActions.tsx
- packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.scss
- Change background color for Reset Balance color
> [WALL] Aizad/WALL-3780/ Change Reset Balance Color Button

- packages/wallets/src/components/WalletsResetMT5Password/WalletsResetMT5Password.scss
- packages/wallets/src/components/WalletsResetMT5Password/WalletsResetMT5Password.tsx
- packages/wallets/src/features/cfd/screens/CreatePassword/CreatePassword.tsx
- packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.tsx
- Update MT5 Reset Modal based on the new design changes
- Fix CreatePassword for DXTrade
- Refactor code
> [WALL] Aizad/WALL-3757/Fix text mismatch on MT5 Reset Modal

- packages/wallets/src/features/cfd/screens/ChangePassword/InvestorPassword/MT5ChangeInvestorPasswordSavedScreen.tsx
> [WALL] Aizad/WALL-3758/ Update Button Copy to OK

- packages/core/src/Stores/Helpers/chart-markers.js
> [DTRA] henry/dtra-967/fix: get start time on the chart translated

- .github/workflows/release_production.yml
Add send-slack-message back to production cicd job.
> chore: add create slack message action

- packages/core/src/Stores/traders-hub-store.js
- packages/tradershub/src/features/cfd/constants.tsx
The short description needs to be updated under CFDs For EU.
> [TRAH]/Mitra/TRAH-3183/Change cfd description for eu

- packages/cashier/src/pages/withdrawal/withdrawal-verification-email/withdrawal-verification-email.tsx
Update the content for WithdrawalEmailVerification request page for both `Wallets` and `Cashier-v2`.
Old Content
New Content
> [cashier] aum / WALL-3801 / cashier-change-content-withdrawal-email-verification-request

- packages/wallets/src/features/cashier/modules/CashierLocked/CashierLocked.tsx
Before
https://github.com/binary-com/deriv-app/assets/103016120/5f186a4a-f3c1-4418-8abb-4db034ba3cff
After
https://github.com/binary-com/deriv-app/assets/103016120/a9ece8c0-3122-47f7-b67b-b9b17404e6ae
> [WALL] Fix issue with cashier blocked message blinking

- packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAmountInput/__tests__/TransferFormAmountInput.spec.tsx
- packages/wallets/src/hooks/useInputATMFormatter.ts
https://github.com/binary-com/deriv-app/assets/119863957/a66bc504-2640-4e06-afac-dad89ee6e664
> [WALL] [Fix] Rostislav / WALL-3739 / Transfer amount input issue with editing integers

- packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormDropdown/TransferFormDropdown.tsx
- packages/wallets/src/features/cfd/CFDPlatformsListEmptyState.tsx
- packages/wallets/src/routes/Router.tsx
- Make USD Wallet account to be selected by default when transferring from a crypto wallet
https://github.com/binary-com/deriv-app/assets/103016120/8467d01f-ccb1-4b3a-8de5-bcef3fb5edcd
> [WALL] Make USD Wallet to be selected by default when transferring from a crypto wallet

- packages/wallets/src/components/Base/WalletPasswordField/WalletPasswordField.tsx
- packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx
- packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
- packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
- Added wrong password validation for MT5EnterPassword
> [WALL] Aizad/WALL-3822/Added Wrong Password Validation for MT5EnterPassword

- .github/workflows/smoketests.yml
> Markodonnell deriv run from commitv1

- packages/bot-web-ui/src/components/run-panel/__tests__/run-panel.spec.tsx
- packages/bot-web-ui/src/stores/run-panel-store.ts
> [BOT]Maryia/BOT-1478/test: Run panel component

- packages/wallets/src/components/Dropzone/Dropzone.scss
- packages/wallets/src/components/Dropzone/Dropzone.tsx
https://github.com/binary-com/deriv-app/assets/142860499/ac14a3e3-63ab-44b1-a80a-f8ea69c23ba0
> [WALL] Lubega / WALL-3815 / Dropzone pdf file preview

- packages/core/src/App/Containers/Modals/app-modals.jsx
added the check if user is navigated from derivgo => do not show effortless login modal
> [UPM-927]/evgeniy/do not show efforltess passkeys modal if accessed from derivgo

- .gitignore
- analyze.html
- package.json
- packages/account-v2/package.json
- packages/account/package.json
- packages/appstore/package.json
- packages/bot-web-ui/package.json
- packages/cashier-v2/package.json
- packages/cashier/package.json
- packages/cfd/package.json
- packages/core/package.json
- packages/p2p-v2/package.json
- packages/p2p/package.json
- packages/reports/package.json
- packages/trader/package.json
- packages/tradershub/package.json
- packages/wallets/package.json
This implements a webpack bundle analysis on each package, along with a dashboard in the root.
You can run it by:
```
npm run bootstrap
npm run build:all
npm run analyse
npx ws
```
Then visiting your browser.
http://127.0.0.1:8000/analyze.html
> chore: implement webpack analysing for each package

- packages/p2p/src/pages/my-profile/my-profile-stats/my-profile-privacy/my-profile-privacy.scss
- packages/p2p/src/pages/my-profile/my-profile-stats/my-profile-privacy/my-profile-privacy.tsx
Fixed the nickname toggle by removing the custom styles and following the standard style for `ToggleSwitch` component.
> [P2PS] farrah/P2PS-2718/fix: nickname toggle

- packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.scss
- packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardBack.scss
- packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardBack.tsx
https://github.com/binary-com/deriv-app/assets/142860499/b47fcaa3-0e6d-46f8-80ab-db2e9f60ed52
> [WALL] Lubega / WALL-3820 / Jurisdiction card back missing arrow icon

- packages/components/src/components/icon/appstore/ic-appstore-get-more-accounts.svg
- packages/components/src/components/icon/icons.js
* Fixed ctrader trade modal plus icon
> [WEBREL] Hasan/WEBREL-2711/Ctrader trade modal plus icon

- packages/api-v2/src/__tests__/useMutation.spec.tsx
- packages/api-v2/src/__tests__/useQuery.spec.tsx
Fixed tests failing locally intermittently. Not sure why they haven't failed earlier.
> [WALL] feat: fixed intermittently failing unit tests on localhost

- packages/wallets/src/features/cashier/flows/WalletTransactions/__tests__/WalletTransaction.spec.tsx
- packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsTable/__tests__/TransactionsTable.spec.tsx
> [WALL] Lubega / WALL-2985 / TransactionsTable unit test

- packages/appstore/src/components/modals/modal-manager.tsx
> [CFDS] shontzu/WEBREL-2709/investor-password-reset-password-link-is-not-working

- packages/tradershub/src/features/cfd/modals/ButtonGroups/AddAccountButtonsGroup.tsx
- packages/tradershub/src/features/cfd/screens/ChangePassword/TradingPlatformChangePasswordScreens.tsx
- packages/tradershub/src/hooks/index.ts
- packages/tradershub/src/hooks/useSendEmailHandler.ts
- packages/tradershub/src/modals/Modals.tsx
- packages/tradershub/src/modals/SentEmailContentModal/SentEmailContentModal.tsx
- Added `Forgot password` functionality on password modal
- Refactored duplicate send email code
https://github.com/binary-com/deriv-app/assets/108507236/236936b3-56ca-4bc6-ac02-be457811da19
> [TRAH] [CFDS] shontzu/CFDS-3883/Add-the-functionality-of-Forgot-password-button-on-passwordmodal

- .github/workflows/smoketests.yml
Amended action to use issue property
> Amend action to use issue property

- packages/cfd/src/Constants/jurisdiction-contents/jurisdiction-labuan-contents.ts
- packages/cfd/src/Constants/jurisdiction-contents/jurisdiction-svg-contents.ts
- packages/cfd/src/Containers/cfd-compare-accounts/__tests__/cfd-compare-accounts-description.spec.tsx
- packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-card.spec.tsx
- packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-modal-content.spec.tsx
- packages/cfd/src/Helpers/compare-accounts-config.ts
Updated Jurisdiction modal and Compare modal's financial labuan and financial svg's spread data
> [CFDS] Hasan/CFDS-1312/Jurisdiction modal and compare modal data update

- packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.tsx
- packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardBack.tsx
- packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardRow.tsx
* Fixed COJ page learn more button issue
**Before:**
**After:**
> [CFDS]/Hasan/CFDS-3886/coj learn more btn issue

- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
- packages/account/src/Sections/Profile/PersonalDetails/validation.ts
- removed email field inside Personal Details section for social signup accounts.
> feat: remove email field

- packages/core/src/Stores/client-store.js
> Ako/ test client store

- packages/core/src/Stores/client-store.js
To remove the temporary console log that was added for debugging purpose. 
> Ako/ remove test console

- packages/core/src/Stores/client-store.js
Change `console.warn` to `console.log`
> Sergei / Change console warning to log

- packages/core/src/App/AppContent.tsx
This is to fix the issue when reading clients country from cookie.
Expected output: `my` (as example)
Current output: {clients_country:"my"}
> Ako/ get the clients country from cookies

- packages/core/src/App/Containers/app-notification-messages.jsx
- packages/core/src/Stores/notification-store.js
- packages/core/src/sass/app/modules/notifications-dialog.scss
This reverts "[DTRA] henry/dtra-512/fix: add flutter chart notification (#12949)" commit 9a4cbb3881087c768e552e88b06dfaa444403e12 , except for the style change in notifications-dialog.scss which is affecting all kinds of notifications.
> [DTRA] Maryia/DTRA-1199/remove notification about new trade chart

- packages/cfd/src/Containers/cfd-password-modal.tsx
* Updated mt5 success modal content
> [TRAH] Hasan/TRAH-2245/updated mt5 success modal content

- packages/p2p/src/pages/buy-sell/__tests__/buy-sell-form-receive-amount.spec.js
- packages/p2p/src/pages/buy-sell/buy-sell-form-receive-amount.jsx
Fixed the received amount when creating a buy/sell order by wrapping the component in `observer` to get the updated amount from `BuySellForm`.
> [P2PS] farrah/P2PS-2664/fix: update received amount

- packages/core/src/Stores/client-store.js
DIEL countries user getting automatically logged out after inserting password to signup for Deriv account
> Amina/fix logout issue for DIEL clients

- packages/account/src/hooks/__test__/useKycAuthStatus.spec.tsx
- packages/account/src/hooks/index.ts
- packages/account/src/hooks/useKycAuthStatus.ts
- packages/api/types.ts
Created a useKycAuthStatus hook to make API calls using React query and authorized using client store
> feat: add useKycAuthStatus with mobx

- packages/account/src/Components/poi/idv-status/idv-limited/idv-limited.tsx
- packages/account/src/Sections/Assessment/FinancialAssessment/financial-assessment.tsx
Fix the status messaged displayed when last submit of IDV results in rejection status. The message asking for Re submitting POI should redirects users for Onfido, if the selected country supports it. Else it should redirect to Manual
> [COJ]/likhith/coj-755/fix: resolved IDV last status message

- packages/account/src/Components/self-exclusion/self-exclusion-article-content.tsx
- packages/components/src/components/open-livechat-link/index.ts
- packages/components/src/components/open-livechat-link/open-livechat-link.scss
- packages/components/src/components/open-livechat-link/open-livechat-link.tsx
- packages/components/src/index.ts
Added new component with related action to avoid sonarcloud errors.
> [UPM-982]/evgeniy/redirect to error page while clicking contact us link

- packages/bot-web-ui/src/components/trade-animation/trade-animation.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/analytics/constants.ts
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/analytics/rudderstack-quick-strategy.ts
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/analytics/utils.ts
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/config.ts
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/desktop-form-wrapper.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/mobile-form-wrapper.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/quick-strategy.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/types.ts
- packages/bot-web-ui/src/pages/bot-builder/toolbar/toolbar.tsx
- packages/bot-web-ui/src/pages/bot-builder/toolbox/toolbox.tsx
- packages/bot-web-ui/src/pages/dashboard/cards.tsx
- packages/bot-web-ui/src/pages/tutorials/common/search-input/index.tsx
- Added rudderstack events for quick strategy page action such as select strategy, run and edit strategy
- Added rudderstack events for search on tutorial page
> [BOT] Farabi/bot-1444/map dbot events to rudderstack

- packages/wallets/src/components/WalletsResetMT5Password/WalletsResetMT5Password.tsx
- packages/wallets/src/features/cfd/ResetMT5PasswordHandler.tsx
- packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.tsx
- Refactor code
- Replace ModalStepWrapper with ModalProvider
> [WALL] Aizad/WALL-3961/Center Modal Investor Password Modal in responsive

- packages/wallets/src/components/WalletCard/WalletCard.tsx
- packages/wallets/src/components/WalletCard/__tests__/WalletCard.spec.tsx
> [WALL] Lubega / WALL-3945 / USD demo wallet card name

- packages/appstore/src/components/cfds-listing/cfds-listing.scss
- packages/cfd/src/Components/cfd-account-card.tsx
- packages/cfd/src/Containers/ctrader-derivx-trade-modal.tsx
- packages/cfd/src/Containers/mt5-trade-modal.tsx
- packages/cfd/src/Helpers/config.tsx
- packages/cfd/src/Helpers/constants.ts
- packages/cfd/src/Stores/Modules/CFD/cfd-store.js
- packages/cfd/src/features/Containers/cfd-trade-modal.tsx
- packages/cfd/src/features/Containers/other-cfds-trade-modal.tsx
- packages/cfd/src/types/cfd-store.types.ts
Currently, Traders hub is requesting a Ctrader token during load time. This is a short lived token. Therefore, if client takes more than 60 seconds to open Ctrader web terminal from Trader hub, the token received will be invalid and he will not be able to login and the solution is that the request for the token should be made when the user clicks on terminal button
> [CFDs] Hirad/CFDs-1371/ Using the token call on click of the terminal button

- packages/wallets/.eslintrc.js
Attempt to fix the slow ESLint check in the CI/CD pipeline for wallets.
> [WALL] chore: fix eslint for wallets

- packages/api-v2/src/AuthProvider.tsx
- packages/api-v2/src/hooks/useAuthorize.ts
- packages/api-v2/src/hooks/useAvailableWallets.ts
- packages/wallets/src/components/DesktopWalletsList/DesktopWalletsList.tsx
- packages/wallets/src/components/WalletListCardBalance/WalletListCardBalance.tsx
- packages/wallets/src/components/WalletsAddMoreCarousel/WalletsAddMoreCarousel.tsx
Removed unnecessary loaders when switching account. 
Before: 
https://github.com/binary-com/deriv-app/assets/141034155/2304e760-58a1-40b0-936a-6e1c663f4ed6
After:
https://github.com/binary-com/deriv-app/assets/141034155/e48ab65b-b3ee-4c95-af72-b32d9d79cb08
> [WALL-3735] loaders review

- packages/bot-web-ui/src/stores/toolbox-store.ts
Refactored the adjust workspace function 
card: https://app.clickup.com/t/20696747/FEQ-2191
> [FEQ-2191]/Rupato/Refactored the adjust workspace function

- packages/core/src/public/.well-known/apple-app-site-association
> Check issue with passkey redirection 

- packages/wallets/src/components/Base/ModalStepWrapper/ModalStepWrapper.scss
- Made style changes to ModalStepWrapper
https://github.com/binary-com/deriv-app/assets/103104395/edffcbac-448e-4e55-9902-5c07e506c280
> [WALL] Aizad/WALL-4048/Adding Scroll To ModalStepWrapper

- packages/account/src/Sections/Verification/ProofOfIdentity/onfido-sdk-view-container.tsx
- packages/core/src/sass/app/_common/components/account-common.scss
Locked Onfido Web SDK version to 13.8.4 (Latest available vis CDN). Fixed CSS styling as per the layout of the screen rendered based on this version.
Lower versions are not providing the Live document upload feature.
> [coj]/likhith/COJ-772/chore: locked Onfido SDK version

- packages/appstore/src/modules/traders-hub/index.tsx
- disclaimer content update for EU/DIEL percentage
> [TRAH-3462] shahzaib / update eu disclaimer

- packages/appstore/src/modules/traders-hub/index.tsx
Reverts binary-com/deriv-app#15143
> Revert "[TRAH-3462] shahzaib / update eu disclaimer"

- packages/cashier/src/components/transactions-crypto-history/transactions-crypto-history.tsx
Fix translation issue for recent transactions.
> Suisin/fix: translation issue for recent transactions

- packages/reports/src/Components/__tests__/currency-wrapper.spec.tsx
- packages/reports/src/Components/__tests__/filter-component.spec.tsx
> [DTRA] henry/webrel-12/fix: add tests for currency wrapper and filter component

- packages/appstore/src/modules/traders-hub/index.tsx
- disclaimer content update for EU/DIEL percentage
> [TRAH-3462] shahzaib / disclaimer update

- packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountSelection/TransferFormAccountSelection.tsx
- packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountSelection/__tests__/TransferFormAccountSelection.spec.tsx
> [WALL] Lubega / WALL-2992 / TransferFormAccountSelection unit test

- packages/wallets/src/features/cashier/modules/Transfer/components/TransferForm/TransferForm.tsx
- packages/wallets/src/features/cashier/modules/Transfer/components/TransferForm/__tests__/TransferForm.spec.tsx
- Added unit tests for TransferForm component.
> [WALL] aum / WALL-2990/ unit-test-transfer-form

- packages/wallets/src/components/WalletsErrorScreen/WalletsErrorScreen.tsx
- packages/wallets/src/components/WalletsErrorScreen/__tests__/WalletsErrorScreen.spec.tsx
- packages/wallets/src/constants/errorCodes.ts
- packages/wallets/src/features/cashier/modules/Transfer/Transfer.tsx
- packages/wallets/src/features/cashier/modules/Transfer/__tests__/Transfer.spec.tsx
https://github.com/binary-com/deriv-app/assets/142860499/4bcffd20-076b-4bbd-827e-1de12d87ab68
https://github.com/binary-com/deriv-app/assets/142860499/942c7009-f9f9-4431-98e4-2a60d8147652
> [WALL] Lubega / WALL-3730 / Transfer API error screen

- packages/wallets/src/components/WalletTourGuide/WalletTourGuideSteps.tsx
- Update copywriting for some of the steps for onboarding.
> Aizad/WALL-4088/Update Copywriting for Onboarding

- packages/components/src/components/modal/modal.scss
- Add `width` and `height` with `!important` for currency selection modal
> [FEQ] Sergei / FEQ - 2203 / Select account popup for tablet

- packages/appstore/src/components/cfds-listing/cfds-listing.scss
- fix transition glitch when flipping from jurisdiction modal to dynamic leverage modal
https://github.com/binary-com/deriv-app/assets/108507236/c8e40ab4-6cb4-461b-837e-8aff1c08f61e
> [CFDS] shontzu/CFDS-3502/unexpected-behaviour-upon-clicking-dynamic-leverage

- packages/wallets/src/features/cashier/modules/Transfer/components/TransferMessages/__tests__/TransferMessages.spec.tsx
> [WALL] Lubega / WALL-4090 / TransferMessages unit test

- packages/reports/src/Containers/__tests__/reports.spec.tsx
It includes all the test cases required for covering reports.tsx Container in Reports Packages
> [DTRA]Ahmad WEBREL-21/Reports.tsx Coverage

- package-lock.json
- packages/bot-web-ui/package.json
- packages/core/package.json
- packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.17
> Update deriv-charts to 2.1.17

- packages/trader/src/Stores/Modules/Trading/trade-store.ts
To fetch tick_history without subscribing when the market is closed.
> [DTRA] Bala/market closed

- packages/trader/src/AppV2/Components/BottomNav/bottom-nav.scss
- packages/trader/src/AppV2/Components/BottomNav/bottom-nav.tsx
> Fix bottom nav scroll

- packages/api-v2/src/hooks/useCtraderServiceToken.ts
- packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeLink/MT5TradeLink.tsx
The request for a token should be made when the user clicks on cTrader web terminal.
> Hirad/wall-4006/ Terminal button will call the token and redirect user with a new token

- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/analytics/__tests__/utils.spec.ts
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/descriptions/__tests__/strategy-description.spec.tsx
Added missing test case inside quick strategy folder
> [BOT]test: added missing test case in qs folder

- packages/p2p/src/pages/my-ads/create-ad-form.jsx
the header texts were not wrapped in localize. hence wrapped it in the localize function. 
> [WEBREL] nada/fix: translation not handled for header fix

- packages/wallets/src/components/Base/Tooltip/Tooltip.tsx
- packages/wallets/src/components/Base/Tooltip/__tests__/Tooltip.spec.tsx
> [WALL] [Jest] Rostislav / WALL-3047 / Unit test for Tooltip component

- packages/appstore/src/components/containers/listing-container.tsx
Reverts binary-com/deriv-app#15309
> Revert "[WEBREL]/Mitra/[WEBREL-2748] Remove the condition as we use the component for bot…"

- packages/appstore/src/components/containers/listing-container.tsx
- packages/appstore/src/components/containers/trading-app-card.tsx
- packages/appstore/src/components/options-multipliers-listing/index.tsx
- packages/appstore/src/helpers/available-platforms-helper.ts
- packages/appstore/src/helpers/index.ts
- packages/appstore/src/modules/traders-hub/__tests__/index.spec.tsx
- packages/appstore/src/modules/traders-hub/index.tsx
- packages/core/src/Stores/traders-hub-store.js
Reverts binary-com/deriv-app#15013
> Revert "[TRAH-3380] shahzaib / remove authorization and loader from options & multipliers]"

- packages/core/src/Stores/client-store.js
- fix `user_id` attribute missing on rudderstack by passing the `user_id` on setAttribute call
> [CRO] Amir/CRO-582/Fix `user_id` attribute missing on rudderstack

- packages/wallets/src/features/accounts/screens/SelfieDocumentUpload/SelfieDocumentUpload.tsx
https://github.com/binary-com/deriv-app/assets/119863957/647c8aa3-72df-46b9-b084-3902d6929b98
> [WALL] [Fix] Rostislav / WALL-4125 / Fix POA document going missing when navigating the flow stages

- packages/core/src/App/Containers/Layout/header/show-notifications.tsx
- packages/core/src/App/Containers/Layout/header/traders-hub-header-wallets.tsx
- packages/core/src/App/Containers/Layout/header/traders-hub-header.tsx
- packages/core/src/App/Containers/Layout/header/traders-hub-onboarding.tsx
- packages/core/src/sass/app/_common/components/account-switcher.scss
Hide header notification, onboarding, and account settings popover
> [DTRA] Farhan/FEQ-2205/Header notification icon and account settings links are not working as expected

- packages/appstore/src/components/cfds-listing/cfds-listing.scss
Change desktop mixin to new desktop-screen mixin
> Sergei / TRAH 3524 / Jurisdiction popup on ipad pro

- packages/wallets/src/AppContent.scss
https://github.com/binary-com/deriv-app/pull/15217
> [WALL] George/Lubega : WALL-3890 / MT5 modal iphone issue

- packages/wallets/src/components/WalletsAddMoreCard/__tests__/WalletsAddMoreCard.spec.tsx
- packages/wallets/src/components/WalletsAddMoreCardBanner/WalletsAddMoreCardBanner.tsx
- packages/wallets/src/components/WalletsAddMoreCardBanner/__tests__/WalletsAddMoreCardBanner.spec.tsx
- packages/wallets/src/components/WalletsContainer/WalletsContainer.tsx
- packages/wallets/src/components/WalletsContainer/__tests__/WalletsContainer.spec.tsx
> [WALL] Lubega / WALL-2904/2905 / Added unit tests for wallet components

- packages/wallets/src/components/Base/ModalStepWrapper/ModalStepWrapper.scss
- packages/wallets/src/components/Base/ModalStepWrapper/ModalStepWrapper.tsx
- packages/wallets/src/features/accounts/screens/PersonalDetails/PersonalDetails.tsx
- packages/wallets/src/features/cfd/flows/Verification/Verification.tsx
- Re-add `overflow: auto`
- Added a new prop inside the ModalStepWrapper called `disableScroll`
> [WALL] Aizad/WALL-4205/Fix Layout Trade Modal

- packages/appstore/src/components/cfds-listing/index.tsx
- packages/appstore/src/components/elements/options-description/index.tsx
- packages/appstore/src/components/get-started-trading-banner/get-started-trading-banner.scss
- packages/appstore/src/components/get-started-trading-banner/get-started-trading-banner.tsx
- packages/appstore/src/components/trustpilot-star-rating/trustpilot-star-rating.tsx
- Add correct button size
- Add logical properties for positioning
- Add check for `RTL` for trustpilot stars
- Change `other CFD platform` to `Deriv X` for logged in TH
> [WEBREL] Sergei / WEBREL - 2770, 2771, 2772 / AR language, Get Started button padding, Content change in logged in TH

- packages/components/src/components/contract-card/contract-card-items/__tests__/contract-update-form.spec.tsx
- packages/components/src/components/contract-card/contract-card-items/__tests__/toggle-card-dialog.spec.tsx
- packages/components/src/components/contract-card/contract-card-items/contract-update-form.tsx
- packages/components/src/components/contract-card/contract-card-items/sass/contract-card-dialog.scss
- packages/components/src/components/contract-card/contract-card-items/toggle-card-dialog.tsx
- packages/components/src/components/input-wth-checkbox/input-with-checkbox.tsx
- packages/trader/src/Modules/Contract/Components/AccumulatorsStats/accumulators-stats.tsx
- packages/trader/src/sass/app/modules/contract/accumulators-stats.scss
Fixing these issues:
- Accumulator state chart is left aligned instead of center
- Accumulator State video is not fully visible
- Take profit and stop loss fields are appearing in background for ongoing contracts
> [DTRA] Farhan/Tablet view subtasks

- .github/workflows/release_production.yml
- .github/workflows/release_staging.yml
- .github/workflows/release_test.yml
- .github/workflows/release_uat.yml
add `TRUSTPILOT_API_KEY` secret for 4 workflows
> [TRAH] Sergei / TRAH - 3558 / Add TRUSTPILOT_API_KEY secret for 3 workflows

- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/analytics/constants.ts
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/analytics/rudderstack-quick-strategy.ts
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/analytics/utils.ts
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/desktop-form-wrapper.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/mobile-form-wrapper.tsx
- packages/bot-web-ui/src/pages/tutorials/quick-strategy-content/quick-strategy-guides-details.tsx
- Fixed rudderstack event for run bot
- Fixed rudderstack event for quick strategy guide
> [BOT] Farabi/bot-1809/update rudderstack events

- packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_market.js
- packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_restartbuysell.js
> [BOT]maryia/FEQ-828/fix: trackJS error Cannot read properties of null (reading 'connect')

- packages/p2p/src/pages/my-profile/payment-methods/edit-payment-method-form/edit-payment-method-form.tsx
Issue with duplicate PM - save button not enabled after closing error modal.
> [WEBREL] nada/fix: issue with duplicate PM

- packages/wallets/src/features/accounts/screens/PoiPoaDocsSubmitted/PoiPoaDocsSubmitted.tsx
- packages/wallets/src/features/cfd/flows/Verification/Verification.tsx
- packages/wallets/src/features/cfd/screens/Onfido/Onfido.tsx
- Fix to not show POA if the clients POI fails given that the client had done POI and POA previously.
https://github.com/binary-com/deriv-app/assets/125039206/70fe1931-d3f1-427a-a8e4-378c3f41417c
> [WALL] aum / WALL-4272/ poa-showing-after-2nd-attempt-of-poi

- packages/components/src/components/search-box/search-box.jsx
Fix issue with variable accessed before initialization
> [P2PS-3015]/Nada/fix: cannot access t before initialization

- packages/components/src/components/contract-card/contract-card.scss
- packages/reports/src/Containers/__tests__/reports.spec.tsx
- packages/reports/src/sass/app/modules/reports.scss
- packages/trader/jest.config.js
- packages/trader/src/App/Containers/__tests__/trade-header-extensions.spec.tsx
> Fix tablet view issues

- .github/actions/analyze/action.yml
- .github/actions/build/action.yml
- .github/workflows/analyze.yml
Add Trustpilot api key to 2 more github actions
> Sergei / Add Trustpilot api key to 2 more github actions

- packages/wallets/src/components/WalletTourGuide/WalletTourGuideSettings.tsx
> [WALL] [Fix] Rostislav / WALL-4252 / Fix onboarding flow breaking in various ways when initiating from crypto wallet overlay

- packages/appstore/src/modules/traders-hub/index.tsx
We are showing the banner for MF clien , but it should be shown only for Non EU client
> [WEBREL]/MITRA/WEBREL-2800/Should not show banner to eu client

- packages/hooks/src/useP2PExchangeRate.ts
- Removed default value for exchange rate
> [P2PS] / Ameerul / Remove the default value for exchange rate

- packages/account/src/Components/personal-details/__tests__/personal-details.spec.tsx
- packages/account/src/Configs/personal-details-config.ts
- packages/account/src/Helpers/utils.tsx
- packages/account/src/Sections/Profile/PersonalDetails/__tests__/personal-details-form.spec.tsx
- packages/account/src/Sections/Profile/PersonalDetails/validation.ts
- packages/shared/src/utils/validation/declarative-validation-rules.ts
- packages/tradershub/src/utils/validations/validations.ts
- packages/wallets/src/features/accounts/validations.ts
Reverted the commit from this PR (https://github.com/binary-com/deriv-app/pull/15138).
> revert problematic commit

- packages/wallets/src/features/cfd/modals/MT5AccountAdded/MT5AccountAdded.tsx
- Fix popup **title** message for Swap Free Accounts
Before:
---
After:
---
> Aizad/WALL-4210/Fix Popup Title Message inside of CFD Success Modal

- packages/core/src/App/Containers/ConfirmEmailModal/confirm-email-modal.jsx
- packages/core/src/App/Containers/ResetEmailModal/reset-email-modal.jsx
- packages/core/src/Stores/client-store.js
Fix: Trigger email change modal even if user refresh the email change link.
> [COJ-1143]Amina/ fix: reset_email_modal_refresh_issue

- packages/wallets/src/components/WalletAddedSuccess/__test__/WalletAddedSuccess.spec.tsx
- Added Test Case for `WalletAddedSuccess` component
> [WALL] Aizad/WALL-2886/ WalletAddedSuccess Test Case

- packages/components/src/components/contract-card/contract-card-items/__tests__/accumulator-card-body.spec.tsx
- packages/components/src/components/contract-card/contract-card-items/__tests__/toggle-card-dialog.spec.tsx
- packages/components/src/components/contract-card/contract-card-items/accumulator-card-body.tsx
- packages/components/src/components/contract-card/contract-card-items/contract-card-body.tsx
- packages/components/src/components/contract-card/contract-card-items/multiplier-card-body.jsx
- packages/components/src/components/contract-card/contract-card-items/sass/contract-card-dialog.scss
- packages/components/src/components/contract-card/contract-card-items/toggle-card-dialog.tsx
- packages/shared/src/utils/constants/__tests__/contract.spec.ts
- packages/shared/src/utils/constants/contract.ts
- packages/trader/src/Assets/Trading/Categories/Description/__tests__/accumulator-trade-description.spec.tsx
- packages/trader/src/Assets/Trading/Categories/Description/accumulator-trade-description.tsx
- packages/trader/src/Modules/Trading/Components/Form/ContractType/ContractTypeInfo/contract-type-glossary.tsx
- packages/trader/src/Modules/Trading/Components/Form/ContractType/__tests__/contract-type-glossary.spec.tsx
- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/__tests__/take-profit.spec.tsx
- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/take-profit.tsx
- Updated TP tooltip, contract description and glossary for Acc;
- Refactored toggle-card-dialog.tsx;
- Covered changes with tests
> OPT-796 / Kate / Update Take Profit information and functionality for Accumulators contract

- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/__tests__/accordion-strategy-group.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/__tests__/desktop-form-wrapper.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/__tests__/form-tabs.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/__tests__/mobile-form-wrapper.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/__tests__/useQsSubmitHandler.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/accordion-strategy-group.tsx
test folder: [Test Coverage] Folder: bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers
**Covered with tests from scratch:**
- AccordionStrategyGroup
- DescriptionContent
- FormTabs
- useQsSubmitHandler hook
**Increased test coverage of component tests:**
- Desktop form wrapper
- Mobile form wrapper
> [BOT] maryia/ BOT-1486/[Test Coverage] Folder: bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers

- packages/reports/src/Containers/__tests__/statement.spec.tsx
- to fix failing Statement test case
> [DTRA] Maryia/test: fix failing Statement test case

- package-lock.json
- packages/bot-web-ui/package.json
- packages/core/package.json
- packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.20
> Update deriv-charts to 2.1.20

- packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/__tests__/countLimitsMessageFn.spec.ts
- packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/__tests__/cumulativeAccountLimitsMessageFn.spec.ts
- packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/__tests__/lifetimeAccountLimitsBetweenWalletsMessageFn.spec.ts
- packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/cumulativeAccountLimitsMessageFn.ts
- countLimitMessageFn
- cumulativeAccountLimitsMessageFn
- lifetimeAccountLimitsBetweenWalletsMessageFn
> [WALL] Lubega / WALL-4345 / useTransferMessages utils unit test

- packages/wallets/src/features/cashier/components/WalletCashierHeader/__tests__/WalletCashierHeader.spec.tsx
- Add more unit tests for `WalletCashierHeader` component
> [WALL] aum / WALL-2962 / unit-tests-for-WalletCashierHeader

- packages/core/src/App/Containers/Layout/header/header.tsx
- packages/shared/src/utils/routes/routes.ts
- packages/trader/src/AppV2/Components/BottomNav/__tests__/bottom-nav.spec.tsx
- packages/trader/src/AppV2/Components/BottomNav/bottom-nav.tsx
- packages/trader/src/AppV2/Containers/Markets/markets.tsx
- packages/trader/src/AppV2/Containers/Menu/menu.tsx
- packages/trader/src/AppV2/Containers/Positions/__tests__/positions-content.spec.tsx
- packages/trader/src/AppV2/Containers/Positions/__tests__/positions.spec.tsx
- packages/trader/src/AppV2/Containers/Positions/positions.tsx
- packages/trader/src/AppV2/Containers/Trade/trade.tsx
- packages/trader/src/AppV2/Routes/router.tsx
- packages/trader/src/AppV2/Routes/routes.tsx
- packages/trader/src/AppV2/app.tsx
Implemented a router for trader v2.
> [DTRA] Bala/add router for appv2

- .github/workflows/smoketests.yml
- .github/workflows/smoketests_manual.yml
> Markodonnell deriv manual smoketests

- packages/bot-skeleton/src/scratch/hooks/workspace_svg.js
- packages/bot-web-ui/src/app/app-content.jsx
- packages/bot-web-ui/src/components/bot-notification/bot-notification.tsx
- packages/bot-web-ui/src/components/transactions/transaction.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/__tests__/form.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/inputs/__tests__/qs-input.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/inputs/qs-input.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/__tests__/contract_type.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/__tests__/duration_type.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/__tests__/symbol.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/__tests__/trade-type.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/contract-type.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/duration-type.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/symbol.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/trade-type.tsx
- packages/bot-web-ui/src/pages/dashboard/load-bot-preview/recent-workspace.tsx
- Added data-testid for the 4 main blocks
- Added data-testid for dashboard bot list action buttons such as open, save and delete
- Added data-testid for notifications on dbot
> [BOT] Farabi/bot-1469/update locators on dbot

- package-lock.json
- packages/account/package.json
- packages/api-v2/package.json
- packages/cashier-v2/package.json
- packages/cfd/package.json
- packages/core/package.json
- packages/p2p-v2/package.json
- packages/p2p/package.json
- packages/p2p/src/pages/app.jsx
- packages/trader/package.json
- packages/tradershub/package.json
- packages/wallets/package.json
Used the p2p-v2 feature flag to redirect the internal users to the standalone application.
> [FEQ]farrah/FEQ-2347/refactor: p2p-v2-feature-flag

- packages/bot-web-ui/src/pages/bot-builder/__tests__/workspace-wrapper.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/toolbar/__tests__/toolbar.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/toolbar/__tests__/workspace-group.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/toolbar/toolbar.tsx
- packages/bot-web-ui/src/pages/bot-builder/toolbar/workspace-group.tsx
- packages/bot-web-ui/src/pages/dashboard/load-bot-preview/index.scss
- Increased test coverage to 100% for all the toolbar components
> [BOT] Farabi/bot-1489/test cases for toolbar folder

- .github/workflows/smoketests_manual.yml
Reduce manual run down to triggering a yml.
> Markodonnell deriv manual smoketests v2

- packages/wallets/src/components/Base/ModalStepWrapper/ModalStepWrapper.scss
- packages/wallets/src/features/cfd/constants.tsx
The QR Codes in MT5 and CTrader trade modals are wrong. This PR fixes it.
> [WALL] Nijil / WALL-4390 / QR codes for MT5, DerivX and CTrader

- packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx
- packages/core/src/sass/app.scss
Load the required CSS on App initialization. The CSS files contains styles used by different components present in core and accounts package
> [COJ]/likhith/coj-1236/incorporated css fix for mt5 poi

- packages/reports/src/Components/Form/CompositeCalendar/__tests__/composite-calendar-mobile.spec.tsx
- Fixed date in failing test case. Sorry
> WEBREL-3 / Kate / Fix: failing test case

- packages/account/src/Components/poa/common-mistakes/common-mistake-examples.scss
- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.tsx
- packages/account/src/Styles/account.scss
- packages/appstore/src/components/real-account-creation-banner/real-account-creation-banner.scss
- packages/appstore/src/components/real-account-creation-banner/real-account-creation-banner.tsx
Change `mobile` mixins for `mobile-or-tablet` mixins, and change js breakpoints for tablet view
> [FEQ] Sergei / FEQ - 2374, 2375, 2376 / Tablet view issues 4

- packages/account/src/Components/poa/common-mistakes/common-mistake-examples.scss
- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.tsx
- packages/account/src/Styles/account.scss
- packages/appstore/src/components/real-account-creation-banner/real-account-creation-banner.scss
- packages/appstore/src/components/real-account-creation-banner/real-account-creation-banner.tsx
Reverts binary-com/deriv-app#15659
> Revert "[FEQ] Sergei / FEQ - 2374, 2375, 2376 / Tablet view issues 4"

- packages/account/src/Sections/Profile/PersonalDetails/validation.ts
Need to accept one character for first name 
bug: 
fix:
> [WEBREL-2822]/Mitra/Accept one character for first name

- packages/account/build/constants.js
- packages/account/package.json
- packages/account/src/Components/poa/common-mistakes/common-mistake-examples.scss
- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.tsx
- packages/account/src/Styles/account.scss
- packages/appstore/src/components/real-account-creation-banner/real-account-creation-banner.scss
- packages/appstore/src/components/real-account-creation-banner/real-account-creation-banner.tsx
Change mobile mixins for mobile-or-tablet mixins, and change js breakpoints for tablet view
> [FEQ] Sergei / FEQ - 2374, 2375, 2376 / Tablet view issues 4 (2)

- packages/core/src/Modules/P2PIFrame/P2PIFrame.tsx
- packages/core/src/Stores/client-store.js
- fixed p2p iframe url issue
- send stored language to p2p as well
> fix: fixed p2p iframe url issue + send language to p2p

- packages/bot-web-ui/src/pages/bot-builder/toolbox/__tests__/toolbox.spec.tsx
- Added test case for the toolbox component
> [BOT] Farabi/bot-1490/test coverage for toolbox

- packages/cashier/src/components/transactions-crypto-history/__tests__/transactions-crypto-renderer.spec.tsx
- packages/cashier/src/components/transactions-crypto-history/transactions-crypto-history.scss
- packages/cashier/src/components/transactions-crypto-history/transactions-crypto-renderer.tsx
'transaction_type' coming from BE is not translated by passing to Localize component.
So adding new variable with checking transaction_type and assigning Localize with correct text
> [UPM-1100]/evgeniy/withdrawal word is not translated on recent transaction page

- packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormDropdown/__tests__/TransferFormDropdown.spec.tsx
> [WALL] Lubega / WALL-2994 / TransferFormDropdown unit test

- packages/appstore/src/components/main-title-bar/index.tsx
The diff should be just one change after https://github.com/binary-com/deriv-app/pull/15186 is merged
> [WALL] Rostislav / WALL-4202 / Narrow down condition for wallets migration banner

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
due to this PR #15441 there is a bug in which we are hiding the real account creation in account swithcer , please refer to the card for the screenshot of the fix for all scenarios
https://github.com/binary-com/deriv-app/assets/64970259/8f8d333c-668b-4a56-9177-e0e14e43adb6
> [TRAH]/Mitra/TRAH-3722/show eu real account creation in account switcher

- packages/appstore/src/components/real-account-creation-banner/real-account-creation-banner.scss
Add some styles for mobile and tablet screens
https://github.com/binary-com/deriv-app/assets/120570511/2c91b6b8-54ae-41c2-b3dd-cd06c02ee5e2
> [FEQ] Sergei / FEQ - 2376 / "Get real account" button for DIEL

- packages/account/src/Sections/Profile/PersonalDetails/__tests__/personal-details-form.spec.tsx
- packages/account/src/Sections/Profile/PersonalDetails/__tests__/validation.spec.tsx
- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
- packages/hooks/src/__tests__/useResidenceList.spec.tsx
- packages/hooks/src/__tests__/useStatesList.spec.tsx
- packages/hooks/src/index.ts
- packages/hooks/src/useResidenceList.ts
- packages/hooks/src/useStatesList.ts
Personal details reloads when user interacts with it when resized to mobile or tablet view. 
Also the section makes API calls when interacted in all the views.
https://github.com/binary-com/deriv-app/assets/98398322/8e20284b-1f93-4458-8a37-5c97521ad350
> [COJ]/likhith/coj-1127/fix: personal-details rendering issue

- packages/api-v2/src/APIProvider.tsx
> [WALL] Lubega/ WALL-4344 / APIProvider unmounted component console error

- packages/hooks/src/useP2PAdvertInfo.ts
- packages/p2p/src/pages/advertiser-page/__tests__/advertiser-page.spec.tsx
- packages/p2p/src/pages/advertiser-page/advertiser-page-row.jsx
- packages/p2p/src/pages/advertiser-page/advertiser-page.jsx
- Reverted the changes done to advertiser page but implemented the proper way to handle isSubscribed and isLoading cases
- Prevent p2p_advert_info to be called onMount if no id is passed, since it called the endpoint without id being passed
- Properly subscribed to p2p_advert_info in advertiser's page when user opens buy sell modal
https://github.com/binary-com/deriv-app/assets/103412909/33b51031-e170-459b-930a-2d8352fdfda6
https://github.com/binary-com/deriv-app/assets/103412909/9357fee2-f798-4f7a-aabb-d4f3e26167e0
https://github.com/binary-com/deriv-app/assets/103412909/62142f6a-5f7a-4539-b75f-1d6201642129
https://github.com/binary-com/deriv-app/assets/103412909/4e379b9e-8baa-4261-829c-d6ad0ed2e4bb
> [P2PS] / Ameerul / P2PS-2970 Share My Ads - 'This ad is currently unavailable' pop not showing

- packages/appstore/src/components/cfds-listing/index.tsx
- packages/appstore/src/components/elements/cfds-description/cfds-description.tsx
- packages/appstore/src/components/elements/options-description/options-description.tsx
- packages/appstore/src/components/options-multipliers-listing/index.tsx
- packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.tsx
- packages/wallets/src/features/cfd/CFDPlatformsList.tsx
Update description for "Options" and "CFDs" in TH and Wallets
> [TRAH] Sergei / TRAH - 3740 / Description update for "Options" and "CFDs"

- packages/wallets/src/components/AppCard/__tests__/AppCard.spec.tsx
- add unit test for AppCard component
> [WALL] george / WALL-2864 / Unit test for AppCard component

- packages/p2p/src/pages/advertiser-page/advertiser-page.jsx
- Removed currently from the error modal when sharing unavailable ad
> chore: removed currently string from modal title

- packages/components/src/components/dropdown/dropdown.scss
- reverted back the changes done to dropdown.scss file
> [WEBREL] / Ameerul / WEBREL-2860 UI Bug : The search and filter boxes on P2P buy/sell tab are not aligned in desktop and responsive mode 

- packages/appstore/src/modules/traders-hub/index.tsx
- Change text size for desktop
> [WEBREL] Sergei / WEBREL - 2872 / EU disclaimer content font size is smaller in staging

- packages/core/src/App/Components/Elements/LandscapeBlocker/landscape-blocker.tsx
Add check for wallet account in `LandscapeBlocker` component
> [WEBREL] Sergei / WEBREL - 2863 / Wallet issues

- packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.scss
> [WEBREL] Sergei / WEBREL - 2870 / Amount input field is middle aligned and spacing issue in Transfer page and in transfer pop up

- packages/account/src/Components/address-details/__tests__/address-details.spec.tsx
- packages/account/src/Components/address-details/address-details.tsx
- packages/account/src/Components/forms/personal-details-form.jsx
- packages/account/src/Components/personal-details/__tests__/personal-details.spec.tsx
- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
- packages/cfd/src/Containers/ctrader-derivx-trade-modal.tsx
- packages/cfd/src/Containers/dmt5-trade-modal.tsx
- packages/cfd/src/Containers/mt5-trade-modal.tsx
- packages/cfd/src/features/Containers/cfd-trade-modal.tsx
- packages/cfd/src/features/Containers/mt5-trade-modal.tsx
- packages/cfd/src/features/Containers/other-cfds-trade-modal.tsx
- packages/cfd/src/sass/cfd.scss
- packages/components/src/components/form-progress/form-progress.scss
- packages/components/src/components/form-progress/form-progress.tsx
- packages/components/src/components/page-overlay/page-overlay.scss
- packages/core/src/App/Containers/RealAccountSignup/finished-add-currency.jsx
- packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx
- packages/core/src/App/Containers/RealAccountSignup/status-dialog-container.jsx
- packages/core/src/App/Containers/VerificationModal/verification-modal.scss
- packages/core/src/Constants/ui.js
- packages/core/src/sass/account-wizard.scss
- packages/core/src/sass/add-or-manage.scss
- packages/shared/src/utils/screen/responsive.ts
Add `useDevice` hook instead of `is_mobile` from the store
> [WEBREL] Sergei / WEBREL - 2856 / UI Bugs for Tablet View Implementation

- packages/components/src/components/drawer/__tests__/drawer.spec.tsx
Fix the test case for drawer component
> fix: failing test cases for drawer component

- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/Stores/client-store.js
This PR helps to redirect the user to login page in case the user tries to request email but is not logged in
Uploading Screen Recording 2024-06-20 at 4.35.29 PM.mov…
> chore: redirect to login and from login for email request modal

- packages/api-v2/src/hooks/useCtraderAccountsList.ts
- packages/api-v2/src/hooks/useDxtradeAccountsList.ts
- packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.scss
- packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.tsx
https://github.com/binary-com/deriv-app/assets/142860499/3defd3b7-0ecd-406d-a915-7c82ba2527ad
> [WALL] Lubega / WALL-4281 / Add transfer button to mt5 trade modal

- packages/core/src/Stores/client-store.js
- packages/wallets/src/features/cashier/flows/WalletWithdrawal/WalletWithdrawal.tsx
https://github.com/binary-com/deriv-app/assets/142860499/15225685-54db-4218-8794-da7bd6725881
https://github.com/binary-com/deriv-app/assets/142860499/66fa97a3-4240-4ad9-8981-51e02bd16271
https://github.com/binary-com/deriv-app/assets/142860499/94f69506-cb24-4857-8320-8e0cc781ac40
https://github.com/binary-com/deriv-app/assets/142860499/4c64de61-3400-435f-8dd8-9be79f67d074
> [WALL] Lubega / DERG-2459 / Deriv go redirection blank issue

- packages/wallets/src/components/WalletListCardBadge/WalletListCardBadge.tsx
- packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/__tests__/TransactionsCompletedRow.spec.tsx
- packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowAccountDetails/__tests__/TransactionsCompletedRowAccountDetails.spec.tsx
- packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowTransferAccountDetails/__tests__/TransactionsCompletedRowTransferAccountDetails.spec.tsx
- packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAmountInput/__tests__/TransferFormAmountInput.spec.tsx
> [WALL] Lubega / WALL-2981 / TransactionsCompletedRow unit test

- packages/wallets/src/components/OptionsAndMultipliersListing/LinkTitle.tsx
- packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.tsx
- packages/wallets/src/components/OptionsAndMultipliersListing/__test__/LinkTitle.spec.tsx
- packages/wallets/src/components/OptionsAndMultipliersListing/__test__/OptionsAndMultipliersListing.spec.tsx
- Created OptionsAndMultipliersListing test case 
- Created LinkTitle test case
> [WALL] Aizad/WALL-2856/OptionsAndMultipliersListing Test Case

- packages/reports/src/Components/Routes/__tests__/binary-link.spec.tsx
- packages/reports/src/Components/Routes/__tests__/binary-routes.spec.tsx
- packages/reports/src/Components/Routes/__tests__/route-with-sub-routes.spec.tsx
- packages/reports/src/Components/Routes/binary-link.tsx
> [DTRA] henry/webrel-16/chore: add tests

- packages/reports/src/Containers/__tests__/profit-table.spec.tsx
- packages/reports/src/Containers/profit-table.tsx
It includes coverage for the profitTable.tsx .
> Ahmad/DTRA-1367/Reports: Profit Table Coverage

- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/inputs/__tests__/qs-input.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/inputs/qs-input.tsx
test: increase test coverage for input folder: bot-web-ui/src/pages/bot-builder/quick-strategy/inputs
> [BOT]maryia/BOT-1487/test: increase test coverage for input folder: bot-web-ui/src/pages/bot-builder/quick-strategy/inputs

- packages/bot-web-ui/src/analytics/__tests__/utils.spec.ts
- packages/bot-web-ui/src/analytics/utils.ts
- packages/bot-web-ui/src/pages/tutorials/__tests__/tutorial-tab-desktop.spec.tsx
test: Folder **bot-web-ui/src/analytics**
- utils.ts
- rudderstack-tutorials.ts
> [BOT]maryia/BOT-1485/test: Folder bot-web-ui/src/analytics

- packages/bot-web-ui/src/pages/dashboard/dashboard.scss
- packages/bot-web-ui/src/pages/dashboard/load-bot-preview/index.scss
- packages/bot-web-ui/src/pages/dashboard/load-bot-preview/recent-workspace.tsx
- packages/bot-web-ui/src/pages/tutorials/tutorials.scss
- Fixed dashboard ui related to shortcut icons alignment on responsive.
- Added cypress locator for dashboard quick action buttons on responsive
> [BOT] Farabi/webrel 2882/dbot UI bugs from tablet implementation

- packages/trader/src/AppV2/Containers/Positions/positions-content.tsx
> DTRA / Kate/ Fix: typo

- packages/components/src/components/themed-scrollbars/themed-scrollbars.scss
Remove the mixin for tablet view for themed-scrollbar to fix the bug in tradingList view
> fix: remove mixin for tablet-mobile

- packages/account/src/Components/article/article.scss
- packages/account/src/Styles/account.scss
- packages/components/src/components/icon/icons.js
- packages/core/src/sass/app/_common/components/account-common.scss
Fixed tablet view spacing issue
> Fasih/WEBREL-2885/ Fixed tablet view spacing issue

- packages/core/src/App/Components/Layout/Footer/toggle-language-settings.tsx
- packages/core/src/App/Components/Layout/Header/Components/ToggleMenu/mobile-language-menu.tsx
The word "Select Language" is not getting translated after changing the language to anything other than English.
> [COJ]/likhith/fix: title of language change modal

- packages/appstore/webpack.config.js
> Niloofar/ trustpilot issue

- packages/wallets/src/components/WalletAddedSuccess/WalletAddedSuccess.tsx
- packages/wallets/src/components/WalletCard/WalletCard.scss
- packages/wallets/src/components/WalletCard/WalletCard.tsx
- packages/wallets/src/components/WalletCard/__tests__/WalletCard.spec.tsx
- packages/wallets/src/components/WalletsAddMoreCardBanner/WalletsAddMoreCardBanner.tsx
- packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
- packages/wallets/src/features/cashier/modules/Transfer/components/TransferReceipt/TransferReceipt.tsx
- packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoReceipt/WithdrawalCryptoReceipt.tsx
- packages/wallets/src/features/cfd/modals/MT5AccountAdded/MT5AccountAdded.tsx
- packages/wallets/src/features/cfd/modals/MT5AccountAdded/__tests__/MT5AccountAdded.spec.tsx
- packages/wallets/src/features/cfd/screens/CFDSuccess/CFDSuccess.tsx
> [WALL] Lubega / WALL-4431 / Remove badge from wallet card

- packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/__test__/AddedDxtradeAccountsList.spec.tsx
Added test case for AddedDxtradeAccountsList
> Aizad/WALL-2936/Unit test for AddedDxtradeAccountsList in Dxtrade flow

- packages/cfd/src/Stores/Modules/CFD/cfd-store.js
* Set the company type to "SVG" when creating a demo account.
> [CFDS]/Hasan/CFDS-4030/mt5 demo account's company input issue

- packages/trader/src/Stores/Modules/Trading/trade-store.ts
This PR addresses and resolves several MobX warnings within the trader-store module, enhancing the stability and performance of the application.
> [DTRA] Bala/Fix trader-store mobx warnings

- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/Stores/client-store.js
Reverts binary-com/deriv-app#15720
> Revert "chore: redirect to login and from login for email request modal"

- packages/p2p/src/pages/my-ads/my-ads.scss
Screen issue with myads page in firefox browser
After
https://github.com/binary-com/deriv-app/assets/122768621/a07316e1-87c9-41d4-a755-5b1cf872d6ca
Before
https://github.com/binary-com/deriv-app/assets/122768621/4d793e65-dfd8-4e4b-b5e6-b10bd070161b
> [P2PS] - Nada/2788/fix: issue with my ads page in firefox browser

- packages/p2p/src/components/modal-manager/modals/preferred-countries-modal/__tests__/preferred-countries-modal.spec.tsx
- packages/p2p/src/components/modal-manager/modals/preferred-countries-modal/preferred-countries-modal.tsx
- Clear the list if Clear is clicked
- Added test cases
https://github.com/binary-com/deriv-app/assets/103412909/697a6549-f6d8-481e-b725-c8dc0cd6721a
https://github.com/binary-com/deriv-app/assets/103412909/2deebee5-96bd-4b37-b6f7-e03b5cbf0a6d
> [P2PS] / Ameerul / P2PS-3051 Clicking on Clear button is not unchecking the preferred country list

- package-lock.json
- packages/bot-web-ui/package.json
- packages/core/package.json
- packages/trader/package.json
This PR updates @deriv/deriv-charts to 2.1.24
> Update deriv-charts to 2.1.24

- packages/bot-web-ui/src/stores/app-store.ts
fix: allow Japan and Norway to use the Bot platform
> [BOT]maryia/BOT-1969/fix: allow Japan and Norway to use the Bot platform

- package-lock.json
- packages/account/package.json
- packages/appstore/package.json
- packages/cfd/package.json
- packages/core/package.json
Fix @deriv-com/translations version to 1.3.3
> fix: remove_khmer_language_from_langugaes_list

- packages/core/src/sass/app/_common/components/account-common.scss
Issue: white page when we upload documents in POI page and status of POI does not pop up in responsive view.
Recreate issue :   
1. On POI page select Kenya from the dropdown
2. upload the documents in mobile or tablet view 
3. white blank page pops up
> Dhruv/webrel 2896/poi status page fix

- packages/appstore/src/components/add-options-account/add-options-account.tsx
- packages/appstore/src/components/banners/wallets-banner/wallets-banner-upgrade.tsx
- packages/appstore/src/components/cfds-listing-logged-out/cfds-listing-logged-out.tsx
- packages/appstore/src/components/cfds-listing/index.tsx
- packages/appstore/src/components/compare-account/compare-account.tsx
- packages/appstore/src/components/containers/trading-app-card-actions.tsx
- packages/appstore/src/components/containers/trading-app-card.tsx
- packages/appstore/src/components/currency-switcher-card/demo/demo-account-card.tsx
- packages/appstore/src/components/get-started-trading-banner/get-started-trading-banner.tsx
- packages/appstore/src/components/main-title-bar/asset-summary.tsx
- packages/appstore/src/components/main-title-bar/index.tsx
- packages/appstore/src/components/main-title-bar/regulators-switcher.tsx
- packages/appstore/src/components/modals/failed-veriification-modal/failed-verification-modal.tsx
- packages/appstore/src/components/modals/open-positions-svg-modal/open-positions-svg-modal.tsx
- packages/appstore/src/components/modals/regulators-compare-modal/regulators-compare-modal-content.tsx
- packages/appstore/src/components/modals/regulators-compare-modal/regulators-compare-modal.tsx
- packages/appstore/src/components/modals/wallets-upgrade-modal/wallets-upgrade-modal.tsx
- packages/appstore/src/components/multi-action-button-group/multi-action-button-group.tsx
- packages/appstore/src/components/options-multipliers-listing/index.tsx
- packages/appstore/src/components/routes/routes.tsx
- packages/appstore/src/components/trade-button/trade-button.tsx
- packages/appstore/src/modules/Page404/Components/Page404.tsx
- packages/appstore/src/modules/traders-hub/index.tsx
- packages/translations/src/components/localize.jsx
- packages/translations/src/i18next/i18next.ts
This reverts commit 8a5f2d45c09552d6a22977789b35ee1f1c8b67d4 (https://github.com/binary-com/deriv-app/pull/15430)
> Revert "Sergei / Fix Localize issue (#15430)"

- packages/p2p/src/pages/app.scss
https://github.com/binary-com/deriv-app/assets/122768621/c8c12518-920b-416f-9f11-7b6003ddf252
> [P2PS]- Nada/3162/fix: responsive tabs not scrolling

- packages/p2p/src/pages/my-ads/edit-ad-form.jsx
String was not wrapped in localize function. Fixed it.
> [P2PS] - Nada/P2PS-3086/fix: translation handle for edit ad header

- packages/p2p/src/stores/general-store.js
- Made status default to an empty array.
- Fixed this.hideModal is undefined console error issue when cashier has maintenance
> [FEQ] / Ameerul / FEQ-2028 [TrackJS] Error:Cannot read properties of undefined (reading 'includes')

- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/inputs/qs-input.tsx
Placeholder value changes from 0.00 to 0 after user edits the field
> [BOT]maryia/BOT-1683/feat: Placeholder value changes from 0.00 to 0 after user edits the field

- packages/bot-web-ui/src/stores/run-panel-store.ts
fix TrackJS error Cannot read properties of undefined (reading 'shouldRestartOnError')
> [BOT]maryia/BOT-1889/fix: Cannot read properties of undefined (reading 'shouldRestartOnError')

- packages/p2p/src/components/floating-rate/floating-rate.tsx
- packages/p2p/src/components/modal-manager/modals/block-user-filter-modal/block-user-filter-modal.tsx
- packages/p2p/src/components/modal-manager/modals/filter-modal/__tests__/filter-modal.spec.tsx
- packages/p2p/src/components/modal-manager/modals/invalid-verification-link-modal/__tests__/invalid-verification-link-modal.spec.tsx
- packages/p2p/src/components/modal-manager/modals/order-details-confirm-modal/order-details-confirm-modal.tsx
- packages/p2p/src/pages/my-profile/block-user/block-user-table/block-user-table-error/__tests__/block-user-table-error.spec.tsx
> Nada/fix: sonar issues

- package-lock.json
- packages/account/package.json
- packages/core/package.json
- packages/trader/package.json
Fix text not bold issue
Before:
After:
> Suisin/fix: text not bold in email and password page

- package-lock.json
- package.json
- packages/account/package.json
- packages/api-v2/package.json
- packages/appstore/package.json
- packages/cashier-v2/package.json
- packages/cfd/package.json
- packages/components/package.json
- packages/core/package.json
- packages/hooks/package.json
- packages/reports/package.json
- packages/shared/package.json
- packages/trader/package.json
- packages/wallets/package.json
- packages/wallets/src/AppContent.tsx
> Feq 2494 update @deriv com/analytics package to v1.9.0 in deriv app

- packages/trader/README.md
Update the naming conventions of dtrader
> Update the naming conventions of dtrader

- packages/core/src/root_files/localstorage-sync.html
- add staging-hub as allowed domains for storage sync
> chore: add staging-hub as allowed domains for storage sync

- packages/trader/src/AppV2/Hooks/__tests__/useOrderDetails.spec.tsx
- packages/trader/src/AppV2/Hooks/useOrderDetails.ts
Some fixes are added in the PR . It includes
- Strike price and Duration sequence is maintained now in order details
- Added Currency in Payout per point
> Ahmad/DTRA-1408/Fix Vanilla Contract in Contract Details V2

- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_create_with.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_getIndex.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_getSublist.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_indexOf.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_isEmpty.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_length.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_repeat.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_setIndex.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_sort.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_split.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/List/lists_statement.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/Loops/controls_flow_statements.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/Loops/controls_for.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/Loops/controls_forEach.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/Loops/controls_repeat.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/Loops/controls_repeat_ext.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/Loops/controls_whileUntil.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/Variable/variables_get.js
- packages/bot-skeleton/src/scratch/blocks/Advanced/Variable/variables_set.js
- packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/accumulator_take_profit.js
- packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_candleinterval.js
- packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_contracttype.js
- packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_market.js
- packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_restartbuysell.js
- packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_restartonerror.js
- packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_tradetype.js
- packages/bot-skeleton/src/scratch/utils/index.js
> Rupato/BOT-2013/fix: added missing translations for blockly context menu

- packages/wallets/component-tests/wallets-carousel-content.spec.tsx
> [WALL] Jim/WALL-4588/fix failing tests

- packages/core/src/App/Containers/Redirect/redirect.jsx
Fixed console error by adding use effect
> Fasih/COJ-1341/ Fixed console error by adding use effect

- packages/account/src/Components/additional-kyc-info-modal/additional-kyc-info-form.tsx
- packages/account/src/Components/forms/personal-details-form.jsx
- packages/account/src/Components/personal-details/__tests__/personal-details.spec.tsx
Enable tooltip again
Reverts binary-com/deriv-app#16048
> Fasih/TRAH-3827/ Enable tooltip again

- packages/core/src/App/Components/Elements/LandscapeBlocker/landscape-blocker.tsx
- packages/trader/src/App/Components/Elements/TogglePositions/toggle-positions-mobile.tsx
- to hide recent positions modal and show landscape blocker for contract details and reports
> [DTRA] henry/webrel-3029/hotfix: hide recent positions modal and show landscape blocker for contract details and reports

- packages/bot-web-ui/src/components/trade-animation/trade-animation.scss
- packages/bot-web-ui/src/components/trade-animation/trade-animation.tsx
- packages/bot-web-ui/src/pages/tutorials/tutorials.scss
- Fixed the run button colors when running and stopping bot status
- Improved the play button on the tutorials tab guide videos
https://github.com/user-attachments/assets/1528fb3c-6972-4287-a20a-bc3d3435926e
> [BOT] Farabi/bot-1624/ui inconsistencies on dashboard

- .github/workflows/build_docker_passkey_image.yml
Added yml file to ease deployment for passkey from FE
> Suisin/chore: added yml file to ease deployment for passkey

- vercel.dr.json
Removes the cleanUrl key from vercel.dr.json
> fix: removed clean urls from vercel dr json

- __mocks__/translation.mock.js
- packages/account/src/Components/financial-details/financial-details-partials.tsx
- packages/account/src/Components/trading-assessment/risk-tolerance-warning-modal.tsx
- packages/account/src/Components/trading-assessment/test-warning-modal.tsx
- packages/account/src/Components/trading-assessment/trading-assessment-dropdown.tsx
- packages/account/src/Components/trading-assessment/trading-assessment-form.tsx
- packages/account/src/Configs/financial-details-config.ts
- packages/account/src/Containers/toast-popup.tsx
- packages/account/src/Sections/Assessment/FinancialAssessment/financial-assessment.tsx
- packages/account/src/Sections/Assessment/FinancialAssessment/financial-information-list.ts
- packages/account/src/Sections/Assessment/TradingAssessment/trading-assessment.jsx
The Assessment section under Account settings now fetched translations from deriv-com/translations replacing the old library
> chore: replace localize import with new library

- vercel.dr.json
This is to override the installCommand of vercel on DR step.
> Ako/ override installCommand of vercel

- .github/workflows/release_staging.yml
- vercel.dr.json
> Ako/ fix vercel dr install

- .github/workflows/build_docker_image.yml
> Ako/ change env usage on docker creator workflow

- packages/bot-web-ui/src/pages/server-side-bot/add-bot/add-bot.tsx
- packages/bot-web-ui/src/pages/server-side-bot/add-bot/config.ts
- packages/bot-web-ui/src/pages/server-side-bot/add-bot/form.tsx
- packages/bot-web-ui/src/pages/server-side-bot/add-bot/inputs/qs-text-input.scss
- packages/bot-web-ui/src/pages/server-side-bot/add-bot/inputs/qs-text-input.tsx
- packages/bot-web-ui/src/pages/server-side-bot/add-bot/types.ts
- packages/bot-web-ui/src/pages/server-side-bot/bot-list/bot-list.tsx
- packages/bot-web-ui/src/stores/server-side-bot-store.ts
- Added new input field for text component
- Fix  multi bot running issue
> [BOT] Shafin/bot/chore  server side bot journal

- packages/wallets/src/App.tsx
https://github.com/user-attachments/assets/44255435-4c9e-49d9-a2be-b34c7da50704
https://github.com/user-attachments/assets/238c9caf-2494-40b6-b69d-e58b9033887b
> [WALL] Lubega / WEBREL-3040 / Responsive modal popup fix

- packages/bot-web-ui/src/stores/load-modal-store.ts
- updated file names
- updated extension name
> fix: :fire: updated file names

- package-lock.json
- package.json
- packages/account/package.json
- packages/api-v2/package.json
- packages/appstore/package.json
- packages/cfd/package.json
- packages/core/package.json
- packages/hooks/package.json
- packages/reports/package.json
- packages/shared/package.json
- packages/trader/package.json
- packages/wallets/package.json
This is to update the analytics package to send geo_location as well as handle the caching mechanism in case rudderstack is not available yet.
> Ako/ update analytics package to version 1.11.0

- packages/bot-web-ui/src/pages/server-side-bot/bot-list/bot-list.tsx
Server Side Bot (Behind the endpoint feature flag and country of residence check)
- Typo fix
> [BOT] sandeep/server-bot-typo-fix

- packages/trader/src/AppV2/Components/ClosedMarketMessage/closed-market-message.tsx
> fix: build failure

- packages/cashier/src/components/cashier-locked/cashier-locked.scss
- packages/cashier/src/components/page-container/page-container.scss
- packages/cashier/src/components/page-container/page-container.tsx
- packages/cashier/src/containers/cashier/cashier.scss
- packages/cashier/src/containers/cashier/cashier.tsx
- packages/cashier/src/pages/account-transfer/__tests__/account-transfer.spec.tsx
- packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.scss
- packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.tsx
- packages/cashier/src/pages/account-transfer/account-transfer-receipt/account-transfer-receipt.scss
- packages/cashier/src/pages/account-transfer/account-transfer-receipt/account-transfer-receipt.tsx
- packages/cashier/src/pages/account-transfer/account-transfer.tsx
- packages/cashier/src/pages/on-ramp/__tests__/on-ramp.spec.tsx
- packages/cashier/src/pages/on-ramp/on-ramp.scss
- packages/cashier/src/pages/on-ramp/on-ramp.tsx
- packages/cashier/src/pages/payment-agent-transfer/__tests__/payment-agent-transfer.spec.tsx
- packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer-form/payment-agent-transfer-form.tsx
- packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer.tsx
- packages/cashier/src/pages/payment-agent/__tests__/payment-agent.spec.tsx
- packages/cashier/src/pages/payment-agent/payment-agent-list/payment-agent-list.scss
- packages/cashier/src/pages/payment-agent/payment-agent.tsx
- packages/cashier/src/pages/withdrawal/withdrawal-crypto-form/withdrawal-crypto-form.tsx
- packages/cashier/src/pages/withdrawal/withdrawal-crypto-receipt/withdrawal-crypto-receipt.scss
- packages/cashier/src/pages/withdrawal/withdrawal-crypto-receipt/withdrawal-crypto-receipt.tsx
- packages/cashier/src/pages/withdrawal/withdrawal.tsx
- packages/components/src/components/page-overlay/page-overlay.scss
- packages/p2p/src/components/cashier-under-maintenance/cashier-under-maintenance.scss
- Transfer page header doesn't have top padding for mobile and tablet screens.
- Lock screens doesn't have top padding for mobile and tablet screens.
- Transfer to clients page doesn't have top padding for mobile and tablet screens.
- Close button in page overlay is not aligned to the account switcher chevron icon.
- Crypto address and copy icons not on the same line in Crypto withdrawal receipt.
> Nijil / WALL-4548 / Fix UI issues raised for Cashier Tablet UI

- .github/workflows/sync-translations.yml
> [WALL] Lubega / WALL-4641 / Failing sync translations workflow

- packages/bot-skeleton/src/scratch/blocks/Logic/controls_if.js
- packages/bot-skeleton/src/scratch/hooks/flyout_base.js
Blockly V10
Post release of Blockly Update, Fixing the + method for if, else block
updated the blockly mutator method
> Rupato/fix: controls if statement

- packages/cfd/src/Constants/jurisdiction-contents/jurisdiction-bvi-contents.ts
- packages/cfd/src/Constants/jurisdiction-contents/jurisdiction-labuan-contents.ts
- packages/cfd/src/Constants/jurisdiction-contents/jurisdiction-svg-contents.ts
- packages/cfd/src/Constants/jurisdiction-contents/jurisdiction-vanuatu-contents.ts
- packages/cfd/src/Containers/cfd-compare-accounts/__tests__/cfd-compare-accounts-description.spec.tsx
- packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-card.spec.tsx
- packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-modal-content.spec.tsx
- packages/cfd/src/Helpers/compare-accounts-config.ts
Update pips values for compare accounts table and for CFD cards too
> [TRAH] Sergei / TRAH - 3844 / Compare account Table Pips (spread) update

- packages/appstore/src/components/modals/modal-manager.tsx
Remove lazy load of `cfd reset password modal`
> [WEBREL] Sergei / WEBREL - 3054 / Change Investor Password Link is Not Working

- packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-checkbox.tsx
- packages/cfd/src/sass/cfd.scss
- packages/core/src/sass/app/_common/base/common.scss
* Updated jurisdiction-modal-checkbox component's design.
> [CFDS]/Hasan/CFDS-4260/tnc design update

- .github/workflows/build_docker_image.yml
edit workflows on build docker image 
> Suisin/chore: edit workflows on build docker image

- packages/appstore/src/components/cfds-listing/cfds-listing.scss
- packages/appstore/src/components/modals/open-positions-svg-modal/__test__/open-positions-svg-modal.spec.tsx
- packages/appstore/src/components/modals/open-positions-svg-modal/open-positions-svg-modal.tsx
- packages/cfd/src/Components/migration-success-modal/__tests__/migration-success-modal-content.spec.tsx
- packages/cfd/src/Components/migration-success-modal/migration-success-modal-content.tsx
- packages/cfd/src/Components/migration-success-modal/migration-success-modal.tsx
Updated modal content and design
> Fasih/COJ-1146/ Updated modal content and design

- packages/wallets/src/features/accounts/screens/PersonalDetails/PersonalDetails.tsx
- Added empty list message to the dropdown
- Added functionality to clear previous value incase the currently selected value is invalid
> [WALL] Jim/WEBREL-3064/add empty list message for citizenship dropdown

- packages/wallets/src/components/DerivAppsSection/__test__/DerivAppsGetAccount.spec.tsx
- packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/__tests__/CryptoTransaction.spec.tsx
> Jim/wall 4713/deriv apps get account test cases

- packages/bot-web-ui/src/app/app-content.jsx
- FIxed dbot not loading issue for CRW (wallet) accounts
> [WEBREL] Farabi/webrel-3071/dbot not loading for CRW account

- packages/cashier/src/components/crypto-fiat-converter/crypto-fiat-converter.scss
Fix the text alignment for transfer input fields.
> [WEBREL] aum/WEBREL-3077/cashier-transfer-input-cursor-position

- packages/appstore/src/components/banners/business-closure-banner/business-closure-banner.tsx
- Removed the line break from the string inside the Localize component to fix translation issues for senegal account closure banner on traders hub page.
> [WEBREL] Farabi/webrel-3079/translation-for-senegal-account-closure-banner

- packages/trader/src/AppV2/Components/ContractCard/contract-card-status-timer.tsx
- packages/trader/src/AppV2/Components/PurchaseButton/purchase-button.tsx
- packages/trader/src/AppV2/Containers/Notifications/notifications.tsx
Added keys to some Quill components props as it caused console errors, which are visible only in test links
> DTRA / Kate / DTRA-1594 / console error fix

- packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/__tests__/accumulators-trade-description.spec.tsx
- packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/__tests__/multiplier-trade-description.spec.tsx
- packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/__tests__/turbos-trade-description.spec.tsx
- packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/__tests__/vanillas-trade-description.spec.tsx
- packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/accumulators-trade-description.tsx
- packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/multipliers-trade-description.tsx
- packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/turbos-trade-description.tsx
- packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/vanillas-trade-description.tsx
- packages/trader/src/AppV2/Components/Guide/Description/trade-description.tsx
- packages/trader/src/AppV2/Components/Guide/__tests__/guide-definition-modal.spec.tsx
- packages/trader/src/AppV2/Components/Guide/__tests__/guide.spec.tsx
- packages/trader/src/AppV2/Components/Guide/guide-definition-modal.tsx
- packages/trader/src/AppV2/Components/Guide/guide-description-modal.tsx
- packages/trader/src/AppV2/Components/Guide/guide.scss
- packages/trader/src/AppV2/Components/Guide/guide.tsx
- packages/trader/src/AppV2/Utils/__tests__/contract-description.spec.tsx
- packages/trader/src/AppV2/Utils/contract-description-utils.tsx
Contains bug fixes for:
- Glossary title (term) was not translated in any of the languages without refreshing the page
- The video player was not fully fitting the screen
+Refactored tests
> DTRA / Kate / DTRA-1434 / Guide component bug fixes

- packages/wallets/src/components/WalletGradientBackground/WalletGradientBackground.tsx
- packages/wallets/src/components/WalletGradientBackground/__test__/WalletGradientBackground.spec.tsx
- added unit test `WalletGradientBackground`
> [WALL] Aizad/WALL-2891/Unit test for WalletGradientBackground component

- packages/core/src/App/Containers/AccountSignupModal/account-signup-modal.jsx
- packages/core/src/App/Containers/PasswordSelectionModal/password-selection-modal.jsx
- packages/core/src/Utils/Analytics/analytics.ts
- packages/core/src/Utils/Analytics/index.ts
- packages/core/src/index.tsx
Country screen data tracking value is coming lesser than that of password screen.This issue is fixed in this PR by creating a cache method for storing the events in the localstorage when the rudderstack is not loaded.
> Aswathy/fix: test analytics for country screen

- packages/p2p/src/pages/my-profile/__tests__/my-profile.spec.tsx
- packages/p2p/src/pages/my-profile/my-profile.tsx
- added is_p2p_user === false check to ensure the user is not a p2p user, 
https://github.com/user-attachments/assets/59905126-113d-4162-8b7f-a60cf152a892
> [WEBREL] / Ameerul / WEBREL-3084 Nickname pop is getting displayed in my profile page for P2P advertiser whose nickname is already added 

- packages/wallets/src/components/SentEmailContent/SentEmailContent.tsx
- packages/wallets/src/components/SentEmailContent/__test__/SentEmailContent.spec.tsx
- added unit test for SentEmailContent
> Aizad/WALL-2882/Unit Test SentEmailContent

- packages/wallets/src/features/cashier/context/__tests__/CashierScrollContext.spec.tsx
- packages/wallets/src/features/cashier/helpers/__tests__/helpers.spec.ts
- packages/wallets/src/features/cashier/helpers/__tests__/transaction-helpers.spec.tsx
- packages/wallets/src/features/cashier/helpers/transaction-helpers.tsx
> [WALL] Lubega / WALL-4746 / Wallets cashier helpers unit test

- packages/wallets/src/features/cashier/screens/DepositErrorScreen/__tests__/DepositErrorScreen.spec.tsx
- packages/wallets/src/features/cashier/screens/TransferNotAvailable/__tests__/TransferNotAvailable.spec.tsx
- packages/wallets/src/features/cashier/screens/TransferNotAvailable/__tests__/TransferNotAvailableProvider.spec.tsx
- packages/wallets/src/features/cashier/screens/WithdrawalErrorScreen/__tests__/WithdrawalErrorScreen.spec.tsx
- packages/wallets/src/features/cashier/screens/WithdrawalNoBalance/__tests__/WithdrawalNoBalance.spec.tsx
> [WALL] Lubega / WALL-4747 / TransferNotAvailable and cashier screens unit test

- packages/core/src/public/.well-known/assetslinks.json
Update the certificate in assetlinks.json
> [P2PS] farrah/P2PS-3323/fix: update assetlinks.json

- packages/wallets/src/features/cfd/modals/MT5AccountAdded/MT5AccountAdded.tsx
- packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
- packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModalFooters.tsx
Reverts binary-com/deriv-app#16383
> Revert "[WALL] Aizad/WALL-4274/FIx Success Button on MT5 Account Added Modal"

- packages/core/src/App/Components/Layout/Header/signup-button.jsx
We need to implement Feature flag for Signup button in High code along with user agent for devices except iOS.
> Niloofar/Implemented Feature flag for Signup button

- packages/trader/src/App/Components/Elements/TogglePositions/toggle-positions-mobile.tsx
- Removed unnecessary check for `has_wallet`
https://github.com/user-attachments/assets/0aa2b011-0017-496b-aab9-24b5651f21f3
https://github.com/user-attachments/assets/2ce7a3e0-5e61-408d-a8f6-66f9fde64411
> [WALL] Jim/WALL-4610/remove unnecessary check for has_wallet

- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/__tests__/form.spec.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/trade-type.tsx
- packages/bot-web-ui/src/pages/server-side-bot/add-bot/__tests__/form.spec.tsx
- packages/bot-web-ui/src/pages/server-side-bot/add-bot/selects/trade-type.tsx
Bug Fixing
- Empty fields shown on quick strategy modal and add bot form in server-bot feature
NA
> [BOT] sandeep/bot-2145/fix Fixed empty tradetype field being shown in quick strategy

- packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.tsx
- packages/cfd/src/Containers/cfd-server-maintenance-modal.tsx
- packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/tradingPlatformStatusMessageFn.tsx
- packages/wallets/src/features/cfd/screens/TradingPlatformStatus/TradingPlatformStatus.tsx
> [CFDS] shontzu/CFDS-4554/to-fix-the-typo-Maybe-in-server-maintenance-badge

- packages/bot-web-ui/src/pages/dashboard/announcements/__tests__/announcement-dialog.spec.tsx
- packages/bot-web-ui/src/pages/dashboard/announcements/__tests__/announcements.spec.tsx
- packages/bot-web-ui/src/pages/dashboard/announcements/announcements.tsx
> refactor: improvement accourding to comments

- packages/bot-web-ui/src/pages/dashboard/announcements/__tests__/announcement-dialog.spec.tsx
- packages/bot-web-ui/src/pages/dashboard/announcements/__tests__/announcements.spec.tsx
- packages/bot-web-ui/src/pages/dashboard/announcements/announcements.tsx
> feat: adapt Notifications component

- packages/wallets/src/features/cfd/screens/CFDSuccess/CFDSuccess.tsx
- packages/wallets/src/features/cfd/screens/CFDSuccess/__test__/CFDSuccess.spec.tsx
> [WALL] Lubega / WALL-2946 / CFDSuccess unit test

- packages/wallets/src/features/cfd/screens/DynamicLeverage/DynamicLeverageMarketCard.tsx
- packages/wallets/src/features/cfd/screens/DynamicLeverage/DynamicLeverageScreen.tsx
- packages/wallets/src/features/cfd/screens/DynamicLeverage/DynamicLeverageTitle.tsx
- packages/wallets/src/features/cfd/screens/DynamicLeverage/__tests__/DynamicLeverageMarketCard.spec.tsx
- packages/wallets/src/features/cfd/screens/DynamicLeverage/__tests__/DynamicLeverageScreen.spec.tsx
- packages/wallets/src/features/cfd/screens/DynamicLeverage/__tests__/DynamicLeverageTableColumnHeader.spec.tsx
- packages/wallets/src/features/cfd/screens/DynamicLeverage/__tests__/DynamicLeverageTitle.spec.tsx
> [WALL] Lubega / WALL-2949 / Dynamic leverage unit test

- packages/appstore/src/modules/traders-hub/traders-hub.scss
Add margin for clevertap banner in Trader's Hub
> [TRAH] Sergei / Add margin for clevertap banner in Trader's Hub

- packages/bot-web-ui/src/pages/tutorials/guide-content/__tests__/guide-content.spec.tsx
- packages/bot-web-ui/src/pages/tutorials/guide-content/guide-content.tsx
test: [Test Coverage] Folder: bot-web-ui/src/pages/tutorials/guide-co
> [BOT]maryia/test: [Test Coverage] Folder: bot-web-ui/src/pages/tutorials/guide-content

- packages/appstore/src/modules/traders-hub/traders-hub.scss
Add margin to wrapper instead of children for clevertap banner in Trader's Hub
> [TRAH] Sergei / Add margin to wrapper instead of children for clevertap banner in Trader's Hub 

- packages/trader/src/AppV2/Components/Guide/guide.tsx
- packages/trader/src/AppV2/Components/TradeParameters/Stake/stake.tsx
- packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.tsx
> [DTRA] henry/dtra-1708/fix: resolve console errors in dtrader v2

- packages/core/src/App/Components/Layout/Header/signup-button.jsx
Updated the existing code to ensure that Growthbook is fully loaded before assigning or using any feature flags. This will prevent any potential issues with undefined or incorrect flag values being used in the application logic.
> Niloofar / Added a condition to ensure that Growthbook is fully loaded before assigning or using any feature flags

- packages/cashier/src/pages/on-ramp/__tests__/on-ramp.spec.tsx
- packages/cashier/src/pages/on-ramp/on-ramp.tsx
- add onMount function into onRamp page
> [WALL] / george / WALL-4812 / Banxa is not working for any crypto currencies

- packages/bot-web-ui/src/pages/tutorials/guide-content/__tests__/guide-content.spec.tsx
> [BOT]maryia/test: improve guide-content

- packages/bot-web-ui/src/components/load-modal/__tests__/load-modal.spec.tsx
- packages/bot-web-ui/src/pages/server-side-bot/add-bot/add-bot.tsx
- packages/bot-web-ui/src/pages/server-side-bot/add-bot/inputs/add-text-input.tsx
- Fix the issue of empty name being submit for server bot
- Fix test case failure on load modal tests
> shafin/fix: server bot empty name save issue fix

- packages/core/src/App/Containers/Redirect/redirect.jsx
- using the redirect route, add an action named `livechat` to open the live chat after redirecting the user to Deriv App.
https://github.com/user-attachments/assets/9251d92f-bc8e-4843-98bd-278442915e36
> [TRAH-4046] shahzaib / added action to open live chat

- packages/trader/src/AppV2/Components/AccumulatorStats/accumulator-stats-description.tsx
- packages/trader/src/AppV2/Components/AccumulatorStats/accumulator-stats.scss
- packages/trader/src/Modules/Trading/Helpers/video-config.ts
This PR adds the video for accumulator stats in the description action sheet . The video is of 16:9 aspect ratio and doesn't depend on absolute width and height.
> [DTRA]/Ahmad/Add Accumulator Stats Video

- packages/account/src/Configs/terms-of-use-config.ts
Make "No" as default value
https://github.com/user-attachments/assets/bf697743-8ba7-40b8-b72c-cb10d0eb3674
> [TRAH] Sergei / TRAH - 3966 / Pre-Select the FATCA declaration as "NO" on T&C page

- packages/core/src/App/Containers/Modals/deposit-now-or-later-modal/deposit-now-or-later-modal.tsx
Don't close both modals when the user click cross icon
https://github.com/user-attachments/assets/6570fba7-60bd-4489-8a4d-784fbfbc6ddf
> [TRAH] Sergei / TRAH - 3959 / To fix Add funds and start trading modal

- packages/wallets/src/features/cashier/screens/DepositErrorScreen/DepositErrorScreen.tsx
- packages/wallets/src/features/cashier/screens/DepositErrorScreen/__tests__/DepositErrorScreen.spec.tsx
> [WALL] Lubega / WALL-4568 / Deposit maintenance error title fix

- packages/p2p/src/pages/orders/chat/__tests__/chat-messages.spec.jsx
- packages/p2p/src/pages/orders/chat/chat-message-text.jsx
- packages/p2p/src/pages/orders/chat/chat-messages.jsx
- packages/p2p/src/pages/orders/chat/chat-messages.scss
- Changed text content for disclaimer message in chat box
> [P2PS] / Ameerul / P2PS-2351 Adding Safety Disclaimer to P2P Chatbox

- .github/workflows/release_staging.yml
> fix: node env value on staging

- packages/trader/src/AppV2/Components/TradeParameters/Duration/container.tsx
- packages/trader/src/AppV2/Components/TradeParameters/Duration/datepicker.tsx
- packages/trader/src/AppV2/Components/TradeParameters/Duration/duration.scss
- packages/trader/src/AppV2/Components/TradeParameters/Duration/wheelpicker.tsx
- packages/trader/src/AppV2/Utils/__tests__/trade-param-utils.spec.tsx
- packages/trader/src/AppV2/Utils/trade-params-utils.tsx
This PR caters all the fixes related to the duration trade params identified by the design team . 
**Duration issues**
Flickering issue when switching between chips
Current time for Endtime should be live time in GMT and font size is wrong
Calendar button for Days should be an icon button from Quill
Left and right padding missing for picker.
Remove scroll bar while chips is scrolling
> [DTRA]/Ahmad/Duration Fixes

- packages/trader/src/AppV2/Components/BottomNav/bottom-nav.scss
- packages/trader/src/AppV2/Components/OnboardingGuide/guide-container.tsx
- packages/trader/src/AppV2/Components/OnboardingGuide/onboarding-guide.scss
- packages/trader/src/AppV2/Components/OnboardingGuide/steps-config.tsx
Changed the position of next button from right to left in onboarding tooltip.
Changed the animation for tooltip
Step 4 scroll to work on entire page
https://github.com/user-attachments/assets/a7f357a1-4c05-4dcb-957c-64cdeec1a645
> [DTRA]fix: fix the animation and scrolling behavior in step 4 for onboarding

- packages/trader/src/AppV2/Containers/ContractDetails/contract-details.scss
> [DTRA-V2]fix: contract details scroll

- packages/bot-skeleton/src/scratch/backward-compatibility.js
- packages/bot-skeleton/src/utils/index.js
- packages/bot-skeleton/src/utils/local-storage.js
- packages/bot-web-ui/src/stores/data-collection-store.ts
Added a check to determine whether this is a DBot strategy on every run and save.
card: https://app.clickup.com/t/20696747/BOT-2117
> Rupato/BOT-2117/fix: adding is dbot to every strategy action

- packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
- packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
- packages/wallets/src/features/cfd/screens/EnterPassword/__test__/EnterPassword.spec.tsx
Added `checked` flag to the disabled prop value 
https://github.com/user-attachments/assets/002196d1-fd9a-4def-a6fa-79ba3eb03f40
https://github.com/user-attachments/assets/f24d0a3b-7be8-44b4-9e10-c864a0cfac31
> [WEBREL] Jim/WEBREL-3159/add account button enabled before tnc is checked

- packages/wallets/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.tsx
https://github.com/user-attachments/assets/8bee10f0-780f-4961-921a-277f4c9335ba
https://github.com/user-attachments/assets/ede61557-11cc-4bad-b44d-c77af184dbce
> [WALL] Lubega / WEBREL-3158 / Zero spread scrolling issue

- packages/wallets/src/features/cfd/modals/JurisdictionModal/JurisdictionModal.scss
- Fix button alignment inside of Jurisdiction Modal
**Before**:
**After**:
> Aizad/WALL-4885/Fix Button alignment in Jurisdiction Modal

- packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
- packages/wallets/src/features/cfd/screens/CreatePasswordMT5/CreatePasswordMT5.tsx
- packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
- Moved terms and conditions state to parent component, so that it's shared by both desktop and mobile
- Made TnC related props optional
https://github.com/user-attachments/assets/1bc048f1-7e3d-4c63-9bac-fd4cd051957b
https://github.com/user-attachments/assets/8a0a2bd2-6f33-4858-9deb-b2ccb274fb91
https://github.com/user-attachments/assets/ded8bfa8-8b32-4be3-bdfa-4704fdd1b9d9
https://github.com/user-attachments/assets/45c639a6-072f-451e-b4df-44051346f3a7
> [WEBREL] Jim/WEBREL-3164/ terms and conditions issue

- package-lock.json
- packages/account/package.json
- packages/appstore/package.json
- packages/cashier/package.json
- packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-info-notice/__test__/deposit-crypto-info-notice.test.tsx
- packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-info-notice/deposit-crypto-info-notice.tsx
- packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-info-notice/index.ts
- packages/cashier/src/modules/deposit-crypto/components/index.ts
- packages/cashier/src/modules/deposit-crypto/deposit-crypto.tsx
- packages/cfd/package.json
- packages/components/package.json
- packages/core/package.json
- packages/core/src/Stores/notification-store.js
- packages/p2p/package.json
- packages/reports/package.json
- packages/trader/package.json
- packages/wallets/package.json
- packages/wallets/src/features/cashier/modules/DepositCrypto/DepositCrypto.scss
- packages/wallets/src/features/cashier/modules/DepositCrypto/DepositCrypto.tsx
- packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoInfoNotice/DepositCryptoInfoNotice.tsx
- packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoInfoNotice/__tests__/DepositCryptoInfoNotice.spec.tsx
- packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoInfoNotice/index.ts
> [WALL] Lubega / WALL-4842 /  tUSDT notice banner and notification

- packages/wallets/src/components/WalletListCardActions/WalletListCardActions.scss
- Fix scss inside of `WalletListCardActions`
**Before**:
**After**:
> [WALL] AIzad/WALL-4895/Reset Balance Misalignment

- packages/appstore/src/components/app-content.tsx
- If user is logged in, visiting {domain}?one_time_deposit=true should trigger one time deposit modal
- After the one time deposit modal, the URL params should be removed.
> [TRAH-4153] shahzaib / one_time_deposit url param to trigger deposit modal if logged in

- packages/wallets/src/features/cfd/components/CFDPasswordModalTnc/CFDPasswordModalTnc.scss
- packages/wallets/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.scss
- packages/wallets/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.tsx
- packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.scss
- packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.scss
> [WEBREL] george / WEBREL-3173 / Zero Spread Alignment issues

- packages/bot-web-ui/src/constants/dashboard.ts
- packages/bot-web-ui/src/pages/dashboard/load-bot-preview/recent-workspace.tsx
added tool tip to dashboard icons
> fix: tooltip added for dashboard icons

- packages/bot-skeleton/src/scratch/utils/index.js
- packages/bot-web-ui/src/stores/load-modal-store.ts
- Fixed upload strategy started event on rudderstack
- Fixed upload strategy complete event
- Fixed upload strategy failed event
> [BOT] Farabi/bot-2205/rudderstack-upload-strategy-complete-event

- packages/bot-web-ui/src/pages/main/__tests__/main.spec.tsx
- packages/bot-web-ui/src/pages/main/main.tsx
- packages/stores/src/mockStore.ts
- packages/stores/types.ts
Added jest test suite for the `<Main />` component
> [BOT] sandeep/test: 🔥 added test suite for main component

- packages/trader/src/AppV2/Components/AccumulatorStats/accumulator-stats-modal.tsx
- packages/trader/src/AppV2/Components/AccumulatorStats/accumulator-stats-row.tsx
- packages/trader/src/AppV2/Components/AccumulatorStats/accumulator-stats.scss
- packages/trader/src/AppV2/Components/AccumulatorStats/accumulator-stats.tsx
- packages/trader/src/AppV2/Components/BottomNav/bottom-nav.scss
- packages/trader/src/AppV2/Components/PurchaseButton/purchase-button.tsx
This PR fixes all the bugs reported by QA for accumulator stats
- Stats arrow showing down when not open and not able to scroll down the previous stats - https://app.clickup.com/t/86c096umn
- Stats bar is sharp edge instead of round edge  - (https://app.clickup.com/t/86c09mtc8)
- Stats green/red gauge are not appear for every running tick  - https://app.clickup.com/t/86c0976w4
- adding loader on the purchase button - https://app.clickup.com/t/86c09mt3p
> [DTRA]/Ahmad/Accumulator fixes

- packages/core/src/Stores/contract-store.js
- packages/trader/src/AppV2/Components/RiskManagementItem/risk-management-item.tsx
This fix enhances the validation logic for take profit and stop loss values, ensuring more accurate and user-friendly error handling.
- Validation Logic: Improve the validation checks for take profit and stop loss inputs, preventing incorrect values from being accepted.
- Error Messaging: Provide clear and informative error messages to guide users when invalid values are entered.
- User Experience: Ensure that validation occurs in real-time, offering instant feedback and improving the overall trading experience.
This fix ensures more robust handling of take profit and stop loss values, leading to a smoother and more reliable trading process for users.
> Akmal / fix: improve take profit and stop loss validation handling

- packages/trader/src/AppV2/Components/CurrentSpot/current-spot-display.tsx
> fix: speed up animation time

- packages/trader/src/AppV2/Components/TradeParameters/Stake/__tests__/stake.spec.tsx
- packages/trader/src/AppV2/Components/TradeParameters/Stake/stake-details.tsx
- packages/trader/src/AppV2/Components/TradeParameters/Stake/stake.tsx
- packages/trader/src/Stores/Modules/Trading/Helpers/proposal.ts
> [DTRA-V2] fix: display max payout

- packages/wallets/src/features/cfd/flows/MT5/AvailableMT5AccountsList/__test__/AvailableMT5AcountsList.spec.tsx
> [WALL] Lubega / WALL-2935 / AvailableMT5AccountsList unit test

- packages/account/src/Sections/Profile/PhoneVerification/__test__/confirm-phone-number.spec.tsx
- packages/account/src/Sections/Profile/PhoneVerification/__test__/otp-verification.spec.tsx
- packages/account/src/Sections/Profile/PhoneVerification/confirm-phone-number.tsx
- packages/account/src/Sections/Profile/PhoneVerification/otp-verification.tsx
> [PNV] - (UPM1501) Suisin/chore: update stepper for pnv flow

- packages/trader/src/AppV2/Components/PurchaseButton/purchase-button.scss
> DTRA-1921 / Kate / [DTrader-V2] The stake details on the purchase button are appearing in black

- packages/core/src/Stores/client-store.js
> fix: [WEBREL-3186]/evgeniy/unable to signup - blank screen

- package-lock.json
- packages/account/package.json
- packages/api-v2/package.json
- packages/api/package.json
- packages/cfd/package.json
- packages/core/package.json
- packages/p2p/package.json
- packages/shared/package.json
- packages/trader/package.json
- packages/wallets/package.json
updating the Utils package.
noticed incorrect work of URLUtils.getDerivStaticURL on previous version.
> webrel-3187 - wrong lang value passed to url

- packages/translations/src/i18next/i18next.ts
while checking the value from localstorage first try to parse it from JSON, then pick the value
> fix: [WEBREL-3185]/evgeniy/dbot is navigated to EN page from non-EN TH page

- packages/account/src/Sections/Profile/PhoneVerification/__test__/phone-verification-card.spec.tsx
- packages/account/src/Sections/Profile/PhoneVerification/__test__/phone-verification-page.spec.tsx
- packages/account/src/Sections/Profile/PhoneVerification/confirm-phone-number.tsx
- packages/account/src/Sections/Profile/PhoneVerification/otp-verification.tsx
- packages/account/src/Sections/Profile/PhoneVerification/phone-verification-card.tsx
- packages/account/src/Sections/Profile/PhoneVerification/phone-verification-page.tsx
- packages/account/src/Sections/Profile/PhoneVerification/phone-verification.scss
- packages/hooks/src/__tests__/usePhoneNumberVerificationSessionTimer.spec.tsx
- packages/hooks/src/usePhoneNumberVerificationSessionTimer.ts
> [PNV] - (UPM1500) Suisin/chore: create expiry count down timer

- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
- packages/account/src/Sections/Profile/PersonalDetails/validation.ts
- packages/account/src/Sections/Profile/PhoneVerification/confirm-phone-number.tsx
- packages/core/src/Services/socket-general.js
strip any characters other than + and numbers for phone number
> [PNV] - (UPM1498) Suisin/chore: strip any characters other than + and numbers for phone number

- packages/cashier/src/containers/cashier/cashier.tsx
- add tablet view support for header
> [WALL] george / WALL-4874 / Transfer to client header is missing in tablet view

- packages/account/src/Sections/Profile/PhoneVerification/__test__/confirm-phone-number.spec.tsx
- packages/account/src/Sections/Profile/PhoneVerification/__test__/otp-verification.spec.tsx
- packages/account/src/Sections/Profile/PhoneVerification/confirm-phone-number.tsx
- packages/account/src/Sections/Profile/PhoneVerification/didnt-get-the-code-modal.tsx
- packages/account/src/Sections/Profile/PhoneVerification/otp-verification.tsx
update content based on latest figma design.
> [PNV] - (UPM1502) Suisin/chore: update content based on latest design

- packages/wallets/src/features/cfd/flows/MT5/AddedMT5AccountsList/__test__/AddedMT5AccountsList.spec.tsx
> [WALL] Lubega / WALL-2934 / AddedMT5AccountsList unit test

- packages/core/src/Utils/Hotjar/index.ts
adding check for undefined value
> [UPM-1598]/evgeniy/trackJS error, reading passkeys_list.length

- packages/core/src/App/Containers/NotificationsDialog/notification-list-wrapper.tsx
- packages/core/src/App/Containers/NotificationsDialog/notifications-dialog.tsx
- packages/core/src/sass/app/modules/notifications-dialog.scss
> [TRAH] george / TRAH-3946 / Notification is truncated in CFD compare account and Wallet cashier page

- packages/api-v2/src/AuthProvider.tsx
- packages/api-v2/src/__tests__/useSubscription.spec.tsx
- packages/api-v2/src/useSubscription.ts
- fix subscribe method (remove onError callback) and handle it in catch block
https://github.com/user-attachments/assets/44742810-4022-4741-aa42-9e470b57ffd0
> [WALL] george / WALL-4929 / Noticing that crypto estimation fee is not displayed

- packages/trader/src/AppV2/Components/PurchaseButton/purchase-button.tsx
- Changed conditions for showing 'Close' button and for showing animation 
https://github.com/user-attachments/assets/b746bc29-3f84-49ac-848b-c2c6912025ba
> DTRA-1959 / Kate / [DTrader-V2]: Close button for Acc is visible for other contracts

- packages/account/src/Sections/Profile/PhoneVerification/__test__/cancel-phone-verification-modal.spec.tsx
- packages/account/src/Sections/Profile/PhoneVerification/cancel-phone-verification-modal.tsx
- packages/account/src/Sections/Profile/PhoneVerification/otp-verification.tsx
- packages/hooks/src/usePhoneNumberVerificationSessionTimer.ts
fix growthbook FF off pnv routing issue
> [PNV] UPM1635 Suisin/chore: fix growthbook FF off pnv routing issue

- packages/trader/src/AppV2/Components/ForwardStartingBanner/__tests__/forward-starting-banner.spec.tsx
- packages/trader/src/AppV2/Hooks/__tests__/useOrderDetails.spec.tsx
> DTRA / Kate / Fix failing tests

- packages/trader/src/AppV2/Components/OnboardingGuide/GuideForPages/steps-config.tsx
- Changed css selector after library update 
Thank you Vinu for help! 
https://github.com/user-attachments/assets/076f2ca7-49e3-4773-b5f1-c104b447eca0
> DTRA-2014 / Kate / [DTrader-V2] Broken trade onboarding after Step 3

- packages/trader/src/AppV2/Components/OnboardingGuide/GuideForPages/__tests__/onboarding-guide.spec.tsx
- packages/trader/src/AppV2/Components/OnboardingGuide/GuideForPages/onboarding-guide.tsx
- packages/trader/src/AppV2/Containers/Positions/positions.tsx
This feature introduces a delay for the position card animation until the onboarding process is completed, enhancing the user experience during initial interactions.
1. Animation Delay: Implement a mechanism to delay the position card animation, ensuring it does not trigger while the onboarding is active.
2. User Interface Integration: Update the UI logic to check the onboarding status before executing the position card animation.
3. Seamless Transition: Ensure that once onboarding is closed, the position card animation plays smoothly, providing a polished and engaging experience.
This change aims to minimize distractions during onboarding, allowing users to focus on essential initial steps before interacting with the position cards.
> Akmal / feat: delay position card animation until onboarding is closed

- .github/workflows/push_and_pull_crowdin_translations.yml
> ako/ update translations workflow condition

- packages/core/src/App/AppContent.tsx
- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/Layout/default-footer.jsx
- packages/core/src/App/Containers/Layout/trading-hub-footer.jsx
- packages/hooks/src/useIsGrowthbookLoaded.ts
Reverts deriv-com/deriv-app#16726
> Revert "[TRAH] Sergei / TRAH - 4040 / Feature toggles doesn't work as expected for initial loading in TH"

- .github/workflows/push_and_pull_crowdin_translations.yml
This is to update the sync translations workflow if condition. 
> ako/ update translations workflow if condition

- .github/CODEOWNERS
- .github/workflows/automationrc.json
- .github/workflows/generate_and_push_deriv_api_types.yml
- .github/workflows/push_and_pull_crowdin_translations.yml
- .github/workflows/remote_config_pr.yml
- README.md
- docs/Stylesheet/README.md
- packages/account/package.json
- packages/cashier/package.json
- packages/cfd/package.json
- packages/components/README.md
- packages/core/package.json
- packages/indicators/package.json
- packages/p2p/scripts/update-translations.sh
- packages/reports/package.json
- packages/shared/package.json
- packages/trader/package.json
- packages/translations/README.md
- packages/translations/package.json
To update the repo name globally in the repo.
> Ako/ update the repo name globally

- packages/shared/src/utils/config/platform-config.ts
- packages/shared/src/utils/platform/platform.ts
Add back to p2p button for redirection from v2.
> [FEQ-2607] [P2PS] - Nada/fix: add back to p2p button for redirection from v2

- packages/core/src/Constants/form-error-messages.js
- packages/shared/src/utils/validation/declarative-validation-rules.ts
- packages/shared/src/utils/validation/form-error-messages-types.ts
- packages/trader/src/AppV2/Components/TradeParameters/Stake/__tests__/stake.spec.tsx
- packages/trader/src/AppV2/Components/TradeParameters/Stake/stake.tsx
This fix improves the validation and handling of error messages for barrier and stake inputs, ensuring clarity and better user guidance.
1. Barrier Validation: Enhance the validation logic for barrier inputs, ensuring that invalid values trigger appropriate and clear error messages.
2. Stake Error Messaging: Refine the error messages for stake inputs to be more informative and user-friendly.
This fix improves the accuracy and clarity of error messages, enhancing the overall user experience when configuring trades.
> Akmal / fix: barrier and stake error messages

- packages/trader/src/AppV2/Hooks/useContractsForCompany.ts
Please provide a summary of the change. See title above^
> [DTRA-V2] henry/dtra-2039/fix: assign correct barrier category to rise/fall

- packages/trader/src/AppV2/Components/MarketCategories/market-categories.scss
- packages/trader/src/AppV2/Components/MarketCategory/market-category.tsx
Please provide a summary of the change. Scroll selected market to middle when opening in all tab
> [DTRA-V2] henry/dtra-2045/fix: scroll selected market to middle and add padding bottom

- packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/__tests__/AvailableCtraderAccountsList.spec.tsx
> [WALL] Lubega / WALL-2933 / AvailableCtraderAccountsList unit test

- packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-disclaimers/__test__/deposit-crypto-disclaimers.test.tsx
- packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-disclaimers/deposit-crypto-disclaimers.tsx
> [WALL] Lubega / WALL-4967 / Legacy cashier crypto disclaimer content update

- packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoDisclaimers/DepositCryptoDisclaimers.tsx
- packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoDisclaimers/__tests__/DepositCryptoDisclaimers.spec.tsx
> [WALL] Lubega / WALL-4928 / Deposit crypto disclaimer content update

- packages/bot-skeleton/src/services/tradeEngine/utils/helpers.js
- Take echo_req directly from error_obj to solve trackjs error
> fix: get echo_req from error object to fix trackjs error

- packages/bot-skeleton/src/utils/date-time-helper.js
- packages/bot-web-ui/src/pages/dashboard/bot-list/index.scss
- packages/bot-web-ui/src/pages/dashboard/bot-list/recent-workspace.tsx
- packages/bot-web-ui/src/pages/tutorials/constants.ts
- packages/bot-web-ui/src/pages/tutorials/tutorials.scss
> [BOT]/mayuran/2163/DBot minor UI bugs

- packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-disclaimers/__test__/deposit-crypto-disclaimers.test.tsx
- packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-disclaimers/deposit-crypto-disclaimers.tsx
- packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoDisclaimers/DepositCryptoDisclaimers.tsx
- packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoDisclaimers/__tests__/DepositCryptoDisclaimers.spec.tsx
https://deriv-group.slack.com/archives/C0548T15K1P/p1728451433336619?thread_ts=1728281684.137479&cid=C0548T15K1P
> [WALL] Lubega / WEBREL-3222 / Deposit disclaimer content change

- packages/wallets/src/features/cfd/modals/CreatePasswordModal/CreatePasswordModal.tsx
- packages/wallets/src/features/cfd/modals/EnterPasswordModal/EnterPasswordModal.tsx
- packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
https://github.com/user-attachments/assets/5d3d8fd0-4349-49e1-9c35-9581be6c5a3c
https://github.com/user-attachments/assets/20f186ad-c13e-4e76-be2b-3cdac401482b
> [WALL] Lubega / WALL-4896 / DerivX create password button disable

- packages/bot-web-ui/src/pages/dashboard/announcements/announcements.tsx
- packages/bot-web-ui/src/pages/tutorials/dbot-tours/onboarding-tour/onboarding-tour-mobile.tsx
This PR is to merge the rc changes in the lastest master done in this card Rupato/WEBREL-3221/Fix--dbot-console-errors
to avoid cherry-picking
> Rupato/fix--dbot errors-This PR is to merge the rc changes in the lastest master

- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
- packages/account/src/Sections/Profile/PersonalDetails/verify-button.scss
- packages/account/src/Styles/account.scss
Fix numbers overlapping verify button in personal details page
> [UPM1641] Suisin/fix: number overlapping verify button in personal details page

- packages/bot-web-ui/src/pages/main/main.tsx
- packages/bot-web-ui/src/pages/tutorials/dbot-tours/onboarding-tour/onboarding-tour-mobile.tsx
Fix for the active tour when we open the mobile tour
> Rupato/BOT-2304/fix  for the onboarding tour

- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
- packages/account/src/Sections/Profile/PhoneVerification/confirm-phone-number.tsx
- packages/account/src/Sections/Profile/PhoneVerification/otp-verification.tsx
- packages/account/src/Sections/Profile/PhoneVerification/phone-number-verified-modal.tsx
- packages/account/src/Sections/Profile/PhoneVerification/phone-verification.scss
- packages/account/src/Styles/account.scss
phone number + icon not align properly in arabic
> Suisin/fix: phone number + icon not align properly in arabic

- packages/wallets/src/features/cfd/CFDPlatformsList.scss
- packages/wallets/src/features/cfd/CFDPlatformsListEmptyState.tsx
- packages/wallets/src/features/cfd/__tests__/CFDPlatformsListEmptyState.spec.tsx
> [WALL] Lubega / WALL-4965 / CFDs crypto empty state transfer funds

- packages/trader/src/AppV2/Components/DraggableList/draggable-list-item.tsx
- packages/trader/src/AppV2/Components/TradeParameters/trade-parameters-container.tsx
- packages/trader/src/AppV2/Components/TradeParameters/trade-parameters.scss
- packages/trader/src/AppV2/Containers/Trade/trade.scss
fix the overlapping issue of parameter with purchase button and unpin issue when only one item is present
> [DTRA-V2]fix: fix the overlapping issue of parameter with purchase button

- .github/actions/publish_to_pages_uat/action.yml
- .github/workflows/release_uat.yml
- .github/workflows/release_uat2.yml
Added UAT2 Github Workflow
Also changed the UAT deploy github action to accept branch name as param.
> Ako/ add uat2 env

- packages/core/src/App/Components/Elements/LiveChat/use-freshchat.ts
> Nuzhy/fresh chat integration[POC]

- packages/account/src/Sections/Profile/PhoneVerification/phone-number-verified-modal.tsx
When remove verified number from BO, UI should update automatically
> [UPM1640] Suisin/fix: when remove verified number from BO, UI should update automatically

- .github/CODEOWNERS
> chore: add rms to translations codeowners

- package-lock.json
- packages/bot-skeleton/package.json
- packages/bot-skeleton/src/services/api/binary-utils.js
- packages/bot-skeleton/src/services/api/ticks_service.js
- packages/bot-skeleton/src/services/tradeEngine/trade/Ticks.js
1. Remove binary-utils package
2. Replace the functions being used by moving them into respected places
NA
> [BOT] sandeep/refactor: :fire: remove binary-utils package

- packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-container.jsx
fixing blank screen, when IDV POI expires for CR non-regulated account
> fix: blank screen in POI 

- packages/wallets/src/features/cfd/components/ModalTradeWrapper/ModalTradeWrapper.tsx
- packages/wallets/src/features/cfd/components/ModalTradeWrapper/__tests__/ModalTradeWrapper.spec.tsx
> [WALL] Lubega / WALL-2928 / ModalTradeWrapper unit test

- package-lock.json
- packages/hooks/package.json
1. Bumped up the version for auth-client
> chore: update auth-client library

- package-lock.json
- packages/account/package.json
- packages/appstore/package.json
- packages/bot-web-ui/package.json
- packages/cashier/package.json
- packages/cfd/package.json
- packages/components/package.json
- packages/core/package.json
- packages/p2p/package.json
- packages/reports/package.json
- packages/trader/package.json
- packages/wallets/package.json
Updated "@deriv-com/ui" from v1.36.2 to v1.36.4
https://github.com/deriv-com/deriv-app/actions/runs/11332621189?pr=15805
Vulnerability reported -   https://github.com/rollup/rollup/security
> [coj]/likhith/update-deriv-ui package version to fix vulnerability issue

- packages/p2p/src/pages/app.jsx
This pull request addresses the issue with the transition from app.deriv.com to p2p.deriv.com, which previously resulted in glitches that disrupted the user experience. The update ensures seamless redirection for both staging and production environments, allowing users to navigate smoothly from staging app.deriv.com to staging p2p.deriv.com, as well as from production app.deriv.com to production p2p.deriv.com.
https://github.com/user-attachments/assets/437d3116-88e1-416d-91eb-b326dec5de9d
> [P2PS] - Nada/P2PS-4249/fix: staging deriv to staging p2p

- packages/account/src/Components/poi/status/verified/verified.tsx
- packages/account/src/Sections/Verification/ProofOfIdentity/__tests__/proof-of-identity-container.spec.js
- packages/account/src/Sections/Verification/ProofOfIdentity/onfido.jsx
- packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-container.jsx
- packages/account/src/Types/common.type.ts
> fix: issue WEBREL-3238

- packages/account/src/Components/poi/status/verified/verified.tsx
- packages/account/src/Sections/Verification/ProofOfIdentity/__tests__/proof-of-identity-container.spec.js
- packages/account/src/Sections/Verification/ProofOfIdentity/onfido.jsx
- packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-container.jsx
- packages/account/src/Types/common.type.ts
Cherry-picking hotfix to master
> [WEBREL] WEBREL-3238-IDV-verified-success-message-is-changed

- packages/account/src/Sections/Profile/PhoneVerification/__test__/session-timeout-modal.spec.tsx
- packages/account/src/Sections/Profile/PhoneVerification/confirm-phone-number.tsx
- packages/account/src/Sections/Profile/PhoneVerification/otp-verification.tsx
- packages/account/src/Sections/Profile/PhoneVerification/phone-verification-page.tsx
- packages/account/src/Sections/Profile/PhoneVerification/session-timeout-modal.tsx
- packages/hooks/src/useRequestPhoneNumberOTP.tsx
- packages/hooks/src/useSendOTPVerificationCode.tsx
Add Tracking events for error scenarios in PNV flow
> Suisin/chore: add analytics to track error events

- packages/account/build/constants.js
- packages/account/build/webpack.config.js
Fix issues that crept during merge of branch to master
> fix: eslint errors occured during merge

- packages/core/src/App/Components/Elements/LiveChat/live-chat.tsx
> Prince/fix: destroy instead of minimize

- packages/p2p/src/pages/app.jsx
> WEBREL-3244/Nada/redirection issue

- packages/p2p/src/pages/app.jsx
Cherry-pick the fix from rc_V20241015_0 to master.
> [WEBREL] / WEBREL-3244-Redirection-to-staging-p2p-is-not-working?expand=1

- packages/account/src/Configs/kyc-validation-config.ts
In Real account creation user is unable to move to next step after entering  IDV details.
Fixed the issue by adding proper validation for document field and skipping check of additional document field if it is not required
> [WEBREL]/likhith/webrel-3246/fix idv data entry in real account creation

- packages/account/src/Configs/kyc-validation-config.ts
- Cherry-pick fix from rc_V20241015_0 branch to master.
> [WEBREL] WEBREL-3246-Not-able-to-proceed-account-creation-for-IDV?expand=1

- packages/account/src/Components/forms/form-fields/employment-status.tsx
- packages/account/src/Styles/account.scss
Fixed CSS styling to align Employment status field in Financial assessment form
> [WEBREL]/likhith/misaligned employment-status field

- packages/account/src/Components/forms/form-fields/employment-status.tsx
- packages/account/src/Styles/account.scss
Cherry-pick fix from rc_V20241015_0 to master
> WEBREL-3247-Financial-Assessment-Form-Spacing-Issue

- packages/core/src/App/Components/Elements/LiveChat/live-chat.tsx
- packages/core/src/App/Components/Layout/Header/login-button.jsx
- packages/core/src/Utils/Analytics/index.ts
- packages/hooks/src/useGrowthbookGetFeatureValue.ts
- types/global.d.ts
> CSIT-1558/Prince/Livechat icon on testlinks

- packages/account/src/Components/poi/status/limited/limited.tsx
- packages/account/src/Configs/poi-error-config.tsx
- packages/appstore/src/components/modals/wallets-migration-failed/wallets-migration-failed.tsx
- packages/cashier/src/components/cashier-locked/cashier-locked-provider.tsx
- packages/cashier/src/components/side-notes/side-note-faq/side-note-faq.tsx
- packages/cashier/src/modules/cashier-onboarding/components/cashier-onboarding-side-notes/cashier-onboarding-side-note-fiat.tsx
- packages/cashier/src/modules/deposit-fiat/deposit-fiat.tsx
- packages/components/src/components/open-livechat-link/open-livechat-link.tsx
- packages/core/src/App/Containers/OneTimeDepositModal/one-time-deposit-modal-content.tsx
- packages/core/src/App/Containers/RealAccountSignup/change-account-currency.jsx
- packages/core/src/App/Containers/RealAccountSignup/signup-error-content.jsx
- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/Stores/notification-store.js
- packages/hooks/src/useIsLiveChatWidgetAvailable.ts
- packages/hooks/src/useLiveChat.ts
- packages/p2p/src/components/dp2p-blocked/dp2p-blocked-description.tsx
- packages/p2p/src/components/modal-manager/modals/ad-visibility-error-modal/ad-visibility-error-modal.tsx
- packages/shared/src/utils/constants/phone-number-verification.tsx
- packages/wallets/src/features/accounts/modules/TaxInformation/components/NeedHelpMessage/NeedHelpMessage.tsx
- packages/wallets/src/features/cashier/modules/DepositLocked/DepositLockedContent.tsx
- packages/wallets/src/features/cashier/modules/WithdrawalLocked/WithdrawalLockedContent.tsx
> Livechat check optional uat

- packages/account/src/Configs/user-profile-validation-config.ts
- packages/account/src/Containers/employment-tax-details-container/employment-tax-details-container.tsx
- packages/account/src/Containers/employment-tax-info/employment-tax-info.tsx
- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
- packages/account/src/Sections/Profile/PersonalDetails/validation.ts
- packages/account/src/Types/common.type.ts
- packages/core/src/sass/account-wizard.scss
Fixed the styling on label of Employment status field to prevent cropped content
> [WEBREL]/likhith/webrel-3250-Fix behavior on Employment & Tin section

- packages/components/src/components/video-player/video-player.scss
- packages/trader/src/AppV2/Components/Guide/guide.scss
> [DTRA-V2] henry/dtra-2084/fix: change video loading screen color based on theme

- packages/components/src/components/loading/loading.scss
> [DTRA-V2] henry/dtra-2088/fix: change skeleton loader lines css to semantic token'

- packages/account/src/Components/poi/status/verified/__tests__/verified.spec.tsx
- packages/account/src/Components/poi/status/verified/verified.tsx
Add continue trading button when POI successful verified
> [COJ1414] Suisin/fix: add Continue Trading button in POI

- packages/trader/src/AppV2/Components/TradeParameters/Stake/stake.tsx
This update includes multiple fixes for the stake field, improving its functionality, validation, and user experience.
1. Input Validation: Strengthen validation for the stake field to ensure only valid entries are accepted, reducing errors and incorrect inputs.
2. Error Handling: Improve error messaging for invalid stake values, providing clearer guidance to users.
3. User Experience: Refine the stake input interaction, making it more responsive and user-friendly.
These fixes ensure a smoother and more reliable experience when users interact with the stake field.
> Akmal / fix: multiple fixes for stake field

- packages/trader/src/AppV2/Containers/Chart/contract-details-chart.scss
- packages/trader/src/AppV2/Containers/Trade/trade.scss
A bug was identified in testing that chart is not loading when the language is changed to arabic. this applied to both chart in trade page as well as contract details page . It is fixed in this PR.
> [DTRA]/Ahmad/DTRA-2170/ Chart Loading in Arabic Language

- packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
- Memoized objects to avoid rerenders.
https://github.com/user-attachments/assets/d33e98b9-5526-47f8-aae4-57b774985425
> [WEBREL] Jim/WEBREL-3262/memoize wallet lists to prevent re-renders

- packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
Cherry-pick fix from rc_V20241017_0 to master
> WEBREL-3262-Crypto-Wallets-Swiping-on-it's-own

- packages/trader/src/AppV2/Components/AccumulatorStats/accumulator-stats-description.tsx
- packages/trader/src/AppV2/Components/OnboardingGuide/GuideForPages/onboarding-video.tsx
- packages/trader/src/AppV2/Components/StreamIframe/__tests__/stream-iframe.spec.tsx
- packages/trader/src/AppV2/Components/StreamIframe/stream-iframe.scss
- packages/trader/src/AppV2/Components/StreamIframe/stream-iframe.tsx
- packages/trader/src/AppV2/Utils/layout-utils.tsx
- Added loader for stream iframe
https://github.com/user-attachments/assets/fa0c4007-ccff-45cc-837e-458fe18ad1e5
https://github.com/user-attachments/assets/b3014224-45ab-49c3-aeec-1a742676424b
> DTRA-1948 / Kate / Add loader for the videos

- packages/trader/src/AppV2/Components/TradeParameters/Stake/stake.tsx
- Added missing dependency to stake save callback
https://github.com/user-attachments/assets/27e30604-ed2c-4fbc-8b4c-97f6a2f22aea
> DTRA-2194 / Kate / Stake saving functionality

- packages/trader/src/AppV2/Hooks/useContractsForCompany.ts
> [DTRA-V2] henry/dtra-2160/fix: call contracts for on landing company change

- packages/account/src/Components/poi/status/upload-complete/upload-complete.tsx
- packages/account/src/Sections/Profile/PhoneVerification/__test__/cool-down-period-modal.spec.tsx
- packages/account/src/Sections/Profile/PhoneVerification/cool-down-period-modal.tsx
redirect user to previous route after failing to verify otp
> [UPM-1687] Suisin/Chore: redirect user to previous route after failing to verify otp

- packages/wallets/src/components/FormDropdown/__tests__/FormDropdown.spec.tsx
- Added test cases for `FormDropdown` component
> [WALL] Jim/WALL-4872/unit tests for form dropdown

- packages/account/src/Components/poi/status/upload-complete/upload-complete.tsx
remove continue trading from upload complete
> [COJ-1418] Suisin/coj1418/remove continue trading from upload complete

- packages/core/src/Utils/Analytics/analytics.ts
> fix: domain change

- packages/appstore/src/components/banners/business-closure-banner/business-closure-banner.tsx
- packages/cashier/src/components/cashier-locked/cashier-locked-provider.tsx
- packages/core/src/Stores/client-store.js
- packages/core/src/Stores/notification-store.js
- packages/trader/src/App/Components/Elements/Modals/TradingDisabledByResidenceModal/trading-disabled-by-residence-modal-content.tsx
* chore: remove hardcoded country
* chore: add static content for message
* chore: add static content for message
> habib/remove hardcoded country (#17346)

- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/upgraded-qs-v2/qs-stepper.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/upgraded-qs-v2/strategy-list.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/upgraded-qs-v2/strategy-template-picker.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/upgraded-qs-v2/trade-constants.ts
fix: Translation issues in Quick strategy
> [BOT]maryia/GRWT-1246/fix: Translation issues in Quick strategy

- packages/appstore/src/components/cfds-listing/index.tsx
- packages/core/src/Stores/traders-hub-store.js
> fix: logged_out

- packages/account/src/Components/personal-details/__tests__/personal-details.spec.tsx
- packages/account/src/Configs/__test__/user-profile-validation.spec.ts
- packages/account/src/Configs/user-profile-validation-config.ts
- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
- packages/appstore/src/components/cfds-listing/index.tsx
- packages/cfd/src/Containers/cfd-server-error-dialog.tsx
- packages/core/src/Stores/traders-hub-store.js
> Rc v20241101 0

- packages/wallets/src/features/cfd/modals/MT5ErrorModal/MT5ErrorModal.tsx
- packages/wallets/src/features/cfd/modals/MT5ErrorModal/index.ts
- packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
- improve error modal when user created an MT5 account
https://github.com/user-attachments/assets/bf82678b-d672-4176-b9fb-47ad565379a1
> [WEBREL] george / WEBREL-3304 / unable to create regulated mt5 account for the user without citizenship

- packages/wallets/src/features/cfd/modals/MT5ErrorModal/MT5ErrorModal.tsx
- packages/wallets/src/features/cfd/modals/MT5ErrorModal/index.ts
- packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
Cherry-picking fix from rc_V20241101_0 to master
> [WEBREL] georeg / WEBREL-3304 / [Wallet] Unable to create regulated mt5 account for the user without citizenship

- packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/__tests__/risk-management.spec.tsx
- packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/risk-management.tsx
It is about renaming Risk "Management" to "management"
> [DTRA-V2]/Ahmad/Rename Risk Management

- packages/trader/src/AppV2/Components/AccumulatorStats/accumulator-stats-modal.tsx
- packages/trader/src/AppV2/Components/AccumulatorStats/accumulator-stats.scss
> [DTRA] henry/dtra-2026/fix: make accu stats header sticky

- packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx
- packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/__tests__/DxtradeEnterPasswordModal.spec.tsx
> [WALL] Lubega / WALL-2940 / DxtradeEnterPasswordModal unit test

- packages/wallets/src/features/cfd/modals/MT5PasswordModal/__tests__/MT5PasswordModalFooters.spec.tsx
> [WALL] Lubega / Fix failing master

- packages/wallets/src/features/cfd/screens/CreatePasswordMT5/CreatePasswordMT5.tsx
- packages/wallets/src/features/cfd/screens/CreatePasswordMT5/__tests__/CreatePasswordMT5.spec.tsx
> [WALL] Lubega / WALL-5108 / CreatePasswordMT5 unit test

- packages/cashier/src/components/cashier-container/virtual/virtual.tsx
- packages/core/build/config.js
This is a PR to master containing changes from [this](https://github.com/deriv-com/deriv-app/pull/17496) PR
> [WEBREL] Jim/WEBREL-3330/Console errors on Cashier page

- packages/core/src/Stores/client-store.js
- packages/stores/types.ts
- packages/trader/src/AppV2/Components/TradeParameters/Stake/__tests__/stake.spec.tsx
- packages/trader/src/AppV2/Components/TradeParameters/Stake/stake.tsx
It reset the stake to default value when we change account just so that the stake and currency of one account (say crypto) should reflect in another account . .
> [DTRA-V2]/Ahmad/Default Stake Currency fix

- packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsCard.scss
- packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsDescription.scss
- packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsDescription.tsx
- packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/CompareAccountsCard.spec.tsx
- packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/CompareAccountsDescription.spec.tsx
- packages/wallets/src/features/cfd/screens/CompareAccounts/__tests__/compareAccountsConfig.spec.ts
- packages/wallets/src/features/cfd/screens/CompareAccounts/compareAccountsConfig.ts
- packages/wallets/src/routes/CompareAccountsRoute/CompareAccountsRoute.scss
Reverts deriv-com/deriv-app#17441
> Revert "[WALL] george / WALL-5105 / Remove the jurisdiction information on compare account table for wallets"

- packages/bot-web-ui/src/stores/google-drive-store.ts
- Catch invalid token error thrown by google drive oAuth and show respective error to the user
> [BOT] mayuran/FEQ-2478/TrackJS Dbot - 400 : POST https://oauth2.googleapis.com/revoke

- packages/trader/src/AppV2/Components/ContractDetailsFooter/__tests__/contract-details-footer.spec.tsx
- packages/trader/src/AppV2/Components/ContractDetailsFooter/contract-details-footer.tsx
- Show bid price on close button (when it's not disabled) during active DC
https://github.com/user-attachments/assets/fd70c179-6b74-442e-a7e5-73e8c7be2a84
> DTRA-1894 / Kate / Add bid price on Close button when DC is active on Contract details

- package-lock.json
- package.json
- packages/bot-web-ui/package.json
- packages/core/package.json
- packages/trader/package.json
> [DTRA]feat: update chart version

- packages/cashier/src/components/side-notes/side-note-faq/__tests__/side-note-faq.spec.tsx
- packages/cashier/src/components/side-notes/side-note-faq/side-note-faq.tsx
- Updated `FAQ` content on the cashier deposit page.
> [WALL] Jim/WALL-4937/update content on the cashier deposit page

- package-lock.json
- package.json
- packages/account/package.json
- packages/api-v2/package.json
- packages/appstore/package.json
- packages/cashier/package.json
- packages/cfd/package.json
- packages/core/package.json
- packages/core/src/Utils/Analytics/index.ts
- packages/hooks/package.json
- packages/p2p/package.json
- packages/reports/package.json
- packages/shared/package.json
- packages/trader/package.json
- packages/wallets/package.json
- types/global.d.ts
> chore: adding network information

- packages/bot-web-ui/src/stores/google-drive-store.ts
> fix: 400 error

- packages/bot-web-ui/src/stores/google-drive-store.ts
> [Bot]/WEBREL-3341/release 400 error

- packages/core/src/sass/account-wizard.scss
Add padding for account opening dropdown
> TRAH-4430/habib/padding for account opening dropdown

- packages/core/src/App/Containers/Redirect/redirect.jsx
https://github.com/user-attachments/assets/4a284efb-211b-420f-aaf1-38406c8fd3a3
> [TRAH] [ODC] shontzu/cfd-to-accounts-navigation

- packages/core/src/App/Containers/Redirect/redirect.jsx
Reverts deriv-com/deriv-app#17572
> Revert "[TRAH] [ODC] shontzu/cfd-to-accounts-navigation"

- packages/core/src/App/Containers/Redirect/redirect.jsx
Reverts deriv-com/deriv-app#17576
> Revert "Revert "[TRAH] [ODC] shontzu/cfd-to-accounts-navigation""

- packages/trader/src/AppV2/Components/Guide/guide.tsx
- packages/trader/src/AppV2/app.tsx
Fix for tracking events in dtrader v2 for open and guide action
> [DTRA]fix dtrader v2 events for open action and guide action

- packages/core/src/App/Containers/Redirect/redirect.jsx
https://github.com/user-attachments/assets/39c20208-5f69-4d7f-9142-8dff5707f368
> [TRAH] [ODC] shontzu/lowcode-to-highcode-navigation-2

- packages/core/src/App/Containers/Redirect/redirect.jsx
Reverts deriv-com/deriv-app#17610
> Revert "[TRAH] [ODC] shontzu/lowcode-to-highcode-navigation-2"

- packages/core/src/App/Containers/Redirect/redirect.jsx
> [TRAH] shontzu/Redirect-Users-app-deriv-com-for-KYC-flow-from-CFD

- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
Fix logout not functioning properly in pnv flow
> [WEBREL-3356] Suisin/chore: add a promise instead of await

- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
> Suisin/chore: add a promise instead of await

- packages/core/src/Stores/client-store.js
> Agrim/CRO-787/chore: remove signup_continued action

- packages/wallets/src/features/cfd/modals/TradingPlatformStatusModal/TradingPlatformStatusModal.tsx
- packages/wallets/src/features/cfd/modals/TradingPlatformStatusModal/__tests__/TradingPlatformStatusModal.spec.tsx
- packages/wallets/src/features/cfd/screens/TradingPlatformStatus/TradingPlatformStatus.tsx
- packages/wallets/src/features/cfd/screens/TradingPlatformStatus/__tests__/TradingPlatformStatus.spec.tsx
> [WALL] Lubega / WALL-5163 / TradingPlatformStatus unit test

- packages/core/src/App/Containers/Redirect/redirect.jsx
> [TRAH] [ODC] shontzu/lowcode-to-higcode-seamless-login

- packages/wallets/src/components/ModalProvider/ModalProvider.tsx
- packages/wallets/src/components/WalletsChangeMT5Password/WalletSuccessChangeMT5Password.scss
- packages/wallets/src/components/WalletsChangeMT5Password/WalletSuccessChangeMT5Password.tsx
- packages/wallets/src/components/WalletsChangeMT5Password/__tests/WalletSuccessChangeMT5Password.spec.tsx
- packages/wallets/src/components/WalletsChangeMT5Password/index.ts
- packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
- packages/wallets/src/features/cfd/modals/MT5PasswordModal/__tests__/MT5PasswordModal.spec.tsx
- Correct the visibility of the password change popup and account creation popup when the user is updating the password for their MT5 account.
https://github.com/user-attachments/assets/fcf8db12-dc83-47b9-be57-77355fed8f7e
> [WALL] george / WALL-4850 / Password change and account creation success message are not shown when changing password

- packages/appstore/src/components/add-options-account/add-options-account.tsx
- packages/appstore/src/components/app-content.tsx
- packages/appstore/src/components/banners/book-banner/banner-template.tsx
- packages/appstore/src/components/banners/deposit-now-banner/deposit-now-banner.tsx
- packages/appstore/src/components/banners/real-account-creation-banner/real-account-creation-banner.tsx
- packages/appstore/src/components/banners/wallets-banner/wallets-banner-unsuccessful.tsx
- packages/appstore/src/components/banners/wallets-banner/wallets-banner-upgrade.tsx
- packages/appstore/src/components/banners/wallets-banner/wallets-banner-upgrading.tsx
- packages/appstore/src/components/cfds-listing/index.tsx
- packages/appstore/src/components/compare-account/compare-account.tsx
- packages/appstore/src/components/containers/trading-app-card.tsx
- packages/appstore/src/components/currency-switcher-card/real/real-account-card.tsx
- packages/appstore/src/components/main-title-bar/account-type-dropdown.tsx
- packages/appstore/src/components/options-multipliers-listing/index.tsx
- packages/bot-web-ui/src/analytics/__tests__/utils.spec.ts
- packages/bot-web-ui/src/analytics/rudderstack-bot-builder.ts
- packages/bot-web-ui/src/analytics/rudderstack-common-events.ts
- packages/bot-web-ui/src/analytics/rudderstack-dashboard.ts
- packages/bot-web-ui/src/analytics/rudderstack-quick-strategy.ts
- packages/bot-web-ui/src/analytics/rudderstack-tutorials.ts
- packages/core/src/App/Containers/AccountSignupModal/account-signup-modal.jsx
- packages/core/src/App/Containers/PasswordSelectionModal/password-selection-modal.jsx
- packages/core/src/Utils/Analytics/analytics.ts
- packages/shared/src/index.ts
- packages/trader/src/Analytics/index.ts
- packages/trader/src/Stores/Modules/Trading/trade-store.ts
Reverts deriv-com/deriv-app#17549
> Revert "Agrim/CRO-770/Missing-Userid"

- packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/deal-cancellation.tsx
- packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/take-profit-and-stop-loss-container.tsx
- Removed incorrect delay. Now the default delay (4s) will be applied.
https://github.com/user-attachments/assets/577dee34-4833-4a64-8381-1db0053602f7
> DTRA-2414 / Kate / [DTrader-V2]: Snackbar for RM is disappearing too fast

- packages/account/src/Sections/Profile/PhoneVerification/phone-verification-page.tsx
- packages/core/src/App/AppContent.tsx
- packages/core/src/Stores/client-store.js
- packages/core/src/Stores/notification-store.js
- packages/stores/types.ts
fix noti and pnv flow issue when ff is off and both sms and whatsapp carriers are off from BO
> [WEBREL3373] Suisin/chore: fix noti and pnv flow issue when ff is off

- packages/account/src/Sections/Profile/PhoneVerification/phone-verification-page.tsx
- packages/core/src/App/AppContent.tsx
- packages/core/src/Stores/client-store.js
- packages/core/src/Stores/notification-store.js
- packages/stores/types.ts
Notification and pnv flow should be same as prod
> [WEBREL3373] Suisin/chore: fix notification and pnv flow to be same as prod

- .github/workflows/coveralls.yml
Reverts deriv-com/deriv-app#17663
Reverting this PR because cache  isn't hitting as expected.
> Revert "[FEQ] george / FEQ-2702 / Improve Coverall workflow time execution. Part 2. Adding caching npm packages"

- packages/bot-web-ui/src/stores/dashboard-store.ts
> [BOT-2440]/mayuran/tutorial-video bug

- .github/workflows/coveralls.yml
- remove redundant key restoration
> perf: remove redundant cache key restoration

- packages/core/src/Stores/traders-hub-store.js
Fix on refresh, EU account Multipliers section will change to `Options` then to `Multipliers` afterwards
EU:
ROW:
> [TRAH4562] Suisin/chore: add condition to check is_eu_user on giving contentFlag

- packages/bot-skeleton/src/scratch/utils/index.js
- packages/bot-skeleton/src/services/tradeEngine/utils/helpers.js
- packages/bot-web-ui/src/stores/run-panel-store.ts
> [BOT]/mayuran/bot-2180/ improve journal messages

- packages/bot-web-ui/src/constants/contract.ts
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/form-wrappers/strategy-list.tsx
- packages/bot-web-ui/src/pages/bot-builder/quick-strategy/types.ts
fix: Search by "all" results are not shown correctly
> [BOT]maryia/BOT-2445/fix: Search by "all" results are not shown correctly

- packages/trader/src/AppV2/Components/OnboardingGuide/GuideForPages/guide-tooltip.tsx
Fixed the next and skip button appearing twice in onboarding guide 
> [Dtra] fix: ui for tooltip of onborading guide

- packages/trader/src/Stores/Modules/Trading/trade-store.ts
fix the change of variable name is_dtrader_v2 in trade store
> fix: fix the change of variable name is_dtrader_v2 in trade store

- package-lock.json
- packages/bot-web-ui/package.json
- packages/core/package.json
- packages/trader/package.json
> feat: update deriv-charts version

- packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
- packages/core/src/App/Constants/platform-config.ts
- Fixed redirection to dbot.deriv.com using platform switcher by updating platform config of deriv bot
> [BOT] Farabi/bot-2594/fix-redirection-to-bot-standalone-from-platform-switcher

- packages/wallets/src/features/cfd/modals/CTraderSuccessModal/__tests__/CtraderSuccessModal.spec.tsx
> [WALL] Lubega / WALL-5219 / CtraderSuccessModal unit test

- packages/bot-web-ui/src/pages/bot-builder/toolbar/workspace-group.tsx
- packages/bot-web-ui/src/pages/dashboard/dashboard.scss
- packages/bot-web-ui/src/stores/quick-strategy-store.ts
> BOT-2443/mayuran/fix: ui bugs

- packages/core/src/App/Containers/app-notification-messages.jsx
- packages/core/src/Stores/Helpers/client-notifications.js
- packages/core/src/Stores/notification-store.js
Add notification for pre-acceptance terms and condition
> [WALL5212] Suisin/chore: create reacceptance tnc notification

- packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeLink/MT5TradeLink.tsx
- fix ctrader webterminal link creation
> [WALL] george / WALL-5229 / CTrader Webterminal redirection  is not working on QA

- packages/trader/src/AppV2/Components/OnboardingGuide/GuideForPages/onboarding-guide.tsx
> Akmal / update welcome modal

- packages/trader/src/AppV2/Components/OnboardingGuide/TradeTypesSelectionGuide/trade-types-selection-guide.tsx
> Akmal / feat: update trade type selection guide

- packages/appstore/src/constants/wallet-migration-video-translations.ts
- adding all languages for the migration video
> [WALL] george / WALL-5233 / Adding all languages for the migration video

- packages/cfd/src/Containers/cfd-password-modal.tsx
Remove misleading information message and tnc checkbox when creating DXTrader account
> [CFDS-4846] Suisin/chore: fix misleading info when creating DXTrader account

- package-lock.json
- package.json
- packages/account/package.json
- packages/bot-web-ui/package.json
- packages/core/package.json
- packages/trader/package.json
Updated the version of quill-ui
> feat: update the version of quill-ui for wheel-picker changes

- packages/core/src/App/Containers/Redirect/redirect.jsx
> Populate active wallet login id from cookies

- packages/appstore/src/components/modals/modal-manager.tsx
- add wallet reset migration on try again button click if migration fails
> [WALL] george / WALL-5238 / Allow EU users to restart the wallet migration in case of failure

- packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/__tests__/take-profit-and-stop-loss-input.spec.tsx
- packages/trader/src/AppV2/Components/TradeParameters/RiskManagement/take-profit-and-stop-loss-input.tsx
The field limit for TP and SL in v2 has been made same as v1 prod
> [GRWT]fix: add limit to tp and sl field same as prod behavior

- packages/core/src/App/Containers/Redirect/redirect.jsx
Handle Platform checker from Oustsystems
> Remove platform checker from Redirect

- packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/TransactionsPendingRow.tsx
- fix time visibility in mobile and tablet view
> [WALL] george / WALL-5158 / Able to notice incorrect time format being displayed

- packages/trader/src/AppV2/Components/OnboardingGuide/QuickAdjGuide/quick-adj-guide.tsx
- packages/trader/src/AppV2/Components/OnboardingGuide/TradeParamsGuide/trade-params-guide.tsx
- packages/trader/src/AppV2/Containers/Trade/trade-types.tsx
> Akmal / fix: guide review suggestions #1

- packages/cashier/src/stores/iframe-store.ts
Add `https"//cashier.deriv.be` and `https://cashier.deriv.me` as trusted origins in the variable.
> Nijil / WALL-5259 / Add cashier.deriv.be and cashier.deriv.me as trusted origins in the variable

- packages/core/src/App/AppContent.tsx
- packages/hooks/src/useSilentLoginAndLogout.ts
- There might be a race condition issue happening that causes Deriv.app to be Single-Logout when OIDC is disabled in Deriv.app
> Adrienne / Fix race condition issue with Growthbook and OIDC

- packages/bot-web-ui/src/stores/run-panel-store.ts
- packages/reports/src/Containers/open-positions.tsx
> fix: change to search query

- package-lock.json
- packages/core/package.json
- packages/core/src/Stores/portfolio-store.js
- packages/trader/package.json
- revert mobx-utils implementation and portfolio store
> [WEBREL] george / WEBREL-3463 / revert mobx-utils implementation

- package-lock.json
- packages/core/package.json
- packages/core/src/Stores/portfolio-store.js
- packages/trader/package.json
- revert mobx-utils implementation
> [WEBREL] george / WEBREL-3436 / revert mobx-utils implementation

- packages/reports/src/Components/Form/CompositeCalendar/__tests__/two-month-picker.spec.tsx
Test was failing since it was taking into consideration the current year. so for the end of the year, the current year and previous year will be different which makes the length of the current year in the test to be 1.
> fix: failing test in staging

- packages/core/src/App/AppContent.tsx
- Enable OIDC back for SSO/SLO to test out signup changes in Traders Hub
> Adrienne / Enable OIDC back for SSO/SLO

- packages/reports/src/Components/Form/CompositeCalendar/__tests__/two-month-picker.spec.tsx
Test was failing since it was taking into consideration the current year. so for the end of the year, the current year and previous year will be different which makes the length of the current year in the test to be 1.
https://github.com/deriv-com/deriv-app/pull/17924
> fix: failing test pr to master

- packages/reports/src/Components/Form/CompositeCalendar/__tests__/two-month-picker.spec.tsx
> fix: failing test pr to master (#17925)

- packages/reports/src/Components/Form/CompositeCalendar/__tests__/two-month-picker.spec.tsx
> Adrienne / Update UAT1 branch with master

- packages/api-v2/src/APIProvider.tsx
- packages/api-v2/src/AuthProvider.tsx
- packages/api-v2/src/constants/index.ts
- packages/api-v2/src/constants/platforms.ts
- packages/api-v2/src/ws-client/ws-client.ts
- packages/shared/src/utils/config/config.ts
- packages/wallets/src/App.tsx
Reverts deriv-com/deriv-app#17820
Clickup card for reference: https://app.clickup.com/t/20696747/WALL-5227
> Revert "Jim/wall 5227/switch ws connection when clients switch between real and demo wallets"

- packages/core/src/App/AppContent.tsx
- packages/shared/src/utils/login/login.ts
Should provide app id once user clicks on login, instead of connecting it to server
> [WEBREL3510] Suisin/chore: append app id only happens at login not ws

- packages/core/src/App/AppContent.tsx
- packages/shared/src/utils/login/login.ts
Approvals here https://github.com/deriv-com/deriv-app/pull/17948
> chore: append app id only happens at login not ws

- packages/appstore/src/components/disclaimer/disclaimer.tsx
- packages/wallets/src/components/WalletsDisclaimerBanner/WalletsDisclaimerBanner.tsx
Change from 70.84% to 70% for disclaimer
> [TRAH5275] suisin/chore: change 70.84% to 70% for disclaimer

- packages/hooks/src/__tests__/useIsHubRedirectionEnabled.spec.tsx
- packages/hooks/src/useIsHubRedirectionEnabled.ts
> suisin/chore: fix redirection logs user out

- packages/appstore/src/components/disclaimer/disclaimer.tsx
- packages/wallets/src/components/WalletsDisclaimerBanner/WalletsDisclaimerBanner.tsx
> suisin/chore: update cfds loss percentage from 70.84% to 70%

- packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-flow.tsx
> Amina/fix: POI -URL redirect fix

- packages/core/src/App/AppContent.tsx
> Adrienne / Remove iframe references to smarttrader

- packages/core/src/App/AppContent.tsx
- packages/reports/src/Components/Form/CompositeCalendar/__tests__/two-month-picker.spec.tsx
- Enable OIDC SSO/SLO back to Deriv.app
> Adrienne / Merge UAT OIDC changes to staging Deriv.app

- packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/wallets/src/components/ModalProvider/ModalProvider.tsx
Redirection should happen for wallets enabled country and already logged into hub.deriv.com
> [WEBREL3580] Suisin/chore: change to check and trading hub instead of or

- packages/core/src/App/AppContent.tsx
> Adrienne / Revert OIDC changes

- packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/wallets/src/components/ModalProvider/ModalProvider.tsx
> Suisin/chore: change to check and trading hub instead of or

- packages/core/src/App/AppContent.tsx
> Adrienne / Enable back OIDC SSO and SLO

- packages/core/src/App/AppContent.tsx
> Adrienne / Release OIDC changes to Deriv.app

- packages/hooks/src/useSilentLoginAndLogout.ts
> Adrienne / Add backward compatability for social signup

- packages/core/src/App/AppContent.tsx
- packages/hooks/src/useSilentLoginAndLogout.ts
> Adrienne / Added backward compatability for social signup

- packages/hooks/src/useSilentLoginAndLogout.ts
> Adrienne / Fix issue where user is still not logged in after oidc social login

- packages/hooks/src/useSilentLoginAndLogout.ts
> Adrienne / Fix OIDC backward compatible release

- packages/core/src/Stores/client-store.js
- packages/hooks/src/useSilentLoginAndLogout.ts
> Adrienne / Set cookies to false to support social login

- packages/core/src/Stores/client-store.js
> Set cookies to false to support social login RC branch

- packages/api-v2/src/hooks/useIsHubRedirectionEnabled.ts
- packages/core/src/App/AppContent.tsx
- packages/hooks/src/__tests__/useIsHubRedirectionEnabled.spec.tsx
- packages/hooks/src/useIsHubRedirectionEnabled.ts
Change from checking citizen to checking residence
> [TRAH5324] Suisin/chore: fix to not check citizen and check residence instead

- packages/api-v2/src/hooks/useIsHubRedirectionEnabled.ts
- packages/hooks/src/__tests__/useIsHubRedirectionEnabled.spec.tsx
- packages/hooks/src/useIsHubRedirectionEnabled.ts
> [TRAH5324] Lubega/Suisin: Change redirection for residence based on authorize country

- packages/api-v2/src/hooks/useIsHubRedirectionEnabled.ts
- packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/hooks/src/__tests__/useIsHubRedirectionEnabled.spec.tsx
- packages/hooks/src/useIsHubRedirectionEnabled.ts
- packages/wallets/src/components/ModalProvider/ModalProvider.tsx
- packages/wallets/src/components/WalletsAddMoreCardBanner/__tests__/WalletsAddMoreCardBanner.spec.tsx
- packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/__tests__/CryptoTransaction.spec.tsx
- packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/__tests__/TransactionsPendingRow.spec.tsx
- packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/__tests__/AddedCTraderAccountsList.spec.tsx
- packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/__tests__/AvailableCtraderAccountsList.spec.tsx
- packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/__test__/AddedDxtradeAccountsList.spec.tsx
- packages/wallets/src/features/cfd/modals/CTraderSuccessModal/__tests__/CtraderSuccessModal.spec.tsx
- packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/__tests__/DxtradeEnterPasswordModal.spec.tsx
> Change redirection for residence

- packages/account/src/Sections/Profile/PersonalDetails/constants.ts
- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
> Amina/fix: add addditional dropdown options for account opening reason

- packages/api-v2/src/hooks/useIsHubRedirectionEnabled.ts
- packages/core/src/App/AppContent.tsx
- packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/hooks/src/__tests__/useIsHubRedirectionEnabled.spec.tsx
- packages/hooks/src/useIsHubRedirectionEnabled.ts
- packages/wallets/src/components/ModalProvider/ModalProvider.tsx
- packages/wallets/src/components/WalletsAddMoreCardBanner/__tests__/WalletsAddMoreCardBanner.spec.tsx
- packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/__tests__/CryptoTransaction.spec.tsx
- packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/__tests__/TransactionsPendingRow.spec.tsx
- packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/__tests__/AddedCTraderAccountsList.spec.tsx
- packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/__tests__/AvailableCtraderAccountsList.spec.tsx
- packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/__test__/AddedDxtradeAccountsList.spec.tsx
- packages/wallets/src/features/cfd/modals/CTraderSuccessModal/__tests__/CtraderSuccessModal.spec.tsx
- packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/__tests__/DxtradeEnterPasswordModal.spec.tsx
> Lubega/TRAH: 5324/Change redirection for residence

- packages/api-v2/src/hooks/useIsHubRedirectionEnabled.ts
- packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/hooks/src/__tests__/useIsHubRedirectionEnabled.spec.tsx
- packages/hooks/src/useIsHubRedirectionEnabled.ts
- packages/wallets/src/components/ModalProvider/ModalProvider.tsx
- packages/wallets/src/components/WalletsAddMoreCardBanner/__tests__/WalletsAddMoreCardBanner.spec.tsx
- packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/__tests__/CryptoTransaction.spec.tsx
- packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/__tests__/TransactionsPendingRow.spec.tsx
- packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/__tests__/AddedCTraderAccountsList.spec.tsx
- packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/__tests__/AvailableCtraderAccountsList.spec.tsx
- packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/__test__/AddedDxtradeAccountsList.spec.tsx
- packages/wallets/src/features/cfd/modals/CTraderSuccessModal/__tests__/CtraderSuccessModal.spec.tsx
- packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/__tests__/DxtradeEnterPasswordModal.spec.tsx
Fix redirection issue on staging
> [TRAH5324] Suisin/chore: fix redirection issue during staging

- packages/core/src/App/Containers/ResetPasswordModal/reset-password-modal.tsx
> Adrienne / Reset password redirect to OIDC

- packages/core/src/Stores/client-store.js
> Adrienne / Fix social login OIDC cookies

- packages/reports/src/Components/Form/CompositeCalendar/__tests__/two-month-picker.spec.tsx
- packages/reports/src/Components/Form/CompositeCalendar/two-month-picker.tsx
- added comprehensive test cases for TwoMonthPicker component with fixed dates
> george / Add comprehensive test cases for TwoMonthPicker component

- package-lock.json
- package.json
- packages/account/package.json
- packages/api-v2/package.json
- packages/appstore/package.json
- packages/cashier/package.json
- packages/cfd/package.json
- packages/core/package.json
- packages/hooks/package.json
- packages/p2p/package.json
- packages/reports/package.json
- packages/shared/package.json
- packages/trader/package.json
- packages/wallets/package.json
- updated `@deriv-com/analytics` to version `1.30.2`
> Shayan/CRO-919/updated @deriv-com/analytics to the latest version

- package-lock.json
- package.json
- packages/account/package.json
- packages/api-v2/package.json
- packages/appstore/package.json
- packages/cashier/package.json
- packages/cfd/package.json
- packages/core/package.json
- packages/hooks/package.json
- packages/p2p/package.json
- packages/reports/package.json
- packages/shared/package.json
- packages/trader/package.json
- packages/wallets/package.json
- updated `@deriv-com/analytics` to version `1.30.2`
> build: updated @deriv-com/analytics to the latest version

- packages/core/src/App/Containers/RootComponent/root-component.jsx
Change redirection url from `hub.deriv.com/tradershub/cfds` to `hub.deriv.com/tradershub`
> Suisin/chore: change redirection to home instead of cfds

- packages/cfd/src/Containers/ctrader-derivx-trade-modal.tsx
- packages/cfd/src/Helpers/constants.ts
Make translation happen when language is switched
> Suisin/chore: make strategy_provider_notes to be in a returning function

- packages/core/src/Services/socket-general.js
Reverts deriv-com/deriv-app#18078
> Revert "Adrienne / Fix self exclusion not logging out with OIDC"

- packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.tsx
> Adrienne / Add loader to Wallets before redirecting to Traders Hub

- packages/core/build/config.js
- packages/core/src/root_files/front-channel.html
> Adrienne / Add front channels

- packages/core/src/App/AppContent.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/core/src/Stores/client-store.js
- packages/hooks/src/useIsHubRedirectionEnabled.ts
- packages/hooks/src/useSilentLoginAndLogout.ts
- packages/stores/types.ts
> Adrienne / Fix SSO triggering before Traders Hub redirection

- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/App/app.jsx
- packages/core/src/Modules/Callback/CallbackPage.tsx
- packages/core/src/Stores/client-store.js
> Suisin/chore: fix blank screen issue

- packages/trader/src/Modules/Trading/Containers/trade.tsx
clear session storage once you land on Dtrader page to fix OIDC redirecting back to Dtrader page
> Suisin/chore: fix redirection session storage issue

- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/Stores/client-store.js
Fix staging redirection to pages breaking issue. Added a optional checking for type which fails redirection page and add a default {} in clientStore 
> Suisin/chore: fix staging breaking redirection issue

- packages/core/src/App/Components/Layout/Footer/regulatory-information.jsx
sage
Update regulatory information message
> [TRAH-5139] Darren/chore: update regulatory information message

- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/core/src/Modules/Callback/CallbackPage.tsx
- packages/core/src/Stores/client-store.js
Fix account syncing after login doesn't work
> Suisin/chore: fix account syncing after loging in

- packages/core/src/Modules/Callback/CallbackPage.tsx
- packages/core/src/Stores/client-store.js
> Adrienne / Fix token undefined during account switching session storage handling

- packages/core/src/App/AppContent.tsx
> fix: add translation in callback account loader

- packages/core/src/Stores/ui-store.js
> Fix redirection to OS issue

- packages/core/src/sass/app/_common/components/callback.scss
> fix: add margin to callback loader

- packages/core/src/Stores/client-store.js
https://github.com/user-attachments/assets/f704f57e-0ceb-4146-a7bd-9cbf024393fd
> User always redirected to first created account when attempting to withdraw via Payment Agent

- packages/account/src/Containers/Account/page-overlay-wrapper.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/core/src/Stores/client-store.js
- packages/stores/types.ts
Fix redirection to hub.deriv.com if user click on logout button
https://github.com/user-attachments/assets/d8fed0cd-ae2f-440c-817e-978e2e7b46d9
> Suisin/chore: do not trigger redirection if user is logging out

- packages/core/src/App/Components/Layout/Header/login-button.jsx
- packages/core/src/App/Containers/Modals/wallets-upgrade-logout-modal/wallets-upgrade-logout-modal.tsx
- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/App/Containers/ResetPasswordModal/reset-password-modal.tsx
- packages/hooks/src/useOauth2.ts
- packages/hooks/src/useSilentLoginAndLogout.ts
> Adrienne / Handle errors for OIDC-related login

- packages/shared/src/utils/login/login.ts
- packages/shared/src/utils/url/constants.ts
- packages/shared/src/utils/url/url.ts
Change redirection url to hub.deriv.com/tradershub/signup instead of deriv.com
https://github.com/user-attachments/assets/517ac44d-283b-4bbf-96d0-0d7a674bcac4
> Suisin/chore: change redirection url to hub.deriv.com instead of deriv.com

- packages/core/src/App/app.jsx
fix the first time account switching issue in dtrader when coming form tradershub
> fix: fix the first time account switching issue in dtrader

- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
Add setIsLoggingOut function towards mobile logout button
https://github.com/user-attachments/assets/ad5a1554-1c6e-47e7-a232-d2d59149bd75
> Suisin/chore: fix mobile logout redirection issue

- packages/core/src/App/Components/Routes/route-with-sub-routes.jsx
> fix: use total logout logic on route subroute

- packages/core/src/App/AppContent.tsx
- packages/core/src/App/Components/Routes/route-with-sub-routes.jsx
> fix: ensure logged out app will redirect correctly

- packages/core/src/Modules/Callback/CallbackPage.tsx
Checking for account in session storage in oidc callback
> fix: fixed the account syncing issue in dtrader

- packages/core/src/Modules/Callback/CallbackPage.tsx
> fix: fix for the account syncing in dtrader

- packages/core/src/Modules/Callback/CallbackPage.tsx
* fix: fix for the account syncing in dtrader
* fix: Trigger Build
> fix: fix for the account syncing in dtrader (#18222)

- packages/cfd/src/Containers/ctrader-transfer-modal/ctrader-transfer-modal.tsx
- show Transfer modal directly if the user has only one cTrader acc
https://github.com/user-attachments/assets/0ee9f2c4-78ca-4681-8cc3-5aa2027368ed
> [TRAH] george / TRAH-5801 / When Client have only one cTrader account, it should not display to choose an account modal

- packages/core/src/Modules/Callback/CallbackPage.tsx
- packages/core/src/Stores/client-store.js
Fix account switcher infinite loading issue 
https://github.com/user-attachments/assets/011eb737-10bc-4ff3-8ee0-ad4d2cdc10ef
> Suisin/chore: fix account switcher loading issue

- packages/account/src/Sections/Profile/PersonalDetails/__tests__/verify-button.spec.tsx
- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
- packages/account/src/Sections/Profile/PersonalDetails/verify-button.tsx
Passing financial_information_version for pnv if dynamic fa is enabled
> Nada/86c2texdx/set-settings/fix: issue with set settings in pnv

- packages/core/src/App/Components/Layout/Header/login-button.jsx
Edit isStaging to isStaging() because it's a function
> Suisin/chore: edit isStaging because its a function

- packages/trader/src/AppV2/Components/PurchaseButton/purchase-button.tsx
In DTrader V2 mobile add check for contract basis. If it's 'payout' and 'stake' is available, then the basis will be switched to 'stake'.
https://github.com/user-attachments/assets/421903e9-9f20-42a0-87be-4179bc4e2a72
> GRWT-5434 / Kate / Add automatic switching of contract basis

- packages/trader/src/Stores/Modules/Trading/trade-store.ts
…available choices
This PR fixes an issue with Strike price selection in Vanilla Call/Put trades when End time is set to today. Previously, when the available Strike price options changed due to market updates, the system would reset the user's selection to 0.00 or a median value. With this fix, the system now finds the closest available value to the user's previous selection, providing a more intuitive and user-friendly experience.
> Akmal / refactor: improve barrier selection logic to find closest value from available choices

- packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/__tests__/accumulators-trade-description.spec.tsx
- packages/trader/src/AppV2/Components/Guide/Description/ContractDescription/accumulators-trade-description.tsx
- packages/trader/src/Assets/Trading/Categories/Description/__tests__/accumulator-trade-description.spec.tsx
- packages/trader/src/Assets/Trading/Categories/Description/accumulator-trade-description.tsx
Change text content in Acc description section (desktop + mobile + tests)
> GRWT-5445 / Kate / Accumulator guide description changes

- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/Modules/Callback/CallbackPage.tsx
Added a check for postLoginRedirectURL if there's an account, switch to that particular account
https://github.com/user-attachments/assets/3469d4e9-b85e-48f3-9e58-baa2ca0b2de3
> Suisin/chore: fix new added wallet syncing issue in dtrader

- packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationRequest/WithdrawalVerificationRequest.tsx
- packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationRequest/__tests__/WithdrawalVerificationRequest.spec.tsx
- packages/wallets/src/features/cashier/modules/WithdrawalVerification/__tests_/WithdrawalVerification.spec.tsx
> [WALL] george / TRAH-5973 / "Press the button below" Content is Inconsistent on Withdrawal Page

- packages/core/src/Modules/ComplaintsPolicy/Components/complaints-policy-content.jsx
Content changes for DIEL complaints
> [TRAH5608] Suisin/chore: update content for DIEL complaints

- packages/cashier/src/modules/cashier-onboarding/cashier-onboarding.tsx
Fixed the order of onboarding in Cashier.
> farrah/fix: order of cashier onboarding

- packages/api-v2/src/hooks/useTransferBetweenAccounts.ts
- fix error message visibility
> [WEBREL] george / WEBREL-3936 / No error message is displayed in transfer page if client transferring an amount not allowed range

- packages/shared/src/utils/browser/browser_detect.ts
Fix IOS Device keeps logging out
> Suisin/chore: fix ios device logout issue

- packages/shared/src/utils/browser/browser_detect.ts
Fix localStorage clearing in IOS devices
> Suisin/chore: add ios specification in getUserBrowser logic

- packages/shared/src/utils/browser/browser_detect.ts
Fix Sequence of Firefox and Safari 
> Suisin/chore: change firefox and safari sequence

- packages/shared/src/utils/browser/browser_detect.ts
Move Safari check last as IOS Safari will always be in the userAgent
> Suisin/chore: fix Firefox OIDC

- packages/account/src/Containers/Account/page-overlay-wrapper.tsx
- packages/components/src/components/page-overlay/page-overlay.tsx
- packages/core/src/Stores/common-store.js
- packages/stores/src/mockStore.ts
- packages/stores/types.ts
Added a redirection to P2P in closing the accounts section if the user is coming from P2P.
> farrah/P2PS-5281/fix: add redirection to p2p

- packages/core/src/App/Containers/Redirect/redirect.jsx
Auto sync added account even user did not pass the new currency towards the URL param
https://github.com/user-attachments/assets/41ec2315-3c73-4648-bfd5-667670cc7ba5
> [TRAH6139] Suisin/chore: handle auto sync when adding different account from hub

- packages/core/src/App/Containers/RootComponent/root-component.jsx
during manage funds the useState runs twice, causing a race condition
> fix: manage funds redirection issue

- packages/trader/src/Modules/Trading/Components/Form/form-layout.tsx
- packages/trader/src/Modules/Trading/Components/Form/screen-large.tsx
- packages/trader/src/Modules/Trading/Containers/trade.tsx
> Add skeleton loaders to charts during SSO

- packages/core/src/Modules/Callback/CallbackPage.tsx
Fix hub redirect to dtrader loader keeps showing issue
> Suisin/chore: rc branch fix in master

- packages/core/src/Modules/Callback/CallbackPage.tsx
Fix OIDC loader when redirecting from hub to dtrader
> Suisin/chore: add replaceState in another if else statement

- packages/account/src/Containers/Account/account.tsx
Removed the platform session on unmount of Accounts page.
> farrah/fix: remove platform on unmount of accounts page

- packages/core/src/App/Components/Layout/Header/account-actions.jsx
- remove deposit button from cashier page
> [TRAH] TRAH-5806 / george / Deposit CTA is displayed inside deposit page

- packages/account/src/Components/error-component/error-component.tsx
- packages/core/src/App/Components/Layout/Header/login-button.jsx
- packages/core/src/App/Containers/Modals/wallets-upgrade-logout-modal/wallets-upgrade-logout-modal.tsx
- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/App/Containers/ResetPasswordModal/reset-password-modal.tsx
- packages/hooks/src/__tests__/useSilentLoginAndLogout.spec.tsx
- packages/hooks/src/useOauth2.ts
- packages/hooks/src/useSilentLoginAndLogout.ts
Fix to only render OIDC in any url that contains deriv.com
> Suisin/chore: update to render OIDC in only deriv.com

- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-flow.tsx
- packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-flow.tsx
Fixed the formatted url to use `config.platform` when redirecting to Accounts OS.
> farrah/fix: formatted url

- packages/trader/src/App/Components/Elements/ContractAudit/contract-audit.tsx
- packages/trader/src/AppV2/Components/TakeProfitHistory/__tests__/take-profit-history.spec.tsx
- packages/trader/src/AppV2/Components/TakeProfitHistory/take-profit-history.tsx
> fix: tab change

- packages/trader/src/Modules/Trading/Components/Elements/PayoutPerPoint/__tests__/payout-per-point-input.spec.tsx
- packages/trader/src/Modules/Trading/Components/Elements/PayoutPerPoint/payout-per-point-input.tsx
- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Turbos/payout-selector.tsx
feat: update payout per point content
> Akmal / feat: update payout per point content

- packages/trader/src/Stores/Modules/Trading/trade-store.ts
feat: auto-scroll to bottom of page after opening contract
> Akmal / feat: auto-scroll to bottom of page after opening contract

- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- packages/core/src/App/Containers/Layout/header/traders-hub-home-button.tsx
> [TH OS] Lubega / TRAH-6357 / Traders hub redirection account syncing

- packages/trader/src/Modules/Trading/Components/Form/DatePicker/trading-date-picker.tsx
> fix: wrong year calculation

- packages/core/src/Modules/Callback/AccessDeniedScreen.scss
Summary: When user has staging-app set to dark mode, the "Switch Account" CTA is not working/not showing (only shows when hovering over where it should be).
> Niloofar/WEBREL-4240/Fix: "Switch Account" CTA is not showing if user has app in dark mode

- packages/trader/src/AppV2/Components/TradeParameters/Duration/chips.tsx
> fix: duration issuee

- packages/trader/src/App/Components/Elements/ContractAudit/contract-audit.tsx
> fix: hide accumulator tab

- packages/hooks/src/__tests__/useAccountSettingsRedirect.spec.ts
- packages/hooks/src/useAccountSettingsRedirect.ts
get currency from queryParams instead of using loginid
https://github.com/user-attachments/assets/e2e85be0-068e-4a90-ac79-861b092d8fc8
> Suisin/chore: fix account syncing issue from dtrader to account OS

- packages/core/src/App/Components/Layout/Header/wallets/account-actions-wallets.tsx
- packages/core/src/App/Containers/Layout/header/traders-hub-header-wallets.tsx
- packages/hooks/src/__tests__/useAccountSettingsRedirect.spec.ts
- packages/hooks/src/useAccountSettingsRedirect.ts
Updated test case and resolved merge conflicts
> Moiz-WEBREL-4290-Low code TH Wallet account bug fixes when redirection

- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/hooks/src/useAccountSettingsRedirect.ts
Added redirection to OS Account Link in mobile
> Suisin/chore: fix mobile redirection issue

- packages/hooks/src/useIsHubRedirectionEnabled.ts
> fix: fixed redirection issue from dtrader to hub

- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet.tsx
Change URL to current OS format
> Suisin/chore: fix cfds redirection url to current format

- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet.tsx
> Suisin/chore: fix redirect url to current format

- packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
> fix: currency redirection in wallets account

- packages/wallets/src/components/WalletListHeader/WalletListHeader.tsx
- packages/wallets/src/components/WalletsOutsystemsMigrationModal/WalletsOutsystemsMigrationModal.tsx
- packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.tsx
Fix the following subtasks raised:
- https://app.clickup.com/t/20696747/WEBREL-4358
- https://app.clickup.com/t/20696747/WEBREL-4357
- https://app.clickup.com/t/20696747/WEBREL-4359
> [TRAH] Lubega / Wallets outsystems migration modal bugfix

- packages/wallets/src/components/WalletListHeader/WalletListHeader.tsx
- packages/wallets/src/components/WalletsOutsystemsMigrationModal/WalletsOutsystemsMigrationModal.tsx
- packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.tsx
Fix the following subtasks raised:
- https://app.clickup.com/t/20696747/WEBREL-4358
- https://app.clickup.com/t/20696747/WEBREL-4357
- https://app.clickup.com/t/20696747/WEBREL-4359
> Wallets outsystems migration modal bugfix

- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/wallets/src/components/WalletListHeader/WalletListHeader.tsx
- packages/wallets/src/components/WalletsOutsystemsMigrationModal/WalletsOutsystemsMigrationModal.tsx
> [TRAH] Lubega / Wallets outsystems migration modal dependency fix

- packages/core/src/App/Components/Layout/Header/wallets/account-actions-wallets.tsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/reports/src/Components/Elements/Modals/ServicesErrorModal/insufficient-balance-modal.tsx
- packages/trader/src/AppV2/Components/ServiceErrorSheet/service-error-sheet.tsx
> fix: use session storage first before url params

- packages/wallets/src/components/WalletsOutsystemsMigrationModal/WalletsOutsystemsMigrationModal.scss
Updated the css value for modal footer button
> Suisin/chore: fix modal button overlapped issue

- packages/wallets/src/components/WalletsOutsystemsMigrationModal/WalletsOutsystemsMigrationModal.scss
Update css for migration modal to fix overlapped issue in IOS
> Suisin/chore: sync master branch with migration button overlapped issue with rc

- packages/core/src/Stores/client-store.js
> fix: set session storage during switch

- package-lock.json
- package.json
Reverts deriv-com/deriv-app#18055
> Revert "build(deps-dev): bump the npm_and_yarn group across 1 directory with 2 updates"

- packages/account/src/Components/error-component/error-component.tsx
- packages/core/src/App/Components/Layout/Header/login-button.jsx
- packages/core/src/App/Containers/Modals/wallets-upgrade-logout-modal/wallets-upgrade-logout-modal.tsx
- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/App/Containers/ResetPasswordModal/reset-password-modal.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/core/src/Stores/client-store.js
- packages/hooks/src/useOauth2.ts
- packages/hooks/src/useSilentLoginAndLogout.ts
- packages/wallets/src/components/WalletsOutsystemsMigrationModal/WalletsOutsystemsMigrationModal.tsx
> chore: fix staying on deriv-app on second login

- packages/account/src/Components/error-component/error-component.tsx
- packages/core/src/App/Components/Layout/Header/login-button.jsx
- packages/core/src/App/Containers/Modals/wallets-upgrade-logout-modal/wallets-upgrade-logout-modal.tsx
- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/App/Containers/ResetPasswordModal/reset-password-modal.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/core/src/Stores/client-store.js
- packages/hooks/src/useOauth2.ts
- packages/hooks/src/useSilentLoginAndLogout.ts
- packages/wallets/src/components/WalletsOutsystemsMigrationModal/WalletsOutsystemsMigrationModal.tsx
> Suisin/chore: sync rc with  master

- packages/core/src/Modules/Callback/CallbackPage.tsx
> Suisin/chore: rc fix account syncing

- packages/core/src/Modules/Callback/CallbackPage.tsx
> Suisin/chore: fix account syncing

- packages/core/src/App/Containers/RootComponent/root-component.jsx
> fix: don't render while checking for redirection

- packages/core/src/App/Containers/RootComponent/root-component.jsx
Reverts deriv-com/deriv-app#18481
> Revert "fix: don't render while checking for redirection"

- packages/core/src/Modules/Callback/CallbackPage.tsx
- packages/core/src/Stores/client-store.js
> Suisin/chore: fix demo account displaying issue

- packages/core/src/Stores/client-store.js
- packages/core/src/Stores/contract-trade-store.js
- packages/stores/src/mockStore.ts
- packages/stores/types.ts
- packages/trader/src/Stores/Modules/Trading/trade-store.ts
feat: enhance accumulator barriers handling during account switching
> Akmal / feat: enhance accumulator barriers handling during account switching

- packages/core/src/App/app.jsx
- packages/core/src/Modules/Callback/CallbackPage.tsx
- packages/core/src/Stores/client-store.js
- packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.tsx
> Suisin/chore: fix demo account displaying

- packages/account/src/Components/article/article.scss
- packages/account/src/Components/self-exclusion/self-exclusion-wrapper.tsx
- packages/account/src/Components/self-exclusion/self-exclusion.scss
* Added hint on how to remove/ increase limit for MF clients
* Fixed height and css issue when the hint banner is displayed
> Hasan/TRAH-6062/Added hint on how to remove/ increase limit for MF clients

- packages/core/src/Stores/notification-store.js
> fix: update content for notification

- packages/core/src/Stores/notification-store.js
> fix: fa notification fix to master

- package-lock.json
- package.json
> Aswathy/fix: security issue for nth-check package

- packages/components/src/components/contract-card/contract-card.scss
- packages/components/src/components/data-list/data-list.tsx
- packages/trader/src/App/Components/Elements/PositionsDrawer/positions-drawer.tsx
This pull request includes multiple changes across different files, focusing on code cleanup, style adjustments, and performance improvements. The most important changes include refactoring CSS transitions for readability, optimizing imports in `data-list.tsx`, and adding a delayed execution for a measurement function in `positions-drawer.tsx`.
* [`packages/trader/src/App/Components/Elements/PositionsDrawer/positions-drawer.tsx`](diffhunk://#diff-d28667223fb6b8fc1d16524903e6594fb1cfa08f3c7e93a5cdb8350639cd689dL54-R59): Added a `setTimeout` with a delay of 0 to defer the execution of the `measure` function, ensuring it runs after the current execution context.
* [`packages/components/src/components/contract-card/contract-card.scss`](diffhunk://#diff-22918f00eed6e54fc0ebd561bfdd7e6d4258c5f89 …
> [DTrader] Farabi/grwt-6031/contract-not-appearing-after-refreshing-reports-page

- packages/account/src/Configs/__test__/user-profile-validation.spec.ts
- packages/account/src/Configs/user-profile-validation-config.ts
- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.tsx
- packages/shared/src/utils/validation/declarative-validation-rules.ts
updating state regex to accept special characters
> Amina/ fix: update_state_regex

- packages/cashier/src/components/side-notes/side-note-faq/__tests__/side-note-faq.spec.tsx
- packages/cashier/src/components/side-notes/side-note-faq/side-note-faq.tsx
> [TRAH] Lubega / Updated deposit and withdrawal FAQ

- packages/core/src/Stores/client-store.js
- packages/hooks/src/useTMB.ts
Fix defaulting value to false instead of true
> Suisin/chore: default back to false instead of true for is_tmb_enabled

- packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-list.tsx
- packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-widget.tsx
- packages/trader/src/Modules/Trading/Helpers/__tests__/contract-type.spec.tsx
- packages/trader/src/Modules/Trading/Helpers/contract-type.tsx
Reverts deriv-com/deriv-app#18543
>  "Akmal / fix: remove 'NEW!' label from contract types""

- packages/trader/src/AppV2/Components/TradeParameters/Duration/duration.tsx
> fix: expiry date wrong date in V2

- packages/core/src/App/app.jsx
remove redirect_url after login
> Suisin/chore: remove redirect_url when lands on app after login

- packages/utils/src/getActiveAccounts.ts
fix user gets logged out after failing appropriateness test
> Suisin/chore: fix user gets logged out after failing appropriateness test

- packages/utils/src/getActiveAccounts.ts
fix newly created wallet not selected
> Suisin/chore: fix newly created wallet not selected

- packages/utils/src/getActiveAccounts.ts
> Suisin/chore: fix not able to login issue

- .github/workflows/release_test.yml
> Aswathy/fix: testing the codql workflow issue in release-test.yml

- .github/workflows/release_production.yml
related to https://github.com/deriv-com/deriv-app/security/code-scanning/113
> fix: upgrade download-artifact and upload-artifact actions to the latest version

- .github/workflows/release_test.yml
> Aswathy/fix: test-release codeql workflow

- packages/trader/src/Modules/Trading/Components/Elements/PayoutPerPoint/__tests__/payout-per-point-input.spec.tsx
- packages/trader/src/Modules/Trading/Components/Elements/PayoutPerPoint/payout-per-point-input.tsx
Akmal / fix: update label from 'Distance to current spot' to 'Barrier' in PayoutPerPointInput component
> Akmal / fix: update label from 'Distance to current spot' to 'Barrier' in PayoutPerPointInput component

- .github/workflows/release_uat.yml
- .github/workflows/release_uat2.yml
> Aswathy/fix: uat security workflow issues

- .github/workflows/coveralls.yml
- .github/workflows/generate_and_push_deriv_api_types.yml
- .github/workflows/smoketests_manual.yml
- .github/workflows/test.yml
- .github/workflows/update_npm_cache.yml
> Aswathy/fix: patch github workflow permissions

- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer-accounts-os.jsx
- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
MobileDrawer overlay element not removed from DOM on exit
> Nijil/ WEBREL-4572 / MobileDrawer overlay element not removed from DOM on exit

- packages/trader/src/Modules/Trading/Components/Form/TradeParams/amount.tsx
> fix: trade param change

- .github/workflows/release_staging.yml
> Aswathy/fix: workflow permission in staging

- packages/core/src/App/Containers/AccountSwitcher/helpers/account-helper.js
> Mayuran/GRWT-6097/[DTrader] Accounts should be sorted according to the balance

- .github/workflows/release_production.yml
> Aswathy/fix: workflow permission in production

- .github/workflows/release_production.yml
> Aswathy/fix: permission security fix in production

- packages/cashier/src/containers/routes/binary-routes.tsx
> [TRAH] Lubega / Cashier redirect to outsystems

- packages/cashier/src/containers/routes/binary-routes.tsx
> [TRAH] Lubega / Cashier redirect to outsystems checks on staging

- packages/shared/src/utils/login/login.ts
- packages/shared/src/utils/url/url.ts
Added logic to include redirect url when signup from dtrader
> [GRWT-6114] Suisin/chore: add redirection url back to dtrader page after signup

- packages/core/src/Stores/client-store.js
- packages/core/src/Utils/Analytics/index.ts
> Aswathy/fix: [BUG] account_type is being passed with wrong value in trading events in deriv-app

- package-lock.json
- packages/account/package.json
- packages/cashier/src/containers/routes/binary-routes.tsx
- packages/core/package.json
- packages/core/src/App/Components/Layout/Header/login-button.jsx
- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Components/Layout/Header/wallets/account-actions-wallets.tsx
- packages/core/src/App/Containers/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- packages/core/src/App/Containers/Layout/header/traders-hub-home-button.tsx
- packages/core/src/App/Containers/RootComponent/root-component.jsx
- packages/core/src/Modules/Callback/AccessDeniedScreen.tsx
- packages/core/src/Stores/Helpers/redirectToOutSystems.ts
- packages/hooks/package.json
- packages/hooks/src/__tests__/useAccountSettingsRedirect.spec.ts
- packages/hooks/src/useAccountSettingsRedirect.ts
- packages/reports/src/Components/Elements/Modals/ServicesErrorModal/insufficient-balance-modal.tsx
- packages/shared/src/utils/config/platform-config.ts
- packages/shared/src/utils/routes/routes.ts
- packages/shared/src/utils/url/url.ts
- packages/trader/src/AppV2/Components/ServiceErrorSheet/service-error-sheet.tsx
- packages/utils/package.json
- packages/wallets/src/components/WalletsAddMoreCardBanner/__tests__/WalletsAddMoreCardBanner.spec.tsx
> Suisin/chore: fix redirection to .me and .be

- packages/core/src/Stores/client-store.js
> Aswathy/fix: account type tracking issue

- packages/trader/src/AppV2/Components/TradeParameters/Duration/day.tsx
- packages/trader/src/AppV2/Components/TradeParameters/Duration/duration.tsx
> Akmal / fix: ensure minimum duration is one day and update expiry date to today

- packages/core/src/Stores/client-store.js
- packages/core/src/Stores/traders-hub-store.js
- packages/utils/src/index.ts
- packages/utils/src/logging.ts
- add utility for logging to TrackJS and Datadog
- log wallet migration failures in client store
- log opening of wallet migration failure popup
> Add TrackJS/Datadog logs for wallet migration issues

- packages/cashier/src/containers/cashier/cashier.tsx
- packages/cashier/src/containers/routes/binary-routes.tsx
* fix: handle wallet redirection loading
* Update cashier.tsx
* Update binary-routes.tsx
* remove console.logs
* Update binary-routes.tsx
* remove extra bracket
* Update binary-routes.tsx
* rebuild to fix test cases
* fix syntax error
> Fix cashier loading due to wallet redirection (#18742)

- packages/trader/src/AppV2/Components/TradeParameters/Duration/duration.tsx
Reverts deriv-com/deriv-app#18749
> Revert "Mayuran/check length error"

- packages/trader/src/AppV2/Components/TradeParameters/Duration/duration.tsx
Reverts deriv-com/deriv-app#18750
> Revert "fix: crash"

- packages/cashier/src/containers/routes/binary-routes.tsx
- packages/components/src/components/page-error-container/page-error-container.tsx
> Add error logging and remove cookie set for wallets

- packages/core/build/webpack.config.js
> Add full hash for corejs

- packages/cashier/src/containers/routes/binary-routes.tsx
- packages/components/src/components/page-error-container/page-error-container.tsx
> chore: add console message to update hash

- packages/cashier/src/containers/routes/binary-routes.tsx
- packages/components/src/components/page-error-container/page-error-container.tsx
> chore: add console message to update hash (#18789)

- packages/hooks/src/__tests__/useIsEnabledNakala.spec.ts
- packages/hooks/src/useIsEnabledNakala.ts
> chore: fix env handling for nakala

- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
> Suisin/chore: fix phone validation error

- packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx
Fixed phone number validation error
> Suisin/chore: fix phone number field validation error

- packages/hooks/src/__tests__/useIsEnabledNakala.spec.tsx
- packages/hooks/src/useIsEnabledNakala.ts
Check if it's demo then don't call the Nakala server
> Suisin/chore: fix track js issue

- packages/hooks/src/useIsEnabledNakala.ts
Update Nakala api gateway to follow production domain for .me and .be
> Suisin/chore: update domain url for nakala api gateway

- packages/core/src/App/Containers/Modals/app-modals.jsx
- packages/core/src/App/Containers/Modals/complete-user-profile-modal/complete-user-profile-modal.tsx
added a logic check for if user has real account created, only we show complete profile modal
> Suisin/chore: add real account check for pop up modals

- packages/core/src/App/Containers/Modals/complete-user-profile-modal/complete-user-profile-modal.tsx
> chore: fix wording in complete user profile

- .github/workflows/push_and_pull_crowdin_translations.yml
- packages/cashier/src/constants/routes-config.tsx
Fixed the redirection from Cashier to P2P. Removed p2p-related actions from translation workflow.
> farrah/WEBREL-4967/fix: p2p redirection

- .github/workflows/push_and_pull_crowdin_translations.yml
- packages/cashier/src/constants/routes-config.tsx
Fixed the redirection from Cashier to P2P. Removed p2p-related actions from translation workflow.
> farrah/fix: p2p redirection

- packages/cfd/src/Containers/account-nakala-modal/account-nakala-modal.scss
Fix alignment issue with desktop view for Nakala Modal
> Suisin/chore: fix alignment issue in desktop view

- package-lock.json
- package.json
- packages/account/package.json
- packages/appstore/package.json
- packages/bot-web-ui/package.json
- packages/cashier/package.json
- packages/cfd/package.json
- packages/components/package.json
- packages/core/package.json
- packages/indicators/package.json
- packages/publisher/package.json
- packages/reports/package.json
- packages/shared/package.json
- packages/trader/package.json
- packages/trader/src/AppV2/Components/TradeParameters/Duration/day.tsx
- packages/translations/package.json
- packages/wallets/package.json
> mayuran/sept month chracter issue/GRWT-6957

- packages/trader/src/Assets/Trading/Categories/Description/__tests__/even-odd-trade-description.spec.tsx
- packages/trader/src/Assets/Trading/Categories/Description/__tests__/match-diff-trade-descriptioon.spec.tsx
- packages/trader/src/Assets/Trading/Categories/Description/even-odd-trade-description.tsx
- packages/trader/src/Assets/Trading/Categories/Description/match-diff-trade-description.tsx
- packages/trader/src/Assets/Trading/Categories/Description/vanilla-trade-description.tsx
> Mayuran / GRWT-7057 / Fix translation issue in CALL/PUT guide content
