deriv-com/deriv-app

- README.md
- package.json
- scripts/release-prod.sh
- scripts/release-staging.sh
- scripts/update-translations.sh
- src/sass/README.md
+ Changed references to `binary-static` to `deriv-app`
> + Added production and staging release scripts

- README.md
- scripts/release-prod.sh
+ Updated root README for release procedure
> Updated invalid documented `gh-pages` argument to a valid one

- package.json
- packages/core/src/App/Components/Elements/Drawer/drawer-item.jsx
- packages/core/src/App/Components/Elements/login-prompt.jsx
- packages/core/src/App/Components/Layout/Footer/toggle-fullscreen.jsx
- packages/core/src/App/Components/Layout/Footer/toggle-positions.jsx
- packages/core/src/App/Components/Layout/Footer/toggle-settings.jsx
- packages/core/src/App/Components/Routes/__tests__/binary-link.spec.js
- packages/core/src/App/Components/Routes/binary-link.jsx
- packages/core/src/App/app.jsx
- packages/core/src/Utils/Language/__tests__/fill-template.spec.js
- packages/trader/src/App/Components/Elements/Drawer/drawer-item.jsx
- packages/trader/src/App/Components/Elements/login-prompt.jsx
- packages/trader/src/App/Components/Layout/Footer/toggle-fullscreen.jsx
- packages/trader/src/App/Components/Layout/Footer/toggle-positions.jsx
- packages/trader/src/App/Components/Layout/Footer/toggle-settings.jsx
- packages/trader/src/App/Components/Routes/__tests__/binary-link.spec.js
- packages/trader/src/App/Components/Routes/binary-link.jsx
- packages/trader/src/App/app.jsx
- packages/trader/src/Modules/Contract/Containers/contract-link.jsx
- packages/trader/src/Utils/Language/__tests__/fill-template.spec.js
+ Removed `href='javascript:;'` attributes
+ Fixed webpack prefetch value in app.jsx
+ Updated Core to reflect changes
+ Added `nohoist` rule to project `hoist` script
> [core|trader] mahdi/project_updates_and_fixes

- packages/trader/scripts/release-prod.sh
- packages/trader/scripts/release-staging.sh
Update release script to be faster (also fixes build issue for release)
> [trader] mahdi/project-updates

- packages/trader/src/App/Containers/RealAccountSignup/personal-details.jsx
> Mahdi.aryayi / Updated birth-date format

- packages/bot/src/components/transactions.jsx
- packages/bot/src/stores/transactions-store.js
Dont show PL before contract expiration.
> Mahboobeh/Show PL only when contract closes

- packages/core/.babelrc
- packages/core/src/App/Containers/RealAccountSignup/account-wizard.jsx
- packages/core/src/App/Containers/RealAccountSignup/personal-details.jsx
- packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx
- packages/core/src/Stores/client-store.js
- packages/core/src/Utils/Validator/declarative-validation-rules.js
- packages/trader/src/Modules/Account/Sections/Profile/PersonalDetails/personal-details.jsx
- packages/trader/src/Utils/Validator/declarative-validation-rules.js
Reverts binary-com/deriv-app#548
> Revert "mamali/fix phone in real account signup"

- packages/components/src/components/numpad/index.js
- packages/components/src/components/numpad/number-button.jsx
- packages/components/src/components/numpad/number-grid.jsx
- packages/components/src/components/numpad/numpad.jsx
- packages/components/src/components/numpad/numpad.scss
- packages/components/src/components/numpad/step-input.jsx
- packages/components/stories/numpad/numpad.stories.js
**Components**
- Added Numpad component.
> mamali/Add Numpad Component

- packages/components/src/components/collapsible/collapsible.jsx
- packages/trader/src/sass/app/modules/trading.scss
**Trader**
Update collapsible component for `trade-params`.
> mamali / Add Collapsible in Trader

- packages/components/.storybook/addons.js
- packages/components/package-lock.json
- packages/components/package.json
- packages/components/src/components/toast-error/index.js
- packages/components/src/components/toast-error/toast-error.jsx
- packages/components/src/components/toast-error/toast-error.scss
- packages/components/stories/toast-error/toast-error.stories.js
> Add ToastError Component

- packages/trader/src/Modules/MT5/Containers/mt5-dashboard.jsx
- packages/trader/src/Modules/MT5/Helpers/constants.js
Reverts binary-com/deriv-app#777
> Revert "negar/update_mt5_server_link"

- packages/trader/src/Modules/MT5/Containers/mt5-dashboard.jsx
- packages/trader/src/Modules/MT5/Helpers/constants.js
Reverts binary-com/deriv-app#778
> Revert "negar/update_mt5_server_link_master"

- package-lock.json
- packages/bot-web-ui/package-lock.json
- packages/bot-web-ui/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/trader/package-lock.json
- packages/trader/package.json
**Trader**
- Updated to `smartcharts-beta@0.8.0-betam.3`.
**Core**
- Updated to `smartcharts-beta@0.8.0-betam.3`.
**Bot**
- Updated to `smartcharts-beta@0.8.0-betam.3`.
> zaki/ update_smartcharts_mobile

- .circleci/config.yml
Reverts binary-com/deriv-app#894
> Revert "Add docker image to release with latest tag"

- packages/components/src/components/select-native/select-native.scss
- packages/core/src/App/Containers/RealAccountSignup/account-wizard.jsx
- packages/core/src/App/Containers/RealAccountSignup/address-details.jsx
- packages/core/src/App/Containers/RealAccountSignup/terms-of-use.jsx
- packages/core/src/sass/terms-of-use.scss
Changelog
- UI fixes for new account signup.
> zaki / apply fixes for ui bugs for account signup

- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/Layout/header.jsx
- packages/trader/src/Modules/Account/Sections/Profile/FinancialAssessment/financial-assessment.jsx
- packages/trader/src/Modules/Account/Sections/Verification/ProofOfIdentity/onfido.jsx
- packages/trader/src/sass/app/modules/account.scss
Changelog
- Added `Proof of Identity` mobile responsive layouts.
- Fixed AppCrash when non high risk users manage load financial assessment pages.
> zaki / Add poi mobile

- packages/components/src/components/dialog/dialog.jsx
- packages/components/src/components/dialog/dialog.scss
- packages/components/src/components/select-native/select-native.jsx
- packages/core/src/App/Containers/AccountSignupModal/account-signup-modal.jsx
- packages/core/src/App/Containers/SetResidenceModal/set-residence-form.jsx
- packages/core/src/sass/app/modules/account-signup.scss
**Core**
- Added `PasswordMeter` to new account signup modal.
- Use `SelectNative` for country of residence on mobile.
**Components**
- Added `prop` to Dialog component to allow margin-ed full width dialog.
> zaki/ new_account_signup_mobile

- packages/trader/package-lock.json
- packages/trader/package.json
- update onfido-sdk-ui -> 5.8.0
> amam/update onfido-sdk-ui

- packages/core/src/App/Containers/AccountTypesModal/account-card.jsx
- packages/core/src/App/app.jsx
- packages/core/src/sass/app/modules/account-types.scss
The Test link is just for demonstration, the temporary modal is not included in the PR.
> Mahdi Aryayi / Add account card

- .github/CODEOWNERS
- Updated codeowners file for Trader and Shared.
> zaki / Updated codeowners

- packages/components/src/components/select-native/select-native.jsx
- packages/components/src/components/select-native/select-native.scss
- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Constants/routes-config.js
- packages/core/src/App/Containers/Layout/header.jsx
- packages/core/src/App/Containers/SetResidenceModal/set-residence-form.jsx
- packages/core/src/Modules/Cashier/Components/Error/error.jsx
- packages/core/src/Modules/Cashier/Components/Form/payment-agent-withdraw-form.jsx
- packages/core/src/Modules/Cashier/Components/Receipt/payment-agent-receipt.jsx
- packages/core/src/Modules/Cashier/Components/payment-agent-list.jsx
- packages/core/src/Modules/Cashier/Containers/cashier.jsx
- packages/core/src/Stores/Modules/Cashier/cashier-store.js
- packages/core/src/sass/app/modules/cashier.scss
- packages/trader/src/App/Containers/trade-header-extensions.jsx
- packages/trader/src/Modules/Account/Sections/Profile/FinancialAssessment/financial-assessment.jsx
- packages/trader/src/sass/app/modules/account.scss
- Updated Cashier -> Deposit pages for fiat on Mobile.
- Updated Cashier -> Payment Agents Page on Mobile.
- Updated Cashier -> Withdrawal pages for fiat on Mobile.
> zaki / Add cashier mobile

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/App/Components/Layout/Footer/toggle-settings.jsx
- packages/core/src/App/Constants/routes-config.js
- packages/core/src/App/Containers/Lazy/index.js
- packages/core/src/App/Containers/Routes/routes.jsx
- packages/core/src/Modules/Cashier/index.js
- packages/trader/package-lock.json
- packages/trader/package.json
- packages/trader/src/App/Components/Form/CompositeCalendar/composite-calendar.jsx
- packages/trader/src/App/Constants/routes-config.js
- packages/trader/src/App/Containers/Lazy/index.js
- packages/trader/src/App/Containers/Routes/routes.jsx
- packages/trader/src/App/Containers/trade-settings-extensions.jsx
- packages/trader/src/App/app.jsx
- packages/trader/src/Modules/Account/index.js
- packages/trader/src/Modules/Reports/index.js
- packages/trader/src/Modules/Trading/Components/Form/form-layout.jsx
Reverts binary-com/deriv-app#906
> Revert "oskar|mahdi/code_split_route_modules"

- packages/core/src/Stores/Modules/Cashier/cashier-store.js
(fix) - wait for authorize in cashier-store before withdrawal requests
> Oskar/wait for authorize cashier [hotfix]

- packages/components/src/components/checklist/checklist.jsx
- packages/components/src/components/checklist/checklist.scss
- packages/components/src/components/checklist/index.js
- packages/components/webpack.config.js
- packages/p2p/src/components/app.jsx
- packages/p2p/src/components/app.scss
- packages/p2p/src/components/buy-sell/buy-sell.jsx
- packages/p2p/src/components/my-ads/my-ads.jsx
- packages/p2p/src/components/my-ads/my-ads.scss
- packages/p2p/src/components/verification/verification.jsx
- packages/p2p/src/components/verification/verification.scss
Reverts binary-com/deriv-app#1292
> Revert "Sam/Revert "flow changes""

- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/core/src/Stores/client-store.js
- remove getting device data from redirect on signup
- set device data on client init
- handle device data on localstorage in mobx client store
> amam|oskar/save_params_to_storage

- packages/core/src/Modules/Cashier/Components/Form/account-transfer-form.jsx
- packages/core/src/Modules/Cashier/Containers/cashier.jsx
- packages/core/src/sass/app/modules/cashier.scss
only update side note on update of its params
> negar|mehdi/fix_render_loop

- packages/bot-web-ui/src/stores/journal-store.js
- packages/bot-web-ui/src/utils/journal-notifications.js
Fix the revert (https://github.com/binary-com/deriv-app/pull/1351) which broke expansion panel for array in journal - DBot (https://github.com/binary-com/deriv-app/pull/1128)
> Nijil/Fix the revert which caused Journal array message (expansion panel) issue.

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
- packages/core/src/Stores/Helpers/client.js
- packages/core/src/Stores/Modules/Cashier/cashier-store.js
- packages/core/src/_common/base/client_base.js
- packages/trader/src/Stores/Helpers/client.js
- packages/trader/src/Stores/Modules/MT5/Helpers/mt5-config.js
- packages/trader/src/Stores/Modules/MT5/mt5-store.js
Reverts binary-com/deriv-app#1423
> Revert "negar/update_mt5_names_prod"

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
- packages/core/src/Stores/Helpers/client.js
- packages/core/src/Stores/Modules/Cashier/cashier-store.js
- packages/core/src/_common/base/client_base.js
- packages/trader/src/Stores/Helpers/client.js
- packages/trader/src/Stores/Modules/MT5/Helpers/mt5-config.js
- packages/trader/src/Stores/Modules/MT5/mt5-store.js
Reverts binary-com/deriv-app#1277
> Revert "negar/update_mt5_names"

- .circleci/config.yml
Changelog
- chore: sync dev and master for release flow update
> sync dev with master

- packages/core/src/App/Components/Elements/CookieBanner/cookie-banner.jsx
**Changelog**
- fix: shared import in cookie-banner
> zaki / fixed_cookie_banner_import

- packages/core/src/App/Constants/routes-config.js
**Changelog**
- fix: wrong title for account subroute config
> zaki / fix_wrong_subroute_title

- packages/core/src/Stores/client-store.js
Added conditions to NOT remove affiliate_token from query params upon virtual signup
> amam-zaki/fix_affiliate_token

- packages/core/src/App/Containers/SetAccountCurrencyModal/set-currency-modal.jsx
- packages/core/src/sass/account-wizard.scss
Changelog
fix: set currency dialog truncated on mobile
> zaki / fix_truncated_set_currency_dialog_mobile

- packages/core/src/sass/app/modules/account-signup.scss
**Changelog**
- fix: account signup ui bugs
> zaki / fix_account_signup_dialog

- packages/core/src/App/Containers/RealAccountSignup/address-details.jsx
- packages/core/src/App/Containers/RealAccountSignup/personal-details.jsx
- packages/core/src/App/Containers/RealAccountSignup/signup-error-content.jsx
- landline or internet → landline, or internet
- contact email → email
- Ltd. → Limited
> salar / fix: apply CW changes

- packages/core/src/App/Components/Elements/live-chat.jsx
- add ID to the element that get clicked to open chat window
> amam/fix id livechat for GTM trigger

- packages/core/src/App/Components/Layout/Header/account-info.jsx
- packages/core/src/App/Containers/RealAccountSignup/personal-details-form.js
handle balance being undefined for no cur on default account and not having tax residence
> negar|zaki/handle_no_cur_exceptions

- packages/components/src/components/select-native/select-native.scss
- packages/core/src/App/Containers/RealAccountSignup/financial-details.jsx
- packages/core/src/App/Containers/RealAccountSignup/personal-details.jsx
- packages/trader/src/Modules/MT5/Containers/mt5-password-manager-modal.jsx
- packages/trader/src/sass/app/modules/mt5/mt5-dashboard.scss
**Changelog**
- fix: use SelectNative instead of Autocomplete for personal details in Deriv Financial account signups. (EU)
- fix: MT5 button alignment in success modal dialog.
> zaki/ fix_staging_bugs

- packages/account/src/Sections/Profile/FinancialAssessment/financial-assessment.jsx
- packages/account/src/Sections/Profile/FinancialAssessment/financial-information-list.js
Use interpolation instead of Component to translate fa dropdown values
> Bala/financial assessment mobile - dropdown fix

- package-lock.json
- packages/bot-skeleton/package-lock.json
- packages/components/package-lock.json
- packages/shared/package-lock.json
- packages/translations/package.json
Reverts binary-com/deriv-app#1597
> Revert "Mahdi Aryayi / Fixed dependencies security issues"

- packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-container.jsx
Previously we checked service token error response to determine unsupported country
recent backend changes, we used is_country_supported flag instead
> amam/fix POI unsupported country

- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/Layout/header.jsx
Disable dark theme toggle for DBot in responsive navigation drawer.
> Nijil/Dbot - disable dark theme toggle

- packages/bot-web-ui/src/components/load-modal.jsx
- packages/bot-web-ui/src/constants/load-modal.js
- packages/bot-web-ui/src/stores/load-modal-store.js
Fix an issue with load-modal component in DBot where two modal-footers got rendered.
> Nijil/DBot Hotfix - Load-modal footer issue

- packages/trader/src/Modules/Reports/Containers/statement.jsx
- Show loading placeholder when account is switching on Reports -> Statement to avoid issues with currency formatting.
- [Trello Card](https://trello.com/c/w1yNRptr)
> salar / Fix: show loading when account is switching

- packages/core/src/App/Components/Elements/Errors/error-component.jsx
**Changelog**
- fix: resolve setError issues on route history callback
> zaki / fix_error_history_callback_hook

- packages/core/src/App/Containers/RealAccountSignup/address-details-form.js
- packages/core/src/Constants/form-error-messages.js
- packages/shared/src/utils/validation/declarative-validation-rules.js
**Changelog**
- fix: re-added POBox validation and use getErrorMessages from shared validations
> zaki / fix_signup_validaitons

- packages/components/src/components/autocomplete/autocomplete.jsx
- packages/components/src/components/mobile-dialog/mobile-dialog.jsx
- packages/components/src/components/mobile-dialog/mobile-dialog.scss
- packages/core/src/App/Containers/RealAccountSignup/address-details.jsx
- packages/core/src/sass/details-form.scss
- packages/trader/src/Modules/MT5/Containers/mt5-password-modal.jsx
**Changelog**
- fix: real account responsive bug
- feat: add loader while fetching `states_list` from **API**
> zaki /  fix_real_acc_and_province_loader

- packages/account/src/Styles/account.scss
- packages/components/src/components/autocomplete/autocomplete.jsx
- packages/components/src/components/autocomplete/autocomplete.scss
- packages/trader/src/Modules/MT5/Components/mt5-poa.jsx
- packages/trader/src/sass/app/modules/mt5/mt5-dashboard.scss
**Changelog**
- fix: autocomplete toggle when clicking on trailing arrow icon
> zaki / hotfixes_poi_poa_autocomplete

- packages/shared/src/utils/login/login.js
**Changelog**
- fix: incorrect oauth urls
> zaki/fix_incorrect_oauth_urls [production]

- packages/shared/src/utils/login/login.js
**Changelog**
- fix: incorrect oauth urls
> zaki / fix_incorrect_oauth_domains

- packages/trader/src/sass/app/_common/layout/trader-layouts.scss
**Changelog**
- fix: rendering of smartcharts-portal is conflicting with closed markets overlay `z-index`
> zaki / fix_closed_markets_mobile

- packages/account/src/Sections/Security/ApiToken/api-token.jsx
- packages/account/src/Sections/Security/ApiToken/article.jsx
Fix: missing article component in API token page
> Matin/Fix missing article component in API token page

- packages/core/src/App/Containers/Layout/app-contents.jsx
**Changelog**
- fix: remove redundant domain checks and fixed `eslint` warning for hooks input deps
> zaki / remove_domain_checks

- packages/core/src/App/Containers/AccountSwitcher/account-switcher-account-list.jsx
- fix: missing demo badge in `AccountSwitcherList` when there is real currency.
> zaki / fix_missing_demo_badge

- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.jsx
**Changelog**
- fix: add tax required values for MF clients in proof of address when submitting document
> zaki / fix_mf_poa

- packages/components/src/components/card/card.jsx
- packages/components/src/components/card/card.scss
- packages/components/src/components/card/index.js
- packages/components/src/index.js
- packages/components/stories/card/card.stories.js
- packages/components/stories/card/card.stories.scss
Matin/Add: New Card component and storybook
> Matin/Add: New Card component and storybook

- packages/core/src/App/Components/Elements/Modals/DenialOfServiceModal/denial-of-service.jsx
- packages/core/src/App/Components/Elements/Modals/DenialOfServiceModal/index.js
- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
- packages/core/src/App/Containers/Layout/footer.jsx
- packages/core/src/App/Containers/Modals/app-modals.jsx
- packages/core/src/App/Containers/RealAccountSignup/add-or-manage-accounts.jsx
- packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx
- packages/core/src/Modules/Endpoint/Endpoint.jsx
- packages/core/src/Stores/client-store.js
- packages/core/src/Stores/ui-store.js
- packages/trader/src/Modules/MT5/Components/mt5-demo-account-display.jsx
- packages/trader/src/Modules/MT5/Components/mt5-real-account-display.jsx
- packages/trader/src/Modules/MT5/Containers/mt5-dashboard.jsx
- packages/trader/src/Modules/Trading/Containers/purchase.jsx
Reverts binary-com/deriv-app#1872
> Revert "negar/enable_eu"

- .github/workflows/generate_app_id.yml
> aaron/Add Deriv App ID action

- packages/components/src/components/input/input.scss
- packages/core/src/Modules/Cashier/Components/Form/account-transfer-form.jsx
- packages/core/src/Modules/Cashier/Components/Receipt/account-transfer-receipt.jsx
- packages/core/src/Modules/Cashier/Components/Receipt/payment-agent-receipt.jsx
- packages/core/src/sass/app/modules/cashier.scss
- packages/trader/src/Stores/Modules/Portfolio/Helpers/portfolio-notifications.js
**Changelog**
- fix: add currency symbol to account transfer input field
> zaki / fix_missing_currency_in_account_transfer

- packages/trader/src/App/Components/Elements/PositionsDrawer/positions-drawer.jsx
- packages/trader/src/sass/app/_common/drawer/positions-drawer.scss
**Changelog**
- fix: positions drawer card height bugs
> zaki / fix_position_drawer_bugs

- packages/core/src/Modules/Cashier/Containers/deposit.jsx
- packages/core/src/Modules/Cashier/Containers/withdrawal.jsx
**Changelog**
- fix: do not use setSideNote for mobile
> zaki / fix_cryptocashier_mobile

- packages/core/src/Modules/Cashier/Containers/deposit.jsx
- packages/core/src/Modules/Cashier/Containers/withdrawal.jsx
**Changelog**
- fix: withdrawals page for mobile cryptocashier
> zaki / fix_withdrawals_page_mobile_cryptocashier

- packages/core/src/App/Containers/RealAccountSignup/terms-of-use-messages.jsx
- packages/core/src/App/Containers/RealAccountSignup/terms-of-use.jsx
- packages/core/src/sass/terms-of-use.scss
* Fix misaligned Hr element in terms of use component and msgs.
* Separate Hr element of Set Currency and Terms of use
> Matin/Fix: misaligned Hr element in terms of use component and msgs.

- packages/components/src/components/modal/modal.jsx
Fix issue in close modal. The modal was closing and opening again on double click the outside.
> ali / fix modal close issue

- packages/components/src/components/password-meter/password-meter.jsx
- packages/components/webpack.config.js
- Load `zxcvbn` in a lazy way to reduce main bundle size
> salar / Lazy load zxcvbn

- packages/trader/src/Stores/Modules/Profit/profit-store.js
- packages/trader/src/Stores/Modules/Statement/statement-store.js
* Reset date filters and clear Profit table onUnmount
> Matin/Fix: Reset date filters and clear Profit table onUnmount

- packages/components/src/components/contract-card/contract-card.scss
- packages/components/src/components/input-field/input-field.scss
- packages/trader/src/sass/app/_common/drawer/positions-drawer.scss
**Changelog**
- style: add max-width to contract-drawer header in recent positions to handle long translation texts
> zaki / fix_positions_drawer_localization_bugs

- packages/trader/src/Modules/MT5/Components/mt5-poa.jsx
**Changelog**
- fix: mt5 poa document upload issues and validation with state dropdown
> zaki / fix_mt5_poa_upload_woes

- packages/core/src/sass/app/modules/cashier.scss
**Changelog**
- style: increase margin between form fields in mobile and handle error messages
> zaki / fix_acc_transfer_mobile

- packages/account/src/Sections/Security/DerivPassword/change-password-form.jsx
- packages/components/src/components/password-meter/password-meter.jsx
- packages/core/src/App/Containers/AccountSignupModal/account-signup-modal.jsx
- packages/core/src/App/Containers/ResetPasswordModal/reset-password-modal.jsx
- packages/core/src/Constants/form-error-messages.js
- packages/trader/src/Modules/MT5/Containers/mt5-password-manager-modal.jsx
- packages/trader/src/Modules/MT5/Containers/mt5-password-modal.jsx
- packages/trader/src/Modules/MT5/Containers/mt5-reset-password-modal.jsx
**Changelog**
- feat: add localization to password validation phrases 🔐
> zaki / add_password_warning_phrases_localization

- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/stop-loss.jsx
- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/take-profit.jsx
- packages/trader/src/sass/app/modules/trading.scss
**Changelog**
- fix: alignment for amount input field
- fix: handle overflowing of text in amount field using input wrapper
- style: corrected font-size and border-radius for currency dropdown
> zaki / fix_amount_input_alignment

- packages/components/src/components/autocomplete/autocomplete.jsx
- packages/components/src/components/date-picker/date-picker-calendar.jsx
- packages/components/src/components/date-picker/date-picker.jsx
- packages/components/src/components/date-picker/date-picker.scss
- packages/components/src/components/dropdown-list/dropdown-list.jsx
- packages/components/src/components/dropdown/dropdown.jsx
- packages/components/src/hooks/use-blockscroll.js
- packages/p2p/src/components/my-profile/my-profile.jsx
- packages/p2p/src/utils/orders.js
- packages/shared/src/utils/dom/position.js
- Disabled mouse scroll
- Fixed calendar positioning
- Refactored position function
> Akmal | Bala / Fixed calendar positioning

- .circleci/config.yml
<details> 
<summary>Spoiler</summary>
Jokes on us as we're moving away from both soon. :trollface: 
</details>
> aaron/Migrate tests from Travis to CircleCI

- packages/account/src/Sections/Verification/ProofOfIdentity/onfido.jsx
- packages/core/src/Stores/Helpers/client-notifications.js
* fix: race condition on onfido initialization
* revert phrases changes
* fix: check for empty object for missing required field
Co-authored-by: Mustofa Ghaleb Amami (Front End) <mustofa@binary.com>
> amam/fix_race_condition_onfido (#2189)

- packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx
**Changelog**
- fix: remove checks for non event click handlers for `closeModal` `func`
> zaki / fix_cashier_acc_creation_deposit_btn

- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Duration/duration-wrapper.jsx
In the `hasDurationUnit` function I've changed `duration_unit` to `duration_type` because this name is already used in the props.
> Amir / Refactor DurationWrapper component

- packages/core/src/App/Containers/RealAccountSignup/add-crypto-currency.jsx
* Refactor AddCryptoCurrency class to functional component
> Matin/Refactor: AddCryptoCurrency class to functional component

- packages/core/src/App/Containers/RealAccountSignup/change-account-currency.jsx
* ChangeAccountCurrency class to functional component
> Matin/Refactor: ChangeAccountCurrency class to functional component

- packages/core/src/App/Components/Layout/Footer/regulatory-information.jsx
updated regulatory information for MX and MLT
> suthesh/updated regulatory information for MX and MLT

- packages/components/src/components/accordion/accordion.jsx
**Changelog**
- Fixed incorrect reference for `usePrevious`.
> zaki / fix_useprevious_name_change

- packages/trader/src/App/Components/Elements/Modals/UnsupportedContractModal/unsupported-contract-modal.jsx
- Refactor unsupported contract modal to functional component
> Sean / refactor unsupported contract modal to functional component

- packages/core/src/App/Components/Layout/Footer/__tests__/toggle-fullscreen.spec.js
**Changelog**
- fix: failing tests for toggleFullscreen
> zaki / fix_toggleScreen_tests

- packages/trader/src/Modules/MT5/Containers/mt5-dashboard.jsx
**Changelog**
- fix: check if is logging_in before displaying dashboard or error message for mt5
> zaki / fix_mt5_error_message_showing_up

- packages/trader/src/App/Components/Elements/ContractDrawer/contract-drawer.jsx
These values wasn’t used anywhere:
is_collapsed
state.is_shade_on
redirectBackToReports()
> Amir / Refactor "ContractDrawer" component

- packages/account/src/Sections/Profile/FinancialAssessment/financial-assessment.jsx
* Redirect to Personal Details upon completing FA after refresh the page
> Matin/Fix: redirect to Personal Details upon completing FA

- packages/account/src/Sections/Profile/PersonalDetails/personal-details.jsx
* Enable `Email Preference` checkbox for virtual accounts in Personal Details tab
> Matin/Fix: Enable Email Preference checkbox for virtual accounts

- packages/core/src/App/Containers/Redirect/redirect.jsx
- packages/trader/src/Modules/MT5/Containers/mt5-reset-password-modal.jsx
**Changelog**
- fix: mt5 reset password issues
> zaki / fix_mt5_pw_issues [production]

- packages/core/src/Stores/client-store.js
- packages/trader/src/Modules/MT5/Components/mt5-poi.jsx
- packages/trader/src/Modules/MT5/Containers/mt5-financial-stp-real-account-signup.jsx
**Changelog**
- fix: use authentication status in case `needs_verification` status is empty and no `status` for `allow document upload`
> zaki / fix_mt5_stp_poi

- packages/cashier/src/Stores/Cashier/cashier-store.js
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/App/Components/Layout/Footer/toggle-settings.jsx
- packages/core/src/App/Containers/Routes/routes.jsx
- packages/core/src/Stores/client-store.js
- packages/core/src/_common/lazy-load.js
- packages/trader/package-lock.json
- packages/trader/package.json
- packages/trader/src/App/Components/Form/CompositeCalendar/composite-calendar.jsx
- packages/trader/src/App/Constants/routes-config.js
- packages/trader/src/App/Containers/Routes/routes.jsx
- packages/trader/src/App/Containers/trade-settings-extensions.jsx
- packages/trader/src/App/app.jsx
- packages/trader/src/Modules/Trading/Components/Form/form-layout.jsx
Reverts binary-com/deriv-app#2324
> Revert "mamali/replace react-loadable with react-loadable-hooks"

- packages/cashier/src/Components/Form/account-transfer-form.jsx
- packages/components/src/components/carousel/carousel-nav.jsx
- packages/components/src/components/carousel/carousel.jsx
- packages/components/src/components/radio-group/radio-group.jsx
- packages/components/src/components/radio-group/radio-group.scss
- packages/components/stories/carousel/carousel.stories.js
- packages/core/src/App/Containers/AccountSwitcher/account-switcher-account-list.jsx
- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
- packages/core/src/Stores/client-store.js
- packages/core/src/_common/base/socket_base.js
- packages/core/src/sass/app/_common/components/account-switcher.scss
- packages/trader/src/Modules/MT5/Components/mt5-account-card.jsx
- packages/trader/src/Modules/MT5/Components/mt5-demo-account-display.jsx
- packages/trader/src/Modules/MT5/Components/mt5-real-account-display.jsx
- packages/trader/src/Modules/MT5/Containers/mt5-dashboard.jsx
- packages/trader/src/Modules/MT5/Containers/mt5-password-manager-modal.jsx
- packages/trader/src/Modules/MT5/Containers/mt5-password-modal.jsx
- packages/trader/src/Modules/MT5/Containers/mt5-reset-password-modal.jsx
- packages/trader/src/Stores/Modules/MT5/mt5-store.js
- packages/trader/src/sass/app/modules/mt5/mt5-dashboard.scss
- packages/trader/src/sass/app/modules/mt5/mt5.scss
> Mahdi Aryayi - Mamali / Adding server selection to deriv MT5

- packages/cashier/src/Components/payment-agent-list.jsx
* Cashier PA page is rendering correctly
* Class component features removed from functional component
> Matin/Fix: Cashier PA page is rendering correctly

- packages/trader/src/Modules/MT5/Components/mt5-account-card.jsx
**Changelog**
- fix: mt5 mobile card render issue
> zaki / fix_mt5_mobile_card_render_bug

- packages/core/src/Stores/ui-store.js
- packages/core/src/sass/add-or-manage.scss
* real_account_signup_target resets on closeRealAccountSignup
> Matin/Fix: real_account_signup_target resets on closeRealAccountSignup

- packages/cashier/src/Components/payment-agent-list.jsx
> Matin/Bug: supported banks bug

- packages/account/src/Sections/Profile/FinancialAssessment/financial-assessment.jsx
- packages/components/src/components/dropdown/dropdown.jsx
- packages/components/src/components/dropdown/dropdown.scss
- packages/components/src/components/select-native/select-native.jsx
- packages/components/src/components/select-native/select-native.scss
**Changelog**
- fix: errors with text message and dropdown
> zaki / fix_dropdown_and_error_messages

- packages/cashier/src/Stores/Cashier/cashier-store.js
- add check for undefined on  `mt5_login_list`
> Kseniya/TrackJS - Cannot read property 'find' of undefined

- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/multiplier.jsx
- packages/trader/src/Modules/Trading/Containers/Multiplier/multiplier-options-modal.jsx
**Changelog**
- chore: add gross word
> zaki / add_gross_text

- packages/trader/src/sass/app/modules/mt5/mt5-dashboard.scss
- add space between button and missing-real on DMT5 page
- level the container in width
> Kseniya/UI improvement for ES language on DMT5 page

- packages/core/src/App/Constants/routes-config.js
**Changelog**
- fix: add blinking fix to dashboard context route
> zaki / fix_sign_in_bug

- packages/components/src/components/button-toggle/button-highlight-wrapper.jsx
- packages/components/src/components/button-toggle/button-highlight.jsx
**Changelog**
- fix: broken highlight color for button toggle
> zaki / fix_broken_button_toggle_highlight

- packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx
We had this on desktop here:
https://github.com/binary-com/deriv-app/pull/2590
I just added the solution to mobile as well
> Amir / Fix: Remove console error in account switcher

- packages/bot-skeleton/package-lock.json
- packages/dashboard/package-lock.json
- packages/dashboard/package.json
```diff
diff --new-file '--unified=3' --recursive --expand-tabs '--tabsize=2' --unidirectional-new-file --ignore-space-change --ignore-trailing-space --ignore-blank-lines @deriv__@__api-types-1.0.16/package/index.d.ts @deriv__@__api-types-1.0.17/package/index.d.ts
--- @deriv__@__api-types-1.0.16/package/index.d.ts	1985-10-26 08:15:00.000000000 +0000
+++ @deriv__@__api-types-1.0.17/package/index.d.ts	1985-10-26 08:15:00.000000000 +0000
@@ -8132,6 +8132,167 @@
req_id?: number;
}
/**
+ * Maximum amount for deposits for this currency.
+ */
+export type Max = number;
+/**
+ * Minimum amount for deposit for this currency.
+ */
+export type Min = number;
+/**
+ * How much time it takes for a deposit to be processed.
+ */
+export type DepositTime = string;
+/**
+ * Short description explaining …
```
> Bump @deriv/api-types to 1.0.17

- packages/core/src/Utils/pwa/register-service-worker.js
- fix: remove refresh on s/w registration
> zaki / fix_signup_refresh

- packages/account/src/Sections/Profile/PersonalDetails/personal-details.jsx
show multi tax residences if any
> negar/handle_multi_tax_residence [Prod]

- packages/core/src/App/app.js
- Cleanup the Deriv setting that located in local storage when the user comes from the signup email
> Shayan / clean on signup

- packages/core/src/Services/socket-general.js
**Changelog**
- fix: easteregg fix for signup refresh bug with qa box accounts
> zaki / fix_qabox_refresh_on_signup

- packages/core/src/Stores/Helpers/client-notifications.js
only show disabled if no auth requested
> negar/hide_redundant_notification [Prod]

- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.jsx
**Changelog**
- fix: send correct address_state value in document upload
> zaki / fix_poa_address_state

- packages/dashboard/package-lock.json
- packages/dashboard/package.json
```diff diff --new-file '--unified=3' --recursive --expand-tabs '--tabsize=2' --unidirectional-new-file --ignore-space-change --ignore-trailing-space --ignore-blank-lines @deriv__@__api-types-1.0.17/package/index.d.ts @deriv__@__api-types-1.0.19/package/index.d.ts
--- @deriv__@__api-types-1.0.17/package/index.d.ts	1985-10-26 08:15:00.000000000 +0000
+++ @deriv__@__api-types-1.0.19/package/index.d.ts	1985-10-26 08:15:00.000000000 +0000
@@ -3614,7 +3614,7 @@
/**
* Telephone (note: Only available for users who have at least one real account)
*/
-  phone?: string;
+  phone?: null | string;
/**
* Place of birth, 2-letter country code.
*/
@@ -5201,9 +5201,9 @@
| "11-39 transactions in the past 12 months"
| "40 transactions or more in the past 12 months";
/**
-   * [Optional] Starting with `+` …
```
> Bump @deriv/api-types from 1.0.17 to 1.0.19

- packages/account/src/Components/currency-selector/radio-button.jsx
- packages/components/src/components/popover/popover.scss
* Update Tether popover description
> Matin/Update: Tether popover description

- packages/cashier/src/Components/Error/error.jsx
* Centred withdrawal error message
> Matin/Fix: Centred withdrawal error message

- packages/components/src/components/password-input/password-input.jsx
- packages/components/src/components/password-input/password-input.scss
- fix: eye overlapping with lastpass icon
- fix: wrong icons for visibility of password
> zaki / fix_pw_woes

- packages/core/build/config.js
- packages/core/build/webpack.config.js
- packages/core/src/import-pushwoosh.js
Reverts binary-com/deriv-app#2918
> Revert "amam/fix_push_woosh"

- packages/core/src/Utils/pwa/register-service-worker.js
- adjust performance.now timing
> reza-amam/fix_sw

- packages/dashboard/package-lock.json
- packages/dashboard/package.json
```diff diff --new-file '--unified=3' --recursive --expand-tabs '--tabsize=2' --unidirectional-new-file --ignore-space-change --ignore-trailing-space --ignore-blank-lines @deriv__@__api-types-1.0.19/package/index.d.ts @deriv__@__api-types-1.0.24/package/index.d.ts
--- @deriv__@__api-types-1.0.19/package/index.d.ts	1985-10-26 08:15:00.000000000 +0000
+++ @deriv__@__api-types-1.0.24/package/index.d.ts	1985-10-26 08:15:00.000000000 +0000
@@ -963,6 +963,10 @@
*/
loginid?: string;
/**
+   * User's preferred language, ISO standard code of language
+   */
+  preferred_language?: null | string;
+  /**
* Scopes available to the token.
*/
scopes?: string[];
@@ -3076,6 +3080,10 @@
*/
risk_classification: string;
/**
+   * Social identity provider a user signed up with.
+   */
+ …
```
> Bump @deriv/api-types from 1.0.19 to 1.0.24

- packages/account/src/Components/personal-details/personal-details.jsx
- packages/account/src/Sections/Profile/PersonalDetails/personal-details.jsx
- packages/components/src/components/autocomplete/autocomplete.jsx
- packages/components/src/components/dropdown-list/dropdown-list.jsx
- packages/trader/src/Modules/MT5/Components/mt5-personal-details-form.jsx
This reverts commit 830df0bc64ad730229bcc587c18456374da53a72. (#2773)
> Bala/Revert Disabled user selection of disabled countries in tax residence field 

- packages/account/src/Components/currency-selector/radio-button-group.jsx
> mahdiyeh/fix: change choosing currency info message

- packages/shared/src/utils/url/constants.js
change all links pointing to deriv.com to deriv.me
change the appId to - 1411
> Habib/add 'deriv.me url support'

- packages/cashier/src/Containers/cashier.jsx
- packages/cashier/src/Containers/deposit.jsx
- remove cashier onboarding CR+EU
> amam-bahar/remove_cashier_onboarding

- packages/account/src/Sections/Security/Passwords/passwords.jsx
> Matin/Fix: Pass missing props properly

- packages/account/src/Sections/Security/DeactivateAccount/account-has-balance.jsx
- packages/account/src/Sections/Security/DeactivateAccount/deactivate-account-reason.jsx
- packages/account/src/Styles/account.scss
Reverts binary-com/deriv-app#2973
> Revert "Sean/feat(account-closure): add pending withdrawals as a third reason for disallowing account closures"

- packages/components/src/components/contract-card/contract-card-items/contract-card-body.jsx
- packages/trader/src/App/Components/Elements/PositionsDrawer/PositionsDrawerCard/positions-drawer-card.jsx
- packages/trader/src/App/Components/Elements/PositionsDrawer/positions-modal-card.jsx
**Changelog**
- fix: do not show progress slider if already sold on mobile
> zaki / fix_crypto_multipliers_positions_mobile_timer

- .circleci/config.yml
> Patch circle ci

- package-lock.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/Stores/pushwoosh-store.js
Use our in-house `web-push-notifications` package maintained by @mustofa-binary
> amam/yashim/fix: trackjs pushwoosh subscription errors

- packages/core/src/Stores/client-store.js
Fix: legal_allowed_currencies missing conditions
> Matin/Fix: legal_allowed_currencies missing conditions

- packages/core/src/App/Components/Layout/Header/account-actions.jsx
> Kseniya/Missing currency option when switching for MX to MF account

- packages/core/src/Stores/Helpers/client-notifications.js
Reverts binary-com/deriv-app#3506
> Revert "Sara / Added system-maintenance to client notification"

- packages/trader/src/Stores/Modules/Trading/trade-store.js
Set contract type to `rise_fall_equal` if user checks allow equal checkbox
> Fix: set contract type to rise_fall_equal if user checks allow equal checkbox

- packages/trader/src/Modules/CFD/Containers/cfd-password-modal.jsx
- packages/trader/src/Stores/Modules/CFD/cfd-store.js
- Fixed type in translation text
- Fixed showing trading password modal after creating new account
> [Hotfix] Mahdi / Fixed showing trading password popup after MT5 account creation

- packages/bot-web-ui/src/app/app.jsx
- packages/core/src/Stores/client-store.js
Reverts binary-com/deriv-app#3320
This revert has been requested by DBot team @mehrzad-fs
> Revert "Mikita / fixed issue according to reboot au account"

- packages/core/src/App/Components/Layout/Footer/regulatory-information.jsx
Updated links for MLT and MX licences in regulatory information.
> Maryia/Updated links for MLT and MX licences in regulatory information

- packages/account/src/Modules/Page404/Components/Page404.jsx
- packages/cashier/src/Components/Page404.jsx
- packages/components/src/components/page-error/page-error.jsx
- packages/components/src/components/page-error/page-error.scss
- packages/components/stories/page-error/README.md
- packages/components/stories/page-error/stories/basic.js
- packages/components/stories/page-error/stories/has-image.js
- packages/components/stories/page-error/stories/has-redirect.js
- packages/core/src/Modules/Page404/Components/Page404.jsx
- packages/core/src/sass/app/modules/page-404.scss
- packages/trader/src/Modules/Page404/Components/Page404.jsx
Changed view of 404 page for responsive
>  Nikita / Implementation of 404 page in Responsive mode

- packages/account/src/Components/api-token/api-token.scss
- packages/components/src/components/timeline/timeline.scss
Added padding under Step 1 on the API token page.
> Maryia/Added padding under step 1 on api-token page

- packages/core/build/config.js
- fix typo assetlinks.json for universal links
> amam/fix typo assetlinks.json

- packages/shared/src/utils/validation/declarative-validation-rules.js
> Mahdiyeh/ Fix: transfer notification when value is less than possible minimum value

- packages/account/src/Components/Routes/route-with-sub-routes.jsx
- packages/account/src/Containers/account.jsx
- packages/account/src/Sections/Profile/FinancialAssessment/financial-assessment.jsx
- packages/account/src/Sections/Profile/PersonalDetails/personal-details.jsx
- packages/cashier/src/Containers/cashier.jsx
- packages/components/src/components/page-overlay/page-overlay.jsx
- packages/components/src/components/vertical-tab/vertical-tab.jsx
- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/Layout/header/default-header.jsx
- packages/core/src/App/app.js
- packages/core/src/Stores/common-store.js
- packages/core/src/sass/app/_common/layout/header.scss
- packages/shared/src/utils/config/platform-config.js
- packages/shared/src/utils/route/route.js
Reverts binary-com/deriv-app#3692
> Revert "yashim/feat: hide headers for account + cashier when opened in mobile app"

- packages/account/src/Configs/personal-details-config.js
- packages/core/src/App/Components/Elements/NotificationMessage/notification.jsx
Setting the remoteTimeoutSession function only for timeout popups.
> Hubert / TNC button hotfix

- packages/account/src/Sections/Verification/ProofOfIdentity/onfido-sdk-view.jsx
- Add retry to get token if there is an error
- Moved error showing to another function
> yashim/fix: add token fetching retry

- packages/trader/src/Modules/CFD/Containers/cfd-dashboard.jsx
-   Fix: Update active tab index
> Matin/Fix: Update active tab index

- packages/bot-skeleton/src/scratch/blocks/Binary/After Purchase/trade_again.js
- packages/bot-skeleton/src/scratch/xml/main.xml
- packages/bot-skeleton/src/services/tradeEngine/Interface/MiscInterface.js
- packages/bot-skeleton/src/services/tradeEngine/Interface/index.js
- packages/bot-skeleton/src/services/tradeEngine/__tests__/block-tests/tools-test/Misc.js
- packages/bot-skeleton/src/services/tradeEngine/trade/Total.js
- packages/bot-web-ui/src/components/run-panel/run-panel.jsx
- packages/bot-web-ui/src/components/run-panel/run-panel.scss
- packages/bot-web-ui/src/components/toolbox/toolbox-items.jsx
- packages/bot-web-ui/src/stores/quick-strategy-store.js
- packages/bot-web-ui/src/stores/run-panel-store.js
- packages/bot-web-ui/src/stores/transactions-store.js
- packages/bot-web-ui/src/xml/dalembert.xml
- packages/bot-web-ui/src/xml/martingale.xml
- packages/bot-web-ui/src/xml/oscars_grind.xml
This reverts commit be13837b66d27cbaaec789dae818c5d564f51c07.
-   ... …
> Revert "Sara / Added SLTP to trade again (#3958)"

- .circleci/config.yml
> fix: circle ci git fetch

- packages/cashier/src/Stores/Cashier/cashier-store.js
Reverts binary-com/deriv-app#4309
> Revert "Fixed cashier height"

- packages/core/src/App/app.jsx
- packages/trader/src/Stores/Modules/Trading/trade-store.js
> mamali/Adding console info (harmless) to trigger content change

- packages/cashier/src/Stores/Cashier/cashier-store.js
Reverts binary-com/deriv-app#4360
> Revert "bahar/order_of_min_and_max_withdraw_amount_flipped"

- packages/components/src/components/drawer/drawer.jsx
Reverts binary-com/deriv-app#4270
> Revert "Mikita / refactoring Drawer component"

- packages/core/src/App/app.jsx
- packages/trader/src/Stores/Modules/Trading/trade-store.js
> Matin/Chore: Remove console logs

- packages/dashboard/src/components/pages/platforms/components/get-section/get-section.tsx
-   fix: error TrackJS 'Cannot read property '0' of undefined'
-   [x] If this change disrupt current flow
-   [ ] …
> MaryiaF/fix: error TrackJS 'Cannot read property '0' of undefined'

- packages/dashboard/src/components/pages/platforms/components/get-section/get-section.tsx
Reverts binary-com/deriv-app#4376
> Revert "MaryiaF/fix: error TrackJS 'Cannot read property '0' of undefined'"

- packages/account/package.json
- packages/bot-web-ui/package.json
- packages/cashier/package.json
Reverts binary-com/deriv-app#4317
> Revert "Bala/fix gh-pages folder build"

- packages/account/package.json
- packages/bot-web-ui/package.json
- packages/cashier/package.json
> Bala/fix gh-pages folder build

- packages/account/src/Components/poi-idv-document-submit/poi-idv-document-submit.jsx
- packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-submission.jsx
- packages/account/src/Styles/account.scss
- packages/components/package.json
- packages/components/src/components/popover/popover.jsx
- packages/core/package.json
Reverts binary-com/deriv-app#4185
> Revert "yashim/fix: tooltip ref & idv submit layout"

- packages/components/src/components/input-field/increment-buttons.jsx
- packages/components/src/components/input-field/input-field.scss
-   Fix allow equals overlap on test link
> Mahdiyeh/Fix: allow equals overlap

- packages/core/src/Stores/Helpers/client-notifications.js
-   Fix: Avoided a console error when account_status is undefined
- …
> Maryia/Fix:Avoided a console error when account_status is undefined

- packages/account/src/Components/api-token/api-token.jsx
- packages/components/src/components/button/button.scss
- packages/components/src/components/input/input.scss
> Nikita/Token name and create buttons should follow the design 

- packages/trader/src/App/Components/Elements/PositionsDrawer/__tests__/result-mobile.spec.js
- packages/trader/src/App/Components/Elements/PositionsDrawer/positions-modal-card.jsx
- packages/trader/src/App/Components/Elements/PositionsDrawer/result-mobile.jsx
-   Convert ResultMenu class component to functional one
-   [x] If this change disrupt current flow
-   [x] Ensure utility / function has a test case 
-   [ ] …
> Mahdiyeh/Improvement: convert ResultMobile  class component to functional

- packages/trader/src/Modules/Reports/Components/indicative-cell.jsx
-   Convert IndicativeCell class component to functional component
-   [] Ensure all the tests are passing
- …
> Mahdiyeh/Improvement: convert IndicativeCell class component to functional component

- packages/core/src/App/Containers/RealAccountSignup/proof-of-identity.jsx
> artsem / convert ProofOfIdentityForm from class to func

- packages/dashboard/src/components/pages/platforms/components/get-section/get-section.tsx
> "MaryiaF/fix: error TrackJS 'Cannot read property '0' of undefined'""

- packages/p2p/src/components/order-details/order-details.scss
-   Bug: Positioning of the Complain link is not proper in responsive …
> NikitaK/Bug Positioning of the Complain link(#50670)

- packages/account/src/Sections/Security/ConnectedApps/__tests__/connected-apps.spec.js
- packages/account/src/Sections/Security/ConnectedApps/connected-apps.jsx
- packages/components/jest.config.js
- packages/components/package.json
- packages/components/src/components/modal/__tests__/modal.spec.js
- packages/components/src/components/modal/modal.jsx
-  Convert ConnectedApps class component to functional
-   [x] If this change disrupt current flow
> Hojjat|Mahdiyeh/ Improvement: connected apps

- packages/trader/src/Modules/Trading/Components/Form/ContractType/__tests__/contract-type-widget.spec.js
- packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-widget.jsx
-   Convert ContractTypeWidget class component to functional component
-   [x] If this change disrupt current flow …
> Mahdiyeh/ Improvement: convert ContractTypeWidget class component to functional

- packages/trader/src/Modules/Trading/Containers/test.jsx
> Artsem / convert Test.jsx component from class to func

- packages/cashier/jest.config.js
- packages/cashier/src/Components/Error/__tests__/account-transfer-no-account.spec.js
> george/ added tests for account-transfer-no-account component

- packages/trader/src/Modules/Trading/Components/Elements/purchase-fieldset.jsx
Reverts binary-com/deriv-app#4264
> Revert "Hubert / Refactoring purchase-fieldset component"

- CNAME
> Mahdiyeh/bug: remove cname

- packages/cashier/src/Stores/payment-agent-store.js
-   fix: trackJS error cannot read properties of undefined(reading "list") …
> MaryiaF/fix: trackJS error cannot read properties of undefined(reading "list")

- packages/core/src/Stores/client-store.js
-   Fix: Remove duplicated is_bot_allowed flag
> Matin/Fix: Remove duplicated is_bot_allowed flag

- packages/core/src/App/Containers/Layout/header/default-header.jsx
-   Fix: replaceCashierMenuOnClick prop
> Matin/Fix: replaceCashierMenuOnClick prop

- packages/cashier/src/Sass/cashier.scss
-   Fix: Cashier margin top misalignment
> Matin/Fix: Cashier margin top misalignment

- packages/components/src/components/modal/modal.jsx
Reverts binary-com/deriv-app#4563
> Revert "george/added closing of modal on ESC button"

- packages/core/src/index.html
- packages/core/src/root_files/localstorage-sync.html
- packages/shared/src/utils/config/config.js
- packages/shared/src/utils/url/constants.js
Reverts binary-com/deriv-app#4489
> Revert "khalid/add deriv.be domain"

- packages/components/src/components/modal/modal.jsx
Reverts binary-com/deriv-app#4633
> george/added closing of modal on ESC button

- packages/trader/src/Modules/CFD/Containers/cfd-dashboard.jsx
> Fix: Extra import by removing it

- packages/trader/package.json
- packages/trader/src/App/Containers/Modals/success-dialog.jsx
- packages/trader/src/Modules/CFD/Containers/cfd-change-password-confirmation.tsx
- packages/trader/src/Modules/CFD/Containers/cfd-dashboard.jsx
- packages/trader/src/Modules/CFD/Containers/cfd-password-modal.jsx
- packages/trader/src/Modules/CFD/Containers/props.types.ts
- packages/trader/src/Modules/CFD/index.js
Reverts binary-com/deriv-app#4708
> Revert "Maryia/Migrated cfd-password-modal to TS"

- packages/core/src/App/Components/Layout/Header/menu-links.jsx
- packages/core/src/App/app.js
- packages/core/src/Stores/client-store.js
- packages/core/src/Stores/notification-store.js
-   Hotfix to show correct notifications 
> Maryia/Hotfix to show correct notifications 

- packages/components/src/components/modal/modal.jsx
- packages/components/src/components/numpad/numpad.jsx
- packages/components/src/components/tick-picker/tick-picker.jsx
-   This is made to fix the app crash of open modal on mobile devices. …
> Ako/ fix crash on mobile's modal

- packages/account/src/Components/poi-idv-document-submit/poi-idv-document-submit.jsx
- For Ghana, exclude voter_id document
- For Nigeria exclude voter_id, nin and nin_slip
-   [ ] …
> yashim/feat: disable certain document type for certain country

- packages/shared/src/utils/config/config.js
- packages/shared/src/utils/url/constants.js
- packages/shared/src/utils/url/helpers.js
- Added app IDs for staging
- Fixed platform redirection for deriv.be …
> khalid/deriv-be app IDs

- packages/cashier/src/Stores/general-store.js
- packages/p2p/src/components/app-content.jsx
- packages/p2p/src/components/unsupported-account/index.js
- packages/p2p/src/components/unsupported-account/unsupported-account.jsx
- packages/p2p/src/components/unsupported-account/unsupported-account.scss
- packages/p2p/src/stores/general-store.js
Reverts binary-com/deriv-app#4851
> Revert "likhith/Removed UnsupportedAccount Component"

- packages/p2p/src/components/my-profile/payment-methods/add-payment-method/add-payment-method-form.jsx
> carol/ P2P:  Missing PM name (Hotfix)

- packages/p2p/src/components/buy-sell/buy-sell-form.jsx
> carol/ P2P: Deleted payment method is sent (hotfix)

- packages/trader/src/Modules/CFD/Containers/cfd-password-manager-modal.jsx
- packages/trader/src/Modules/CFD/Containers/investor-password-manager.jsx
Refactor investor password component
> Bala/ refactor investor password

- packages/trader/src/Modules/CFD/Containers/compare-accounts-content.tsx
- packages/trader/src/Modules/CFD/Containers/compare-accounts-modal.tsx
-   Refactor compare account content as a separate component to be used by modal and also Appstore component.
-   [X] Refactor code
-   [ ] …
> Nuri/Refactor: Refactor compare account

- packages/core/src/Stores/notification-store.js
-   Fix TrackJS error - i.resetVirtualBalance is not a function
-   [ …
> MaryiaF/fix: TrackJS error - i.resetVirtualBalance is not a function

- packages/trader/src/Modules/CFD/Components/cfd-demo-account-display.tsx
- packages/trader/src/Modules/CFD/Components/cfd-poa.tsx
> MaryiaF/chore: remove consoles

- packages/translations/scripts/extract-string.js
-   Added TS files for translation extraction
> Matin/Add: TS files for translation extraction

- packages/p2p/src/components/my-profile/my-profile-header/my-profile-header.jsx
- packages/p2p/src/components/my-profile/my-profile-stats/my-profile-stats.jsx
> carol/ Hotfix: Fix stats text

- packages/p2p/src/components/advertiser-page/advertiser-page-stats.jsx
> carol/ Hotfix: Trade volume updated

- packages/p2p/src/components/buy-sell/buy-sell-header.scss
> carol/ Hotfix: Header alignment

- packages/appstore/src/components/app-card/app-card.scss
- packages/appstore/src/components/app-card/app-card.tsx
-   Added some fixes for small size of Appcard (Appstore)
-   [ ] …
> NJ/fix - Appstore Appcard styling fixes

- packages/appstore/src/components/app-card/stories/app-card.stories.tsx
-   Added Appstore app-card storybook
-   [X] New feature
> NJ/Feat: Appstore app-card storybook

- packages/p2p/src/components/my-ads/ad-status.scss
- packages/p2p/src/components/my-ads/my-ads-row-renderer.jsx
- packages/p2p/src/components/my-ads/my-ads-table.jsx
- packages/p2p/src/components/my-ads/my-ads.scss
> Artsem / Floating rate banner and warning for existing ads

- packages/p2p/src/components/advertiser-page/advertiser-page.jsx
> carol/ P2P: Fix badge

- packages/appstore/src/components/choose-product/choose-product.tsx
- packages/appstore/src/components/product-card/index.ts
- packages/appstore/src/components/product-card/platform-card.tsx
- packages/appstore/src/components/product-card/product-card-modal.tsx
- packages/appstore/src/components/product-card/product-card.scss
- packages/appstore/src/components/product-card/stories/platform-card.stories.tsx
- packages/appstore/src/components/product-card/stories/trade-type-card.stories.tsx
- packages/appstore/src/components/product-card/trade-type-card.tsx
-   Refactor product card into platform card and trade type cards
-   Storybook for platform card and trade type cards
-   Product card modal
-   [X] New feature
-   [X] Refactor code
- …
> NJ/Feat: Product card component

- packages/appstore/src/components/wallet-description/index.ts
- packages/appstore/src/components/wallet-description/stories/wallet-description.stories.tsx
- packages/appstore/src/components/wallet-description/wallet-description.scss
- packages/appstore/src/components/wallet-description/wallet-description.tsx
- packages/appstore/src/constants/wallet-description.ts
> Wallet description component

- packages/bot-skeleton/src/scratch/blocks/Math/math_on_list.js
- packages/bot-skeleton/src/scratch/blocks/Text/text_charAt.js
> Sara / Fixed issue with list rename

- packages/cashier/src/Stores/__tests__/iframe-store.spec.js
> george / add tests for iframe store

- packages/p2p/src/components/my-profile/my-profile-stats/my-profile-name/my-profile-name.jsx
> carol/ P2P: Fix incorrect trade badge in My profile

- .github/workflows/generate_app_id.yml
> Bump Binary-com/vercel-preview-url-action version

- .github/workflows/generate_app_id.yml
> yashim/chore: use latest vercel action

- .github/workflows/generate_app_id.yml
-   Fix vercel url fetching for app id generation
> yashim/fix: vercel url fetching

- packages/core/src/Stores/notification-store.js
> george / fix refreshNotifications action in notification store

- packages/trader/src/Stores/Modules/Trading/Helpers/process.js
-   Fix: Using relevant allow equals state to subscribe to correct proposal …
> Maryia/Fix: Using relevant allow equals state to subscribe to correct proposal

- packages/bot-skeleton/src/services/api/ticks_service.js
> Sara / Fixed issue with authorized api

- packages/cashier/src/Components/Error/cashier-locked.jsx
> george / fix error message for withdrawal locked status

- packages/cashier/src/Stores/__tests__/error-dialog-store.spec.js
> george / add tests for error-dialog-store

- packages/cfd/src/Containers/compare-accounts-content.tsx
> Hirad/ fix--CFD compare account table header bug

- .circleci/config.yml
> Bala/fix circle-ci bootstrap timeout

- packages/trader/src/Modules/Trading/Components/Elements/purchase-fieldset.jsx
-   Convert_purchaseField_class_to_function
> Hubert| Mahdiyeh/ refactore: convert PurchaseFieldset class component to functional

- packages/cfd/src/Components/cfd-demo-account-display.tsx
- packages/cfd/src/Components/cfd-real-account-display.tsx
-   Change **Synthetic** to **synthetic** in DerivX account page. (Read and Demo Account)
-   [ ] …
> hamid/Fix Syntethic typo in DerivX

- packages/bot-skeleton/src/services/tradeEngine/trade/Balance.js
-   Fix: The amount of Balance is not Properly shown in the Journal
- …
> MaryiaF/fix: The amount of Balance is not Properly shown in the Journal

- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Duration/duration.jsx
> fix not showing ticks on different trade type

- packages/p2p/src/components/advertiser-page/advertiser-page.scss
-   Deleted the margin-top value as it created a white space between the buy/sell tab and the buy/sell rows below. 
-   [x ] Bug fix
-   [ ] …
> ameerul / changed the margin-top for mobile view for buy-sell

- packages/account/package.json
- packages/core/package-lock.json
-   ...
-   [ X ] Dependency update
> Jim / chore: update @binary-com-binary-document-uploader to version 2_4_7

- packages/core/src/Modules/Endpoint/Endpoint.jsx
> Sara / Fixed issue with responsive issue

- packages/core/src/Stores/client-store.js
Reverts binary-com/deriv-app#5380 as it's causing withdrawal and MT5 issues
> Revert "Maryia/Fix: Hide URL query params before sending to 3rd parties"

- packages/p2p/src/components/buy-sell/buy-sell-modal.jsx
- packages/p2p/src/components/my-ads/create-ad-add-payment-method-modal.jsx
- packages/p2p/src/components/my-ads/my-ads.scss
- packages/p2p/src/components/my-ads/quick-add-modal.jsx
- packages/p2p/src/components/my-profile/my-profile-content.jsx
- packages/p2p/src/components/my-profile/payment-methods/add-payment-method/add-payment-method-form.jsx
- packages/p2p/src/components/my-profile/payment-methods/add-payment-method/add-payment-method.jsx
- packages/p2p/src/components/my-profile/payment-methods/add-payment-method/add-payment-method.scss
Reverts binary-com/deriv-app#5561
> Revert "Adrienne / P2P responsive add PM full screen modal button footers are now fixed by design"

- packages/account/src/Components/poi/idv-document-submit/__tests__/idv-document-submit.spec.js
> yauheni / IdvDocumentSubmit test coverage

- packages/cashier/src/components/resend-email-button-wrapper/__tests__/resend-email-button-wrapper.spec.js
- packages/cashier/src/components/resend-email-button-wrapper/index.jsx
- packages/cashier/src/components/resend-email-button-wrapper/resend-email-button-wrapper.jsx
- packages/cashier/src/components/verification-email/__tests__/verification-email.spec.js
- packages/cashier/src/components/verification-email/verification-email.jsx
- packages/cashier/src/pages/payment-agent/payment-agent-list/payment-agent-list.jsx
- packages/cashier/src/pages/withdrawal/withdrawal-verification-email/withdrawal-verification-email.jsx
…t button gets rerendered
-   A wrapper component added around resend email button wrapper
-   [ ] …
> Vinu/fix: a wrapper component is added around resend email button

- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.jsx
-   Removed validation for State/Province field and Postal/Zip code field
-   [X] Ensure all the tests are passing …
> likhith/removed address validation in PoA

- packages/p2p/src/stores/general-store.js
-  Added new `blockUnblockUser` function
-  Refactored some observables `is_block_user_modal_open`, `block_unblock_user_loading`, and `block_unblock_user_error` which were used in both my profile and advertiser page to be included in general store
-   [ ] …
> Block unblock function draft

- packages/cfd/src/Containers/missing-real-account.tsx
- packages/cfd/src/sass/cfd-dashboard.scss
> Aizad/ adjust stylings for missing real account heder

- packages/p2p/src/components/orders/orders.scss
> farrah/ fixed order table row spacing

- packages/p2p/src/components/buy-sell/buy-sell-form.jsx
-   Added a condition to update the received amount when the amount or exchange rate has changed
- …
> farrah/ update received amount if rate has changed

- packages/p2p/src/components/buy-sell/buy-sell-form-receive-amount.jsx
> farrah/ formatted invalid buy/sell amount

- packages/p2p/src/components/buy-sell/buy-sell-form.jsx
- packages/p2p/src/stores/buy-sell-store.js
> farrah/ fixed input amount validation on buy/sell form

- packages/p2p/src/components/my-ads/my-ads-row-renderer.jsx
-   Disabled edit button on ads page if user is temporary banned
-   [ …
> farrah/ disabled edit button for temporary banned users

- now.json
> fix: fix vercel build

- packages/p2p/src/components/order-details/order-details.scss
- packages/p2p/src/components/orders/order-table/order-table-row.jsx
- packages/p2p/src/components/orders/orders.scss
-   Fixed overlapping status by reducing the font-size
> farrah/ fixed overlapping status in order page

- packages/account/src/Components/real-account-signup/__tests__/splitValidationResultTypes.spec.js
- packages/account/src/Components/real-account-signup/helpers/__tests__/splitValidationResultTypes.spec.js
> Test Case for splitValidationResultTypes

- package-lock.json
- packages/appstore/.storybook/webpack.config.js
- packages/appstore/package.json
- packages/appstore/src/components/cards-link/cards-link.tsx
- packages/appstore/tsconfig.json
- packages/components/.storybook/webpack.config.js
- packages/components/package.json
> Fix appstore build

- packages/cashier/src/containers/cashier/cashier.jsx
- packages/cashier/src/containers/cashier/cashier.scss
-   Fixed height of cashier wrapper in mobile
> farrah/ fixed height of cashier wrapper in mobile

- packages/bot-web-ui/src/stores/transactions-store.js
Reverts binary-com/deriv-app#6024
> Revert "MaryiaF/fix: P/L is not getting updated when a contract is terminated…"

- packages/p2p/src/stores/floating-rate-store.js
> farrah/ fixed exchange rate subscription error

- packages/p2p/src/components/buy-sell/buy-sell-form.jsx
> farrah/ fixed sell form validation

- packages/cfd/src/Helpers/constants.ts
-   Updated MT5 windows app url
> Matin/Updated MT5 windows app url

- .circleci/config.yml
-   Use context (project) instead of repository defined variables
@balakrishna-binary
> Use context instead repository defined environment variables

- packages/components/src/components/accordion/accordion.jsx
- packages/components/src/components/autocomplete/autocomplete.jsx
- packages/components/src/components/input-field/input-field.jsx
- packages/components/src/components/input-field/input.jsx
-   Fixed eslint errors in components workspace
> farrah/ fixed component eslint errors

- packages/cfd/src/Components/cfd-account-card.tsx
> Amina/ trade-modal-fix

- packages/components/src/components/dropdown/display-text.jsx
> george: fix proptypes for value, add number type (DisplayText component)

- packages/components/src/components/input-field/input-field.jsx
> Akmal / Convert string into integer

- packages/cfd/src/sass/cfd-dashboard.scss
> Hirad/ Added scroll on the y axis for mt5-trade-modal

- packages/p2p/src/stores/my-ads-store.js
> farrah/ fixed typo error in price rate validation message

- packages/account/src/Components/api-token/api-token.scss
-   in this PR we implement proper alignment of the api token in account settings when the user checks only one access scope …
> george / rm71464 / align api token

- packages/reports/src/sass/app/modules/reports.scss
-  Fix profit_loss color in profit table of Reports menu
-   [x] If this change is adding new flow
-   [ ] …
> Mahdiyeh/fix: profit_loss color in profit table of reports

- packages/core/src/Stores/portfolio-store.js
- packages/trader/src/App/Components/Elements/PositionsDrawer/positions-drawer.jsx
- packages/trader/src/Stores/Modules/Trading/trade-store.js
-    Show barrier price when hover on open positions
> Mahdiyeh/ Fix: show barrier price when hover on open positions cards

- packages/shared/src/utils/validation/declarative-validation-rules.js
-   Removed the validation if the user provided a single letter
-   [ …
> farrah/ fixed town/city validation

- packages/bot-web-ui/src/components/contract-card-loading/contract-card-loading.tsx
- packages/bot-web-ui/src/components/summary/summary-card.tsx
- packages/bot-web-ui/src/components/summary/summary-card.types.ts
-   Convert summary-card to TS
> MaryiaF/refactor: convert summary-card to ts

- packages/cfd/src/Components/cfd-account-card.tsx
- packages/cfd/src/Containers/mt5-compare-table-content.tsx
> Hirad/ Finished MF urgent changes

- packages/components/src/components/positions-drawer-card/index.js
- packages/components/src/components/positions-drawer-card/positions-drawer-card.jsx
- packages/components/src/index.js
- packages/reports/build/webpack.config.js
- packages/reports/src/Components/Elements/PositionsDrawerCard/index.js
- packages/reports/src/Containers/open-positions.jsx
- packages/trader/build/loaders-config.js
- packages/trader/src/App/Components/Elements/PositionsDrawer/positions-drawer.jsx
-   Move PositionsDrawerCard to components
-   Remove Reports from Trader's loaders-config
-   [x] If this change is adding new flow
-   [ ] …
> Mahdiyeh/Improvement:move PositionsDrawerCard from reports to components

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
> Hirad/ Fixed the bug in account switcher which causes the app to crash

- packages/p2p/src/components/advertiser-page/advertiser-page.jsx
- packages/p2p/src/components/advertiser-page/advertiser-page.scss
- packages/p2p/src/components/my-profile/my-profile-stats/my-profile-name/my-profile-name.jsx
- packages/p2p/src/components/recommended-by/recommended-by.jsx
- packages/p2p/src/components/recommended-by/recommended-by.scss
- packages/p2p/src/components/user-rating-button/user-rating-button.jsx
… and profile
-   Check if only user has ratings to display user ratings and if they were recommended
-   If user has no recommendations, still display recommendations but set default value to 0
-   Changed in my profile and advertiser page
-   [ ] Translation …
> Ameerul /Bug 69036 rating thumbs removed when the user is not recommended

- packages/cashier/src/components/transfer-confirm/transfer-confirm.tsx
> george / align transfer-confirm component

- packages/cfd/src/Containers/jurisdiction-modal-content.tsx
> yashim/feat: update jurisdiction order

- packages/bot-web-ui/src/app/app.jsx
-   Added Hotjar script for tracking the user data only for `DBot`
- …
> added hotjar script and fixed eslint errors

- packages/account/src/Components/poi/status/upload-complete/__tests__/upload-complete.spec.js
-   Fix UploadComplete tets file
> Mahdiyeh/fix: UploadComplete test file

- packages/components/src/components/mobile-drawer/mobile-drawer.scss
> thisyahlen/ mobile drawer glitch

- packages/appstore/src/components/app-launcher/app-launcher.scss
- packages/appstore/src/components/app-launcher/app-launcher.tsx
- packages/appstore/src/components/app-launcher/index.ts
- packages/appstore/src/components/app-launcher/stories/app-launcher.stories.tsx
> Vinu/feat: add app launcher component

- packages/core/src/Stores/rudderstack-store.js
-  Fixing the issue- Cannot_read_properties_of_null_(reading_'toString') …
> Amina/trackjs: reading tostring() of undefined

- .circleci/config.yml
- .eslintrc.js
- .github/workflows/codecov.yml
- .github/workflows/generate_and_push_deriv_api_types.yml
- .github/workflows/push_and_pull_crowdin_translations.yml
- .prettierignore
- README.md
- e2e_tests/README.md
- package-lock.json
- package.json
- packages/account/package.json
- packages/appstore/package.json
- packages/bot-web-ui/package.json
- packages/cashier/package.json
- packages/cashier/src/stores/__tests__/account-transfer-store.spec.js
- packages/cfd/package.json
- packages/components/package.json
- packages/core/package.json
- packages/indicators/package.json
- packages/p2p/package.json
- packages/p2p/src/components/order-details/__test__/order-details-cancel-modal.spec.js
- packages/publisher/package.json
- packages/reports/package.json
- packages/shared/package.json
- packages/trader/package.json
- packages/translations/package.json
> Update node 16.16.0

- packages/cfd/src/Containers/mt5-trade-modal.tsx
- packages/core/src/Constants/cfd-text.js
- packages/shared/src/utils/cfd/cfd.js
> Hirad/ Removed MFSA from MF cfds

- packages/trader/src/sass/app/modules/trading.scss
> Aizad / Fix Gap Dtrader Multiplier

- packages/core/src/sass/app/modules/account-signup.scss
> yauheni / 73461 extra white space between Choose Country and Next button

- packages/core/src/public/.well-known/apple-app-site-association
-   Add redirect url for p2p in AASA
> Add redirect url for p2p in AASA

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
-   Fix: Issue with real accounts with no currency assigned
-   [ ] …
> Matin / Fix: Issue with real accounts with no currency assigned

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
-   Fixe issue on real accounts with no currency
> Matin/Fix: issue on real accounts with no currency

- package-lock.json
- packages/bot-web-ui/package.json
- packages/cfd/package.json
- packages/components/package.json
- packages/core/package.json
- packages/p2p/package.json
- packages/reports/package.json
- packages/trader/package.json
> Niloofar Sadeghi / Account switcher issue

- packages/components/src/components/progress-bar-onboarding/index.ts
- packages/components/src/components/progress-bar-onboarding/progress-bar-onboarding.scss
- packages/components/src/components/progress-bar-onboarding/progress-bar-onboarding.tsx
- packages/components/src/index.js
> Hirad/ Onboarding progress bar

- packages/appstore/src/components/add-derived/add-derived.scss
- packages/appstore/src/components/add-derived/add-derived.tsx
- packages/appstore/src/components/add-derived/index.ts
- packages/appstore/src/components/add-derived/stories/add-derived.stories.tsx
- packages/components/src/components/icon/appstore/ic-appstore-add-rounded.svg
- packages/components/src/components/icon/icons.js
- packages/components/stories/icon/icons.js
-   Add More Derived accounts component
> Mahdiyeh/Feature: add more derived acounts component

- packages/shared/src/utils/date/__tests__/date-time.spec.js
- packages/shared/src/utils/date/date-time.js
> eduard-deriv / moment.js bugfix

- packages/components/src/components/fade-wrapper/index.js
- packages/components/src/components/icon-trade-types/index.js
> Niloofar Sadeghi / Circleci issue

- packages/cfd/src/sass/cfd-dashboard.scss
> Hirad/ Added scroll to cfd personal details modal

- packages/core/src/App/Containers/AccountSignupModal/validate-signup-fields.jsx
-   Remove resticted country validation from citizenship
-   [ ] …
> Amina/remove  disabled country validation from citizenship

- packages/appstore/src/components/add-options-account/add-options-account.scss
- packages/appstore/src/components/add-options-account/add-options-account.tsx
- packages/appstore/src/components/add-options-account/index.ts
- packages/appstore/src/modules/trading-hub/index.tsx
- packages/core/src/App/Components/Layout/Header/menu-links.jsx
- packages/core/src/App/Containers/Layout/header/trading-hub-header.jsx
- packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx
> thisyahlen/create an options account component 

- packages/p2p/src/components/advertiser-page/advertiser-page.scss
…ments
-   Aligned avatar profile icon in advertiser page to `flex-start` as per design requirements
-   [ ] Dependency …
> Adrienne / Aligned avatar to flex start in advertiser page

- packages/p2p/src/components/my-profile/my-profile-stats/my-profile-name/my-profile-name.jsx
- packages/p2p/src/components/my-profile/my-profile-stats/my-profile-name/my-profile-name.scss
- packages/p2p/src/components/my-profile/my-profile.scss
- Fixed an issue where the block user count is not aligned correctly in responsive according to design
- Fixed an issue where the Blocked Advertisers tab in responsive is not fully visible at the bottom
- Cleaned up styling class names and necessary subclasses
-   ...
-   [ ] …
> Adrienne / Fixed alignment issues with block user count in responsive and bug where Blocked Advertisers responsive tab is not fully visible

- packages/p2p/src/components/advertiser-page/block-user/block-user-count.jsx
- packages/p2p/src/stores/general-store.js
-   Block user count is now updated live according to subscription in `p2p_advertiser_info`
-   [ ] …
> Adrienne / Made block user count to be subscribed to updates

- packages/p2p/src/components/my-profile/block-user/block-user-table/block-user-row.jsx
- packages/p2p/src/components/my-profile/block-user/block-user.scss
-   Removed styling for hovering on responsive for each blocked advertiser list rows as per design requirements
-   [ ] …
> Adrienne / Removed hover styling for responsive in blocked advertisers list

- packages/account/src/Components/poi/status/unsupported/unsupported.jsx
- packages/account/src/Sections/Verification/ProofOfIdentity/onfido.jsx
- packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-container.jsx
- packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-submission.jsx
Reverts binary-com/deriv-app#6093
> Revert "fix: display the status for manual upload"

- packages/p2p/src/components/advertiser-page/advertiser-page.scss
-   Made advertiser page scrollable in responsive when no ads
-   [ ] …
> Adrienne / Scrollable advertiser page when no ads in responsive

- packages/bot-skeleton/src/services/api/__tests__/ticks-service.js
- packages/bot-skeleton/src/services/api/appId.js
- packages/bot-skeleton/src/services/tradeEngine/trade/Balance.js
- packages/bot-skeleton/src/services/tradeEngine/trade/index.js
- packages/bot-skeleton/src/services/tradeEngine/utils/cliTools.js
- packages/bot-skeleton/src/services/tradeEngine/utils/interpreter.js
- packages/bot-web-ui/src/app/app.jsx
Reverts binary-com/deriv-app#6555
> Revert "sandeep/65842/unifiy-websocket -- using the same websocket instance from the core …"

- packages/cashier/src/stores/general-store.js
- packages/cashier/src/stores/verification-store.js
-   In Withdrawal resend email button, the counter starts from any random number, it is been fixed in these changes.
-   [ ] …
> Vinu/fix: resend email counter fix on language change

- packages/p2p/src/components/my-ads/edit-ad-form.jsx
- packages/p2p/src/components/my-ads/my-ads.scss
-  Fixed rate field for edit ad form in buy/sell ad is highlighted now instead of greyed out as placeholder
-   [ ] …
> Adrienne / Made Fixed rate field for edit ad form to be highlighted

- nx-cloud.env.example
- nx.json
-   This is to fix the NX cloud token configuration on CI and local machine.
- Also timeout limitation disabled for low speed connections
-   [x] Improve performance
-   [ …
> Ako / 78353 - NX cloud token config improvement

- package.json
-   What i have done is to build the components workspace before others to fix the icons problem.  …
> Ako/ 78371 - Fix build script on nx

- .github/workflows/codecov.yml
> Ako/ update codecov to version 3

- package.json
> Ako/ skip nx cache for components ws

- packages/cfd/src/Components/__tests__/cfd-download-container.spec.js
- packages/cfd/src/Components/cfd-download-container.tsx
- packages/cfd/src/Containers/mt5-trade-modal.tsx
- packages/cfd/src/Helpers/constants.ts
- packages/cfd/src/sass/cfd-dashboard.scss
-   Remove icons and links for mt5-ios app
> remove icons and links for mt5 ios

- packages/p2p/src/components/advertiser-page/advertiser-page.scss
-   Advertiser page is scrollable for screen heights less than or equal to `580px`
-   [ ] …
> Adrienne / Made advertiser page scrollable for very small screen heights

- packages/p2p/src/components/advertiser-page/advertiser-page.scss
-   Real name is now shown at bottom of alternative name when it is too long in advertiser page
- …
> Adrienne / Real name is now shown at bottom of alternative name when it is too long in advertiser page

- packages/p2p/src/components/app.jsx
- packages/p2p/src/components/modal-manager/index.js
- packages/p2p/src/components/modal-manager/modal-manager-context-provider.jsx
- packages/p2p/src/components/modal-manager/modal-manager-context.js
- packages/p2p/src/components/modal-manager/modal-manager.jsx
> farrah/ added modal manager component

- packages/p2p/src/components/buy-sell/buy-sell-form.jsx
> farrah/68222/fixed decimal point in buy/sell amount

- packages/p2p/src/components/buy-sell/__tests__/buy-sell-form-receive-amount.spec.js
-   ...
-   [x] Improve performance
> farrah/55725/add test coverage for BuySellFormReceiveAmount component

- packages/cfd/src/Components/cfd-real-account-display.tsx
- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
> Akmal / Content changes for market restructures

- packages/core/src/Stores/ui-store.js
-    Removing the observable decorator from ui-store
> Amina / remove observable from store

- packages/trader/src/Modules/Trading/Components/Form/DatePicker/trading-date-picker.jsx
> Niloofar / Page not loading when end time is shown

- packages/core/src/App/Containers/WelcomeModal/welcome.jsx
> Akmal / Fix: synthetic to derived on welcome modal

- packages/p2p/src/components/buy-sell/currency-selector/currency-selector.scss
- packages/p2p/src/stores/buy-sell-store.js
> farrah/ fixed cross border ad style

- packages/cashier/src/pages/p2p-cashier/p2p-cashier.jsx
> carol/P2P: show order id in the url after refresh

- packages/p2p/src/stores/my-ads-store.js
-   When adding a new payment method using quick add, you have no ads will show quickly before it reloads the page and shows the updated table. Fixed this issue as it kept resetting the adverts list to an empty array each call.
- …
> Ameerul /Task 79023 You have no Ads" page shown while adding payment methods.

- packages/account/src/Styles/account.scss
> Suisin/fix: broken poa page in responsive mode

- packages/p2p/src/components/buy-sell/filter-modal/filter-modal-header.jsx
- packages/p2p/src/components/buy-sell/filter-modal/filter-modal-search.jsx
- packages/p2p/src/components/buy-sell/filter-modal/filter-modal.jsx
-   Wrapped FilterModalResult in observer as when user searches, the component wouldn't rerender despite it updating the list and setting the loader to true.
-   [ ] …
> Ameerul /Bug 80766 Search payment method filter on buy/sell page does not work as expected

- packages/cfd/src/Components/cfd-account-card.tsx
- packages/cfd/src/sass/cfd-dashboard.scss
> Aizad/ Fix MT5 alignment for both financial and derived section

- packages/bot-web-ui/src/stores/quick-strategy-store.ts
-   fix cognitive complexity of the Quick Strategy store
-   [ ] …
> MaryiaF/81160/refactor: fix cognitive complexity of the Quick Strategy store

- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
> thisyahlen/ bugfix: exit trader hub not redirecting to dtrader

- packages/appstore/src/components/platform-launcher/platform-launcher.tsx
> thisyahlen/ fix: remove new tab for binary bot

- packages/core/src/App/Constants/routes-config.js
> fix: using different_routes_for_appstore

- packages/appstore/src/modules/trading-hub/index.tsx
- packages/cfd/build/webpack.config.js
- packages/cfd/src/Containers/cfd-server-error-dialog.tsx
> Amina/ fix: mt5_server_error_on_mt5_for_trading_hub

- packages/cfd/src/Containers/mt5-compare-table-content.tsx
Reverts binary-com/deriv-app#6951
> Revert "Amina/ fix: pending_verification_derivx_fix"

- packages/appstore/src/modules/trading-hub/index.tsx
- packages/cfd/build/webpack.config.js
- packages/cfd/src/Containers/cfd-server-error-dialog.tsx
Reverts binary-com/deriv-app#6945
> Revert "Amina/ fix: mt5_server_error_on_mt5_for_trading_hub"

- packages/appstore/src/components/onboarding/static-applauncher.scss
- packages/appstore/src/components/onboarding/static-platform-launcher.scss
Reverts binary-com/deriv-app#6937
> Revert "thisyahlen /fix: trade button cursor not allowed"

- packages/core/src/App/Constants/routes-config.js
Reverts binary-com/deriv-app#6932
> Revert "fix: using different_routes_for_appstore"

- packages/appstore/src/components/platform-launcher/platform-launcher.tsx
Reverts binary-com/deriv-app#6925
> Revert "thisyahlen/ fix: remove new tab for binary bot"

- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
Reverts binary-com/deriv-app#6922
> Revert "thisyahlen/ bugfix: exit trader hub not redirecting to dtrader"

- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/components.types.ts
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/data/common-input-properties.ts
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/data/data-fields.ts
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/data/data-uniq-input-obj.ts
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/description.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/duration-fields.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/fields.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/form.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/index.ts
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/input-field.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/inputs.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/selects.tsx
- packages/bot-web-ui/src/stores/quick-strategy-store.ts
-   fix: cognitive Complexity of the Quick Strategy Form and other code smells of new DBot
-   [ ] …
> MaryiaF/78803/refactor: cognitive complexity of the Quick Strategy Form and other code smells of new DBot

- packages/bot-web-ui/src/components/dashboard/dashboard.tsx
> fix: for--tour-guides-missing-state

- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/form.tsx
-   fix: should go throw properly for 2 which is minimum for Martingale …
> MaryiaF/81969_2/should go throw properly for 2 which is minimum for Martingale

- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/form.tsx
-   fix: validation martingale-size of quick strategy form
-   [ ] …
> MaryiaF/81969/fix: validation martingale-size of quick strategy form

- packages/cfd/src/Components/cfd-account-card.tsx
- packages/cfd/src/Components/cfd-real-account-display.tsx
- packages/cfd/src/Components/props.types.ts
- packages/cfd/src/Containers/cfd-dashboard.tsx
- packages/cfd/src/Containers/compare-accounts-modal.tsx
- packages/cfd/src/Containers/mt5-compare-table-content.tsx
- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
> Aizad/ Fix: show cooldown modal in cfd when trading is disabled

- packages/bot-skeleton/src/scratch/hooks/css.js
- packages/bot-web-ui/src/components/dashboard/dashboard-component/index.scss
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/index.scss
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/workspace-control.tsx
- packages/shared/src/styles/themes.scss
-   fix: any style's remarks as per new design DBot
> MaryiaF/82437/fix: any style's remarks as per new design DBot

- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/expiration.jsx
-   Fix moment format unit translation
> Matin/fix: moment format unit translation

- packages/bot-web-ui/src/components/dashboard/tutorial-tab/guide-content.tsx
-   fix: rename 2 guide titles
> MaryiaF/81793(2)/fix: rename 2 guide titles

- packages/bot-skeleton/src/scratch/hooks/css.js
- packages/bot-web-ui/src/stores/save-modal-store.ts
-   Dashboard - preview for the recent strategy is not getting displayed, saved strategy -> status should be "Local"
-   [ ] …
> MaryiaF/82150/Dashboard - preview for the recent strategy is not getting displayed, saved strategy -> status should be "Local"

- packages/core/src/App/Containers/CitizenshipModal/same-citizenship-modal.jsx
- packages/core/src/sass/app/modules/account-signup.scss
> thisyahlen/ chore: add citizenship title to signup

- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy.types.ts
- packages/bot-web-ui/src/stores/quick-strategy-store.ts
-   fix: martingale_size field of quick strategy before compile xml, required strict name
-   [ ] …
> MaryiaF/82060/fix: martingale_size field of quick strategy before compile xml, required strict name

- packages/bot-skeleton/src/scratch/dbot-store.js
- packages/bot-skeleton/src/utils/local-storage.js
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/recent-workspace.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/recent.tsx
- packages/bot-web-ui/src/stores/app-store.js
- packages/bot-web-ui/src/stores/load-modal-store.ts
-   fix: clicking on create and edit should update dashboard page
- …
> MaryiaF/82458/fix: clicking on create and edit should update dashboard page

- packages/account/src/Sections/Security/Passwords/deriv-email.jsx
-   ...
-   [X] Update feature
> Suisin: update feature: hide change email button for Deriv Go users

- packages/core/src/Stores/client-store.js
- packages/core/src/_common/utility.js
> Suisin/fix: bugs on netherlands client

- .commitlintrc.json
> Ako/ disable subject-case rule on commitlint

- packages/appstore/src/components/CFDs/cfd-accounts.tsx
- packages/appstore/src/components/onboarding/static-dashboard.tsx
-   Fix the compare accounts title in traders hub for mf clients
-   [ …
> Amina/fix: title in compare accounts modal

- packages/p2p/src/components/buy-sell/buy-sell-modal.jsx
- packages/p2p/src/constants/api-error-codes.js
- packages/p2p/src/stores/buy-sell-store.js
- packages/p2p/src/stores/my-profile-store.js
-   New PR based from https://github.com/binary-com/deriv-app/pull/6355 with new branch updated from latest master
-   [ ] …
> Adrienne / Show popup on changes in rates

- packages/core/src/sass/app/_common/layout/header.scss
> Akmal / fix: trader's hub bad UI

- packages/core/src/App/Containers/PlatformContainer/PlatformContainer.jsx
- packages/core/src/Modules/Endpoint/Endpoint.jsx
- packages/core/src/Stores/client-store.js
> feat: use BE flag for traders hub ui

- packages/appstore/src/components/account/account.scss
- packages/appstore/src/components/account/account.tsx
- packages/appstore/src/components/options/options-accounts.scss
> chore: restructure account.tsx file and stylings

- packages/cfd/src/Containers/mt5-compare-table-content.tsx
-   Removing derivx content from mt5 dashboard for logged out users
- …
> Amina/ 83129/fix: Compare_accounts_modal_is_broken

- packages/p2p/src/components/modal-manager/modal-manager-context-provider.jsx
- packages/p2p/src/components/modal-manager/modal-manager.jsx
- packages/p2p/src/components/modal-manager/modals/my-ads-floating-rate-switch-modal/index.js
- packages/p2p/src/components/modal-manager/modals/my-ads-floating-rate-switch-modal/my-ads-floating-rate-switch-modal.jsx
- packages/p2p/src/components/my-ads/my-ads-row-renderer.jsx
- packages/p2p/src/components/my-ads/my-ads-table.jsx
- packages/p2p/src/constants/modals.js
- packages/p2p/src/stores/my-ads-store.js
- packages/p2p/webpack.config.js
> farrah/78924/refactor MyAdsFloatingRateSwitchModal

- packages/core/src/index.html
- packages/core/src/sass/app/_common/layout/app-layouts.scss
> Ameerul /Bug 83922 P2P page is blocked in portrait mode in tablet view

- packages/account/src/Components/poi/idv-document-submit/idv-document-submit.jsx
- packages/account/src/Components/poi/poi-form-on-signup/idv-doc-submit-on-signup/idv-doc-submit-on-signup.jsx
> Suisin/fix: bugs on validation message showing when flag not added to URL

- packages/account/src/Components/poi/idv-document-submit/idv-document-submit.jsx
- packages/account/src/Components/poi/poi-form-on-signup/idv-doc-submit-on-signup/idv-doc-submit-on-signup.jsx
> fix: bugs on validation message showing when flag not added to URL

- packages/core/src/App/Containers/Layout/header/dashboard-platform-header.jsx
- packages/core/src/App/Containers/Layout/header/default-header.jsx
- packages/core/src/App/Containers/Layout/header/dtrader-header.jsx
- packages/core/src/App/Containers/Layout/header/trading-hub-header.jsx
- packages/core/src/App/Containers/NotificationsDialog/notifications-dialog.jsx
- packages/core/src/App/Containers/app-notification-messages.jsx
- packages/core/src/Stores/notification-store.js
- packages/trader/src/Stores/Modules/Trading/trade-store.js
-   please notice the comment in the card regarding the implementation: 
currently, without design we just need to hide all notifications into bell icon, and for saving the functionality I just added buttons for these notifications in the toastbox
-   [ ] …
> yauheni/83718/remove all popup notifications from deriv app)

- packages/cashier/src/pages/payment-agent-transfer/__tests__/payment-agent-transfer.spec.js
- packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer-confirm/__tests__/payment-agent-transfer-confirm.spec.js
- packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer-confirm/payment-agent-transfer-confirm.jsx
- packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer-form/__tests__/payment-agent-transfer-form.spec.js
- packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer-form/payment-agent-transfer-form.jsx
- packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer-receipt/__tests__/payment-agent-transfer-receipt.spec.js
- packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer-receipt/payment-agent-transfer-receipt.jsx
- packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer.jsx
-   replace connect with useStore
-   fix tests
> george / rm78415 / replace connect with useStore in payment-agent-transfer page

- packages/cashier/src/pages/payment-agent/__tests__/payment-agent.spec.js
- packages/cashier/src/pages/payment-agent/payment-agent-container/__tests__/payment-agent-container.spec.js
- packages/cashier/src/pages/payment-agent/payment-agent-container/payment-agent-container.jsx
- packages/cashier/src/pages/payment-agent/payment-agent-list/deposit-tab.tsx
- packages/cashier/src/pages/payment-agent/payment-agent-list/payment-agent-list.tsx
- packages/cashier/src/pages/payment-agent/payment-agent-list/withdrawal-tab.tsx
- packages/cashier/src/pages/payment-agent/payment-agent-listed-withdraw-form/__tests__/payment-agent-listed-withdraw-form.spec.js
- packages/cashier/src/pages/payment-agent/payment-agent-listed-withdraw-form/payment-agent-listed-withdraw-form.jsx
- packages/cashier/src/pages/payment-agent/payment-agent-receipt/__tests__/payment-agent-receipt.spec.js
- packages/cashier/src/pages/payment-agent/payment-agent-receipt/payment-agent-receipt.jsx
- packages/cashier/src/pages/payment-agent/payment-agent-search-box/payment-agent-search-box.jsx
- packages/cashier/src/pages/payment-agent/payment-agent-unlisted-withdraw-form/__tests__/payment-agent-withdraw-form.spec.js
- packages/cashier/src/pages/payment-agent/payment-agent-unlisted-withdraw-form/payment-agent-unlisted-withdraw-form.jsx
- packages/cashier/src/pages/payment-agent/payment-agent-withdraw-confirm/__tests__/payment-agent-withdraw-confirm.spec.js
- packages/cashier/src/pages/payment-agent/payment-agent-withdraw-confirm/payment-agent-withdraw-confirm.jsx
- packages/cashier/src/pages/payment-agent/payment-agent.jsx
-   replace connect with useStore
-   fix tests
-   [x] Improve performance
> george / rm78414 /  replace connect with useStore in payment-agent page

- packages/account/src/Configs/trading-assessment-config.js
> chore: ammend last question on trading assessment

- packages/bot-web-ui/src/components/chart/chart.scss
- packages/bot-web-ui/src/components/chart/chart.tsx
- packages/bot-web-ui/src/components/chart/toolbar-widgets.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard-component/index.scss
- packages/bot-web-ui/src/components/dashboard/dashboard.scss
- packages/bot-web-ui/src/components/dashboard/dashboard.tsx
- packages/components/src/components/collapsible/arrow-button.tsx
- packages/components/src/components/collapsible/collapsible.tsx
-   feat: Charts Tab - responsive :
1) markets container & markets dropdown
2) toolbar widgets & showing window
3) absence zoom
4) run panel
- …
> MaryiaF/82106/feat: Charts Tab - responsive

- packages/bot-web-ui/src/components/dashboard/bot-builder/bot-builder.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard.scss
- packages/bot-web-ui/src/components/dashboard/joyride-config.tsx
> fix: bot builder tour text alignments

- packages/shared/src/utils/helpers/duration.ts
- packages/trader/src/Stores/Modules/Trading/Actions/contract-type.js
- packages/trader/src/Stores/Modules/Trading/Helpers/allow-equals.js
- packages/trader/src/Stores/Modules/Trading/Helpers/contract-type.js
> chore: fix bugs occur when contract type is change

- packages/trader/src/App/Components/Routes/__tests__/route-with-sub-routes.spec.tsx
- packages/trader/src/App/Components/Routes/route-with-sub-routes.jsx
> Niloofar Sadeghi / Refactor tests in the route-with-sub-routes.spec.tsx file (trader)

- packages/reports/src/Components/Routes/__tests__/route-with-sub-routes.spec.tsx
- packages/reports/src/Components/Routes/route-with-sub-routes.jsx
> Niloofar Sadeghi / Refactor tests in the route-with-sub-routes.spec.tsx file (reports)

- packages/core/src/App/Components/Layout/Header/__tests__/platform-switcher.spec.tsx
- packages/core/src/App/Components/Layout/Header/platform-switcher.jsx
> Niloofar | Refactor tests in the platform-switcher.spec.tsx file

- packages/core/src/App/Components/Layout/Footer/__tests__/toggle-settings.spec.tsx
- packages/core/src/App/Components/Layout/Footer/toggle-settings.jsx
> Niloofar | Refactor tests in the toggle-settings.spec.tsx file

- packages/cashier/src/containers/routes/__tests__/route-with-sub-routes.spec.tsx
- packages/cashier/src/containers/routes/route-with-sub-routes.tsx
> Niloofar Sadeghi / Refactor tests in the route-with-sub-routes.spec.tsx file

- packages/p2p/src/stores/my-profile-store.js
-   Ad details tab was not loading as is_loading observable was set to true. Changed it to false.
- …
> Ameerul /Bug 84394 Ad details tab not loading

- packages/account/src/Components/account-limits/account-limits.jsx
-   changed sort function for "Derived" section of Account limits
- …
> Sergei / 84373 / stable text sequence in Derived section of Account limits

- packages/p2p/src/components/buy-sell/buy-sell-modal.jsx
- packages/p2p/src/components/buy-sell/buy-sell-modal.scss
- packages/p2p/src/components/my-ads/create-ad-add-payment-method-modal.jsx
- packages/p2p/src/components/my-ads/my-ads.scss
- packages/p2p/src/components/my-profile/my-profile-content.jsx
- packages/p2p/src/components/my-profile/payment-methods/add-payment-method/add-payment-method-form.jsx
- packages/p2p/src/components/my-profile/payment-methods/add-payment-method/add-payment-method.scss
- packages/p2p/src/components/my-profile/payment-methods/payment-methods-list/edit-payment-method-form.jsx
- packages/p2p/src/components/my-profile/payment-methods/payment-methods-list/payment-methods-list.scss
- packages/p2p/src/components/my-profile/payment-methods/payment-methods.jsx
-   Refactored the footer that shows the cancel and add button within add pm modal for both responsive and desktop
-   [ ] …
> Ameerul /Cancel and Add button in Add PM Modal getting cropped in Mobile browsers

- packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal.tsx
-   set auto height of modal container for Deriv MT5 Financial
-   [ ] …
> sergei / 83340 / set auto height of modal container

- packages/bot-web-ui/src/components/chart/chart.scss
-   feat: change styles of the market container on the tab charts
- …
> Maryia/84436/feat: change styles of the market container on the tab charts

- packages/bot-web-ui/src/components/dashboard/tutorial-tab/dialog.scss
- packages/bot-web-ui/src/components/dashboard/tutorial-tab/faq-content.tsx
- packages/bot-web-ui/src/components/dashboard/tutorial-tab/guide-content.tsx
- packages/bot-web-ui/src/components/dashboard/tutorial-tab/index.scss
- packages/bot-web-ui/src/components/dashboard/tutorial-tab/sidebar.scss
- packages/bot-web-ui/src/components/dashboard/tutorial-tab/sidebar.tsx
-   Made new DBot Dashboard tutorials tab mobile responsive
-   [ ] …
> fix: made tutorials tab mobile responsive

- packages/p2p/src/components/my-profile/my-profile-stats/my-profile-stats-table/my-profile-stats-table.scss
-   Fixed padding issues for translations ID and FR
> Ameerul /Bug 84647 [Staging, Deriv app, p2p, My profile,Stats] Elements are displayed incorrectly in ID and FR languages

- packages/bot-web-ui/src/components/dashboard/dashboard-component/cards.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard-component/dashboard-component.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard-component/index.scss
- packages/bot-web-ui/src/components/dashboard/dashboard-component/user-guide.tsx
… strategies as per new design
-   feat: responsive - dashboard tab
- …
> Maryia/82103/feat: responsive - dashboard tab

- packages/bot-web-ui/src/components/dashboard/dashboard-component/index.scss
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/index.scss
- packages/bot-web-ui/src/components/load-modal/load-modal.scss
-   Fixed preview button not visible
-   Fixed minor css and alignment issues with preview & strategy lists
-   [ ] …
> fix: on preview open button is not visible, and alignment fixes

- packages/account/src/Sections/Security/TwoFactorAuthentication/two-factor-authentication.jsx
> Hamza/ fix: Spacing between lines in 2FA page

- packages/core/src/App/Containers/AcuityDownloadModal/acuity-download-modal.tsx
> chore: fix translation issue on acuity modal

- packages/components/src/components/popover/popover.tsx
- packages/core/src/App/Components/Layout/Header/__tests__/account-info.spec.tsx
- packages/core/src/App/Components/Layout/Header/account-info.jsx
> Niloofar | Refactor tests in the account-info.spec.tsx file

- packages/p2p/src/components/order-details/order-details.jsx
- packages/p2p/src/components/order-details/order-details.scss
-   Fixed the instruction details from being overflowed inside div
- …
> Ameerul /Bug 84478 Instruction details are trimmed in the order details page for both buy/sell orders.

- packages/core/src/App/Containers/Modals/app-modals.jsx
> likhith/fix: :bug: resolved issue with trade modal

- packages/bot-web-ui/src/components/chart/chart.scss
-   fix: indent of the toolbar widget for real mobile devices
-   [ ] …
> Maryia/84645/fix: indent of the toolbar widget

- packages/bot-web-ui/src/components/dashboard/dashboard-component/cards.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/footer.tsx
- packages/bot-web-ui/src/components/dashboard/tour-slider.tsx
- packages/bot-web-ui/src/components/dashboard/tour-trigger-dialog.tsx
- packages/bot-web-ui/src/components/dashboard/tutorial-tab/sidebar.tsx
- packages/bot-web-ui/src/stores/dashboard-store.ts
-   fix: code smells of sonar cloud
> Maryia/85089/fix: code smells of sonar cloud

- packages/core/src/App/Containers/Modals/app-modals.jsx
Reverts binary-com/deriv-app#7291
> Revert "likhith/fix: :bug: resolved issue with trade modal"

- packages/bot-web-ui/src/components/chart/chart.scss
- packages/bot-web-ui/src/components/dashboard/dashboard.scss
-   feat: appearance markets dropdown
> Maryia/85333/feat: appearance markets dropdown

- packages/core/src/Utils/Language/__tests__/language.spec.js
> Niloofar Sadeghi / Task - Refactor tests in the language.spec.js file

- packages/trader/src/Stores/Modules/Trading/Helpers/__tests__/proposal.js
> Niloofar Sadeghi / Task - Refactor tests in the proposal.js file

- packages/trader/src/App/Components/Routes/__tests__/binary-link.spec.tsx
- packages/trader/src/App/Components/Routes/binary-link.jsx
> Niloofar Sadeghi / Task - Refactor tests in the binary-link.spec.tsx file

- packages/components/src/components/mobile-dialog/mobile-dialog.jsx
- packages/trader/src/Modules/Trading/Components/Form/ContractType/ContractTypeMenu/contract-type-menu.jsx
- packages/trader/src/Modules/Trading/Components/Form/ContractType/__tests__/contract-type-dialog.spec.tsx
- packages/trader/src/Modules/Trading/Components/Form/ContractType/__tests__/contract-type-menu.spec.js
> Niloofar Sadeghi / Task - Refactor tests in the contract-type-dialog.spec.tsx file

- packages/core/src/App/Components/Layout/Header/__tests__/platform-dropdown.spec.tsx
- packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
> Niloofar Sadeghi / Task - Refactor tests in the platform-dropdown.spec.tsx file

- packages/bot-web-ui/src/components/chart/chart.scss
-   fix: handle edge chart tool issue
> Maryia/fix: handle edge chart tool issue

- packages/bot-web-ui/src/components/dashboard/bot-builder/toolbar/toolbar-icon.tsx
-   Fixed toolbar for mobile responsive
> fix: toolbar is not working as expected on mobile

- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.jsx
-   ...
-   [x] Translation to code
> Hamza/85884 /chore: textual change 85884

- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.jsx
> Hamza/85884/ chore: removal of the statement from poa [Prod]

- packages/reports/src/Components/market-symbol-icon-row.jsx
- packages/reports/src/Helpers/market-underlying.js
-   fix bug when for Higher/Lower Trade type contracts Rise/Fall is shown …
> fix: Higher/Lower Trade type contracts Rise/Fall is shown

- packages/core/src/App/Components/Layout/Header/account-info.jsx
- packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
- packages/core/src/App/Components/Layout/Header/platform-switcher.jsx
- packages/core/src/App/Containers/Layout/header/dashboard-platform-header.jsx
- packages/core/src/App/Containers/Layout/header/default-header.jsx
- packages/core/src/Stores/client-store.js
-   Added a condition to ensure that required data in available before the switcher is  displayed. Added a skeleton loader to keep the UI engaged …
> likhith/fix: :bug: resolved flickering issue in platform switcher

- packages/p2p/src/components/my-profile/payment-methods/payment-methods-list/delete-payment-method-error-modal.jsx
-   Replaced old text with new one for modal title
> Ameerul /Bug 56864 Improve error dialogue box

- packages/p2p/src/components/buy-sell/buy-sell-table.jsx
- packages/p2p/src/components/buy-sell/no-ads/index.js
- packages/p2p/src/components/buy-sell/no-ads/no-ads.jsx
- packages/p2p/src/components/buy-sell/no-ads/no-ads.scss
- packages/p2p/src/components/my-ads/create-ad-form.jsx
- packages/p2p/src/components/my-ads/my-ads.jsx
- packages/p2p/src/stores/buy-sell-store.js
-   Added new component no-ads
> Ameerul /Task 84193 Deriv P2P - Encourage/Initiate Users to Create Ads when there are no ads on the Buy/Sell screen

- packages/p2p/src/components/buy-sell/currency-dropdown.scss
- packages/p2p/src/stores/buy-sell-store.js
-   Fixed issue where text is not overflowing in currency dropdown
- …
> Ameerul /Task 84018 Currency filter UI breaks for lengthy legacy currencies

- packages/bot-web-ui/src/components/dashboard/dashboard-component/index.scss
- packages/shared/src/styles/devices.scss
-   fix: UI issues on Iphone(SE)
> Maryia/86306/fix: UI issues on Iphone(SE)

- packages/bot-web-ui/src/components/run-panel/run-panel.scss
- packages/bot-web-ui/src/components/summary/summary.tsx
-   fix: summary tab of run panel
> Maryia/86513/fix: summary tab of run panel

- .github/workflows/generate_app_id.yml
- Add permissions to GITHUB_TOKEN for `.github/workflows/generate_app_id.yml`
-   [x] Script configuration
> Add permissions to GITHUB_TOKEN

- .github/workflows/push_and_pull_crowdin_translations.yml
> chore: github_token permissions

- .github/workflows/lighthouse.yml
- Give back permissions for GITHUB_TOKEN
-   [x] Script configuration
> Specify GITHUB_TOKEN permissions for lighthouse.yml

- packages/core/src/Stores/notification-store.js
> hamza/hotfix: dp2p notification comming incase of 2 accounts

- packages/bot-web-ui/src/components/chart/chart.scss
-   fix: handle edge chart tool issue
> Maryia/86112/fix: handle edge chart tool issue

- packages/appstore/src/constants/regulators-modal-content.ts
> thisyahlen/chore: remove Volatility 150 Index and Volatility 250 Index for eu regulation

- packages/core/src/App/Containers/NotificationsDialog/notifications-dialog.jsx
> thisyahlen/fix: empty notification dropdown

- packages/core/src/Stores/traders-hub-store.js
> Amina/fix: cfd listing fix

- packages/core/src/Stores/traders-hub-store.js
> Amina/ fix: console_error

- packages/appstore/src/components/options-multipliers-listing/index.tsx
> thisyahlen/fix: trade button

- packages/core/src/App/Components/Elements/Modals/RedirectNotice/redirect-notice-modal.jsx
- packages/core/src/App/Containers/Modals/app-modals.jsx
> Mahdiyeh/ fix: showing notice popup for LOW_RISK/NON_EU

- packages/bot-web-ui/src/stores/app-store.js
- packages/core/src/Stores/client-store.js
> Amina/ fix: is_eu_flag and dbot 

- packages/bot-web-ui/src/stores/app-store.js
- packages/core/src/Stores/client-store.js
> Amina fix is eu flag

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
> Amina/ fix: mf_list

- packages/core/src/App/Containers/Modals/exit-traders-hub-modal/exit-traders-hub-modal.jsx
- packages/core/src/Stores/client-store.js
> 87814/fix blank onboarding  for non en lang

- packages/cfd/src/Containers/cfd-password-modal.tsx
> Sergei / 87513 / change create mt5 demo account congratulations text

- packages/account/src/Components/hooks/useToggleValidation.tsx
- packages/account/src/Components/poi/idv-document-submit/idv-document-submit.jsx
- packages/account/src/Components/poi/poi-form-on-signup/idv-doc-submit-on-signup/idv-doc-submit-on-signup.jsx
> Hubert / fixing IDV validation

- packages/p2p/src/components/my-ads/edit-ad-form.jsx
- packages/p2p/src/stores/my-profile-store.js
-   ... Fixed page breaking and console error when user tries to edit the ad where payment method is disabled from BO
-   [ ] …
> fix: console error on edit ad where payment method is disabled from bo

- packages/stores/src/mockStore.ts
> fix(stores): :green_heart: add missing default value to `mockStore`

- packages/core/src/App/Components/Layout/Footer/regulatory-information.jsx
- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/Layout/default-footer.jsx
- packages/core/src/App/Containers/Layout/trading-hub-footer.jsx
> fix: regulatory information

- packages/core/src/App/Components/Layout/Footer/regulatory-information.jsx
- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/Layout/default-footer.jsx
- packages/core/src/App/Containers/Layout/trading-hub-footer.jsx
Reverts binary-com/deriv-app#7543
> Revert "fix: regulatory information"

- packages/core/src/App/Components/Layout/Footer/regulatory-information.jsx
- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/Layout/default-footer.jsx
- packages/core/src/App/Containers/Layout/trading-hub-footer.jsx
> Mahdiyeh/ fix: regulatory information for non-eu client

- packages/appstore/src/components/currency-switcher-card/real/real-account-switcher.scss
- packages/appstore/src/components/currency-switcher-card/real/real-account-switcher.tsx
- packages/appstore/src/components/main-title-bar/asset-summary.scss
- packages/appstore/src/components/main-title-bar/asset-summary.tsx
- packages/appstore/src/components/main-title-bar/regulators-switcher.scss
- packages/appstore/src/components/main-title-bar/regulators-switcher.tsx
> thisyahlen/fix: all dem barrel spins

- packages/appstore/src/constants/tour-steps-config-new.tsx
> Sergei / 88004 / Rephrase EU/Non-EU regulation pop-up

- packages/appstore/src/components/modals/regulators-compare-modal/regulators-compare-modal-content.tsx
- packages/appstore/src/components/modals/regulators-compare-modal/regulators-compare-modal.tsx
> Sergei / 88006 / Remove 's' from the Non-EU and EU regulations pop up

- packages/shared/src/utils/brand/brand.ts
> Mahdiyeh/ fix: error on traders hub page

- packages/core/src/Stores/client-store.js
- packages/shared/src/utils/url/url.ts
> Sergei / 88005 / page not loading after create demo account

- packages/core/src/Stores/traders-hub-store.js
> thisyahlen/fix: regulation switcher for high risk

- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/index.scss
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/recent-workspace.tsx
-   fix: texts are being cut off under the recent tabs
> MaryiaF/86306_3/fix: texts are being cut off under the recent tabs

- packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity.jsx
- packages/core/src/index.html
- packages/shared/src/utils/dom/seo_optimization.ts
-   udpating meta tag with og:title and og:description for proof of identity page
-   [ ] …
> evgeniy/87910/update meta tags og:title and og:description on proof of identity page

- packages/cfd/src/Containers/cfd-dashboard.tsx
> fix: somethings not right in logged out mt5 page

- packages/core/src/Stores/client-store.js
-   delete extra '/' when signup with lang query
> Sergei / 88629 / When refreshing the traders hub onboarding page the page block size changes

- packages/core/src/App/Components/Elements/Modals/RedirectNotice/redirect-notice-modal.jsx
- packages/core/src/Stores/gtm-store.js
> Niloofar / Fix repository security issue: Incomplete regular expression for hostnames

- packages/account/src/Sections/Security/AccountClosed/account-closed.jsx
- packages/bot-web-ui/src/stores/run-panel-store.js
- packages/cashier/src/stores/base-store.ts
- packages/cfd/src/Stores/base-store.js
- packages/core/src/App/Containers/RedirectToLoginModal/redirect-to-login-modal.jsx
- packages/core/src/App/initStore.js
- packages/core/src/Services/logout.js
- packages/core/src/Stores/base-store.js
- packages/core/src/Stores/client-store.js
- packages/core/src/Stores/portfolio-store.js
- packages/reports/src/Stores/base-store.js
- packages/trader/src/Stores/Modules/Trading/trade-store.js
- packages/trader/src/Stores/base-store.js
Reverts binary-com/deriv-app#7631
> Revert "Fix  local storage sync"

- packages/core/src/Services/socket-general.js
Reverts binary-com/deriv-app#7623
> Revert "fix: localstorage sync"

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
> Amina/ fix: account label

- package-lock.json
- packages/bot-web-ui/package.json
- packages/core/package.json
- packages/trader/package.json
-   ...
-   [x] Dependency update
> maryia/88811/build: Update @deriv/deriv-charts to 1.1.2

- package-lock.json
- packages/bot-web-ui/package.json
- packages/core/package.json
- packages/trader/package.json
This reverts commit dbe55f5d1673771739e6db68515695cd6ab3c1d2.
-   ... …
> Revert "build: Update @deriv/deriv-charts to 1.1.2 (#7637)"

- package-lock.json
- packages/bot-web-ui/package.json
- packages/core/package.json
- packages/trader/package.json
Reverts binary-com/deriv-app#7637
> Revert "maryia/88811/build: Update @deriv/deriv-charts to 1.1.2"

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
-   add check for virtual account for AccountSwitcher component
-   [ …
> Sergei / 88770 / While adding crypto account from demo tab, it showing the real account creation flow

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
-   Checking if the client have any real account to show manage modal or signup modal
-   [ ] …
> Amina/fix: 89022_personal_details_section_on_signup

- packages/account/src/Components/address-details/address-details.jsx
- packages/account/src/Components/personal-details/personal-details.jsx
- packages/account/src/Configs/address-details-config.js
- packages/account/src/Configs/personal-details-config.js
> Amina/fix: 89134_real_account_signup_fields_not_editable

- packages/reports/src/Containers/open-positions.jsx
- packages/reports/src/Containers/profit-table.jsx
- packages/reports/src/Containers/statement.jsx
- packages/trader/src/App/Containers/Modals/trade-modals.jsx
- packages/trader/src/Modules/Contract/Containers/contract-replay.jsx
> Niloofar Sadeghi / Task - Fix repository security issue: Client-side URL redirect

- packages/shared/src/utils/url/url.ts
> Niloofar Sadeghi / Incomplete URL substring sanitization

- packages/appstore/src/components/CFDs/cfd-accounts.tsx
- packages/appstore/src/components/CFDs/cfd-demo-accounts.tsx
- packages/appstore/src/components/CFDs/cfd-real-accounts.tsx
- packages/appstore/src/components/onboarding/static-dashboard.tsx
- packages/appstore/src/components/options/options-accounts.tsx
- packages/appstore/src/components/platform-launcher/platform-launcher.tsx
> yashim/fix: missing localise/improper use of localise

- packages/appstore/src/components/CFDs/cfd-real-accounts.tsx
- packages/core/src/Stores/traders-hub-store.js
- packages/shared/src/utils/cfd/available-cfd-accounts.ts
> yashim/fix: translations

- packages/appstore/src/constants/trading-hub-content.tsx
- packages/appstore/src/modules/onboarding/onboarding.tsx
> yashim/fix: onboarding translations

- packages/appstore/src/constants/tour-steps-config-new.tsx
- packages/appstore/src/modules/tour-guide/tour-guide.tsx
-   ...
-   [x] Translation to code
> yashim/fix: onboarding carousel translations

- packages/appstore/src/constants/tour-steps-config-new.tsx
> yashim/fix: translation in tour-steps-config

- packages/appstore/src/constants/tour-steps-config.tsx
- packages/appstore/src/constants/trading-hub-content.tsx
- packages/translations/scripts/__tests__/extract-string.spec.js
- packages/translations/scripts/extract-string.js
> yashim/fix: improper formatted strings

- packages/cfd/src/sass/cfd-dashboard.scss
-   add styles in cfd-dashboard
> Sergei / 89763 / Server maintenance notice message alignment and font color not proper from account switcher

- package-lock.json
- packages/translations/package.json
- packages/translations/scripts/extract-string.js
> Niloofar Sadeghi / Dependabot alerts

- packages/p2p/src/components/my-profile/block-user/block-user-table/block-user-table.scss
-   added a set height to data list table as autosizer was interfering with the height of the table …
> Ameerul /Bug 87254 Scrolling is not working when reduce the screen size 

- packages/core/src/Stores/client-store.js
- packages/core/src/_common/utility.js
> yashim/feat: add continent to cookie

- packages/account/src/Sections/Assessment/TradingAssessment/trading-assessment.jsx
> likhith/89901/feat: :bug: fixed issue in trading assessment

- packages/core/src/App/Components/Layout/Header/menu-links.jsx
> thisyahlen/fix: show cashier button in header for all

- packages/core/src/App/Components/Layout/Header/menu-links.jsx
> Amina/fix: show reports tab for products

- packages/core/src/App/Containers/NotificationsDialog/notifications-dialog.jsx
- packages/core/src/Stores/notification-store.js
> Adrienne / fixed an issue where is_notifications_visible is undefined and displays error console

- packages/cashier/src/pages/p2p-cashier/p2p-cashier.tsx
- packages/core/src/Stores/notification-store.js
- packages/p2p/src/stores/general-store.js
- packages/stores/src/mockStore.ts
- packages/stores/types.ts
-   Fixed issue for redirecting to p2p my profile page
> Ameerul /Bug 90562 Unable to click on Increase My Limits button

- packages/appstore/src/components/cfds-listing/index.tsx
-   change display_login to display for dxtrade
> Sergei / 90218 / Change Account Number to Username in Deriv X Trader's Hub Dashboard

- packages/cashier/src/pages/account-transfer/account-transfer-receipt/account-transfer-receipt.tsx
- packages/components/src/components/dropdown/items.jsx
-   add check for modal and call the function 'onClose' only when there is modal
-   [ ] …
> Sergei / 88327 / Trackjs Error: t is not a function

- packages/account/src/Components/poi/status/unsupported/card-details/card-details.scss
- packages/account/src/Styles/account.scss
- packages/cashier/src/components/cashier-search-box/cashier-search-box.scss
- packages/components/src/components/autocomplete/autocomplete.scss
- packages/components/src/components/date-picker/date-picker-native.jsx
- packages/components/src/components/date-picker/date-picker.scss
- packages/components/src/components/field/field.scss
- packages/components/src/components/input/input.scss
- packages/components/src/components/input/input.tsx
- packages/components/src/components/password-input/password-input.scss
- packages/components/src/components/search-box/search-box.scss
- packages/components/src/components/select-native/select-native.scss
- packages/components/src/components/select-native/select-native.tsx
- packages/core/src/sass/details-form.scss
- packages/p2p/src/components/my-profile/my-profile-form/my-profile-form.scss
Reverts binary-com/deriv-app#7752
> Revert "Suisin/chore: asterisk title overlapped solved"

- packages/core/src/App/Containers/RealAccountSignup/account-wizard.jsx
> fix: not showing cooldown modal when user clicks no on signup

- packages/bot-web-ui/src/stores/google-drive-store.js
> Vinu/fix: to resolve 500 error from google server on upload

- packages/account/src/Components/poi/idv-document-submit/utils.js
- Refactor `getDocumentData` function
> Kate/91181/Unable to create real account from Kenya country

- packages/translations/src/i18next/i18next.ts
-   Remove `indonesia` language from allowed language
> yashim/chore: remove indonesia from production

- packages/core/src/Services/socket-general.js
> thisyahlen/hotfix: wrong restriction message for austria

- packages/core/src/Services/socket-general.js
Reverts binary-com/deriv-app#8006
> Revert "thisyahlen/hotfix: wrong restriction message for austria"

- packages/core/src/Stores/client-store.js
- packages/core/src/_common/base/socket_cache.js
Reverts binary-com/deriv-app#7926
> Revert "Jim/88166/delay in real account creation flow after clicking add account button in the account creation popup"

- packages/account/src/Sections/Profile/PersonalDetails/personal-details.jsx
- packages/core/src/Stores/client-store.js
Reverts binary-com/deriv-app#8002
> Revert "fix: :bug: fetches latest personal details every time intead of cache…"

- packages/bot-web-ui/jest.config.js
- packages/bot-web-ui/src/components/__tests__/toolbar.spec.tsx
- packages/bot-web-ui/src/components/dashboard/bot-builder/toolbar/__tests__/toolbar.spec.tsx
- packages/bot-web-ui/src/components/dashboard/bot-builder/toolbar/toolbar.tsx
-   feat: setup config file jest tests for bot-web-ui package
-   [x] Script configuration
-   [ ] …
> Maryia/feat: setup config file jest tests for bot-web-ui package

- packages/account/src/Configs/trading-assessment-config.js
> fix: console error in existing mf user

- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/SettingsModal/settings-language.jsx
- packages/core/src/sass/app/_common/components/settings-language.scss
> thisyahlen/fix: language switcher css

- packages/core/src/App/Containers/SetResidenceModal/set-residence-form.jsx
> fix: placeholder signup modal typo

- packages/core/src/App/Containers/AccountSignupModal/account-signup-modal.jsx
> likhith/fix: :bug: button not disabled for account signup

- packages/components/src/components/checkbox/checkbox.tsx
-  fixed Checkbox to set correct checked value
> maryia/92446/fix: allow equals checkbox to set correct checked value

- packages/account/src/Styles/account.scss
> Suisin/chore: fixed text alignment issue in personal detail page

- packages/core/src/App/Containers/Layout/trading-hub-footer.jsx
> thisyahlen/fix: z-index for dark theme popover

- packages/trader/src/Stores/Modules/Trading/trade-store.js
> chore: change reaction and call validateAllProperties

- packages/bot-web-ui/src/components/dashboard/dashboard.scss
-   Fix the scrolling issue for the blocks menu accordion
-   [ ] …
> fix: fix scrolling issue for blocks menu accordion

- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/index.scss
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/recent.tsx
-   Fix load-bot-preview field text alignment issue
> fix: load-bot-preview field text alignment issue

- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/index.scss
-   Fix load-bot-preview cursor issue
> fix: load-bot-preview cursor style issue

- packages/trader/src/Stores/Modules/Trading/trade-store.js
Reverts binary-com/deriv-app#8165
> Revert "chore: change reaction and call validateAllProperties"

- .github/workflows/generate_app_id.yml
> Update qa_server url

- packages/core/src/App/Containers/AccountSignupModal/validate-signup-fields.jsx
> fix: evgeniy/92716/overlapping error msg when selecting citizenship

- packages/shared/src/utils/cfd/cfd.ts
> fix: sub_account_type type

- packages/core/src/Stores/client-store.js
- packages/shared/src/utils/helpers/duration.ts
- packages/shared/src/utils/storage/storage.ts
> Fix broken tik issue 

- packages/core/src/Stores/notification-store.js
-   add check for null and undefined in Object.keys()
> Sergei / 80947 / Cannot convert undefined or null to object

- packages/bot-web-ui/src/components/dashboard/bot-builder/bot-builder.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard.tsx
> fix: react-joy ride alignment on first load in bot-builder page

- packages/components/src/components/tabs/tabs.tsx
- packages/p2p/src/components/app-content.jsx
> fix: fix notification count on p2p orders tab

- packages/bot-skeleton/src/scratch/hooks/workspace_svg.js
> thisyahlen/fix: getHeightWidthError issue

- packages/components/src/components/data-list/data-list-row.jsx
- Delete timer inside `useEffect` as it wasn't cleaned even after implementing `clearTimeout`
> Kate/93656/Track JS Minified React error #188

- packages/core/src/sass/app/_common/components/platform-dropdown.scss
> thisyahlen/fix: design on CTA platform dropdown

- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
- packages/core/src/App/Containers/SetAccountCurrencyModal/set-currency-modal.jsx
> thisyahlen/fix: no currency popup for mf

- packages/appstore/src/components/main-title-bar/index.tsx
- packages/appstore/src/constants/tour-steps-config-new.tsx
- packages/appstore/src/constants/trading-hub-content.tsx
- packages/cashier/src/pages/account-transfer/account-transfer-no-account/__tests__/account-transfer-no-account.spec.tsx
- packages/cashier/src/pages/account-transfer/account-transfer-no-account/account-transfer-no-account.tsx
- packages/core/src/App/Components/Layout/Header/platform-dropdown.jsx
- packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
- packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
- packages/core/src/App/Containers/Layout/header/trading-hub-header.jsx
> thisyahlen/fix: Trader's Hub text

- packages/bot-web-ui/src/app/app-content.jsx
- packages/bot-web-ui/src/app/app.tsx
- packages/bot-web-ui/src/app/dbot-providers.tsx
- packages/bot-web-ui/src/stores/root-store.ts
- packages/bot-web-ui/src/stores/useDBotStore.tsx
- packages/bot-web-ui/src/types/index.ts
- packages/bot-web-ui/src/types/root-stores.types.ts
-   Included temporary TRootStores type to include gtm and portfolio property in TCoreStores 
-   Refactor app-content.jsx to have combined stores for not to break the current structure
-   [ ] Script …
> refactor: RootSotre for gradually refactoring all dbot stores

- packages/hooks/src/useTotalAssetCurrency.ts
> fix: Total asset should not be shown when account has no currency created

- packages/bot-web-ui/src/stores/app-store.js
- packages/bot-web-ui/src/stores/root-store.ts
- packages/bot-web-ui/src/stores/summary-card-store.js
-   refactor: app store & summary card store
> refactor: AppStore, SummaryCardStore

- packages/bot-web-ui/src/stores/journal-store.js
- packages/bot-web-ui/src/stores/root-store.ts
- packages/bot-web-ui/src/stores/run-panel-store.js
> refactor: JournalStore, RunPanelStore

- packages/bot-web-ui/src/stores/root-store.ts
- packages/bot-web-ui/src/stores/toolbox-store.js
- packages/bot-web-ui/src/stores/transactions-store.js
-   refactor: TransactionStore, ToolboxStore
> refactor: TransactionStore, ToolboxStore

- packages/bot-web-ui/src/stores/root-store.ts
- packages/bot-web-ui/src/stores/route-prompt-dialog-store.js
- packages/bot-web-ui/src/stores/self-exclusion-store.js
-   refactor: RoutePromptDialogStore, SelfExclusionStore
-   [ ] …
> refactor: RoutePromptDialogStore, SelfExclusionStore

- packages/bot-web-ui/src/stores/dashboard-store.ts
- packages/bot-web-ui/src/stores/data-collection-store.js
- packages/bot-web-ui/src/stores/root-store.ts
-   refactor: DashboardStore, DataCollectionStore
> refactor: DashboardStore, DataCollectionStore

- packages/core/src/Stores/contract-replay-store.js
> Akmal / fix: tick history logic on language change

- packages/bot-web-ui/src/stores/root-store.ts
- packages/bot-web-ui/src/stores/useDBotStore.tsx
-   remove core properties from RootStore
> refactor: remove core properties from RootStore

- packages/core/src/App/Containers/Layout/header/trading-hub-header.jsx
- packages/core/src/sass/app/_common/layout/trading-hub-header.scss
> thisyahlen/fix: deriv logo in traders hub

- packages/components/src/components/badge/__tests__/badge.spec.tsx
- packages/components/src/components/badge/badge.scss
- packages/components/src/components/badge/badge.tsx
- packages/components/src/components/badge/index.ts
- packages/components/src/index.js
-   add badge component
-   add tests
```
<Badge background_color='blue' type='contained'>
Demo
</Badge>
```
1. **_background_color_** = 'blue' | 'orange' | 'red' | 'gray' (background for *contained* badge type)
2. **_className_**
3. **_custom_color_** (custom color to override the default one)
4. **_weight_** = bold' | 'normal'
5. **_rounded_corners_** = 2 | 4 (number of rounded corners)
6. **_size_** = 'medium' | 'large' (contains the height and font size), automatic switching from desktop to mobile
7. **_type_** = 'contained' | 'bordered'
-   [ ] If components from external libraries are being used to define the flow, e.g. …
> george / WALL-520 / create badge component

- packages/core/src/Stores/client-store.js
> FarhanNurzi/ is_p2p_disabled cookie doesn't get removed when user logs out

- packages/core/src/App/Components/Elements/LiveChat/use-livechat.ts
> Sergei / Livechat reinit without page refresh when user changes theme or language

- packages/core/build/config.js
- packages/core/globals.d.ts
- packages/core/package.json
- packages/core/src/App/Constants/platform-config.js
- packages/core/src/App/Constants/routes-config.js
- packages/new-bot-web-ui/package.json
- packages/new-bot-web-ui/src/app/app.js
- packages/new-bot-web-ui/src/components/blocks/blocks.scss
- packages/new-bot-web-ui/src/components/blocks/blocks.tsx
- packages/new-bot-web-ui/src/components/blocks/index.ts
- packages/new-bot-web-ui/src/components/dashboard/bot-builder/bot-builder.tsx
- packages/new-bot-web-ui/src/components/index.js
- packages/new-bot-web-ui/src/stores/app-store.js
- packages/new-bot-web-ui/webpack.config.js
- packages/shared/brand.config.json
- packages/shared/src/utils/brand/brand.ts
- packages/shared/src/utils/platform/platform.ts
- packages/shared/src/utils/routes/routes.ts
- packages/translations/scripts/extract-string.js
-   feat: setup routing new bot builder, market dropdown
-   [ ] …
> feat: setup routing new bot builder, market dropdown

- packages/cashier/src/components/cashier-onboarding/cashier-onboarding.scss
> george / rm94220 /  loader position in cashier onboarding

- packages/core/src/Stores/common-store.js
> george / rm94252 / smartchart constant loading after switching the language

- packages/core/src/App/Components/Elements/LiveChat/use-livechat.ts
Reverts binary-com/deriv-app#8447
> Revert "Sergei / Livechat reinit without page refresh when user changes theme or language"

- packages/core/src/App/Components/Elements/LiveChat/use-livechat.ts
- packages/core/src/App/Containers/Routes/routes.jsx
- packages/shared/src/utils/url/url.ts
Reverts binary-com/deriv-app#7619
> Revert "Sergei / 67781 / live chat color"

- packages/bot-web-ui/src/components/chart/chart.scss
- packages/bot-web-ui/src/stores/save-modal-store.ts
-   fix: unable to see chart setting modal on any devices
-   [ ] …
> Maryia/94162/fix: unable to see chart setting modal on any devices

- packages/components/src/components/data-list/data-list.tsx
- packages/core/src/App/Containers/Modals/trading-assessment-existing-user.jsx
> Niloofar Sadeghi / Bug - Getting "Sorry for interruption" error message while trying to open P2P page on responsive

- packages/trader/src/Modules/Trading/Components/Form/Purchase/contract-info.jsx
> likhith/fix: :art: resolved incorrect CSS style

- packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.scss
> Niloofar Sadeghi / Mobile/Responsive: Alignment issue in cashier-->transfer page

- packages/core/src/App/Components/Elements/Errors/error-component.jsx
> chore: fix error message for unavailable platform

- packages/bot-web-ui/src/components/dashboard/dashboard.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy.scss
-   fix: there is collapsable menu present on quick strategy page
- …
> Maryia/94248/fix: there is collapsable menu present on quick strategy page

- packages/bot-web-ui/src/components/dashboard/bot-builder/toolbar/__tests__/toolbar.spec.tsx
- packages/bot-web-ui/src/components/dashboard/bot-builder/toolbar/toolbar.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/components.types.ts
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/container.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/fields.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/form.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy.types.ts
-   fix: on changing asset type, the duration and trade types dont get updated
-   update: tests for toolbar
-   [ ] …
> Maryia/94247/fix: on changing asset type, the duration and trade types dont get updated

- packages/core/src/Stores/client-store.js
-  added optional chaining to 'financial_company' related variable for preventing console errors being thrown.
-   [ ] …
> fix: :bug: adds optional chaining for landing_companies. variable

- packages/cfd/src/Containers/__tests__/cfd-password-modal.spec.js
- packages/shared/src/utils/validation/declarative-validation-rules.ts
> Amina/fix:  password validation to match BE

- packages/appstore/src/components/containers/__tests__/currency-switcher-container.spec.tsx
- packages/appstore/src/components/containers/currency-switcher-container.tsx
- packages/stores/src/mockStore.ts
- packages/stores/types.ts
> thisyahlen/chore: add test coverage for currency switcher container

- packages/p2p/src/stores/general-store.js
- Removed setAppProps as this function was removed in a previous PR and causing issues in accessing P2P
> Ameerul /Bug 94561 Unable to access P2P on staging 

- packages/trader/src/Stores/Modules/Trading/trade-store.js
> chore: fix issue when changing language

- packages/cashier/src/pages/payment-agent/payment-agent-list/payment-agent-list.tsx
- packages/cashier/src/pages/payment-agent/payment-agent-list/withdrawal-tab.tsx
- packages/cashier/src/stores/general-store.ts
- packages/cashier/src/stores/payment-agent-store.ts
> george / rm95052 / user is switched to deposit page while changing language 

- packages/appstore/src/components/main-title-bar/asset-summary.tsx
- packages/appstore/src/components/onboarding-new/static-cfd-account-manager.tsx
- packages/appstore/src/components/onboarding-new/static-trading-app-card.tsx
- packages/appstore/src/components/trade-button/trade-button.tsx
-   Add char 's' to 'Total asset' and change trade to open in Trader's hub …
> Sergei / wall-738 and wall-749 / Add char 's' to 'Total asset' and change trade to open

- .circleci/config.yml
> Use larger circleci containers for faster build

- packages/bot-web-ui/src/components/flyout/flyout.jsx
> Vinu/ fix: the position of flyout

- packages/bot-web-ui/src/stores/load-modal-store.ts
> Vinu/ fix: close the dashboard dialog when xml is uploaded

- packages/bot-web-ui/src/components/dashboard/tutorial-tab/sidebar.scss
> fix: change zindex to 1

- packages/core/src/Constants/form-error-messages.js
> Suisin/chore: remove dot from error message of empty address

- packages/core/src/App/Containers/Layout/header/trading-hub-header.jsx
- packages/core/src/sass/app/_common/layout/trading-hub-header.scss
> thisyahlen/chore: deriv icon redirect to deriv com

- packages/bot-web-ui/src/components/dashboard/dashboard-component/cards.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard-component/info-panel.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/delete-dialog.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/google-drive.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/local-footer.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard.tsx
- packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy.tsx
- packages/bot-web-ui/src/components/dashboard/tour-guide.tsx
- packages/bot-web-ui/src/components/dashboard/tour-slider.tsx
- packages/bot-web-ui/src/components/dashboard/tour-trigger-dialog.tsx
- packages/bot-web-ui/src/components/journal/journal.tsx
- packages/bot-web-ui/src/components/load-modal/load-modal.tsx
- packages/bot-web-ui/src/components/load-modal/local-footer.tsx
- packages/bot-web-ui/src/components/load-modal/local.tsx
- packages/bot-web-ui/src/components/self-exclusion/self-exclusion.jsx
- packages/bot-web-ui/src/components/summary/summary-card.tsx
- packages/bot-web-ui/src/components/summary/summary-card.types.ts
- packages/bot-web-ui/src/components/summary/summary.tsx
- packages/bot-web-ui/src/components/trade-animation/trade-animation.jsx
- packages/bot-web-ui/src/components/transactions/transaction.jsx
- packages/bot-web-ui/src/components/transactions/transactions.jsx
- packages/components/src/components/types/contract.types.ts
> Shafin/bot 188/refactor  connect removal in master

- packages/account/src/Sections/Profile/PersonalDetails/personal-details.jsx
> likhith/fix: :bug: resolved required field error

- packages/appstore/src/components/cfds-listing/cfds-listing.scss
- packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-content-wrapper.tsx
- packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal.tsx
- packages/cfd/src/sass/cfd-dashboard.scss
added scrollable content support for low resolution screens
> fix: :bug: adds scrollable content support for low res screens

- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.jsx
- packages/core/src/sass/app/_common/components/onfido-container.scss
> shahzaib / fix / poi field width overflow

- packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.jsx
- packages/core/src/sass/app/_common/components/onfido-container.scss
> fix: poi field width overflow

- packages/bot-web-ui/src/utils/journal-notifications.js
fix the imports for arrayAsMessage in  journal-notifications
> fix: fix the imports in journal-notifications

- packages/bot-web-ui/src/utils/journal-notifications.js
Fix imports of functions in journal-notifications
> Vinu/ fix: imports of functions in journal-notifications

- packages/core/src/App/Components/Elements/LiveChat/use-livechat.ts
- packages/core/src/Stores/client-store.js
- packages/shared/src/utils/storage/storage.ts
- packages/shared/src/utils/url/constants.ts
- packages/shared/src/utils/url/helpers.ts
- packages/translations/src/i18next/i18next.ts
Reverts binary-com/deriv-app#8880
> Revert "Shaheer/wall 565/language related fixes"

- packages/core/src/App/Containers/AcuityDownloadModal/acuity-download-modal.tsx
- packages/core/src/Utils/Language/__tests__/language.spec.js
- packages/translations/src/i18next/i18next.ts
> yashim/chore: disable PT

- packages/account/src/Components/leave-confirm/__tests__/leave-confirm.spec.tsx
> Fix: leave confirm tests failed

- .github/workflows/merge_and_release_to_staging.yml
> Adrienne / Fix wrong branch name in automation

- packages/appstore/src/components/cfds-listing/index.tsx
> fix: change other CFDS to other CFD platforms

- packages/cfd/src/Containers/trade-modal.tsx
> thisyahlen/fix: missing account number for deriv x modal

- packages/bot-skeleton/src/services/api/api-middleware.js
- packages/bot-web-ui/src/stores/app-store.js
- packages/bot-web-ui/src/stores/run-panel-store.js
- packages/bot-web-ui/webpack.config.js
> Vinu/ fix: datadog env for clientToken fixed

- packages/cfd/src/Containers/trade-modal.tsx
> chore: localize text

- packages/cfd/src/Helpers/constants.ts
- packages/cfd/src/Stores/Modules/CFD/cfd-store.js
> Hirad/ Fixed the issue where the user could not trade in deriv EZ

- packages/core/src/Services/socket-general.js
> Ako/  Fix custom invalid token error

- packages/cfd/src/Stores/Modules/CFD/cfd-store.js
- packages/core/src/_common/base/socket_base.js
> Hirad/ fixed the issue of deriv ez token

- packages/bot-web-ui/src/components/dashboard/dashboard-component/index.scss
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/local.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard-component/user-guide.tsx
- packages/bot-web-ui/src/components/dashboard/tutorial-tab/index.scss
- packages/components/src/components/icon/common/ic-dbot-user-guide.svg
Updated user guide button on dashboard for both light and dark theme
> Farabi/bot 359/update user guide button

- packages/cfd/src/Helpers/constants.ts
Change the metatrader url to `metatraderweb.app`
> fix: change the metatrader url

- packages/components/.eslintrc.js
- packages/components/package.json
> Ako/ add overrides attr to eslintrc to fix husky pre commit issue

- packages/components/.eslintrc.js
- packages/components/package.json
> Fix husky issue

- packages/account/src/Configs/__test__/address-details-config.spec.ts
- packages/account/src/Configs/address-details-config.ts
- packages/account/src/Sections/Security/AccountClosed/account-closed.tsx
> update feature_branch with master

- packages/components/src/components/numpad/numpad.tsx
- packages/components/src/components/numpad/step-input.tsx
> Niloofar Sadeghi / Discrepancy compared to production

- .github/workflows/merge_and_release_to_staging.yml
> ci: restore checkout step

- packages/p2p/package.json
- packages/shared/src/utils/route/route.ts
- packages/shared/src/utils/routes/routes.ts
- Changed logic for matching routes
> Ameerul /WEBREL 711 Displaying incorrect tab when switch it "transfer to client" page

- packages/bot-skeleton/src/services/api/api-middleware.js
- packages/bot-web-ui/src/stores/run-panel-store.js
> Vinu/fix: session sample rate in dbot

- packages/bot-web-ui/src/components/dashboard/bot-builder/bot-builder.tsx
- packages/bot-web-ui/src/components/dashboard/bot-builder/toolbox/toolbox.tsx
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/stop-bot-modal.tsx
Fix code smells (unused variables)
> Shafin/bot 117/feat  connect method remove code smells

- packages/account/src/Components/forms/personal-details-form.jsx
> Amina/wall-1225/fix: translation_for_hint_text

- packages/account/src/Sections/Profile/PersonalDetails/__tests__/personal-details.spec.js
> likhith/fix: :bug: fixed failing testcase

- packages/core/src/Stores/gtm-store.js
Reverts binary-com/deriv-app#9287
> Revert "Amir/Feq-235/_tfa is not defined"

- .circleci/config.yml
- packages/analytics/src/__tests__/rudderstack.spec.tsx
- packages/analytics/src/rudderstack.ts
- packages/core/src/App/Containers/Layout/app-contents.jsx
> Adrienne / fix an issue where pages are not tracked in rudderstack page view

- packages/bot-web-ui/src/components/dashboard/joyride-config.tsx
- packages/bot-web-ui/src/components/dashboard/tour-trigger-dialog.tsx
- packages/bot-web-ui/src/components/dashboard/tutorial-tab/guide-content.tsx
Added localize on missing texts
> farabi/webrel 800/fix missing translations

- packages/trader/src/sass/app/_common/components/contract-type-dialog.scss
> fix: fix scrolling issue for trade types mobile

- packages/bot-skeleton/src/services/api/api-middleware.js
> Vinu/ fix: added history call to the list of request for datadog

- packages/bot-web-ui/src/components/dashboard/dashboard-component/index.scss
- packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/index.scss
> farabi/webrel 806/translation and ui issue

- packages/cfd/src/Components/__tests__/cfd-download-container.spec.js
- packages/cfd/src/Helpers/constants.ts
> Hirad/chore: updated mt5 links

- packages/p2p/src/components/buy-sell/__tests__/buy-sell.spec.jsx
- Added mocks for sendbird in `packages/p2p/src/components/buy-sell/__tests__/buy-sell.spec.jsx`
> fix: fix failing tests

- packages/api/src/APIProvider.tsx
- packages/api/src/useFetch.ts
- packages/api/src/utils.ts
- packages/appstore/src/modules/wallets/wallets.tsx
- packages/core/src/Stores/traders-hub-store.js
- packages/hooks/src/useAuthorize.ts
- packages/hooks/src/useAvailableWallets.ts
- packages/shared/src/utils/config/config.ts
- Add VRW to the config files
- Add authorization nedded calls to the fetch hook
- Remove loading from wallets page
- Hardcoded `svg` landing company for available wallets when the active_wallet is `virtual`
> bugfix: logout issue

- .github/CODEOWNERS
- packages/account/src/Sections/Security/Passwords/deriv-password.jsx
- Update Deriv-app codeowners list
> Update Deriv-app Codeowners

- packages/core/src/App/Containers/Modals/app-modals.jsx
- packages/core/src/App/Containers/Modals/mt5-notification/mt5-notification.tsx
- packages/core/src/Stores/traders-hub-store.js
- packages/stores/src/mockStore.ts
- packages/stores/types.ts
Notice the modal is being cut off half way in some languages , unable to see the OK button. 
> Hamza/hotfix: overflowing instruction in non-english language

- packages/trader/src/Stores/Modules/Trading/trade-store.js
- Removed extra function call `openPositionsDrawer` for mobile
> Kate / OPT-322 / [Mobile] Delete pop-up when the contract starts for Accumulators and Multiplayers

- packages/components/src/components/dropdown/dropdown.scss
- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Duration/advanced-duration.jsx
- packages/trader/src/Modules/Trading/Components/Form/TradeParams/Duration/duration-mobile.jsx
- packages/trader/src/Modules/Trading/Containers/trade-params-mobile.jsx
- packages/trader/src/sass/app/modules/trading.scss
- Add Expiry date for contracts with possible duration > 1 day (not only for Vanillas)
- Change style for data-picker  and duration field according to design
> Kate / DTRA-320 / Expiry date Updates

- packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-widget.jsx
> maryia/DTRA-333/feat: Reorder trade types

- packages/cashier/src/components/switch-to-fiat-account-dialog/switch-to-fiat-account-dialog.tsx
- packages/hooks/src/__tests__/useFiatAccountList.spec.tsx
- packages/hooks/src/useFiatAccountList.ts
fixing issue where user was not able to access cashier when accessing cashier after switching to non eu 
> Nada/prodqa 1263/cashier issue

- packages/appstore/src/components/multi-action-button-group/__test__/multi-action-button-group.spec.tsx
> chore: added test case for multi action button group

- packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.scss
> fix: WEBREL-1064/ transfer modal paddings issue

- packages/cashier/src/containers/cashier/cashier.tsx
- Added tab_index to array dependency to check if tab_index is 0 and p2p is not enabled, then route to deposit
> Ameerul /PRODQA 1240 Cashier is blank when client is in P2P cashier and switching from Fiat to Crypto

- packages/account/src/Components/poa-address-mismatch-hint-box/__test__/poa-address-mismatch-hint-box.spec.tsx
Created test case for Poa Address Mismatch
> chore: test case for Poa Address Mismatch Hint Box

- packages/stores/src/mockStore.ts
- packages/stores/types.ts
- packages/trader/src/Modules/Trading/Containers/__tests__/allow-equals.spec.jsx
- packages/trader/src/Modules/Trading/Containers/__tests__/contract-type.spec.jsx
- packages/trader/src/Modules/Trading/Containers/__tests__/radio-group-options-modal.spec.jsx
- packages/trader/src/Modules/Trading/Containers/__tests__/toast-popup.spec.jsx
- Added unit tests for s`rc/Modules/Trading/Containers/toast-popup.jsx`, `allow-equals.jsx`, `contract-type.jsx` and `radio-group-options-modal.jsx` file
> Kate / WEBREL-35 / Tests for Trading/Containers files in Trader package

- packages/appstore/src/components/wallet-transfer/wallet-transfer.tsx
- packages/appstore/src/types/common.types.ts
> fix: type, sonarcloud issue

- packages/bot-web-ui/src/stores/data-collection-store.js
- Update the endpoint for data collection (requested from BI team)
- N/A
> yashiim/fix: updated bi data collection endpoint

- packages/cashier/src/containers/cashier/cashier.tsx
fixed issue with routing to deposit tab on refreshing from any tab in cashier.
> fix: issue with routing to deposit page on any tab selection in cashier

- packages/trader/src/Stores/Modules/Trading/Helpers/proposal.js
> Maryia/Kate/webrel-1084/hotfix: limit order

- .github/workflows/push_and_pull_crowdin_translations.yml
Reverts binary-com/deriv-app#9661
> Revert "Prince/ updated slack webhook URL"

- packages/appstore/src/components/wallet-cards-carousel/cards-slider-swiper.tsx
- Add containScroll option to carousel
- Change data to data?.length in array dependency to prevent blinking of cards
> Sergei / just fix wallet carousel for responsive

- packages/bot-web-ui/src/components/dashboard/tutorial-tab/guide-content.tsx
> Prince/ translation workflow trigger

- packages/bot-web-ui/src/components/dashboard/tutorial-tab/guide-content.tsx
Reverts binary-com/deriv-app#9684
> Revert "Prince/ translation workflow trigger"

- packages/trader/src/App/Containers/ProgressSliderStream/__tests__/progress-slider-stream.spec.jsx
> Kate / WEBREL-51 / Test coverage: ProgressSliderStream in Trader package

- packages/appstore/src/components/cfds-listing/__tests__/index.spec.tsx
- packages/stores/src/mockStore.ts
- packages/stores/types.ts
> fix: duplicate_types
