deriv-com/deriv-app

src/sass/app/_common/components/range-slider.scss
MS Edge's 'range' input has a known issue where the thumb's height is limited to the track's height, which makes the thumb partially disappear. A workaround was implemented here until the issue is fixed in the new Chromium-based Edge (according to [this](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/20882987/))
=> khalid/MS Edge range thumb 

src/javascript/app/Constants/contract.js, src/javascript/app/Modules/Reports/Containers/profit-table.jsx, src/javascript/app/Modules/Reports/Containers/statement.jsx, src/javascript/app/Modules/Reports/Helpers/market-underyling.js
+ Refactored contract support checks to look for supported contracts
and default to "unsupported"
=> + Added support for legacy contracts

packages/core/src/App/Containers/WelcomeModal/welcome-modal.jsx, packages/core/src/Stores/client-store.js, packages/core/src/Stores/ui-store.js
**Changelog**
- fix: view welcome modal only once upon login or refresh by setting viewed `boolean` in `localStorage`.
=> zaki / fix_constant_welcome_modal

packages/components/src/components/vertical-tab/vertical-tab.jsx, packages/core/src/Stores/client-store.js
**Changelog**
- fix: `VerticalTabl` `PropType` warning for `label`
- fix: hide welcome modal if **MT5** is not allowed
=> zaki / no_welcome_modal_if_no_mt5

packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.jsx
**Changelog**
- fix: remove empty properties from `setSettings` if tax required fields are not defined.
- fix:  remove validation requirement for `states_list` fetched from `API`
=> zaki / fix_mx_poa

packages/trader/src/Modules/MT5/Components/mt5-account-card.jsx
**Changelog**
- fix: missing currency symbol for MT5 Account cards
=> zaki / mt5_card_currency_fix

packages/account/src/Sections/Security/SelfExclusion/self-exclusion.jsx
Accept null value and allow CR clients to save self-exclusion values
=> Matin/Improvement: Accept null self-exclusion values for CR clients only

packages/bot-web-ui/src/utils/journal-notifications.js
For example, In case of a division by zero operation inside `Notify` block, check for NaN and show `Tried to perform an invalid operation` error in Journal with a `Go to block` button which takes you to the block that caused the error.
=> Nijil/Handle NaN notification in DBot journal

packages/core/src/Modules/Cashier/Containers/cashier.jsx, packages/core/src/Stores/Modules/Cashier/cashier-store.js
* Hide cashier Transfer tab for IOM clients based on `im` residence
* Hidden tab before and after creating real money account
=> Matin/Fix: Hide cashier Transfer tab for IOM clients

packages/account/src/Sections/Security/SelfExclusion/self-exclusion.jsx, packages/account/src/Styles/account.scss
* Datepicker bottom alignment on tablet and mobile
* 1 column to display fields on tablet and mobile
=> Matin/Fix: Date field in self exclusion is not hidden on small screens

packages/components/src/components/data-list/data-list.jsx
- Adding back `TransitionGroup` because `onEntered` event wasn't fired on it's `CSSTransition` children
=> Bala/add back transition group in data-list

packages/core/src/Modules/Cashier/Components/Form/account-transfer-form.jsx, packages/core/src/Stores/Modules/Cashier/cashier-store.js
* Await to set `transfer from & to` values and proceed with setting `transfer limits`
* Set amount initial value to undefined instead of `account_transfer_amount ` to make it an uncontrollable value
=> Matin/Fix: display transfer amount hint on page load

packages/cashier/src/Components/Form/payment-agent-withdraw-form.jsx
- PA radios should be automatically selected by choosing values from dropdown or filling the input field.
- Mobile version should not show `empty option` on dropdown just like desktop version. It also leads to a console error.
Note. Desktop works since Radio and dropdown sit on the same line hence propagating the click from dropdown to Radio. I've added the correct logic for both.
=> salar / Fix PA radio to be auto selected

packages/shared/src/utils/shortcode/shortcode.js
**Changelog**
- fix: add checks for multiplier in `isForwardStarting` check as sell transaction returns `purchase_time` value causing false positive
=> zaki / fix_step_rng_multiup|down_sell

packages/account/src/Configs/personal-details-config.js, packages/components/src/components/dialog/dialog.jsx, packages/components/src/components/text/text.jsx
This PR fixes MT5 account creation issues
* When `<Localize />` is passed to `Dialog` component it gets wrapped up with `div` since `<Localize />` is of type `object` 
* Blank page appears due to an error of `Cannot read property 'text' of undefined` in `personal-details-config`
* style in `Text` component gets always overwritten since there is no an `else` block.
=> Abdalla/Fix: MT5 Account Creation error

packages/core/src/sass/app/modules/account-types.scss
**Changelog**
- fix: remove whitespace for account types in mobile
=> zaki / fix_account_types_box_mobile_spacing

packages/account/src/Components/api-token/api-token-table.jsx
Changing the prop name "token" to "text_copy" resolved the issue.
=> hubert/ wrongly declared prop in api-token-table

packages/p2p/src/components/page-return/page-return.scss
- removed extra height from button which shifted it by making the line-height equal to the height of the inline svg element
=> Kseniya/DP2P - Back arrow icon on the order details page is not vertically centered

packages/dashboard/package-lock.json, packages/dashboard/package.json
```diff <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>versions must be exact semver values</pre>
</body>
</html> ```
=> Bump @deriv/api-types from 1.0.24 to 1.0.36

packages/shared/src/utils/shortcode/shortcode.js
Fix: wrongly detected forward starting contracts.
Forward starting contracts have f character at the end of their start_time extracted from shortcode
=> Matin/Fix: wrongly detected forward starting contracts

packages/cashier/src/Components/usdt-side-note.jsx
Added the name of a specific wallet that is available for withdrawal into the round brackets at the end of the side note title: changed ’About Tether’ to ‘About Tether (Ethereum)’ for Tether eUSDT and to ‘About Tether (Omni)’ for Tether USDT.
=> Maryia/Added name of wallet for withdrawal to 'About Tether' note title

packages/trader/src/Stores/Modules/Trading/Helpers/active-symbols.js
-   Defining the country by the client's country of residence received in get_settings WS response in showMxMltUnavailableError()
-   [ ] Style …
=> Maryia/Defining the country by the client's country of residence in showMxMltUnavailableError()

.circleci/config.yml
circleci test time increased to 30 minutes to prevent circleci failure.
since we need the testCoverage for sonarcloud the test time has increased and in some cases it throws error when ci is running.
As you can see in [this](https://circleci.com/docs/2.0/configuration-reference/) documentation (search for `no_output_timeout` in it) with the added option we can increase task time. 
-   [ ] New …
=> Ako/ increase test time to prevent ci failure

packages/account/src/Configs/address-details-config.js, packages/account/src/Sections/Profile/PersonalDetails/personal-details.jsx, packages/shared/src/utils/validation/regex-validation.js
-   Fix for non-Jersey postcode regex
=> Maryia/Fix for non-Jersey postcode regex

packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_multiplier.js, packages/bot-web-ui/src/app/app.jsx, packages/bot-web-ui/src/stores/app-store.js, packages/cashier/src/_common/utility.js, packages/core/src/_common/utility.js, packages/shared/src/utils/digital-options/digital-options.js, packages/shared/src/utils/location/location.js
This is to add another condition to show Digital Options banner to EU clients with only a VRTC account.
=> salar / Hotfix/multiplier eu

packages/cashier/src/Components/Form/payment-agent-deposit.jsx
-   `value` prop in SelectNative was receiving `0` as string making the placeholder remain at the top even without any selection.
-   [ ] Style …
=> Nijil/Pass correct value to SelectNative value prop from PA dropdown

packages/cashier/src/Stores/__tests__/verification-store.spec.js
=> george / add tests for verification_store in cashier package

packages/cashier/src/Stores/__tests__/error-store.spec.js
=> george / add tests for error_store in cashier package

packages/account/src/Components/reset-trading-password-modal/reset-trading-password-modal.jsx, packages/cfd/src/Containers/cfd-reset-password-modal.tsx, packages/cfd/src/sass/cfd.scss
-   Fix infinite re-rendering TradingPasswordModal component
-   [ ] …
=> Mahdiyeh/ Fix: rerendering the TradingPasswordModal component

.github/workflows/generate_app_id.yml
-   Bump vercel preview url action to v1.0.4
=> Bump vercel preview url action to v1.0.4

.circleci/config.yml
-   Create CACHE_KEY based on package.json
=> Mahdiyeh/fix: create CACHE_KEY based on package.json in circleci

.eslintrc.js, packages/cashier/build/webpack.config.js
I changed two of our eslint errors to warning for now 
- import/no-extraneous-dependencies
- global-require
Also two problem in the webpack config of cashier workspace has been solved
-   [x] Script configuration
-   [ ] …
=> Ako/ Improve eslint config

.circleci/config.yml, .github/workflows/generate_and_push_deriv_api_types.md, .github/workflows/push_and_pull_crowdin_translations.md
DO NOT MERGE
- Publish website to Cloudflare pages: [cf-pages-app.deriv.com](https://cf-pages-app.deriv.com/) and [staging.cf-pages-app.deriv.com](https://staging.cf-pages-app.deriv.com)
=> Publish to Cloudflare (on push master, on tag production)

packages/components/src/components/data-list/data-list-row.jsx, packages/reports/src/Components/placeholder-component.jsx
-   fixed CompositeCalendarMobile loading in statements by eliminating DataListRow's infinite update
-   additionally: eliminated some console warnings encountered
-   [ ] …
=> Maryia/fix: CompositeCalendarMobile loading in Statements

packages/core/src/App/Containers/Layout/header/default-header.jsx
-   we should not call replaceCashierMenuOnclick() being logged out, because cashier menu is not allowed for unlogged users. This function replace cashier object in array in menu-store. But being logged out there is no such object
- …
=> yauheni / 65898 out of bound index mobx warning

packages/cfd/src/Containers/jurisdiction-modal.tsx
- Adding condition to check if svg account is already created 
-   
- ## When you need to add unit test
-   [ ] Dependency …
=> Amina/fix: next button enabled for svg account even after account added

packages/p2p/src/components/my-profile/my-profile-stats/my-profile-name/my-profile-name.jsx, packages/p2p/src/components/my-profile/my-profile-stats/my-profile-name/my-profile-name.scss, packages/p2p/src/components/my-profile/my-profile.scss
-   Blocked user count tooltip wasn't appearing in my profile if the user was not rated but has been blocked. Changed the logic and moved blocked-user-count out of the check for rating average
-   [ ] …
=> Blocked user count not appearing in my profile

packages/p2p/src/components/advertiser-page/advertiser-page-dropdown-menu.jsx, packages/p2p/src/components/advertiser-page/advertiser-page.jsx, packages/p2p/src/components/advertiser-page/advertiser-page.scss
- Hide block user dropdown when user views their own advertiser page
-  Fixed a UI issue where the return header is cropped out due to blocked user overlay …
=> Adrienne / Hide block user dropdown when user views their own advertiser page

packages/p2p/src/components/advertiser-page/advertiser-page.jsx, packages/p2p/src/components/error-modal/error-modal.jsx, packages/p2p/src/stores/general-store.js
-   Added error modal in advertiser page to handle any error messages when blocking the advertiser. …
=> Ameerul /Bug 77176 The Block modal keep on looping for Disable P2P user 

packages/p2p/src/components/my-ads/my-ads.scss
-   Forced the quick add modal to have opacity: 1 as when the user goes outside of p2p, then to p2p, and then to my-ads, if they click the Add button, modal does not show, but it is rendered on the dom with an opacity of 0
-   [ ] …
=> Ameerul /Bug 73568 Unable to click on +Add button under My Ads

packages/account/src/Components/account-limits/account-limits-table-cell.jsx, packages/account/src/Components/account-limits/account-limits-turnover-limit-row.jsx, packages/account/src/Components/account-limits/account-limits.jsx, packages/account/src/Components/account-limits/account-limits.scss
=> Fix: derived and forex account limits structure

packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/footer.tsx, packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/form.tsx
…reate is only displayed
-   Quick strategy--On entering 2 in Martingale strategy throwing error message, Create is only displayed instead of Create and Edit
-   [ ] …
=> MaryiaF/81969/Quick strategy--On entering 2 in Martingale strategy throwing error message, Create is only displayed instead of Create and Edit

packages/p2p/src/stores/my-ads-store.js
-   Fixed logic to show AdExceedsDailyLimitModal when user's daily limit is less than the min order set when creating an advert
-   [ ] Style …
=> Ameerul /Bug 80941 Wrong error modal when creating ads while pausing ads

packages/appstore/src/components/add-options-account/add-options-account.tsx
-   Changed text in trader's hub page for users with virtual account with ROW residence. Before: 'You need to create an Options and Multipliers account to create a CFD account.'. After: 'You need to create an Options and Multipliers account to add a CFD account.'
-   [ ] …
=> Kate/84375/Need update copy to Create new CR account

packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.jsx
- trim() was implemented in validateFields function in order to clean value (for each value from all 5 inputs) from extra spaces. 
- bug was connected only with 2 inputs (Town/City, Postal/ZIP code), but in order to make everything in same style, all of the inputs were trimmed. 
-   [ ] Translation to …
=> Kate/78088/fix: trimming POA input fields

packages/p2p/src/components/buy-sell/buy-sell-modal.jsx
-   Fixed an issue where rate change modal is shown when the advert rate is still not fetched in buy sell page when page is loaded for the first time …
=> Adrienne / fix issue where rate change modal is shown when buy sell page is loaded for the first time

packages/bot-web-ui/src/components/dashboard/dashboard-component/index.scss
-   fix: on the responsive dashboard should have 4 icons in 1 line on the big screen like iPhone 13 Pro Max
to check it we should set 428 width in the browser
-   [ ] …
=> Maryia/85246/on the responsive dashboard should have 4 icons in 1 line on the big screen like iPhone 13 Pro Max

packages/bot-skeleton/src/scratch/dbot.js, packages/bot-skeleton/src/services/api/api-base.js, packages/bot-web-ui/src/stores/app-store.js
-   Fixed summary panel flickering
=> fix: summary panel flickering

packages/core/src/App/Components/Routes/__tests__/route-with-sub-routes.spec.tsx, packages/core/src/App/Components/Routes/route-with-sub-routes.jsx
=> Niloofar Sadeghi / Refactor tests in the route-with-sub-routes.spec.tsx file (Core)

packages/core/src/App/Components/Layout/Header/__tests__/login-button.spec.tsx
=> Niloofar | Refactor tests in the login-button.spec.tsx file

packages/p2p/src/components/my-ads/create-ad-form.jsx
-   Changed call to get default_advert_description from my_ads_store to general_store
-   [ ] …
=> Ameerul /Bug 84324 Instruction details added in Profile page are not field automatically when creating an Ad

packages/trader/src/Modules/Trading/Containers/trade.jsx
Component topWidgets was covered by React.useCallback to avoid its rerendering every time, when new tick / digits was received by parent component <Trade>. Without this memoization, the bug with flashing content of symbols menu (markets)  on mobiles become visible. 
-   [ …
=> Kate/ 84780/ trade instruments are flashing after choosing Digits trade type on mobile  

packages/trader/src/Modules/Trading/Components/Form/DatePicker/trading-date-picker.jsx
Added optional chaining in getMinDuration function, because in some scenarios one variable in that function, called duration_min_max, is equal to {}, so we can't get 'min' from empty object and as a result get error. …
=> Kate/ 84150/ Cannot read properties of undefined (reading 'min')

packages/trader/src/App/Components/Elements/TogglePositions/__tests__/toggle-positions.spec.tsx, packages/trader/src/App/Components/Elements/TogglePositions/toggle-positions.jsx
=> Niloofar Sadeghi / Task - Refactor tests in the toggle-positions.spec.tsx file

packages/components/src/components/checkbox/checkbox.tsx
Delete defaultChecked property in order to make component controlled. Otherwise it caused console error
=> kate/ 86205/console errors in local host 

packages/trader/src/Modules/Contract/Components/LastDigitPrediction/digit-display.jsx
Add one more available proptype (_selected_digit: PropTypes.oneOfType([PropTypes.number, PropTypes.bool])_) for component DigitDisplay as in some cases we pass not a number, but a boolean value (below you can see a line of code from parent component):
_selected_digit={isSelectableDigitType() ? selected_digit : false}_
selected_digit is number, but if isSelectableDigitType() returns false, we pass boolean.
- …
=> Kate/86838/ add one more available proptype for component DigitDisplay

packages/account/src/Containers/account.jsx
=> Amina/fix: close_button_on_responsive

packages/core/src/Stores/client-store.js, packages/shared/src/utils/url/url.ts
Implemented query check for some specific unused query params (which were described in task): created a small ignore list (an array) and with the help of URLSearchParams and filter method query string now can be cleaned from unnecessary params.
All these manipulations were written in the end of init function in order not no delete by chance useful params , because there are extracted above.
Notes: there is a function filterUrlQuery, which can do the opposite action - it takes a string with parameters and an array of allowed parameters and returns a new filtered string. Unfortunately, it can't be used in this case as we don't know which params are allowed, but we do know, which are unnecessary. 
-   [ ] …
=> Kate/80001/Remove unused query params from the URL on initialize 

packages/cashier/src/components/cashier-onboarding/cashier-onboarding.jsx
=> Rostislav / 86373 / Bug fix for side note on cashier page going missing once we navigate to different tabs like Withdrawal, Payments agents

packages/p2p/src/stores/general-store.js
-   Removed SetTimeout as there is a 24.8 day limit for it, so I checked if the date is after instead to set if the user is temp barred to null …
=> Ameerul /Bug 86546 P2P clients (Not POI verified clients) are not temp. banned when we block temporary until 14th of next month or any further dates. 

packages/core/src/Stores/client-store.js
- On new user sign up and language selection, if a currently unsupported language(country name) is selected, language will be set to english by default.
- Appends the language code 'en' instead of the erroneous 'll' wherever applicable. eg: smarttrader.deriv.com/**en**/trading.html instead of smarttrader.deriv.com/**ll**/trading.html 
-   [x] Ensure the language is set to english(en) by default when a new user selects an …
=> fix: :bug: safely pulls lang from query params, defaults to english

packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
=> thisyahlen/fix: Unable to add CR fiat account

packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx, packages/core/src/Stores/client-store.js
=> Sergei / 88771 / Australian VRTC accounts are not able to create real account

packages/p2p/src/stores/my-ads-store.js
-   ...pop up modal for error thrown for activating ad from my ads table is empty
-   [ ] …
=> fix: popup empty for error thrown when activating ad from table

packages/trader/src/Modules/Trading/Containers/radio-group-options-modal.jsx
-   To fix: RadioGroupOptionsModal for Multiplier options to display for all languages, not only EN …
=> maryia/92212/fix: RadioGroupOptionsModal for Multiplier options in all languages

packages/cfd/src/Containers/cfd-reset-password-modal.tsx, packages/cfd/src/Containers/props.types.ts, packages/core/src/Stores/client-store.js
=> Amina/fix: error in investor password

packages/cashier/src/containers/cashier/cashier.tsx, packages/cashier/src/stores/__tests__/general-store.spec.ts, packages/cashier/src/stores/general-store.ts
-   Used new p2p notifications hook and deleted old code for getting unseen notifications
-   [ ] …
=> Ameerul /Bug 93397 Notification_counter_not_updated_correctly

packages/bot-skeleton/src/scratch/hooks/workspace_svg.js, packages/core/src/App/Containers/RealAccountSignup/account-wizard.jsx, packages/core/src/Stores/Modules/Trading/Helpers/currency.js, packages/indicators/src/indicators/relative-strength-index.js, packages/indicators/src/utils/math.js, packages/trader/src/Stores/Modules/Trading/Helpers/currency.js
=> thisyahlen/fix: Reduce of empty array with no initial value

packages/stores/src/mockStore.ts
=> fix: codecov_fix

packages/core/build/constants.js, packages/core/src/Utils/Datadog/index.ts
Use release tag version for datadog version tag
=> Ako/ use circleci CIRCLE_TAG as version in datadog

packages/core/src/App/app.jsx
=> Farzin/94405/Deriv P2P tab is not loading for first time login in mobile

packages/p2p/src/components/modal-manager/modals/email-link-verified-modal/email-link-verified-modal.jsx
-   Passed should_hide_all_modals: true to hideModal when clicking Confirm in the modal to make sure this modal will no longer show after clicking confirm …
=> Ameerul /Bug P2PS-598 Confirmation popup showing 2 times in DP2P

packages/p2p/src/components/order-details/order-details-footer.jsx
-   ... Disabled popup buttons until page is completely rendered.
- …
=> fix: disabled buttons until chat url is updated

packages/core/src/App/Containers/app-notification-messages.jsx, packages/core/src/Stores/Helpers/client-notifications.js, packages/core/src/Stores/notification-store.js, packages/stores/src/mockStore.ts, packages/stores/types.ts
=> feat: create success toast message for wallets

packages/p2p/src/components/my-profile/my-profile.jsx
- onUnmounting my profile page, setShouldShowAddPaymentMethodForm I passed in false as it was still true when navigating to other pages.
=> Ameerul /P2PS-868 Add payment method modal is showing in buy/sell page

.circleci/config.yml
- Change resource_class to large for jobs possibly running on user CircleCI
Some users report issues running builds after they set up CircleCI on their forks:
```Resource class docker for xlarge is not available for your project, or is not a valid resource class. This message will often appear if the pricing plan for this project does not support docker use.```
While it seems a configuration issue (not all users impacted, some had the issue and it's fixed now), better to use `resource_class: large` so we won't have this issue anymore. We can still add again `xlarge` later.
According to [CircleCI resource classes](https://circleci.com/product/features/resource-classes/), the `large` resource class should be available to everyone and faster than what was the default 1 month ago (it was …
=> Change  resource_class to large

.eslintrc.js, .lintstagedrc.json, package.json
- Added override config for the proptypes on ts
- Set the Max worker for jest to 6
- Build accounts package before the rest to fix the build problem on CI
=> Ako / FEQ 400/ Fix ci failings

packages/account/src/Sections/Security/AccountClosed/account-closed.tsx
**steps to reproduce:**
1- login to an account and from profile setting select close account 
2- select reasons and click on close
3- bypass the warning
**expected behaviour:** closing account message should shows up
**current behaviour:** no message shows up
Fixed this issue here!
=> Niloofar Sadeghi / Fixed close account message doesn't show up issue

README.md
=> Ako/ Add coveralls badge

.github/workflows/push_and_pull_crowdin_translations.yml
Translation team wants to standardize all notification for translation request and thus we 
are sending deriv-app translation requests to #announce_translation_request channel on slack
=> Prince/ updated slack webhook URL

packages/cashier/src/pages/account-transfer/account-transfer.tsx, packages/cashier/src/pages/withdrawal/withdrawal.tsx
=> Farzin/WEBREL-1103/Not displaying `Recent Transactions` table on clicking `view all` button

packages/api/src/hooks/index.ts, packages/api/src/hooks/useTradingPlatformAccounts.ts, packages/api/types.ts
=> thisyahlen/chore: add useTradingPlatformAccounts to deriv api package

packages/cashier/src/containers/cashier/cashier.tsx, packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-side-notes/deposit-crypto-side-note-try-fiat-onramp.tsx, packages/cashier/src/pages/withdrawal/withdrawal.tsx, packages/cashier/src/stores/general-store.ts, packages/cashier/src/stores/withdraw-store.ts, packages/components/src/components/vertical-tab/vertical-tab.tsx
=> fix(cashier): :bug: fix fiat withdrawal issue on mobile

packages/core/src/Stores/pushwoosh-store.js
Just added optional chaining in order to fix the newly introduced push-woosh issue
=> Ako/ fix `Cannot read properties of null (reading 'Login ID')` on PushWoosh 

packages/bot-web-ui/src/components/contract-result-overlay/contract-result-overlay.spec.tsx
- Added test case for contract result overlay
- Testing for contract result overlay component to be rendered
- Testing if contract is won or loss based on profit value
=> Farabi/bot 533/contract result overlay test case

packages/appstore/src/components/onboarding-new/__tests__/static-dashboard.spec.tsx, packages/appstore/src/components/onboarding-new/static-dashboard.tsx
=> Arshad/ WALL-833/ show correct platform on trader's hub onboarding

packages/appstore/src/components/account-transfer-modal/__tests__/account-transfer-modal.spec.tsx, packages/appstore/src/components/account-transfer-modal/account-transfer-modal.tsx, packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.tsx
- fix active container for TH transfer
- fix insufficient balance check for transfer_from with 0 balance
- fix tests
=> george / PRODQA-1316 / Transfer from Tradershub validation

packages/cfd/src/Helpers/compare-accounts-config.ts
Baskets, Commodities, Derived FX and Forex micro are  not offering in MT5 Swap Free account.Hence Derived FX should be disabled and Forex:standard/micro needs to be updated in Real.
=> Hamza/Hotfix: regression bug regarding market offerings

packages/appstore/src/components/compare-account/compare-account.tsx
Compare accounts and Account Information link in CFD section is shown little bigger than the production.
=> Hamza/ hotfix: compare account text size difference

packages/api/src/hooks/index.ts, packages/api/src/hooks/useCreateMT5Account.ts, packages/api/src/hooks/useCreateOtherCFDAccount.ts, packages/api/types.ts
Create a hook to handle the account creation of all of our CFD platforms.
- useCreateOtherCFDAccount
- useCreateMT5Account
```
createMT5Account({
payload: {
account_type: 'account_type',
mainPassword: 'password',
email: 'test@test.com',
leverage: 500,
name: 'Johnny Depp',
mt5_account_type: 'account_type',
country: 'id',
},
});
```
```
createOtherCFDAccount({
payload: {
account_type: 'rael',
password: 'password',
email: 'test@test.com',
platform: 'dxtrade'
market_type: 'all',
company: '',
},
});
```
=> Hamza/chore: useCreateOtherCFDAccount and useCreateMT5Account hooks added

packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_multiplier.js, packages/bot-skeleton/src/services/tradeEngine/trade/Total.js, packages/bot-skeleton/src/services/tradeEngine/trade/index.js
- Added a function to validate TradeOptions, this can be used to shape the config and add additional settings later. 
=> Prince/  allow custom variables and function values for limit order

packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/__tests__/bot-preview.spec.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/bot-preview.tsx
One TS type change to remove TS error and test case for bot-preview.tsx component.
=> chore: test case for BotPreview

packages/account/src/Components/personal-details/__tests__/personal-details.spec.js, packages/account/src/Components/personal-details/personal-details.jsx
Removed a text statement that was part of appstore config
=> likhith/fix: :coffin: removed old text related to appstore

packages/p2p/src/components/my-ads/create-ad-form-payment-methods.jsx, packages/p2p/src/components/my-ads/edit-ad-form-payment-methods.jsx
Edit ad form payment methods throwing error when payment method is undefined issue fixed
=> fix: issue with page breaking in edit ad form payment methods

packages/bot-web-ui/src/stores/save-modal-store.ts
The strategy name is not updated under the "Your bots" section on the dashboard on saving from the bot builder page.
- Changed the sequence of code execution order. 
- Updated the bot name in the store first and then called the saving method.
=> fix: update bot name on saving bot

packages/bot-web-ui/src/components/dashboard/dbot-tours/mobile-tours/__tests__/bot-builder-tour.spec.tsx, packages/bot-web-ui/src/components/dashboard/dbot-tours/mobile-tours/__tests__/onboarding-tour.spec.tsx
Added `eslint-disable-next-line simple-import-sort/imports` to exempt the import order from ESLint's automatic sorting. This change was necessary because our project requires a specific, predefined import order, which was causing test failures on Circle CI when ESLint reordered the imports automatically.
=> Rupato/fix  eslint order

packages/bot-web-ui/src/components/dashboard/dbot-tours/mobile-tours/__tests__/bot-builder-tour.spec.tsx, packages/bot-web-ui/src/components/dashboard/dbot-tours/mobile-tours/__tests__/onboarding-tour.spec.tsx
Added` eslint-disable-next-line simple-import-sort/imports` to exempt the import order from ESLint's automatic sorting. This change was necessary because our project requires a specific, predefined import order, which was causing test failures on Circle CI when ESLint reordered the imports automatically.
=> Rupato/fix  eslint order sort

packages/core/src/App/Containers/app-notification-messages.jsx, packages/core/src/Stores/Helpers/client-notifications.js, packages/core/src/Stores/notification-store.js
User Story: As a [type of user], I want [an action] so that [a benefit/a value].
As a user I do not want to see the MT5 broker name change pop-up notification on Trader's Hub since this issue no longer happens.
CU Card: https://app.clickup.com/t/20696747/CFDS-925
=> Hamza/chore: remove the broker code mt5 notification from traders hub

packages/trader/src/Assets/Trading/Categories/__tests__/contract-type-description-video.spec.tsx, packages/trader/src/Assets/Trading/Categories/contract-type-description-video.tsx, packages/trader/src/sass/app/_common/components/contract-type-info.scss
- CSS changes
- Refactor component: remove `width` and `hight` attributes from `ContractTypeDescriptionVideo` + remove `isMobile()` (will be deprecated soon)
- Refactor test cases
=> Kate / DTRA-384 /Video improvement

packages/p2p/src/utils/chat-message.ts
- Wrapped admin message with localize as translations team were not picking up the new string for the chatbox. Should fix the translations issue 
=> Ameerul /WEBREL-1253 P2P Chatbox bot-message is not translated in any of the languages other than English

packages/p2p/src/components/modal-manager/modals/quick-add-modal/quick-add-modal.jsx
- Added missing p2p_advertiser_payment_methods prop to SellAdPaymentMethodsList 
=> Ameerul /WEBREL-1255 Created payment method is not reflected from Add payment methods model for SELL ads

packages/appstore/src/components/modals/real-wallets-upgrade/components/modal-elements/desktop-real-wallets-upgrade.tsx, packages/components/src/components/modal/modal.tsx
fix: modal component (revert to master implementation)
=> george / fix: modal component (revert to master implementation)

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
- update deriv-charts version to 1.3.5
=> maryia/WEBREL-1166/build: update deriv-charts version to 1.3.5

packages/appstore/src/components/cfds-listing/cfds-listing.scss, packages/cfd/src/Containers/mt5-trade-modal.tsx, packages/cfd/src/Containers/trade-modal.tsx
Replace the Web terminal and Windows app links from the cTrader trade modal on responsive view
=> Hamza/chore: added ctrader coming soon banner for responsive + desktop

packages/bot-web-ui/src/components/transaction-details/desktop-transaction-table.tsx, packages/bot-web-ui/src/components/transaction-details/mobile-transaction-card.tsx, packages/bot-web-ui/src/components/transaction-details/transaction-details-desktop.tsx, packages/bot-web-ui/src/components/transaction-details/transaction-details-mobile.tsx, packages/bot-web-ui/src/components/transaction-details/transaction-details.types.ts, packages/bot-web-ui/src/components/transactions/transactions.jsx, packages/bot-web-ui/src/stores/run-panel-store.js, packages/bot-web-ui/src/stores/transactions-store.js
Currently, the transaction is not stored based on the user account (for ex: demo or any real account). In this PR we are solving that issue by
- Storing the transaction by mapping it to the client's loginid
- Changing the transactions if the account is switched and only showing the transactions based on loginid
- Clearing the transactions if the reset button is clicked but only clearing the one on which platform the user is in
- Also we are enabling the account and balance column in the detailed transaction modal/pop-up
=> refactor: transaction store refactor to adjust trx by loginid

packages/trader/src/Modules/SmartChart/Components/all-markers.jsx
- Added `ctx.save()` in order to avoid situations when we entered the condition where there are no ticks and restored canvas without saving (line line 393):
```
if (!ticks.length || !barrier) {
ctx.restore();
return;
}
```
=> Kate / DTRA-371 / Lines of the candlestick, hollow and OHLC changes to dash after purchasing a contract

packages/components/src/components/input-field/input-field.tsx, packages/components/src/components/tooltip/tooltip.scss
- Changes will be applied to those components, which are importing `<InputWithCheckbox />` as there we pass a prop to `<InputField />` : `is_error_tooltip_hidden={isMobile()}`. Currently it's only `<StopLoss />` and <`TakeProfit />` from trader package (no other package should be affected)
=> Kate / OPT-328 / Responsive: tooltips for Take profit get cut off

packages/bot-skeleton/src/scratch/dbot.js, packages/bot-skeleton/src/scratch/utils/index.js
Added a fix for the Trackjs issue which was because of there was no mobile check and the Blockly used to load first and was not getting the reference resulting null as there is no trashcan on the mobile view.
=> Rupato/BOT-741/fix: for trackJS SVGGroup_ issue

packages/appstore/src/components/wallet-transfer/timer/__tests__/timer.spec.tsx, packages/appstore/src/components/wallet-transfer/timer/index.ts, packages/appstore/src/components/wallet-transfer/timer/timer.tsx
In this PR we added Counter for wallet transfer operations
=> george / WALL-1832 / timer implementation

packages/wallets/src/components/DesktopWalletsList/DesktopWalletsList.tsx, packages/wallets/src/components/WalletCard/WalletCard.tsx, packages/wallets/src/components/WalletCardIcon/WalletCardIcon.tsx
1. Added missed currency code in mapper
2. Used currency type instead of `display_code` since it doesnt have demo
3. Removed currency from wallet card since we already have it in `display_balance`
=> fix: currency icon

packages/account/src/Sections/Security/Passwords/deriv-password.jsx, packages/core/src/App/Components/Routes/language-link.tsx
This fix is going to address the issue that happens after switching the language and certain words do not translate properly by adding `await` before calling `async` changeSelectedLanguage() function.
ts of the change.
=> Matin / Fix language switch issue

packages/hooks/src/useAuthorize.ts, packages/hooks/src/useWalletsList.ts
1) `useAuthorize`
- add enabled option to only call when token exist.
2) `useWalletList`
- remove store dependencies and replace with hooks
- fix onboarding issues for DIEL clients signup.
=> Aizad/WALL-1987/Seeing loading issue during DIEL account creation

packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/cancel-deal.jsx
Deal cancellation should only be available for symbols/contracts with `cancellation_range_list` with length bigger than 0. `cancellation_range_list` comes from `contracts_for` response and comes back with empty array when deal cancellation is not be available.
=> henry/dtra-422/fix: hide deal cancellation component when cancellation is not available

.github/actions/build/action.yml, .github/workflows/release_production.yml
To Use correct rudderstack key on production release.
Use prod build script for staging release
=> Ako/ Use prod build script on staging release

packages/bot-web-ui/src/components/download/download.tsx
- Transaction download button should be disabled if bot is running
=> fix: trx dwnld btn should be disabled if bot is running

packages/api/src/APIProvider.tsx
This is to temporarily removing react query dev tools as its showing up in staging server even tho we have NODE_ENV as staging.
=> Ako/ remove react-query-devtools as it showing up in staging server

packages/p2p/src/pages/buy-sell/buy-sell-form.scss, packages/p2p/src/pages/my-profile/payment-methods/add-payment-method/add-payment-method-form.scss
- removed style `height: 4rem` which causes the field to always be that height
- fixed error not showing on the bottom of the text-area field
=> Ameerul /P2PS-1704 Overlap of buy modal when sellers instructions are too long

packages/p2p/src/components/modal-manager/modals/order-details-confirm-modal/__tests__/order-details-confirm-modal.spec.js, packages/p2p/src/components/modal-manager/modals/order-details-confirm-modal/order-details-confirm-modal.jsx, packages/p2p/src/utils/file-uploader.js
- Changed maximum upload size for POT from 2MB to 5MB to match mobile team
- Updated strings and test cases where it referenced 2MB
=> Ameerul /P2PS-1577 Change the maximum file upload size to 5 MB in POT popup for FE

package-lock.json, packages/appstore/src/components/main-title-bar/__tests__/index.spec.tsx, packages/appstore/src/components/main-title-bar/index.tsx, packages/appstore/src/components/modals/modal-manager.tsx, packages/appstore/src/components/routes/routes.tsx, packages/appstore/src/components/wallet-cards-carousel/__tests__/wallet-cards-carousel.spec.tsx, packages/core/src/App/Containers/Layout/header/dtrader-header.jsx, packages/hooks/src/__tests__/useActiveWallet.spec.tsx, packages/hooks/src/__tests__/useTransferBetweenAccounts.spec.tsx, packages/hooks/src/__tests__/useWalletTransactions.spec.tsx, packages/wallets/src/components/WalletTransactions/WalletTransactions.tsx
`useWalletList` and `useWalletMigration` are being used in different parts of the code right now, these hooks are in-turn triggering redundant `authorize` calls. Most probably because of which, chances of hitting `RateLimit` is increased. What I suggest as stop gap for now is to comment out the pieces of code utilising `useWalletList` and `useWalletMigration` because we’re never going to need it until Wallet is launched. So, commenting out these hooks won’t affect production behaviour, but we’ll have some time to investigate and find ways to handle this more elegantly.
=> Nijil/Comment out usage of useWalletList and useWalletMigration

.eslintrc.js
=> set global-require eslint rule to off

.lintstagedrc.json
This is causing lots of issues, Disabling the rule temporarily to fix in the next step.
=> Ako/ Disable import sort order auto-fix temporarily

packages/account/src/Sections/Verification/ProofOfIdentity/onfido-sdk-view-container.tsx, packages/appstore/webpack.config.js
- `onfido-sdk-ui` and `@onfido` when bundled with other dependencies has a size of 34MB, thus this dependency is bundled into a separate chunk in order to only load it during onfido verification process and reduce the size of each chunk in appstore and allow each chunk size to not exceed 25MB for Cloudflare deployment
The dependency bundle which contains onfido is downloaded on first load in Trader's Hub:
The onfido bundle is only downloaded when required during the verification process:
https://github.com/binary-com/deriv-app/assets/103016120/c0a7cdce-abc0-46c7-acda-73c279da626e
=> feat: reduced appstore bundle size due to onfido

packages/bot-web-ui/src/components/flyout/__tests__/flyout-text.spec.tsx, packages/bot-web-ui/src/components/flyout/help-contents/flyout-help-base.jsx, packages/bot-web-ui/src/components/flyout/help-contents/flyout-text.tsx
1. add test case for flyout-text.jsx
2. convert flyout-text **.jsx** to **.tsx**
=> Maryia/Bot-682/test: add test case for flyout-text.jsx

packages/bot-web-ui/src/components/journal/journal-components/__tests__/filter-dialog.spec.tsx
Test case for the journal filter dialog component
- Test if the FilterDialog component renders properly
- Test if the FilterDialog shows the filters in the UI that are passed to it
- Test if toggleFilterDialog which is to toggle the pop-up (open/close state) gets called if the user clicks outside of the pop-up
=> Shafin/bot 685/chore  filter dialog test case

__mocks__/globals.js, package-lock.json, packages/account/package.json, packages/account/src/Containers/__tests__/routes.spec.tsx, packages/account/src/Sections/Verification/ProofOfIdentity/__tests__/proof-of-identity-container.spec.js, packages/account/src/Sections/Verification/ProofOfIdentity/onfido-sdk-view-container.tsx, packages/appstore/webpack.config.js, packages/core/src/index.html, types/global.d.ts
=> adrienne / load Onfido through CDN

packages/account/src/Sections/Security/Passwords/deriv-password.jsx, packages/core/src/Stores/client-store.js
cTrader `trading_platform_available_accounts` API call is removed because it is not needed nor it is being used.
=> Matin / cTrader trading_platform_available_accounts API call is removed.

packages/trader/src/sass/app/modules/trading.scss
- Only CSS: change `margin-top` in order to put word 'Spot' on its normal place. Most probably, the original style was overwritten by the release of old PRs. As I checked, `strike-field--text` class is being used only for `<Strike />` component (for desktop).
=> Kate / DTRA-432 / [Bug] Spot alignment in Vanillas trade type

packages/api/src/hooks/index.ts, packages/api/src/hooks/useWalletMigration.ts
1. Moved useWalletMigration hook to api package
=> [42069] thisyahlen/chore: move useWalletMigration to api package

packages/core/src/public/.well-known/apple-app-site-association
- Added path to `/cashier/p2p/advertiser` so mobile team can navigate to the advertiser page for share my ads
=> Ameerul /P2PS-1726 Add the path /cashier/p2p/advertiser to apple-app-site-association file

packages/components/src/components/dropdown/dropdown.scss, packages/components/src/components/dropdown/dropdown.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/__tests__/widgets.spec.jsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/multiplier.jsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/widgets.jsx, packages/trader/src/Modules/Trading/Helpers/contract-type.tsx, packages/trader/src/sass/app/_common/mobile-widget.scss
- Add optional label NEW! to the `dropdown.tsx` and `widgets.jsx`.
- According to the card's requirements, this label should be shown for `Multipliers` with chosen `Volatility` symbol, **EXCEPT** `Vol 150 (1 sec)/ Vol 250 (2 sec)` , so I created a helper function for this purpose. As `NEW!` label is temporary, there is no need in flag from BE, it can be handled by FE powers.
- Add unit tests.
=> Kate / DTRA-438 / Add 'NEW!' label for Multipliers dropdown and widget

packages/core/src/App/Constants/routes-config.js
Bot bundle is loading on the homepage.
- changed the webpackChunkName from bot to bot-web-ui-app
=> fix: remove bot bundle chunk from landing page

packages/bot-web-ui/src/app/app.scss, packages/bot-web-ui/src/components/bot-snackbar/__tests__/bot-snackbar.spec.tsx, packages/bot-web-ui/src/components/bot-snackbar/bot-snackbar.scss, packages/bot-web-ui/src/components/bot-snackbar/bot-snackbar.tsx, packages/bot-web-ui/src/components/bot-snackbar/index.tsx, packages/bot-web-ui/src/components/dashboard/bot-builder/bot-builder.tsx
- We need to show a snack bar message if the bot is running and the user tries to update the strategy
- A generic snack bar component is added
- On the bot builder component a workspace onChange listener is added if the bot is running and there is no active listener registered yet
- The snack bar message is shown to the user if there is any change received from the listener
- The listener is removed if the bot is not running or the user moves away from the component
Screenshot:
=> chore: notify users that changes made wont affect running bot

packages/p2p/webpack.config.js
As we didn't have split chunks configuration on p2p webpack config our bundles were more than 20MB.
This will fix that issue.
=> ako/ Split p2p chunks

packages/trader/src/Stores/Modules/Trading/Constants/__tests__/validation-rules.spec.ts
- Add unit tests for `validation-rules.ts`. As this file contains functions that return `object as const`, I tested mostly fields with methods.
=> Kate / WEBREL-28 / Test coverage: validation-rules.ts in Trader package

packages/bot-web-ui/src/components/trade-animation/trade-animation.scss
fix: Snackbar **close icon** appearance on Safari doesn't match rest of the browsers:
* Do this for dark theme
* Do this for light theme
=> Maryia/BOT-795/fix: snackbar close icon appearance on Safari doesn't match rest of the browsers

packages/bot-web-ui/src/components/dashboard/dashboard.scss
1. fixed the positioning of the Next and Previous buttons  on the footer for **the onboarding tour** on responsive
2. fixed styles as per the design on responsive such as the size of the video, main background color, and size, and background color of the video container
3. fixed the positioning of the Next and Previous buttons on the footer for **bot builder guide tour** on responsive
https://github.com/binary-com/deriv-app/assets/103181650/907062be-3d87-4784-83b3-b25f6e4b5a2a
=> Maryia/BOT-80/fix: the positioning of Next and Previous buttons  on the footer for onboarding tour on responsive

packages/wallets/src/components/Base/InlineMessage/InlineMessage.scss, packages/wallets/src/components/Base/InlineMessage/InlineMessage.tsx
https://app.clickup.com/t/20696747/WALL-2125
Added variant to InlineMessage in order to support account verification badge.
Updated BEM convention a bit, centered text vertically.
Original task was about implementing component for badge, but turned out, that there is already a component which does almost exactly what is needed, so only added variant to InlineMessage.
=> WALL-2125 feat: refactored BEM a bit, added support for variants to InlineMessage [42069]

packages/core/src/Services/socket-general.js
Add the logged in user id to the error we are displaying, if no response happens after 30 seconds.
Also refactored:
- the `timer` variable to be more explicit
- moved the timeout start time to the onOpen event
=> chore: add user id to response timeout error

packages/bot-skeleton/src/scratch/hooks/flyout_base.js
The mouse pointer position remains a bit further from the block if the block is dragged out of the flout panel
- Changed the coordinate a bit to adjust the mouse pointer closer to the edge of the block
=> fix: change coordinate of mouse on flyout dragging

packages/bot-web-ui/src/components/journal/journal-components/__tests__/filters.spec.tsx
Added test case for filter component inside dashboard
=> Rupato/BOT-686/fix: added test case for filters

packages/bot-web-ui/src/components/dashboard/dashboard.tsx, packages/bot-web-ui/src/components/dashboard/dbot-tours/bot-builder-tour/bot-builder-tour-mobile.tsx
* Avoid showing "Lets build a bot" when user opens quick strategy in dbot
* Bot builder tour "Bot Builder guides" shouldn't come for the mobile version when the quick strategy is opened
https://github.com/binary-com/deriv-app/assets/103181650/40b7ceda-d478-44db-ab4a-08d52d5ea227
https://github.com/binary-com/deriv-app/assets/103181650/0cf40711-260f-4825-8cef-5934d322c75a
=> Maryia/BOT-846/fix: avoid showing "Lets build a bot" when user opens quick strategy in dbot

packages/bot-web-ui/src/components/quick-strategy/config.ts
Replaced template literal with single quotes, I think the template literal caused issue to crowding to not catch the English strings
=> refactor: quick-strategy add missing translation

packages/wallets/src/components/Base/WalletButton/WalletButton.scss
=> [Wallets] Aizad / chore: Re-add large button into WalletButton scss mapper

packages/bot-web-ui/src/components/dashboard/dashboard.tsx, packages/bot-web-ui/src/components/dashboard/dbot-tours/bot-builder-tour/bot-builder-tour-mobile.tsx
Fixed breaking deriv-bot due to change of the variable name.
It was `is_strategy_dialog_open`
the new variable name is `is_open` and is being imported from the `quick_strategy` store
=> chore: quick-strategy - fix breaking dbot

packages/wallets/src/AppContent.scss, packages/wallets/src/features/cashier/WalletCashier.scss, packages/wallets/src/features/cashier/WalletCashier.tsx, packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.scss, packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.tsx
Apply animation for hiding the wallet-name and wallet-icon when the user scrolls the wallet-cashier-content (given it is scrollable).
https://github.com/binary-com/deriv-app/assets/125039206/880f0b02-4313-4148-98f4-c87d2e55f7f2
=> [Wallet] Aum / WALL-2245 / wallet-overlay-animation-onscroll

packages/wallets/src/components/WalletsActionScreen/WalletsActionScreen.scss, packages/wallets/src/components/WalletsActionScreen/WalletsActionScreen.tsx, packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationRequest/WithdrawalVerificationRequest.scss, packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationRequest/WithdrawalVerificationRequest.tsx, packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationSent/WithdrawalVerificationSent.scss, packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationSent/WithdrawalVerificationSent.tsx
- Fix the design inconsistencies of the withdrawal verification pages for desktop and responsive
- Modify `WalletsActionScreen` to accept different format of actionText and icon as optional
- Convert pages to use wallet components and remove unused css properties
- Ensure that the design of the fiat deposit page is correct and consistent
Source: https://docs.google.com/document/d/12F8UftGIVXvYEY73saAexw7oRWVfR6yd7IJdYX24L4E/edit
=> [Wallet] Lubega / WALL-2279 / Fix UI inconsistencies for withdrawal verification pages

packages/wallets/src/features/cashier/modules/ResetBalance/ResetBalance.tsx
This PR changes the user-flow and the content of the demo reset balance according to this rule:
1. When the user opens the `Reset Balance` tab, show the reset balance screen (as shown below) and let the user click and reset their balance REGARDLESS of their current balance.
2. Once the user resets the balance, show the success screen (as shown below) with the CTA of `Transfer Funds` to redirect the user to the transfer tab.
=> [Wallet] Aum / WALL-2291 / flow-and-content-change-for-demo-reset-balance

packages/api/src/hooks/useCtraderAccountsList.ts, packages/wallets/src/components/Base/ModalWrapper/ModalWrapper.scss, packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.scss, packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx, packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx, packages/wallets/src/features/cfd/screens/CreatePassword/CreatePassword.tsx
1. Fix close icon for enter password modal
2. Throw error modal if error for ctrader
=> [wallets] thisyahlen/WALL-2300/chore: fix close icon and error handling for ctrader

packages/core/build/webpack.config.js
We have an issue on core package that it has a bundle from p2p which is 34 MB. this is to fix that issue.
=> Ako/ reduce core bundle sizes

packages/api/src/hooks/useTransactions.ts, packages/wallets/src/features/cashier/WalletCashier.scss, packages/wallets/src/features/cashier/modules/TransactionStatus/TransactionStatus.scss, packages/wallets/src/features/cashier/modules/Transactions/Transactions.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompleted/TransactionsCompleted.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPending/TransactionsPending.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsTable/TransactionsTable.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsTable/TransactionsTable.tsx
https://github.com/binary-com/deriv-app/assets/119863957/837e23eb-3e89-4664-92e8-a8e2176cd79b
=> [Wallets] Rostislav / WALL-2348 / Implement Loader on initial render, Loader on scroll and fix double scroll

packages/api/src/hooks/useCreateOtherCFDAccount.ts, packages/api/src/hooks/useCtraderAccountsList.ts, packages/api/src/hooks/useDxtradeAccountsList.ts
Removed token from other cfd accounts because we need to request new token when we click the terminal button as the lifespan of this token is too short to be added in the Account List response. 
Affected Platforms:
cTrader
Dxtrade
=> Hamza/chore: removed token from other cfd accounts

packages/appstore/src/components/cfds-listing/cfds-listing.scss, packages/appstore/src/components/modals/account-type-modal/account-type-modal.scss, packages/appstore/src/components/modals/account-type-modal/account-type-modal.tsx, packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-modal-checkbox.spec.tsx, packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-checkbox.tsx, packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-content-wrapper.tsx, packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal.tsx
A new PR [CFDS-1324](https://app.clickup.com/t/20696747/CFDS-1324) for the reverted card [CFDS-1209 / PRODQA-1335](https://app.clickup.com/t/20696747/PRODQA-1335)
- "Next" button not visible in mobile with navigation bar
- A lot of extra space when "Next" button is visible
- gap in footer between checkbox and "Next" button 
- double scrollers in tablet view causing glitchy experience
- checking for issue in desktop, tablet, and mobile, using CR and MF account
- [figma](https://www.figma.com/file/8jC3I58t0WCAyI6pGDAIVl/Release---Deriv-MT5-accounts?type=design&node-id=17000-286959&mode=design&t=SwmSXVOGgM1Y1FlU-4)
https://github.com/binary-com/deriv-app/assets/108507236/cd4fbb0b-afc3-4396-a4f1-b307d5a6047d
=> fix: jurisdiction modal next button issue

packages/wallets/src/components/Base/IconButton/IconButton.scss, packages/wallets/src/components/Base/IconButton/IconButton.tsx, packages/wallets/src/components/Base/IconButton/index.ts, packages/wallets/src/components/Base/index.ts
- Created Icon Button component
=> Aizad/WALL-2439/Created Icon Button Component

packages/wallets/src/components/Base/WalletDropdown/WalletDropdown.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsTable/TransactionsTable.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsTable/TransactionsTable.tsx
https://github.com/binary-com/deriv-app/assets/119863957/fdc0b108-4200-45e6-98f8-fcd7cd7bfce4
=> Rostislav / WALL-2344 (2) / Fix remaining issues

packages/wallets/src/features/cashier/modules/TransactionStatus/TransactionStatus.tsx, packages/wallets/src/features/cashier/modules/TransactionStatus/components/TransactionStatusSuccess/TransactionStatusSuccess.tsx
Align `TransactionStatus` font sizes with Figma and fix "No recent transactions." display.
=> [Wallets] Rostislav / WALL-2443 / Align `TransactionStatus` header font size with Figma

packages/account/src/Components/poi/status/unsupported/detail-component.tsx
- Incorrect request payload cause the document to be uploaded under wrong category. Changed Request payload to match the API
=> fix: renamed payload props for file upload

packages/bot-web-ui/src/utils/__tests__/session-storage.spec.ts
This PR covers the test case for session-storage.js
- Tested `getStoredItemsByKey()` to check if the default value is returned if the storage is empty
- Tested `getStoredItemsByUser()` to check if the default value is returned if the storage is empty
- Tested `setStoredItemsByKey()` to check if the value that is set is returned 
- Tested `setStoredItemsByKey()` to check if the set value is an invalid object then it's throwing an error
=> chore: Test case for session-storage.js

packages/wallets/src/features/cashier/modules/DepositCrypto/DepositCrypto.scss, packages/wallets/src/features/cashier/modules/TransactionStatus/TransactionStatus.scss
Fix `TransactionStatus` positioning in responsive crypto deposit
https://github.com/binary-com/deriv-app/assets/119863957/8a23afcc-4678-42b4-8c03-6d90740a6910
=> [Wallets] Rostislav / WALL-2445 / Fix `TransactionStatus` positioning in responsive crypto deposit

packages/bot-web-ui/src/utils/__tests__/multiplier.spec.ts
Test case for multiplier.js in utils folder
- Test to check if `getBuyPrice()` return the correct `buy_price` retrieving it from the `contract_store`
- Test to check if `getContractUpdateConfig()` return the correct values for `contract_update_stop_loss`, `contract_update_take_profit `, `has_contract_update_stop_loss `, `has_contract_update_take_profit ` if the `limit_order` is present
- Test to check if `getContractUpdateConfig()` return the default values for `contract_update_stop_loss`, `contract_update_take_profit `, `has_contract_update_stop_loss `, `has_contract_update_take_profit ` if the `limit_order` is empty
=> chore: Test for multiplier.js in utils

packages/wallets/.stylelintrc.js, packages/wallets/src/components/Base/Divider/Divider.scss, packages/wallets/src/components/Base/InlineMessage/InlineMessage.scss, packages/wallets/src/components/Base/Tooltip/Tooltip.scss, packages/wallets/src/components/Base/WalletAlertMessage/WalletAlertMessage.scss, packages/wallets/src/components/Base/WalletButton/WalletButton.scss, packages/wallets/src/components/Base/WalletDropdown/WalletDropdown.scss, packages/wallets/src/components/Base/WalletTextField/WalletTextField.scss, packages/wallets/src/components/SkeletonLoader/TradingAppCardLoader/TradingAppCardLoader.scss, packages/wallets/src/components/SkeletonLoader/WalletsDepositCryptoAddressLoader/WalletsDepositCryptoAddressLoader.scss, packages/wallets/src/components/TradingAccountCard/TradingAccountCard.scss, packages/wallets/src/components/WalletNoWalletFoundState/WalletNoWalletFoundState.scss, packages/wallets/src/components/WalletsAddMoreCarousel/WalletsAddMoreCarousel.scss, packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoAddress/DepositCryptoAddress.scss, packages/wallets/src/features/cashier/modules/Transactions/Transactions.scss, packages/wallets/src/features/cashier/modules/Transfer/TransferForm/TransferForm.scss, packages/wallets/src/features/cashier/modules/Transfer/TransferForm/components/TransferFormDropdown/components/TransferFormAccountCard/TransferFormAccountCard.scss, packages/wallets/src/features/cashier/modules/Transfer/TransferForm/components/TransferFormDropdown/components/TransferFormAccountSelection/TransferFormAccountSelection.scss, packages/wallets/src/features/cfd/components/ModalTradeWrapper/ModalTradeWrapper.scss, packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.scss, packages/wallets/src/styles/devices.scss
1. Add new stylelint rule to accept predefined rules ['%', 'deg', 'em', 'fr', 'ms', 'rem', 's', 'svh', 'vh', 'vw'].
2. Therefore will throw an error if px unit is used
=> thisyahlen/WALL-2465/chore: add styelint rule to accept defined units

packages/wallets/src/components/DesktopWalletsList/DesktopWalletsList.scss, packages/wallets/src/components/WalletsAccordion/WalletsAccordion.scss
- Accordion loader not showing on the first load
https://github.com/binary-com/deriv-app/assets/125247833/49806e27-bd48-4f72-8a67-06a7c02e12ac
https://github.com/binary-com/deriv-app/assets/125247833/0ffbeb4e-ba65-47eb-841f-55f4414e7d58
=> [wallets] Farhan/WALL-2470/Accordion skeleton loader not showing on the first load (Desktop)

packages/bot-web-ui/src/utils/__tests__/window-size.spec.tsx
test: test coverage for the file window-size.js
=> Maryia/BOT-768/test: test coverage for the file window-size.js

nx.json
Since the NX access token is expired it needs to be removed. 
Later on if we enable nx back we can simply commit the readonly token again.
=> Ako/ remove nx access token as its expired

packages/wallets/src/features/cashier/WalletCashier.scss, packages/wallets/src/features/cashier/modules/DepositCrypto/DepositCrypto.scss, packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoDisclaimers/DepositCryptoDisclaimers.scss
1. Added padding for the `WalletCashierContent`:
```
desktop: top=4.8rem inline=1.6rem
responsive: top=2.4rem inline=1.6rem
```
2. Translate the `DepositCryptoModule` by `-2.4rem in desktop` and `-1.2rem in responsive` to account for the padding in `WalletCashierContent` and center it to the screen.
3. Fixed the `margin-left` for disclaimer list-items and gap between title and list-items.
=> [Wallet] fix: aum/WALL-2435/fix-crypto-deposit-padding-alignment

packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.tsx
On first login, the first wallet should be expanded by default. Only applies to wallets which has linked_to trading account. 
If the wallet doesnt have linked_to trading account, the first wallet is expanded by default. 
https://app.clickup.com/t/20696747/WALL-2514
=> thisyahlen/WALL-2514/chore: on first login switch to the first wallet by default

packages/trader/src/Modules/Trading/Components/Form/TradeParams/Duration/duration-wrapper.jsx
- to fix Vanilla Duration disappearing when switching from a Duration that is unavailable for Vanillas (e.g. Ticks/Minutes) on another trade type (e.g. Rise/Fall).
=> [DTRA] Maryia/WEBREL-1645/Hotfix: Vanilla Duration disappears when switching from unavailable duration

packages/core/src/App/Containers/app-notification-messages.jsx, packages/core/src/Stores/notification-store.js
We need to hide the Reassembly Notification from Notification tray and Toast Popup(Yellow Banner) from the whole Deriv-app.
- The Deriv MT5: Your action is needed notification has been hidden from the page and the notification inbox in both desktop and responsive
=> [CFDS] Hamza/ chore: hide the reassembly notification and popup

packages/wallets/src/features/cashier/modules/DepositCrypto/DepositCrypto.scss, packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoDisclaimers/DepositCryptoDisclaimers.scss
- `Notes` section in Crypto Deposit should be left aligned.
- Gap between elements in Crypto Deposit for mobile screens should be 1.6rem.
=> Nijil/ WALL-2575/ Notes section in Crypto Deposit is not left aligned

packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
- Change `||` to `??` because `0` is valid value
https://app.clickup.com/t/20696747/WALL-2527
=> [Wallets] Sergei / wall - 2527 / Scroll wallets carousel to fiat wallet

packages/wallets/src/features/cashier/WalletCashier.scss, packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoDisclaimers/DepositCryptoDisclaimers.scss
Wallet Overlay content is not centre aligned anymore until design files are updated.
Also `Notes` section should be
- Centre aligned in desktop
- Left aligned in responsive.
=> [WALL] Nijil/ WALL-2526 / Wallet overlay content is not centre aligned anymore

.github/workflows/smoketests.yml
We should be able to run everything in the smoke test folder now.
Removed the t in the spec file filter. At the moment it will only run traders hub tests and we want to run others in that folder now.
=> Remove t* filter for smoke tests

packages/wallets/src/components/DerivAppsSection/DerivAppsGetAccount.tsx
Add `closeOnEscape` property
https://app.clickup.com/t/20696747/WALL-2476
https://github.com/binary-com/deriv-app/assets/120570511/00fa3be5-f56e-403a-bd8a-67c139c6c9b8
=> [Wallets] Sergei / Wall 2476 / On pressing escape key success modal should be closed

packages/api/src/hooks/usePOI.ts
- There's some issues with naming. `next` naming causes consumer to think it is an iterable. Rename it to `current` instead.
=> yashim/chore: renamed usePOI api to prevent confusion

packages/wallets/src/components/WalletTourGuide/WalletMobileTourGuide.tsx, packages/wallets/src/components/WalletTourGuide/WalletTourGuide.tsx
All PRs fail because `useAvailableWallets` was changed, but `WalletMobileTourGuide` component used this hook. Need to change it to `useAllWalletAccounts` hook
- change `useAvailableWallets` to `useAllWalletAccounts`
https://app.clickup.com/t/20696747/WALL-2600
=> [WALL] Sergei / fix PR for useAvailableWallets hook

packages/wallets/src/components/DerivAppsSection/DerivAppsGetAccount.tsx, packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.scss, packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.tsx
- Decrease Options and Multipliers subtitle font size in responsive
- Increase Deriv Apps description font size
https://app.clickup.com/t/20696747/WALL-2478
=> [Wallets] Sergei / wall - 2478 / Texts in Options and multipliers looks too small in responsive

packages/core/src/Stores/notification-store.js
Notification for reset demo account balance is not shown in traders_hub . It was because the notification had a config that it should be shown only in dtrader. Removing the platform restriction in this PR
=> [COJ]/WALL_1460/Amina/fix: reset balance notification

packages/api/src/hooks/useTradingPlatformPasswordChange.ts, packages/api/src/useMutation.ts, packages/hooks/src/__tests__/useDepositCryptoAddress.spec.tsx, packages/hooks/src/__tests__/useWalletMigration.spec.tsx
The difference between mutate and mutateAsync is as follows:
- `mutate`: This is used to trigger the mutation without waiting for the result. It initiates the mutation, and any updates to the cache or UI are handled in the background.
- `mutateAsync`: This is used when you want to await the result of the mutation before proceeding. It is beneficial when actions or decisions need to be based on the outcome of the mutation.
We need to add the callback on the mutateAsync function so we can use `useTradingPlatformChange` and `useCreateMT5Account` websocket calls asynchronously.
Slack Discussion:
[Discussion](https://deriv-group.slack.com/archives/C05NSB1LPMX/p1699958017256429)
CU Card:
[Modifying useMutation in api …
=> [Wallets] Hamza/WALL-2608/Modifying useMutation in api package

packages/wallets/src/features/cfd/screens/ChangePassword/ChangePassword.scss, packages/wallets/src/features/cfd/screens/ChangePassword/ChangePassword.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/MT5Password.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/index.ts, packages/wallets/src/features/cfd/screens/index.ts
- added styles and component
- added tabs and switching functionality
- separate first page into it's own component
- mobile friendly
https://github.com/binary-com/deriv-app/assets/103104395/3d67be3b-e62e-44d8-ab1a-aaabab15a382
=> [WALL] chore: created ChangePassword Modal screen:

packages/trader/src/App/Components/Elements/PositionsDrawer/__tests__/positions-drawer.spec.tsx
- Add tests to the mentioned file
=> [DTRA] / Kate / WEBREL-43 / Test coverage: positions-drawer.tsx in Trader package

.github/actions/build_and_push_docker_image/action.yml
Based on [this](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-writing-an-environment-variable-to-github_env) github document I altered the usage of `GITHUB_ENV` to fix the docker push action issue.
=> Ako/ pass the secrets to github env

.github/workflows/coveralls.yml, .github/workflows/integration-tests.yml, .github/workflows/release_production.yml, .github/workflows/release_test.yml, .github/workflows/test.yml
In order to maintain the runner cost we need to use 8 cores cpu for the runners. 
=> Ako/ use 8 cores runner

packages/api/src/hooks/usePOI.ts
- `usePOI` no longer depends on `account_status.is_idv_revoked` as its only checked for `IDV` and `Labuan` cases on `useJurisdictionStatus` hook
=> [WALL] removed idv_revoked dependency on usePOI

packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.scss, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.tsx, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AvailableDxtradeAccountsList/AvailableDxtradeAccountsList.scss
1. Fix the styles and spacing for deriv x account 
2. Use WalletText and replace p tags
=> WALL-2620/chore: fix deriv x account text and styles

packages/wallets/src/features/cashier/modules/TransactionStatus/TransactionStatus.scss
Transaction Status component should be placed at 2.4rem from top. But since the padding of wallet-cashier-content is 4.8rem and position of transaction status is `absolute`, it should have a negative top of -2.4rem.
=> [WALL] Nijil/WALL-2621/Adjust padding-top of transaction-status component

packages/wallets/src/features/cfd/modals/JurisdictionModal/JurisdictionModal.tsx
- Fixed a bug, where upon selecting SVG in jurisdiction modal, the Next button is disabled
https://github.com/binary-com/deriv-app/assets/103016120/6092694d-b18c-40e0-8ad1-6277cf92dd41
=> [WALL] Fixed an issue where next button is disabled on selecting svg

packages/wallets/src/components/AccountsList/AccountsList.tsx, packages/wallets/src/components/WalletTourGuide/WalletMobileTourGuide.tsx, packages/wallets/src/components/WalletsCarousel/WalletsCarousel.tsx, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
Previous logic waited for MT5 section load and started onboarding, but if this section loaded too fast and carousel didn't have enough time to scroll to the proper wallet the user could see the issue on the image attached
- To prevent this added one more callback for wallet carousel to wait for wallet settle
https://app.clickup.com/t/20696747/WALL-2631
=> [WALL] Sergei / wall - 2631 / wrong wallet is selected, onboarding is not properly showing

packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-submission.jsx
This PR fixes the issue where if the IDV POI check fails 3 times, client is supposed to be redirected to onfido if there are submissions are available for the client, however, the flow is being redirected to manual.
=> [COJ] shahzaib / idv poi not redirecting to onfido if failed in last attempt

packages/bot-web-ui/src/components/quick-strategy/inputs/qs-checkbox.tsx, packages/bot-web-ui/src/components/quick-strategy/inputs/qs-input-label.tsx, packages/bot-web-ui/src/components/quick-strategy/inputs/qs-input.tsx, packages/bot-web-ui/src/components/quick-strategy/quick-strategy.tsx
- CU https://app.clickup.com/t/20696747/BOT-1001
- Put the popover to show at the top for mobile devices 
- Change showing error on popover logic. Now it will show a red border whenever an error occurs and on hover it will show the error messages in the popover 
- Validation logic is updated and dynamically taken from the config file if any field is dependent upon any other field
- Perform validation checks on `validateOnBlur` `validateOnChange` `validateOnMount`
https://github.com/binary-com/deriv-app/assets/129021108/afcce7e9-fb60-4110-853b-da371afe5c2c
=> [BOT] chore: fix quick strategy max stake disable error issue

packages/bot-web-ui/src/components/quick-strategy/config.ts, packages/bot-web-ui/src/xml/reverse_martingale.xml
- Added reverse martingale strategy for quick strategies
- Added the required fields for reverse martingale to the quick strategy config
- Added the reverse martingale xml with updated fields
=> [BOT] Farabi/bot-155/add reverse martingale strategy

packages/bot-web-ui/src/app/__tests__/app-main.spec.tsx, packages/bot-web-ui/src/app/app-main.tsx, packages/bot-web-ui/src/public-path.ts
- Removed survicate code snippet from app-main as we are no longer using survicate tool for tracking and will be replacing with hotjar tool
- Updated test file for app-main.spec to remove the test case for survicate
- Updated the deprecated TRootStore with TStores in app-main.spec
- Removed survicate code snippet from public-path
=> [BOT] Farabi/bot-985/remove survicate code snippet

packages/api/src/APIContext.ts, packages/api/src/APIProvider.tsx, packages/api/src/useAPI.ts
- Wrapped DerivAPI instance around refs without breaking current functionality
- Added initial support for WebSocket language settings by reading 'i18n_language' local storage item
- Fixed reconnection failing for certain scenarios
=> [WALL] yashim/refactor: api provider websocket instance to follow react lifecycle

packages/appstore/src/modules/traders-hub/index.tsx
we had an ts error for `<OrderedPlatformSections/>` 
and to fix it I converted the components props into an object.
=> shayan/feq-931/ fixed ts error for OrderedPlatformSections component

packages/bot-web-ui/src/stores/data-collection-store.js
- This PR is to debug the Trackjs issues listed in https://app.clickup.com/t/20696747/BOT-991
- We are only changing the request header `mode` to 'no-cors' which was previously 'cors'
=> [BOT] chore: trackjs appspot issue

packages/wallets/src/features/cashier/WalletCashier.scss, packages/wallets/src/features/cashier/flows/WalletTransfer/WalletTransfer.tsx, packages/wallets/src/features/cashier/modules/DepositCrypto/DepositCrypto.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsTable/TransactionsTable.scss, packages/wallets/src/features/cashier/modules/Transfer/Transfer.tsx, packages/wallets/src/features/cashier/modules/Transfer/provider/TransferProvider.tsx, packages/wallets/src/features/cashier/screens/TransferNotAvailable/TransferNotAvailable.scss, packages/wallets/src/features/cashier/screens/TransferNotAvailable/TransferNotAvailable.tsx, packages/wallets/src/features/cashier/screens/TransferNotAvailable/TransferNotAvailableProvider.tsx, packages/wallets/src/features/cashier/screens/TransferNotAvailable/index.ts
- add no transfer available screens
=> [Wallet] WALL-2195 / george / Implement No Transfer Available Screen

packages/components/src/components/contract-card/contract-card-items/__tests__/turbos-card-body.spec.tsx, packages/components/src/components/contract-card/contract-card-items/turbos-card-body.tsx, packages/reports/src/Constants/data-table-constants.tsx, packages/trader/src/App/Components/Elements/PositionsDrawer/__tests__/position-modal-card.spec.tsx
- In current implementation of` <TurbosCardBody />` `Total Profit/Loss` was not shown if profit was === 0 because of `!!profit` && check. File was refactored together with tests. Confirmed by PO, that we shouldn't show any color indication for such cases.
- Add additional check for zero-values in Reports -> Open Contracts (_packages/reports/src/Constants/data-table-constants.tsx_), because previously PNL was not shown if it was zero. Applied to all contracts.
=> [DTRA] / Kate / DTRA-518/ Profit/Loss in not shown when it is equal to zero

packages/bot-web-ui/src/app/__tests__/app-content.spec.tsx
https://app.clickup.com/t/20696747/BOT-959
- Test case for app content.jsx
- Check if the loader is working properly
- Check if the Dashboard is loading if the user is not logged in
- Check if open contracts are getting settled
- Check if the message handler is unsubscribed on component unmount
- Check if the loader is not shown when the user goes offline
=> [BOT] chore: test case for app-content

packages/bot-web-ui/src/components/chart/__tests__/chart.spec.tsx
- Added test case for chart component
=> [BOT] Farabi/bot-960/test coverage for chart

packages/bot-web-ui/src/components/quick-strategy/quick-strategy.tsx, packages/bot-web-ui/src/components/quick-strategy/selects/duration-type.tsx, packages/bot-web-ui/src/stores/quick-strategy-store.ts
https://app.clickup.com/t/20696747/WEBREL-1687
- Duration field error schema is not updating based on the latest duration type selection
- Remove one `useEffect` from `quick-strategy.tsx` as we are only taking the latest min and max value from here which we can also collect from the `duration-type.tsx` file.
- Created one more observable in the store which will store the currently selected duration's min and max value
=> fix: quick strategy duration issue

packages/components/src/hooks/__tests__/use-onlongpress.spec.tsx, packages/components/src/hooks/use-onlongpress.ts
- to fix a console error: '_Unable to preventDefault inside passive event listener invocation_'.
Test coverage of the `useLongPress` hook:
=> [DTRA] Maryia/DTRA-494/fix: console error about preventDefault inside passive event listener

packages/wallets/src/components/FlowField/FlowTextField.tsx, packages/wallets/src/features/accounts/screens/IDVDocumentUpload/IDVDocumentUpload.tsx, packages/wallets/src/features/accounts/screens/PersonalDetails/PersonalDetails.tsx, packages/wallets/src/features/accounts/validations.ts, packages/wallets/src/features/cfd/flows/Verification/Verification.tsx
1. Update the regex for idv flow
2. Update form values for formik
https://github.com/binary-com/deriv-app/assets/104053934/add46e15-bb92-4a7d-9fa7-2bc3775057c7
=> WALL-2708/chore: fix remaining validations for idv page

packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeDetailsItem/MT5TradeDetailsItem.tsx
- assign reset password button inside MT5 Trade Modal to show MT5 Change Password
- remove success message
https://github.com/binary-com/deriv-app/assets/103104395/eaf33343-d795-44c0-8093-b59fc0cbd103
=> [WALL] Aizad/WALL-2701/Linking MT5 Change Password Modal to existing MT5 Trade modal

packages/core/src/Services/socket-general.js
- Add the `websocketUrl` to the timeout error for trackjs.
- Add the `clientsCountry` to the timeout error for trackjs.
- Use the TrackJS error function as documented [here](https://docs.trackjs.com/browser-agent/sdk-reference/agent-methods/#consoleerror)
=> [FEQ] Add websocketurl to timeout

packages/api/src/hooks/index.ts, packages/api/src/hooks/useAccesiblePlatforms.ts
- using flags like `CFDs_restricted_countries` and `financial_restricted_countries` to filter for available cTrader and dxTrade accounts:
- using the `landing_company` hook to check if ctrader and dxtrade are allowed in client's country of residence 
- in the case of dxtrade, when it is available, `dxtrade_all_company` will be in the response, else, it is not in the response
- in the case of ctrader, when it is available, `ctrader` will be in the response and the jurisdiction will be svg. Else, `ctrader` will be in the response but the jurisdiction will be empty string (' ') or `undefined`
=> [Refactoring] shontzu/CFDS-1435/use-landing-company-hooks-for-cTrader-and-DxTrade

packages/bot-web-ui/src/components/quick-strategy/inputs/qs-input.tsx
duration field validation error is not displayed in mobile
https://github.com/binary-com/deriv-app/assets/103181650/b4daa244-94ae-4f72-bd94-60e0429afcee
=> [BOT]/Maryia/WEBREL-1698/fix: duration field validation error is not displayed in mobile

packages/p2p/src/stores/buy-sell-store.js
- removed `should_filter_by_payment_method` computed value from the buy sell store as it is not being used anywhere
=> [P2PS] Ameerul /P2PS-1933 Remove the unused function in BuySellStore

packages/p2p/src/stores/my-profile-store.js
- Removed these observables and functions from the store as they were unused: `createPaymentMethod, onClickDelete, onEditDeletePaymentMethodCard, delete_error_message, setDeleteErrorMessage, selected_payment_method_type, setSelectedPaymentMethodType`
=> [P2PS] Ameerul /P2PS-1936 Remove the unused observables and functions in MyProfileStore

packages/p2p/src/components/order-details/order-details.jsx, packages/p2p/src/stores/order-store.js
- removed `data, setData, user_email_address, setUserEmailAddress, getSettings` from order store as they were unused.
- removed getSettings from order-details component as it only called `setUserEmailAddress` which was removed.
Did a quick sanity check on removing the `getSettings` function in order details: 
https://github.com/binary-com/deriv-app/assets/103412909/a109d6e0-afec-4513-a932-bc258d1f83a7
=> [P2PS] Ameerul /P2PS-1937 Remove the unused observables and functions in OrderStore

packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoForm/components/WithdrawalCryptoAmountConverter/WithdrawalCryptoAmountConverter.tsx, packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx, packages/wallets/src/features/cfd/modals/JurisdictionModal/JurisdictionModal.tsx, packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx, packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
1. Add error modal to show if there is any error when creating cfd account from BE
https://github.com/binary-com/deriv-app/assets/104053934/69c1576f-19c6-4a27-85d5-df35a4db2af7
=> WALL-2749/feat: add error modal to cfd

packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowTransferAccountDetails/TransactionsCompletedRowTransferAccountDetails.tsx
Transfer transaction lookup now has a temporary workaround for BE `statement` and `mt5_login_list` accounts `loginid` mismatch
=> [WALL] [Fix] Rostislav / WALL-2731 / Temporary workaround for BE `statement` and `mt5_login_list` accounts `loginid` mimatch

packages/wallets/src/AppContent.scss, packages/wallets/src/components/Base/WalletButton/WalletButton.tsx, packages/wallets/src/features/cashier/WalletCashier.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsTable/TransactionsTable.scss
https://github.com/binary-com/deriv-app/assets/142860499/2c5f8a8d-a0d4-4c23-ac53-9fa109128f10
https://github.com/binary-com/deriv-app/assets/142860499/74019eb4-271f-40bc-beea-761132c50ace
=> [WALL] Lubega / WALL-2733 / Feat: Base component scrollbar

packages/wallets/src/AppContent.scss, packages/wallets/src/components/Base/WalletButton/WalletButton.tsx, packages/wallets/src/features/cashier/WalletCashier.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsTable/TransactionsTable.scss
This PR reverts https://github.com/binary-com/deriv-app/pull/11737
Reverts this PR because of design issues in mobile and desktop view. Scrollbar shifts the content to the left.
=> Revert "[WALL] Lubega / WALL-2733 / Feat: Base component scrollbar"

packages/wallets/src/components/Base/WalletPasswordField/WalletPasswordField.scss
1. Fixed an issue where password meter is not full width
=> WALL-2763/fix: password meter to be full width

packages/wallets/src/features/cfd/screens/CFDSuccess/CFDSuccess.tsx
1. Fixed the account title for swap free in success modal
Before: 
After:
=> WALL-2764/chore: fix swap free title in success modal

packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionTncSection/JurisdictionTncSection.tsx
1. Fixed for showing static landing company name. Now it shows proper landing company name in the terms and conditions section for jurisdiction modal according to selected jurisdiction
https://github.com/binary-com/deriv-app/assets/104053934/27feb0dc-2b78-4c77-8c9e-9b37ecddd202
=> WALL-2761/fix: landing company name in the terms and conditions checkbox according to selected jurisdiction

packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
1. Fixed to show the correct account name in enter password modal for MT5 
Before: 
https://github.com/binary-com/deriv-app/assets/104053934/4c250e31-8329-4578-93b6-5ce5e5eea6c7
After:
https://github.com/binary-com/deriv-app/assets/104053934/c45e056d-fd26-4ed8-9b83-c7f3a4286607
=> WALL-2762/fix: account name in enter password modal

packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoForm/WithdrawalCryptoForm.tsx
Found and fixed the issue with the percentage of the crypto withdrawal amount shown below the percentage selector. The calculated percentage was not multiplied by 100.
=> [WALL] [Fix] Aum/WALL-2778/fix-withdrawal-crypto-percentage-message

packages/wallets/src/features/cashier/modules/DepositCrypto/DepositCrypto.scss, packages/wallets/src/features/cashier/modules/DepositCrypto/DepositCrypto.tsx, packages/wallets/src/features/cashier/modules/TransactionStatus/TransactionStatus.scss, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/WithdrawalCrypto.scss, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/WithdrawalCrypto.tsx
Position `TransactionStatus` in crypto deposit & withdrawal in a way that avoids overlapping on smaller desktop screens.
https://github.com/binary-com/deriv-app/assets/119863957/f6add4c7-ef46-44d6-aa5c-e805828ae0cb
=> [WALL] Rostislav / WALL-2296 / Correct `TransactionStatus` positioning in crypto deposit & withdrawal

packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.tsx
1. Remove minus icon for svg jurisdiction
https://github.com/binary-com/deriv-app/assets/104053934/03fe3696-ca9f-499a-bbb6-11b2ca04e927
=> [wallets]thisyahlen/WALL-2766/chore: remove minus icon for svg jurisdiction

packages/wallets/src/components/Base/WalletPasswordField/WalletPasswordField.tsx, packages/wallets/src/components/Base/WalletTextField/WalletTextField.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/ChangePassword.scss, packages/wallets/src/features/cfd/screens/ChangePassword/MT5ChangeInvestorPasswordScreens.tsx
Fixing minor issues on `<MT5InvestorChangePassword />` Modal
- added name prop inside of WalletPasswordField
- change stylings of password field so it resembles figma design
- minor code changes
**Before:**
https://github.com/binary-com/deriv-app/assets/103104395/e2a9274f-2043-4233-87b9-f21976dbc6ac
**After:**
https://github.com/binary-com/deriv-app/assets/103104395/405cebdd-7958-4ee3-9a35-b18fde1f1018
=> [WALL] Aizad/WALL-2784/ Minor fix on Investor Change Password Modal

packages/api/src/hooks/useAccesiblePlatforms.ts
[[Refactoring] Add the is_mt5_allowed in the useAccessiblePlatforms](https://app.clickup.com/t/20696747/CFDS-1505)
- Update the useAccessiblePlatforms  to contains the check for MT5 Platform.
For now we have checks only for Ctrader and Deriv X accounts.
- We need to add the check for MT5 Accounts so we can use this in Traders Hub to show only Accessible Platforms in that particular client's residence country.
- Only accessible platforms should be shown to client based on client's residence country.
- Landing Company Response in case of MT5 Accessible by client country of residence
- Landing Company Response in case of MT5 not accessible by client country of residence
=> [CFDS] [Refactoring] Add the is_mt5_allowed in the useAccessiblePlatforms

packages/wallets/src/components/DerivAppsSection/DerivAppsGetAccount.tsx
1. Balance is showing 10000, when creating new trading account in wallet success modal
Before: 
After:
https://github.com/binary-com/deriv-app/assets/104053934/783bb1de-b20e-4135-b690-467dbbe17b06
=> [wallets]thisyahlen/wall-2802/fix: on creating new real trading account in wallet, the balance is showing 10000 in success modal

packages/bot-web-ui/src/components/quick-strategy/inputs/qs-checkbox.tsx, packages/bot-web-ui/src/components/quick-strategy/inputs/qs-input-label.tsx
Made change in QS modal in bots , so that popover message appears at the top of lable.
=> [Bot] fix: change tooltip position to top in QS modal for desktop view

packages/wallets/src/components/SentEmailContent/SentEmailContent.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/MT5ChangePasswordScreens.tsx, packages/wallets/src/utils/cfdUtils.ts
- added `useVerifyEmail` hook inside of `<ChangeMT5Passwords />` to send password reset link via email.
- updated  `useVerifyEmail` hook inside of `<SentEmailContent />` by adding `url_parameter` inside.
=> [WALL] Aizad/WALL-2727/Adding Logic inside of MT5ChangePassword

packages/p2p/src/pages/advertiser-page/advertiser-page.jsx, packages/p2p/src/stores/advertiser-page-store.js
Currently in production, when a user visits client A, then goes back to buy sell page and then visits client B, we could see the details of client A in client B's page. This PR is to fix the issue. 
=> [P2PS]-fix: advertiser badges not showing on initial load

packages/cashier/src/pages/withdrawal/withdrawal-crypto-form/__tests__/withdrawal-crypto-form.spec.tsx, packages/cashier/src/pages/withdrawal/withdrawal-crypto-form/withdrawal-crypto-form.tsx, packages/cashier/src/pages/withdrawal/withdrawal-crypto-receipt/__tests__/withdrawal-crypto-receipt.spec.tsx, packages/cashier/src/pages/withdrawal/withdrawal-crypto-receipt/withdrawal-crypto-receipt.tsx, packages/hooks/src/useCryptoTransactions.ts
- Removed the resetWithdrawForm function when unMounting from withdrawl crypto form since it is already called when you request to withdraw in `requestWithdraw` function
- Removing the above helps to ensure the address is displayed and wont get reset if component unmounts
- Added proper transaction status changes if use decides to stay on the page using `last_transaction` from `useCryptoTransactions`, similar to how it is used in `TransactionsCryptoTransactionStatusSideNote`
- Updated test cases
=> [WALL] Ameerul /WALL-1422 Noticing issue in Crypto Withdrawal transaction page

packages/integration/src/exampleMock.ts, packages/integration/src/utils/mocks/generateOauthLoginFromAccounts.ts, packages/integration/src/utils/mocks/mocks.ts
This abstracts the oauth url generation, and allows us to print the url when creating a standalone mock server.
=> [FEQ] chore: abstract mock oauth url logic[

packages/wallets/src/features/cfd/components/ModalTradeWrapper/ModalTradeWrapper.tsx
1. Fixed the order of the app icons in cfd trade modal
=> [wallets]Thisyahlen/wall 2794/icon platform not in order mt5 trade modal

packages/wallets/src/features/cfd/screens/CFDSuccess/CFDSuccess.tsx
1. Removed jurisdiction from dxtrade real success modal
=> [wallets]thisyahlen/WALL-2640/fix: remove jurisdiction from real dxtrade success popup

packages/wallets/src/components/WalletsAddMoreCarousel/WalletsAddMoreCarousel.scss
1. Remove border and adjust padding in add more wallets section to match design
=> [wallets]thisyahlen/WALL-2821/fix: remove border and adjust padding in add more wallets section to match design

packages/wallets/src/components/Base/WalletPasswordField/WalletPasswordField.scss, packages/wallets/src/components/Base/WalletPasswordField/WalletPasswordField.tsx, packages/wallets/src/constants/passwordConstants.ts, packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
- Change border radius for password meter
- Change warning message to resemble the one in production
- Remove password meter and warning messages inside of Enter Password modal
1. Password meter width is not aligned properly
3. Change warning message from **" This is a very commonly password"** to be **"This is a very common password"**
4. Remove password meter and warning messages inside of `EnterPassword` Modal 
https://github.com/binary-com/deriv-app/assets/103104395/342b827c-2889-4a7c-a01f-91602192bcb5
=> [WALL] Aizad/WALL-2828/Fix issues related to Password Meter component and Enter Password Modal in Deriv X

packages/cashier/src/pages/withdrawal/withdrawal-crypto-form/withdrawal-crypto-form.scss
Fixed the spacing between the crypto-address-field and the percentage-selector in the crypto-withdrawal screen in cashier.
Broken:
Fixed:
=> [Fix] aum/WALL-2813/fix-crypto-withdrawal-message-overlap

packages/api/src/hooks/index.ts, packages/api/src/hooks/useInfiniteTransactions.ts, packages/wallets/src/features/cashier/modules/Transactions/Transactions.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompleted/TransactionsCompleted.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedDemoResetBalance/TransactionsCompletedDemoResetBalance.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedDemoResetBalance/TransactionsCompletedDemoResetBalance.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedDemoResetBalance/index.ts, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/TransactionsCompletedRow.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowAccountDetails/TransactionsCompletedRowAccountDetails.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/index.ts, packages/wallets/src/types.ts
https://github.com/binary-com/deriv-app/assets/119863957/a325e9c5-41a0-4d98-b016-f9f1855e386f
=> [WALL] [Fix] Rostislav / WALL-2689 / Demo transactions `reset_balance` workaround

packages/bot-web-ui/src/components/chart/chart.scss, packages/bot-web-ui/src/components/chart/chart.tsx, packages/bot-web-ui/src/components/dashboard/bot-builder/toolbar/workspace-group.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/__tests__/chart-modal-desktop.spec.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/__tests__/chart-modal.spec.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/chart-modal/chart-modal-desktop.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/chart-modal/chart-modal.scss, packages/bot-web-ui/src/components/dashboard/dashboard-component/chart-modal/chart-modal.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/chart-modal/index.ts, packages/bot-web-ui/src/components/dashboard/dashboard-component/index.ts, packages/bot-web-ui/src/components/dashboard/dashboard.scss, packages/bot-web-ui/src/components/dashboard/dashboard.tsx, packages/bot-web-ui/src/components/draggable/draggable.scss, packages/bot-web-ui/src/components/draggable/draggable.tsx, packages/bot-web-ui/src/stores/dashboard-store.ts
Being able to see the charts while building a bot:
1.1 The chart view should be displayed as a pop-up window with an **active background** 
1.2 The chart pop-up window should be **movable around the screen**. The user should not be allowed to resize the screen. 
1.3 Tab(text and icon) should be **disabled** when modal window with charts are active 
1.4 To be handled only **for desktop**
1.5 Make as per design, available buttons for the desktop version on the modal window should be different depending on the full window on the tab charts 
1.6 Adjust the market dropdown list in the chart modal window
1.7 The modal window should not extend beyond the **screen boundaries**, the user should have the ability to drag the window always
1.8 Fixed signature label Beta chart
1.9  Fix bounce bug upon …
=> [BOT]Maryia/BOT-1012/Adapt to changes made in SmartCharts to show chart while building bot on desktop

packages/appstore/src/modules/traders-hub/index.tsx, packages/stores/src/mockStore.ts, packages/stores/types.ts
- Banner for EU account should visible on Trader's hub (Disclaimer banner as per screenshot below)
- Refer below screenshot for DIEL MF account:
CU Card:
[[Trader's Hub] EU banner is missing for MF only account](https://app.clickup.com/t/20696747/PRODQA-928)
=> [Trader's Hub] EU banner is missing for MF only account

packages/trader/src/Modules/Trading/Containers/trade.jsx
It was a bug where the digits were not visible on the mobile screen for the matchers/differs contract type.
=> [dtra]/Ahmad/showing digits on the Matchers/Differs contract type on mobile screen

packages/bot-web-ui/src/stores/__tests__/route-prompt-store.spec.tsx, packages/bot-web-ui/src/stores/route-prompt-dialog-store.js
- Added another check of `is_running` to the warning prompt showing logic
=> [BOT] shafin/BOT-862/fix dont show warning pop-up when leaving bot if bot is not running

packages/trader/src/Modules/Trading/Containers/trade.jsx
Reverts binary-com/deriv-app#12010
=> Revert "[dtra]/Ahmad/showing digits on the Matchers/Differs contract type on mobile screen"

packages/wallets/src/hooks/__tests__/useDevice.spec.ts
1. Add unit test to useDevice hook in wallets package
=> [wallets]thisyahlen/wall-3006/chore: add unit test for usedevice hook

packages/wallets/src/components/SentEmailContent/SentEmailContent.scss, packages/wallets/src/components/SentEmailContent/SentEmailContent.tsx, packages/wallets/src/components/WalletsActionScreen/WalletsActionScreen.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/ChangePassword.scss, packages/wallets/src/features/cfd/screens/ChangePassword/ChangePassword.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/InvestorPassword/MT5ChangeInvestorPasswordScreens.scss, packages/wallets/src/features/cfd/screens/ChangePassword/InvestorPassword/MT5ChangeInvestorPasswordScreens.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/MT5ChangePasswordScreens.tsx
- Move send email screen outside of the tabs for the reset investor password
- update styles to follow the design
https://app.clickup.com/t/20696747/WALL-3020
How it was:
How it's now:
=> [WALL] Sergei / wall 3020 / Reset investor password design change

packages/bot-web-ui/src/stores/route-prompt-dialog-store.js, packages/bot-web-ui/src/stores/run-panel-store.js
- Unregister the `setPromptHandler` if the bot is stopped due to an error
- Change back the `shouldNavigateAfterPrompt` method to the previous implementation
=> fix: leaving already pop up not shown at all issue

packages/wallets/src/features/accounts/screens/CommonMistakesExamples/__tests__/CommonMistakesExamples.spec.tsx
1. Add unit test for CommonMistakesExamples
=> [wallets]thisyahlen/WALL-2919/chore: add unit test for CommonMistakesExamples

packages/components/src/components/button/button.scss, packages/components/src/components/modal/modal.scss, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/__tests__/cancel-deal.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/__tests__/expiration-modal.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/__tests__/expiration.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/__tests__/info.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/__tests__/multiplier.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/__tests__/stop-loss.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/__tests__/take-profit.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/__tests__/widgets.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/expiration-modal.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/expiration.tsx, packages/trader/src/sass/app/modules/trading.scss
- Add unit tests and refactored old ones for mentioned above files
- Refactored _packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/expiration.tsx, packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/expiration-modal.tsx_ . Moved inline-styles to css and removed unused `observer`.
=> [DTRA] / Kate / WEBREL-75 / Test coverage + Refactoring: Multiplier trade params in Trader package

packages/p2p/src/pages/my-ads/my-ads-row-renderer.jsx
Currently when an ad is in floating rate, and in BO the rate is changed to fixed rate, or ad is in fixed and in BO the rate is changed to floating rate, the indication for the hidden ad will not be given. Its because the reason is determined based on the code obtained from the <visibility_status> field which appears only when the cron job is run. In production since the cron job is run only once in 24 hours, by any chance if the rate is changed and cron job is not run, the reason will not be visible. This PR fixes the issue by manually stating the reason until the value is received from BE.
=> [P2PS]-fix: issue where reason was not listed for fixed-to-float or viceversa

packages/trader/src/Modules/Contract/Components/Digits/__tests__/digits.spec.tsx
This pull request (PR) is a fix that addresses a Jest error specifically in the "digits" test file. Jest errors in test files typically indicate issues with the test cases, such as failing assertions or unexpected behavior during testing.
The fix may involve correcting the problematic test cases, resolving issues with setup or teardown procedures, or ensuring that the test file aligns with the expectations of the Jest testing framework. This type of fix is crucial for maintaining the reliability and accuracy of tests, ensuring that they accurately reflect the expected behavior of the code they are testing.
=> Akmal / fix: jest error in digits test file

packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationRequest/WithdrawalVerificationRequest.tsx, packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationRequest/__tests__/WithdrawalVerificationRequest.spec.tsx
=> [WALL] Lubega / WALL-3002 / Chore: Withdrawal verification request unit test

packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationSent/WithdrawalVerificationSent.tsx, packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationSent/__tests__/WithdrawalVerificationSent.spec.tsx
=> [WALL] Lubega / WALL-3003 / Chore: Withdrawal verification sent unit test

packages/account/src/Components/forms/scroll-to-field-with-error.tsx
according to TrackJS log this error occurs in old browsers, because Object.hasOwn is not supported in old browsers.
so modifying it here to Object.prototype.hasOwnProperty.call() to apply the same functionality
=> [COJ] Evgeniy/COJ-1024/fix track.js error Object.hasOwn is not a function

packages/bot-web-ui/src/stores/google-drive-store.js
- Added condition to check if the callback response has the access code and also it doesn't contain any error. Only then proceed to show the user as connected.
=> [BOT] shafin/BOT-869/fix google drive showing connected even on abort action

packages/api/src/constants/index.ts, packages/api/src/constants/payment-method-icons.ts, packages/api/src/hooks/p2p/useAdvertInfo.ts, packages/api/src/hooks/p2p/usePaymentMethods.ts, packages/hooks/src/useP2PAdvertInfo.ts
- Moved the `useAdvertInfo` hook from the `hooks` package to the `api` package
=> [FEQ] Jim/FEQ-990/p2p advert information

packages/wallets/src/components/Base/ATMAmountInput/ATMAmountInput.scss
=> [WALL] [Fix] Rostislav / WALL-3092 / Fix transfer ATM fields position on mobile

packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAmountInput/TransferFormAmountInput.tsx
=> [WALL] [Fix] Rostislav / WALL-3090 / Fix debounce failing when quickly un-focusing the input

packages/cfd/src/Constants/jurisdiction-contents/jurisdiction-verification-contents.ts, packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-card-back.spec.tsx
Noticed that the sentence "A copy of your identity document (e.g. identity card, passport, driver's license)" is not translated according to the selected language.
=> [WEBREL] [CFDS] Hamza/WEBREL-1769/Content translation for "Verification explained" in the Jurisdiction selection table for CFDs

packages/cfd/src/sass/cfd.scss, packages/components/src/components/modal/modal.scss
Fixed user have to scroll to see the next button issue for pop-up modal.
Previous issue:
=> Suisin/chore: update scss to not use max height for jurisdiction modal

packages/p2p/src/stores/my-ads-store.js
- Changed min and max validation messages to `Only up to 2 decimals are allowed.` if user enters more than 2 decimals and `Only numbers are allowed.` if the user enters non numbers. Previously the messages were only `Enter a valid amount.`
=> [P2PS] Ameerul / P2PS-969 / Improve validation message for amount fields (FE)

packages/api/src/hooks/p2p/useOrderCancel.ts
- added hook for p2p order cancel endpoint
=> [FEQ] Ameerul / FEQ-1000 / P2P Order Cancel Hook

packages/account/src/Components/poi/idv-status/idv-failed/idv-failed.tsx, packages/core/src/sass/app/_common/components/account-common.scss
This PR fixes the alignment issue with the `Verify` button in POI screen in accounts when the POI is rejected at least once.
=> [COJ] shahzaib / COJ-414 / verify button alignment in POI accounts screen

packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-submission.jsx
Fixed the condition that was used to decide the screen to be displayed when a High risk user verified earlier by IDV opens POI screen
=> [COJ]/likhith/KYC-1523/display appropriate POI screen for Highrisk user

docs/JavaScript/README.md
We currently use the airbnb styleguide, but override some of their recommendations.
To try and adhere to the wider JavaScript community, I am proposing we following airbnb's styleguide with no overrides.
=> [FEQ] chore: reduce airbnb linting overrides

packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsTitleIcon.tsx
- Change cTrader title from `cTrader` & `cTrader Demo` to `Deriv cTrader` && `Deriv cTrader Demo`
=> [WALL] Aizad/WALL-3121/Deriv cTrader heading inside of Compare Accounts Modal

packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsCard.tsx, packages/wallets/src/features/cfd/screens/CompareAccounts/InstrumentsLabelHighlighted.scss, packages/wallets/src/features/cfd/screens/CompareAccounts/InstrumentsLabelHighlighted.tsx
- added alternative classname for demo to fix spacing between Icon List and text description within `InstrumentsLabelHighlighted`
Before:
After:
=> [WALL] Aizad/WALL-3117/ Fix spacing issue inside Compare Accounts Modal for demo

packages/wallets/src/features/cfd/screens/CompareAccounts/CompareAccountsScreen.scss, packages/wallets/src/routes/CompareAccountsRoute/CompareAccountsRoute.scss
- Added a `max-width` for the CompareAccounts container similar to production.
=> [WALL] Aizad/WALL-3110/Compare Accounts Container Fix

packages/shared/src/utils/helpers/format-response.ts
There are few IDV errors may come from IDV provider which are not handled on FE side.
The code should execute default 'failed' scenario.
Fixing here the error of reading the property on not exiting object.
=> [COJ]/evgeniy/coj-423/fix handling unusual IDV errors

packages/trader/src/App/Containers/__tests__/populate-header.spec.tsx, packages/trader/src/App/Containers/__tests__/trade-header-extensions.spec.tsx
=> [DTRA] henry/webrel-54/fix: test coverage for portfolio component in the header

packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/__tests__/local.spec.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/local.tsx
Added test case for local component under dashboard component load bot preview folder
=> [BOT] Farabi/bot-971/test-case-for-local-component 

packages/tradershub/src/App.tsx
1. Add breakpointprovider to have access to isMobile, isDesktop and isTablet from @deriv/quill-design
=> thisyahlen/TRAH-2303/chore: add breakpointprovider for device flags

packages/api/src/hooks/p2p/useAdvertList.ts, packages/api/src/hooks/p2p/useOrderInfo.ts, packages/api/src/hooks/p2p/useOrderList.ts
- Created hook for p2p order information
- Changed return value for any instances of `is_recommended` as the null value represents the advertiser/client who have not been recommended yet.
- Changed tsdocs since the return value for some values are not 1 or 0 but boolean now. So removed any indication that it will return 1 or 0
=> [FEQ] Ameerul / FEQ-1004 / P2P Order Information Hook

packages/tradershub/src/components/Base/ButtonGroup/ButtonGroup.tsx, packages/tradershub/src/components/Base/ButtonGroup/index.ts
- [CU](https://app.clickup.com/t/86bwu60ud)
- In order to move other dxtrade components from wallets to tradershub, some custom wallets components are missing and N/A in quill so we are adding it in the tradershub Base component directory
N/A
=> [TRAH] shontzu/TRAH-2304/ButtonGroup-component-in-tradershub-package

packages/tradershub/src/components/ContentSwitcher/ContentHeaderList.tsx, packages/tradershub/src/components/ContentSwitcher/ContentPanelContainer.tsx, packages/tradershub/src/components/ContentSwitcher/ContentSwitcher.tsx, packages/tradershub/src/components/ContentSwitcher/ContentTabPanel.tsx, packages/tradershub/src/components/ContentSwitcher/index.ts, packages/tradershub/src/components/index.ts
- Created Content Switcher component for `Non-EU & EU` and `Options & CFD`.
- Use `tailwindcss` and `@deriv/quill-design` for stylings.
- added TSDocs for component info.
Figma Design:
The component:
=> [TRAH] Aizad/TRAH-2305/Content Switcher

packages/wallets/src/components/Base/WalletTextField/WalletTextField.tsx, packages/wallets/src/components/Base/WalletTextField/__tests__/HelperMessage.spec.tsx, packages/wallets/src/components/Base/WalletTextField/__tests__/WalletTextField.spec.tsx
=> [WALL] Lubega /WALL-3053/ Chore: WalletTextField unit test

packages/api/src/hooks/p2p/__tests__/useAdvertiserAdverts.spec.tsx, packages/api/src/hooks/p2p/useAdvertiserAdverts.ts
- Creating new hook `useAdvertiserAdverts` to get the list of adverts under the current client
- Write test cases for the hook
=> [FEQ] Farhan/FEQ-993/P2P advertiser Adverts

packages/api/src/hooks/useCashierFiatAddress.ts
The iframe received Deposit-Fiat and Withdrawal-Fiat is in dark mode theme. As the theming is not yet done for the wallets project, we fix the iframe theme to light-mode.
=> [WALL] aum/WALL-3128/fix-light-mode-DF-iframe

packages/cashier/src/containers/routes/binary-routes.tsx
This is to prevent adding redundant p2p-v2 entries in cashier sidebar.
=> fix: to prevent add p2p-v2 route if it's already there

packages/api/src/hooks/useCryptoTransactions.ts, packages/wallets/src/features/cashier/modules/Transactions/Transactions.scss, packages/wallets/src/features/cashier/modules/Transactions/Transactions.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPending/TransactionsPending.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/TransactionsPendingRow.tsx
=> [WALL] [Fix] Rostislav / WALL-3134 & 3136 / Pending transactions UI issues

packages/cfd/src/Containers/mt5-migration-modal/__test__/mt5-migration-front-side-content.spec.tsx, packages/cfd/src/Containers/mt5-migration-modal/__test__/mt5-migration-modal-content.spec.tsx, packages/cfd/src/Containers/mt5-migration-modal/mt5-migration-front-side-content.tsx, packages/cfd/src/Containers/mt5-migration-modal/mt5-migration-modal-content.tsx, packages/cfd/src/Containers/mt5-migration-modal/mt5-migration-modal.scss, packages/cfd/src/Containers/mt5-migration-modal/mt5-migration-modal.tsx
Remove mt5-migration-back-side-content from mt5 migration pop up modal and update content in mt5-migration-front-side-content.
Figma design is as below:
https://www.figma.com/file/p3d3hK27vuQtA4BDhTjjpp/branch/rfB1heNl8v1aT5bwi0fGtM/Release-(Rebuild)---Low-risk-ROW-Trader%E2%80%99s-hub?type=design&node-id=502-240141&mode=design&t=XOZBkabLclXWAbxq-0
=> Suisin/chore: remove back-side-content from svg bvi migration

packages/core/src/App/Containers/AccountSignupModal/account-signup-modal.jsx, packages/core/src/App/Containers/QuestionnaireModal/__tests__/questionnaire-modal.spec.tsx, packages/core/src/App/Containers/QuestionnaireModal/index.ts, packages/core/src/App/Containers/QuestionnaireModal/questionnaire-modal.scss, packages/core/src/App/Containers/QuestionnaireModal/questionnaire-modal.tsx
Adding a user experience survey immediately after setting a password. 
`onSignupComplete` fn moved from creating password to choose an answer in new modal form about trader's experience. 
The questionnaire has 2 options taken from the Growthbook platform:
A: {
"question": "Which type of trading are you interested in?",
"id": 1,
"answers": [
{"code": "1_1", "text": "Not sure"},
{"code": "1_2", "text": "CFDs"},
{"code": "1_3", "text": "Options"},
{"code": "1_4", "text": "both"}
]
}
B: {
"question": "How would you rate your trading experience?",
"id": 1,
"answers": [
{"code": "1_1", "header": "Beginner:", "text": "I have no experience"},
{"code": "1_2", "header": "Intermediate:", "text": "I have basic skills"},
{"code": "1_3", "header": "Experienced:", "text": "I have advanced skills"}, …
=> [CRO] NikitK/CRO-357/Questionary adding by ab testing approach for new users right after email verification

packages/bot-web-ui/src/components/quick-strategy/selects/symbol.tsx
* fix: Reset the asset field to the previous value after an invalid search
When a user performs an invalid search on the Asset  field and moves away from the field without selecting anything, the previously saved value should be displayed.
https://github.com/binary-com/deriv-app/assets/103181650/6cec3228-587e-4311-9f53-444b47be4c68
=> [BOT]/Maryia/BOT-1141/fix: Reset the asset field to the previous value after an invalid search

packages/p2p/src/components/app-content.jsx, packages/p2p/src/components/cashier-under-maintenance/__tests__/cashier-under-maintentance.spec.tsx, packages/p2p/src/components/cashier-under-maintenance/cashier-under-maintenance.scss, packages/p2p/src/components/cashier-under-maintenance/cashier-under-maintenance.tsx, packages/p2p/src/components/cashier-under-maintenance/index.ts, packages/p2p/src/components/routes/routes.jsx
- Instead of using the `CashierLocked` component inside cashier package, opted to create our own since we don't need the extra checks for p2p.
- Added new component `CashierUnderMaintenance` which will be shown if cashier is under maintenance by checking the `useIsSystemMaintenance` hook. 
- Placed it above if the user is blocked as this takes higher precedence
- Added the hook in app-content in p2p to make sure the tabs and disclaimer modal dont show as it shows the cashier maintenance message
- Added test cases
https://github.com/binary-com/deriv-app/assets/103412909/601f0ecd-db06-4b91-8000-9d57e5f1205f
=> [P2PS] Ameerul / P2PS-1327 / Show "Cashier maintenance" in P2P when Cashier is down due to maintenance

packages/wallets/src/components/Base/WalletPasswordField/WalletPasswordField.tsx, packages/wallets/src/components/Base/WalletPasswordField/index.ts, packages/wallets/src/components/Base/WalletPasswordFieldLazy/WalletPasswordFieldLazy.tsx, packages/wallets/src/components/Base/WalletPasswordFieldLazy/index.ts, packages/wallets/src/components/Base/index.ts, packages/wallets/src/features/cfd/screens/ChangePassword/InvestorPassword/MT5ChangeInvestorPasswordInputsScreen.tsx, packages/wallets/src/features/cfd/screens/CreatePassword/CreatePassword.tsx, packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx, packages/wallets/src/utils/password.ts
Dynamic loading of zxcvbn library due to its size. Using react lazy.
Zxcvbn library is now loaded on demand, only when you actually display component with password field.
Looks like its pretty easy and re-usable pattern for anything, including onfido, gives loader for free and pretty much all the hassle/boilerplate of loading is abstracted away from developer.
As per discussions - ideally we should consider removing this library entirely.
No change - password field works as previously.
=>  [WALL] wojtek/WALL-3012/feat: dynamic load of zxcvbn library for password scoring

packages/p2p/src/pages/my-ads/create-ad-form.jsx, packages/p2p/src/pages/my-ads/edit-ad-form.jsx, packages/p2p/src/stores/my-ads-store.js
- Added `setFieldTouched` when user focuses on any of the input boxes because touched is only registered for onBlur event. Need to immediately set touched to true to get an immediate response.
- Removed if check if error object contains `Enter a valid amount.` string because it will override all the other errors if it exists in the object.
=> [P2PS] / Ameerul P2PS-2132 / Error message is not showing when enter invalid value for total amount, fixed rate, max, and min field

packages/cfd/src/Containers/cfd-compare-accounts/cfd-compare-accounts-button.tsx, packages/cfd/src/Helpers/compare-accounts-config.ts
1. Create Deriv account
2. Make POI and POA verified
3. Try to create MT5 BVI/DVL/Vanuatu from compare account table
Submit your proof of identity and address modal with the message "Your documents were submitted successfully" is shown before password prompt.
There shouldn't be any message shown when the account is already POI and POA verified. It should only show password prompt.
=> [CFDS] Hamza/CFDS-2816/Submit your POI and POA modal is showing incorrect modal

.github/actions/build/action.yml, .github/workflows/release_production.yml, .github/workflows/release_staging.yml, .github/workflows/release_test.yml, .github/workflows/release_uat.yml, packages/core/src/App/Containers/AccountSignupModal/account-signup-modal.jsx, packages/core/src/App/Containers/QuestionnaireModal/__tests__/questionnaire-modal.spec.tsx, packages/core/src/App/Containers/QuestionnaireModal/index.ts, packages/core/src/App/Containers/QuestionnaireModal/questionnaire-modal.scss, packages/core/src/App/Containers/QuestionnaireModal/questionnaire-modal.tsx
Adding a user experience survey immediately after setting a password.
onSignupComplete fn moved from creating password to choose an answer in new modal form about trader's experience.
The questionnaire has 2 options taken from the Growthbook platform:
A: {
"question": "Which type of trading are you interested in?",
"id": 1,
"answers": [
{"code": "1_1", "text": "Not sure"},
{"code": "1_2", "text": "CFDs"},
{"code": "1_3", "text": "Options"},
{"code": "1_4", "text": "both"}
]
}
B: {
"question": "How would you rate your trading experience?",
"id": 1,
"answers": [
{"code": "1_1", "header": "Beginner:", "text": "I have no experience"},
{"code": "1_2", "header": "Intermediate:", "text": "I have basic skills"},
{"code": "1_3", "header": "Experienced:", "text": "I have advanced skills"},
{"code": …
=> [CRO] NikitK/CRO-381/Questionary adding by ab testing approach for new users right after email verification

packages/tradershub/src/features/cfd/components/CTraderList/CTraderList.tsx, packages/tradershub/src/features/cfd/components/OtherCFDPlatformsList/OtherCFDPlatformsList.tsx, packages/tradershub/src/features/cfd/components/OtherCFDPlatformsList/index.ts, packages/tradershub/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx, packages/tradershub/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx, packages/tradershub/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.tsx, packages/tradershub/src/features/cfd/flows/OtherCFDs/Dxtrade/AvailableDxtradeAccountsList/AvailableDxtradeAccountsList.tsx, packages/tradershub/src/routes/TradersHubRoute/TradersHubRoute.tsx
- [CU](https://app.clickup.com/t/20696747/TRAH-2343)
=> [TRAH] shontzu/TRAH-2343/show-dxtrade-in-tradershub-rout4e

packages/account/src/Helpers/__tests__/utils.spec.tsx, packages/account/src/Helpers/utils.tsx
Render default config structure for IDV supported countries that dosen't have custom config on FE side. 
These countries will use data from API and render the IDV supported documents and the validation for the IDV document number
=> [COJ]/likhith/fix: added null check to return default config for IDV countries

packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/CryptoTransaction.scss
https://github.com/binary-com/deriv-app/assets/119863957/ff08cd3d-6e57-4859-8708-1845acc46103
=> [WALL] [Fix] Rostislav / Remove outline for cancel transaction button in `TransactionStatus` when ESC is pressed

packages/wallets/src/features/cashier/modules/WithdrawalCrypto/WithdrawalCrypto.scss
=> [WALL] [Fix] Rostislav / WALL-3161 / `TransactionStatus` in mobile withdrawal

packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormDropdown/TransferFormDropdown.tsx, packages/wallets/src/features/cashier/modules/Transfer/types/types.ts, packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx, packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/__tests__/AddedCTraderAccountsList.spec.tsx, packages/wallets/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.tsx
- Add account loginid to query param when redirecting from the account listing
- Set `toAccount` value if query param and account with given loginid exist
https://github.com/binary-com/deriv-app/assets/125247833/793599d5-0a26-4b9e-ab72-7f4bdc5d8245
=> [WALL] Farhan/WALL-3040/Not selected corresponding accounts in Transfer modal

packages/wallets/src/features/cfd/components/CompareAccountsCarousel/CompareAccountsCarouselButton.scss, packages/wallets/src/features/cfd/components/CompareAccountsCarousel/CompareAccountsCarouselButton.tsx
Change compare account arrow icon
=> [WALL] Farhan/WALL-3111/Arrow button in the Compare accounts modal is not same as in design

packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.tsx
Fix: Metatrader web option is not displayed on mobile
=> [WALL] Farhan/WALL-3067/Metatrader web option is not displayed on mobile

packages/tradershub/src/components/Modal/Modal.classnames.ts, packages/tradershub/src/components/Modal/Modal.tsx, packages/tradershub/src/components/Modal/ModalContent.tsx, packages/tradershub/src/components/Modal/ModalFooter.tsx, packages/tradershub/src/components/Modal/ModalHeader.tsx, packages/tradershub/src/components/Modal/index.ts, packages/tradershub/src/components/index.ts
- Refactored `ModalStepWrapper` to `Modal`.
- Adapt to Desktop and Mobile screens.
- Added TSDocs inside
=> [TRAH] Aizad/FEQ-1352/Refactoring Modal Step Wrapper

packages/wallets/src/components/Base/WalletAlertMessage/WalletAlertMessage.scss
The top and bottom of the message changed to 7 px for desktop and 9 px for mobile
The right gap between the message and icons changed to 4 px for both mobile and desktop
=> [WALL] Lubega / WALL-3187 / Fix: Transfer message padding update

packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/useTransferMessages.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/transferFeesBetweenWalletsMessageFn.ts, packages/wallets/src/features/cashier/modules/Transfer/types/types.ts
=> [WALL] Lubega / WALL-3188 / Fix: Transfer message source account

packages/core/src/Stores/client-store.js, packages/shared/src/utils/config/config.ts, packages/shared/src/utils/url/helpers.ts, packages/translations/src/i18next/i18next.ts
1. Fix an issue where if next_wallet is enabled, login redirection goes to appstore/traders_hub. its should go to /wallets
https://github.com/binary-com/deriv-app/assets/104053934/47ee640a-9aa6-4b8d-8e54-df2e5a4c7e9d
=> thisyahlen/WALL-2765/chore: fix wallet redirection issue if next_wallet flag is enabled upon login

packages/wallets/src/features/cashier/modules/DepositCrypto/DepositCrypto.scss
=> [WALL] Lubega / WALL-3137 / Fix: Transaction status mobile ui

packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/TransactionsCompletedRow.tsx
=> [WALL] Lubega / WALL-3173 / Fix: Transactions amount colour

packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.tsx
Change MT5 login id format in MT5 trade popup
=> [WALL] Farhan/WALL-3163/MT5 login id format in MT5 trade popup is different from the design

packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/__tests__/save-modal.spec.tsx
Added unit test case for save-modal in bot-web-ui
=> [Bot]test: add test case for save-modal in bot-web-ui

packages/wallets/src/features/cashier/modules/Transfer/components/TransferReceipt/TransferReceipt.tsx, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/transferFeesBetweenWalletsMessageFn.ts
1. 🐛 Fix the blue transfer fees message when the transfer is happening between `crypto-wallets`,
from: Fee: 0.00003200 LTC (2% transfer fee or 0.00000001 LTC, whichever is higher, applies for fund transfers between your `{{active_wallet_name}} Wallet and cryptocurrency Wallets`)
to: Fee: 0.00003200 LTC (2% transfer fee or 0.00000001 LTC, whichever is higher, applies for fund transfers between your `cryptocurrency Wallets`)
2. 🐛 Fixed the signs of the transferred amount in wallet-cards in the TransferReceipt screen.
=> [WALL]Aum/WALL-3189/fix blue message for transfer between crypto wallets

packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/transferFeesBetweenWalletsMessageFn.ts
=> [WALL] Lubega / WALL-3211 / Fix: Transfer message missing 'Wallet' in fiat transfer

packages/p2p/src/pages/buy-sell/buy-sell-form.scss
- changed the height to min-height to fix the issue of the text overlapping with other text inside of buy sell modal
=> [P2PS] / Ameerul P2PS-2176 / Overlap of buy modal when sellers instructions are too long (recurring bug)

packages/tradershub/src/features/cfd/components/CompareAccountsCarousel/CompareAccountsCarousel.tsx, packages/tradershub/src/features/cfd/components/CompareAccountsCarousel/CompareAccountsCarouselButton.tsx, packages/tradershub/src/features/cfd/components/CompareAccountsCarousel/index.ts
implement CompareAccountsCarousel inside TradersHub
=> [TRAH] Hamza / TRAH-2615 /Added Carousel component

packages/wallets/src/components/WalletCard/WalletCard.tsx, packages/wallets/src/components/WalletListCardBadge/WalletListCardBadge.tsx, packages/wallets/src/components/WalletListCardBadge/__tests__/WalletListCardBadge.spec.tsx
=> [WALL] george / WALL-3216 / The colour of the wallet name, the balance and the badge does not align with the design

packages/tradershub/src/features/cfd/screens/DynamicLeverage/DynamicLeverageTableColumnHeader.tsx
Added DynamicLeverageTableColumnHeader Component to Trader's Hub
CU: https://app.clickup.com/t/20696747/TRAH-2617
=> [TRAH] Arshad / TRAH-2617 / DynamicLeverageTableColumnHeader Component to Trader's Hub

packages/bot-web-ui/src/components/quick-strategy/quick-strategy.scss
fix: Responsive/ On Quick strategy modal, the dropdown in overlapping with the text
=> [BOT]/Maryia/WEBREL-1870/fix: Responsive/ On Quick strategy modal, the dropdown in overlapping with the text

packages/wallets/src/features/cashier/modules/Transfer/components/TransferReceipt/TransferReceipt.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferReceipt/TransferReceipt.tsx
- fix gap
- fix content (remove space in card balance)
=> [WALL] george / WALL-3220 / The padding size between cards in the success page does not align with design.(Mobile view)

packages/api/src/hooks/useCryptoTransactions.ts, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/TransactionsPendingRow.tsx
Fixing the following bugs for pending transactions in transactions tab for crypto-wallets:
1. Remove 0 from the end of the transaction status name.
2. Show confirmation count when the transaction status is upgraded from `In review` to `In process`.
=> [WALL] aum/bug-fixes-for-pending-transactions-tab

packages/core/src/Utils/Datadog/index.ts
This is to ensure that we are not running datadog session replay on the repo.
=> Ako/ remove datadog session replay

packages/wallets/src/components/Base/ATMAmountInput/ATMAmountInput.tsx, packages/wallets/src/features/cashier/WalletCashier.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountSelection/TransferFormAccountSelection.scss
- fix bouncing when scroll up/down on iPhone devices
- fix overlapping side navigation menu by dropdown transfer
bug:
https://github.com/binary-com/deriv-app/assets/103181646/d43b051a-7eb7-428e-b4cb-741eafa1582b
fix:
https://github.com/binary-com/deriv-app/assets/103181646/5bd6b503-b76f-4bb4-a3fb-b75dd52a2fee
Bug overlapping:
Fix overlapping
=> [WALL] george / WALL-3237 / Bouncing of the header when scrolling up and down on IPhone device

packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/useTransferMessages.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/transferFeesBetweenWalletsMessageFn.ts, packages/wallets/src/features/cashier/modules/Transfer/types/types.ts
🐛 Fix for transfer between wallets:
- Hide the blue message for transfer fees when a very small amount is entered for transfer as the amount will be rounded-off to zero for the opposite field after conversion.
- Disable the transfer button if the above scenario is encountered.
[](https://github.com/binary-com/deriv-app/assets/125039206/4e4a3f9f-858b-4bac-b9e1-e9dc760bab8a)
=> [WALL] Aum/WALL-3240/fix-transfer-blue-message-showing-for-small-amount

packages/account/src/Sections/Verification/ProofOfIdentity/onfido-sdk-view-container.tsx
=> fix: loading of onfido script upon component mount

packages/account/src/Components/poi/idv-document-submit/idv-document-submit.tsx
Incorrect status object prop was used to render the error message. This caused the error message not to be displayed for a certain error code.
Issue is resolved by fixing the status prop
=> [COJ]/likhith/fix: used correct prop to display error message

packages/tradershub/src/AppContent.tsx, packages/tradershub/src/components/CurrencySwitcher/CurrencySwitcher.tsx, packages/tradershub/src/components/Loaders/CurrencySwitcherLoader.tsx, packages/tradershub/src/components/Modal/Modal.tsx, packages/tradershub/src/components/Modal/ModalContent.tsx, packages/tradershub/src/components/TradingAccountsList/TradingAccountsList.tsx, packages/tradershub/src/routes/TradersHubRoute/TradersHubRoute.tsx
- added modal id inside of AppContent for responsive view
- change ModalStepWrapper to Modal
- change tailwind classes for Modal to accommodate responsive view
https://github.com/binary-com/deriv-app/assets/103104395/28123c1d-62ec-4199-b606-24245db8dc8b
=> [TRAH] Aizad/TRAH-2627/Currency Switcher Modal for responsive

packages/wallets/src/components/Base/WalletTextField/WalletTextField.scss, packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.scss
Before:
https://github.com/binary-com/deriv-app/assets/142860499/eaec6e49-eacd-4518-9253-99d145f38edc
After:
https://github.com/binary-com/deriv-app/assets/142860499/436ac9e3-59a2-4559-a7c4-6ae580c99896
=> [WALL] Lubega / WALL-3245 / Fix: Enter/create password modal ui issues

packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/TransactionsCompletedRow.tsx
=> [WALL] Lubega / WALL-3243 / Fix: Transactions CTrader completed transfer message

packages/account/src/Sections/Assessment/FinancialAssessment/financial-assessment.tsx
"Unemployed" option still showing in occupation list for Financial assessment in mobile.
So fixed the props used in the function
=> [WEBREL-1889]/likhith/fix: add required prop

packages/tradershub/src/components/CFDSection/CFDContent/CFDContent.tsx, packages/tradershub/src/components/TradersHubContent/TradersHubContent.tsx, packages/tradershub/src/components/TradersHubContent/index.ts, packages/tradershub/src/components/index.ts, packages/tradershub/src/routes/TradersHubRoute/TradersHubRoute.tsx
1. Dont show ctrader and derivx in eu countries
2. Show CFD section on top in eu countrues
https://github.com/binary-com/deriv-app/assets/104053934/aafe8dfe-1141-48c0-b4f9-11dac989df64
=> thisyahlen/TRAH-2664/chore: swap the order of cfd and deriv platform section and hide ctrader and derivx for eu

packages/tradershub/src/components/OptionsAndMultipliersSection/OptionsAndMultipliersContent/OptionsAndMultipliersContent.tsx, packages/tradershub/src/components/TradingAccountCard/TradingAccountCardComponent.tsx, packages/tradershub/src/components/TradingAccountCard/index.ts, packages/tradershub/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx, packages/tradershub/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.tsx, packages/tradershub/src/features/cfd/flows/OtherCFDs/Dxtrade/AvailableDxtradeAccountsList/AvailableDxtradeAccountsList.tsx
- Created a reusable component layout within the `TradingAccountCardComponent` and used across Options and Multipliers, MT5, Deriv X and CTrader accounts.
- Created a coral light button
- Fix alignment issues and some other minor tweaks
- All of the changes above supports different screen sizes
https://github.com/binary-com/deriv-app/assets/103104395/45d6a2e0-1794-4786-8924-16b10f1d3c50
=> [TRAH] Aizad/TRAH-2651/Trading App Card improvements

packages/cfd/src/Containers/__tests__/cfd-financial-stp-real-account-signup.spec.js, packages/cfd/src/Containers/cfd-dbvi-onboarding.tsx, packages/cfd/src/Containers/cfd-financial-stp-real-account-signup.tsx, packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-content-wrapper.tsx, packages/hooks/src/useIsAccountStatusPresent.ts, packages/shared/src/utils/cfd/cfd.ts
Changed the POA trigger condition used during MT5 account creation based on the below conditions
IDV verification status:
- IDV authenticated with POA scan - applicable for DBVI, DFX and DVL
- IDV authenticated with photo - applicable for DBVI
- IDV authenticated with address - applicable for DBVI
- IDV authenticated with photo + address - applicable for DBVI & DFX
=> [COJ]likhith/[COJ-210]/fix: changed condition for POA trigger based on jurisdiction

packages/cfd/src/features/Containers/__tests__/real-account-signup-verifications.spec.js, packages/cfd/src/features/Containers/real-account-signup-verifications.tsx
Fix the build issue that occured due to incorrect variables and dead code.
Occured due to duplicate component
=> fix: build issues in staging

packages/wallets/src/components/AccountsList/AccountsList.scss, packages/wallets/src/features/cfd/screens/CreatePassword/CreatePassword.tsx
Fix 1:
https://github.com/binary-com/deriv-app/assets/142860499/20d526c0-05be-4cea-bac8-73b2d45bde0c
Fix 2:
=> [WALL] Lubega / WALL-3265 / Fix: Blue border on ESC button click

packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
Figma reference:
Fix:
https://github.com/binary-com/deriv-app/assets/142860499/7b650247-3190-49c1-97a1-e5d7299bb296
=> [WALL] Lubega / WALL-3274 / Fix: Display hint message on invalid password input

packages/cfd/src/Containers/__tests__/cfd-financial-stp-real-account-signup.spec.js, packages/cfd/src/features/Containers/__tests__/real-account-signup-verifications.spec.js, packages/shared/src/utils/cfd/cfd.ts
For fully authenticated clients, POA is being asked upon creating MT5 regulated account
POA should not be asked when CR account is fully authenticated
=> [COJ]/likhith/WEBREL-1894/fix: poa trigger issue

package-lock.json
- There is an issue where the incorrect generated package-lock.json with the key `Linux-build-master-cache-07a6a705c020ca99227651a244f241dd22d2af64af3dd693979dabf27fbbc533` was pushed to `master` branch and is cached to all PR builds, causing all other workflows to reuse this failed cache
- Regenerated a new package-lock.json based on a new repository clone of `deriv-app` through `npm i && npm run bootstrap:dev`
=> fix: issue with package-lock caching

packages/account/src/Sections/Assessment/FinancialAssessment/__tests__/financial-assessment.spec.tsx, packages/account/src/Sections/Assessment/FinancialAssessment/financial-assessment.tsx
When Self-Employed or Unemployed is selected for Employment status, client is not able to save their Financial Information.
Fixed the validation condition used for form submission
=> [COJ]/likhith/coj-531/fix fianncial assessment form submission

packages/appstore/src/components/eu-disclaimer/eu-disclaimer.scss, packages/appstore/src/modules/traders-hub/traders-hub.scss
Fix height  for eu disclaimer for French
Before:
After:
=> [TRAH]/2663/Mahdiyeh: Fix: eu disclaimer for french

packages/library/src/providers/CFDProvider/CFDProvider.tsx, packages/tradershub/src/features/cfd/screens/MT5AccountType/MT5AccountType.tsx
1. Fix mt5 account type screen not showing in modal
=> thisyahlen/TRAH-2680/fix: mt5 account type screen not showing in modal

packages/api/src/hooks/useSortedMT5Accounts.ts, packages/tradershub/src/features/cfd/components/MT5PlatformsList/MT5PlatformsList.tsx, packages/tradershub/src/features/cfd/modals/MT5AccountTypeModal/MT5AccountTypeModal.tsx
1. mt5 get more button not launching jurisdicton modal 
2. cfd maltainvest is showing in non-eu section
=> thisyahlen/TRAH-2684/fix: mt5 get more button not launching jurisdicton modal and cfd maltainvest

packages/p2p/src/components/modal-manager/modals/my-profile-balance-modal/__tests__/my-profile-balance-modal.spec.tsx, packages/p2p/src/components/modal-manager/modals/my-profile-balance-modal/my-profile-balance-modal.scss, packages/p2p/src/components/modal-manager/modals/my-profile-balance-modal/my-profile-balance-modal.tsx
- updated the my-profile-balance-modal with the new description
=> [P2PS] / Ameerul / P2PS-2084 Improvise Deriv P2P Available Balance Information

packages/shared/src/utils/cfd/cfd.ts
For IDV supp. countries, if the IDV POI fails while the POA is submitted but still in pending status, when client attempt to create regulated MT5 account, Still asks for POA
So fixed the condition that will trigger POA for MT5 account creation
=> [COJ]/likhith/COJ-563/fix poa pending error on MT5

packages/wallets/src/features/cashier/modules/Transfer/components/TransferForm/TransferForm.tsx
If either of the transfer amount fields after conversion have 0 as its value, we disable the transfer button.
=> [WALL] aum/WALL-3340/disable-transfer-button-for-either-amounts-to-be-zero

packages/bot-web-ui/src/stores/google-drive-store.js
Handle Google Drive error response. Currently, if users cancel the sign-in flow, it is showing connected in the app.
- Added a response check to see if there is a token with no error, only then proceed to sign in the user.
=> fix: handle google drive error response

packages/api/src/hooks/useBalance.ts
Disabled balances refetching every 30s, as with new upcoming designs it won't be needed anyway, while at the moment its contributing to some of the bugs we have.
=> [WALL] wojtek/disabled refetching every 30s as it caused problems and to limit the possibility of race hazards 

packages/api/src/hooks/__tests__/useKycAuthStatus.spec.ts, packages/api/src/hooks/useKycAuthStatus.ts, packages/api/types.ts
Created a new hook that uses `useKycAuthStatus` API call.
This will replace usePOI hook as most of the business logic is moved to the BE which will control the POI and POA flow
=> feat: implemented useKycAuthStatus hook

packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAmountInput/TransferFormAmountInput.tsx
Fix the hiding of transfer blue message and disabling of the transfer button once the timer expires and target amount is not updated with the new exchange rate.
https://github.com/binary-com/deriv-app/assets/125039206/00ac5306-7902-4728-8806-12a3823f9ccf
=> [WALL] aum/WALL-3357/blue-transfer-disappear-and-button-disabled-wallets

packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowAccountDetails/TransactionsCompletedRowAccountDetails.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowTransferAccountDetails/TransactionsCompletedRowTransferAccountDetails.tsx
=> [WALL] [Fix] Rostislav / WALL-3320 / Transaction tab MT5 transactions name & badge

packages/wallets/src/components/Loader/Loader.tsx, packages/wallets/src/components/Loader/__tests__/Loader.spec.tsx, packages/wallets/src/features/cashier/modules/DepositFiat/__tests__/DepositFiat.spec.tsx, packages/wallets/src/features/cashier/modules/FiatOnRamp/components/FiatOnRampDisclaimer/__tests__/FiatOnRampDisclaimer.spec.tsx, packages/wallets/src/features/cashier/modules/TransactionStatus/__tests__/TransactionStatus.spec.tsx, packages/wallets/src/features/cashier/modules/WithdrawalFiat/__tests__/WithdrawalFiat.spec.tsx
=> [WALL] Lubega / WALL-2989 / TransactionStatus unit test

packages/wallets/src/components/Base/ATMAmountInput/ATMAmountInput.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferForm/TransferForm.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormDropdown/TransferFormDropdown.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormDropdown/TransferFormDropdown.tsx
=> [WALL] [Fix] Rostislav / WALL-3345 / Align transfer tab component size with Figma

packages/shared/src/utils/constants/poi-failure-codes.tsx, packages/shared/src/utils/helpers/__tests__/format-response.spec.ts, packages/shared/src/utils/helpers/format-response.ts
Display `DuplicateDocument` error message when error code is returned in response
=> feat: added error config for duplicate-doc

packages/trader/src/Stores/Modules/Trading/Helpers/__tests__/contract-type.spec.ts, packages/trader/src/Stores/Modules/Trading/Helpers/contract-type.ts, packages/trader/src/Stores/Modules/Trading/trade-store.ts, packages/trader/src/sass/app/_common/components/number-selector.scss, packages/trader/src/sass/app/modules/trading.scss
This change addresses an issue where the accumulators' growth rate fails to update correctly after a refresh. The previous implementation did not properly handle the recalculation of growth rates following a refresh action, leading to inaccurate or stagnant values in the accumulators. This fix ensures that the growth rate is appropriately updated, maintaining the integrity and accuracy of the accumulators' data. Users can now rely on the system to reflect real-time changes in growth rates, providing a more reliable and consistent experience when working with accumulators.
=> Akmal / fix: accumulators growth rate is not being updated after refresh

packages/tradershub/src/components/Dialog/DialogHeader.tsx, packages/tradershub/src/components/GetADerivAccountBanner/GetADerivAccountDialog.tsx, packages/tradershub/src/components/GetADerivAccountBanner/index.ts
- **You Need A Deriv Account** dialog  ([CU](https://app.clickup.com/t/20696747/TRAH-2644))
- extended `DialogHeader` component to have more than one type of heading and default it as H3
=> [TRAH] shontzu/TRAH-2644/you-need-a-deriv-account-dialog

packages/p2p/src/components/add-payment-method-form/add-payment-method-form.scss, packages/p2p/src/pages/my-ads/edit-ad-form.scss, packages/p2p/src/pages/my-profile/payment-methods/edit-payment-method-form/edit-payment-method-form.scss
- made the error field unset as it was floating in the div itself
=> [P2PS] / Ameerul / P2PS-2277 Error message for instruction field is overlapping with the textbox

packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/CryptoTransaction.tsx
(including desktop as well just to show that the changes don't break that)
https://github.com/binary-com/deriv-app/assets/119863957/7e659da6-91e9-4033-86f3-18153bcfd39b
https://github.com/binary-com/deriv-app/assets/119863957/b08c64a3-1143-4139-b51e-a9d9440fe184
=> [WALL] [Fix] Rostislav / WALL-3368 / Address mobile `TransactionStatus` inconsistencies

packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/cumulativeAccountLimitsMessageFn.ts
https://github.com/binary-com/deriv-app/assets/119863957/6101b778-8d96-4c2d-aaa6-3e9f6206891c
=> [WALL] [Fix] Rostislav / WALL-3380 & WALL-3381 / Fix daily limits messages values conversion

packages/wallets/src/features/cashier/modules/TransactionStatus/components/TransactionStatusSuccess/TransactionStatusSuccess.tsx
code changes are too self-explanatory for this 👀
=> [WALL] [Fix] Rostislav / WALL-3387 / Fix navigating from `TransactionStatus` to transactions tab

packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.tsx
Got two error messages for the Duplicate File upload error in MT5 account creation page. 
Remove the message in the footer
=> fix: updated mt5 account error message display

packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/CryptoTransaction.scss, packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/CryptoTransaction.tsx
https://github.com/binary-com/deriv-app/assets/119863957/df09cb03-4b55-4c9d-b2d4-b9161a988cfd
=> [WALL] [Fix] Rostislav / WALL-3389 / Align `TransactionStatus` "Cancel transaction" button on mobile with Figma

packages/tradershub/src/components/ActionScreen/ActionScreen.tsx, packages/tradershub/src/components/SentEmailContent/SentEmailContent.tsx, packages/tradershub/src/components/Tooltip/Tooltip.tsx, packages/tradershub/src/components/TradingAccountCard/TradingAccountCard.tsx, packages/tradershub/src/features/cfd/screens/CFDSuccess/CFDSuccess.tsx, packages/tradershub/src/features/cfd/screens/CreatePassword/CreatePassword.tsx, packages/tradershub/src/features/cfd/screens/EnterPassword/EnterPassword.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardVerificationTag.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionTncSection/JurisdictionTncSection.tsx, packages/tradershub/src/features/cfd/screens/MT5AccountType/MT5AccountType.tsx, packages/tradershub/src/features/cfd/screens/MT5AccountTypeCard/MT5AccountTypeCard.tsx, packages/tradershub/src/modals/RegulationModal/Row.tsx
- based on a slack discussion [here](https://deriv-group.slack.com/archives/C054SHJDZJP/p1706593314460919) we have decided to follow one convention to name our types 
- `TComponentName` format is easier to identify if there's any type error because the name is unique to that file/component
- no more `TProps` or `FC` in TH package
=> [TRAH] shontzu/TRAH-2704/Rename-TProps

packages/bot-web-ui/src/components/trading-view-chart/trading-view.tsx, packages/bot-web-ui/src/pages/bot-builder/toolbar/workspace-group.tsx
Trading view chart section should remain white even on dark theme
=> [WEBREL] Farabi/webrel-2310/trading view section should have light theme

packages/cashier/src/containers/cashier/cashier.scss, packages/cashier/src/pages/account-transfer/account-transfer.tsx, packages/cashier/src/pages/on-ramp/on-ramp.tsx, packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer.tsx, packages/cashier/src/pages/payment-agent/payment-agent.tsx
- fix cashier locked message alignment in PA, Account transfer, PA Transfer, FiatOnRamp
=> [WALL] george / WALL-3289 / Cashier Locked message is not aligned properly in transfer page

packages/appstore/src/components/containers/currency-switcher-container.tsx, packages/appstore/src/components/currency-switcher-card/real/real-account-card.tsx, packages/core/src/App/Containers/CurrencySelectionModal/curreny-selection-modal.tsx, packages/core/src/App/Containers/RealAccountSignup/set-currency.jsx
- Change the icon for not assigned currency
- Fixed infinite reloading when user wants to set the currency
- Removed the balance from currency switcher in the traders hub page  
=> [COJ]/Mahdiyeh/338/fix: no assigned currency

packages/p2p/src/pages/app.jsx, packages/p2p/src/pages/app.scss
- added className to Loading component and changed the styling of the height
=> [P2PS] / Ameerul / P2PS-2322 Loading icon in the p2p cashier is shifted to the right of the screen

packages/bot-web-ui/src/pages/bot-builder/quick-strategy/config.ts
- Fixed incorrect tooltips for reverse martingale and reverse d'alembert strategy on quick strategy modal
- Size field for reverse martingale strategy
- Unit field for reverse d'alembert strategy
=> [BOT] Farabi/bot-1290/fix incorrect tooltips on quick strategy modal

packages/p2p-v2/src/components/PaymentMethodsFormFooter/PaymentMethodsFormFooter.tsx, packages/p2p-v2/src/components/PaymentMethodsFormFooter/__tests__/PaymentMethodsFormFooter.spec.tsx
- Add test cases form `PaymentMethodFormFooter` component
=> [FEQ]Jim/FEQ-1646/add test cases for payment method form footer component

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
update deriv-charts version to 2.0.4
------------------------------------------------------------------------------------------------
=> [DTRA]/update deriv-charts version to 2.0.4

packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
The problem was we send mt5 account creation before trading_platform_password_change give us back the response. Use mutateAsync and await for that fix this issue.
=> [WALL] Farhan/WALL-3399/Add MT5 account fails on the first attempt

packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/TransactionsPendingRow.tsx
=> [WALL] Lubega / WALL-3261 / Transactions GMT time display

packages/bot-web-ui/src/components/download/__tests__/download.spec.tsx
Added test case for download component
=> [BOT] Farabi/bot-1021/test coverage for download component

packages/p2p/src/components/composite-calendar/composite-calendar.tsx, packages/p2p/src/pages/orders/chat/__tests__/chat-messages.spec.jsx, packages/p2p/src/pages/orders/chat/chat-messages.jsx, packages/p2p/src/utils/chat-message.ts
- Moved the array into the composite calendar component because when you call localize outside of a component, it doesn't have access to the current locale or the translation messages.
- Due to this discovery, I also fixed the issue with the admin message, as initially the translation wasn't working, but when I move the string to the component itself, it is fixed (after changing the string a little bit and changing the crc32 value). So translation team need to change the text again and it should work
=> [P2PS] / Ameerul / P2PS-2214 Date filters selection in past order tab is not translated to other languages

packages/core/src/public/.well-known/apple-app-site-association
Added the `/redirect` path to open the p2p mobile application via a link to reset the password.
=> [P2PS] farrah/P2PS-2302/fix: ios redirection

packages/account/src/Components/self-exclusion/__tests__/self-exclusion-article-content.spec.tsx, packages/account/src/Components/self-exclusion/self-exclusion-article-content.tsx
Change Self Exclusion Content message to follow the document: https://docs.google.com/document/d/1laQxwr-u7IDZu5h7nRlGjYKd37Wjgq0JhDwHZpSZ0Ig/edit
ROW Users
EU Users
=> [UPM-611] Suisin/upm611/change self exclusion learn more content

packages/bot-web-ui/src/components/trading-view-chart/trading-view-modal.tsx
Trading view chart modal is getting stuck at the top left corner upon dragging.
- The previously added boundary class was removed
- Newly named boundary class is added for the draggable boundary
=> [BOT] fix: Trading view chart drag issue
