deriv-com/deriv-app

packages/account/src/Sections/Security/Passwords/deriv-password.jsx, packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-submission-for-mt5.jsx, packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-submission.jsx, packages/core/src/App/Containers/RealAccountSignup/account-wizard.jsx
This PR is to remove `/* eslint-disable react-hooks/exhaustive-deps */` from a couple of components to make sure all developers will get ESLint issues in their local machine and won't push them to master.
=> Matin / Remove ESLint Ignore

packages/appstore/src/components/cfds-listing/__tests__/index.spec.tsx
=> fix: circle ci error

packages/bot-web-ui/src/utils/gtm.js
=> fix: gtm issue

packages/p2p/src/components/advertiser-page/__tests__/advertiser-page.spec.jsx, packages/p2p/src/components/advertiser-page/advertiser-page.jsx, packages/p2p/src/components/buy-sell/__tests__/buy-sell.spec.jsx, packages/p2p/src/components/buy-sell/buy-sell.jsx, packages/p2p/src/components/my-ads/my-ads.jsx, packages/p2p/src/components/my-profile/my-profile.jsx, packages/p2p/src/components/orders/orders.jsx, packages/p2p/src/stores/general-store.js
Fix issue where nickname submission redirects user to buy sell page instead of staying on verification.
=> fix: registration flow in buy/sell tab

packages/bot-web-ui/src/app/__tests__/dbot-providers.spec.tsx, packages/bot-web-ui/src/utils/mock/index.js, packages/bot-web-ui/src/utils/mock/ws-mock.js
=> chore: test case for dbot-providers

packages/p2p/src/components/orders/__test__/orders.spec.js
- fixed failing orders test cases
=> Ameerul /WEBREL-1098 Fix codecov and circleci issues

.github/CODEOWNERS
=> maryia/chore: update codeowners file

packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.tsx, packages/cashier/src/pages/account-transfer/account-transfer.tsx, packages/cashier/src/pages/on-ramp/on-ramp.tsx, packages/cashier/src/pages/payment-agent/payment-agent-list/payment-agent-list.tsx, packages/cashier/src/pages/payment-agent/payment-agent.tsx, packages/cashier/src/pages/withdrawal/withdrawal.tsx
=> Farzin/WEBREL-1097/Unable to access CFD-DerivX transfer - hitting server error.

packages/cashier/src/pages/payment-agent/payment-agent-container/payment-agent-container.tsx, packages/cashier/src/stores/general-store.ts, packages/cashier/src/stores/payment-agent-store.ts
=> fix: 🐛  Farzin/Aum/WEBREL-1102/pa-withdrawal-redirection-fix

packages/cashier/src/pages/withdrawal/withdrawal.tsx, packages/components/src/components/vertical-tab/vertical-tab.scss
=> Rostislav / WEBREL-1106, WEBREL-1107 / Cashier withdrawal tab fixes for crypto

packages/appstore/src/modules/wallets/wallets.tsx
=> Remove duplicate ThemeScrollbars

package-lock.json, packages/api/package.json, packages/api/src/useAuthorize.ts, packages/utils/package.json, packages/utils/src/__tests__/getAccountsFromLocalStorage.spec.ts, packages/utils/src/__tests__/getActiveAuthTokenIDFromLocalStorage.spec.ts, packages/utils/src/__tests__/getActiveLoginIDFromLocalStorage.spec.ts, packages/utils/src/getAccountsFromLocalStorage.ts, packages/utils/src/getActiveAuthTokenIDFromLocalStorage.ts, packages/utils/src/getActiveLoginIDFromLocalStorage.ts, packages/utils/src/index.ts
- Hook contributed from https://github.com/binary-com/deriv-app/pull/9579
=> Adrienne / Added use-authorize hook to API package

packages/api/src/hooks/useAccountsList.ts
Add balance to each account in the useAccountsList hook
=> thisyahlen/chore: add balance to useAccountlist

package-lock.json, packages/account/package.json, packages/api/package.json, packages/api/src/hooks/index.ts, packages/api/src/hooks/useMT5LoginList.ts, packages/appstore/package.json, packages/cashier/package.json, packages/cfd/package.json, packages/p2p/package.json, packages/shared/package.json, packages/stores/package.json, packages/utils/package.json
=> thisyahlen/chore: add useMT5LoginList to deriv/api

packages/cashier/src/pages/account-transfer/__tests__/account-transfer.spec.tsx, packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.tsx, packages/cashier/src/pages/account-transfer/account-transfer.tsx, packages/cashier/src/pages/withdrawal/withdrawal.tsx
=> Farzin/WALL-1628/Side Note issue on staging environment

packages/bot-web-ui/src/components/dashboard/bot-builder/toolbox/__tests__/search-icon.spec.tsx, packages/bot-web-ui/src/components/dashboard/bot-builder/toolbox/search-box/search-icon.tsx
=> Maryia/BOT-538/test: search-icon

packages/bot-web-ui/src/components/dashboard/dashboard-component/__tests__/run-strategy.spec.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/run-strategy.tsx
=> Maryia/BOT-537/test: RunStrategy

packages/bot-web-ui/src/components/audio/__tests__/audio.spec.tsx, packages/bot-web-ui/src/components/bot-notification-messages/__tests__/bot-notification-messages.spec.tsx, packages/bot-web-ui/src/components/bot-notification-messages/bot-notification-messages.tsx
=> Vinu/test: add test case for bot-notification-messages component

packages/core/src/App/Containers/RealAccountSignup/account-wizard.jsx
Fix request payload for creation of Real account for Non-IDV supporting countries
=> likhith/fix: sending empty payload to non idv countries

packages/core/src/Stores/client-store.js, packages/core/src/Stores/traders-hub-store.js, packages/shared/src/utils/config/config.ts
=> thisyahlen/chore: update wallet loginids

packages/bot-web-ui/src/components/chart/__tests__/toolbar-widgets.spec.tsx
=> Shafin/bot 531/chore  toolbar widget test

packages/bot-web-ui/src/components/contract-card-loading/__tests__/contract-card-loading.spec.tsx, packages/bot-web-ui/src/components/contract-card-loading/contract-card-loading.tsx
=> chore: contract card loading tests

packages/bot-web-ui/src/components/contract-result-overlay/contract-result-overlay.spec.tsx
=> Farabi/bot 533/contract result overlay test case

packages/components/src/components/dropdown/dropdown.scss, packages/trader/src/sass/app/modules/trading.scss
=> henry/webrel-1160/hotfix: space issue dropdown

packages/wallets/src/AppContent.tsx, packages/wallets/src/app-content.scss, packages/wallets/src/components/WalletList/WalletList.scss, packages/wallets/src/components/WalletList/WalletList.tsx
=> fix: overwritten styles

packages/p2p/src/components/buy-sell/buy-sell-header.scss, packages/p2p/src/components/buy-sell/currency-dropdown.scss, packages/p2p/src/components/buy-sell/sort-dropdown.scss
- Added important to margin as it was being overriden by the changes in dropdown.scss file
=> Ameerul /WEBREL-1159 Sort by column alignment in P2P Buy/Sell page is off

.circleci/config.yml
* ci: remove k8s workflow
* ci: remove docker build and  push workflow
=> Ako/remove docker k8s config (#9933)

packages/appstore/src/components/containers/trading-app-card.scss, packages/components/src/index.ts
=> george / CFD accounts and Options broken markup, appstore build failed

packages/appstore/src/components/onboarding-new/static-dashboard.tsx, packages/appstore/src/components/options-multipliers-listing/index.tsx
- The "market price movements" should "market movements" under options and multipliers
=> Mahdiyeh/fix: change market price movements to market movements

packages/components/src/components/mobile-drawer/mobile-drawer.scss
=> chore: updated z-index for language switcher

packages/bot-skeleton/src/scratch/utils/index.js, packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/constants.ts, packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/delete-dialog.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/recent-workspace.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/save-modal.tsx, packages/bot-web-ui/src/components/dashboard/dashboard.tsx, packages/bot-web-ui/src/components/dashboard/hooks/useComponentVisibility.tsx, packages/bot-web-ui/src/stores/load-modal-store.ts, packages/bot-web-ui/src/stores/quick-strategy-store.ts, packages/bot-web-ui/src/stores/save-modal-store.ts, packages/bot-web-ui/src/stores/toolbar-store.ts, packages/bot-web-ui/src/types/index.ts, packages/bot-web-ui/src/types/strategy.types.ts, packages/bot-web-ui/src/utils/dom-observer.ts, packages/bot-web-ui/src/utils/gtm.js, types/blockly.d.ts, types/global.d.ts
=> Shafin/bot 301/fix  preview delete save edit issue

packages/bot-skeleton/src/scratch/blocks/Binary/Trade Definition/trade_definition_tradetype.js, packages/bot-skeleton/src/scratch/dbot.js, packages/bot-skeleton/src/services/api/ticks_service.js, packages/bot-skeleton/src/services/tradeEngine/trade/Balance.js, packages/bot-skeleton/src/services/tradeEngine/trade/OpenContract.js, packages/bot-skeleton/src/services/tradeEngine/trade/Proposal.js, packages/bot-skeleton/src/services/tradeEngine/trade/Ticks.js, packages/bot-skeleton/src/services/tradeEngine/trade/index.js, packages/bot-skeleton/src/services/tradeEngine/utils/interpreter.js, packages/bot-web-ui/src/stores/run-panel-store.js
ticks_history call is made when symbol change and not on run button click
=> Vinu/bot 92/ticks history refactor

packages/bot-web-ui/src/stores/dashboard-store.ts
- Tour test cases failed on Circle CI as it was not getting Blockly reference. 
- Added window.Blockly as Blockly is initialized to the window object.
=> fix: test case for tour

packages/bot-web-ui/src/components/dashboard/tour-guide.tsx
Fixed onboarding wrapper not working on small screens
=> fix: onboarding tour for mobile

packages/components/src/components/wallet-card/wallet-card.tsx, packages/core/src/App/Components/dev-tools/mock-dialog.scss, packages/core/src/App/Components/dev-tools/mock-dialog.tsx, packages/hooks/src/__tests__/useAvailableWallets.spec.tsx, packages/hooks/src/useAuthorize.ts, packages/hooks/src/useWalletTransactions.ts, packages/shared/src/styles/constants.scss
Fixed review comments and sonar cloud code smells in feature/wallets_with_traders_hub
No visual change
=> Fix Review Comments Wallets Feature branch

packages/api/src/hooks/useVerifyEmail.ts, packages/hooks/src/useVerifyEmail.ts
=> thisyahlen/chore: add useverifyemail hook to api package

packages/appstore/src/components/wallet-cards-carousel/cards-slider-swiper.tsx
Add function to event 'settle' of carousel
=> Sergei / wall - 1817 / fix wallet carousel

packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.tsx, packages/wallets/src/components/ProgressBar/ProgressBar.tsx, packages/wallets/src/components/WalletListCardIActions/WalletListCardIActions.tsx, packages/wallets/src/components/WalletsAccordionContainer/WalletsAccordionContainer.tsx, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
=> FarhanNurzi/ (Clean-up) Array.map keys

packages/appstore/src/components/onboarding-new/static-dashboard.tsx
=> Hirad/ fixed the cTrader australia issue

packages/wallets/src/components/CTraderList/CTraderList.scss, packages/wallets/src/components/CTraderList/CTraderList.tsx, packages/wallets/src/components/MT5List/MT5List.scss, packages/wallets/src/components/MT5List/MT5List.tsx, packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.scss, packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.tsx, packages/wallets/src/components/OtherCFDPlatformsList/OtherCFDPlatformsList.scss, packages/wallets/src/components/OtherCFDPlatformsList/OtherCFDPlatformsList.tsx, packages/wallets/src/components/PrimaryActionButton/PrimaryActionButton.scss, packages/wallets/src/components/TradingAccountCard/TradingAccountCard.tsx
=> thisyahlen/chore: refactor tradingaccountcard

packages/cfd/src/Helpers/constants.ts
Update the link for cTrader Windows app.
=> Hamza/ hotfix: update the ctrader windows url

packages/p2p/src/pages/orders/chat/chat-footer.scss
Fixed the alignment of attachment button and message counter. 
=> farrah/WEBREL-1254/fix: chat footer alignment

packages/p2p/scripts/extract-string.js
Added ts and tsx files when extracting strings for translation.
=> farrah/ fix: extracting of translation strings

packages/api/src/hooks/index.ts, packages/api/src/hooks/useCreateOtherCFDAccount.ts, packages/api/src/hooks/useCtraderAccountsList.ts, packages/api/src/hooks/useCtraderServiceToken.ts, packages/api/types.ts
Added service Token for Ctrader Accounts in the Account List
=> Hamza/ chore: added service token for cTrader

packages/p2p/src/components/modal-manager/modals/quick-add-modal/quick-add-modal.jsx
Reverts binary-com/deriv-app#10150
=> Revert "Ameerul /WEBREL-1255 Created payment method is not reflected from Add payment methods model for SELL ads"

packages/appstore/src/components/cfds-listing/index.tsx, packages/appstore/src/components/modals/real-wallets-upgrade/components/modal-elements/desktop-real-wallets-upgrade.tsx, packages/appstore/src/components/wallet-content/__tests__/wallet-transfer-block.spec.tsx, packages/components/src/components/modal/modal.tsx
=> georege / fix circle ci errors, fix modal header visibility

packages/appstore/src/components/wallet-cards-carousel/cards-slider-swiper.tsx, packages/appstore/src/components/wallet-content/wallet-cfds-listing.tsx, packages/appstore/src/components/wallet-content/wallet-content.tsx, packages/appstore/src/components/wallet-header/wallet-currency-card.tsx, packages/appstore/src/components/wallet-header/wallet-header-buttons.tsx, packages/appstore/src/modules/wallets/mobile-wallets-carousel.tsx, packages/core/src/sass/app/_common/components/wallet.scss
=> Rostislav / Wallets feature branch refactors

packages/appstore/src/components/add-more-wallets/__test__/add-more-wallets.spec.tsx, packages/appstore/src/components/add-more-wallets/wallet-add-card.tsx, packages/appstore/src/components/containers/currency-switcher-container.tsx, packages/appstore/src/components/main-title-bar/__tests__/index.spec.tsx
Code Refactoring, add Localize, refactor types.
=> Wallet feature branch fixes 

packages/bot-web-ui/src/components/dashboard/bot-builder/toolbox/toolbox.scss, packages/bot-web-ui/src/components/dashboard/bot-builder/toolbox/toolbox.tsx
Add an indicator for the active tab in the flyout menu for blocks.
=> chore: add indicator for selected block in flyout

packages/bot-skeleton/src/services/tradeEngine/trade/index.js
fixed the issue where accountInfo is undefined when getTotalRun function is called.
=> Vinu: fix: fixed the issue where accountinfo is undefined.

packages/p2p/src/stores/advertiser-page-store.js, packages/p2p/src/stores/buy-sell-store.js, packages/p2p/src/stores/general-store.js, packages/p2p/src/stores/my-ads-store.js, packages/p2p/src/stores/my-profile-store.js, packages/p2p/src/stores/order-details-store.js
removed unused functions and observables in store
=> refactor: remove unused functions in store

packages/account/src/Components/poi/poi-confirm-with-example-form-container/__tests__/poi-confirm-with-example-form-container.spec.tsx, packages/account/src/Components/poi/poi-confirm-with-example-form-container/poi-confirm-with-example-form-container.tsx
Resolved issue of re-initialize of names due to re-render
=> fix: :bug: fixed re-render-issue

packages/appstore/src/components/onboarding-new/static-cfd-account-manager.scss, packages/appstore/src/components/onboarding-new/static-cfd-account-manager.tsx
Fixed Trader's hub Onboarding get button animation speed.
=> Arshad / WALL-1766 /  Trader's hub onboarding get button animation

packages/appstore/src/constants/routes-config.ts, packages/core/src/App/Constants/routes-config.js
=> fix: change document title for trader's hub

packages/wallets/src/components/AccountsList/AccountsList.tsx, packages/wallets/src/components/ExternalTradingPlatforms/CFDPlatformsList/CFDPlatformsList.scss, packages/wallets/src/components/ExternalTradingPlatforms/CFDPlatformsList/CFDPlatformsList.tsx, packages/wallets/src/components/ExternalTradingPlatforms/CTraderList/CTraderList.scss, packages/wallets/src/components/ExternalTradingPlatforms/MT5PlatformsList/MT5PlatformsList.scss, packages/wallets/src/components/ExternalTradingPlatforms/OtherCFDPlatformsList/OtherCFDPlatformsList.scss, packages/wallets/src/components/Tabs/TabList.scss, packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.scss
=> thisyahlen/chore: add cfd section for responsive and fix general styling

packages/wallets/src/components/ExternalTradingPlatforms/AddedMT5AccountsList/AddedMT5AccountsList.scss, packages/wallets/src/components/ExternalTradingPlatforms/AddedMT5AccountsList/AddedMT5AccountsList.tsx
=> thisyahlen/chore: add landing company badge to mt5 accounts

packages/api/src/hooks/index.ts, packages/api/src/hooks/useDerivezAccountsList.ts, packages/api/src/hooks/useDerivezServiceToken.ts
=> Hamza/chore: added pandats service token

packages/account/src/Containers/Account/page-overlay-wrapper.tsx
=> likhith/fix: resolved routing

packages/account/src/Components/currency-selector/radio-button.tsx, packages/api/src/hooks/usePOIStatus.ts
=> yashim/fix: radio button

packages/wallets/.stylelintrc.js
=> thisyahlen/chore: add stylelint for wallets

packages/core/src/App/Containers/Layout/header/dtrader-header.jsx, packages/core/src/Stores/notification-store.js, packages/hooks/src/useWalletMigration.ts
- Move logic to add notifications in `DTraderHeader` component
- Add `useAuthorize` inside of the `useWalletMigration` to activate `Tanstack useQuery` to pass check from `isAuthorized` function
=> Sergei / feq 740 / wallet migration notifications by default

packages/cfd/src/Containers/cfd-top-up-demo-modal.tsx
=> fix: top up modal height issue

packages/trader/src/sass/app/modules/trading.scss
=> henry/dtra-284/fix: move input text

packages/wallets/src/components/JurisdictionModal/JurisdictionModal.scss, packages/wallets/src/components/JurisdictionModal/JurisdictionModal.tsx, packages/wallets/src/components/JurisdictionModal/index.ts, packages/wallets/src/components/WideWrapper/WideWrapper.scss, packages/wallets/src/components/WideWrapper/WideWrapper.tsx, packages/wallets/src/components/WideWrapper/index.ts
=> adrienne / added wide wrapper for jurisdiction modal

packages/components/src/components/dropdown/dropdown.scss
=> Kate / DTRA-406 / margin of the dropdown for stake

packages/trader/src/Modules/Trading/Components/Form/TradeParams/__tests__/min-max-stake-info.spec.tsx
=> sergei / fix fb1 test for min-max-stake

packages/cfd/src/Components/__tests__/cfd-dxtrade-demo-account-display.spec.tsx
=> Kate / DTRA-130 / Test coverage: cfd-dxtrade-demo-account-display.tsx in CFD package

packages/trader/src/Modules/Trading/Components/Form/TradeParams/amount.jsx
=> Kate / DTRA-431 / [Bug] Min and Max Stake info is not rendered in desktop

packages/core/src/App/Containers/RealAccountSignup/__tests__/real-account-signup.spec.jsx, packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx
=> Amina/fix: mf_account_signup

packages/cfd/src/Containers/cfd-top-up-demo-modal.tsx, packages/components/src/components/modal/modal.tsx
remove unnecessary modal min height param
=> Remove unnecessary modal min height param

packages/bot-skeleton/src/services/api/api-middleware.js
fix: Console error on multipliers when using invalid stop loss amount
=> Maryia/BOT-483/fix: Console error on multipliers when using invalid stop loss amount

packages/account/src/Components/address-details/__tests__/address-details.spec.tsx, packages/account/src/Components/address-details/address-details.tsx
=> Amina/fix: state loader in address detail component

packages/trader/src/Modules/Trading/Components/Elements/__tests__/purchase-button.spec.tsx, packages/trader/src/Modules/Trading/Components/Elements/__tests__/purchase-fieldset.spec.tsx, packages/trader/src/Modules/Trading/Containers/__tests__/purchase.spec.tsx
- Add unit tests for: _src/Modules/Trading/Containers/purchase.jsx_, _src/Modules/Trading/Components/Elements/purchase-button.jsx_, _src/Modules/Trading/Components/Elements/purchase-fieldset.jsx_ files
=> Kate / WEBREL-68 / Test coverage: Purchase files in Trader package

packages/wallets/.eslintrc.js, packages/wallets/src/components/MT5AccountTypeModal/MT5AccountTypeModal.tsx, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx, packages/wallets/tsconfig.json
Reverts binary-com/deriv-app#10380
=> Revert "Thisyahlen/new eslint rules"

packages/trader/src/Modules/Trading/Components/Elements/__tests__/purchase-button.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/__tests__/form-layout.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/__tests__/screen-large.spec.tsx, packages/trader/src/Modules/Trading/Containers/__tests__/purchase.spec.tsx
=> henry/dtra-434/fix: failing test cases on master

packages/wallets/src/components/CreatePassword/CreatePassword.tsx, packages/wallets/src/components/WalletsAccordion/WalletsAccordion.tsx
1. Removed unnecessary bracket
2. Hide arrow when wallet is active
=> thisyahlen/fix: remove bracket and hide arrow if wallet is expanded

packages/cashier/src/components/crypto-fiat-converter/crypto-fiat-converter.scss, packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.scss, packages/components/src/components/input/input.scss
Fixing appearance issues on the account transfer cashier page (see screenshots).
Old:
New:
=> Rostislav / WALL-1986 / Alignment issues in Transfer limit message

packages/bot-web-ui/src/components/dashboard/tutorial-tab/tutorial-content.tsx
=> Maryia/BOT-312/fix: text content on FAQ

.github/actions/build/action.yml, .github/workflows/coveralls.yml, .github/workflows/release_production.yml, .github/workflows/release_staging.yml, .github/workflows/test.yml
=> Ako: Fix Staging github Workflow

packages/wallets/src/components/ExternalTradingPlatforms/AddedCTraderAccountsList/AddedCTraderAccountsList.scss, packages/wallets/src/components/ExternalTradingPlatforms/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx, packages/wallets/src/components/ExternalTradingPlatforms/AddedCTraderAccountsList/index.ts, packages/wallets/src/components/ExternalTradingPlatforms/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/wallets/src/components/ExternalTradingPlatforms/AvailableCTraderAccountsList/AvailableCTraderAccountsList.scss, packages/wallets/src/components/ExternalTradingPlatforms/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx, packages/wallets/src/components/ExternalTradingPlatforms/AvailableCTraderAccountsList/index.ts, packages/wallets/src/components/ExternalTradingPlatforms/AvailableMT5AccountsList/AvailableMT5AccountsList.tsx, packages/wallets/src/components/ExternalTradingPlatforms/CTraderList/CTraderList.scss, packages/wallets/src/components/ExternalTradingPlatforms/CTraderList/CTraderList.tsx, packages/wallets/src/components/ExternalTradingPlatforms/MT5AccountTypeCard/MT5AccountTypeCard.scss, packages/wallets/src/components/ExternalTradingPlatforms/index.ts, packages/wallets/src/components/TradingAccountCard/TradingAccountCard.scss
1. To show the added cTrader demo account. 
2. To create demo ctrader account(CANT CREATE YET THO CAUSE OF QA BOX NOT WHITELISTED) 😭
=> thisyahlen/chore: add ctrader demo to create and show the accounts

.github/actions/versioning/action.yml, .github/workflows/release_production.yml, .github/workflows/release_staging.yml
This meant to checkout the code before access the files one the code.
Otherwise there's no file to read!
=> Ako/ Fix release slack notification  

packages/bot-web-ui/src/components/journal/journal-components/format-message.tsx
- Remove <0></0> from welcome messages to have the translation properly running
=> fix: journal welcome msg translation

packages/hooks/src/useWalletsList.ts
=> Sergei / wall 2007 / logout again

packages/cashier/src/components/crypto-fiat-converter/crypto-fiat-converter.scss, packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.scss
Made some more changes to fix appearance in cashier account transfer page to align responsive with production.
This branch compared to production:
=> Rostislav / WALL-1986 (2) / Alignment issues in Transfer limit message

packages/core/src/Stores/notification-store.js
Reverts binary-com/deriv-app#9452
=> Revert "FarhanNurzi/P2PS-1122/Toast message is disappearing automatically after completing a buy order"

packages/wallets/src/components/WalletTransactions/WalletTransactions.tsx
1. Import useState instead of using React.useState.
=> thisyahlen/fix: import usestate

packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.tsx
Removed percentage selector for cashier transfer between fiat accounts.
=> Rostislav / WALL-2011 / Fiat<->Fiat transfer percentage selector removed

packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.tsx
Reverts binary-com/deriv-app#10511
=> Revert "Rostislav / WALL-2011 / Fiat<->Fiat transfer percentage selector removed"

packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.scss
Align Transfer modal with staging
=> george / WALL-2020 / transfer modal height

packages/bot-web-ui/src/components/journal/journal-components/__tests__/date-item.spec.tsx
Add test case for date-item.tsx
- Test if the component renders properly
- Test if the correct date is shown
- Test if correct time is shown
=> chore: add test case for date-item.tsx

packages/appstore/src/modules/traders-hub/index.tsx
=> fix: changed the percentage

packages/trader/src/Modules/Trading/Components/Form/__tests__/screen-small.spec.tsx
=> Kate/ Fix: file extension

packages/core/src/App/Constants/routes-config.js
Reverts binary-com/deriv-app#10403
=> Revert "fix: remove bot bundle chunk from landing page"

.circleci/config.yml, .github/workflows/test.yml, packages/core/build/config.js, packages/core/package.json, packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx, packages/core/src/App/Constants/routes-config.js, packages/core/src/App/Containers/Layout/header/__tests__/traders-hub-header.spec.tsx, packages/core/src/App/Containers/Layout/header/__tests__/traders-hub-home-button.spec.tsx, packages/core/src/App/Containers/Layout/header/traders-hub-home-button.tsx, packages/shared/src/utils/routes/routes.ts, packages/stores/types.ts, packages/wallets/.eslintignore, packages/wallets/babel.config.json, packages/wallets/declarations.d.ts, packages/wallets/package.json, packages/wallets/src/App.tsx, packages/wallets/src/components/WalletGradientBackground/WalletGradientBackground.scss, packages/wallets/src/components/WalletListCardActions/WalletListCardActions.tsx, packages/wallets/src/components/WalletsAccordion/WalletsAccordion.scss, packages/wallets/src/features/cashier/components/WalletCashierContent/WalletCashierContent.tsx, packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.tsx, packages/wallets/src/features/cashier/screens/WalletTransactionsScreens/WalletTransactionsNoDataState/WalletTransactionsNoDataState.tsx, packages/wallets/src/index.tsx, packages/wallets/src/routes/Router.tsx, packages/wallets/src/utils/loader/index.ts, packages/wallets/src/utils/loader/lazy-load.tsx, packages/wallets/src/utils/loader/module-loader.tsx, packages/wallets/tsconfig.json, packages/wallets/webpack.config.js
Reverts binary-com/deriv-app#10626
=> Revert "Revert "adrienne / added routing for wallets and wallets build workflow""

packages/core/src/App/Constants/routes-config.js
Reverts binary-com/deriv-app#10624
=> Revert "Revert "fix: remove bot bundle chunk from landing page""

packages/cfd/src/Containers/dmt5-trade-modal.tsx, packages/cfd/src/Helpers/constants.ts
Reverts binary-com/deriv-app#10290
=> Revert "shontzu/CFDS-928/Redirect-clients-to-new-MT5-webtrader-URL-based-on-their-MT5-server"

packages/cfd/src/Containers/dmt5-trade-modal.tsx, packages/cfd/src/Helpers/constants.ts
Reverts binary-com/deriv-app#10632
=> Revert "Revert "shontzu/CFDS-928/Redirect-clients-to-new-MT5-webtrader-URL-based-on-their-MT5-server""

packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/google-drive.tsx, packages/bot-web-ui/src/stores/google-drive-store.js
Reverts binary-com/deriv-app#10406
=> Revert "Farabi/bot-726/fix snackbar shown on opening gdrive"

packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/google-drive.tsx, packages/bot-web-ui/src/stores/google-drive-store.js
Reverts binary-com/deriv-app#10636
=> Revert "Revert "Farabi/bot-726/fix snackbar shown on opening gdrive""

packages/shared/src/utils/helpers/__tests__/detail.ts, packages/shared/src/utils/helpers/details.ts
- Add missing field
- Add test case
=> Kate / WEBREL-1501 / While clicking on duration field (Ticks) we are getting error

packages/account/src/Components/personal-details/personal-details.jsx, packages/account/src/Helpers/__tests__/utils.spec.tsx, packages/account/src/Helpers/utils.tsx, packages/core/src/sass/account-wizard.scss
- Modify the citizen value used to trigger Identity check
- SCSS style to fix layout
=> fix: cr account creation for DIEL clients

.github/CODEOWNERS
=> yashim/chore: add wojciech-deriv to codeowners

packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/container.tsx, packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/data/data-fields.ts, packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/duration-fields.tsx, packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/fields.tsx, packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/form.tsx, packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/input-field.tsx, packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/inputs.tsx, packages/bot-web-ui/src/components/dashboard/quick-strategy/quick-strategy-components/selects.tsx, packages/bot-web-ui/src/components/journal/journal-components/filter-dialog.tsx, packages/bot-web-ui/src/components/journal/journal-components/journal-item.tsx, packages/bot-web-ui/src/components/journal/journal-components/journal-tools.tsx, packages/bot-web-ui/src/utils/journal-notifications.js
This will fix the circular dependency issue on staging and production releases. 
=> Ako/ remove circular imports from index files of bots package

.circleci/config.yml
As we are migrating to github actions and the actions are working fine on test and staging releases I created this to remove those workflows from circleci action.
=> Ako/ remove test & staging workflows from circleci

packages/bot-web-ui/src/components/dashboard/dbot-tours/bot-builder-tour/bot-builder-tour-desktop.tsx, packages/bot-web-ui/src/components/run-panel/run-panel.scss, packages/bot-web-ui/src/components/run-panel/run-panel.tsx, packages/bot-web-ui/src/components/summary/summary.tsx
Reverts binary-com/deriv-app#10453
=> Revert "Farabi/bot-785/fix performance panel not closing"

packages/bot-web-ui/src/components/download/download.tsx
Reverts binary-com/deriv-app#10526
=> Revert "Shafin/bot 582/chore  inform download btn disable reason"

packages/core/src/Stores/notification-store.js
Removed condition that redisplays the notification on component load
=> likhith/fix: removed condition to re-render again in same session

packages/bot-web-ui/src/stores/blockly-store.ts, packages/bot-web-ui/src/stores/dashboard-store.ts, packages/bot-web-ui/src/stores/load-modal-store.ts, packages/bot-web-ui/src/stores/quick-strategy-store.ts, packages/bot-web-ui/src/stores/save-modal-store.ts, packages/bot-web-ui/src/stores/toolbar-store.ts, packages/components/src/components/contract-card/contract-card-items/contract-card-body.tsx, packages/components/src/components/contract-card/contract-card-items/contract-update-form.tsx, packages/components/src/components/contract-card/contract-card-items/toggle-card-dialog.tsx, packages/components/src/components/contract-card/contract-card-items/turbos-card-body.tsx, packages/components/src/components/data-list/data-list-row.tsx, packages/components/src/components/data-list/data-list.tsx, packages/components/src/components/data-table/data-table.tsx, packages/components/src/components/data-table/table-row.tsx, packages/components/src/components/input-field/increment-buttons.tsx, packages/components/src/components/input-field/input-field.tsx, packages/components/src/components/input-field/input.tsx, packages/shared/src/utils/files/file-uploader-utils.ts, packages/shared/src/utils/files/image/image_utility.ts
As we had import from/to the same files webpack had an issue on serving the bundles.
this will fix the mentioned issue.
=> Ako/ fix bot package circular dependecies

packages/core/src/App/Components/Layout/Header/menu-links.jsx, packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx, packages/core/src/App/Containers/Layout/header/__tests__/default-mobile-links.spec.tsx, packages/core/src/App/Containers/Layout/header/__tests__/traders-hub-header.spec.tsx, packages/core/src/App/Containers/Layout/header/default-mobile-links.tsx, packages/core/src/App/Containers/Layout/header/header.tsx
1. Show traders hub header for wallets page
2. Hide cashier buttons in mobile and desktop for wallets
=> [42069] thisyahlen/chore: show traders hub header and hide cashier in wallets

packages/wallets/src/components/WalletGradientBackground/WalletGradientBackground.tsx
=> yashim/fix: typescript wallet gradient background

packages/cfd/src/Helpers/cfd-config.ts
New config file to remove the hard-coded variables from the cfd package, and to start using the single source of truth.
=> Hamza/chore: added new config file in Helpers

packages/trader/src/App/Components/Elements/__tests__/market-countdown-timer.spec.tsx, packages/trader/src/App/Components/Elements/__tests__/market-is-closed-overlay.spec.tsx
- Add unit tests for mentioned files.
=> Kate / WEBREL-45 / Test coverage: MarketIsClosedOverlay + MarketCountdownTimer in Trader package

packages/trader/src/Modules/Trading/Containers/__tests__/trade-params-mobile.spec.tsx, packages/trader/src/Modules/Trading/Containers/__tests__/trade-params.spec.tsx
- Add unit tests for the mentioned files
=> Kate / WEBREL-34 / Test coverage: TradeParams + TradeParamsMobile in Trader package

packages/p2p/src/components/nickname-form/nickname-form.tsx, packages/p2p/src/stores/general-store.js
Fixed issue where nick name popup was not closing on clicking on confirm button after entering the nickname.
=> fix: issue with nickname popup not closing

packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/google-drive.tsx, packages/bot-web-ui/src/stores/google-drive-store.js
Reverts binary-com/deriv-app#10641
=> Revert "Revert "Revert "Revert "Farabi/bot-726/fix snackbar shown on opening gdrive""""

packages/bot-web-ui/src/components/dashboard/dbot-tours/bot-builder-tour/bot-builder-tour-desktop.tsx, packages/bot-web-ui/src/components/run-panel/run-panel.scss, packages/bot-web-ui/src/components/run-panel/run-panel.tsx, packages/bot-web-ui/src/components/summary/summary.tsx
- Fixed the toggle of hiding and opening of summary panel
- Added active tour checks for showing accurate panel during tour
=> Farabi/bot 785/fix  performance panel not closing

packages/api/src/hooks/useAccountStatus.ts, packages/api/src/hooks/usePOI.ts
A KYC hook with the following functionalities: 
- Get the previous POI attempts details (if any)
- Get the next step based on a few check. Returns configuration for document validation as well
=> yashim/feat: add usePOI hook

packages/shared/src/utils/brand/brand.ts
- fix: allow localhost domain.
=> Maryia/fix: allow localhost domain

packages/core/src/App/Containers/NotificationsDialog/notification-list-wrapper.tsx, packages/wallets/docs/examples/FlowProvider/AccountFlow/AccountFlow.tsx, packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.tsx, packages/wallets/src/components/WalletTourGuide/WalletTourGuide.tsx, packages/wallets/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.tsx, packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx, packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx, packages/wallets/src/routes/Router.tsx
1. Code cleanup and added routing for internal platforms.
=> [42069] thisyahlen/chore: code cleanup and add routing for internal platforms

packages/api/src/hooks/useAccountStatus.ts, packages/api/src/hooks/usePOI.ts
- Fix multiple calls to `get_account_status` (Remove dependencies to useAccountStatus)
- Remove unnecessary types
- Forwarded props from useGetAccountStatus
=> yashim/fix: usepoi hook

packages/wallets/src/components/Base/WalletText/WalletText.tsx, packages/wallets/src/components/Base/types.ts, packages/wallets/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/wallets/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.tsx, packages/wallets/src/features/cfd/modals/JurisdictionModal/JurisdictionModal.tsx, packages/wallets/src/features/cfd/modals/MT5AccountTypeModal/MT5AccountTypeModal.tsx, packages/wallets/src/features/cfd/screens/MT5AccountType/MT5AccountType.tsx
1. Fix walletbutton type
2. general cleanup on code
3. Launch jurisdiction modal on get button 
4. Sort Derived, Financial and then Swap free in account type modal
=> [42069] thisyahlen/fix: launch jurisdiction modal on get button and fix type

packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionScreen.tsx, packages/wallets/src/features/cfd/screens/Success/Success.tsx
- Fixed an issue where password creation for demo results in an error
- Fixed an issue where success modal shows `(VIRTUAL)` for demo accounts
=> [69420] adrienne/thisyahlen: fixed an issue where mt5 password creation for demo is error

packages/wallets/src/components/WalletsActionScreen/WalletsActionScreen.scss, packages/wallets/src/components/WalletsActionScreen/WalletsActionScreen.tsx, packages/wallets/src/components/WalletsActionScreen/index.ts, packages/wallets/src/features/cashier/flows/WalletResetBalance/WalletResetBalance.tsx
Component to be used for all standard action screens (at the moment of writing this, there are already at least 3 different patterns across wallets codebase - and I'm counting only patterns from wallets v2).
Build to be used within IDV flows.
=> feat: generic component for IDV flows / any action screen

packages/trader/src/Stores/Modules/Trading/Constants/__tests__/validation-rules.spec.ts
=> Kate / Fixes tests cases on master

packages/bot-web-ui/src/stores/dashboard-store.ts
Fix the dark mode when user does any changes on the workspaceo on switch of theme the changes will retain
=> Rupato/BOT-651/fix: added fix for dark mode

packages/components/src/components/mobile-dialog/mobile-dialog.scss, packages/components/src/components/mobile-dialog/mobile-dialog.tsx, packages/shared/src/utils/constants/__tests__/contract.spec.ts, packages/shared/src/utils/constants/contract.ts, packages/trader/src/Modules/Trading/Components/Form/ContractType/ContractTypeMenu/contract-type-menu.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/__tests__/contract-type-menu.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/__tests__/contract-type-widget.spec.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-dialog.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-list.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-widget.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/types.ts, packages/trader/src/Modules/Trading/Containers/__tests__/contract-type.spec.jsx, packages/trader/src/Modules/Trading/Containers/contract-type.tsx, packages/trader/src/Modules/Trading/Helpers/__tests__/contract-type.spec.tsx, packages/trader/src/Modules/Trading/Helpers/contract-type.tsx, packages/trader/src/Stores/Modules/Trading/Helpers/contract-type.ts, packages/trader/src/Stores/Modules/Trading/trade-store.ts, packages/trader/src/sass/app/_common/components/contract-type-dialog.scss, packages/trader/src/sass/app/_common/components/contract-type-list.scss
Reverts binary-com/deriv-app#10539
=> Revert "maryia/DTRA-147/feat: update trade types list"

packages/trader/src/Assets/Trading/Categories/Description/multiplier-trade-description.tsx
- hotfix: multipliers translation issue
=> Maryia/WEBREL-1520/hotfix: multipliers translation issue

packages/cfd/src/Components/__tests__/cfd-download-container.spec.js, packages/cfd/src/Containers/dmt5-trade-modal.tsx, packages/cfd/src/Helpers/constants.ts
Windows link changed.
Broker Name changed
=> Hamza/chore: update the broker name and windows link

packages/bot-web-ui/src/components/load-modal/__tests__/local-footer.spec.tsx
Added test coverage for local-footer component in bot-web-ui
=> test: :white_check_mark: add test case for local-footer component

packages/bot-web-ui/src/components/journal/journal-components/__tests__/journal-item.spec.tsx, packages/bot-web-ui/src/components/journal/journal-components/journal-item.tsx, packages/bot-web-ui/src/components/journal/journal.types.ts
test: add test case for journal-item.tsx
=> Maryia/Bot-687/test: add test case for journal-item.tsx

packages/wallets/src/components/Base/Divider/Divider.scss, packages/wallets/src/components/Base/Divider/Divider.tsx, packages/wallets/src/components/Base/Divider/index.ts, packages/wallets/src/components/Base/index.ts
- Added reusable base component `Divider`
- Added orientation and margin properties to the `Divider` component
=> [Wallet] Lubega / WALL-2293 / Base component divider

packages/bot-web-ui/src/components/journal/journal-components/__tests__/journal-loader.spec.tsx
test: add test case for journal-loader.tsx
=> Maryia/Bot-688/test: add test case for journal-loader.tsx

package.json
Build bot before everything else.
=> ako/ build bot beforehand

packages/api/src/hooks/useWalletAccountsList.ts, packages/wallets/src/components/AccountsList/AccountsList.scss, packages/wallets/src/components/Base/Tabs/TabList.scss, packages/wallets/src/components/DerivAppsSection/DerivAppsSection.scss, packages/wallets/src/components/DesktopWalletsList/DesktopWalletsList.tsx, packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.scss, packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.tsx, packages/wallets/src/components/SkeletonLoader/TradingAppCardLoader/TradingAppCardLoader.scss, packages/wallets/src/components/SkeletonLoader/TradingAppCardLoader/TradingAppCardLoader.tsx, packages/wallets/src/components/SkeletonLoader/index.ts, packages/wallets/src/components/TradingAccountCard/TradingAccountCard.tsx, packages/wallets/src/components/WalletListCard/WalletListCard.tsx, packages/wallets/src/components/WalletListCardIDetails/WalletListCardIDetails.tsx, packages/wallets/src/components/WalletListCardTitle/WalletListCardTitle.tsx, packages/wallets/src/features/cashier/modules/Transfer/TransferForm/components/TransferFormDropdown/components/TransferFormAccountSelection/TransferFormAccountSelection.tsx, packages/wallets/src/features/cfd/CFDPlatformsList.tsx, packages/wallets/src/features/cfd/components/MT5PlatformsList/MT5PlatformsList.tsx, packages/wallets/src/features/cfd/components/OtherCFDPlatformsList/OtherCFDPlatformsList.tsx, packages/wallets/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.scss
1. Cleanup wallets to match design 
=> [wallets]thisyahlen/ chore: wallets cleanup ui

packages/wallets/src/hooks/useInputATMFormatter.ts
=> [Wallet] Farhan/Fix ATMInputFormatter Hook

.github/actions/publish_to_pages_uat/action.yml, .github/workflows/release_uat.yml
Setup UAT environment on Cloudflare.
=> Ako/setup uat environment (#10685)

packages/bot-web-ui/src/components/journal/journal-components/__tests__/journal-tools.spec.tsx
Test case for FilterDialog
- test if the FilterDialog component renders properly
- test if journal filter option passed as prop is showing properly
=> chore: test case for journal tools

packages/api/src/hooks/usePOA.ts, packages/api/src/hooks/usePOI.ts
- Add hook to get POA data
- Pre-calculate all statuses at the hook level
=> yashim/feat: add poa hook

packages/bot-web-ui/src/components/load-modal/__tests__/recent-workspace.spec.tsx, packages/bot-web-ui/src/components/load-modal/recent-workspace.tsx
- Test if RecentWorkspace renders successfully 
- Test if the date passed to the component renders in the correct format
- Test if selected workspace is updated on clicking the strategy
=> chore: test case for RecentWorkspace

.github/CODEOWNERS
=> yashim/chore: update codeowners - add vinu

packages/wallets/src/features/cashier/WalletCashier.scss, packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.scss, packages/wallets/src/features/cashier/components/WalletCashierHeader/WalletCashierHeader.tsx
- add height transition with opacity to make an animation smoother
**Old animation:**
https://github.com/binary-com/deriv-app/assets/103181646/2c76c637-189f-4941-976a-23ac87560fe3
**New animation:**
https://github.com/binary-com/deriv-app/assets/103181646/6a8f752d-e70d-44d6-acfb-e97076548ade
https://github.com/binary-com/deriv-app/assets/103181646/0865c42e-7462-41be-8065-653a25d5ec74
https://github.com/binary-com/deriv-app/assets/103181646/10ff0329-54fb-4e20-970d-3d4ddf8be063
=> [Wallet] george / cashier header animation (heigth transition + opacity)

packages/account/src/Components/financial-details/financial-details-partials.tsx
Fix field value in financial form
=> Amina/fix: mf account

packages/wallets/src/components/Loader/Loader.scss, packages/wallets/src/components/Loader/Loader.tsx
- Modified `Loader` component to match Figma design
https://github.com/binary-com/deriv-app/assets/142860499/c4ecc1fd-ad5f-4830-8801-9bbbdbb9dc59
Figma reference:
- https://www.figma.com/proto/e6OnVx9ZbHhWmLkFVZB8mk/%5BWallets%5D%E2%80%A8-Wallets'-flow?type=design&node-id=424-197145&t=IBXBTstvr0U2nP3Z-0&scaling=min-zoom&page-id=3%3A59
- https://www.figma.com/file/e6OnVx9ZbHhWmLkFVZB8mk/%5BWallets%5D%E2%80%A8-Wallets'-flow?type=design&node-id=424-197145&mode=design&t=im3HgbBx7Kkqsoyr-4
=> [Wallet] Lubega / WALL-2349 / Composite component: Loader

packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/__tests__/recent.spec.tsx
test: test case for recent component
=> Maryia/BOT-755/test: test case for recent component

packages/bot-web-ui/src/components/summary/__tests__/summary.spec.tsx, packages/bot-web-ui/src/components/summary/summary.tsx
=> Maryia/BOT-759/test: summary component

packages/bot-web-ui/src/utils/__tests__/bot-notifications.spec.tsx
test: bot-notifications journalError()
=> Maryia/BOT-763/test: bot-notifications journalError()

.github/actions/build/action.yml
to fix the NODE_ENV issue on PROD
=> Ako/ fix NODE_ENV issue

packages/bot-web-ui/src/stores/__tests__/use-dbot-store.spec.tsx
test: add test case for useDBotStore.tsx
=> Maryia/bot-762/test: add test case for useDBotStore.tsx

packages/bot-web-ui/src/stores/__tests__/self-exclusion-store.spec.tsx
test: add test cases for store self-exclusion
=> Maryia/bot-761/ test: add test cases for store self-exclusion

packages/core/build/webpack.config.js
Reverts binary-com/deriv-app#11042
=> Revert "Ako/ reduce core bundle sizes"

packages/appstore/src/constants/tour-steps-config.tsx
Move `div` outside of the `p` tag
=> Sergei / webrel-1588 / Console Error: Warning: validateDOMNesting

packages/appstore/src/components/cfds-listing/cfds-listing.scss, packages/appstore/src/components/modals/account-type-modal/account-type-modal.scss, packages/appstore/src/components/modals/account-type-modal/account-type-modal.tsx, packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-checkbox.tsx, packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-content-wrapper.tsx, packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal.tsx
Reverts binary-com/deriv-app#10844
=> Revert "Shontzu/prodqa 1335/swap free jurisdiction modal has extra spaces and next button not visible on mobile"

packages/api/src/hooks/index.ts, packages/api/src/hooks/useDxtradeAccountsList.ts, packages/api/src/hooks/useDxtradeServiceToken.ts
=> Hamza/ chore: added dxtrade service token in dxtrade Accounts list

packages/components/src/components/contract-card/contract-card-items/__tests__/vanilla-options-card-body.spec.tsx
This pull request (PR) addresses the issue by modernizing the test cases for a component or feature related to "vanilla." This likely involves updating and improving the testing approach to align with current best practices and standards. The PR is focused on enhancing the testing suite for better code quality and reliability.
=> Akmal / fix: modernize test cases for vanilla

packages/wallets/src/components/ModalProvider/ModalProvider.tsx
- Add an option to mount the modal at a custom root
=> [Wallets] adrienne /  added custom modal root option to modal provider

packages/wallets/src/components/Base/WalletButton/WalletButton.scss, packages/wallets/src/components/Base/WalletButton/WalletButton.tsx, packages/wallets/src/components/Loader/Loader.scss, packages/wallets/src/components/Loader/Loader.tsx, packages/wallets/src/features/cashier/components/WalletActionModal/WalletActionModal.tsx, packages/wallets/src/features/cashier/modules/TransactionStatus/components/TransactionStatusError/TransactionStatusError.tsx, packages/wallets/src/features/cashier/modules/TransactionStatus/components/TransactionStatusSuccess/TransactionStatusSuccess.tsx
- added loading state inside of button
- added new isFullscreen prop for loader
- assign colors based on the colors and variants of the button
=> Aizad/ WALL-2418/ adding Loading State inside of Button

packages/api/src/hooks/index.ts, packages/api/src/hooks/useActiveLinkedToTradingAccount.ts, packages/wallets/src/components/DerivAppsSection/DerivAppsGetAccount.tsx, packages/wallets/src/components/DerivAppsSection/DerivAppsSection.tsx, packages/wallets/src/components/DerivAppsSection/DerivAppsTradingAccount.tsx
1. Put balance in trading account section. 
https://github.com/binary-com/deriv-app/assets/104053934/4518a6ec-f53a-4ece-b565-61a80e77145a
=> [wallets] thisyahlen/WALL-2392/fix: update the balance in trading account section in wallets

packages/cfd/src/Containers/dmt5-trade-modal.tsx
=> Hirad/ chore: fixed the hard coded broker name

packages/bot-web-ui/src/components/quick-strategy/quick-strategy.scss, packages/bot-web-ui/src/components/quick-strategy/selects/contract-type.tsx
Fix for the style of duration field for the quick strategy form
=> fix--duration-style

packages/p2p/src/pages/my-profile/block-user/block-user-dropdown/block-user-dropdown.jsx
- Changed the text in my counterparties tab dropdown from `Sort by` to `Filter by`
=> Ameerul /P2PS 1705 Change Dropdown name for My Counterparties tab

packages/wallets/src/components/WalletListCardActions/WalletListCardActions.tsx, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
1. Fix carousel scroll on page mount. 
https://github.com/binary-com/deriv-app/assets/104053934/a9c8ac4e-d1d2-4caa-84ab-a4121ff2a3e8
=> thisyahlen/WALL-2299/chore: fix carousel scroll not working on page mount

packages/api/src/hooks/useAvailableWallets.ts
- Change the order of add new wallets section
- Put the added wallets at the end of the list
https://github.com/binary-com/deriv-app/assets/125247833/bb6290f3-2c6d-4e35-8464-51d4aae7c0b7
=> [Wallet] Farhan/WALL-2449/Fix the accounts order (added account should be at the end)

packages/api/src/hooks/useActiveLinkedToTradingAccount.ts, packages/wallets/src/components/DerivAppsSection/DerivAppsSection.scss, packages/wallets/src/components/DerivAppsSection/DerivAppsTradingAccount.tsx
1. Fix dtrade linked login id for wallets 
2. Add loading state for the balance in deriv app section
=> thisyahlen/WALL-2440/fix: dtrade linked login id

packages/wallets/.stylelintrc.js, packages/wallets/src/components/Base/Divider/Divider.scss, packages/wallets/src/components/Base/InlineMessage/InlineMessage.scss, packages/wallets/src/components/Base/Tooltip/Tooltip.scss, packages/wallets/src/components/Base/WalletAlertMessage/WalletAlertMessage.scss, packages/wallets/src/components/Base/WalletButton/WalletButton.scss, packages/wallets/src/components/Base/WalletDropdown/WalletDropdown.scss, packages/wallets/src/components/Base/WalletTextField/WalletTextField.scss, packages/wallets/src/components/SkeletonLoader/TradingAppCardLoader/TradingAppCardLoader.scss, packages/wallets/src/components/SkeletonLoader/WalletsDepositCryptoAddressLoader/WalletsDepositCryptoAddressLoader.scss, packages/wallets/src/components/TradingAccountCard/TradingAccountCard.scss, packages/wallets/src/components/WalletNoWalletFoundState/WalletNoWalletFoundState.scss, packages/wallets/src/components/WalletsAddMoreCarousel/WalletsAddMoreCarousel.scss, packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoAddress/DepositCryptoAddress.scss, packages/wallets/src/features/cashier/modules/Transactions/Transactions.scss, packages/wallets/src/features/cashier/modules/Transfer/TransferForm/TransferForm.scss, packages/wallets/src/features/cashier/modules/Transfer/TransferForm/components/TransferFormDropdown/components/TransferFormAccountCard/TransferFormAccountCard.scss, packages/wallets/src/features/cashier/modules/Transfer/TransferForm/components/TransferFormDropdown/components/TransferFormAccountSelection/TransferFormAccountSelection.scss, packages/wallets/src/features/cfd/components/ModalTradeWrapper/ModalTradeWrapper.scss, packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.scss, packages/wallets/src/styles/devices.scss
This PR reverts binary-com/deriv-app#11236
=> Revert "thisyahlen/WALL-2465/chore: add styelint rule to accept defined units"

packages/core/src/App/Containers/Redirect/redirect.jsx, packages/wallets/src/features/cfd/components/ModalTradeWrapper/ModalTradeWrapper.tsx, packages/wallets/src/features/cfd/constants.tsx, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeLink/MT5TradeLink.tsx, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.scss, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.tsx, packages/wallets/src/types.ts
- Fixed an issue where balance and username in Deriv X is not visible
- Removed types for DerivEZ
- Removed code checks for DerivEZ
=> [Wallets] cleanup derivez, update types, fix bug on trade modal

packages/account/src/Components/forms/personal-details-form.jsx
This PR focuses on fixing the design mismatch for a IDV section in account profile settings.
=> WEBREL-1626 / add condition to fix idv section design change

packages/wallets/src/components/WalletTourGuide/WalletTourGuideSettings.tsx
Delete has css method for onboarding steps because it fails for Firefox browser
https://deriv-group.slack.com/archives/C05NSB1LPMX/p1699014891402679
=> [Wallets] Sergei / fix for Firefox browser

.github/workflows/smoketests.yml
Changed the test runner from: Runner_16cores_Deriv-app to ubuntu-latest.
=> Change test runner to ubuntu-latest

.github/workflows/push_and_pull_crowdin_translations.yml
Added  a body message for automated translation PRs
=> Prince/ added body message for translation automated PRs

.github/workflows/push_and_pull_crowdin_translations.yml
Added default title for Translation Sync 
```must provide `--title` and `--body` (or `--fill` or `fill-first`) when not running interactively```
=> Prince/ added title in the automated PR

packages/bot-skeleton/src/services/tradeEngine/utils/interpreter.js
Added InvalidtoBuy to the errors list to stop the bot if error occurs.
=> fix: added InvalidtoBuy to stop bot on error

packages/account/src/Styles/account.scss
=> likhith/fix: field layout in financial info

packages/wallets/src/components/Base/ModalStepWrapper/ModalStepWrapper.tsx, packages/wallets/src/components/Base/ModalWrapper/ModalWrapper.tsx, packages/wallets/src/features/cfd/components/ModalTradeWrapper/ModalTradeWrapper.tsx, packages/wallets/src/features/cfd/modals/JurisdictionModal/JurisdictionModal.tsx, packages/wallets/src/features/cfd/modals/MT5AccountTypeModal/MT5AccountTypeModal.tsx, packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
Close the modal on escape key
- https://app.clickup.com/t/20696747/WALL-2491
=> [wallets] thisyahlen/WALL-2491/chore: close modal on escape key

packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx
1. Based on is_dxtrade_password_not_set api, if its not set show the Create Password Modal. If its set show the Enter password modal
https://github.com/binary-com/deriv-app/assets/104053934/40395fc9-026c-4fc7-ad3f-b5fd433a9677
=> [wallets] thisyahlen/WALL-2336/chore: update derivx create modal to appear if is_dxtrade_password_not_set

packages/hooks/src/__tests__/useTransferBetweenAccounts.spec.tsx, packages/hooks/src/useTransferBetweenAccounts.ts, packages/wallets/src/components/WalletTourGuide/WalletTourGuideSettings.tsx
- fix type error for transfer_between_accounts response because of changing API types
- fix test
- fix Joyride type error (temporary change it to any). seems like an issue is in library types itself
=> george / fix transfer between accounts type error

packages/wallets/src/routes/WalletsListingRoute/WalletsListingRoute.tsx
- Add check `isMobile` for `WalletTourGuide`
* https://app.clickup.com/t/20696747/WALL-2504
=> [Wallets] Sergei / wall - 2504 / Server hit a bump in responsive

packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.tsx
Added key prop in jurisdiction modal return statement. Fixing the console error on launching the modal. 
https://app.clickup.com/t/20696747/WALL-2512
=> thisyahlen/WALL-2512chore: update missing key prop to jurisdiction modal

packages/api/src/APIProvider.tsx
- Add reconnection when WebSocket is closed or closing. (This happens when the user have internet disconnections)
- Add keep alive using ping when the user is idle for a long time (sends ping every 10s)
=> yashim/feat: add reconnection/keepAlive mechanism to wallets WS

packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
1. Update the proper description for deriv x enter password modal
=> thisyahlen/WALL-2519/chore: update description for deriv x enter password modal

packages/appstore/src/components/onboarding-new/static-dashboard.tsx, packages/appstore/src/components/onboarding-new/static-trading-app-card.scss, packages/appstore/src/components/onboarding-new/static-trading-app-card.tsx, packages/appstore/src/constants/trading-hub-content.tsx
- Add animation to the open buttons in step 6 of onboarding
https://github.com/binary-com/deriv-app/assets/82078941/95d8221a-ca67-46d1-be0b-9a3eeb5d846c
=> Mahdiyeh/ WALL- 1923/chore: add animation to the step 6 of onboarding

packages/wallets/src/features/cfd/components/ModalTradeWrapper/ModalTradeWrapper.scss, packages/wallets/src/features/cfd/components/ModalTradeWrapper/ModalTradeWrapper.tsx, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeDetailsItem/MT5TradeDetailsItem.scss, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.tsx
1. Initially description was hardcoded for MT5 only. Now its dynamic to the ones we select before. 
2. CSS cleanup to match design for QR code and others
https://app.clickup.com/t/20696747/WALL-2578
=> WALL-2578/chore: cfd trade modal description fix for different platforms and css cleanup

.github/workflows/smoketests.yml
Added MT5_E2E environment variables
=> Add MT5 envrionment variables

packages/wallets/src/components/DerivAppsSection/DerivAppsGetAccount.tsx
Add `your` word
https://app.clickup.com/t/20696747/WALL-2477
=> [Wallets] Sergei / Wall - 2477 / Content change in success modal

packages/api/src/hooks/useStatesList.ts
1. Add useStatesList hook to api package
=> WALL-2590/chore: add useStatesList hook to api package

packages/account/src/Components/account-limits/account-limits-table-cell.tsx, packages/account/src/Components/account-limits/withdrawal-limits-table.tsx
Removed unwanted wrapper tag `<tr>`  in withdrawal table to wrap a footer text. The tag was not inside a `<table>` tag
=> likhith/[WEBREL-1665]/removed unwanted  wrapper tag

packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-title.tsx
Fixing the Localize function usage for Jurisdiction title.
=> [COJ]/WALL_2310/Amina/ fix: mt5 text translate

packages/wallets/src/components/Base/WalletDropdown/WalletDropdown.scss
https://github.com/binary-com/deriv-app/assets/119863957/a382bac8-193d-4ac3-9088-95caf4cc2c89
=> [Wallets] [Fix] Rostislav / WALL-2594 / Dropdown hitbox size

packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/TransactionsCompletedRow.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/TransactionsCompletedRow.tsx
=> [Wallets] [Fix] Rostislav / WALL-2597 / Jurisdiction badge in transaction list

.github/actions/build_and_push_docker_image/action.yml
This is to fix the indentation issues and missed things to the action.
=> ci: add bash and format the action

.github/workflows/coveralls.yml
To use the correct runner name
=> Ako/ fix the runner name

packages/wallets/src/components/WalletTourGuide/WalletTourGuideSettings.tsx
- change closeProps to skipProps
https://app.clickup.com/t/20696747/WALL-2629
=> [WALL] Sergei / wall - 2629 / X button is not closing the Onboarding

.github/CODEOWNERS
=> yashim/chore: update aizad as codeowner

.github/actions/build_and_push_docker_image/action.yml, .github/workflows/release_production.yml
As the Validation Step wasn't working I removed it to make sure that things are working fine.
I also fixed another issue with the passed inputs to the docker action.
=> Ako/ fix docker image creation

.github/actions/build_and_push_docker_image/action.yml
This is to enable docker image verification.
=> Ako/ verify nginx image

.github/actions/build_and_push_docker_image/action.yml
This is to fix the issue on push to k8s cluster.
=> Ako/ Add CA to env vars

packages/wallets/src/components/WalletTourGuide/DesktopSteps.tsx, packages/wallets/src/components/WalletTourGuide/MobileSteps.tsx, packages/wallets/src/components/WalletTourGuide/WalletMobileTourGuide.tsx, packages/wallets/src/components/WalletTourGuide/WalletTourGuide.tsx, packages/wallets/src/components/WalletTourGuide/WalletTourGuideSettings.tsx
- add `getFiatWalletLoginId`
- add `getWalletIndexForTarget`
- add `walletIndex` to `target` selector
https://app.clickup.com/t/20696747/WALL-2632
For mobile:
https://github.com/binary-com/deriv-app/assets/120570511/f9d3dc67-6f72-4b84-ba8f-316f1de290d1
For desktop:
https://github.com/binary-com/deriv-app/assets/120570511/2b5e7965-14f0-4300-a0e8-3370308b4529
=> [WALL] Sergei / wall - 2632 / Onboarding is not showing if client has crypto wallet only

packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-wallet-address/deposit-crypto-wallet-address.tsx
- Changed component from QRCodeSVG back to QRCode which should fix the changes I did when upgrading the library.
=> [WEBREL] Ameerul /WEBREL-1675 Crypto QR is shrink on deposit page on mobile

packages/wallets/src/features/cashier/modules/FiatOnRamp/FiatOnRamp.tsx
https://www.figma.com/file/e6OnVx9ZbHhWmLkFVZB8mk/%5BWallets%5D%E2%80%A8-Wallets'-flow?type=design&node-id=17-70489&mode=design&t=Wcs5EjJfeaK7GkYu-4
=> [WALL] [QA] Lubega / WALL-2647 / Fix: Updated fiat onramp content

packages/wallets/src/components/Base/WalletDropdown/WalletDropdown.tsx, packages/wallets/src/components/SentEmailContent/SentEmailContent.tsx, packages/wallets/src/features/accounts/screens/IDVDocumentUpload/IDVDocumentUpload.scss, packages/wallets/src/features/accounts/screens/ResubmitPOA/ResubmitPOA.tsx
1. Fix dropdown component label
2. Avoid repetitions of text and move them to a mapper
=> WALL-2656/refactor: dropdown label fix and general code cleanup

.github/CODEOWNERS
Adding a new username to the list of CODEOWNERS of Wallets package.
GH User Added: @heorhi-deriv
=> [WALL]/Matin/Update CODEOWNERS list for wallets

packages/api/src/__tests__/useJurisdictionStatus.spec.tsx, packages/api/src/hooks/usePOI.ts
- Added `country_code` to check for Nigeria country in the verification flow and status
=> [WALL] Removed unused hook and added new attributes for usePOI

packages/api/src/hooks/useSettings.ts, packages/wallets/src/features/accounts/screens/ManualDocumentUpload/ManualDocumentUpload.tsx, packages/wallets/src/features/accounts/screens/ManualDocumentUpload/components/DocumentSelection/DocumentSelection.scss, packages/wallets/src/features/accounts/screens/ManualDocumentUpload/components/DocumentSelection/DocumentSelection.tsx, packages/wallets/src/features/accounts/screens/ManualDocumentUpload/constants.tsx, packages/wallets/src/features/cfd/flows/Verification/Verification.tsx, packages/wallets/src/features/cfd/modals/JurisdictionModal/JurisdictionModal.tsx
1. Link all the flow for mt5 real account signup including idv, onfido and manual upload.
2. All according to BE response.
=> WALL-2668/chore: link all the flow for mt5 real account signup including idv, onfido and manual upload

packages/wallets/src/components/Base/WalletDropdown/WalletDropdown.scss, packages/wallets/src/components/Base/WalletDropdown/WalletDropdown.tsx, packages/wallets/src/components/Base/WalletTextField/WalletTextField.scss, packages/wallets/src/features/cashier/modules/Transactions/Transactions.scss
Made a few small changes to `WalletDropdown`, `WalletTextField`, and their use to fix a few issues
The issue in transactions:
The issue in `PersonalDetails` (when there's no icon):
https://github.com/binary-com/deriv-app/assets/119863957/227a241c-aa9c-4805-951c-7bdc5ef3b6f2
=> [Wallets] [Fix] Rostislav / `WalletDropdown` issues

packages/wallets/src/features/accounts/screens/PersonalDetails/PersonalDetails.tsx, packages/wallets/src/features/accounts/screens/ResubmitPOA/ResubmitPOA.tsx, packages/wallets/src/features/cfd/flows/Verification/Verification.tsx
1. Cleanup on personal detail screens and validations
=> WALL-2673/chore: personal details cleanup

packages/cashier/src/pages/account-transfer/account-transfer-no-account/__tests__/account-transfer-no-account.spec.tsx, packages/cashier/src/pages/account-transfer/account-transfer-no-account/account-transfer-no-account.tsx
- Show button if the user is not from deriv go with is_from_derivgo. 
=> Ameerul /WALL-1643 Hide Back to Trader's Hub button in transfer page for Deriv GO

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
This pull request (PR) introduces a new feature where the price spot will be relocated when it overlaps with a barrier. This change improves the accuracy or functionality of a system or application by addressing issues related to overlapping barriers and price spots.
=> Update charts 1.4.1

packages/wallets/src/features/accounts/constants.tsx, packages/wallets/src/features/accounts/screens/IDVDocumentUpload/IDVDocumentUpload.scss, packages/wallets/src/features/accounts/screens/IDVDocumentUpload/IDVDocumentUpload.tsx, packages/wallets/src/types.ts
1. Error message for idv screen for expired and rejected status
For Rejected status
For Expired status
=> WALL-2679/chore: error message for idv screen for expired and rejected status

packages/bot-skeleton/src/scratch/backward-compatibility.js
- Adaptation of BBot blocks for DBot to migration clients
=> Maryia/BOT-888/fix: adaptation of BBot blocks for DBot to migration users

packages/api/src/hooks/useTransferBetweenAccounts.ts, packages/wallets/package.json, packages/wallets/src/components/Base/ATMAmountInput/ATMAmountInput.scss, packages/wallets/src/components/Base/ATMAmountInput/ATMAmountInput.tsx, packages/wallets/src/components/Base/ATMAmountInput/index.ts, packages/wallets/src/components/Base/index.ts, packages/wallets/src/features/cashier/modules/Transfer/components/TransferForm/TransferForm.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferForm/TransferForm.tsx, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAmountInput/TransferFormAmountInput.tsx, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAmountInput/index.ts, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormDropdown/TransferFormDropdown.tsx, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormInputField/index.ts, packages/wallets/src/features/cashier/modules/Transfer/components/index.ts, packages/wallets/src/features/cashier/modules/Transfer/helpers/helpers.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useExtendedTransferAccountProperties.ts, packages/wallets/src/features/cashier/modules/Transfer/provider/TransferProvider.tsx, packages/wallets/src/features/cashier/modules/Transfer/types/types.ts
- add currency conversion between transfer accounts
- add debouncing when user enters an amount
- move `TransferFormInputField` to wallets base components as `ATMAmountInput` component
- add `lodash.debounce` library (BUNDLE SIZE MINIFIED = 1.9Kb )
https://github.com/binary-com/deriv-app/assets/103181646/a1e91c8f-2644-476e-8725-1756f675843f
=> [Wallets] george / WALL-2094 / currency conversion between accounts

packages/wallets/src/components/Base/WalletDropdown/WalletDropdown.tsx, packages/wallets/src/components/FlowField/FlowTextField.tsx, packages/wallets/src/components/FlowProvider/FlowProvider.tsx, packages/wallets/src/features/accounts/screens/IDVDocumentUpload/IDVDocumentUpload.tsx, packages/wallets/src/features/accounts/screens/IDVDocumentUpload/components/IDVDocumentUploadDetails/IDVDocumentUploadDetails.tsx, packages/wallets/src/features/accounts/screens/PersonalDetails/PersonalDetails.tsx, packages/wallets/src/features/accounts/screens/ResubmitPOA/ResubmitPOA.tsx, packages/wallets/src/features/accounts/validations.ts, packages/wallets/src/features/cfd/flows/Verification/Verification.tsx
1. Add validations to account flow. Error messages and button disables
=> WALL-2688/feat: add validations to account flow

packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.scss, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardVerificationTag.scss, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardVerificationTag.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionScreen.tsx, packages/wallets/src/types.ts
Implement added jurisdiction and document status indication
=> [WALL] Farhan/WALL-2686/Jurisdiction card enhancement

packages/p2p/src/pages/buy-sell/buy-sell-form.jsx, packages/p2p/src/stores/general-store.js
- Used useFormik instead of Formik to handle the Formik changes
- Let the useEffect handle the formik changes to disable and set the submit form function
https://github.com/binary-com/deriv-app/assets/103412909/3684f11c-60a7-467c-b297-0f4545924d71
=> [P2PS] Ameerul / P2PS-1941 Facing Console errors on staging environment

packages/wallets/src/components/Base/WalletText/WalletText.tsx, packages/wallets/src/components/WalletCard/WalletCard.tsx, packages/wallets/src/components/WalletCardIcon/WalletCardIcon.tsx, packages/wallets/src/features/cashier/modules/Transfer/Transfer.tsx, packages/wallets/src/features/cashier/modules/Transfer/components/TransferReceipt/TransferReceipt.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferReceipt/TransferReceipt.tsx, packages/wallets/src/features/cashier/modules/Transfer/components/TransferReceipt/index.ts, packages/wallets/src/features/cashier/modules/Transfer/components/index.ts, packages/wallets/src/features/cashier/modules/Transfer/provider/TransferProvider.tsx
- add transfer receipt screen
- add temporary error handling by displaying a message with a reset button
https://github.com/binary-com/deriv-app/assets/103181646/314427ff-202a-4796-a0d5-0af60cec8237
https://github.com/binary-com/deriv-app/assets/103181646/7c2b68be-da9e-489d-aa26-697e7d8bc196
=> [WALL] george / WALL-2636 / Transfer Receipt Screen

packages/wallets/src/features/cfd/constants.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionFootNoteTitle/JurisdictionFootNoteTitle.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionScreen.scss, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionScreen.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionTncSection/JurisdictionTncSection.scss, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionTncSection/JurisdictionTncSection.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionTncSection/index.ts, packages/wallets/src/features/cfd/screens/Jurisdiction/index.ts
1. Fix the jurisdiction tnc section in mobile (make it sticky)
2. Add proper redirection links for terms and conditions in the jurisdiction footnote
https://github.com/binary-com/deriv-app/assets/104053934/c4d74763-416b-4422-adf2-c2f1cf9d3b23
=> WALL-2700/chore: fix jurisdiction tnc section and add proper terms and condition links

packages/wallets/src/features/cashier/modules/FiatOnRamp/components/FiatOnRampDisclaimer/FiatOnRampDisclaimer.tsx
https://github.com/binary-com/deriv-app/assets/142860499/3c2aaf8c-ef16-4191-acb7-409abee4a81c
=> [WALL] [QA] Lubega / WALL-2670 / Fix: Added loading function for fiat onramp provider

packages/wallets/src/features/accounts/screens/IDVDocumentUpload/components/IDVDocumentUploadDetails/IDVDocumentUploadDetails.tsx, packages/wallets/src/features/accounts/screens/PersonalDetails/PersonalDetails.tsx, packages/wallets/src/features/accounts/utils.ts, packages/wallets/src/features/cfd/flows/Verification/Verification.tsx
1. Make get_settings api call for idv and poa screen
##Screenshot
https://github.com/binary-com/deriv-app/assets/104053934/11a73406-41ad-44ca-8585-1dffa47417cb
=> WALL-2712/chore: make get_settings api call for idv and poa screen

packages/wallets/src/features/cashier/modules/FiatOnRamp/FiatOnRamp.scss, packages/wallets/src/features/cashier/modules/FiatOnRamp/components/FiatOnRampDisclaimer/FiatOnRampDisclaimer.scss, packages/wallets/src/features/cashier/modules/FiatOnRamp/components/FiatOnRampDisclaimer/FiatOnRampDisclaimer.tsx
https://www.figma.com/file/e6OnVx9ZbHhWmLkFVZB8mk/%5BWallets%5D%E2%80%A8-Wallets'-flow?type=design&node-id=17-70488&mode=dev
=> [WALL] Lubega / WALL-2709 / Feat: Fiat onramp design updates

packages/wallets/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx
1. Fix the cfd account title font size
=> [WALL-2714]/fix: cfd account title

packages/wallets/src/features/cashier/modules/FiatOnRamp/components/FiatOnRampDisclaimer/FiatOnRampDisclaimer.tsx
https://github.com/binary-com/deriv-app/assets/142860499/ceb4b370-3b42-417e-a6da-a8e48b4e36b3
=> [WALL] Lubega / WALL-2716 / Fix: Fiat onramp currency select

packages/wallets/src/features/cfd/screens/ChangePassword/ChangePassword.tsx, packages/wallets/src/features/cfd/screens/ChangePassword/MT5ChangePasswordScreens.tsx
- added platform prop inside of `ChangePassword` modal so it can be used for every platform i.e: Deriv MT5, Deriv X, ...
https://github.com/binary-com/deriv-app/assets/103104395/34d2a082-a9e4-43a1-91b1-9bf4f66462b0
=> [WALL] Aizad/ChangePasswordModalImprovements

packages/p2p/src/stores/general-store.js
This PR is for removing the unused observables and functions in general-store.
=> refactor: remove unused observable and functions from general-store

packages/p2p/src/stores/__tests__/my-ads-store.spec.js, packages/p2p/src/stores/my-ads-store.js
This PR is to clean up the ads-store file. Removed the variables, functions and conditions which were not being used anywhere.
=> [P2PS]-fix: remove unsed functions and values from my-ads-store

packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
1. Fixed a bug where financial mt5 account is not being created
https://github.com/binary-com/deriv-app/assets/104053934/28ea80ac-e255-4aa7-969e-3ce440a81185
=> WALL-2742/fix: financial mt5 account creation

packages/wallets/src/components/Base/WalletButton/WalletButton.scss
Need to remove hovering effect on inactive buttons
https://github.com/binary-com/deriv-app/assets/125247833/46253aa4-132e-4840-ba2b-53421839a1fb
=> [WALL] Farhan/WALL-2713/Need to remove hovering effect on inactive buttons

packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx
1. Fixed dxtrade password button for enter password modal
=> WALL-2746/fix: dxtrade password button fix

packages/wallets/src/features/cfd/modals/JurisdictionModal/JurisdictionModal.tsx
1. Fixed jurisdiction checkbox not clickable
=> WALL-2753/fix: jurisdiction modal checkbox

packages/bot-web-ui/src/components/dashboard/bot-builder/toolbar/__tests__/workspace-group.spec.tsx, packages/bot-web-ui/src/components/dashboard/bot-builder/toolbar/toolbar-icon.tsx, packages/bot-web-ui/src/components/dashboard/bot-builder/toolbar/workspace-group.tsx
Added unit test case for workspace-group file in bot-web-ui
=> [Bot] test: added unit test case for workspace-group file in bot-web-ui

packages/wallets/src/features/accounts/screens/DocumentSubmission/DocumentSubmission.scss, packages/wallets/src/features/accounts/screens/DocumentSubmission/DocumentSubmission.tsx, packages/wallets/src/features/cfd/flows/Verification/Verification.tsx
Implement POA document submission
https://github.com/binary-com/deriv-app/assets/125247833/6e1f2e1e-b730-4f84-8f98-2c974c89f6b2
=> [WALL] Farhan/WALL-2747/Implement POA document submission

.stylelintrc.js, packages/wallets/src/AppContent.scss, packages/wallets/src/AppContent.tsx, packages/wallets/src/components/Base/ModalStepWrapper/ModalStepWrapper.scss, packages/wallets/src/features/cashier/WalletCashier.scss, packages/wallets/src/utils/utils.ts
- Add viewport vh instead of svh because svh is not supported for the old browsers
No card
=> [WALL] Sergei / wall - nothing / Change svh to computed viewport vh

packages/trader/src/Modules/Trading/Containers/purchase.tsx
- Add missing `key` prop for the component, which is rendered inside of `.forEach` method. Applicable for desktop + mobile
1st screenshot before the fix, 2d - after.
=> [DTRA] / Kate / DTRA-536 / [Console error] Error after purchasing Accumulator contract

packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.scss, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.tsx, packages/wallets/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardRow.scss
1. Fixed border bottom for jurisdiction modal and mt5 password modal
https://github.com/binary-com/deriv-app/assets/104053934/9068ab29-190f-4a6a-b312-2ac6fc09155a
=> [wallets]thisyahlen/WALL-2768/chore: fix border bottom for jurisdiction modal and is_mt5_password_not_set for password modal

packages/api/src/hooks/useSortedMT5Accounts.ts, packages/wallets/src/features/cfd/components/MT5PlatformsList/MT5PlatformsList.tsx
1. Dont show get more mt5 accounts button if all the mt5 accounts are created
=> [WALL] thisyahlen/WALL-2772/chore: dont show get more accounts button if all the mt5 accounts are created

packages/api/src/hooks/useJurisdictionStatus.ts
1. Fix the verification badge in mt5 section to show based on poa as well.
=> [wallets]thisyahlen/WALL-2771/fix: verification badge for pending based on poa and poi

packages/core/src/index.html
Removing the old Optimize tag as it's not being used, and Google have abandoned it.
=> [FEQ] - Remove optimize tag

packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.scss, packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx
1. Add error handling for ctrader account. 
https://github.com/binary-com/deriv-app/assets/104053934/ad5d098f-a453-4375-ad29-56d71113d12e
=> [wallets]thisyahlen/WALL-2770/chore: add error handling for ctrader account creation

packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAmountInput/TransferFormAmountInput.tsx
- fix amount to label default value
=> [WALL] george / WALL-2775 / fix amount to label

packages/p2p/src/components/modal-manager/modals/filter-modal/filter-modal.scss, packages/p2p/src/pages/orders/chat/chat-message-text.jsx
Fixed the `Reset` and `Apply` buttons alignment in `FilterModal` component.  
Fixed the chat message where `Note` should be on the next line.
=> [WEBREL] farrah/fix: chat message and buttons alignment

packages/appstore/src/components/cfds-listing/index.tsx, packages/cfd/src/Containers/__tests__/dmt5-trade-modal.spec.tsx, packages/cfd/src/Containers/dmt5-trade-modal.tsx
Fixing the vanuatu account status  in Trader's Hub when POI is verified and POA pending is less than 5 days.
=> [COJ]/Amina/fix: vanuatu_account_status

packages/api/src/APIProvider.tsx
Fix connection drop after idle for sometimes
https://github.com/binary-com/deriv-app/assets/125247833/88fd4b62-fdce-491d-a586-00f66df1ba36
=> [WALL] Farhan/Reconnection on idle

packages/wallets/src/components/Base/WalletButton/WalletButton.tsx
https://github.com/binary-com/deriv-app/assets/142860499/33742424-eb90-4488-a3e6-68aeaec0a7a0
=> [WALL] Lubega / WALL-2789 / Fix: add WalletButton isLoading disable function

packages/api/src/APIProvider.tsx
To hide react query logs from console
https://github.com/binary-com/deriv-app/assets/125247833/de1b73a2-37b1-45d1-aa95-fb737b944aa9
=> [WALL] Farhan/Hide react-query error logs

packages/bot-web-ui/src/components/dashboard/tutorial-tab/__tests__/tutorial-tab-desktop.spec.tsx, packages/bot-web-ui/src/components/dashboard/tutorial-tab/common/search-input/index.tsx, packages/bot-web-ui/src/components/dashboard/tutorial-tab/tutorials-tab-desktop.tsx
Removed ref from parent component tutorial-tab.tsx.
instead Added ref to the child component search-input.tsx
=> [BOT] Rupato/WEBREL-1710/dbot tutorial page console error

packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx, packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.scss, packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx
1. Fix responsive css for ctrader
Before: 
After:
=> [wallets]thisyahlen/WALL-2800/fix: ctrader platform css in responsive and bit of refactor

packages/bot-web-ui/src/components/dashboard/bot-builder/__tests__/workspace-wrapper.spec.tsx
* test case for workspace-wrapper.tsx
=> [BOT]Maryia/BOT-963/test: test case for workspace-wrapper.tsx

packages/api/src/hooks/index.ts, packages/api/src/hooks/useTradingPlatformPasswordReset.ts
- added `useTradingPlatformPasswordReset` hook
=> [WALL] Aizad/WALL-2803/Create useTradingPlatformPasswordReset hook for resetting the MT5 password

packages/api/src/hooks/useCtraderAccountsList.ts, packages/wallets/src/features/cfd/CFDPlatformsList.tsx, packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.scss, packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx, packages/wallets/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx
1. Add ctrader demo and real account
https://github.com/binary-com/deriv-app/assets/104053934/a2c9b40f-a95f-40c4-9de6-8fc1a2cbe2d7
https://github.com/binary-com/deriv-app/assets/104053934/b46fb5c7-6ab0-4b7a-aa16-c883c25a5750
=> [wallets]thisyahlen/WALL-2156/feat: adding ctrader demo and real account

packages/p2p/src/pages/my-ads/edit-ad-form.jsx, packages/p2p/src/stores/floating-rate-store.js, packages/p2p/src/stores/general-store.js
This PR is to clean up the floating-rate-store file. Removed the variables, functions and conditions which were not being used anywhere.
=> [P2PS]-fix: remove the unused functions, variables from floating-rate-store

README.md
Updated readme for it to be inline with current recommendations. 
As per slack topic: https://deriv-group.slack.com/archives/C3AHMSM3P/p1701269180932269?thread_ts=1699612857.831589&cid=C3AHMSM3P
=> [WALL] wojciech/tiny update of readme

packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx
1. Update description content for demo dxtrade success modal
=> [wallets]thisyahlen/WALL-2667/chore: update description content for derivx success modal demo

packages/bot-web-ui/src/components/quick-strategy/config.ts, packages/bot-web-ui/src/components/quick-strategy/descriptions/index.ts, packages/bot-web-ui/src/components/quick-strategy/descriptions/martingale.ts, packages/bot-web-ui/src/components/quick-strategy/descriptions/oscar_grind.ts, packages/bot-web-ui/src/components/quick-strategy/form-wrappers/strategy-description.tsx, packages/bot-web-ui/src/components/quick-strategy/quick-strategy.scss, packages/bot-web-ui/src/components/quick-strategy/types.ts
Added long description for Oscar's Grind Strategy
=> feat: qs add long description for oscar's grind

packages/wallets/src/AppContent.tsx, packages/wallets/src/components/WalletLanguageSidePanel/WalletLanguageSidePanel.scss, packages/wallets/src/components/WalletLanguageSidePanel/WalletLanguageSidePanel.tsx, packages/wallets/src/components/WalletLanguageSidePanel/index.ts, packages/wallets/src/components/index.ts
1. Add temporary language panel for language switching in wallets
=> [trah]thisyahlen/TRAH-2195/chore: add temporary language panel for wallets

packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeDetailsItem/MT5TradeDetailsItem.tsx, packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.scss
1.  icon spacing and add tooltip for change password
=> [wallets]thisyahlen/WALL-2796/fix: icon spacing and add tooltip for change password

packages/appstore/src/components/containers/trading-app-card.tsx, packages/appstore/src/components/options-multipliers-listing/index.tsx, packages/appstore/src/components/wallet-content/wallet-option-multipliers-listing.tsx
Fix redirection issue for option and multipliers link
=> [WALL-2252] Mahdiyeh/fix: options link issue

packages/wallets/src/features/cfd/screens/CFDSuccess/CFDSuccess.tsx
1. Fix wrong title for ctrader success modal
Before: 
After:
=> [wallets]thisyahlen/WALL-2833/fix: title for ctrader success modal

packages/trader/src/Modules/SmartChartBeta/Components/LaunchModal/__tests__/launch-modal.spec.tsx
=> [DTRA] Bala/Fix switcher test case

packages/p2p/src/components/modal-manager/modals/disclaimer-modal/disclaimer-modal.tsx
This pr is to fix the issue where screen was getting stuck when user tries to toggle the checkbox for more than 10 times, with 1 press each second.
=> [P2PS]-fix: issue where checkbox toggling for a long time freezes the app

packages/trader/src/Stores/Modules/Trading/trade-store.ts
- Fix analytic types
- It was failing the build in trader
=> yashim/fix: analytics types

.github/actions/versioning/action.yml, .github/workflows/release_staging.yml, .github/workflows/release_uat.yml
This is to have the current version of released app on the dist folder in order to make sure that we are delivering and serving correct version on prod.
=> Ako/ create version txt file on dist

packages/trader/src/App/Containers/SettingsModal/__tests__/settings-chart.spec.tsx, packages/trader/src/App/Containers/__tests__/trade-settings-extensions.spec.tsx
- Add tests for mentioned filed
=> [DTRA] / Kate / WEBREL-53 / Test coverage: TradeSettingsExtensions + ChartSettings in Trader package

packages/wallets/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/jurisdiction-verification-contents.ts
**For Onfido** 
-  A copy of your identity document (identity card, passport) -> A copy of your identity document (e.g. identity card, passport, driver’s license)
**For IDV** 
-   Document number (identity card, passport) -> Document number (e.g identity card, passport, driver’s license)
-   A recent utility bill ( electricity, water or gas) ...[rest remains as is] -> A recent utility bill (e.g. electricity, water or gas)... 
[rest remains as is]
-   Your document is pending for verification -> Verification in review.
-   Verification failed. Resubmit during account creation. -> Verification failed. Resubmit your details.
-   Your document is verified. -> Verification successful.
Before :
After :
=> [WALL] Mahdiyeh/WALL-2846/ update content for jurisdiction selection modal

packages/wallets/src/AppContent.scss, packages/wallets/src/components/WalletAddedSuccess/WalletAddedSuccess.tsx
Fix mobile height on iphone and change wallet added success modal title
https://github.com/binary-com/deriv-app/assets/125247833/ea75ecb0-a6f9-4a3f-b2e3-82066ca55854
=> [WALL] Farhan/WALL-2824/Explore wallet section is getting cropped in iOS devices

packages/trader/src/Modules/SmartChartBeta/Components/LaunchModal/__tests__/launch-modal.spec.tsx
Reverts binary-com/deriv-app#11962
=> Revert "[DTRA] Bala/Fix switcher test case"

packages/wallets/package.json, packages/wallets/src/components/Dropzone/Dropzone.tsx, packages/wallets/src/components/Dropzone/__tests__/Dropzone.spec.tsx
This PR to create unit tests for Dropzone component
=> [WALL] Farhan/WALL-2870/Unit test for DropZone component

packages/bot-web-ui/src/stores/run-panel-store.js
Reverts binary-com/deriv-app#11942
=> Revert "[BOT] Rupato/WALL-2263/Logout issue on dbot"

packages/wallets/src/routes/WalletsListingRoute/__tests__/WalletsListingRoute.spec.tsx
1. Add unit test for WalletListingRoute
=> [wallets]thisyahlen/WALL-3011/chore: add unit test to WalletListingRoute

packages/wallets/src/routes/CashierModalRoute/__tests__/CashierModalRoute.spec.tsx
1. Add unit test for CashierModalRoute
=> [wallets]thisyahlen/WALL-3010/chore: unit test for CashierModalRoute

packages/wallets/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/__tests__/AddedCTraderAccountsList.spec.tsx
1. Add unit test for AddedCTraderAccountList
=> [wallets]thisyahlen/WALL-2932/chore: add unit test for addedctraderaccountlist

packages/wallets/src/features/cashier/modules/FiatOnRamp/components/FiatOnRampDisclaimer/FiatOnRampDisclaimer.tsx, packages/wallets/src/features/cashier/modules/FiatOnRamp/components/FiatOnRampDisclaimer/__tests__/FiatOnRampDisclaimer.spec.tsx
=> [WALL] Lubega / WALL-2976 / chore: fiat onramp disclaimer unit test

packages/wallets/src/features/cashier/modules/FiatOnRamp/components/FiatOnRampProviderCard/FiatOnRampProviderCard.tsx, packages/wallets/src/features/cashier/modules/FiatOnRamp/components/FiatOnRampProviderCard/__tests__/FiatOnRampProviderCard.spec.tsx, packages/wallets/src/features/cashier/modules/FiatOnRamp/constants.tsx
=> [WALL] Lubega / WALL-2977 / chore: fiat onramp provider card unit test

packages/bot-web-ui/src/components/dashboard/dashboard.tsx, packages/bot-web-ui/src/components/dashboard/tutorial-tab/faq-content/index.tsx, packages/bot-web-ui/src/components/dashboard/tutorial-tab/guide-content/index.tsx, packages/bot-web-ui/src/components/dashboard/tutorial-tab/tutorial-tab.tsx
fix for run and video dialog because is_dialog_open was not rendering the component. So to fix this we have passed it from parent. Used localize instead of Localize component.
=>  Rupato/WEBREL-1739/fix for run and video dialog

packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.scss, packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.scss, packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
1. Fix password validation issue in mt5 create password modal and button alignment issue
https://github.com/binary-com/deriv-app/assets/104053934/785cd868-20f4-46b9-9116-2b11275a01db
=> [wallets]thisyahlen/WALL-3038/fix: password validation and button alignment

packages/core/src/Components/markers/marker-spot-label.jsx
- Add missing type for align-label in packages/core/src/Components/markers/marker-spot-label.jsx
=> [DTRA] / Kate / DTRA-558 / Marker console error

packages/core/src/Utils/Hotjar/index.ts, packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-display.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-widget.tsx, packages/trader/src/Stores/Modules/Trading/trade-store.ts
Please provide a summary of the change. yellow bello
=> [DTRA] henry/dtra-535/hotjar-events-for-trade-types

packages/wallets/src/components/WalletTourGuide/DesktopSteps.tsx, packages/wallets/src/components/WalletTourGuide/WalletMobileTourGuide.tsx, packages/wallets/src/components/WalletTourGuide/WalletTourGuide.tsx
- Set `scrollDuration` to 0 for desktop and mobile onboarding
- delete `disableAnimation` for one of the steps [refactor]
https://app.clickup.com/t/20696747/WALL-2676
https://github.com/binary-com/deriv-app/assets/120570511/7a08afed-d578-4693-a40d-d1b3974c2736
=> [WALL] Sergei / wall - 2676 / Blocks getting Flickered on moving to each steps from onboarding screen

packages/wallets/src/components/ToggleSwitch/__tests__/ToggleSwitch.spec.tsx
Unit tests for ToggleSwitch component
=> [WALL] Farhan/WALL-2884/Unit test for ToggleSwitch component

packages/wallets/src/features/cashier/constants/constants.ts, packages/wallets/src/features/cashier/helpers/helpers.ts, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/TransactionsCompletedRow.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowAccountDetails/TransactionsCompletedRowAccountDetails.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowTransferAccountDetails/TransactionsCompletedRowTransferAccountDetails.tsx, packages/wallets/src/features/cashier/modules/Transfer/hooks/useExtendedTransferAccountProperties.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useSortedTransferAccounts.ts, packages/wallets/src/features/cashier/modules/WithdrawalCrypto/components/WithdrawalCryptoReceipt/WithdrawalCryptoReceipt.tsx
=> [WALL] Lubega / WALL-3028 / Create cashier platform constants

packages/account/src/Components/address-details/address-details.tsx, packages/core/src/sass/details-form.scss
Removing extra spacing for address form for CR clients
=> [COJ]/Amina/fix: scrolling in address details form

packages/core/src/App/Containers/VerificationModal/verification-modal.scss, packages/core/src/sass/app/_common/components/account-common.scss
Fixes regression styling issue
=> [COJ] Shaheer / WEBREL-1758 / Regression styling issue

packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-widget.tsx
Please provide a summary of the change. hello
=> [DTRA] henry/dtra-569/fix: change to clicked_item.value for current contract type

packages/trader/src/Modules/Contract/Components/Digits/__tests__/digits.spec.tsx
- Add unit tests for mentioned file
=> [DTRA] / Kate / WEBREL-59 / Test coverage: digits.tsx in Trader package

packages/core/src/App/Containers/RealAccountSignup/real-account-signup.jsx
=> [COJ] WEBREL-1757 / fix: condition to render the modal in real account creation

packages/bot-skeleton/src/scratch/hooks/css.js, packages/bot-web-ui/src/components/dashboard/dashboard.scss, packages/bot-web-ui/src/components/flyout/flyout.scss
Fix click on learn more button on blocks menu which was not working because of css
=> [BOT] Rupato/BOT-1137/fix learn more button

packages/wallets/src/hooks/useInputATMFormatter.ts
=> [WALL] [Fix] Rostislav / WALL-3089 / Fix pasting "-" into ATM input field

packages/bot-web-ui/src/stores/google-drive-store.js
Reverts binary-com/deriv-app#12040
=> Revert "[BOT] shafin/BOT-869/fix google drive showing connected even on abort action"

packages/api/src/hooks/p2p/useChatCreate.ts
- Created the `useChatCreate` hook
=> [FEQ] Jim/FEQ-999/p2p chat create

packages/wallets/src/hooks/__tests__/useInputDecimalFormatter.spec.ts, packages/wallets/src/hooks/useInputDecimalFormatter.ts
- Create unit tests for `useInputDecimalFormatter` hook
- Fix check for +/- sign in `useInputDecimalFormatter` hook (need to check 1st char instead of left part of the input number)
https://app.clickup.com/t/20696747/WALL-3008
=> [WALL] Sergei / wall - 3008 / Unit tests for useInputDecimalFormatter hook

packages/hooks/src/useP2PExchangeRate.ts
- Removed the handleSubscription function from useEffect dependancy as it was spamming the endpoint everytime you are on either buy/sell page or my-ads page
https://github.com/binary-com/deriv-app/assets/103412909/ad7e12bc-6d42-4591-8b02-ca4719b9699f
https://github.com/binary-com/deriv-app/assets/103412909/cc785a48-056f-4acf-876e-0a7bb1fc929f
=> [P2PS] Ameerul / P2PS-2105 / The page is not responding while adding a payment method

packages/wallets/src/components/WalletGradientBackground/WalletGradientBackground.tsx, packages/wallets/src/components/WalletListCard/WalletListCard.tsx, packages/wallets/src/components/WalletListCard/__tests__/WalletListCard.spec.tsx, packages/wallets/src/components/WalletListCardIDetails/WalletListCardIDetails.tsx, packages/wallets/src/components/WalletsAppLinkedWithWalletIcon/__tests__/WalletsAppLinkedWithWalletIcon.spec.tsx, packages/wallets/src/features/cashier/components/WalletCashierHeader/__tests__/WalletCashierHeader.spec.tsx
Create unit test for WalletListCard component
=> [WALL] Farhan/WALL-2893/Unit test for WalletListCard component

packages/wallets/src/components/Base/ProgressBar/ProgressBar.tsx, packages/wallets/src/components/Base/ProgressBar/__tests__/ProgressBar.spec.tsx
Added unit tests for progress bar component.
=> [WALL] Arshad WALL-3045 Unit tests for progress bar component

packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/__tests__/google-drive.spec.tsx, packages/bot-web-ui/src/components/dashboard/dashboard-component/load-bot-preview/google-drive.tsx
=> [BOT] Maryia/BOT-970/test: google-drive.tsx

packages/wallets/src/components/Base/ModalStepWrapper/ModalStepWrapper.tsx, packages/wallets/src/components/Base/ModalStepWrapper/__tests__/ModalStepWrapper.spec.tsx
Added unit tests for ModalStepWrapper Component
=> [WALL] Arshad  Unit tests for ModalStepWrapper Component

packages/wallets/src/components/Base/InlineMessage/InlineMessage.tsx, packages/wallets/src/components/Base/InlineMessage/__tests__/InlineMessage.spec.tsx
Added unit tests for inline message component
=> [WALL] Arshad WALL-3043 Unit test for Inline Message 

packages/tradershub/src/types.ts
=> thisyahlen/fix: rename type hook

packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoTryFiatOnRamp/__tests__/DepositCryptoTryFiatOnRamp.spec.tsx
=> [WALL] Lubega / WALL-2974 / Chore: DepositCryptoTryFiatOnRamp unit test

packages/trader/package.json, packages/trader/src/App/Containers/__tests__/trade-footer-extensions.spec.tsx
Please provide a summary of the change. yellow
=> [DTRA] henry/webrel-55/fix: add test cases and add history as dev dependency

packages/tradershub/src/features/cfd/screens/ActionScreen/ActionScreen.tsx, packages/tradershub/src/features/cfd/screens/ActionScreen/index.ts, packages/tradershub/src/features/cfd/screens/index.ts
Added success modal in the tradershub
=> [TRAH] Hamza/ Added success modal in the tradershub

packages/tradershub/src/constants/password.ts, packages/tradershub/src/features/cfd/screens/EnterPassword/EnterPassword.tsx, packages/tradershub/src/features/cfd/screens/EnterPassword/index.ts, packages/tradershub/src/utils/password.ts
EnterPassword modal
Implement EnterPassword modal when the password is already created for another account.
=> [TRAH] Hamza/ 2301/EnterPassword modal

packages/account/src/Sections/Assessment/TradingAssessment/trading-assessment.jsx
Fix console errors when accessing Trading assessment page for EU.
Adding unique key for dropdown field for Trading assessment form
=> Amina/fix: console error on tradingassessment page

packages/tradershub/src/features/cfd/screens/CreatePassword/CreatePassword.tsx, packages/tradershub/src/features/cfd/screens/CreatePassword/index.ts, packages/tradershub/src/features/cfd/screens/index.ts
Implement CreatePassword modal for creating new password when adding a new CFD platform
=> [TRAH] Hamza/2302/create password component

packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionFootNoteTitle/JurisdictionFootNoteTitle.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionFootNoteTitle/index.tsx
Implement JurisdictionFootNoteTitle component in the Traders Hub Package
=> [TRAH] Hamza/ TRAH-2314/Added urisdictionFootNoteTitle

package-lock.json, packages/account/src/Components/poi/idv-status/idv-submit-complete/__tests__/idv-submit-complete.spec.tsx, packages/account/src/Configs/__test__/personal-details-config.spec.ts, packages/account/src/Sections/Verification/ProofOfIdentity/__tests__/proof-of-identity-container.spec.js, packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-card-front.spec.tsx, packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-card-section.spec.tsx, packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-card.spec.tsx, packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-modal-foot-note.spec.tsx, packages/cfd/src/Containers/jurisdiction-modal/__test__/jurisdiction-title-indicator.spec.tsx, packages/cfd/src/Containers/props.types.ts, packages/integration/src/mocks/auth/getAccountStatus.ts, packages/stores/src/mockStore.ts
Since the backend schema changed and they added `p2p_poa_required` to the schema I added it as mandatory field in the types.
=> Ako/ fix account status type

packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountSelection/TransferFormAccountSelection.scss
- style changes (gaps removal between Wallets and trading accounts sections)
=> [WALL] george / WALL-3112 / gaps removal between Wallets and trading accounts sections

packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountSelection/TransferFormAccountSelection.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountSelection/TransferFormAccountSelection.tsx
- style changes (right and left padding around the 'transfer from')
=> [WALL] george / WALL-3115 / right and left padding around the 'transfer from'

packages/p2p/src/stores/my-profile-store.js
- removed payment_methods_list_values from my-profile-store as it was unused
=> [P2PS] / P2PS-2127 Ameerul / Remove payment_methods_list_values in MyProfileStore

packages/wallets/src/components/TradingAccountCard/__tests__/TradingAccountCard.spec.tsx
To create unit test for TradingAccountCard component
=> [WALL] Farhan/WALL-2885/Unit test for TradingAccountCard component

packages/wallets/src/components/WalletListCardBadge/__tests__/WalletListCardBadge.spec.tsx
To create unit test for WalletListCardBadge component
=> [WALL] Farhan/WALL-2895/Unit test for WalletListCardBadge component

packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionTncSection/JurisdictionTncSection.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionTncSection/index.ts
- Implement JurisdictionTncSection component in the Traders Hub Package
=> [TRAH] Hamza/TRAH-2315/added JurisdictionTncSection

packages/tradershub/src/components/GetADerivAccountBanner/GetADerivAccountBanner.tsx, packages/tradershub/src/components/GetADerivAccountBanner/index.ts, packages/tradershub/src/components/index.ts
1. Add get a real deriv account banner in the cfd section
=> [trah]thisyahlen/chore: add get a deriv account banner

packages/core/src/App/Containers/AccountSwitcher/account-switcher.jsx
Fixing -On account creation flow , idv content is showing for EU (DIEL) account.
=> Amina/fix: idv_fix_for_diel

packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardTag.tsx
Implement JurisdictionCardTag component in the Traders Hub Package
=> [TRAH] Hamza/TRAH-2317/ Added JurisdictionCardTag component

packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/TransactionsPendingRow.tsx
(ignore other issues in the video)
https://github.com/binary-com/deriv-app/assets/119863957/ab592219-a771-4232-84d5-163f7f52899a
=> [WALL] [Fix] Rostislav / WALL-3135 / Fix "x" button for cancelling pending transactions not being clicked on desktop

packages/cashier/src/components/page-container/page-container.tsx, packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-disclaimers/deposit-crypto-disclaimers.scss, packages/cashier/src/modules/deposit-crypto/components/deposit-crypto-disclaimers/deposit-crypto-disclaimers.tsx, packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoDisclaimers/DepositCryptoDisclaimers.tsx
- change minimum deposit message content for tUSDT currency
- fix word typo
- fixed paddings for cashier mobile pages
- fixed list left margin
=> [WALL] george / WALL-2028 / additional note for tUSDT in deposit page

packages/tradershub/src/features/cfd/constants.tsx, packages/tradershub/src/features/cfd/screens/MT5AccountTypeCard/MT5AccountTypeCard.tsx
=> thisyahlen/fix: tradershub types

packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAmountInput/TransferFormAmountInput.tsx, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/useTransferMessages.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/__tests__/insufficientBalanceMessageFn.spec.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/cumulativeAccountLimitsMessageFn.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/index.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/insufficientBalanceMessageFn.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/lifetimeAccountLimitsBetweenWalletsMessageFn.ts, packages/wallets/src/features/cashier/modules/Transfer/hooks/useTransferMessages/utils/transferFeesBetweenWalletsMessageFn.ts, packages/wallets/src/features/cashier/modules/Transfer/types/types.ts
https://github.com/binary-com/deriv-app/assets/119863957/9e35a94c-61aa-4fd0-9660-8a959df858bf
=> [WALL] Rostislav / WALL-3150 / Insufficient balance transfer message

.github/actions/build/action.yml, .github/workflows/release_production.yml, .github/workflows/release_staging.yml, .github/workflows/release_test.yml, .github/workflows/release_uat.yml
Enable A/B testing platform connection (growthbook) in github environment
=> [CRO] Nikita/WEBREL-1836/hotfix: ab feature enabling in gh environment

.github/actions/build/action.yml, .github/workflows/release_production.yml, .github/workflows/release_staging.yml, .github/workflows/release_test.yml, .github/workflows/release_uat.yml
Reverts binary-com/deriv-app#12522
=> Revert "[CRO] Nikita/WEBREL-1836/hotfix: ab feature enabling in gh environment"

packages/api/src/hooks/index.ts, packages/api/src/hooks/useResetVirtualBalance.ts, packages/tradershub/src/components/CurrencySwitcher/CurrencySwitcher.tsx
1. Able to reset virtual balance in the currency switcher 
https://github.com/binary-com/deriv-app/assets/104053934/58fc8b09-3dcf-491f-826a-841a0dabb5ff
=> [trah]thisyahlen/TRAH-2339/chore: reset virtual balance in currency switcher

packages/p2p/src/components/composite-calendar/composite-calendar.tsx, packages/p2p/src/pages/orders/order-table/order-table.jsx, packages/p2p/src/stores/order-store.js
Enable dates upon selecting `from date` then hide the calendar upon selecting from and to date. 
=> [WEBREL] farrah/WEBREL-1835/fix date filter issues

packages/wallets/src/components/FlowField/__tests__/FlowTextField.spec.tsx
To create unit test for FlowField component
=> [WALL]  Farhan/WALL-2872/Unit test for FlowField component

packages/wallets/scripts/update-translations.sh, packages/wallets/src/translations/de.json, packages/wallets/src/translations/en.json, packages/wallets/src/translations/id.json, packages/wallets/src/translations/ms.json
Add check in translations script before uploading to crowdin
=> [WALL] Farhan/Fix translations keys not updated

packages/tradershub/src/App.tsx, packages/tradershub/src/components/ModalProvider/ModalProvider.tsx
1. Fix close on click outside in modal
https://github.com/binary-com/deriv-app/assets/104053934/d3cd66dd-eacd-4674-8b80-cb7a1d83604d
=> [trah]thisyahlen/TRAH-2341/fix: modal close on click outside

packages/tradershub/src/features/cfd/components/CTraderList/CTraderList.tsx, packages/tradershub/src/features/cfd/components/CTraderList/index.ts, packages/tradershub/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx, packages/tradershub/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx, packages/tradershub/src/routes/TradersHubRoute/TradersHubRoute.tsx
- [CU](https://app.clickup.com/t/20696747/TRAH-2338)
=> [TRAH] shontzu/TRAH-2338/show-ctrader-in-tradershub-route

packages/library/package.json, packages/library/src/index.scss, packages/library/src/index.ts
=> chore: added tailwind css config

packages/wallets/src/components/SkeletonLoader/WalletsTransactionStatusLoader/WalletsTransactionStatusLoader.scss, packages/wallets/src/components/SkeletonLoader/WalletsTransactionStatusLoader/WalletsTransactionStatusLoader.tsx, packages/wallets/src/components/SkeletonLoader/index.ts, packages/wallets/src/features/cashier/modules/TransactionStatus/TransactionStatus.scss, packages/wallets/src/features/cashier/modules/TransactionStatus/TransactionStatus.tsx
https://github.com/binary-com/deriv-app/assets/142860499/b9967a64-db79-4cdd-bebc-9aca8ef07778
https://github.com/binary-com/deriv-app/assets/142860499/dacc4504-839c-40a5-be0c-cbdc7e7756e7
=> [WALL] Lubega / WALL-3157 / Fix: Transaction status loader design

packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/CryptoTransaction.tsx
https://github.com/binary-com/deriv-app/assets/142860499/6c2cd3f6-381e-406b-af82-6febe53f7161
https://github.com/binary-com/deriv-app/assets/142860499/e866dc7c-d06c-41ff-bbc9-0c7b9ce9b91e
=> [WALL] Lubega / WALL-3160 / Fix: Transaction status address redirection

packages/core/package.json, packages/core/src/App/app.jsx, packages/core/src/index.html, packages/library/package.json, packages/library/src/index.ts, packages/library/src/providers/CFDProvider/CFDProvider.tsx, packages/library/src/providers/CFDProvider/index.ts, packages/library/src/providers/ModalProvider/ModalProvider.tsx, packages/library/src/providers/ModalProvider/index.ts, packages/library/src/providers/index.ts, packages/library/src/types.ts
1. Add modal and cfd providers to deriv/library
=> [trah]thisyahlen/chore: add modal and cfd provider to deriv library

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
Update `deriv-chart` to stable version
=> Bala/update deriv-chart version

packages/wallets/src/features/cfd/screens/MT5TradeScreen/MT5TradeDetailsItem/MT5TradeDetailsItem.scss
- Change text font to follow design
=> [WALL] Farhan/WALL-3162/Text font is different in MT5 trade popup

packages/wallets/src/components/Base/WalletPasswordField/WalletPasswordField.tsx, packages/wallets/src/features/cfd/modals/DxtradeEnterPasswordModal/DxtradeEnterPasswordModal.tsx, packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
Fix: While entering the wrong password,  the user can’t type derivX password next time
https://github.com/binary-com/deriv-app/assets/125247833/5f2fbad1-c5f0-4f44-90bb-94aa204fd2fd
=> [WALL] Farhan/WALL-3151/While entering the wrong password,  the user can’t type derivX password next time

packages/account/src/Sections/Security/ApiToken/api-token.tsx
This PR fixes the typo of missing colon in API tokens screen in Accounts
=> [COJ] shahzaib / WEBREL-1850 / fix typo in accounts api token screen

packages/appstore/src/modules/traders-hub/index.tsx
[Mobile] Issue in Traders hub - On login we are getting all the products (Options and CFD's) in one screen
=> [WEBREL]/Hamza/WEBREL-1846/mobile issue button toggle cfd

packages/account/src/Constants/api-token-card-details.tsx, packages/account/src/Sections/Security/ApiToken/api-token.tsx
Fixing validation for api-token name
=> [COJ]/ Amina / webrel_1847/ fix: validation for api token

packages/appstore/src/components/onboarding-new/static-trading-app-card.tsx
The description 'Multipliers trading platform.' is repeated for the products stated above
=> [WEBREL] / Hamza/ WEBREL-1848/chore: fixed the wrong platform description on Traders Hub

packages/wallets/src/features/cashier/modules/WithdrawalVerification/__tests_/WithdrawalVerification.spec.tsx
=> [WALL] Lubega / WALL-3004 / Chore: WithdrawalVerification unit test

packages/bot-web-ui/src/components/load-modal/__tests__/recent-workspace.spec.tsx
fix for failing testcase in recent-workspace.spec.ts which is related to timestamp.
=> fix: fix for failing testcase in recent-workspace.spec.ts

packages/tradershub/src/components/StaticLink/StaticLink.tsx, packages/tradershub/src/features/cfd/components/DynamicLeverageContext/DynamicLeverageContext.tsx, packages/tradershub/src/features/cfd/components/DynamicLeverageContext/index.ts, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.classnames.ts, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/jurisdiction-bvi-contents.ts, packages/tradershub/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/jurisdiction-contents.ts, packages/tradershub/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/jurisdiction-labuan-contents.ts, packages/tradershub/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/jurisdiction-svg-contents.ts, packages/tradershub/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/jurisdiction-vanuatu-contents.ts, packages/tradershub/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/jurisdiction-verification-contents.ts, packages/tradershub/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/jurisdiction_maltainvest_contents.ts, packages/tradershub/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/props.types.ts, packages/tradershub/tailwind.config.js
Implement JurisdictionCard component in the Traders Hub Package
=> [TRAH] TRAH-2320 /Hamza/trah 2320/jurisdiction card component

.github/actions/send_slack_notifications/action.yml, .github/workflows/release_production.yml
- Separated `Docker` and `Kubernetes` Status notification from `Cloudflare Pages` deployment slack notification
=> [FEQ] Jim/FEQ-1088/separate docker and k8s notification on deriv-app

packages/api/src/APIProvider.tsx
Reinstantiated disabled errors. As much as I dislike console errors, I dislike even more, when errors gets unnoticed and potentially dangerous bugs are hidden. 
=> [WALL] feat: reinstantiate errors

packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountSelection/TransferFormAccountSelection.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAccountSelection/TransferFormAccountSelection.tsx
Add gap between group title and accounts in transfer account selection
=> [WALL] Farhan/WALL-3165/There should be gaps under the titles.

packages/wallets/src/features/cashier/modules/TransactionStatus/components/CryptoTransaction/CryptoTransaction.tsx
=> [WALL] Lubega / WALL-3196 / Fix: Transaction hash tab redirection

packages/account-v2/build/build-loaders.ts, packages/account-v2/build/build-webpack-config.ts, packages/account-v2/package.json
Updated the package with the following
- Included @deriv/library
- Renamed section to pages
- Incorporated Sonar lint suggestions
=> [account-v2]/likhith/chore: added deriv lib

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
Update @deriv/deriv-charts version - 2.0.1
=> Bala/update version 2.0.1

packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsHeader.tsx
Implement  CompareAccountsHeader inside Tradershub Package
=> [TRAH] Hamza / TRAH-2569/Added header component

packages/cashier/src/pages/payment-agent-transfer/payment-agent-transfer-confirm/payment-agent-transfer-confirm.tsx, packages/cashier/src/pages/payment-agent/payment-agent-withdraw-confirm/payment-agent-withdraw-confirm.tsx
=> Rostislav / WEBREL-1857 / Console warning for unique key for list elements

packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccounts.classnames.ts, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsPlatformLabel.tsx, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/constants.ts
Implement CompareAccountsPlatformLabel inside Tradershub Package
=> [TRAH] Hamza/TRAH-2570 / Added label component

packages/tradershub/src/components/Base/Clipboard/Clipboard.tsx
- this thing has merged yesterday and it causing some issues on some of the prs
=> [TRAH] hotfix: add missing prop in clipboard which causing error

packages/tradershub/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/tradershub/src/features/cfd/flows/MT5/AddedMT5AccountsList/index.ts, packages/tradershub/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.tsx, packages/tradershub/src/features/cfd/flows/MT5/AvailableMT5AccountsList/index.ts, packages/tradershub/src/features/cfd/flows/MT5/MT5AccountIcon.tsx, packages/tradershub/src/features/cfd/flows/MT5/index.ts, packages/tradershub/src/types.ts
- [CU](https://app.clickup.com/t/20696747/TRAH-2293)
- N/A
=> [TRAH] shontzu/TRAH-2293/AddedMT5-and-AvailableMT5-Accounts-List

packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/InstrumentsLabelHighlighted.tsx
Description:
Implement the InstrumentsLabelHighlighted inside TradersHub Package
Screenshots:
=> [TRAH]/Hamza/TRAH-2612/chore: added Highlighted component

packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsDescription.tsx
Implement CompareAccountsDescription inside TradersHub Package
=> [TRAH] Hamza/TRAH-2613/chore: added Description component

packages/wallets/src/components/Base/WalletPasswordField/WalletPasswordField.tsx, packages/wallets/src/components/Base/WalletTextField/WalletTextField.tsx, packages/wallets/src/components/Base/WalletTextField/__tests__/WalletTextField.spec.tsx
Fix `This is very common password` error not shown in password field
=> [WALL] Farhan/WALL-3086/Error message 'This is a very common password' is not displaying

packages/p2p/src/pages/buy-sell/currency-dropdown.jsx, packages/p2p/src/pages/buy-sell/currency-dropdown.scss
- Added label 'Currency' to the currency dropdown
=> [P2PS] / P2PS-981 Ameerul / Add a Title for the Currency Dropdown Box on the Buy/Sell Screen.

packages/bot-web-ui/src/components/quick-strategy/descriptions/reverse_dalembert.ts, packages/bot-web-ui/src/components/quick-strategy/descriptions/strategy_1_3_2_6.ts
Updated missing Key Parameters title for D'Alembert strategy and content update according to the document provided in the card
=> [BOT] Farabi/webrel-1868/quick strategy content

packages/api/src/hooks/useTotalAssets.ts, packages/tradershub/src/components/DemoRealSwitcher/DemoRealSwitcher.tsx
1. Implement switching logic in the real demo dropdown
https://github.com/binary-com/deriv-app/assets/104053934/0b7e6aec-b529-49bb-9f1d-bc37a0509ff3
=> thisyahlen/TRAH-2622/chore: switching logic in real demo dropdown

packages/wallets/src/features/cashier/modules/Transfer/components/TransferReceipt/TransferReceipt.tsx, packages/wallets/src/features/cashier/modules/Transfer/provider/TransferProvider.tsx
- fix transfer fees message content
=> [WALL] george / WALL-3217 / The transfer fee message does not align with the design

packages/tradershub/src/features/cfd/screens/DynamicLeverage/DynamicLeverageTableColumnHeader.tsx, packages/tradershub/src/features/cfd/screens/DynamicLeverage/DynamicLeverageTitle.tsx
Added Dynamic Leverage Title Component to Trader's Hub
CU: https://app.clickup.com/t/20696747/TRAH-2618
=> [TRAH] Arshad /TRAH-2618/ Dynamic leverage title component

packages/account/src/Components/file-uploader-container/file-uploader-container.tsx
The position of the UPLOAD field and the COMMON MISTAKES section needs to be exchanged for better visibility of the COMMON MISTAKES section.
=> [COJ]/likhith/COJ-240/feat: swapped uploader and common mistakes section

packages/appstore/src/components/eu-disclaimer/eu-disclaimer.tsx, packages/appstore/src/modules/traders-hub/index.tsx
Change CFD loss for EU desclaimer from 71 to 70.1
=> [TRAH]/mahdiyeh/TRAH-2616/fix: changed cfd loss for EU desclaimer

packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/TransactionsCompletedRow.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedRow/components/TransactionsCompletedRowTransferAccountDetails/TransactionsCompletedRowTransferAccountDetails.tsx
=> [WALL] Rostislav / WALL-3175 / cTrader transactions display issue fix by a temporary workaround

packages/wallets/src/features/cfd/screens/Onfido/Onfido.scss
Fix height and width of onfido iframe for mobile
=> [WALL] Farhan/WALL-3113/WALL-3114/Fix onfido iframe on mobile view

packages/api/src/__tests__/useJurisdictionStatus.spec.tsx, packages/api/src/hooks/useJurisdictionStatus.ts, packages/tradershub/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/wallets/src/components/Base/WalletPasswordField/WalletPasswordField.tsx, packages/wallets/src/components/Base/WalletTextField/WalletTextField.tsx, packages/wallets/src/components/Base/WalletTextField/__tests__/WalletTextField.spec.tsx, packages/wallets/src/components/FlowField/FlowTextField.tsx, packages/wallets/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/wallets/src/features/cfd/modals/MT5AccountAdded/MT5AccountAdded.tsx, packages/wallets/src/features/cfd/modals/MT5AccountAdded/__tests__/MT5AccountAdded.spec.tsx, packages/wallets/src/features/cfd/modals/MT5AccountAdded/index.ts, packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx, packages/wallets/src/types.ts
…ion with pending poi and poa
Show pending verification message upon creating MT5 account with pending POI and POA
=> [WALL] Farhan/WALL-3097/WALL-3100/MT5 Account created modal (pending verification)

packages/tradershub/.eslintignore, packages/tradershub/tailwind.config.js
- added `*.config.* inside of .eslintignore to resolve the below build error
=> [TRAH] Aizad/ ESLint error in tailwind.config.js inside of Tradershub

packages/wallets/src/features/cashier/modules/Transfer/components/TransferReceipt/TransferReceipt.tsx
=> [WALL] george / WALL-3215 / The font size of the button does not align with the design

packages/wallets/src/components/Base/WalletAlertMessage/WalletAlertMessage.scss, packages/wallets/src/components/Base/WalletAlertMessage/WalletAlertMessage.tsx, packages/wallets/src/features/cashier/modules/Transfer/components/TransferMessages/TransferMessages.scss, packages/wallets/src/features/cashier/modules/Transfer/components/TransferMessages/TransferMessages.tsx
=> [WALL] george / WALL-3232 / The gap between the 'Verify' button and the green message does not align

packages/core/src/App/Components/Layout/Header/toggle-notifications.jsx, packages/core/src/App/Containers/Layout/header/header.tsx
Move P2P order notification handler from header to notification component
--
=> [WEBREL] Farhan/WEBREL-1875/Unable to signup and create DIEL account

packages/appstore/src/components/modals/regulators-compare-modal/regulators-compare-modal-content.tsx
=> [WEBREL] Sergei / WEBREL - 1877 / Console error on regulation tooltip on Trader's Hub page

packages/api/src/hooks/useMobileCarouselWalletsList.ts
Fixed one of the flows in which carousel was stuck in loading state.
=> [WALL] wojtek/WALL-3075 - fixed bug with carousel being stuck in loading state

packages/tradershub/src/components/CurrencySwitcher/CurrencySwitcher.tsx, packages/tradershub/src/components/OptionsAndMultipliersSection/OptionsAndMultiplersHeading/OptionsAndMultipliersHeading.tsx, packages/tradershub/src/components/OptionsAndMultipliersSection/OptionsAndMultipliersContent/OptionsAndMultipliersContent.tsx, packages/tradershub/src/components/OptionsAndMultipliersSection/OptionsAndMultipliersSection.tsx, packages/tradershub/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx, packages/tradershub/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.tsx, packages/tradershub/src/features/cfd/flows/OtherCFDs/Dxtrade/AvailableDxtradeAccountsList/AvailableDxtradeAccountsList.tsx, packages/tradershub/src/routes/TradersHubRoute/TradersHubRoute.tsx
- Change font size to `12px` to match production
- Change font style to use IBM Plex instead
- Replace `sm:` with `lg:` 
##Screenshots:
=> [TRAH] Aizad/Cleanup Tradershub Homepage

packages/trader/src/App/Components/Elements/market-countdown-timer.tsx
Add localisation for Date by tools of the `moment` library (`.locale`) and `current_language` from `common` store. 
Link to the old PR with suggestions (was closed because of unverified commits): https://github.com/binary-com/deriv-app/pull/12636
=> [DTRA] / Kate / DTRA-677 / Translation issue in Marked closed section 

.github/workflows/release_production.yml
- Updated statement to write to `GITHUB_OUTPUT` instead of `GITHUB_ENV`
=> [FEQ] Jim/write to github output instead of github env

packages/shared/src/utils/brand/brand.ts
Add deriv.dev into isDomainAllowed to fix passkey_project Icons
=> Suisin/chore: add deriv.dev into isDomainAllowed

packages/api/src/hooks/index.ts, packages/api/src/hooks/useDerivAccountsList.ts, packages/api/src/hooks/useIsDIELEnabled.ts, packages/api/src/hooks/useIsEuRegion.ts, packages/tradershub/src/components/RegulationSwitcher/RegulationSwitcherDesktop.tsx, packages/tradershub/src/components/RegulationSwitcher/index.ts, packages/tradershub/src/components/TradingAccountsList/TradingAccountsList.tsx, packages/tradershub/src/constants/constants.tsx, packages/tradershub/src/routes/TradersHubRoute/TradersHubRoute.tsx
1. Add regulation switcher in desktop and logic
https://github.com/binary-com/deriv-app/assets/104053934/99638f65-c7ef-49d3-b067-4fc2f7830812
=> thisyahlen/TRAH-2263/chore: regulation switcher logic switch in desktop

packages/tradershub/src/features/cfd/components/DummyComponent/DummyComponent.tsx, packages/tradershub/src/features/cfd/components/DummyComponent/index.ts, packages/tradershub/src/features/cfd/constants.tsx, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsButton.tsx, packages/tradershub/src/routes/TradersHubRoute/TradersHubRoute.tsx
Implement CompareAccountsButton inside of Tradershub package
=> [TRAH] Hamza/TRAH-2564/ compare accounts button component

packages/tradershub/src/features/cfd/modals/VerificationFailedModal/VerificationFailedModal.tsx, packages/tradershub/src/features/cfd/modals/VerificationFailedModal/index.ts, packages/tradershub/src/features/cfd/modals/index.ts, packages/tradershub/src/features/cfd/screens/VerificationFailed/VerificationFailed.tsx
- Create `VerificationFailedModal` component
https://app.clickup.com/t/20696747/TRAH-2604
=> [TRAH] Sergei / TRAH - 2604 / Implement verification failed modal

packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoDisclaimers/__tests__/DepositCryptoDisclaimers.spec.tsx
=> [WALL] Lubega / WALL-2973 / DepositCryptoDisclaimer unit test

packages/wallets/src/features/cashier/modules/DepositCrypto/components/DepositCryptoCurrencyDetails/__tests__/DepositCryptoCurrencyDetails.spec.tsx
=> [WALL] Lubega / WALL-2972 / DepositCryptoCurrencyDetails unit test

packages/wallets/src/features/cashier/modules/TransactionStatus/components/TransactionStatusSuccess/TransactionStatusSuccess.tsx, packages/wallets/src/features/cashier/modules/Transactions/Transactions.tsx
- fixed typo in "View more" url (missing "/")
- added support for pending to be preselecated when "View more" button from deposit page is pressed
- fixed race hazard within Transactions page when some conditions were called before data was actually loaded and correct thus preventing toggle to be set correctly in some circumstances (TBH I expect more of such race hazards to be spread across codebase - probably we should really pay attention to it right now)
https://app.clickup.com/t/20696747/WALL-3158
=> [WALL] wojtek/WALL-3158 added support for preselecting toggle and fixed some issues

packages/wallets/src/features/cashier/modules/ResetBalance/__tests__/ResetBalance.spec.tsx
=> [WALL] Lubega / WALL-2978 / ResetBalance unit test

packages/tradershub/src/features/cfd/modals/TradeModal/TradeModal.tsx, packages/tradershub/src/features/cfd/screens/MT5TradeScreen/MT5TradeDetailsItem/index.ts, packages/tradershub/src/features/cfd/screens/MT5TradeScreen/MT5TradeLink/index.ts, packages/tradershub/src/features/cfd/screens/MT5TradeScreen/index.ts, packages/tradershub/src/features/cfd/screens/TradeScreen/TradeDetailsItem/TradeDetailsItem.tsx, packages/tradershub/src/features/cfd/screens/TradeScreen/TradeDetailsItem/index.ts, packages/tradershub/src/features/cfd/screens/TradeScreen/TradeLink/TradeLink.tsx, packages/tradershub/src/features/cfd/screens/TradeScreen/TradeLink/index.ts, packages/tradershub/src/features/cfd/screens/TradeScreen/TradeScreen.tsx, packages/tradershub/src/features/cfd/screens/TradeScreen/index.ts
Renamed components:
- packages/tradershub/src/features/cfd/screens/MT5TradeScreen/MT5TradeScreen.tsx 
- packages/tradershub/src/features/cfd/screens/MT5TradeScreen/MT5TradeDetailsItem/MT5TradeDetailsItem.tsx 
- packages/tradershub/src/features/cfd/screens/MT5TradeScreen/MT5TradeLink/MT5TradeLink.tsx
https://app.clickup.com/t/20696747/TRAH-2625
=> [TRAH] Sergei / TRAH - 2625 / Improve MT5 components to be useful for other platforms

packages/tradershub/src/AppContent.tsx, packages/tradershub/src/components/CFDSection/CFDContent/CFDContent.tsx, packages/tradershub/src/components/CFDSection/CFDHeading/CFDHeading.tsx, packages/tradershub/src/components/EUDisclaimerMessage/EUDisclaimerMessage.tsx, packages/tradershub/src/components/EUDisclaimerMessage/index.ts, packages/tradershub/src/components/index.ts, packages/tradershub/src/routes/Router.tsx, packages/tradershub/src/routes/TradersHubRoute/TradersHubRoute.tsx, packages/tradershub/tailwind.config.js
- Added checks for CFD if account is EU.
- Added loading animation placeholder for CFD section
- Added EU Disclaimer message
- Added new values inside of tailwind config and remove unused values from the config file.
=> [TRAH] Aizad/ TRAH-2264/ EU disclaimer banner

packages/wallets/src/features/cashier/flows/WalletDeposit/__tests__/WalletDeposit.spec.tsx
=> [WALL] Lubega / WALL-2964 / WalletDeposit unit test

packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsCard.tsx
Implement ComapreAccountsCard inside TradersHub
=> [TRAH]/Hamza/TRAH-2614/ Added component ComapreAccountsCard

packages/wallets/src/features/cfd/modals/JurisdictionModal/JurisdictionModal.tsx, packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx, packages/wallets/src/features/cfd/screens/CFDSuccess/CFDSuccess.tsx, packages/wallets/src/features/cfd/screens/EnterPassword/EnterPassword.tsx
Fix: Alignment issues on demo MT5 modal
=> [WALL] Farhan/WALL-3271/Alignment issues on demo MT5 modal

packages/bot-web-ui/src/stores/google-drive-store.js
Added console to debug the Google drive issue that is only occurring in production/staging.
=> [BOT] fix: test google drive issue

packages/bot-web-ui/src/stores/google-drive-store.js
Reverts binary-com/deriv-app#12977
=> Revert "[BOT] fix: test google drive issue"

packages/tradershub/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx
1. Show successmodal after creating ctrader real/demo account
https://github.com/binary-com/deriv-app/assets/104053934/26f651cf-7bf0-4857-be17-9b149d519742
=> thisyahlen/TRAH-2674/chore: show ctrader success modal after creating ctrader account

packages/core/src/App/Containers/Layout/default-footer.jsx, packages/core/src/App/Containers/Layout/trading-hub-footer.jsx
To disable whatsapp icon temporary from footers.
=> Ako/ to disable whatsapp icon from footer

packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx, packages/core/src/App/Containers/Layout/default-footer.jsx, packages/core/src/App/Containers/Layout/trading-hub-footer.jsx
This is to revert the temporary whatsapp icon disable in footer and sidebar.
=> Ako/ enable back the wa icon

packages/account/src/Sections/Profile/PersonalDetails/validation.ts
Fix validation issue from account settings personal details.
=> chore: update validation errors and regex

packages/core/src/App/Containers/Layout/header/header.tsx, packages/shared/src/utils/routes/routes.ts, packages/tradershub/src/components/CFDSection/CFDHeading/CFDHeading.tsx, packages/tradershub/src/features/cfd/components/CompareAccountsCarousel/CompareAccountsCarousel.tsx, packages/tradershub/src/features/cfd/components/CompareAccountsCarousel/CompareAccountsCarouselButton.tsx, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsCard.tsx, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsScreen.tsx, packages/tradershub/src/routes/Router.tsx
Implement  CompareAccountsScreen inside TradersHub
=> [TRAH]/Hamza/trah 2673/compare accounts screen

packages/api/src/hooks/useSortedMT5Accounts.ts
=> thisyahlen/chore: fix mt5 created accounts for demo and real

packages/bot-web-ui/src/stores/google-drive-store.js
- Debug Gdrive response
- Add condition to only process completed request
=> fix: debug gdrive response

.github/workflows/release_uat.yml
This is to add the missing env vars to uat environment
=> Ako/ add missing env vars to uat environment

packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.tsx
1. Error in launching mt5 financial jurisdiction modal
Before
https://github.com/binary-com/deriv-app/assets/104053934/59609d4e-bcca-4694-9d94-24501293e91e
After:
https://github.com/binary-com/deriv-app/assets/104053934/6b1a32ed-931a-4c99-bb0d-82ea8f1bcfab
=> [trah]thisyahlen/fix: undefined category in mt5 financial jurisdiction modal

packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCard.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/jurisdiction-contents/jurisdiction-contents.ts
1. Only show malta jurisdiction for eu 
https://github.com/binary-com/deriv-app/assets/104053934/ffb3744e-12b6-42e7-988a-be3a50e3ef24
=> [trah]thisyahlen/chore: only show malta jurisdiction in the modal for eu and filter out malta jurisdiction for non-eu

packages/core/build/constants.js, packages/core/src/App/Containers/AccountSignupModal/account-signup-modal.jsx, packages/core/src/App/app.jsx
- Added support for toggling the usage of growthbook by changing the environment variable `IS_GROWTHBOOK_ENABLED: true|false`
=> [CRO] Amir/Add growthbook toggle feature using env var

packages/components/src/components/contract-card/contract-card-items/__tests__/accumulator-card-body.spec.tsx, packages/components/src/components/contract-card/contract-card-items/__tests__/multiplier-card-body.spec.tsx, packages/components/src/components/contract-card/contract-card-items/__tests__/turbos-card-body.spec.tsx, packages/components/src/components/contract-card/contract-card-items/__tests__/vanilla-options-card-body.spec.tsx, packages/components/src/components/contract-card/contract-card-items/accumulator-card-body.tsx, packages/components/src/components/contract-card/contract-card-items/contract-card-body.tsx, packages/components/src/components/contract-card/contract-card-items/contract-update-form.tsx, packages/components/src/components/contract-card/contract-card-items/multiplier-card-body.jsx, packages/components/src/components/contract-card/contract-card-items/turbos-card-body.tsx, packages/components/src/components/contract-card/contract-card-items/vanilla-options-card-body.tsx, packages/trader/src/App/Components/Elements/PositionsDrawer/__tests__/positions-modal-card.spec.tsx, packages/trader/src/App/Components/Elements/PositionsDrawer/positions-modal-card.tsx
- Added condition, which prevents from showing arrow indicator if the contract was sold.
- Added test cases.
=> [DTRA] / Kate / DTRA-708/ Arrow logic improvements

packages/bot-skeleton/src/services/api/ticks_service.js
handled unsubscribe of history call to avoid alreadySubscribed error
=> [Bot]fix: added condition to forget history call

packages/trader/src/App/Components/Elements/LaunchModal/launch-modal.tsx
=> [DTRA] / Kate / WEBREL-1919/ Fix: height of the pop-up for PT language

package-lock.json, packages/account-v2/package.json, packages/p2p-v2/package.json, packages/tradershub/package.json
This is to update UI lib to latest version. 
=> ako/ update ui lib to latest version

packages/api/src/APIProvider.tsx, packages/api/src/hooks/useAuthorize.ts
Disabled refetching authorise on window focus to limit excessive calls and avoid race hazards. One of the many changes to limit them and limit instability of wallets.
No functional changes so no screenshots.
=> [WALL] wojtek/limit unnecessary calls in order to avoid race hazards

packages/bot-web-ui/src/pages/bot-builder/quick-strategy/config.ts
- Updated the naming of 1-3-2-6 strategy to match with the xml to fix unable to run 1-3-2-6 strategy from quick strategies
=> [BOT] Farabi/bot-1281/unable to run 1-3-2-6 strategy

packages/cfd/src/Containers/dmt5-trade-modal.tsx
Reverts binary-com/deriv-app#12840
=> Revert "Hirad: adding deep-linking"

packages/wallets/src/features/cashier/modules/TransactionStatus/components/TransactionStatusSuccess/TransactionStatusSuccess.tsx, packages/wallets/src/features/cashier/modules/TransactionStatus/components/TransactionStatusSuccess/__tests__/TransactionStatusSuccess.spec.tsx, packages/wallets/src/features/cashier/modules/Transactions/Transactions.tsx, packages/wallets/src/routes/Router.tsx
- fix query parameter
https://github.com/binary-com/deriv-app/assets/103181646/058bb3f1-05c8-4976-990c-1b62351af5b6
=> [WALL] george / WALL-3366 / Pending transaction should be loaded on clickin `View more` button on transaction status

packages/reports/src/Containers/statement.tsx
- capitalize first letter for crypto transaction statement
=> [WALL] george / WALL-3341 / WALL-3341  "transaction" in the BTC statement is not capitalise

packages/api/src/hooks/useAuthorize.ts
Brought back refetchOnMount as it was generating problems. 
CU: https://app.clickup.com/t/20696747/WALL-3375
=> [WALL-3375] wojtek/bring back refetch on mount

packages/tradershub/src/features/cfd/constants.tsx, packages/tradershub/src/features/cfd/modals/TradeModal/TradeModal.tsx, packages/tradershub/src/features/cfd/screens/TradeScreen/TradeDetailsItem/TradeDetailsItem.tsx, packages/tradershub/src/features/cfd/screens/TradeScreen/TradeLink/TradeLink.tsx, packages/tradershub/src/features/cfd/screens/TradeScreen/TradeScreen.tsx
- change `Text` from `quill-design` to `Text` from `deriv-com/ui` package
- set footer `align` to `center`
- change `login` to `account_id` and `display_balance` to `formatted_balance` for cTrader
- add divider between platforms
- delete jurisdiction for `dxtrade` and `ctrader` accounts
- set `width` for icon
https://app.clickup.com/t/20696747/TRAH-2687
https://github.com/binary-com/deriv-app/assets/120570511/9e954a60-b358-44a2-b9e9-2bf96c327f3a
=> [TRAH] Sergei / TRAH - 2687 / Mismatch in trade modal

packages/core/src/App/Containers/Modals/app-modals.jsx
Add `is_authorize` check in React useEffect to solve DIEL users logged out issue.
=> Suisin/chore: add authorize check to solve issue

packages/tradershub/src/components/CurrencySwitcher/CurrencySwitcher.tsx, packages/tradershub/src/components/RegulationSwitcher/RegulationSwitcherDesktop.tsx, packages/tradershub/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx, packages/tradershub/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/tradershub/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.tsx
=> thisyahlen/fix: use button from ui library and regulation fix

packages/account/src/Sections/Verification/ProofOfAddress/proof-of-address-form.tsx, packages/components/src/components/hint-box/hint-box.tsx
In POA a disclaimer is shown when user is asked to resubmit. But if the resubmit triggers an error, then the error message is displayed along with the disclaimer.
Only one message must be displayed
=> [COJ]/likhith/COJ-571/Display single error message in POA section

packages/bot-web-ui/src/components/draggable/draggable.tsx, packages/bot-web-ui/src/components/transaction-details/__tests__/transaction-details-desktop.spec.tsx, packages/bot-web-ui/src/components/transaction-details/desktop-transaction-table.tsx, packages/bot-web-ui/src/components/transaction-details/transaction-details-desktop.scss, packages/bot-web-ui/src/components/transaction-details/transaction-details-desktop.tsx, packages/bot-web-ui/src/pages/chart/chart-modal/chart-modal-desktop.tsx, packages/bot-web-ui/src/pages/chart/chart-modal/chart-modal.scss
. Added functionality to resize the modals in deriv bot.
=> [Bot] feat: added resize functionality to modal in dbot

packages/core/src/App/Containers/Modals/app-modals.jsx, packages/core/src/App/Containers/Modals/mt5-notification/mt5-notification-description.tsx, packages/core/src/App/Containers/Modals/mt5-notification/mt5-notification.scss, packages/core/src/App/Containers/Modals/mt5-notification/mt5-notification.tsx, packages/core/src/App/Containers/app-notification-messages.jsx, packages/core/src/Stores/notification-store.js, packages/shared/src/utils/cfd/cfd.ts
Reverts binary-com/deriv-app#13088
=> Revert "[CFDS]/ Hamza/notification content for white label"

packages/account/src/Components/forms/idv-form.tsx
Removed FE side IDV document filter for Ghana and Nigeria.
The IDV documents returned in API will be listed in UI
=> fix: removed filtering IDV documents

packages/bot-web-ui/src/components/network-toast-popup/__tests__/network-toast-popup.spec.tsx, packages/bot-web-ui/src/components/network-toast-popup/network-toast-popup.tsx
- Pass should_open as a dependency to the component with default value false
- Fix TS errors 
- Write test cases with 100% coverage
=> chore: network toast popup

packages/p2p-v2/src/components/AdvertiserName/AdvertiserName.tsx, packages/p2p-v2/src/components/AdvertiserName/AdvertiserNameBadges.tsx, packages/p2p-v2/src/components/AdvertiserName/AdvertiserNameStats.tsx, packages/p2p-v2/src/pages/my-profile/screens/MyProfileAdDetails/MyProfileAdDetails.tsx, packages/p2p-v2/src/pages/my-profile/screens/MyProfileBalance/MyProfileBalance.tsx, packages/p2p-v2/src/pages/my-profile/screens/MyProfileStats/MyProfileStats.tsx, packages/p2p-v2/src/routes/Home/index.tsx
Replace custom loading component with `Loader` component from ui library.
=> [FEQ] farrah/FEQ-1593/fix: use Loader component

packages/components/stories/icon/icons.js, packages/core/src/Components/markers/marker-spot-label.jsx, packages/trader/src/App/Components/Form/RangeSlider/range-slider.tsx
Please provide a summary of the change. 
=> [DTRA] henry/webrel-2332/hotfix: resolve console error

packages/cashier/src/components/crypto-fiat-converter/crypto-fiat-converter.scss, packages/cashier/src/components/percentage-selector/__tests__/percentage-selector.spec.tsx, packages/cashier/src/components/percentage-selector/percentage-selector.scss, packages/cashier/src/components/percentage-selector/percentage-selector.tsx, packages/cashier/src/pages/account-transfer/account-transfer-form/account-transfer-form.scss, packages/cashier/src/pages/withdrawal/withdrawal-crypto-form/withdrawal-crypto-form.scss
- fix transfer form width for crypto transfers
- fix percentage selection when the user selects previous percent
- fix style issues according figma design
https://github.com/binary-com/deriv-app/assets/103181646/7dfa0f7d-b9a7-4111-9142-6669f212baca
=> [WALL] geroeg / WALL-3288 / Transfer from width is incorrect, previous percentage selection selects wrong percent

packages/core/src/App/app.jsx, packages/core/src/Utils/Hotjar/index.ts
This feature introduces Hotjar lazy loading functionality to enhance performance and optimize user experience. Previously, Hotjar scripts might have contributed to initial page load times, potentially impacting site responsiveness. With this addition, Hotjar scripts are now loaded asynchronously, allowing the main content of the page to render first before fetching and executing Hotjar scripts. As a result, users experience faster initial page load times, smoother navigation, and improved overall performance. This implementation aligns with best practices for web optimization, ensuring a seamless and efficient browsing experience while still providing valuable insights through Hotjar analytics.
=> Akmal / feat: add hotjar lazy loading

packages/wallets/src/features/accounts/constants.tsx, packages/wallets/src/features/accounts/screens/DocumentSubmission/DocumentSubmission.tsx, packages/wallets/src/features/accounts/screens/DocumentSubmission/__tests__/DocumentSubmission.spec.tsx
Unit test for DocumentSubmission screen
=> [WALL] Farhan/WALL-2920/Unit test for DocumentSubmission screen

packages/bot-web-ui/src/components/summary/__tests__/summary-card.spec.tsx, packages/bot-web-ui/src/components/summary/summary-card.tsx, packages/bot-web-ui/src/components/summary/summary-card.types.ts
=> [BOT]Maryia/BOT-1029/test: Summary card component

packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/symbol.tsx
- Fixed an issue where empty field was shown on quick strategy modal when switching tabs.
- Default symbol value has been set when symbol is not found during tab switching on quick strategy modal.
=> [BOT] Farabi/bot-1255/fix empty field shown on quick strategy

packages/reports/src/sass/app/_common/layout/trader-layouts.scss, packages/trader/src/sass/app/_common/layout/trader-layouts.scss
Remove smartcharts styling from deriv-app into smartcharts repo to fix barrier alignment issue in mobile contract details page.
=> [DTRA] henry/feq-758/fix: remove styles from deriv-app and apply the styling to smartcharts

packages/core/src/App/Containers/UpdateEmailModal/update-email-modal.jsx
Fixed rendering of conditional text as per the language selected in the Deriv app platform. This fixes the untranslated text in Change Email Success modal
=> [COJ]/likhith/[TRAH-2753]/fix: String localization render

packages/tradershub/src/components/GetDerivAccount/GetDerivAccount.tsx, packages/tradershub/src/components/Loaders/TotalAssetsLoader/TotalAssetsLoader.tsx, packages/tradershub/src/components/Loaders/TotalAssetsLoader/index.ts, packages/tradershub/src/components/Loaders/index.ts, packages/tradershub/src/components/TotalAssets/TotalAssets.tsx, packages/tradershub/src/features/cfd/modals/TradeModal/TradeModal.tsx
1. Fix total assets loader glitch, style and icon fixes
=> thisyahlen/TRAH-2765/fix: total assets loader glitch and minor style fix

packages/tradershub/src/screens/CurrencySelector/Currencies.tsx
Update the currency selector helper message based on updated design.
=> shahzaib / update currency selector helper message

packages/p2p-v2/jest.config.js, packages/p2p-v2/src/components/Checklist/Checklist.tsx, packages/p2p-v2/src/components/Verification/Verification.tsx, packages/p2p-v2/src/components/Verification/__tests__/Verification.spec.tsx
- Added unit tests for Verification component
- Added option to pass test id to buttons in checklist (buttons need to be able to pass data-testid, need to discuss with shayan)
=> [FEQ] / Ameerul / FEQ 1674 Add unit test for verification

packages/p2p-v2/src/components/PaymentMethodForm/PaymentMethodForm.tsx, packages/p2p-v2/src/pages/my-profile/screens/MyProfileStats/MyProfileStatsItem.scss, packages/p2p-v2/src/pages/my-profile/screens/MyProfileStats/MyProfileStatsItem.tsx
Replace `span` with Text component from ui library.
=> [FEQ] farrah/FEQ-1592/fix: use Text component

packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsNoDataState/__tests__/TransactionNoDataState.spec.tsx, packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormAmountInput/TransferFormAmountInput.tsx
=> [WALL] Lubega / WALL-2982 / TransactionsNoDataState unit test

packages/wallets/src/components/FlowField/__tests__/FlowTextField.spec.tsx, packages/wallets/src/features/accounts/screens/IDVDocumentUpload/components/IDVDocumentUploadDetails/__tests__/IDVDocumentUploadDetails.spec.tsx, packages/wallets/src/features/cashier/modules/FiatOnRamp/__tests__/FiatOnRamp.spec.tsx, packages/wallets/src/features/cashier/modules/TransactionStatus/components/TransactionStatusSuccess/__tests__/TransactionStatusSuccess.spec.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompleted/__tests__/TransactionsCompleted.spec.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedDemoResetBalance/TransactionsCompletedDemoResetBalance.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsCompletedDemoResetBalance/__tests__/TransactionsCompletedDemoResetBalance.spec.tsx, packages/wallets/src/features/cfd/CFDPlatformsList.tsx
- Added act and async function wrappers to FlowTextField, IDVDocumentUploadDetails and TransactionsCompleted unit tests
- Added mock components for FiatOnRamp unit test
- Added unique id for TransactionStatusSuccess unit test
- Moved descriptionLink in CFDPlatformsList into the component due to import error
=> [WALL] Lubega / WALL-2980 / TransactionsCompletedDemoResetBalance unit test

package-lock.json, packages/account-v2/package.json, packages/cashier-v2/package.json, packages/p2p-v2/package.json, packages/tradershub/package.json
1. Update deriv-com/ui version
=> thisyahlen/chore: update deriv-com/ui version

packages/tradershub/src/screens/PersonalDetails/Sections/Details.tsx
=> shahzaib / style: personal details section example alignment for responsive

packages/trader/src/Modules/Trading/Components/Form/ContractType/ContractTypeInfo/contract-type-glossary.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/ContractTypeInfo/contract-type-info.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/__tests__/contract-type-glossary.spec.tsx
This feature enhancement enriches the entry spot description, providing users with more comprehensive information and context. Previously, the entry spot description may have lacked detail or clarity, potentially leading to confusion or misunderstanding. With this update, the entry spot description is refined to offer a more detailed and informative overview, including relevant data points or explanatory notes. Users can now benefit from a clearer understanding of the entry spot, facilitating more informed decision-making and analysis. This enhancement contributes to a more user-friendly and insightful experience, empowering users to navigate and interpret entry spot data with greater confidence and efficiency.
=> Akmal / feat: update entry spot description

packages/tradershub/src/flows/RealAccountSIgnup/SignupWizard/Actions/index.tsx, packages/tradershub/src/screens/Address/Address.tsx, packages/tradershub/src/screens/CurrencySelector/CurrencyCard.tsx, packages/tradershub/src/screens/CurrencySelector/CurrencySelector.tsx, packages/tradershub/src/screens/PersonalDetails/PersonalDetails.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/AdditionalInformation.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/Details.tsx, packages/tradershub/src/utils/index.ts, packages/tradershub/src/utils/validations/validations.ts
1. Create validations for personal details, address and currency selector in real account signup
https://github.com/binary-com/deriv-app/assets/104053934/a18a4015-d8af-4dab-bce8-78125f6f7b91
https://github.com/binary-com/deriv-app/assets/104053934/bf320c4d-8b0a-4655-a6ad-6f0bed7c3063
=> thisyahlen/TRAH-2822/chore: real account signup validations

packages/trader/src/Modules/Trading/Components/Form/ContractType/ContractTypeInfo/contract-type-glossary.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/ContractTypeInfo/contract-type-info.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/__tests__/contract-type-glossary.spec.tsx
Reverts binary-com/deriv-app#13201
=> Revert "Akmal / feat: update entry spot description"

packages/tradershub/src/screens/Address/Address.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/AdditionalInformation.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/Details.tsx, packages/tradershub/src/screens/TermsOfUse/TermsOfUse.tsx, packages/tradershub/src/screens/TermsOfUse/TermsOfUseSections/PEPs.tsx
1. Add checkbox to Personal Details and Terms of use page in real account signup
=> thisyahlen/TRAH-2826/chore: add checkbox

packages/api/src/hooks/p2p/entity/advertiser/p2p-advertiser/useAdvertiserUpdate.ts, packages/p2p-v2/src/pages/my-ads/screens/MyAds/MyAdsTable/MyAdsTable.scss, packages/p2p-v2/src/pages/my-ads/screens/MyAds/MyAdsTable/MyAdsTable.tsx, packages/p2p-v2/src/pages/my-ads/screens/MyAds/MyAdsTableRow/MyAdsTableRow.scss, packages/p2p-v2/src/pages/my-ads/screens/MyAds/MyAdsTableRow/MyAdsTableRow.tsx, packages/p2p-v2/src/pages/my-ads/screens/MyAds/MyAdsToggle/MyAdsToggle.tsx, packages/p2p-v2/src/pages/my-ads/screens/MyAds/MyAdsToggle/__tests__/MyAdsToggle.spec.tsx, packages/p2p-v2/src/pages/my-ads/screens/MyAds/MyAdsToggle/index.ts
=> [FEQ] P2P toggle ads.

packages/tradershub/src/features/cfd/components/CTraderList/CTraderList.tsx, packages/tradershub/src/features/cfd/components/OtherCFDPlatformsList/OtherCFDPlatformsList.tsx
1. Fix demo ctrader and dxtrade accounts showing in real if no real account
https://github.com/binary-com/deriv-app/assets/104053934/48862359-09aa-4eba-8f77-c7fce3c8c518
https://github.com/binary-com/deriv-app/assets/104053934/53a5e157-d73d-4db2-80bc-2a1b93731835
=> thisyahlen/TRAH-2828/fix: demo ctrader and dxtrade accounts showing in real if no real account

packages/p2p/src/pages/buy-sell/no-ads/no-ads.jsx
Fixed the condition for showing the nickname modal before redirecting the users to My ads page if there is no ad and nickname is not yet provided.
=> [P2PS] farrah/P2PS-2174/fix: ad redirection

packages/tradershub/src/flows/RealAccountSIgnup/SignupWizard/Actions/index.tsx, packages/tradershub/src/screens/CurrencySelector/CurrencySelector.tsx, packages/tradershub/src/screens/PersonalDetails/PersonalDetails.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/AdditionalInformation.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/Details.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/DetailsConfirmation.tsx, packages/tradershub/src/screens/TermsOfUse/TermsOfUse.tsx, packages/tradershub/src/screens/TermsOfUse/TermsOfUseSections/FatcaDeclaration.tsx, packages/tradershub/src/screens/TermsOfUse/TermsOfUseSections/PEPConfirmation.tsx, packages/tradershub/src/screens/TermsOfUse/TermsOfUseSections/PEPs.tsx, packages/tradershub/src/utils/validations/validations.ts
1. Update validations for checkbox and disable add account button
=> thisyahlen/TRAH-2834/chore: update validations for checkbox and buttons

packages/p2p/src/pages/buy-sell/no-ads/no-ads.jsx
Fixed `Create ad` redirection for advertisers and non-advertisers.
=> farrah/WEBREL-2502/fix: create ad redirection

packages/wallets/src/features/cashier/modules/Transfer/components/TransferFormDropdown/TransferFormDropdown.tsx
https://github.com/binary-com/deriv-app/assets/119863957/8291f8f4-ea6f-4645-a330-1ad776e54648
=> [WALL] Rostislav / WALL-3431 / Only allow user to use active wallet as source wallet in transfer tab

packages/core/src/App/Containers/ConfirmEmailModal/confirm-email-modal.jsx, packages/core/src/App/Containers/ResetEmailModal/reset-email-modal.jsx
This PR helps to retain the email value upon submission for reset-email-modal
=> fix: retain email value after submission

packages/p2p/src/pages/orders/chat/chat-wrapper.jsx, packages/p2p/src/pages/orders/order-table/order-table-row.jsx, packages/p2p/src/stores/order-store.js
- Added an observable that is checked to determine whether or not to hide the order details as we explicitly hid it
https://github.com/binary-com/deriv-app/assets/103412909/f57f052e-3a53-42f5-a9fe-9ad8c46fc8e2
=> [P2PS] / Ameerul / P2PS-1435 User is not navigated to order details page after clicking on back button from chatbox message 

packages/account/src/Components/poi/status/unsupported/unsupported.tsx
Added missing flag that sets the cleanup function to be called when Onfido service is triggered and documents are submitted
The issue was restricted to MT5 section
=> [COJ]/likhith/[COJ-580]/fix: added missing flag required for cleanup function of Onfido in MT5

packages/tradershub/src/components/GetADerivAccountBanner/GetADerivAccountDialog.tsx, packages/tradershub/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx, packages/tradershub/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.tsx, packages/tradershub/src/features/cfd/flows/OtherCFDs/Dxtrade/AvailableDxtradeAccountsList/AvailableDxtradeAccountsList.tsx
1. use react modal for get deriv account dialog
2. Launch signup modal after clicking get
https://github.com/binary-com/deriv-app/assets/104053934/4141dea4-79bd-4a03-988f-168dd86d9329
=> thisyahlen/TRAH-2873/chore: use react modal for get deriv account dialog

packages/tradershub/src/AppContent.tsx, packages/tradershub/src/components/AppContainer/AppContainer.tsx, packages/tradershub/src/components/AppContainer/index.ts, packages/tradershub/src/components/OptionsAndMultipliersSection/OptionsAndMultipliersHeading/OptionsAndMultipliersHeading.tsx, packages/tradershub/src/components/TradingAccountCard/TradingAccountCardComponent.tsx, packages/tradershub/src/components/index.ts, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsCard.tsx, packages/tradershub/src/routes/TradersHubRoute/TradersHubRoute.tsx, packages/tradershub/tailwind.config.js
1. Remove additional quill tailwind config styles
2. Created AppContainer
=> thisyahlen/TRAH-2877/chore: use tailwind breakpoints and create AppContainer

packages/bot-web-ui/src/components/journal/__tests__/journal.spec.tsx, packages/bot-web-ui/src/components/journal/journal.tsx
=> [BOT]/Maryia/BOT-1025/[Test Coverage] - journal.tsx

packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPending/__tests__/TransactionsPending.spec.tsx
=> [WALL] Lubega / WALL-2983 / TransactionsPending unit test

packages/bot-web-ui/src/components/flyout/__tests__/flyout-block-group.spec.tsx, packages/bot-web-ui/src/components/flyout/flyout-block-group.jsx, packages/bot-web-ui/src/components/flyout/help-contents/__tests__/flyout-img.spec.tsx, packages/bot-web-ui/src/components/flyout/help-contents/__tests__/flyout-text.spec.tsx, packages/bot-web-ui/src/components/flyout/help-contents/__tests__/flyout-video.spec.tsx
Added test coverage for `FlyoutBlockGroup` component
=> [BOT] sandeep/bot-1022/code-coverage--flyout-block-group

packages/api/src/hooks/useJurisdictionStatus.ts
=> [WALL] Lubega / WALL-3439 / Remove pending verification for verified POI

packages/tradershub/src/components/Modal/Modal.classnames.ts, packages/tradershub/src/components/Modal/ModalContent.tsx, packages/tradershub/src/components/Modal/ModalHeader.tsx, packages/tradershub/src/features/cfd/screens/DynamicLeverage/DynamicLeverageScreen.tsx, packages/tradershub/src/features/cfd/screens/DynamicLeverage/DynamicLeverageTitle.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionCard/JurisdictionCardBack.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionScreen.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionTncSection/JurisdictionTncSection.tsx, packages/tradershub/src/features/cfd/screens/MT5AccountTypeCard/MT5AccountTypeCard.tsx
1. Fix jurisdiction modal styles
=> thisyahlen/TRAH-2883/chore: fix jurisdiction modal styles

packages/tradershub/src/components/ProgressBar/MobileProgressBar.tsx, packages/tradershub/src/components/ProgressBar/ProgressBar.classnames.ts, packages/tradershub/src/components/ProgressBar/Stepper.tsx, packages/tradershub/src/flows/RealAccountSIgnup/SignupWizard/Actions/index.tsx, packages/tradershub/src/flows/RealAccountSIgnup/SignupWizard/WizardScreenWrapper/WizardScreenWrapper.tsx, packages/tradershub/src/flows/RealAccountSIgnup/SignupWizard/index.tsx, packages/tradershub/src/helpers/formikHelpers.tsx, packages/tradershub/src/helpers/index.ts, packages/tradershub/src/helpers/signupModalHelpers.ts, packages/tradershub/src/screens/Address/Address.tsx, packages/tradershub/src/screens/CurrencySelector/Currencies.tsx, packages/tradershub/src/screens/CurrencySelector/CurrencyCard.tsx, packages/tradershub/src/screens/CurrencySelector/CurrencySelector.tsx, packages/tradershub/src/screens/PersonalDetails/PersonalDetails.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/AdditionalInformation.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/Details.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/DetailsConfirmation.tsx, packages/tradershub/src/screens/PersonalDetails/Sections/TaxInfoConfirmation.tsx, packages/tradershub/src/screens/TermsOfUse/TermsOfUse.tsx, packages/tradershub/src/utils/validations/validations.ts
Fix styles for real account signup with tailwind classes and breakpoints
- Added confirmation checkbox for tax information in personal details screen
- Scroll behaviour on validation error in screens
=> [TRAH] shahzaib / fix styles for real account signup modal

packages/bot-web-ui/src/components/trading-view-chart/trading-view.tsx
Updated TradingView Chart URL
from: [https://tradingview.deriv.com/deriv](https://tradingview.deriv.com/deriv)
to: [https://charts.deriv.com/deriv](https://charts.deriv.com/deriv)
=> [BOT] sandeep/bot-1389/replace tradingview URL

.github/actions/download_remote_config_backup/action.yml, .github/workflows/release_test.yml
added the missed secrets on the test workflow.
=> Ako/ pass proper Keys to the action

.github/actions/download_remote_config_backup/action.yml, .github/workflows/release_test.yml
This is to use github default generated token
=> Ako/ use github default generated token

.github/actions/download_remote_config_backup/action.yml
This is to fix the github token issue on the remote config donwload action
=> Ako/ pass github token from env

.github/actions/download_remote_config_backup/action.yml
This is to checkout to remote config branch before commit to it.
=> Ako/ checkout to branch before commit to it

.github/actions/download_remote_config_backup/action.yml
To disable remote config pr until I make it a separate workflow
=> Ako/ disable remote config pr temporary

packages/wallets/src/AppContent.scss, packages/wallets/src/features/cashier/modules/DepositCrypto/DepositCrypto.scss
https://github.com/binary-com/deriv-app/assets/119863957/30b2d01c-f75b-48f4-810a-17057a9ad33b
=> [WALL] [Fix] Rostislav / WALL-3415 / Fix crypto deposit layout issues

packages/cashier-v2/src/index.tsx, packages/cashier-v2/src/lib/DepositFiat/DepositFiat.module.scss, packages/cashier-v2/src/lib/DepositFiat/DepositFiat.tsx, packages/cashier-v2/src/lib/DepositFiat/__tests__/DepositFiat.spec.tsx, packages/cashier-v2/src/lib/DepositFiat/index.ts, packages/cashier-v2/src/lib/index.ts, packages/cashier-v2/src/routes/Router.tsx, packages/cashier-v2/src/types.ts, packages/cashier-v2/src/utils/utils.ts
- add fiat deposit module 
https://github.com/binary-com/deriv-app/assets/103181646/eba7aed0-c476-4c17-86bd-1b651e581a3a
https://github.com/binary-com/deriv-app/assets/103181646/f4db0c0f-5399-4233-a0ae-094d1170d4e1
https://github.com/binary-com/deriv-app/assets/103181646/e51555da-9821-4ca3-b13b-6533523c7691
=> [Cashier-V2] george / FEQ-1664 / Implement Fiat Deposit module

packages/p2p/src/pages/my-ads/order-time-selection/order-time-selection.tsx
Moved the declaration of order info inside the component to re-render when switching language.
=> [P2PS] farrah/P2PS-2361/fix: order info translation

packages/tradershub/src/screens/PersonalDetails/Sections/AdditionalInformation.tsx, packages/tradershub/src/utils/validations/validations.ts
Added validations for tax information for additional details section in real account creation.
https://github.com/binary-com/deriv-app/assets/129842155/01ec1d75-10dc-4378-912a-88ef6711ef7c
=> [TRAH] shahzaib / add validation for additional information

.github/actions/build/action.yml, .github/workflows/release_production.yml, .github/workflows/release_staging.yml, .github/workflows/release_test.yml, .github/workflows/release_uat.yml
Pass REMOTE_CONFIG_URL to build step in order to access to it on run time.
=> Ako/ pass REMOTE_CONFIG_URL to build step

packages/account/src/Components/personal-details/personal-details.jsx
1. Fix validations in personal details page that keeps resetting when user clicks on another input
https://github.com/binary-com/deriv-app/assets/104053934/9ff07a06-1ac3-4544-b76a-a46846372027
=> thisyahlen/chore: fix validations when user clicks on another input

packages/account/src/Components/trading-assessment/trading-assessment-form.tsx
- make onSave function optional
https://github.com/binary-com/deriv-app/assets/120570511/d6937d92-8c6f-4094-a2e3-9d1ebe2894da
=> Sergei / WEBREL-2520 / When a MF account is created through script, user is not able to complete Trading Experience Assessment on staging

.github/actions/download_remote_config_backup/action.yml, .github/workflows/release_test.yml, .github/workflows/remote_config_pr.yml
Add workflow permissions to it.
Removed useless inputs and steps from the test workflow and the download file action
=> Ako/ add permissions to the workflow

packages/account/src/Components/personal-details/personal-details.jsx, packages/components/src/components/auto-height-wrapper/auto-height-wrapper.tsx, packages/core/src/Stores/client-store.js
- add `is_mounted_ref` for `AutoHeightWrapper` component
- remove `trackEvent` from dependency array
- add check for object destructuring in client store
=> [WEBREL] Sergei / Webrel - 2522 / Seeing console errors while manually creating a new MF account

package-lock.json, packages/account-v2/package.json, packages/cashier-v2/package.json, packages/p2p-v2/package.json, packages/tradershub/package.json
- Bump-deriv-com/ui-version-from-v1.5.3-to-v1.8.1
=> [Cashier-V2] george / FEQ-1756 / Bump-deriv-com/ui-version-from-v1.5.3-to-v1.8.1

packages/account/src/Components/personal-details/personal-details.jsx, packages/components/src/components/auto-height-wrapper/auto-height-wrapper.tsx, packages/core/src/Stores/client-store.js
=> fix: fix console errors for 2 cases (#13667)

packages/core/src/App/Containers/VerificationModal/verification-modal.scss, packages/core/src/sass/app/_common/components/account-common.scss
- proof of identity country selector modal fix
=> Arshad/COJ-581/POI Country Selector Modal Alignment

.github/workflows/release_production.yml, .github/workflows/release_staging.yml, .github/workflows/release_uat.yml
this it to fix the download remote config file step in UAT, Staging and Production workflows.
=> Ako/ use vars instead of env

packages/tradershub/src/components/CFDSection/CFDContent/CFDContent.tsx, packages/tradershub/src/components/CFDSection/CFDHeading/CFDHeading.tsx, packages/tradershub/src/components/DemoRealSwitcher/DemoRealSwitcher.tsx, packages/tradershub/src/components/Loaders/DemoRealSwitcherLoader/DemoRealSwitcherLoader.tsx, packages/tradershub/src/components/Loaders/DemoRealSwitcherLoader/index.ts, packages/tradershub/src/components/Loaders/index.ts, packages/tradershub/src/components/OptionsAndMultipliersSection/OptionsAndMultipliersContent/OptionsAndMultipliersContent.tsx, packages/tradershub/src/components/OptionsAndMultipliersSection/OptionsAndMultipliersHeading/OptionsAndMultipliersHeading.tsx, packages/tradershub/src/features/cfd/modals/TopUpModal/TopUpModal.tsx, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsCard.tsx, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsDescription.tsx, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsHeader.tsx, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsScreen.tsx, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/CompareAccountsTitleIcon.tsx, packages/tradershub/src/features/cfd/screens/CFDCompareAccounts/InstrumentsLabelHighlighted.tsx, packages/tradershub/src/flows/Signup/CitizenshipModal/CitizenshipModal.tsx
1. Remove usage of useIsEURegion in components
2. Used useRegulationFlags instead for isEU condition.
3. Refactored cfd compare accounts to avoid prop drilling 
4. Added loader for demo real switcher to fix the glitch
=> thisyahlen/TRAH-2988/chore: useIsEURegion hook cleanup, minor refactoring and loader for demo real switcher

packages/p2p/src/components/modal-manager/modals/buy-sell-modal/buy-sell-modal.tsx, packages/p2p/src/pages/buy-sell/buy-sell-form.scss
- Added scrollTo function to scroll to top of div in buy sell modal
https://github.com/binary-com/deriv-app/assets/103412909/0e9da365-4d2e-41b1-94cc-0952efce1e08
=> [P2PS] / Ameerul / P2PS-2286 Enhancement to scroll back up to show error message when placing sell order

packages/cashier/src/components/crypto-fiat-converter/crypto-fiat-converter.tsx, packages/cashier/src/stores/crypto-fiat-converter-store.ts
- fix converter issue (cause: wrong decimal places)
- fix `onChangeConverterToAmount` parameter order
https://github.com/binary-com/deriv-app/assets/103181646/58dbcb50-252f-4a4d-a75b-e8a166b9e6e9
=> [WEBREL] george / WEBREL-2532 / Crypto amounts not properly converted for transfer between sibling accounts

packages/p2p/src/pages/my-ads/my-ads-row-renderer.jsx
Added a condition to not allow the temporary banned advertisers to share their ads.
=> [P2PS] farrah/P2PS-2372/fix: disable share button for temporary banned advertisers

.github/CODEOWNERS
This PR is created to update the CODEOWNERS file with the focus on Trader's Hub package.
=> Matin/Chore: Update CODEOWNERS for tradershub

packages/tradershub/src/components/StaticLink/StaticLink.tsx, packages/tradershub/src/flows/Signup/CitizenshipModal/CitizenshipModal.tsx
1. Improve StaticLink component to open a new tab only if href or staticUrl is passed
=> thisyahlen/TRAH-2989/chore: improve StaticLink component

packages/wallets/src/components/DesktopWalletsList/DesktopWalletsList.tsx, packages/wallets/src/components/WalletListCard/WalletListCard.tsx, packages/wallets/src/components/WalletListCard/__tests__/WalletListCard.spec.tsx, packages/wallets/src/components/WalletListCardActions/WalletListCardActions.tsx, packages/wallets/src/components/WalletListCardActions/__tests__/WalletListCardActions.spec.tsx, packages/wallets/src/components/WalletListCardBalance/WalletListCardBalance.tsx, packages/wallets/src/components/WalletListCardBalance/__tests__/WalletListCardBalance.spec.tsx, packages/wallets/src/components/WalletListCardDetails/WalletListCardDetails.tsx, packages/wallets/src/components/WalletListCardDetails/__tests__/WalletListCardDetails.spec.tsx, packages/wallets/src/components/WalletListCardDropdown/WalletListCardDropdown.tsx, packages/wallets/src/components/WalletListCardDropdown/__tests__/WalletListCardDropdown.spec.tsx, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
https://github.com/binary-com/deriv-app/assets/142860499/4c9a765a-5bc1-4ea0-80e1-ec0c56d10902
https://github.com/binary-com/deriv-app/assets/142860499/c9013c81-60b6-4bad-9a23-c5fb1a9ef892
=> [WALL] Lubega / WALL-3497 / Account switcher active wallet loading fix

packages/tradershub/src/components/AppContainer/AppContainer.tsx, packages/tradershub/src/components/DemoRealSwitcher/DemoRealSwitcher.tsx, packages/tradershub/src/components/OptionsAndMultipliersSection/OptionsAndMultipliersHeading/OptionsAndMultipliersHeading.tsx, packages/tradershub/src/components/TotalAssets/TotalAssets.tsx, packages/tradershub/src/components/TradersHubContent/TradersHubContent.tsx, packages/tradershub/src/components/TradingAccountsList/TradingAccountsList.tsx, packages/tradershub/src/hooks/index.ts, packages/tradershub/src/hooks/useAccountSwitcher.ts
1. Minor cleanup
2. Move account switching logic in DemoRealSwitcher to hook
3. Use css for conditional device rendering
=> thisyahlen/TRAH-2999/chore: cleanup and minor refactoring

packages/api-v2/src/hooks/__tests__/useCountryList.spec.tsx, packages/api-v2/src/hooks/__tests__/useKycAuthStatus.spec.ts, packages/api-v2/src/hooks/__tests__/useOnfido.spec.ts, packages/api-v2/src/hooks/index.ts, packages/api-v2/src/hooks/useClientCountry.ts, packages/api-v2/src/hooks/useGetAccountStatus.ts, packages/api-v2/src/hooks/useJurisdictionStatus.ts, packages/api-v2/src/hooks/useKycAuthStatus.ts, packages/api-v2/src/hooks/useOnfido.ts, packages/api-v2/src/hooks/useOnfidoServiceToken.ts, packages/api-v2/src/hooks/useRemoteConfig.ts, packages/api-v2/src/hooks/useSettings.ts, packages/api-v2/src/hooks/useWalletMigration.ts, packages/api-v2/src/index.ts, packages/api-v2/src/remote_config.json
No functional changes. Only re-applied changes from v1 to v2 ahead of switching.
=> [WALL-3503] wojtek/sync api with api-v2 ahead of switching the packages

packages/wallets/src/features/cashier/modules/WithdrawalVerification/WithdrawalVerificationRequest/WithdrawalVerificationRequest.scss
https://github.com/binary-com/deriv-app/assets/119863957/7d11d65b-eb46-490f-a9c0-2ed342f45ee6
=> [WALL] [Fix] Rostislav / WALL-3267 / Withdrawal form layout fix in mobile

package-lock.json, packages/account-v2/package.json
1. Added twMerge in accounts-v2 to replace qtMerge
=> thisyahlen/chore: add twmerge to accounts-v2

packages/account-v2/src/App.tsx, packages/account-v2/src/components/Dropzone/Dropzone.tsx, packages/account-v2/src/modules/IDVForm/__tests__/idv-form.spec.tsx, packages/account-v2/src/modules/IDVForm/idv-form.tsx, packages/account-v2/src/router/components/route-links/route-links.tsx, packages/account-v2/src/router/constants/routes-config.tsx, packages/account-v2/src/utils/idv-form-utils.ts
Improved code coverage of IDV form by added testcases to test the component based on the props provided
=> [account-v2]/likhith/[COJ-598]/added testcases for IDV

packages/account-v2/src/router/components/dummy-route/dummy-route.tsx, packages/account-v2/src/router/components/route-links/route-links.tsx, packages/account-v2/tailwind.config.ts
1. Remove quill base styles in router folder
=> thisyahlen/chore: remove quill base styles in router folder

packages/bot-web-ui/src/stores/__tests__/blockly-store.spec.ts
=> [BOT] Maryia/BOT-1033/test: blockly-store.ts

packages/wallets/src/features/cashier/modules/CashierLocked/CashierLocked.tsx
https://github.com/binary-com/deriv-app/assets/142860499/919ee6e9-561b-4f19-8c00-f80768c2e4c2
=> [WALL] Lubega / WALL-3505 / Lock cashier only for non virtual accounts

packages/core/src/Utils/Datadog/index.ts
This is to remove extra space on the regex.
=> Ako/ remove extra space on dd regex

packages/tradershub/src/components/CurrencySwitcher/CurrencySwitcher.tsx, packages/tradershub/src/modals/AddOrManageAccount/AddOrManageAccount.tsx, packages/tradershub/src/modals/AddOrManageAccount/CurrenciesForm.tsx, packages/tradershub/src/modals/AddOrManageAccount/index.ts, packages/tradershub/src/modals/index.ts, packages/tradershub/src/screens/CurrencySelector/CurrencyCard.tsx
Add or manage account modal 
- Fiat currencies
- Crypto currencies 
https://github.com/binary-com/deriv-app/assets/129842155/e1f5fc4a-99fa-4cb0-a314-700abd46fe0a
https://github.com/binary-com/deriv-app/assets/129842155/351cd6e1-3068-4107-8245-4e275c8be446
=> [TRAH-2282] shahzaib / add or manage account modal and screens

packages/account-v2/src/components/CountrySelector/CountrySelector.tsx, packages/account-v2/src/components/CountrySelector/__test__/CountrySelector.spec.tsx
Added Country Selector component into account v2 package
=> [UPM-783] Suisin/chore: add country selector into account-v2 package

.github/actions/invalidate_npm_cache/action.yml, .github/actions/npm_install_from_cache/action.yml
This is to generate the cache file on each on any package.json file.
=> Ako/ generate cache based on the package.json file

package-lock.json, packages/cfd/package.json, packages/core/package.json, packages/p2p-v2/package.json, packages/p2p/package.json, packages/trader/package.json, packages/tradershub/package.json, packages/tradershub/src/components/OptionsAndMultipliersSection/OptionsAndMultipliersContent/OptionsAndMultipliersContent.tsx, packages/tradershub/src/components/StaticLink/StaticLink.tsx, packages/tradershub/src/constants/constants.tsx, packages/tradershub/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx, packages/tradershub/src/features/cfd/flows/CTrader/AvailableCTraderAccountsList/AvailableCTraderAccountsList.tsx, packages/tradershub/src/features/cfd/flows/MT5/MT5AccountIcon.tsx, packages/tradershub/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.tsx, packages/tradershub/src/features/cfd/flows/OtherCFDs/Dxtrade/AvailableDxtradeAccountsList/AvailableDxtradeAccountsList.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionTncSection/JurisdictionTncSection.tsx, packages/tradershub/src/helpers/urls.ts
1. Used latest for deriv-com/utils in package json
2. Replaced getStaticUrl to getDerivStaticURL
=> thisyahlen/chore: deriv-com/utils

packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-checkbox.tsx
Reverts binary-com/deriv-app#13878
=> Revert "thisyahlen/TRAH-2997/chore: fix terms and conditions link to deriv com when user changes language"

packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
Fixed condition which in certain circumstances was setting index to -1 and thus breaking tests.
=> [WALL-3520] wojtek/feat: fixed missing condition

packages/account-v2/src/App.tsx, packages/account-v2/src/components/AppOverlay/AppOverlay.tsx, packages/account-v2/src/components/AppOverlay/index.ts, packages/account-v2/src/router/components/route-links/route-links.tsx
1. Add AppOverlay and wrap the components in it
https://github.com/binary-com/deriv-app/assets/104053934/6a4c0dfe-c95c-456b-85a5-1ee3edc61df4
=> thisyahlen/chore: add app overlay to match production in account-v2

packages/wallets/src/components/DatePicker/__tests__/DatePicker.spec.tsx
=> [WALL-3525] wojtek/feat/unskipped previously skipped test

nx.json, package-lock.json, package.json
Use nx local cache as the cloud is disabled.
=> Ako/ use local cache instead of cloud

.github/workflows/remote_config_pr.yml
This is to use the Production environment for the backup file download
=> Ako/ use production env to download app config file

packages/shared/src/utils/date/date-time.ts
Update initMoment to exclude arabic translation happening in calenders and date & time.
=> Suisin/chore: update initMoment to exclude arabic language translation

packages/account/src/Components/currency-selector/__tests__/currency-selector.spec.tsx, packages/account/src/Components/currency-selector/__tests__/radio-button-group.spec.tsx, packages/account/src/Components/currency-selector/currency-selector.tsx, packages/account/src/Components/currency-selector/radio-button-group.tsx, packages/account/src/Configs/currency-selector-config.ts, packages/components/stories/icon/icons.js, packages/core/src/App/Containers/RealAccountSignup/set-currency.jsx, packages/core/src/sass/account-wizard.scss, packages/shared/src/utils/currency/currency.ts
- Change information for Fiat currencies 
- Change title in the select account currency
Before:
After:
=> Mahdiyeh/TRH- 2675/ chore: change information content for fiat in Add account

packages/api-v2/src/AuthProvider.tsx, packages/wallets/src/components/DatePicker/__tests__/DatePicker.spec.tsx, packages/wallets/src/features/cashier/components/WalletActionModal/WalletActionModal.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/TransactionsPendingRow.scss, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/TransactionsPendingRow.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/__tests__/TransactionsPendingRow.spec.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/components/TransactionsPendingRowField/TransactionsPendingRowField.tsx, packages/wallets/src/features/cashier/modules/Transactions/components/TransactionsPendingRow/components/TransactionsPendingRowField/__tests__/TransactionsPendingRowField.spec.tsx
=> [WALL] Lubega / WALL-2984 / TransactionsPendingRow unit test and fixes

packages/core/src/App/AppContent.tsx, packages/core/src/App/app.jsx
- Add firebase remote config support for enabling/disabling growthbook
=> Amir/feq 1759/remote config growthbook

packages/wallets/src/components/SkeletonLoader/WalletsCarouselLoader/WalletsCarouselLoader.scss, packages/wallets/src/components/WalletCard/WalletCard.scss, packages/wallets/src/components/WalletCard/WalletCard.tsx, packages/wallets/src/components/WalletCard/__tests__/WalletCard.spec.tsx, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.scss, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx
https://github.com/binary-com/deriv-app/assets/142860499/a7f1f6d9-ad16-461c-8dc4-62deec91d51c
=> [WALL] Lubega / WALL-3532 / Wallets carousel responsive design changes

packages/bot-web-ui/src/pages/chart/chart.tsx, packages/bot-web-ui/src/pages/main/main.scss
RTL supports for Deriv Bot
- Add renderFields_ function to Blockly to render RTL images in the proper order
- Update the cleanup function to support RTL changes once the workspace is sorted
- Add mixin in SCSS to check RTL
- Update styles for the drawer to work properly
- Fix the trashcan to render properly in RTL
- Changed multiple CSS to support RTL and LTR at the same time
- Chart functionality for RTL
=> [BOT] chore: add chart functionality

package-lock.json, packages/account-v2/package.json, packages/cashier-v2/package.json, packages/p2p-v2/package.json, packages/tradershub/package.json
Update deriv-com/ui version to fix text-size
=> Thisyahlen/chore: update deriv-com/ui version to fix text-size

packages/appstore/src/components/containers/trading-app-card.tsx
=> [TRAH] Mitra/ TRAH-2645 / add unique data test id for card containers

packages/tradershub/src/hooks/useRegulationFlags.ts
=> Thisyahlen/chore: fix account type

packages/bot-web-ui/webpack.config.js
- Added the `REMOTE_CONFIG_URL` environment variable to webpack config
=> [FEQ] Jim/WEBREL-2572/fix remote config url is not set dbot

packages/tradershub/src/components/CurrencySwitcher/CurrencySwitcher.tsx, packages/tradershub/src/components/DemoRealSwitcher/DemoRealSwitcher.tsx, packages/tradershub/src/components/GetADerivAccountBanner/GetADerivAccountDialog.tsx, packages/tradershub/src/components/ProgressBar/ProgressBar.classnames.ts, packages/tradershub/src/components/SentEmailContent/SentEmailContent.tsx, packages/tradershub/src/constants/constants.tsx, packages/tradershub/src/features/cfd/flows/CTrader/AddedCTraderAccountsList/AddedCTraderAccountsList.tsx, packages/tradershub/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/tradershub/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.tsx, packages/tradershub/src/features/cfd/modals/ButtonGroups/AddAccountButtonsGroup.tsx, packages/tradershub/src/features/cfd/modals/ButtonGroups/SuccessButtonGroup.tsx, packages/tradershub/src/features/cfd/modals/CTraderSuccessModal/CTraderSuccessModal.tsx, packages/tradershub/src/features/cfd/screens/ChangePassword/TradingPlatformChangePasswordScreens.tsx, packages/tradershub/src/features/cfd/screens/EnterPassword/EnterPassword.tsx, packages/tradershub/src/flows/RealAccountCreation/WizardScreenActions/WizardScreenActions.tsx, packages/tradershub/src/modals/ExitConfirmationDialog/ExitConfirmationDialog.tsx
1. Add color to outlined variant
=> Thisyahlen/TRAH-3036/chore: add color to button for outlined variant

packages/cfd/src/Containers/cfd-password-change.tsx, packages/cfd/src/Containers/mt5-migration-modal/mt5-migration-back-side-content.tsx
1. Removed password validation strength bar from current password field
2. remove password validation strength bar from mt5 migration modal
3. "An lowercase letter" needs to be updated to "A lowercase letter"
=> [CFDS] shontzu/CFDS-3323/Improvement-card-for-MT5-password-policy-changes

packages/bot-web-ui/src/pages/dashboard/load-bot-preview/__tests__/save-modal.spec.tsx, packages/bot-web-ui/src/pages/dashboard/load-bot-preview/save-modal.tsx, packages/bot-web-ui/src/pages/tutorials/quick-strategy-content/index.scss, packages/bot-web-ui/src/pages/tutorials/quick-strategy-content/quick-strategy-guides-details.tsx
- Added quick strategy guide title on the strategy detail page
- Updated the save strategy button text to save
=> [BOT] Farabi/bot-1195/deriv bot ui bugs

packages/bot-web-ui/src/utils/datadog-logs.ts, packages/core/src/Utils/Datadog/index.ts
=> [FEQ] Jim/WEBREL-2574/fix prettier

packages/tradershub/src/hooks/useCurrencies.ts
Fix a type error in `useCurrencies` hook
=> [TRAH] shahzaib / use currencies typo

package-lock.json, packages/account-v2/package.json, packages/cashier-v2/package.json, packages/p2p-v2/package.json, packages/tradershub/package.json
- Updated deriv-com/ui package as white colour variant was removed previously for Text component
=> Ameerul/Chore: Updated deriv-com/ui package to fix white text 

packages/p2p/src/components/modal-manager/modals/email-link-blocked-modal/__tests__/email-link-blocked-modal.spec.tsx, packages/p2p/src/components/modal-manager/modals/email-link-blocked-modal/email-link-blocked-modal.tsx, packages/p2p/src/components/modal-manager/modals/email-link-verified-modal/__tests__/email-link-verified-modal.spec.tsx, packages/p2p/src/components/modal-manager/modals/email-link-verified-modal/email-link-verified-modal.scss, packages/p2p/src/components/modal-manager/modals/email-link-verified-modal/email-link-verified-modal.tsx, packages/p2p/src/components/modal-manager/modals/email-verification-modal/__tests__/email-verification-modal.spec.tsx, packages/p2p/src/components/modal-manager/modals/email-verification-modal/email-verification-modal.scss, packages/p2p/src/components/modal-manager/modals/email-verification-modal/email-verification-modal.tsx, packages/p2p/src/components/modal-manager/modals/invalid-verification-link-modal/__tests__/invalid-verification-link-modal.spec.tsx, packages/p2p/src/components/modal-manager/modals/invalid-verification-link-modal/invalid-verification-link-modal.tsx, packages/p2p/src/components/order-details/order-details.jsx, packages/p2p/src/stores/order-store.js
- Changed content in EmailVerificationModal and EmailLinkVerifiedModal to match with current design
=> [P2PS] / Ameerul / P2PS-2099 Improvise 2FA Email Verification Messages when Completing Orders

packages/wallets/component-tests/wallets-carousel-content.spec.tsx, packages/wallets/src/components/OptionsAndMultipliersListing/OptionsAndMultipliersListing.tsx, packages/wallets/src/components/WalletCard/WalletCard.scss, packages/wallets/src/components/WalletCard/WalletCard.tsx, packages/wallets/src/components/WalletCard/__tests__/WalletCard.spec.tsx, packages/wallets/src/components/WalletsCarousel/WalletsCarousel.scss, packages/wallets/src/components/WalletsCarousel/WalletsCarousel.tsx, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.scss, packages/wallets/src/components/WalletsCarouselContent/WalletsCarouselContent.tsx, packages/wallets/src/components/WalletsCarouselHeader/WalletsCarouselHeader.scss, packages/wallets/src/components/WalletsCarouselHeader/WalletsCarouselHeader.tsx, packages/wallets/src/components/WalletsPrimaryTabs/WalletsPrimaryTabList.scss, packages/wallets/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.scss, packages/wallets/src/features/cfd/flows/MT5/AvailableMT5AccountsList/AvailableMT5AccountsList.tsx
https://github.com/binary-com/deriv-app/assets/142860499/4a7d6d6a-1c36-4a43-9bc5-65ed992bb1ef
=> [WALL] Lubega / WALL-3544 / Wallets carousel vertical and horizontal animation

packages/trader/src/Modules/Trading/Containers/trade-chart.tsx, packages/trader/src/Stores/Modules/Trading/trade-store.ts
- To prevent blank screen appearing instead of chart, which is happening in production deployment and in some test links.
=> [DTRA] Maryia/DTRA-983/fix: prevent blank screen shown instead of chart

packages/cfd/src/Containers/jurisdiction-modal/jurisdiction-modal-checkbox.tsx
1. fix terms and conditon link when language is changed
https://github.com/binary-com/deriv-app/assets/104053934/0048251b-ae2b-4d45-8924-ac4fafcd2699
=> thisyahlen/TRAH-2997/chore: fix terms and conditon link when language is changed

package-lock.json, package.json, packages/appstore/package.json, packages/cfd/package.json, packages/core/package.json, packages/hooks/package.json, packages/hooks/src/useGrowthbookFeatureFlag.ts, packages/reports/package.json, packages/trader/package.json
- update analytics package to version 1.4.13, which includes a fix for a console error 'Uncaught TypeError: Cannot convert undefined or null to object at Function.keys (<anonymous>)'
=> [DTRA] Maryia/WEBREL-2589/build: update analytics package to 1.4.13

packages/components/src/components/autocomplete/autocomplete.tsx
- Add sort function to the Autocomplete component based on the input
**Test Link:**
https://github.com/binary-com/deriv-app/assets/82078941/5a71f9cb-51d5-4c31-ac83-7f5e6b915950
**Production:**
https://github.com/binary-com/deriv-app/assets/82078941/872796d4-0352-4503-9745-61c5f52f01f3
=> Mahdiyeh/2981/ Add sorting  function to autocomplete component

packages/account/src/Components/address-details/address-details.tsx, packages/account/src/Components/inline-note-with-icon/inline-note-with-icon.tsx, packages/account/src/Configs/address-details-config.ts, packages/components/src/components/select-native/select-native.tsx, packages/core/src/App/Containers/RealAccountSignup/account-wizard.jsx
- Fix the disabling issue for not submitted values
- 
https://github.com/binary-com/deriv-app/assets/82078941/d15178fc-32ff-44ae-8a75-f788be110206
=> [TRAH- 3054]/Mahdiyeh/fix: disabling not submitted values

packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx, packages/account/src/Sections/Profile/PersonalDetails/validation.ts
Reverts binary-com/deriv-app#13701
=> Revert "[UPM-670] Suisin/chore: fixed personal details email property issue"

packages/tradershub/src/features/cfd/modals/MT5AccountTypeModal/MT5AccountTypeModal.tsx, packages/tradershub/src/features/cfd/screens/Jurisdiction/JurisdictionScreen.tsx, packages/tradershub/src/features/cfd/screens/MT5AccountType/MT5AccountType.tsx
1.  Remove selected jurisdiction whenever modal is closed
https://github.com/binary-com/deriv-app/assets/104053934/1226fc6f-ed5f-4349-a428-69057670e1be
=> thisyahlen/chore: remove selected jurisdiction whenever modal is closed

packages/cfd/src/Containers/mt5-migration-modal/mt5-migration-front-side-content.tsx
Fixing terms and conditions link fix for localized languages
=> [COJ]/Amina/TRAH_3075/Terms and conditions link fix

packages/reports/src/sass/app/_common/layout/trader-layouts.scss, packages/trader/src/App/Components/Elements/ContractDrawer/contract-drawer.tsx, packages/trader/src/Modules/SmartChart/Components/top-widgets.tsx, packages/trader/src/sass/app/_common/layout/trader-layouts.scss
- Removed inline style for TopWidgets component. Previously, width was 100% and because of it container overlapped handle button, making it unclickable.
- Improved calculations of translateY for contract details and audit: included margin to the formula. Previously it wasn't take in consider and containers were lifted up too much. 
https://github.com/binary-com/deriv-app/assets/121025168/85e0b432-a76d-462a-8b84-051fc69b73d4
=> [DTRA] / Kate / DTRA-946 / [Responsive] - Collapsible button and contract audit issues

packages/tradershub/src/features/cfd/components/MT5PlatformsList/MT5PlatformsList.tsx, packages/tradershub/src/features/cfd/components/OtherCFDPlatformsList/OtherCFDPlatformsList.tsx
1. Fix infinite load and rate limit for mt5 and dxtrade
=> Thisyahlen/chore: remove invalidate which cause infinite load and rate limit

packages/p2p-v2/src/components/Modals/EmailLinkVerifiedModal/EmailLinkVerifiedModal.scss, packages/p2p-v2/src/components/Modals/EmailLinkVerifiedModal/EmailLinkVerifiedModal.tsx, packages/p2p-v2/src/components/Modals/EmailLinkVerifiedModal/__tests__/EmailLinkVerifiedModal.spec.tsx, packages/p2p-v2/src/components/Modals/EmailLinkVerifiedModal/index.ts, packages/p2p-v2/src/routes/AppContent/index.tsx
- Added Order Confirmation modal
- Added test cases
=> [FEQ] / Ameerul / FEQ-1717 Create the order confirmation modal

packages/tradershub/src/hooks/__tests__/useQueryParams.spec.ts
=> Thisyahlen/TRAH-3082/test: unit test for useQueryParams

packages/tradershub/src/components/RegulationSwitcher/RegulationSwitcherMobile.tsx, packages/tradershub/src/components/RegulationTableContent/RegulationTableContent.tsx, packages/tradershub/src/hooks/useAccountSwitcher.ts
1. Fix regulation for diel countries in demo where it stays in EU 
2. Minor border radius fix in regulation switcher mobile
3. Text align center regulation title in regulation modal
=> Thisyahlen/chore: fix border radius for regulation switcher mobile and regulation fix for diel countries

packages/bot-web-ui/src/pages/bot-builder/quick-strategy/selects/trade-type.tsx
Fix quick strategy trade type dropdown
https://app.clickup.com/t/20696747/BOT-1449
=> [BOT]Rupato/BOT-1449/fix: for qs trade type field

packages/tradershub/jest.config.js
1. Setup jest config path aliases to recognise the paths
=> Thisyahlen/chore: setup path for jest config for aliases

packages/trader/src/Modules/Contract/Containers/__tests__/contract-replay.spec.tsx, packages/trader/src/Modules/Contract/Containers/__tests__/contract.spec.tsx, packages/trader/src/Modules/Contract/Containers/__tests__/replay-chart.spec.tsx, packages/trader/src/Modules/Contract/Containers/contract-replay.tsx, packages/trader/src/Modules/Contract/Containers/contract.tsx
This feature involves expanding test coverage to include contract containers, ensuring comprehensive testing across the platform. Previously, test coverage for contract containers might have been limited, potentially leaving areas susceptible to undetected bugs or issues. With this update, additional test cases are implemented to thoroughly assess the functionality, behavior, and performance of contract containers in various scenarios. By increasing test coverage for contract containers, potential defects or regressions can be identified and addressed early in the development cycle, enhancing overall product quality and reliability. This enhancement strengthens the robustness of the platform and improves confidence in its stability and performance.
=> Akmal / feat: add contract containers test coverage

packages/tradershub/src/hooks/__tests__/useAccountSwitcher.spec.ts, packages/tradershub/src/utils/validations/validations.ts
1. Add unit test to useAccountSwitcher
=> Thisyahlen/TRAH-3084/test: add unit test for useAccountSwitcher

packages/tradershub/src/hooks/__tests__/useRegulationSwitcher.spec.ts
1. Unit test for useRegulationSwitcher
=> Thisyahlen/TRAH-3085/test: unit test for useRegulationSwitcher

packages/tradershub/src/hooks/__tests__/useAccountSwitcher.spec.ts, packages/tradershub/src/hooks/__tests__/useRegulationFlags.spec.ts
1. Unit test for useRegulationFlags
=> Thisyahlen/TRAH-3086/test: unit test for useRegulationFlags

packages/tradershub/src/hooks/__tests__/useCurrencies.spec.ts
Unit test cases for `useCurrencies` hook
=> [TRAH-3088] shahzaib / unit test case for useCurrencies

packages/api-v2/src/hooks/useCFDCompareAccounts.tsx
1. Add filtering condition for EU to only show maltainvest content
=> Thisyahlen/TRAH-3078/fix: filtering condition for eu demo

packages/tradershub/src/hooks/__tests__/useTotalAssets.spec.ts
1. Unit test for useTotalAssets
=> Thisyahlen/TRAH-3091/chore: unit test for useTotalAssets

packages/trader/src/Modules/Trading/Containers/trade-chart.tsx
=> [DTRA] henry/dtra-781/fix: remove isDesktop condition

packages/tradershub/src/hooks/__tests__/useCFDAssets.spec.ts
1. Create unit test for useCFDAssets
=> Thisyahlen/TRAH-3094/test: unit test for useCFDAssets

packages/trader/src/Modules/Contract/Components/LastDigitPrediction/last-digit-prediction.tsx
This fix addresses an issue related to the behavior of zero in digit contracts, ensuring correct functionality and user experience. Previously, there might have been inconsistencies or errors in the handling of zero values within digit contracts, potentially leading to unexpected behavior or incorrect outcomes. With this update, the behavior of zero in digit contracts is corrected to align with expected standards and user expectations. Users can now rely on consistent and accurate behavior when interacting with zero values in digit contracts, improving the reliability and usability of the platform. This fix resolves potential confusion or errors related to zero values, enhancing the overall quality and integrity of digit contract functionality.
=> Akmal / fix: digit contracts zero behavior

packages/trader/src/App/__tests__/app.spec.tsx, packages/trader/src/App/__tests__/init-store.spec.ts
Test coverage: app.tsx + init-store.ts in Trader package
=> [DTRA] Farhan/WEBREL-56/tTest coverage: app.tsx + init-store.ts in Trader package

packages/tradershub/src/hooks/__tests__/useDisableFiatCurrencies.spec.ts
- Test case for useDisableFiatCurrencies hook
=> [TRAH-3090] shahzaib / test case for useDisableFiatCurrencies hook

packages/tradershub/src/hooks/__tests__/usePlatformAssets.spec.ts
1. Unit test for usePlatformAssets
=> Thisyahlen/TRAH-3095/test: unit test for usePlatformAssets

packages/account/src/Sections/Profile/PersonalDetails/personal-details-form.tsx, packages/bot-web-ui/src/components/transaction-details/desktop-transaction-table.tsx, packages/bot-web-ui/src/components/transaction-details/mobile-transaction-card.tsx, packages/components/package.json, packages/hooks/src/useIsRtl.ts, packages/trader/src/sass/app/_common/components/contract-type-dialog.scss, packages/trader/src/sass/app/modules/trading.scss, packages/translations/src/i18next/i18next.ts
Edit feature branch code based on comments given
=> [UPM] Suisin/fix suggested codes

.github/workflows/generate_app_id.yml, .github/workflows/lighthouse.yml, .github/workflows/smoketests.yml
- Updated `SHA` to the approved one.
=> [FEQ] Jim/FEQ-1958/update sha for marocchino-sticky-pull-request-comment

package-lock.json, packages/bot-web-ui/package.json, packages/core/package.json, packages/trader/package.json
=> Bala/update charts version 2.1.8

package-lock.json, packages/cashier-v2/package.json, packages/cfd/package.json, packages/core/package.json, packages/p2p-v2/package.json, packages/p2p/package.json, packages/trader/package.json, packages/tradershub/package.json
update `@deriv-com/utils` from using "latest" to "^0.0.11"
=> chore: update @deriv-com/utils from latest to ^0.0.11

packages/bot-web-ui/src/pages/dashboard/stop-bot-modal-content.tsx, packages/bot-web-ui/src/pages/tutorials/dbot-tours/tour-content.tsx
Fixed arabic language text on popup and fix for tour
click up card : https://app.clickup.com/t/20696747/BOT-1500
=> [BOT-1500]/Rupato/fix: arabic language on popup and tour

packages/account/src/Components/financial-details/__tests__/financial-details.spec.tsx, packages/account/src/Components/forms/personal-details-form.jsx, packages/account/src/Configs/__test__/financial-details-config.spec.ts, packages/account/src/Configs/financial-details-config.ts, packages/account/src/Sections/Assessment/FinancialAssessment/__tests__/financial-assessment.spec.tsx, packages/account/src/Sections/Assessment/FinancialAssessment/financial-assessment.tsx, packages/core/src/App/Containers/RealAccountSignup/account-wizard.jsx, packages/shared/src/utils/validation/__tests__/form-validation.spec.ts, packages/shared/src/utils/validation/form-validations.ts
When user selects self-employed on employment_status, Occupation field is to be displayed without Unemployment as a value
=> [COJ]/likhith/KYC-1737/feat: incorporated changes to display occupation field

packages/account-v2/src/router/components/DummyRoute/DummyRoute.tsx, packages/account-v2/src/router/components/RouteLinks/RouteLinks.tsx
Fix the type error in router component in RouteLinks
=> account-v2 / fix: router component type in accounts v2

packages/tradershub/src/components/EUDisclaimerMessage/__tests__/EUDisclaimerMessage.spec.tsx
Unit test for the disclaimer to check on the content and failing once the content changes.
=> [TRAH]/Mitra/TRAH-2774/Unit test for disclaimer component

packages/wallets/src/components/Base/ModalStepWrapper/ModalStepWrapper.scss, packages/wallets/src/components/Base/ModalWrapper/ModalWrapper.scss, packages/wallets/src/styles/animations.scss
- Added modal animation for desktop similar to production.
https://github.com/binary-com/deriv-app/assets/103104395/d3ea144a-d9fd-450a-9773-66db0160cf73
=> [WALL] Aizad/Adding Animation to Modal for Desktop view

packages/wallets/src/hooks/useInputATMFormatter.ts
https://github.com/binary-com/deriv-app/assets/119863957/1e32fc9d-67f8-4da1-bfd0-6d83278f3921
=> [WALL] Rostislav / WALL-3514 / ATM input field pasting crypto values

packages/reports/src/Components/Form/CompositeCalendar/__tests__/two-month-picker.spec.tsx
=> [Dtra]/Ahmad/Report testcase fail

.github/workflows/generate_app_id.yml, .github/workflows/lighthouse.yml, .github/workflows/smoketests.yml
This PR is to update Vercel Preview URL.
=> Matin/ Update Vercel Preview URL

packages/api-v2/src/remote_config.json, packages/api/src/remote_config.json, packages/core/src/App/AppContent.tsx
Added dependancy to useEffect to trigger the logic inside 'if' statement
=> [UPM-880]/evgeniy/not able to connect to analytics

packages/trader/src/Modules/Trading/Components/Form/ContractType/ContractTypeInfo/contract-type-glossary.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/ContractTypeInfo/contract-type-info.tsx, packages/trader/src/Modules/Trading/Components/Form/ContractType/__tests__/contract-type-glossary.spec.tsx
Reverts binary-com/deriv-app#13865
=> "Akmal / feat: update entry spot description""

packages/wallets/src/features/cashier/modules/DepositFiat/DepositFiat.tsx, packages/wallets/src/features/cashier/modules/DepositFiat/__tests__/DepositFiat.spec.tsx
Bug:
https://github.com/binary-com/deriv-app/assets/142860499/788d66b8-a118-4b17-ba5b-55da9d0bea0c
Fix:
https://github.com/binary-com/deriv-app/assets/142860499/6f5ae0a3-e48f-4e89-9cb4-5016050d114a
=> [WALL] Lubega / WALL-3634 / Fiat deposit blank screen fix

packages/core/src/Stores/client-store.js
added try catch block for handling the scenario, when passkeys are not available on BE side
=> [UPM-887]/evgeniy/remove error cannot read properties of undefined (reading 'length')

packages/components/src/components/input-field/input-field.scss, packages/core/build/loaders-config.js
Try adding options in sass loader and revert the previous change
=> Suisin/chore: update sass loader package

packages/components/src/components/popover/popover.scss, packages/trader/src/sass/app/_common/components/purchase-button.scss, packages/trader/src/sass/app/modules/trading.scss
Fix alignment issue based on Proof of Read
=> Suisin/chore: fix alignment issue based on Proof of Read

packages/trader/src/sass/app/_common/components/contract-type-info.scss, packages/trader/src/sass/app/_common/components/purchase-button.scss, packages/trader/src/sass/app/modules/trading.scss
Fix alignment for learn about trade type descriptions and minor fix for purchase button
=> Suisin/chore: update alignment for learn about trade type descriptions

packages/wallets/src/features/cfd/modals/MT5PasswordModal/MT5PasswordModal.tsx
- Fix showing wrong footer buttons for Enter MT5 Password Modal.
=> Aizad/ WALL-3700 / Fix Footer Buttons for Enter MT5 Password Modal

packages/account/src/Sections/Verification/ProofOfIdentity/proof-of-identity-container.jsx
Fixing idv rejected error when overall status of POI is verified
=> [COJ]/Amina/COJ_682/fix: poi for authenticated scans

packages/cashier-v2/src/flows/PaymentAgent/PaymentAgent.module.scss, packages/cashier-v2/src/flows/PaymentAgent/PaymentAgent.tsx, packages/cashier-v2/src/flows/PaymentAgent/__tests__/PaymentAgent.spec.tsx, packages/cashier-v2/src/flows/PaymentAgent/components/PaymentAgentWithdrawalContainer/PaymentAgentWithdrawalContainer.tsx, packages/cashier-v2/src/flows/PaymentAgent/components/PaymentAgentWithdrawalContainer/__tests__/PaymentAgentWithdrawalContainer.spec.tsx, packages/cashier-v2/src/flows/PaymentAgent/components/PaymentAgentWithdrawalContainer/index.ts, packages/cashier-v2/src/flows/PaymentAgent/components/index.ts, packages/cashier-v2/src/lib/PaymentAgent/PaymentAgentWithdrawal/provider/PaymentAgentWithdrawalProvider.tsx, packages/cashier-v2/src/lib/PaymentAgent/PaymentAgentWithdrawal/provider/__tests__/PaymentAgentWithdrawalProvider.spec.tsx
Implement Payment Agent - Flow
https://github.com/binary-com/deriv-app/assets/103181646/e8534092-a213-4047-9327-7a98cccd112d
https://github.com/binary-com/deriv-app/assets/103181646/012adfff-db83-4cc4-a298-fcd0b2e63c9b
=> [Cashier-V2] george / FEQ-2031 / Implement Payment Agent - Flow

packages/api-v2/src/hooks/p2p/entity/order/p2p-order/useOrderInfo.ts, packages/api-v2/types.ts, packages/p2p-v2/src/pages/orders/screens/OrderDetails/OrderDetails.tsx, packages/p2p-v2/src/pages/orders/screens/OrderDetails/__tests__/OrderDetails.spec.tsx, packages/p2p-v2/src/pages/orders/screens/OrdersChatSection/OrdersChatSection.tsx
- Replaced useQuery with useSubscription 
- exposed subscribe so components can subscribe to the endpoint
- refactored OrderDetails and ChatFooter to work with new subscribed data
https://github.com/binary-com/deriv-app/assets/103412909/c7896209-c9a6-485d-8ba0-9444c353b4b9
=> [FEQ] / Ameerul / FEQ-1968 Refactor order info hook

packages/api-v2/src/hooks/useCashierValidation.ts
=> [WALL] Lubega / WALL-3707 / System maintenance status check update

nx.json
- to skip nx cache temporarily
=> Maryia/build: skip nx cache temporarily

nx.json
- to disconnect from nx-cloud temporarily
=> Maryia/build: disconnect from nx-cloud temporarily

nx.json
=> Revert "Maryia/build: nx-cloud disabling attempts (#14505, #14510)"

.github/workflows/release_test.yml
https://github.com/binary-com/deriv-app/actions/workflows/test.yml - Build and test workflow works fine
In this PR, we remove the inputs to action/build to test this workflow
=> remove inputs to action/build

.github/workflows/release_staging.yml
Fix staging workflow with production as node_env
=> Bala/Fix staging workflow with production as node_env

packages/wallets/src/features/cfd/flows/MT5/AddedMT5AccountsList/AddedMT5AccountsList.tsx, packages/wallets/src/features/cfd/flows/OtherCFDs/Dxtrade/AddedDxtradeAccountsList/AddedDxtradeAccountsList.tsx
=> [WALL] [Fix] Rostislav / WALL-3734 / Align wallets added accounts numbers w/ Figma

package-lock.json, packages/bot-web-ui/package.json, packages/bot-web-ui/src/components/draggable/__tests__/draggable-utils.spec.tsx, packages/bot-web-ui/src/components/draggable/__tests__/draggable.spec.tsx, packages/bot-web-ui/src/components/draggable/draggable-resize-wrapper.tsx, packages/bot-web-ui/src/components/draggable/draggable-utils.ts, packages/bot-web-ui/src/components/draggable/draggable.scss, packages/bot-web-ui/src/components/draggable/draggable.tsx, packages/bot-web-ui/src/components/trading-view-chart/__tests__/trading-view-modal.spec.tsx, packages/bot-web-ui/src/components/trading-view-chart/trading-view-modal.tsx, packages/bot-web-ui/src/components/transaction-details/__tests__/transaction-details-desktop.spec.tsx, packages/bot-web-ui/src/components/transaction-details/transaction-details-desktop.scss, packages/bot-web-ui/src/components/transaction-details/transaction-details-desktop.tsx, packages/bot-web-ui/src/pages/chart/chart-modal/__tests__/chart-modal-desktop.spec.tsx, packages/bot-web-ui/src/pages/chart/chart-modal/chart-modal-desktop.tsx, packages/bot-web-ui/src/pages/chart/chart-modal/chart-modal.scss, packages/bot-web-ui/src/pages/main/main.scss
- Remove react-rnd
- Created custom Draggable and Resizable component
- Replaced react-rnd from Chart, Trading view and transaction details modal
- Updated test cases for all components
- Updated package-lock file
=> [BOT] feat: replace react-rnd modal with custom draggable modal

packages/bot-web-ui/src/pages/main/main.scss
A style was missing from the chart. Added it back to main.scss file.
=> [BOT] fix: unable to load dbot chart

packages/cashier-v2/src/containers/Cashier/Cashier.tsx, packages/cashier-v2/src/flows/FiatOnRamp/FiatOnRamp.tsx, packages/cashier-v2/src/flows/FiatOnRamp/__tests__/FiatOnRamp.spec.tsx, packages/cashier-v2/src/flows/FiatOnRamp/index.ts, packages/cashier-v2/src/flows/index.ts, packages/cashier-v2/src/lib/FiatOnRamp/FiatOnRamp.module.scss, packages/cashier-v2/src/lib/FiatOnRamp/FiatOnRamp.tsx, packages/cashier-v2/src/lib/FiatOnRamp/__tests__/FiatOnRamp.spec.tsx, packages/cashier-v2/src/lib/FiatOnRamp/components/DisclaimerDialog/__tests__/DisclaimerDialog.spec.tsx, packages/cashier-v2/src/lib/FiatOnRamp/components/ProviderCard/ProviderCard.tsx, packages/cashier-v2/src/lib/FiatOnRamp/components/ProviderCard/__tests__/ProviderCard.spec.tsx, packages/cashier-v2/src/lib/FiatOnRamp/index.ts, packages/cashier-v2/src/lib/index.ts, packages/cashier-v2/src/routes/Router.tsx
- wrap FiatOnRamp components into the flow
- add tests
=> [Cashier-V2] george / FEQ-2046 / Wrap FiatOnRamp components into the flow

packages/wallets/scripts/update-translations.sh
Fix retry to break on max attempts
=> chore: fix retry to break on max attempts

.github/workflows/generate_and_push_deriv_api_types.yml
Updated the node version to support a range of `minor` and `patch` versions of node
=> [FEQ] Jim/FEQ-2073/update node version to support minor and patch version range

packages/core/src/Stores/client-store.js
=> Hirad/CFDs-3368/Fix: trackJS undefined platform
